
		.WORD 0
		.WORD _format_buf			; 1
		.WORD _dict70
		.WORD _dict71
		.WORD _dict72
		.WORD _dict73
		.WORD _dict74
		.WORD _dict75
		.WORD _dict76
		.WORD _dict77
		.WORD _dict78
		.WORD _dict79
		.WORD _dict7A
		.WORD _dict7B
		.WORD _dict7C
		.WORD _dict7D
		.WORD _dict7E
		.WORD _dict7F
		.WORD _dict80
		.WORD _dict81
		.WORD _dict82
		.WORD _dict83
		.WORD _dict84
		.WORD _dict85
		.WORD _dict86
		.WORD _dict87
		.WORD _dict88
		.WORD _dict89
		.WORD _dict8A
		.WORD _dict8B
		.WORD _dict8C
		.WORD _dict8D
		.WORD _dict8E
		.WORD _dict8F
		.WORD _dict90
		.WORD _dict91
		.WORD _dict92
		.WORD _dict93
		.WORD _dict94
		.WORD _dict95
		.WORD _dict96
		.WORD _dict97
		.WORD _dict98
		.WORD _dict99
		.WORD _dict9A
		.WORD _dict9B
		.WORD _dict9C
		.WORD _dict9D
		.WORD _dict9E
		.WORD _dict9F
		.WORD _dictA0
		.WORD _dictA1
		.WORD _dictA2
		.WORD _dictA3
		.WORD _dictA4
		.WORD _dictA5
		.WORD _dictA6
		.WORD _dictA7
		.WORD _dictA8
		.WORD _dictA9
		.WORD _dictAA
		.WORD _dictAB
		.WORD _dictAC
		.WORD _dictAD
		.WORD _dictAE
		.WORD _dictAF

_dict70:		.BYTE	_ddt,__,_quo,_eol			; ': "'			548
_dict71:		.BYTE	_K,_a,_n,_je,_d,_a,_eol		; 'Kanjeda'		246
_dict72:		.BYTE	_T,_je,_c,_u,_o,_eol		; 'Tjecuo'		182
_dict73:		.BYTE	_dot,_dot,_dot,_eol			; '...'			292
_dict74:		.BYTE	_K,_a,_j,_eol				; 'Kaj'			58
_dict75:		.BYTE	_K,_e,_j,_eol				; 'Kej'			103
_dict76:		.BYTE	_exc,_aof,_quo,_eol			; '!/aof"'		72	unused by now
_dict77:		.BYTE	_dot,_aof,_quo,_eol			; './aof"'		95	unused by now
_dict78:		.BYTE	_t,_mz,_eol					; 'tmz'			229
_dict79:		.BYTE	_s,_ja,_eol					; 'sja'			174
_dict7A:		.BYTE	_t,_o,_eol					; 'to'			521
_dict7B:		.BYTE	_n,_a,_eol					; 'na'			452
_dict7C:		.BYTE	_r,_a,_eol					; 'ra'			303
_dict7D:		.BYTE	_n,_o,_eol					; 'no'			289
_dict7E:		.BYTE	_p,_o,_eol					; 'po'			281
_dict7F:		.BYTE	_r,_o,_eol					; 'ro'			279
_dict80:		.BYTE	_k,_o,_eol					; 'ko'			252
_dict81:		.BYTE	_s,_t,_eol					; 'st'			267
_dict82:		.BYTE	_o,_e,_n,_n,_ji,_eol		; 'oennji'		62
_dict83:		.BYTE	_l,_i,_eol					; 'li' 			276
_dict84:		.BYTE	_n,_e,_eol					; 'ne' 			249
_dict85:		.BYTE	_t,_a,_eol					; 'ta' 			242
_dict86:		.BYTE	_t,_e,_eol					; 'te' 			239
_dict87:		.BYTE	_k,_a,_eol					; 'ka' 			233
_dict88:		.BYTE	_n,_i,_eol					; 'ni' 			223
_dict89:		.BYTE	_l,_a,_eol					; 'la' 			211
_dict8A:		.BYTE	_g,_o,_eol					; 'go' 			210
_dict8B:		.BYTE	_v,_o,_eol					; 'vo' 			209
_dict8C:		.BYTE	_r,_e,_eol					; 're' 			201
_dict8D:		.BYTE	_d,_a,_eol					; 'da' 			195
_dict8E:		.BYTE	__,_i,__,_eol				; ' i '			92
_dict8F:		.BYTE	_mz,__,_eol					; 'mz '			222
_dict90:		.BYTE	_d,_e,_eol					; 'de' 			178
_dict91:		.BYTE	_z,_a,_eol					; 'za' 			177
_dict92:		.BYTE	_r,_i,_eol					; 'ri' 			175
_dict93:		.BYTE	_l,_o,_eol					; 'lo' 			165
_dict94:		.BYTE	_v,_a,_eol					; 'va' 			158
_dict95:		.BYTE	_e,_n,_eol					; 'en' 			150
_dict96:		.BYTE	_m,_o,_eol					; 'mo' 			144
_dict97:		.BYTE	_que,_quo,_eol				; '?"' 			54
_dict98:		.BYTE	_m,_e,_eol					; 'me' 			141
_dict99:		.BYTE	_exc,_quo,_eol				; '!"'			144
_dict9A:		.BYTE	_col,__,_eol				; ', '			412
_dict9B:		.BYTE	_ja,__,_eol					; 'ja '			182
_dict9C:		.BYTE	__,_v,_eol					; ' v'			282
_dict9D:		.BYTE	__,_s,_eol					; ' s'			329
_dict9E:		.BYTE	__,_p,_eol					; ' p'			155
_dict9F:		.BYTE	__,_b,_eol					; ' b' 			151
_dictA0:		.BYTE	_v,_e,_eol					; 've' 			139
_dictA1:		.BYTE	_t,_i,_eol					; 'ti' 			138
_dictA2:		.BYTE	_k,_i,_eol					; 'ki' 			134
_dictA3:		.BYTE	_r,_u,_eol					; 'ru' 			126
_dictA4:		.BYTE	_l,__,_eol					; 'l '			128
_dictA5:		.BYTE	_e,__,_eol					; 'e '			127
_dictA6:		.BYTE	_d,_i,_eol					; 'di'			104
_dictA7:		.BYTE	_eol
_dictA8:		.BYTE	_eol
_dictA9:		.BYTE	_eol
_dictAA:		.BYTE	_eol
_dictAB:		.BYTE	_eol
_dictAC:		.BYTE	_eol
_dictAD:		.BYTE	_eol
_dictAE:		.BYTE	_eol
_dictAF:		.BYTE	_eol

;_dictFB:		; used as RAM offset
;_dictFC:		; spare
;_dictFD:		; spare