
		SECTION_START	F5

		MSG_START	_scene5_msg_lib
		MSG_IDX	_sc5_msg00
		MSG_IDX	_sc5_msg01
		MSG_IDX	_sc5_msg02
		MSG_IDX	_sc5_msg03
		MSG_IDX	_sc5_msg04
		MSG_IDX	_sc5_msg05
		MSG_IDX	_sc5_msg06
		MSG_IDX	_sc5_msg08
		MSG_IDX	_sc5_msg09
		MSG_IDX	_sc5_msg0A
		MSG_IDX	_sc5_msg0B
		MSG_IDX	_sc5_msg0C
		MSG_IDX	_sc5_msg0D
		MSG_IDX	_sc5_msg0E
		MSG_IDX	_sc5_msg0F
		MSG_IDX	_sc5_msg10
		MSG_IDX	_sc5_msg11
		MSG_IDX	_sc5_msg12
		MSG_IDX	_sc5_msg13
		MSG_IDX	_sc5_msg14
		MSG_IDX	_sc5_msg15
		MSG_IDX	_sc5_msg16
		MSG_IDX	_sc5_msg17
		MSG_IDX	_sc5_msg18
		MSG_IDX	_sc5_msg19
		MSG_IDX	_sc5_msg1A
		MSG_IDX	_sc5_msgB3
_sc5_msg00:
		.BYTE	_S,_na,_ch,_a,_la,__,_m,_ji,__p,_ro,_ve,_ri,_li,__,_me,_s,_to,_ret
		.BYTE	_na,_sh,_e,_j,__,_t,_u,_s,_o,_v,_ki,_dot,_ret
		.BYTE	_ret
		.BYTE	_V,_la,_de,_l,_e,_c,_ddt__quo,_an0,_JE,_j,_col_,_h,_va,_ti,_t_mz,__,_m,_en,_ja,_ret
		.BYTE	_ta,_k,__p,_u,_g,_a,_t_mz,_exc,__,_N,_e,_l,_mz,_z,_ja_,_o,_t,_k,_r,_ji,_va,_t_mz,_ret
		.BYTE	_je,_t,_u,__,_g,_r,_jo,_b,_a,_n,_u,_ju,__,_d,_ve,_r,_mz_,_ti,_sh,_e,_que,_exc,__,_CH,_to,_ret
		.BYTE	_va,_m,__,_o,_p,_ja,_t_mz,__,_na,_d,_o,_col_,_p,_a,_r,_ni,_que,_aof,_quo,_eol
_sc5_msg01:
		.BYTE	_V,_la,_de,_l,_e,_c,_ddt__quo,_an0,_JE,_j,_col_,_u,_zh,_e,__v,_e,_r,_n,_u,_li,_s,_mz,_que,_ret
		.BYTE	_N,_a,_sh,_li,__,_Tjecuo,_que,_aof,_quo,_eol
_sc5_msg02:
		.BYTE	_V,_la,_de,_l,_e,_c,_ddt__quo,_an0,_JE,_j,_exc,__,_S,_to,_j,_exc,_aof,_quo,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_V,_o,_t,__,_e,_sch,_jo,_col_,_g,_l,_u,_po,_st,_i,_exc_quo,_eol
_sc5_msg03:
		.BYTE	_M,_ji,__,_d,_o,_st,_i,_g,_li,__s,_e,_k,_to,_ra,__,_num,_dot,_eol
_sc5_msg04:
		.BYTE	_P,_re,_zh,_de,__,_ch,_e,_m,__v,_e,_r,_n,_u,_t_mz,_s_ja,_col_,_na,_m,_ret
		.BYTE	_n,_u,_zh,_no,__,_u,_z,_na,_t_mz,__,_me,_s,_to,_po,_lo,_zh,_e,_ni,_e,_ret
		.BYTE	_Tjecuo,_dot,_eol
_sc5_msg05:
		.BYTE	_M,_u,_zh,_ch,_i,_na,_ddt__quo,_an0,_O,_col_,_Tjecuo,_que,__,_O,_n,__,_e,_h,_a,_l,__v,_ret
		.BYTE	_s,_to,_ro,_n,_u,__s,_e,_k,_to,_ra,__,_2,_dot,_aof,_quo,_eol
_sc5_msg06:
		.BYTE	_M,_u,_zh,_ch,_i,_na,_ddt__quo,_an0,_P,_ri,_d,_u,_r,_ki,_col_,_o,_t,__,_va,_s,_ret
		.BYTE	_s,_li,_sh,_ko,_m,__,_m,_no,_go,__,_sh,_u,_m,_a,_exc,_aof,_quo,_eol
_sc5_msg08:
		.BYTE	_M,_u,_zh,_ch,_i,_na,_ddt__quo,_an0,_Tjecuo,_que,__,_O,_n,__,_to,_l,_mz,_ko,__,_ch,_to,_ret
		.BYTE	_po,_e,_h,_a,_l,__v,__s,_to,_ro,_n,_u,__s,_e,_k,_to,_ra,__,_3,_dot,_aof,_quo,_eol
_sc5_msg09:
		.BYTE	_M,_u,_zh,_ch,_i,_na,_ddt__quo,_an0,_CH,_to,__,_za,__s,_p,_e,_sh,_ka,_que,_aof,_quo,_eol
_sc5_msg0A:
		.BYTE	_M,_u,_zh,_ch,_i,_na,_ddt__quo,_an0,_E,_s,_li,__v,_ji,__,_i,_sch,_e,_te,__,_Tjecuo,_col,_ret
		.BYTE	_to,__,_o,_n,__s,_ko,_re,_e,__v,_s,_e,_go,__,_na,_p,_ra,_v,_i,_l,_s_ja,_ret
		.BYTE	_v,__s,_e,_k,_to,_r,__,_4,_dot,_aof,_quo,_eol
_sc5_msg0D:
		.BYTE	_V,_o,_da,__b,_e,_zh,_i,_t,__,_ch,_e,_re,_z,__,_ka,_na,_l,_col,_ret
		.BYTE	_o,_t,_de,_l,_ja,_ju,_sch,_i,_j,__,_S,_ta,_r,_ji,_j,__,_go,_ro,_d,_ret
		.BYTE	_o,_t,__,_N,_e,_o,_str,_T,_o,_ki,_o,_dot,_eol
_sc5_msg0E:
		.BYTE	_JE,_to,__,_t,_ru,_sch,_o,_b,_ji,__,_N,_e,_o,_str,_T,_o,_ki,_o,_dot,__,_Z,_de,_s,_mz,_ret
		.BYTE	_e,_s,_t_mz,__,_la,_p,_sh,_e,_ch,_na,_ja,__i_,_o,_b,_sch,_a,_g,_a,_dot,_eol
_sc5_msg0F:
		.BYTE	_JE,_to,__,_o,_k,_ra,_i,_na,__,_N,_e,_o,_str,_T,_o,_ki,_o,_dot,__,_Z,_de,_s,_mz,_ret
		.BYTE	_v,__,_o,_k,_ru,_g,_e_,_m,_no,_go,__,_za,_vo,_d,_o,_v,_dot,_eol
_sc5_msg10:
		.BYTE	_Kanjeda,_ddt__quo,_T,_ji,__b,_ji,__,_ta,_k,__,_ne,_ret
		.BYTE	_d,_jo,_r,_g,_a,_l,_s_ja,_col_,_e,_s,_li,__b,_ji,__,_te,_b,_e_,_ne,_ch,_e,_go,_ret
		.BYTE	_b,_ji,_lo,__s,_k,_r,_ji,_va,_t_mz,_dot,__,_M,_o,_zh,_e,_t,_col_,_na,_ch,_n,_jo,_sh,_mz,_ret
		.BYTE	_p,_ro,_da,_va,_t_mz,__,_no,_r,_m,_a,_l,_mz,_n,_u,_ju,__v,_ji,_p,_i,_v,_k,_u,_ret
		.BYTE	_d,_l,_ja_,_na,_ch,_a,_la,_que_quo,_eol
_sc5_msg11:
		.BYTE	_V,_la,_de,_l,_e,_c,_ddt__quo,_an0,_K,_a,_k,__,_na,_s,_ch,_jo,_t,__,_k,_u,_p,_i,_t_mz,_ret
		.BYTE	_ch,_to,_str,_ni,_b,_u,_d,_mz_,_d,_l,_ja_,_na,_ch,_a,_la,_que,_exc,__,_I,_sh,_mz,_col,_ret
		.BYTE	_na,_sh,_li,__s,_e,_b,_e_,_me,_s,_to,__,_d,_l,_ja_,_t,_u,_s,_o,_v,_ki,_exc,_aof,_quo,_ret
		.BYTE	_ret
		.BYTE	_JA,_m,_a,_g,_a,_ta,_ddt__quo,_A,_g,_a,_col_,_p,_i,_t_mz,__,_mo,_ch,_u,__,_t,_vo,_e,_j,_ret
		.BYTE	_s,_o,_b,_a,_ki,_que_quo,_eol
_sc5_msg12:
		.BYTE	_JE,_to,_t,__,_ko,_z,_jo,_l,__p,_r,_ja,_ch,_e,_t,__,_ta,_b,_l,_e,_t,_ki,_ret
		.BYTE	_po,_d,__p,_ri,_la,_v,_ko,_m,_dot,_eol
_sc5_msg13:
		.BYTE	_V,_la,_de,_l,_e,_c,_ddt__quo,_an0,_JE,_j,_col_,_e,_s,_li,__,_t,_ji,__,_i,_sch,_e,_sh,_mz,_ret
		.BYTE	_ta,_b,_l,_e,_t,_ki,_col_,_to,__,_u,__,_m,_en,_ja_,_b,_o,_l,_mz,_sh,_e,_ret
		.BYTE	_ni,_ch,_e,_go,__,_ne,_t,_dot,_aof,_quo,_eol
_sc5_msg18:
		.BYTE	_Kanjeda,_ddt__quo,_I,_z,_v,_i,_ni,_dot,__,_JE,_j,_col_,_mo,_zh,_no,__,_m,_ne,_ret
		.BYTE	_je,_ti,__,_ta,_b,_l,_e,_t,_ki,_que_quo,_eol
_sc5_msg14:
		.BYTE	_V,_la,_de,_l,_e,_c,_ddt__quo,_an0,_JA,__,_d,_u,_m,_a,_ju,_col_,_ch,_to,__,_Tjecuo,_ret
		.BYTE	_na,_p,_ra,_v,_i,_l,_s_ja,__v,__s,_e,_k,_to,_r,__,_num,_dot,_aof,_quo,_eol
_sc5_msg15:
		.BYTE	_N,_e,_t,__,_ni,_ka,_ki,_h,__p,_ri,_z,_na,_ko,_v,__,_Tjecuo,_dot,_eol
_sc5_msg16:
		.BYTE	_M,_u,_zh,_ch,_i,_na,_ddt__quo,_an0,_V,_ji,__p,_ri,_h,_o,_di,_te,__s,_ju,_da,_col,_ret
		.BYTE	_vo,_n,_ja,_ja_,_a,_l,_ko,_go,_l,_e,_m,_col_,_i,_ret
		.BYTE	_v,_ji,_p,_en,_d,_ri,_va,_e,_te,_s,_mz,_dot,__,_P,_ro,_ja,_v,_i,_te,_ret
		.BYTE	_ne,_m,_no,_go,__,_u,_va,_zh,_e,_ni,_ja,_exc,_aof,_quo,_ret
		.BYTE	_ret
		.BYTE	_M,_u,_zh,_ch,_i,_na,__v,_ne,_za,_p,_no,__,_u,_da,_ri,_l_,_m,_en,_ja,_ret
		.BYTE	_po,__,_li,_c,_u,_dot,__,_Z,_a,_v,_ja,_za,_la,_s,_mz_,_d,_ra,_ka,_dot,_eol
_sc5_msg17:
		.BYTE	_Kaj,_ddt__quo,_Kanjeda,_exc,__,_K,_o,_p,_ji,_exc_quo,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_S,_va,_li,_va,_e,_m,_exc_quo,_ret
		.BYTE	_ret
		.BYTE	_N,_o,__,_m,_ji,__b,_ji,_li,__,_po,_j,_m,_a,_n,_ji,__,_po,_li,_c,_i,_e,_j,_dot,_eol
_sc5_msgB3:
		.BYTE	_V,_la,_de,_l,_e,_c,_ddt__quo,_an0,_Tjecuo,__,_na,_p,_ra,_v,_i,_l,_s_ja,__v,_ret
		.BYTE	_s,_to,_ro,_n,_u,__s,_e,_k,_to,_ra,__,_num,_dot,_aof,_quo,_ret
		.BYTE	_ret
		.BYTE	_Kaj,_ddt__quo,_B,_ji,_st,_re,_e,_col_,_m,_ji,__,_te,_r,_ja,_e,_m,_ret
		.BYTE	_v,_re,_m,_ja,_exc_quo,_eol
_sc5_msg19:
		.BYTE	_M,_u,_zh,_ch,_i,_na,_ddt__quo,_an0,_T,_ji,__,_i,_sch,_e,_sh,_mz_,_to,_go,__p,_a,_r,_n,_ja,_que,_ret
		.BYTE	_O,_n,__,_o,_t,_p,_ra,_v,_i,_l,_s_ja,__v,__p,_ro,_m,_z,_o,_n,_u,_dot,_aof,_quo,_eol
_sc5_msg0B:
		.BYTE	_M,_u,_zh,_ch,_i,_na,_ddt__quo,_an0,_JE,_j,_col_,_p,_ro,_va,_li,_va,_j,_exc,_ret
		.BYTE	_dot_dot_dot,_R,_a,_z,_ve,__,_ch,_to,__,_u,__,_te,_b,_ja_,_ne,_ret
		.BYTE	_na,_j,_d,_jo,_t,_s_ja,__,_ta,_b,_l,_e,_to,_k,_dot_dot_dot,_aof,_quo,_eol
_sc5_msg1A:
		.BYTE	_M,_u,_zh,_ch,_i,_na,_ddt__quo,_an0,_H,_e,_str,_h,_e,_dot_dot_dot,__,_T,_a,_k,__,_t,_ji,_ret
		.BYTE	_p,_ri,_n,_jo,_s,__,_m,_ne,__,_ta,_b,_l,_e,_t,_ki,_que,_aof,_quo,_eol
_sc5_msg0C:
		.BYTE	_M,_u,_zh,_ch,_i,_na,_ddt__quo,_an0,_S,_str,_s,_p,_a,_s,_i,_b,_o,_dot,__,_T,_str,_t,_ji,_ret
		.BYTE	_ko,_go,_str,_to,__,_i,_sch,_e,_sh,_mz,_que,_aof,_quo,_eol

		SECTION_END		F5
