
		SECTION_START	F7

		MSG_START	_scene7_msg_lib
		MSG_IDX	_sc7_msg04
		MSG_IDX	_sc7_msg05
		MSG_IDX	_sc7_msg06
		MSG_IDX	_sc7_msg07
		MSG_IDX	_sc7_msg08
		MSG_IDX	_sc7_msg09
		MSG_IDX	_sc7_msg0A
		MSG_IDX	_sc7_msg0B
		MSG_IDX	_sc7_msg0C
		MSG_IDX	_sc7_msg0D
		MSG_IDX	_sc7_msg0E
		MSG_IDX	_sc7_msg0F
		MSG_IDX	_sc7_msg10
		MSG_IDX	_sc7_msg11
		MSG_IDX	_sc7_msg12
		MSG_IDX	_sc7_msg13
		MSG_IDX	_sc7_msg14
		MSG_IDX	_sc7_msg15
		MSG_IDX	_sc7_msg16
		MSG_IDX	_sc7_msg17
		MSG_IDX	_sc7_msg18
		MSG_IDX	_sc7_msg19
		MSG_IDX	_sc7_msg1A
		MSG_IDX	_sc7_msg1B
		MSG_IDX	_sc7_msg1C
		MSG_IDX	_sc7_msg1D
		MSG_IDX	_sc7_msg1E
		MSG_IDX	_sc7_msg1F
		MSG_IDX	_sc7_msg20
		MSG_IDX	_sc7_msg21
		MSG_IDX	_sc7_msg22
		MSG_IDX	_sc7_msg23
		MSG_IDX	_sc7_msg24
		MSG_IDX	_sc7_msg25
		MSG_IDX	_sc7_msg26
		MSG_IDX	_sc7_msg27
		MSG_IDX	_sc7_msg28
		MSG_IDX	_sc7_msg29
		MSG_IDX	_sc7_msg2A
		MSG_IDX	_sc7_msgBB
		MSG_IDX	_sc7_msgBC
		MSG_IDX	_sc7_msgBD
		MSG_IDX	_sc7_msgBE
_sc7_msgBB:
		.BYTE	_T,_o,_j,__,_no,_ch,_mz,_ju,__,_m,_ji,__b,_ji,_li,__v,__s,_a,_d,_u,__,_na,_ret
		.BYTE	_k,_r,_ji,_sh,_e,__p,_e,_re,_d,__,_f,_o,_n,_ta,_no,_m,_col_,_g,_de,_ret
		.BYTE	_o,_b,_zh,_i,_m,_a,_li,_s,_mz_,_ne,_s,_ko,_l,_mz,_ko,__p,_a,_ro,_ch,_e,_k,_dot,_eol
_sc7_msg28:
		.BYTE	_JA,__,_ne,__,_mo,_g,__,_d,_u,_m,_a,_t_mz,__,_ni,__,_o,__,_ch,_jo,_m,_ret
		.BYTE	_d,_ru,_go,_m,_col_,_k,_ro,_me,__,_to,_go,__,_de,_r,_mz,_m,_a,_col_,_ch,_to,_ret
		.BYTE	_s,_l,_u,_ch,_i,_lo,_s,_mz_,_s,__,_na,_m,_i,__,_ne,_da,_v,_no,_dot,_eol
_sc7_msgBC:
		.BYTE	_dot_dot_dot,_V,_s,_jo,_str,_ta,_ki,_col_,_ch,_to,__,_je,_to,__b,_ji,_l_,_za,_ret
		.BYTE	_mo,_r,_sch,_i,_ni,_st,_ji,_j,__,_re,_b,_jo,_no,_k,__,_to,_j,__,_no,_ch,_mz,_ju,_que,_eol
_sc7_msgBD:
		.BYTE	_Tjecuo,__v,_e,_d,_mz_,_ne,__,_i,_me,_e,_t,__,_ni,_ka,_ko,_go,_ret
		.BYTE	_o,_t,_no,_sh,_e,_ni,_ja_,_k,__,_to,_m,_u,__p,_a,_c,_a,_n,_u,_que,__,_K,_u,_da,_col,_ret
		.BYTE	_ch,_jo,_r,_t,__,_po,_b,_e,_ri,_col_,_v,_oennji,_e_,_e,_go,_ret
		.BYTE	_za,_b,_ra,_li,_que,_eol
_sc7_msg29:
		.BYTE	_V,_oennji,_e_,_g,_na,_li,_s,_mz_,_za,__,_de,_v,_u,_sh,_ko,_j,_que,_eol
_sc7_msg2A:
		.BYTE	_E,_s,_li,__v,_oennji,_e_,_za,_n,_ja,_t,_ji,_ret
		.BYTE	_te,_r,_ro,_ri,_st,_a,_m,_i,_col_,_te,_m,__,_l,_u,_ch,_sh,_e,_ret
		.BYTE	_d,_l,_ja_,_na,_s,_dot,_eol
_sc7_msgBE:
		.BYTE	_Kaj,_ddt__quo,_an1,_N,_u,_col_,_o,__,_ch,_jo,_m,__,_za,_d,_u,_m,_a,_li,_s,_mz,_que,_aof,_quo,_ret
		.BYTE	_ret
		.BYTE	_F,_a,_na,_t,_ka,_ddt__quo,_an0,_S,_k,_u,_ko,_ti,_sch,_a,_exc,_aof,_quo,_ret
		.BYTE	_ret
		.BYTE	_JA,_m,_a,_g,_a,_ta,_ddt__quo,_an2,_Z,_a,_mo,_l,_ch,_i,_exc,_aof,_quo,_ret
		.BYTE	_ret
		.BYTE	_F,_a,_na,_t,_ka,_ddt__quo,_an0,_H,_m,_dot_dot_dot,__,_i,_di,_o,_t,_exc,_aof,_quo,_eol
_sc7_msg1F:
		.BYTE	_Kanjeda,_ddt__quo,_P,_a,_r,_ni,_col_,_ja_,_h,_o,_te,_l,_ret
		.BYTE	_ko,_e,_str,_ch,_to,__,_u,__,_va,_s,__s,_p,_ro,_s,_i,_t_mz,_dot_dot_dot,_eol
_sc7_msg04:
		.BYTE	_JA,_m,_a,_g,_a,_ta,_ddt__quo,_an2,_V,_i,_di,_mo,_col_,_Tjecuo,__s,_i,_l,_mz,_no,_ret
		.BYTE	_st,_u,_k,_n,_u,_l,_s_ja,__,_go,_lo,_vo,_j,__,_vo,__v,_re,_m,_ja,_ret
		.BYTE	_a,_va,_ri,_i,_dot,__,_O,_n,__s,_i,_l,_mz,_no,__,_i,_z,_me,_ni,_l,_s_ja,_dot,_aof,_quo,_eol
_sc7_msg05:
		.BYTE	_JA,_m,_a,_g,_a,_ta,_ddt__quo,_an2,_B,_o,_l,_va,_n,_ji,_str,_v,_oennji,_e,_ret
		.BYTE	_ja,_v,_no,__,_ch,_to,_str,_to,__s,_k,_r,_ji,_va,_ju,_t,_dot,_aof,_quo,_eol
_sc7_msg06:
		.BYTE	_JA,_m,_a,_g,_a,_ta,_ddt__quo,_an2,_JE,_to,_t,__s,_o,_p,_l,_ja,_k,__,_ka,_k,_str,_to,_ret
		.BYTE	_s,_v,_ja,_za,_n,__s,__v,_oennji,_m,_i,_dot,_aof,_quo,_eol
_sc7_msg07:
		.BYTE	_JA,_m,_a,_g,_a,_ta,_ddt__quo,_an2,_K,__,_Tjecuo,__v,_oennji,_e,_ret
		.BYTE	_o,_t,_no,_s_ja,_t,_s_ja,__,_ta,_k,__,_zh,_e,_col_,_ka,_k,__i_,_k,__,_to,_m,_u,_ret
		.BYTE	_p,_a,_re,_n,_mz,_k,_u,_dot,_aof,_quo,_eol
_sc7_msg08:
		.BYTE	_JA,_m,_a,_g,_a,_ta,_ddt__quo,_an2,_JE,_to,__,_k,_to,_col_,_ka,_ko,_j,_str,_to,_ret
		.BYTE	_p,_a,_re,_n,_mz_,_i,_z,__,_sh,_ko,_l,_ji,_que,_aof,_quo,_eol
_sc7_msg09:
		.BYTE	_Kaj,_ddt__quo,_an1,_JA,__,_u,_ve,_re,_n,_col_,_ch,_to,__,_o,_n,__,_u,_z,_na,_l,_ret
		.BYTE	_vo,_en,_n,_u,_ju,__,_ta,_j,_n,_u,__,_i,_li,__v,_ro,_de,__,_to,_go,_dot,_aof,_quo,_eol
_sc7_msg0A:
		.BYTE	_Kaj,_ddt__quo,_an1,_K,_a,_zh,_e,_t,_s_ja,_col_,_o,_ni,__,_na,_z,_ji,_va,_li,_ret
		.BYTE	_Tjecuo,__,_quo,_je,_k,_s,_p,_e,_ri,_m,_en,_ta,_l,_mz,_n,_ji,_m,_ret
		.BYTE	_o,_b,_tz,_e,_k,_to,_m,_quo,__,_i,_li,__,_ka,_k,_str,_to,__,_ta,_k,_dot,_aof,_quo,_eol
_sc7_msg0B:
		.BYTE	_Kaj,_ddt__quo,_an1,_M,_o,_zh,_e,_t,_col_,_Tjecuo,__,_u,_zh,_e,_ret
		.BYTE	_p,_re,_v,_ra,_ti,_li,__v,__,_ka,_ko,_j,_str,_to,__v,_oennji,_j,_ret
		.BYTE	_je,_k,_s,_p,_e,_ri,_m,_en,_t,_que,_aof,_quo,_eol
_sc7_msg0C:
		.BYTE	_Kaj,_ddt__quo,_an1,_JA,__,_ne,__,_o,_ch,_en,_mz_,_po,_ni,_m,_a,_ju,_dot,_aof,_quo,_eol
_sc7_msg0D:
		.BYTE	_Kaj,_ddt__quo,_an1,_A,_que,__,_K,_to,__,_je,_to,_que,_aof,_quo,_eol
_sc7_msg0E:
		.BYTE	_F,_a,_na,_t,_ka,_ddt__quo,_an0,_N,_e_,_z,_na,_ju,_dot,_aof,_quo,_eol
_sc7_msg0F:
		.BYTE	_F,_a,_na,_t,_ka,_ddt__quo,_an0,_H,_va,_ti,_t,__,_u,_zh,_e_,_d,_u,_m,_a,_t_mz,_ret
		.BYTE	_o,__v,_s_ja,_ko,_j,__,_e,_ru,_n,_de,_col_,_m,_ji,__,_h,_o,_ti,_m,_ret
		.BYTE	_d,_o,_mo,_j,_dot,__,_B,_e,_z,__s,_vo,_i,_h,__b,_a,_j,_ko,_v,__v,_ji,_ret
		.BYTE	_p,_ro,_s,_to,__,_k,_u,_ch,_ka,__b,_a,_b,_ni,_ko,_v,_str,_ret
		.BYTE	_ne,_u,_da,_ch,_ni,_ko,_v,_dot,_aof,_quo,_eol
_sc7_msg10:
		.BYTE	_Kaj,_ddt__quo,_an1,_S,_a,_m,_a,__,_d,_u,_ra,_dot_dot_dot,_aof,_quo,__,__,__,__,__,__,__,__,__,__,_eol
_sc7_msg11:
		.BYTE	_S,_ra,_z,_u,__,_po,_s,_l,_e_,_to,_go,_col_,_ka,_k,__,_f,_a,_na,_t,_ki,_ret
		.BYTE	_u,_sh,_li,_col_,_na,__,_a,_l,_l,_e,_e,__p,_ro,_i,_z,_o,_sh,_jo,_l,_ret
		.BYTE	_v,_z,_r,_ji,_v,_dot_dot_dot,_eol
_sc7_msg12:
		.BYTE	_CH,_to,__,_je,_to,__b,_ji,_lo,_que,_exc,_ret
		.BYTE	_ret
		.BYTE	__,__,__,__,__,__,_str,_k,_h,_e,_str,_ret
		.BYTE	_ret
		.BYTE	__,__,_P,_o,_mo,_g,_i,_te,_exc,_ret
		.BYTE	_ret
		.BYTE	__,__,__,__,__,__,__,__,__,_B,_e,_g,_i,_te,__,_o,_t,_s,_ju,_da,_exc,_ret
		.BYTE	_ret
		.BYTE	_V,_ji,_z,_o,_v,_i,_te,__,_po,_li,_c,_i,_ju,_exc,_eol
_sc7_msg13:
		.BYTE	_JA,_m,_a,_g,_a,_ta,_ddt__quo,_an2,_P,_ro,_k,_l,_ja,_t_mz,_e,_col_,_s,_no,_va,_ret
		.BYTE	_te,_r,_ro,_ri,_st,_ji,_dot,__,_N,_a,_d,_o,__,_va,_li,_t_mz,_exc,_aof,_quo,_eol
_sc7_msg14:
		.BYTE	_K,_o,_g,_da,__,_ja_,_p,_ro,_b,_i,_l,_s_ja,__s,_k,_vo,_z,_mz_,_to,_l,_p,_u,_ret
		.BYTE	_u,_b,_e,_g,_a,_ju,_sch,_i,_h,__,_l,_ju,_de,_j,_col_,_i,_z,__,_d,_ji,_m,_a,_ret
		.BYTE	_po,_ja,_v,_i,_li,_s,_mz_,_te,_r,_ro,_ri,_st,_ji,_dot,_eol
_sc7_msg15:
		.BYTE	_M,_o,_i,__,_d,_ru,_z,_mz,_ja_,_za,_te,_r,_ja,_li,_s,_mz_,_v,__,_to,_l,_p,_e,_dot,_eol
_sc7_msg16:
		.BYTE	_I,_h,__b,_ji,_lo,__,_4,__,_i,_li,__,_5,_dot,__,_O,_ni,__v,_ji,_sh,_li,__,_i,_z,_ret
		.BYTE	_d,_ji,_m,_a,_col_,_s,_ve,_r,_ka,_ja_,_p,_u,_sh,_ka,_m,_i,_col_,_i,_ret
		.BYTE	_na,_p,_a,_li,__,_na,__v,_oennji,_h,_exc,_eol
_sc7_msg17:
		.BYTE	_S,_re,_di,__,_ni,_h,__b,_ji,_la,__,_de,_v,_u,_sh,_ka,_dot,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_JE,_to,__,_zh,_e_,_ta,__s,_a,_m,_a,_ja,_ret
		.BYTE	_de,_v,_ch,_o,_n,_ka,_exc_quo,_eol
_sc7_msg18:
		.BYTE	_O,_ch,_en,_mz_,_d,_ji,_m,_no,_dot_dot_dot,_eol
_sc7_msg19:
		.BYTE	_V,_oennji,_e_,_po,_g,_na,_li,_s,_mz_,_za,_ret
		.BYTE	_te,_r,_ro,_ri,_st,_a,_m,_i,_col_,_o,_st,_a,_v,_i,_v,__,_a,_l,_l,_e,_ju,_dot,_eol
_sc7_msg1A:
		.BYTE	_JA,__s,_l,_ji,_sh,_u,_col_,_ka,_k,__v,_oennji,_e_,_st,_re,_l,_ja,_ju,_t,_dot,_eol
_sc7_msg1B:
		.BYTE	_V,_oennji,_j,_ddt__quo,_O,_ni,__,_u,_sh,_li,__,_po,_ret
		.BYTE	_ka,_na,_li,_za,_c,_i,_i,_exc_quo,_eol
_sc7_msg1C:
		.BYTE	_V,_oennji,_e_,_da,_li,__,_i,_m,__,_u,_b,_e,_zh,_a,_t_mz,_dot,_eol
_sc7_msg1D:
		.BYTE	_F,_a,_na,_t,_ka,_ddt__quo,_an0,_R,_a,_z,_ve,__,_t,_ji,__,_ne,__,_h,_o,_ch,_e,_sh,_mz,_ret
		.BYTE	_s,_p,_a,_st,_i,__,_Tjecuo,_col_,_Kanjeda,_que,_aof,_quo,_eol
_sc7_msg1E:
		.BYTE	_F,_a,_na,_t,_ka,_ddt__quo,_an0,_L,_a,_d,_no,_col_,_u,_h,_o,_di,_m,_exc,_ret
		.BYTE	_O,_st,_a,_v,_i,_m,__,_je,_ti,_h,__,_i,_z,_v,_ra,_sch,_en,_c,_e,_v,__,_t,_u,_t,_dot,_aof,_quo,_eol
_sc7_msg20:
		.BYTE	_T,_u,_t,__,_m,_ji,__,_t,_u,_s,_u,_e,_m,_s_ja,_dot,__,_K,_a,_k,__,_o,_b,_ji,_ch,_no,_col,_ret
		.BYTE	_z,_de,_s,_mz_,_ni,_ko,_go,__,_ne,_t,_dot,_eol
_sc7_msg21:
		.BYTE	_JA,__,_o,_ka,_za,_l,_s_ja,__v,__,_ka,_na,_li,_za,_c,_i,_i,_dot,_eol
_sc7_msg22:
		.BYTE	_M,_u,_zh,_ch,_i,_na,_ddt__quo,_an0,_D,_e,_v,_u,_sh,_ka,_que,__,_V,_oennji,_e,_ret
		.BYTE	_g,_na,_li,_s,_mz_,_za,__,_k,_e,_m,_str,_to,__,_vo,_n,__,_t,_u,_da,_dot_dot_dot,_aof,_quo,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_S,_p,_a,_s,_i,_b,_o,_exc_quo,_ret
		.BYTE	_ret
		.BYTE	_JA,__,_po,_b,_e,_zh,_a,_l,__v,__,_ka,_na,_li,_za,_c,_i,_ju,_dot,_eol
_sc7_msg23:
		.BYTE	_JA,__p,_ro,_sh,_jo,_l_,_vo,_z,_l,_e_,_la,_p,_sh,_i,_ch,_no,_j,__,_i,_ret
		.BYTE	_o,_b,_sch,_a,_g,__v,__,_S,_ta,_ro,_m,__,_go,_ro,_de,_dot,_eol
_sc7_msg24:
		.BYTE	_M,_u,_zh,_ch,_i,_na,_ddt__quo,_an0,_JE,_str,_je,_col_,_de,_v,_u,_sh,_ka,_que,__,_N,_i,_ko,_go,_ret
		.BYTE	_ne,__v,_i,_de,_l,_dot,_aof,_quo,_eol
_sc7_msg25:
		.BYTE	_JA,__,_o,_t,_p,_ra,_v,_i,_l,_s_ja,__v,__s,_to,_ro,_n,_u,_ret
		.BYTE	_za,_vo,_d,_o,_v,_dot,_eol
_sc7_msg26:
		.BYTE	_M,_u,_zh,_ch,_i,_na,_ddt__quo,_an0,_D,_e,_v,_u,_sh,_ka,_que,_exc,__,_K,_o,_m,_u,__,_ka,_ka,_ja,_ret
		.BYTE	_ra,_z,_ni,_c,_a,_que,__,_D,_a,_j,__,_m,_ne,__,_ta,_b,_l,_e,_to,_k,_exc,_aof,_quo,_eol
_sc7_msg27:
		.BYTE	_Kanjeda,_ddt__quo,_A,_str,_a,_exc_quo,_ret
		.BYTE	_ret
		.BYTE	_N,_a,_r,_ko,_m,_a,_n,__v,_ji,_ta,_sch,_i,_l_,_no,_zh,__,_i,_ret
		.BYTE	_p,_r,_ji,_g,_n,_u,_l_,_na,__,_m,_en,_ja,_exc,_eol

		SECTION_END		F7
