
		SECTION_START	F10

		MSG_START	_scene10_msg_lib
		MSG_IDX	_sc10_msg00
		MSG_IDX	_sc10_msg01
		MSG_IDX	_sc10_msg02
		MSG_IDX	_sc10_msg03
		MSG_IDX	_sc10_msg04
		MSG_IDX	_sc10_msg05
		MSG_IDX	_sc10_msg06
		MSG_IDX	_sc10_msg07
		MSG_IDX	_sc10_msg08
		MSG_IDX	_sc10_msg09
		MSG_IDX	_sc10_msg0A
		MSG_IDX	_sc10_msg0B
		MSG_IDX	_sc10_msg0C
		MSG_IDX	_sc10_msg0D
		MSG_IDX	_sc10_msg0E
		MSG_IDX	_sc10_msg0F
		MSG_IDX	_sc10_msg10
		MSG_IDX	_sc10_msg11
		MSG_IDX	_sc10_msg12
		MSG_IDX	_sc10_msg13
		MSG_IDX	_sc10_msg14
		MSG_IDX	_sc10_msg15
		MSG_IDX	_sc10_msg16
		MSG_IDX	_sc10_msg17
		MSG_IDX	_sc10_msg18
		MSG_IDX	_sc10_msg19
		MSG_IDX	_sc10_msg1A
		MSG_IDX	_sc10_msg1B
_sc10_msg00:
		.BYTE	_Kanjeda,_ddt__quo,_H,_m,_col_,_po,_h,_o,_zh,_e,_col_,_ja_,_v,_ret
		.BYTE	_la,_b,_o,_ra,_to,_r,_no,_m,__,_i,_z,_o,_l,_ja,_to,_re,_dot,__,_G,_de,__,_zh,_e,_ret
		.BYTE	_Kej,_que_quo,_eol
_sc10_msg01:
		.BYTE	_Kej,_ddt__quo,_an0,_O,_ch,_en,_mz_,_na,_b,_l,_ju,_da,_te,_l,_mz,_no,_dot,_ret
		.BYTE	_K,_a,_k,__,_t,_ji,__s,_e,_b,_ja_,_ch,_u,_v,_st,_v,_u,_e,_sh,_mz,_que,_aof,_quo,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_U,_zh,_a,_s,_no,_dot,_quo,_eol
_sc10_msg02:
		.BYTE	_Kej,_ddt__quo,_an0,_T,_ji,__,_d,_l,_ja_,_na,_s,__s,_o,_ve,_r,_sh,_en,_no,_ret
		.BYTE	_b,_e,_s,_po,_l,_e,_z,_en,__i_,_b,_u,_de,_sh,_mz_,_to,_l,_mz,_ko,_ret
		.BYTE	_o,_b,_u,_z,_o,_j,_dot,_aof,_quo,_eol
_sc10_msg03:
		.BYTE	_Kej,_ddt__quo,_an0,_N,_e_,_po,_h,_o,_zh,_e,_col_,_ch,_to,__,_je,_to,_ret
		.BYTE	_mo,_zh,_no,__s,_lo,_m,_a,_t_mz,_dot_dot_dot,_aof,_quo,_eol
_sc10_msg04:
		.BYTE	_Kanjeda,_ddt__quo,_CH,_jo,_r,_to,_v,_ji,__p,_ri,_d,_u,_r,_ki,_exc,_ret
		.BYTE	_Z,_a,_p,_e,_r,_li,__,_m,_en,_ja_,_t,_u,_t,_exc_quo,_eol
_sc10_msg05:
		.BYTE	_Kanjeda,_ddt__quo,_V,_oennji,_e_,_to,_zh,_e_,_i,_sch,_u,_t,_ret
		.BYTE	_je,_to,_go,__,_A,_ki,_ru,_dot_dot_dot,_quo,_ret
		.BYTE	_ret
		.BYTE	_Kej,_ddt__quo,_an0,_O,_ni,__,_e,_go,__b,_o,_ja,_t,_s_ja,_dot,_ret
		.BYTE	_N,_o,_col_,_po,_h,_o,_zh,_e,_col_,_o,_ni,__,_ka,_k,_str,_to,__s,_mo,_g,_li,_ret
		.BYTE	_za,_b,_lo,_ki,_ro,_va,_li,__,_e,_go,__s,_i,_l,_u,_dot,_aof,_quo,_eol
_sc10_msg06:
		.BYTE	_Kanjeda,_ddt__quo,_O,_n,__,_u,_sh,_jo,_l_,_k,__,_A,_ki,_re,_dot_dot_dot,_que_quo,_ret
		.BYTE	_ret
		.BYTE	_Kej,_ddt__quo,_an0,_T,_a,_k,__s,_ka,_za,_l,_ret
		.BYTE	_m,_a,_l,_mz,_ch,_i,_sh,_ka,_dot_dot_dot,_aof,_quo,_eol
_sc10_msg07:
		.BYTE	_Kej,_ddt__quo,_an0,_N,_a,_sh,__b,_o,_s,_s,__,_str,__,_go,_s,_po,_di,_n,_ret
		.BYTE	_N,_e,_d,_z,_u,__,_str,__s,_ka,_za,_l,_col_,_ch,_to,__,_A,_ki,_ra,__,_str,_ret
		.BYTE	_na,_sh,__,_ko,_z,_ji,_r,_mz,_dot,__,_S,__,_ni,_m,__,_m,_ji,__s,_mo,_zh,_e,_m,_ret
		.BYTE	_s,_ve,_r,_g,_n,_u,_t_mz,__,_ko,_r,_ru,_m,_p,_i,_ro,_va,_n,_no,_e,_ret
		.BYTE	_p,_ra,_v,_i,_te,_l,_mz,_st,_vo,_dot_dot_dot,_aof,_quo,_eol
_sc10_msg08:
		.BYTE	_Kej,_ddt__quo,_an0,_R,_ju,__,_go,_vo,_ri,_l_,_m,_ne,_col_,_ch,_to,_ret
		.BYTE	_A,_ki,_ra,__,_str,__,_je,_to,__,_ch,_i,_st,_a,_ja_,_je,_ne,_r,_g,_i,_ja,_dot,_ret
		.BYTE	_N,_a,__p,_ro,_t,_ja,_zh,_e,_ni,_i,__v,_s,_e,_j,__s,_vo,_e,_j,_ret
		.BYTE	_i,_s,_to,_ri,_i,__,_l,_ju,_di,__s,_o,_z,_da,_ju,_t,__,_m,_no,_zh,_e,_st,_vo,_ret
		.BYTE	_v,_e,_sch,_e,_j,_col_,_ta,_k,_que,_aof,_quo,_eol
_sc10_msg09:
		.BYTE	_Kej,_ddt__quo,_an0,_O,_ni,__,_i,_z,_o,_b,_re,_ta,_ju,_t,_col_,_de,_la,_ju,_t,_ret
		.BYTE	_o,_t,_k,_r,_ji,_ti,_ja,_dot_dot_dot,__,_O,_t,_k,_u,_da,__b,_e,_ru,_t,_s_ja,__v,_s,_e,_ret
		.BYTE	_je,_ti,__,_z,_na,_ni,_ja,__i_,_je,_ne,_r,_g,_i,_ja,_que,_ret
		.BYTE	_N,_e_,_ta,_k,__,_da,_v,_no,__,_m,_ji,__b,_ji,_li,__v,_s,_e,_go,_ret
		.BYTE	_li,_sh,_mz_,_o,_b,_e,_z,_mz,_ja,_na,_m,_i,_dot,_aof,_quo,_eol
_sc10_msg0A:
		.BYTE	_Kej,_ddt__quo,_an0,_A,__,_d,_o,__,_je,_to,_go,__b,_ji,_li,_ret
		.BYTE	_re,_p,_ti,_li,_ja,_m,_i,__i_,_r,_ji,_b,_a,_m,_i,_dot,__,_A,__,_e,_sch,_jo,_ret
		.BYTE	_ra,_n,_mz,_sh,_e_,_str,__p,_la,_n,_k,_to,_no,_m,__i_,_a,_m,_jo,_b,_a,_m,_i,_dot,_ret
		.BYTE	_D,_o,_l,_zh,_no,__b,_ji,_t_mz,_col_,_ka,_ka,_ja,_str,_to,_ret
		.BYTE	_ne,_ve,_ro,_ja,_t,_na,_ja_,_je,_ne,_r,_g,_i,_ja_,_s,_k,_r,_ji,_ta,__,_vo,_ret
		.BYTE	_v,_s,_e,_h,__,_je,_ti,_h,__,_f,_o,_r,_m,_a,_h,__,_zh,_i,_z,_ni,_dot,_aof,_quo,_eol
_sc10_msg0B:
		.BYTE	_Kanjeda,_ddt__quo,_JE,_to,__,_ka,_k,_str,_to,__s,_v,_ja,_za,_no,_ret
		.BYTE	_s,__,_g,_e,_na,_m,_i,_dot_dot_dot,_quo,_eol
_sc10_msg17:
		.BYTE	_Kej,_ddt__quo,_an0,_JA,__,_d,_u,_m,_a,_ju,_col_,_ch,_to,__,_o,_na,__b,_ji,_la,_ret
		.BYTE	_t,_u,_t,__,_d,_o,__,_to,_go,_col_,_ka,_k,__v,__,_vo,_de,__,_i,_ret
		.BYTE	_vo,_z,_d,_u,_h,_e_,_po,_ja,_v,_i,_li,_s,_mz_,_p,_e,_r,_v,_ji,_e,_ret
		.BYTE	_a,_m,_i,_no,_ki,_s,_lo,_t,_ji,_dot_dot_dot,__,_I,__,_da,_zh,_e_,_ra,_n,_mz,_sh,_e,_ret
		.BYTE	_ko,_s,_m,_i,_ch,_e,_s,_ko,_j,__p,_ji,_li,_dot,_aof,_quo,_eol
_sc10_msg0C:
		.BYTE	_Kej,_ddt__quo,_an0,_K,_a,_k,_u,_ju,__,_i,_n,_f,_o,_r,_m,_a,_c,_i,_ju,__,_mo,_zh,_e,_t,_ret
		.BYTE	_ne,_st,_i,__,_je,_ta,__,_je,_ne,_r,_g,_i,_ja,_que,__,_P,_a,_m,_ja,_t_mz,__,_o,_ret
		.BYTE	_na,_ch,_a,_l,_e,__v,_re,_m,_jo,_n,_col_,_a,__,_mo,_zh,_e,_t,__,_da,_zh,_e_,_i,_ret
		.BYTE	_o,__,_to,_m,_col_,_ch,_to,__b,_ji,_lo,__,_d,_o,__,_je,_to,_go,_dot_dot_dot,_ret
		.BYTE	_V,_o,_z,_mo,_zh,_no,_col_,_v,__,_ka,_zh,_d,_o,_m,__,_e,_s,_t_mz,__,_je,_ta,_ret
		.BYTE	_p,_a,_m,_ja,_t_mz,_dot,_aof,_quo,_eol
_sc10_msg0D:
		.BYTE	_Kej,_ddt__quo,_an0,_P,_re,_d,_st,_a,_v,_mz,_col_,_ch,_to,__,_mo,_zh,_e,_t,_ret
		.BYTE	_s,_l,_u,_ch,_i,_t_mz,_s_ja,_col_,_e,_s,_li,__p,_ro,_i,_z,_o,_j,_d,_jo,_t,_ret
		.BYTE	_s,_b,_o,_j,__v,__,_po,_r,_ja,_d,_k,_e_,_ro,_zh,_de,_ni,_ja_,_no,_vo,_j,_ret
		.BYTE	_zh,_i,_z,_ni,_col,__i_,_s,_u,_sch,_e,_st,_vo,_col_,_v,_ro,_de,_ret
		.BYTE	_a,_m,_jo,_b,_ji,_col_,_po,_l,_u,_ch,_i,_t,__s,_i,_l,_u,__,_ch,_e,_lo,_ve,_ka,_que,_aof,_quo,_eol
_sc10_msg18:
		.BYTE	_Kanjeda,_ddt__quo,_Z,_na,_ch,_i,_t,_col_,_i,_m,_en,_no,__,_ta,_ki,_m,_ret
		.BYTE	_s,_u,_sch,_e,_st,_vo,_m,__i_,_b,_ji,_l_,_A,_ki,_ra,_que_quo,_eol
_sc10_msg0E:
		.BYTE	_Kej,_ddt__quo,_an0,_A,_m,_jo,_b,_e_,_ne,__,_n,_u,_zh,_en,__,_d,_o,_m,__,_i,_li,_ret
		.BYTE	_o,_de,_zh,_da,_col_,_o,_na,__p,_ro,_s,_to,__,_po,_zh,_ra,_la,__b,_ji,_ret
		.BYTE	_v,_s,_jo,__,_vo,_k,_ru,_g,__s,_e,_b,_ja,_dot,_aof,_quo,_eol
_sc10_msg19:
		.BYTE	_Kanjeda,_ddt__quo,_I,__,_Tjecuo,_que,__,_O,_n,__s,_mo,_g,_ret
		.BYTE	_o,_b,_re,_st,_i,__,_ta,_k,_u,_ju,__,_je,_ne,_r,_g,_i,_ju,_que,_exc,_eol
_sc10_msg0F:
		.BYTE	_H,_o,_ch,_e,_sh,_mz_,_s,_ka,_za,_t_mz,__,_to,_col_,_ch,_to,_ret
		.BYTE	_u,_ni,_ch,_to,_zh,_i,_lo,__,_i,_n,_k,_u,_b,_a,_to,_r,_col,__i_,_b,_ji,_la,_ret
		.BYTE	_je,_ne,_r,_g,_i,_ja_,_Tjecuo,_que,_exc,__,_E,_go,__s,_i,_la,_que,_eol
_sc10_msg10:
		.BYTE	_E,_s,_li,__,_Tjecuo,__,_na,_j,_d,_jo,_t,__,_A,_ki,_ru,_ret
		.BYTE	_ra,_n,_mz,_sh,_e,_col_,_ch,_e,_m,__,_je,_to,__s,_de,_la,_e,_m,__,_m,_ji,_col,_ret
		.BYTE	_s,_l,_u,_ch,_i,_t,_s_ja,__b,_o,_l,_mz,_sh,_a,_ja_,_b,_e,_da,_exc,_eol
_sc10_msg11:
		.BYTE	_Kej,_ddt__quo,_an0,_K,_o,_g,_da,_str,_to,__,_da,_v,_no,__,_na,_sh,_li,_s,_mz,_ret
		.BYTE	_l,_ju,_di,_col_,_ko,_to,_r,_ji,_e_,_za,_h,_o,_te,_li,__,_u,_me,_t_mz,_ret
		.BYTE	_u,_p,_ra,_v,_l,_ja,_t_mz,__,_je,_to,_j,__,_je,_ne,_r,_g,_i,_e,_j,_dot_dot_dot,__,_D,_l,_ja,_ret
		.BYTE	_je,_to,_go,__p,_ra,_v,_i,_te,_l,_mz,_st,_vo,__,_po,_st,_ro,_i,_lo,_ret
		.BYTE	_i,_s,_s,_l,_e,_d,_o,_va,_te,_l,_mz,_s,_ki,_j,__,_c,_en,_t,_r,_dot,_aof,_quo,_eol
_sc10_msg1A:
		.BYTE	_Kej,__v,_d,_ru,_g,__,_za,_go,_vo,_ri,_la,__,_st,_ra,_n,_n,_ji,_m,_ret
		.BYTE	_go,_lo,_s,_o,_m,_dot,_eol
_sc10_msg12:
		.BYTE	_Kej,_ddt__quo,_an0,_O,_ni,__,_po,_te,_r,_p,_e,_li,__,_ne,_u,_da,_ch,_u,_ret
		.BYTE	_i,__,_ra,_z,_b,_u,_di,_li,__s,_i,_l,_u,_col_,_ko,_to,_ra,_ja,_ret
		.BYTE	_u,_ni,_ch,_to,_zh,_i,_la,__,_T,_o,_ki,_o,_dot,_aof,_quo,_eol
_sc10_msg1B:
		.BYTE	_Kej,_ddt__quo,_an0,_D,_o,__s,_i,_h,__,_po,_r,__,_je,_ta,__s,_i,_la,__,_na,_m,_ret
		.BYTE	_ne,_po,_d,_v,_la,_st,_na,_dot,_aof,_quo,_eol
_sc10_msg13:
		.BYTE	_Kanjeda,_ddt__quo,_O,_col_,_d,_ve,_r,_mz_,_o,_t,_k,_r,_ji,_ta,_exc_quo,_eol
_sc10_msg14:
		.BYTE	_M,_ji,__s,__,_Kej,__s,_b,_e,_zh,_a,_li,__,_i,_z,_ret
		.BYTE	_la,_b,_o,_ra,_to,_ri,_i,_dot,_eol
_sc10_msg15:
		.BYTE	_Kej,_ddt__quo,_an0,_CH,_to,__,_t,_ji,__,_de,_la,_e,_sh,_mz,_que,_exc,_aof,_quo,_eol
_sc10_msg16:
		.BYTE	_K,_a,_k,__,_o,_t,_k,_r,_ji,_t_mz,__,_je,_t,_u,__,_d,_ve,_r,_mz,_que,_eol

		SECTION_END		F10
