
		SECTION_START	F11

		MSG_START	_scene11_msg_lib
		MSG_IDX	_sc11_msg00
		MSG_IDX	_sc11_msg01
		MSG_IDX	_sc11_msg02
		MSG_IDX	_sc11_msg03
		MSG_IDX	_sc11_msg04
		MSG_IDX	_sc11_msg05
		MSG_IDX	_sc11_msg06
		MSG_IDX	_sc11_msg07
		MSG_IDX	_sc11_msg08
		MSG_IDX	_sc11_msg09
		MSG_IDX	_sc11_msg0A
		MSG_IDX	_sc11_msg0B
		MSG_IDX	_sc11_msg0C
		MSG_IDX	_sc11_msg0D
		MSG_IDX	_sc11_msg0E
		MSG_IDX	_sc11_msg0F
		MSG_IDX	_sc11_msg10
		MSG_IDX	_sc11_msg11
		MSG_IDX	_sc11_msg12
		MSG_IDX	_sc11_msg13
		MSG_IDX	_sc11_msg14
		MSG_IDX	_sc11_msg15
		MSG_IDX	_sc11_msg16
		MSG_IDX	_sc11_msg17
		MSG_IDX	_sc11_msg18
		MSG_IDX	_sc11_msg19
		MSG_IDX	_sc11_msg1A
		MSG_IDX	_sc11_msg1B
		MSG_IDX	_sc11_msg1C
		MSG_IDX	_sc11_msg1D
		MSG_IDX	_sc11_msg1E
		MSG_IDX	_sc11_msg1F
		MSG_IDX	_sc11_msg20
		MSG_IDX	_sc11_msg21
		MSG_IDX	_sc11_msg22
		MSG_IDX	_sc11_msg23
		MSG_IDX	_sc11_msg24
		MSG_IDX	_sc11_msg25
		MSG_IDX	_sc11_msg26
		MSG_IDX	_sc11_msg27
		MSG_IDX	_sc11_msg28
		MSG_IDX	_sc11_msg95
		MSG_IDX	_sc11_msg98
_sc11_msg00:
		.BYTE	_O,_st,_a,_v,_i,_v,__,_la,_b,_o,_ra,_to,_ri,_ju,_col_,_Kej,__i_,_ja,_ret
		.BYTE	_po,_sh,_li,__,_na,__,_na,_sh,_e_,_me,_s,_to,__,_t,_u,_s,_o,_v,_ki,_dot,_eol
_sc11_msg1F:
		.BYTE	_N,_o,__p,_e,_re,_d,__b,_a,_ro,_m,__s,_to,_ja,_l_,_Kaj,_col_,_i,_ret
		.BYTE	_o,_n,__b,_ji,_l_,_ch,_e,_m,_str,_to,__,_na,_p,_u,_g,_a,_n,_dot_dot_dot,_eol
_sc11_msg01:
		.BYTE	_M,_ji,__,_po,_sh,_li,__s,__,_K,_a,_e,_m,__,_na,__b,_e,_re,_g,__,_re,_ki,_dot,_eol
_sc11_msg95:
		.BYTE	_Kaj,_ddt__quo,_Kanjeda,_dot_dot_dot,_quo,_eol
_sc11_msg20:
		.BYTE	_Kanjeda,_ddt__quo,_CH,_to,__s,__,_JA,_m,_a,_g,_a,_to,_j,_que,_dot,_dot,_quo,_eol
_sc11_msg02:
		.BYTE	_Kaj,_ddt__quo,_an0,_M,_ji,__s,__,_JA,_m,_a,_g,_a,_to,_j,__p,_ri,_sh,_li,__,_na,_ret
		.BYTE	_na,_sh,_e_,_o,_b,_ji,_ch,_no,_e_,_me,_s,_to,_dot,__,_N,_o,__,_ta,_m,__,_m,_ji,_ret
		.BYTE	_u,_v,_i,_de,_li,__,_ne,_ch,_to,_dot_dot_dot,__,_V,__b,_a,_re,__,_c,_a,_ri,_la,_ret
		.BYTE	_ra,_z,_ru,_h,_a,_col_,_a,__v,_la,_de,_l,_e,_c,__b,_ji,_l,_ret
		.BYTE	_m,_jo,_r,_t,_v,_dot_dot_dot,_aof,_quo,_eol
_sc11_msg03:
		.BYTE	_Kaj,_ddt__quo,_an0,_U,_b,_l,_ju,_d,_o,_k,__,_Tjecuo,__s,_i,_de,_l_,_na,_ret
		.BYTE	_o,_b,_lo,_m,_ka,_h,__i_,_u,_m,_i,_ra,_l,__s,_o,__s,_me,_h,_u,_exc,_aof,_quo,_eol
_sc11_msg26:
		.BYTE	_Kaj,_ddt__quo,_an0,_K,_o,_g,_da,__,_ja_,_e,_go,__,_u,_v,_i,_de,_l,_col_,_ja,_ret
		.BYTE	_po,_n,_ja,_l,_col_,_ch,_to,__,_ch,_to,_str,_to,__,_t,_u,_t,__,_ne,__,_ta,_k,_dot,_ret
		.BYTE	_O,_n,__b,_ji,_l_,_o,_de,_t,__v,__,_ka,_ko,_j,_str,_to,_ret
		.BYTE	_b,_o,_l,_mz,_ni,_ch,_n,_ji,_j,__,_h,_a,_la,_t,_dot,__,_JA,_m,_a,_g,_a,_ta,_ret
		.BYTE	_z,_na,_l,_col_,_ch,_to,__v,_ji,__,_o,_t,_p,_ra,_v,_i,_li,_s,_mz,_ret
		.BYTE	_s,_p,_a,_s,_a,_t_mz,__,_Tjecuo,_dot,_aof,_quo,_eol
_sc11_msg04:
		.BYTE	_Kaj,_ddt__quo,_an0,_O,_n,__s,_me,_ja,_l,_s_ja,_col_,_ka,_k,__b,_u,_d,_to,_ret
		.BYTE	_ni,_ch,_e,_go,__,_ne,__p,_ro,_i,_z,_o,_sh,_lo,_exc,__,_I,__,_o,_n,_ret
		.BYTE	_o,_ch,_en,_mz_,_h,_o,_te,_l_,_u,_z,_na,_t_mz,_col_,_g,_de,__,_t,_vo,_j,_ret
		.BYTE	_b,_a,_j,_k,_dot,_aof,_quo,_eol
_sc11_msg05:
		.BYTE	_Kaj,_ddt__quo,_an0,_T,_o,_g,_da,__,_JA,_m,_a,_g,_a,_ta,__,_na,_k,_ri,_ch,_a,_l,_ret
		.BYTE	_na,__,_ne,_go,__i_,_na,_ch,_a,_l_,_ka,_ra,_b,_ka,_t_mz,_s_ja,__,_po,_ret
		.BYTE	_o,_b,_lo,_m,_ka,_m,_dot_dot_dot,__,_I,__,_t,_u,_t,__,_vo,_lo,_s,_ji,_ret
		.BYTE	_Tjecuo,__v,_st,_a,_li,__,_d,_ji,_b,_o,_m,_dot_dot_dot,_aof,_quo,_eol
_sc11_msg06:
		.BYTE	_Kaj,_ddt__quo,_an0,_Tjecuo,__,_i,_s,_po,_l,_mz,_z,_o,_va,_l,_ret
		.BYTE	_ka,_k,_u,_ju,_str,_to,__s,_ve,_r,_h,_tz,_e,_st,_e,_st,_v,_en,_n,_u,_ju,_ret
		.BYTE	_s,_i,_l,_u,_col_,_ch,_to,_b,_ji,__,_de,_r,_zh,_a,_t_mz,__,_JA,_m,_a,_g,_a,_t,_u,_col,_ret
		.BYTE	_k,_ri,_ch,_a,_sch,_e,_go,__,_o,_t,__b,_o,_li,_dot_dot_dot,__,_a,__,_po,_to,_m,_ret
		.BYTE	_ra,_z,_da,_v,_i,_l_,_e,_m,_u,__,_ch,_e,_re,_p,_dot,_aof,_quo,_eol
_sc11_msg27:
		.BYTE	_Kaj,_ddt__quo,_V,__,_o,_b,_sch,_e,_m,_dot_dot_dot,__,_JA,_m,_a,_g,_a,_str,_quo,_eol
_sc11_msg07:
		.BYTE	_Kanjeda,_ddt__quo,_M,_ji,__v,_s,_e,_g,_da,__b,_ji,_li,_ret
		.BYTE	_v,_me,_st,_e,_dot,__,_JA,__,_z,_na,_ju,__,_Tjecuo,__,_ka,_k,__s,_e,_b,_ja,_dot,_ret
		.BYTE	_dot_dot_dot,_I,__,_ja_,_v,_s,_e,_g,_da,__p,_ro,_sch,_a,_l_,_e,_m,_u,__,_e,_go,_ret
		.BYTE	_ko,_s_ja,_ki,_dot_dot_dot,_quo,_eol
_sc11_msg08:
		.BYTE	_Kaj,_ddt__quo,_an0,_V,_e,_r,_no,_dot_dot_dot,__,_K,_a,_k,__v,__,_je,_to,_t,__,_ra,_z,_col,_ret
		.BYTE	_ko,_g,_da,__,_o,_n,__,_u,_g,_na,_l_,_t,_vo,_j,__b,_a,_j,_k,_dot,_aof,_quo,_eol
_sc11_msg21:
		.BYTE	_Kanjeda,_ddt__quo,_M,_o,_j,__b,_a,_j,_k,_que,_dot,_dot,__,_Kaj,_ret
		.BYTE	_mo,_zh,_e,_sh,_mz_,_p,_ri,_ve,_z,_ti,__,_m,_ne,__b,_a,_j,_k,_ret
		.BYTE	_JA,_m,_a,_g,_a,_t,_ji,_que_quo,_eol
_sc11_msg09:
		.BYTE	_JA,__s,_e,_l_,_na,__b,_a,_j,_k,__,_JA,_m,_a,_g,_a,_t,_ji,_col,_ret
		.BYTE	_ko,_to,_r,_ji,_j,__p,_ri,_v,_jo,_l_,_Kaj,_dot,_eol
_sc11_msg22:
		.BYTE	_Kaj,_ddt__quo,_an0,_CH,_to,__,_t,_ji,__,_de,_la,_e,_sh,_mz,_que,_aof,_quo,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_S,_o,_b,_i,_ra,_ju,_s,_mz_,_o,_t,_da,_t_mz,__,_e,_go,_ret
		.BYTE	_JA,_m,_a,_g,_a,_te,_dot_dot_dot,_quo,_eol
_sc11_msg0B:
		.BYTE	_K,_a,_k,__,_Kej,__s,_v,_ja,_za,_na,__s,__,_je,_ti,_m,_i,_ret
		.BYTE	_de,_t_mz,_m,_i,_dot_dot_dot,_eol
_sc11_msg0C:
		.BYTE	_Kanjeda,_ddt__quo,_H,_va,_ti,_t,__s,__,_m,_en,_ja,_dot,_ret
		.BYTE	_B,_ro,_s,_a,_t_mz,__,_l,_ju,_de,_j,__v,__,_a,_ta,_k,_u,__p,_ro,_ti,_v,_ret
		.BYTE	_Tjecuo,__,_str,__,_je,_to,__,_o,_t,_p,_ra,_v,_l,_ja,_t_mz,__,_i,_h,__,_na,_ret
		.BYTE	_v,_e,_r,_n,_u,_ju,__s,_me,_r,_t_mz,_dot_dot_dot,_quo,_eol
_sc11_msg23:
		.BYTE	_JA,__s,_p,_r,_ji,_g,_n,_u,_l,__i_,_po,_b,_e,_zh,_a,_l,_dot,_eol
_sc11_msg0D:
		.BYTE	_Kej,_ddt__quo,_T,_ji,_dot_dot_dot,__,_A,_str,_a,_exc_quo,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_Kej,_col_,_ch,_to,__s,_l,_u,_ch,_i,_lo,_s,_mz,_que,_exc_quo,_eol
_sc11_msg24:
		.BYTE	_JA,__s,_l,_ji,_sh,_a,_l,_col_,_ka,_k,__,_Kej,__,_za,_k,_ri,_ch,_a,_la,_ret
		.BYTE	_g,_de,_str,_to,__,_po,_d,__,_z,_e,_m,_l,_jo,_j,_dot,_eol
_sc11_msg0E:
		.BYTE	_Kanjeda,_ddt__quo,_JE,_to,__,_t,_ji,_dot_dot_dot,__b,_ji,_l_,_ta,_m,_ret
		.BYTE	_to,_j,__,_no,_ch,_mz,_ju,_dot_dot_dot,_quo,_eol
_sc11_msg0F:
		.BYTE	_R,_e,_b,_jo,_no,_k,__v,_ji,_sh,_e,_l_,_i,_z,__,_vo,_d,_ji,__,_i,_ret
		.BYTE	_po,_d,_o,_sh,_jo,_l_,_k,__,_Kej,_dot,_eol
_sc11_msg10:
		.BYTE	_Kanjeda,_ddt__quo,_CH,_to,__,_t,_ji,__,_de,_la,_e,_sh,_mz_,_s,_ret
		.BYTE	_Kej,_que,_exc_quo,_eol
_sc11_msg11:
		.BYTE	_JA,__,_h,_o,_te,_l_,_po,_d,_b,_e,_zh,_a,_t_mz,__,_k,__,_ne,_m,_u,_col_,_no,_ret
		.BYTE	_mo,_jo,__,_te,_lo,__,_po,_ch,_e,_m,_u,_str,_to,__,_o,_t,_ka,_za,_lo,_s,_mz,_ret
		.BYTE	_d,_v,_i,_g,_a,_t_mz,_s_ja,_dot,_eol
_sc11_msg12:
		.BYTE	_Kanjeda,_ddt__quo,_P,_o,_d,_o,_zh,_di,_exc,__,_Kej,_exc_quo,_eol
_sc11_msg13:
		.BYTE	_Kaj,_ddt__quo,_O,_ni,__,_i,_s,_ch,_e,_z,_li,_dot,_quo,_eol
_sc11_msg14:
		.BYTE	_Kanjeda,_ddt__quo,_K,_u,_da,__,_de,_l,_s_ja,__,_je,_to,_t,_ret
		.BYTE	_s,_u,_ki,_n,__s,_ji,_n,_que_quo,_eol
_sc11_msg15:
		.BYTE	_Kej,__i_,_re,_b,_jo,_no,_k,__,_i,_s,_ch,_e,_z,_li,_dot,_eol
_sc11_msg16:
		.BYTE	_V,_o,_da,__b,_ji,_la,__s,_po,_ko,_j,_no,_j,_dot_dot_dot,_eol
_sc11_msg17:
		.BYTE	_Kanjeda,_ddt__quo,_JE,_to,__,_t,_ji,__v,_i,_no,_va,_t,__v,__,_to,_m,_col,_ret
		.BYTE	_ch,_to,__,_Tjecuo,__,_i,_z,_me,_ni,_l,_s_ja,_exc_quo,_ret
		.BYTE	_ret
		.BYTE	_JA,__,_na,_ch,_a,_l,__s,_p,_u,_s,_ka,_t_mz,_s_ja,__,_po,__s,_k,_lo,_n,_u,_col,_ret
		.BYTE	_no,__v,_d,_ru,_g,__,_u,_s,_l,_ji,_sh,_a,_l_,_go,_lo,_s,_dot,_eol
_sc11_msg18:
		.BYTE	_K,_i,_jo,_ko,_ddt__quo,_an0,_S,_i,_la,__,_A,_ki,_r,_ji,__,_mo,_zh,_e,_t,_ret
		.BYTE	_b,_ji,_t_mz,__v,__,_ka,_zh,_d,_o,_m,_dot_dot_dot,_dot,_aof,_quo,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_A,_que,__,_K,_to,__,_z,_de,_s,_mz,_que,_exc_quo,_eol
_sc11_msg19:
		.BYTE	_K,_i,_jo,_ko,_ddt__quo,_an0,_dot_dot_dot,_N,_o,__,_ko,_g,_da,__,_je,_ta,__s,_i,_la,_ret
		.BYTE	_p,_ro,_b,_u,_zh,_da,_e,_t,_s_ja,_col_,_t,_ji,__,_d,_o,_l,_zh,_en,_ret
		.BYTE	_v,_ji,_b,_ra,_t_mz,_col_,_ka,_k,__,_e,_jo,__,_i,_s,_po,_l,_mz,_z,_o,_va,_t_mz,_col,_ret
		.BYTE	_da,_zh,_e_,_e,_s,_li,__,_t,_ji,__,_ne,__,_go,_to,_v,__,_k,__,_je,_to,_m,_u,_dot,_ret
		.BYTE	_T,_vo,_j,__,_d,_ru,_g,__s,_de,_la,_l,__s,_vo,_j,__v,_ji,_b,_o,_r,_dot,_aof,_quo,_eol
_sc11_msg1A:
		.BYTE	_K,_i,_jo,_ko,_ddt__quo,_an0,_Tjecuo,__,_te,_p,_e,_r,_mz_,_s,__,_na,_m,_i,_col,_ret
		.BYTE	_o,_n,__,_st,_a,_l_,_o,_d,_ni,_m,__,_i,_z,__,_na,_s,_dot_dot_dot,_aof,_quo,_eol
_sc11_msg28:
		.BYTE	_K,_i,_jo,_ko,_ddt__quo,_an0,_M,_ji,__,_o,_t,_ch,_a,_st,_i,__v,_i,_no,_va,_t,_ji,_ret
		.BYTE	_v,__s,_l,_u,_ch,_i,_v,_sh,_e,_m,_s_ja,_dot_dot_dot,_aof,_quo,_eol
_sc11_msg1B:
		.BYTE	_Kanjeda,_ddt__quo,_T,_a,_k,__,_ka,_ko,_go,__,_ch,_jo,_r,_ta,__v,_ji,_ret
		.BYTE	_za,_b,_ra,_li,__,_Kej,_que,_exc_quo,_eol
_sc11_msg0A:
		.BYTE	_K,_i,_jo,_ko,_ddt__quo,_an0,_M,_ji,__,_h,_o,_ti,_m,_col_,_ch,_to,_b,_ji,__,_t,_ji,_ret
		.BYTE	_po,_mo,_g,__,_na,_m,_dot,_aof,_quo,_eol
_sc11_msg1C:
		.BYTE	_Kanjeda,_ddt__quo,_V,_e,_r,_ni,_te,__,_Kej,__,_na,_za,_d,_exc,_ret
		.BYTE	_Tjecuo,__,_N,_E,__,_o,_di,_n,__,_i,_z,__,_va,_s,_exc,__,_O,_n,__,_mo,_j,_ret
		.BYTE	_d,_ru,_g,_exc,__,_JA,__,_ra,_z,_b,_e,_ru,_s,_mz_,_s,__,_ni,_m,__s,_a,_m,_exc_quo,_eol
_sc11_msg25:
		.BYTE	_Kanjeda,_ddt__quo,_P,_ro,_k,_l,_ja,_t_mz,_e,_exc_quo,_eol
_sc11_msg1D:
		.BYTE	_CH,_jo,_r,_t,__b,_ji,__,_po,_b,_ra,_l_,_je,_to,_go,__,_Tjecuo,_col,_ret
		.BYTE	_k,_u,_da,__,_o,_n,__,_de,_l,_s_ja,_que,_exc,_eol
_sc11_msg1E:
		.BYTE	_JA,__,_o,_to,_m,_sch,_u,__,_za,__,_JA,_m,_a,_g,_a,_t,_u,_dot,__,_T,_ji,__,_ta,_k,_ret
		.BYTE	_h,_o,_te,_l_,_mo,_j,__b,_a,_j,_k,_col_,_vo,_t,__,_te,_p,_e,_r,_mz,_ret
		.BYTE	_s,_i,_di,__i_,_zh,_di,__,_m,_en,_ja,_dot_dot_dot,_eol
_sc11_msg98:
		.BYTE	_JA,__,_po,_s,_mo,_t,_re,_l_,_na,__,_re,_k,_u,__v,_ni,_z,_u,_dot_dot_dot,_eol

		SECTION_END		F11
