
		SECTION_START	FF

		MSG_START	_sceneF_msg_lib
		MSG_IDX	_scF_msg00
		MSG_IDX	_scF_msg01
		MSG_IDX	_scF_msg02
		MSG_IDX	_scF_msg03
		MSG_IDX	_scF_msg04
		MSG_IDX	_scF_msg05
		MSG_IDX	_scF_msg06
		MSG_IDX	_scF_msg07
		MSG_IDX	_scF_msg08
		MSG_IDX	_scF_msg09
		MSG_IDX	_scF_msg0A
		MSG_IDX	_scF_msg0C
		MSG_IDX	_scF_msg0D
		MSG_IDX	_scF_msg0E
		MSG_IDX	_scF_msg0F
		MSG_IDX	_scF_msg10
		MSG_IDX	_scF_msg11
		MSG_IDX	_scF_msg12
		MSG_IDX	_scF_msg13
		MSG_IDX	_scF_msg14
		MSG_IDX	_scF_msg15
		MSG_IDX	_scF_msg16
		MSG_IDX	_scF_msg17
		MSG_IDX	_scF_msg18
		MSG_IDX	_scF_msg19
		MSG_IDX	_scF_msg1A
		MSG_IDX	_scF_msg1B
		MSG_IDX	_scF_msg1C
		MSG_IDX	_scF_msg1D
		MSG_IDX	_scF_msg1E
		MSG_IDX	_scF_msg1F
		MSG_IDX	_scF_msg92
_scF_msg00:
		.BYTE	_D,_e,_t,_s,_ka,_ja_,_v,_ji,_g,_l,_ja,_de,_la,__,_ka,_k,__,_po,_s,_l,_e,_ret
		.BYTE	_z,_e,_m,_l,_e,_t,_r,_ja,_s,_e,_ni,_ja,_dot,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_JE,_j,_col_,_ne,__s,_mo,_t,_ri,_te,__,_na,_ret
		.BYTE	_m,_en,_ja_,_ta,_k,_col_,_je,_to,__,_N,_E,__,_M,_O,_JA,__v,_i,_na,_exc_quo,_eol
_scF_msg01:
		.BYTE	_Kanjeda,_ddt__quo,_JE,_to,__i_,_e,_s,_t_mz,__,_de,_t,_s,_ka,_ja,_que_quo,_eol
_scF_msg02:
		.BYTE	_JE,_to,__,_to,_t,__s,_a,_m,_ji,_j,__,_m,_a,_l,_mz,_ch,_i,_k,_exc,_eol
_scF_msg03:
		.BYTE	_D,_ru,_z,_mz,_ja_,_m,_a,_l,_mz,_ch,_i,_ka,_que,_eol
_scF_msg04:
		.BYTE	_P,_o,_l,_ko,_v,_ni,_k,_ddt__quo,_U,_b,_e,_ri,_te,__,_de,_te,_j,_ret
		.BYTE	_o,_t,_s,_ju,_da,_col_,_s,_e,_j,_ch,_a,_s,__,_zh,_e,_exc_quo,_eol
_scF_msg05:
		.BYTE	_Tjecuo,_ddt__quo,_Kanjeda,_que,_ret
		.BYTE	_dot_dot_dot,_P,_o,_ch,_e,_m,_u,__,_t,_ji,__,_z,_de,_s,_mz,_que_quo,_eol
_scF_msg06:
		.BYTE	_Kanjeda,_ddt__quo,_Tjecuo,_col_,_t,_ji,__v,__,_po,_r,_ja,_d,_k,_e,_que,_ret
		.BYTE	_JA,__p,_ri,_sh,_jo,_l,__s,_p,_a,_st,_i,__,_te,_b,_ja,_exc_quo,_eol
_scF_msg1A:
		.BYTE	_Kanjeda,_ddt__quo,_an0,_S,_ko,_re,_e,_col_,_na,_d,_o,__b,_e,_zh,_a,_t_mz,_col,_ret
		.BYTE	_i,_di,_o,_t,_exc,_aof,_quo,_eol
_scF_msg07:
		.BYTE	_Tjecuo,_ddt__quo,_an1,_V,_s,_jo,__v,__,_po,_r,_ja,_d,_k,_e,_col_,_Kanjeda,_dot,_ret
		.BYTE	_B,_o,_l,_mz,_sh,_e_,_te,_b,_e_,_ne,__,_n,_u,_zh,_no,__,_m,_en,_ja,_ret
		.BYTE	_s,_p,_a,_s,_a,_t_mz,_dot,__,_O,_t,_n,_ji,_ne,_col_,_ja_,_b,_u,_d,_u,_ret
		.BYTE	_s,_p,_a,_s,_a,_t_mz,__,_te,_b,_ja,_dot_dot_dot,_aof,_quo,_eol
_scF_msg1B:
		.BYTE	_Kanjeda,_ddt__quo,_an0,_CH,_to,_que,__,_CH,_to,__,_t,_ji,__,_vo,_o,_b,_sch,_e,_ret
		.BYTE	_ne,_s,_jo,_sh,_mz,_que,_exc,_aof,_quo,_eol
_scF_msg1C:
		.BYTE	_Tjecuo,_ddt__quo,_an1,_H,_e,_h,_dot_dot_dot,__,_T,_a,_k,__,_t,_ji,__,_ne,_ret
		.BYTE	_po,_ni,_m,_a,_e,_sh,_mz,_que,_dot,_dot,__,_T,_ji,__,_z,_li,_sh,_mz,_s_ja,_que,_ret
		.BYTE	_CH,_to,__,_t,_ji,__,_na,_me,_re,_n,__,_de,_la,_t_mz,__,_da,_l,_mz,_sh,_e,_col,_ret
		.BYTE	_Kanjeda,_que,_aof,_quo,_eol
_scF_msg08:
		.BYTE	_Tjecuo,_ddt__quo,_Kanjeda,_col_,_ch,_to,__,_t,_ji,__,_ta,_m,_ret
		.BYTE	_t,_ja,_v,_ka,_e,_sh,_mz,_que_quo,_eol
_scF_msg09:
		.BYTE	_Tjecuo,_ddt__quo,_an1,_CH,_to,__,_t,_ji,__,_de,_la,_e,_sh,_mz,_que,_exc,_aof,_quo,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_an0,_A,_h,_dot_dot_dot,__,_A,_u,_exc,_aof,_quo,_ret
		.BYTE	_ret
		.BYTE	_B,_u,_m,_exc,_eol
_scF_msg0A:
		.BYTE	_Kanjeda,__,_po,_te,_r,_ja,_l,__s,_o,_z,_na,_ni,_e,_dot_dot_dot,_ret
		.BYTE	_ret
		.BYTE	_Kej,_ddt__quo,_Kanjeda,_dot_dot_dot,_quo,_eol
_scF_msg92:
		.BYTE	_Tjecuo,_ddt__quo,_an0,_A,_str,_h,_a,_str,_h,_a,_str,_h,_a,_str,_h,_a,_str,_h,_a,_dot_dot_dot,_aof,_quo,_eol
_scF_msg0D:
		.BYTE	_Tjecuo,__,_ra,_z,_ru,_sh,_i,_l_,_po,_to,_lo,_k,__v,_ret
		.BYTE	_de,_t,_s,_ko,_j,__i_,_i,_s,_p,_a,_ri,_l,_s_ja,_dot,__,_I,__,_to,_l,_mz,_ko,_ret
		.BYTE	_e,_go,__s,_me,_h,__,_o,_st,_a,_l,_s_ja,__,_g,_u,_l,_ja,_t_mz,__,_je,_h,_o,_m,_ret
		.BYTE	_s,_re,_di,__,_st,_en,_dot,_eol
_scF_msg1D:
		.BYTE	_Tjecuo,_ddt__quo,_CH,_to,__,_je,_to,_que,__,_JE,_ta,__s,_i,_la,_ret
		.BYTE	_de,_j,_st,_v,_i,_te,_l,_mz,_no,__,_mo,_ja,_que,_exc_quo,_eol
_scF_msg0E:
		.BYTE	_K,_i,_jo,_ko,_ddt__quo,_an0,_JE,_to,__,_u,_zh,_a,_s,_no,_exc,__,_JA,__,_ne,_ret
		.BYTE	_d,_u,_m,_a,_la,_col_,_ch,_to,__,_o,_n,__,_ta,_k,__s,_i,_l,_jo,_n,_dot_dot_dot,_aof,_quo,_eol
_scF_msg0F:
		.BYTE	_P,_o,_l,_ko,_v,_ni,_k,_ddt__quo,_an0,_K,_a,_k,__,_o,_n,__s,_mo,_g,_ret
		.BYTE	_o,_b,_re,_st,_i,__,_ta,_k,_u,_ju,__s,_i,_l,_u,__,_za,__,_ta,_ko,_e,_ret
		.BYTE	_ko,_ro,_t,_ko,_e,__v,_re,_m,_ja,_que,_exc,__,_N,_a,_j,_di,_te,__,_e,_go,_exc,_aof,_quo,_eol
_scF_msg1F:
		.BYTE	_P,_o,_l,_ko,_v,_ni,_k,_ddt__quo,_an0,_O,_n,__s,_l,_e,_d,_u,_e,_t,__,_na,_ret
		.BYTE	_za,_p,_a,_d,__,_k,__,_O,_li,_m,_p,_i,_j,_s,_ko,_j,__,_st,_ro,_j,_k,_e,_exc,_ret
		.BYTE	_V,_ji,_s,_ji,_la,_j,_te,__v,_s,_e,__s,_i,_l,_ji,__v,__,_po,_go,_n,_ju,_col,_ret
		.BYTE	_po,_p,_ji,_ta,_j,_te,_s,_mz_,_e,_go,__s,_h,_va,_ti,_t_mz,_exc,_aof,_quo,_eol
_scF_msg1E:
		.BYTE	_P,_o,_l,_ko,_v,_ni,_k,_ddt__quo,_an0,_E,_s,_li,__,_ne,__,_po,_l,_u,_ch,_i,_t,_s_ja,_col,_ret
		.BYTE	_u,_b,_e,_j,_te,__,_e,_go,_exc,_aof,_quo,_eol
_scF_msg10:
		.BYTE	_K,_i,_jo,_ko,_ddt__quo,_an0,_P,_re,_k,_ra,_ti,_dot_dot_dot,__,_B,_o,_l,_mz,_sh,_e_,_ne,_ret
		.BYTE	_p,_ri,_ch,_i,_n,_ja,_j,__,_ni,_ko,_m,_u,__v,_re,_da,_dot_dot_dot,_aof,_quo,_ret
		.BYTE	_ret
		.BYTE	_Tjecuo,_ddt__quo,_G,_de,__,_A,_ki,_ra,_que,_exc_quo,_ret
		.BYTE	_ret
		.BYTE	_K,_i,_jo,_ko,_ddt__quo,_an0,_JA,__,_ne,__s,_dot_dot_dot,_aof,_quo,_eol
_scF_msg0C:
		.BYTE	_Tjecuo,_ddt__quo,_dot_dot_dot,_P,_o,_g,_re,_b,_jo,_n,__,_po,_d,_ret
		.BYTE	_ne,_za,_ko,_n,_ch,_en,_n,_ji,_m,__,_O,_li,_m,_p,_i,_j,_s,_ki,_m,_ret
		.BYTE	_st,_a,_di,_o,_no,_m,_que_quo,_ret
		.BYTE	_ret
		.BYTE	_K,_i,_jo,_ko,_ddt__quo,_an0,_N,_e,_t,_exc,__,_A,_ki,_ra,_dot_dot_dot,_ret
		.BYTE	_P,_o,_d,_o,_zh,_di,_exc,__,_A,_str,_a,_exc,_aof,_quo,_eol
_scF_msg11:
		.BYTE	_Kej,__b,_e,_z,_u,_ch,_a,_st,_no,__,_po,_s,_mo,_t,_re,_la,__,_na,_ret
		.BYTE	_de,_te,_j,_dot,_eol
_scF_msg12:
		.BYTE	_Kanjeda,_ddt__quo,_H,_a,_col_,_d,_o,_h,_la,_ja_,_k,_r,_ji,_s,_a,_dot,_ret
		.BYTE	_N,_a,_ve,_r,_no,_e,_col_,_po,_d,_c,_e,_p,_i,_l_,_e,_jo,_col_,_ko,_g,_da,_ret
		.BYTE	_n,_ji,_r,_ja,_l,__v,__,_ka,_na,_li,_za,_c,_i,_ju,_dot,_quo,_eol
_scF_msg13:
		.BYTE	_P,_o,_l,_ko,_v,_ni,_k,_ddt__quo,_JE,_j,_col_,_p,_a,_re,_n,_mz,_exc,__,_K,_a,_k,_ret
		.BYTE	_t,_ji,__,_e,_go,__,_d,_o,_st,_a,_l,_que,_exc_quo,_eol
_scF_msg14:
		.BYTE	_P,_o,_l,_ko,_v,_ni,_k,_ddt__quo,_CH,_to,__v,_ji,__s,_to,_i,_te,_que,_ret
		.BYTE	_B,_ji,_st,_ro,_col_,_lo,_v,_i,_te,__,_e,_go,_exc_quo,_eol
_scF_msg15:
		.BYTE	_P,_o,_l,_ko,_v,_ni,_k,_ddt__quo,_JE,_j,_col_,_p,_a,_re,_n,_mz,_exc,__,_K,_a,_k,_ret
		.BYTE	_t,_ji,__s,_ju,_da,__,_po,_p,_a,_l,_que,_exc_quo,_eol
_scF_msg16:
		.BYTE	_JA,__,_po,_p,_ji,_ta,_l,_s_ja,__,_za,_go,_vo,_ri,_t_mz,__s,_ret
		.BYTE	_re,_b,_jo,_n,_ko,_m,_dot_dot_dot,_eol
_scF_msg17:
		.BYTE	_N,_o,__,_re,_b,_jo,_no,_k,__,_mo,_l,_ch,_a,_l,_dot,_eol
_scF_msg18:
		.BYTE	_N,_o,__,_re,_b,_jo,_no,_k,__,_to,_l,_mz,_ko,__,_g,_la,_z,_e,_l_,_na,_ret
		.BYTE	_Kej,_col_,_o,_t,_ka,_z,_ji,_va,_ja,_s,_mz_,_o,_t,_ve,_ch,_a,_t_mz,_dot,_ret
		.BYTE	_ret
		.BYTE	_Kej,_ddt__quo,_T,_ji,_dot_dot_dot,_quo,_eol
_scF_msg19:
		.BYTE	_K,_i,_jo,_ko,_ddt__quo,_an0,_V,_e,_r,_no,_dot,_aof,_quo,_eol

		SECTION_END		FF

