
		SECTION_START	FA

		MSG_START	_sceneA_msg_lib
		MSG_IDX	_scA_msg00
		MSG_IDX	_scA_msg01
		MSG_IDX	_scA_msg02
		MSG_IDX	_scA_msg03
		MSG_IDX	_scA_msg04
		MSG_IDX	_scA_msg05
		MSG_IDX	_scA_msg06
		MSG_IDX	_scA_msg07
		MSG_IDX	_scA_msg08
		MSG_IDX	_scA_msg09
		MSG_IDX	_scA_msg0A
		MSG_IDX	_scA_msg0B
		MSG_IDX	_scA_msg0C
		MSG_IDX	_scA_msg0D
		MSG_IDX	_scA_msg0E
		MSG_IDX	_scA_msg0F
		MSG_IDX	_scA_msg10
		MSG_IDX	_scA_msg11
		MSG_IDX	_scA_msg12
		MSG_IDX	_scA_msg13
		MSG_IDX	_scA_msg14
		MSG_IDX	_scA_msg15
		MSG_IDX	_scA_msg17
		MSG_IDX	_scA_msg18
		MSG_IDX	_scA_msg19
		MSG_IDX	_scA_msg1A
_scA_msg00:
		.BYTE	_M,_en,_ja_,_za,_p,_e,_r,_li,__v,__,_te,_s,_no,_va,_to,_m,_ret
		.BYTE	_po,_me,_sch,_e,_ni,_i,_dot,_eol
_scA_msg01:
		.BYTE	_JE,_to,__,_va,_n,_na,_ja_,_ko,_m,_na,_ta,_dot,_eol
_scA_msg02:
		.BYTE	_O,_t,_k,_u,_da,__v,_ji,__v,_z,_ja,_li,_col_,_ch,_to,__,_ja_,_sh,_p,_i,_o,_n,_col,_ret
		.BYTE	_p,_ri,_d,_u,_r,_ki,_que,_exc,_eol
_scA_msg03:
		.BYTE	_Kej,_col_,_na,__,_je,_to,_t,__,_ra,_z,__,_ja_,_u,_zh,__,_to,_ch,_no,_ret
		.BYTE	_p,_ri,_g,_la,_sh,_u,__,_te,_b,_ja_,_na,__s,_v,_i,_da,_ni,_e,_dot,_eol
_scA_msg04:
		.BYTE	_I,_h,__,_po,_ve,_de,_ni,_e_,_i,_z,_me,_ni,_lo,_s,_mz,__i_,_o,_ni,_ret
		.BYTE	_st,_a,_li,__p,_re,_s,_l,_e,_d,_o,_va,_t_mz,__,_Kej,_dot,_ret
		.BYTE	_P,_o,_h,_o,_zh,_e,_col_,_te,_r,_ro,_ri,_st,_ji,__,_me,_ti,_li,__,_vo,_ret
		.BYTE	_ch,_to,_str,_to,__,_o,_ch,_en,_mz_,_s,_e,_r,_mz,_e,_z,_no,_e,_dot,_eol
_scA_msg05:
		.BYTE	_quo,_JE,_k,_s,_p,_e,_ri,_m,_en,_ta,_l,_mz,_n,_ji,_j,__,_o,_b,_tz,_e,_k,_t,_quo,_que,_ret
		.BYTE	_K,_u,_da,_col_,_ch,_jo,_r,_t,__,_po,_b,_e,_ri,_col_,_o,_ni,__,_za,_b,_ra,_li,_ret
		.BYTE	_Tjecuo,_que,_eol
_scA_msg06:
		.BYTE	_JE,_to,__,_va,_n,_na,_dot,_eol
_scA_msg17:
		.BYTE	_V,__s,_l,_e,_d,_u,_ju,_sch,_i,_j,__,_ra,_z,__,_m,_ji,__,_d,_o,_l,_zh,_n,_ji,__b,_ji,_t_mz,_ret
		.BYTE	_t,_u,_t,__v,_me,_st,_e,_col_,_Kej,_exc,__,_R,_str,_r,_str,_m,_ja,_u,_dot_dot_dot,_eol
_scA_msg08:
		.BYTE	_JE,_to,__v,_en,_ti,_l,_ja,_c,_i,_o,_n,_na,_ja_,_s,_i,_st,_e,_m,_a,_dot,_eol
_scA_msg09:
		.BYTE	_Kanjeda,_ddt__quo,_P,_i,_vo,_exc,__,_I,__,_h,_o,_lo,_d,_no,_e,_exc_quo,_eol
_scA_msg10:
		.BYTE	_JE,_to,__,_ja,_sch,_i,_k,__p,_i,_va,_dot,_eol
_scA_msg0A:
		.BYTE	_K,_a,_ne,_da,_ddt__quo,_P,_i,_vo,__,_je,_ti,_h,__,_u,_ro,_d,_o,_v,_col,_ret
		.BYTE	_z,_na,_ch,_i,_t,__p,_mz,_e,_m,__,_d,_o,__,_d,_na,_exc,_ret
		.BYTE	_G,_de,__,_zh,_e_,_o,_t,_k,_r,_ji,_va,_sh,_ka,_dot_dot_dot,_ret
		.BYTE	__,__,__,_dot_dot_dot,_N,_e,_t,__,_o,_t,_k,_r,_ji,_va,_sh,_ki,_dot_dot_dot,_ret
		.BYTE	_K,_a,_k,__b,_ji,__,_m,_ne,__s,_ko,_v,_ji,_r,_n,_u,_t_mz,__,_k,_r,_ji,_sh,_k,_u,_dot,_quo,_eol
_scA_msg0B:
		.BYTE	_K,_a,_ne,_da,_ddt__quo,_V,_o,_t,__,_t,_u,_t,__v,_ro,_de,_ret
		.BYTE	_po,_d,_h,_o,_d,_ja,_sch,_e,_e_,_me,_s,_to,_exc,__,_N,_u,_str,_ka,_dot_dot_dot,_quo,_eol
_scA_msg0C:
		.BYTE	_SH,_po,_n,_exc,__,_B,_a,_m,_exc,_ret
		.BYTE	_ret
		.BYTE	_V,_en,_ti,_l,_ja,_c,_i,_ja_,_o,_t,_k,_r,_ji,_ta,_exc,_ret
		.BYTE	_ret
		.BYTE	_P,_o,_h,_o,_zh,_e,_col_,_ja_,_s,_mo,_g,_u,__v,_ji,_b,_ra,_t_mz,_s_ja,_ret
		.BYTE	_o,_t,_s,_ju,_da,_dot,_eol
_scA_msg0D:
		.BYTE	_D,_z,_ji,_n,_k,_col_,_d,_z,_ji,_n,_k,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_H,_m,_str,_m,_col_,_ne,_t,_col_,_t,_u,_t,__,_ne,_ret
		.BYTE	_po,_l,_u,_ch,_i,_t,_s_ja,_dot,_quo,_eol
_scA_msg0E:
		.BYTE	_JA,__,_za,_b,_ra,_l,_s_ja,__v,__,_vo,_z,_d,_u,_h,_o,_vo,_d,_dot,_eol
_scA_msg0F:
		.BYTE	_dot_dot_dot,_JA,__,_u,_s,_n,_u,_l,_dot,_eol
_scA_msg11:
		.BYTE	_K,_a,_ne,_da,_ddt__quo,_B,_li,_n,_col_,_t,_u,_t,__,_ni,_ch,_e,_go,_ret
		.BYTE	_ne,_t,_dot,_quo,_eol
_scA_msg12:
		.BYTE	_Kanjeda,_ddt__quo,_V,_ji,_g,_l,_ja,_di,_t,__,_te,_s,_no,_va,_to,_dot,_quo,_eol
_scA_msg13:
		.BYTE	_Kanjeda,_ddt__quo,_JA,__p,_ro,_b,_ra,_l,_s_ja,__v,_ret
		.BYTE	_v,_en,_ti,_l,_ja,_c,_i,_ju,__v,__s,_o,_s,_e,_d,_ne,_m,_ret
		.BYTE	_po,_me,_sch,_e,_ni,_i,_dot_dot_dot,_quo,_eol
_scA_msg14:
		.BYTE	_JA,__s,_l,_ji,_sh,_u,__,_go,_lo,_s,_a,_dot,__,_JE,_to,__,_R,_ju,__,_i,_ret
		.BYTE	_te,_r,_ro,_ri,_st,_ji,_dot_dot_dot,_eol
_scA_msg07:
		.BYTE	_Kanjeda,_ddt__quo,_O,_ni,__,_go,_vo,_r,_ja,_t,__,_o,__,_Tjecuo,_exc_quo,_eol
_scA_msg1A:
		.BYTE	_O,__,_ch,_jo,_m,__,_o,_ni,__,_te,_p,_e,_r,_mz_,_ta,_m,__,_go,_vo,_r,_ja,_t,_col,_ret
		.BYTE	_ne,__,_mo,_g,_u,__,_ra,_z,_o,_b,_ra,_t_mz,_que,_eol
_scA_msg15:
		.BYTE	_T,_a,_m,__,_ja_,_s,_mo,_g,_u,__v,_ji,_b,_ra,_t_mz,_s_ja,_dot,_eol
_scA_msg18:
		.BYTE	_SH,_m,_ja,_k,_exc,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_CH,_jo,_r,_t,_exc_quo,_eol
_scA_msg19:
		.BYTE	_T,_e,_r,_ro,_ri,_st,_ddt__quo,_K,_to,__,_z,_de,_s,_mz,_que,_exc_quo,_eol

		SECTION_END		FA
