
		SECTION_START	F1

		MSG_START	_scene1_msg_lib
		MSG_IDX	_sc1_msg0B
		MSG_IDX	_sc1_msg0C
		MSG_IDX	_sc1_msg0D
		MSG_IDX	_sc1_msg0E
		MSG_IDX	_sc1_msg0F
		MSG_IDX	_sc1_msg10
		MSG_IDX	_sc1_msg11
		MSG_IDX	_sc1_msg12
		MSG_IDX	_sc1_msg13
		MSG_IDX	_sc1_msg14
		MSG_IDX	_sc1_msg15
		MSG_IDX	_sc1_msg16
		MSG_IDX	_sc1_msg17
		MSG_IDX	_sc1_msg18
		MSG_IDX	_sc1_msg1A
		MSG_IDX	_sc1_msg1B
		MSG_IDX	_sc1_msg1C
		MSG_IDX	_sc1_msg1D
		MSG_IDX	_sc1_msg1E
		MSG_IDX	_sc1_msg1F
		MSG_IDX	_sc1_msg20
		MSG_IDX	_sc1_msg21
		MSG_IDX	_sc1_msg22
		MSG_IDX	_sc1_msg23
		MSG_IDX	_sc1_msg24
		MSG_IDX	_sc1_msg25
		MSG_IDX	_sc1_msg27
		MSG_IDX	_sc1_msg28
		MSG_IDX	_sc1_msg29
		MSG_IDX	_sc1_msg2A
		MSG_IDX	_sc1_msg2B
		MSG_IDX	_sc1_msg2C
		MSG_IDX	_sc1_msg2D
		MSG_IDX	_sc1_msg31
		MSG_IDX	_sc1_msg32
		MSG_IDX	_sc1_msg80
		MSG_IDX	_sc1_msg81
		MSG_IDX	_sc1_msgB9
_sc1_msgB9:
		.BYTE	_N,_a,__s,_l,_e,_d,_u,_ju,_sch,_i,_j,__,_de,_n,_mz_,_na,_s,__p,_ri,_ve,_li,_ret
		.BYTE	_na,__,_po,_l,_e,_vo,_e_,_vo,_en,_no,_e,__s,_l,_e,_d,_st,_v,_i,_e,_dot,_eol
_sc1_msg0B:
		.BYTE	_V,_oennji,_j,_ddt__quo,_an0,_T,_a,_k,__,_ch,_e,_m,__v,_ji,__v,_s,_jo,_str,_ta,_ki,_ret
		.BYTE	_za,_ni,_m,_a,_li,_s,_mz_,_v,__,_to,_m,__,_me,_st,_e,_que,_aof,_quo,_eol
_sc1_msg0C:
		.BYTE	_Kanjeda,_ddt__quo,_M,_ji,__,_po,_e,_h,_a,_li,__,_na,__,_na,_sh,_i,_h,_ret
		.BYTE	_b,_a,_j,_ka,_h,__,_po,_s,_re,_di,__,_no,_ch,_i,_col_,_ch,_to,_b,_ji,_ret
		.BYTE	_po,_v,_i,_da,_t_mz,__,_mo,_ju,__s,_me,_r,_te,_l,_mz,_no,_ret
		.BYTE	_b,_o,_l,_mz,_n,_u,_ju,__,_m,_a,_t_mz,_col_,_no,__,_na,__,_na,_s,__,_na,_p,_a,_li,_ret
		.BYTE	_K,_lo,_u,_n,_ji,__i_,_o,_di,_n,__,_i,_z,__,_mo,_i,_h,__,_d,_ru,_z,_e,_j,_ret
		.BYTE	_po,_st,_ra,_da,_l,_col_,_po,_je,_to,_m,_u,__,_ja_,_ne,_m,_no,_go,_ret
		.BYTE	_ra,_z,_o,_z,_li,_l,_s_ja,_dot_dot_dot,_quo,_eol
_sc1_msg0D:
		.BYTE	_V,_oennji,_j,_ddt__quo,_an0,_N,_e,_m,_no,_go,__,_ra,_z,_o,_z,_li,_l,_s_ja,_que,_ret
		.BYTE	_V,_o,_t,__,_po,_ch,_e,_m,_u,__,_vo,_s,_e,_m,_mz_,_K,_lo,_u,_no,_v,_ret
		.BYTE	_s,_e,_j,_ch,_a,_s,__,_l,_e,_zh,_a,_t,__v,__b,_o,_l,_mz,_ni,_c,_e,_que,_ret
		.BYTE	_Z,_a,_n,_ja,_t,_no,_dot,__,_A,__,_t,_vo,_ja_,_quo,_s,_me,_r,_te,_l,_mz,_no,_ret
		.BYTE	_b,_o,_l,_mz,_na,_ja,_quo,__,_m,_a,_t_mz,_col_,_ka,_k,__,_o,_na,_que,_aof,_quo,_eol
_sc1_msg0E:
		.BYTE	_Kanjeda,_ddt__quo,_K,__s,_ch,_a,_s,_t_mz,_ju,_col_,_h,_u,_d,_sh,_e,_e,_ret
		.BYTE	_u,_zh,_e_,_po,_za,_di,_col_,_o,_na,__p,_re,_o,_d,_o,_l,_e,_la,_ret
		.BYTE	_b,_a,_r,_mz,_e,_r,_dot,_quo,_eol
_sc1_msg0F:
		.BYTE	_V,_oennji,_j,_ddt__quo,_an0,_P,_re,_o,_d,_o,_l,_e,_la,__b,_a,_r,_mz,_e,_r,_que,_ret
		.BYTE	_H,_m,_col_,_ch,_to,__,_da,_l,_mz,_sh,_e,_col_,_t,_ri,_a,_t,_lo,_n,_que,_aof,_quo,_eol
_sc1_msg11:
		.BYTE	_JE,_to,__v,_oennji,_j,__s,_l,_e,_d,_o,_va,_te,_l,_mz,_dot,_eol
_sc1_msg12:
		.BYTE	_JE,_to,__,_ja,_exc,_eol
_sc1_msg13:
		.BYTE	_JE,_to,__,_na,_sh,_i,__,_vo,_di,_te,_l,_mz,_s,_ki,_e,__p,_ra,_va,_dot,_ret
		.BYTE	_O,_s,_to,_ro,_zh,_ne,_e,__s,__,_ni,_m,_i,_dot,_eol
_sc1_msg14:
		.BYTE	_P,_o,_h,_o,_zh,_e_,_na,__s,_p,_i,_s,_o,_k,__,_i,_z,_ve,_st,_n,_ji,_h,_ret
		.BYTE	_te,_r,_ro,_ri,_s,_to,_v,_dot,_ret
		.BYTE	_ret
		.BYTE	_Z,_a,_ch,_e,_m,__,_na,_s,__,_ta,_m,__,_i,_s,_ka,_t_mz,_col_,_to,_l,_mz,_ko,_ret
		.BYTE	_p,_u,_st,_a,_ja_,_t,_ra,_ta,__v,_re,_me,_ni,_dot,__,_V,_r,_ja,_d,__,_li,_ret
		.BYTE	_m,_ji,__v,__,_n,_jo,_m,__,_e,_s,_t_mz,_dot,_eol
_sc1_msg16:
		.BYTE	_M,_o,_i,__,_d,_ru,_z,_mz,_ja,_exc,__,_M,_ji,__s,_a,_m,_a,_ja_,_k,_ru,_ta,_ja,_ret
		.BYTE	_b,_a,_n,_da,_exc,_eol
_sc1_msg17:
		.BYTE	_JE,_to,__,_mo,_jo,__,_li,_c,_o,_dot,_eol
_sc1_msg18:
		.BYTE	_Kanjeda,_ddt__quo,_G,_o,_s,_po,_di,_col_,_m,_i,_st,_e,_r,_dot_dot_dot,_ret
		.BYTE	_A,__,_ch,_to,__,_V,_JI,__,_de,_la,_li,__v,__,_to,_m,__,_me,_st,_e,_ret
		.BYTE	_p,_ro,_sh,_lo,_j,__,_no,_ch,_mz,_ju,_que_quo,_eol
_sc1_msg1A:
		.BYTE	_JE,_to,__,_JA,_m,_a,_g,_a,_ta,_dot,_eol
_sc1_msg1F:
		.BYTE	_JA,_m,_a,_g,_a,_ta,_ddt__quo,_JE,_h,_col_,_b,_ji,_lo,__b,_ji,__,_u,__,_na,_s,_ret
		.BYTE	_ch,_u,_t_mz,__b,_o,_l,_mz,_sh,_e,__v,_re,_me,_ni,__p,_ro,_sh,_lo,_j,_ret
		.BYTE	_no,_ch,_mz,_ju,_col_,_m,_ji,__b,_ji,__,_ra,_z,_da,_v,_i,_li,__,_je,_ti,_h,_ret
		.BYTE	_K,_lo,_u,_no,_v,_dot,_quo,_eol
_sc1_msg1B:
		.BYTE	_JE,_to,__,_Kaj,_dot,_eol
_sc1_msg20:
		.BYTE	_Kaj,_ddt__quo,_A,_g,_a,_col_,_za,_b,_a,_v,_no,_col_,_m,_i,_st,_e,_r,_dot,_ret
		.BYTE	_T,_a,_k,__,_k,_u,_da,__v,_ji,__,_za,_b,_ra,_li,__,_Tjecuo,_que_quo,_eol
_sc1_msg1C:
		.BYTE	_JE,_to,__,_K,_u,_va,_ta,_dot,_eol
_sc1_msg1D:
		.BYTE	_JE,_to,__,_V,_a,_ta,_na,_b,_e,_dot,_eol
_sc1_msg1E:
		.BYTE	_JE,_to,__,_T,_a,_k,_e,_ja,_m,_a,_dot,_eol
_sc1_msg21:
		.BYTE	_V,_oennji,_j,_ddt__quo,_an0,_JE,_j,_exc,__,_N,_e,_ret
		.BYTE	_o,_t,_vo,_ra,_ch,_i,_va,_j,_s_ja,_exc,_aof,_quo,_eol
_sc1_msg22:
		.BYTE	_V,_oennji,_j,_ddt__quo,_an0,_V,_ji,__,_to,_ch,_no,__,_ne,_ret
		.BYTE	_te,_r,_ro,_ri,_st,_ji,_que,_aof,_quo,_eol
_sc1_msg23:
		.BYTE	_Kanjeda,_ddt__quo,_T,_o,_ch,_no,__,_ne,_t,_exc,__,_M,_ji,__v,_s,_e,_go,_ret
		.BYTE	_li,_sh,_mz_,_b,_a,_n,_da,__,_k,_ru,_t,_ji,_h,__p,_a,_r,_ne,_j,_dot,_quo,_eol
_sc1_msg24:
		.BYTE	_Kanjeda,_ddt__quo,_JE,_j,_col_,_m,_i,_st,_e,_r,_col_,_a,__,_t,_ji,_ret
		.BYTE	_s,_i,_m,_p,_a,_ti,_ch,_n,_ji,_j,_exc_quo,_eol
_sc1_msg25:
		.BYTE	_Kanjeda,_ddt__quo,_JE,_j,_col_,_m,_i,_st,_e,_r,_col_,_u,__,_te,_b,_ja,_ret
		.BYTE	_sh,_i,_ri,_n,_ka,__,_ra,_s,_st,_jo,_g,_n,_u,_ta,_dot,_quo,_eol
_sc1_msg27:
		.BYTE	_JE,_to,_col_,_d,_o,_l,_zh,_no,__b,_ji,_t_mz,_col_,_s,_p,_i,_s,_o,_k,_ret
		.BYTE	_i,_z,_ve,_st,_n,_ji,_h,__,_te,_r,_ro,_ri,_s,_to,_v,_dot_dot_dot,_ret
		.BYTE	_ret
		.BYTE	_O,_col_,_t,_u,_t,__,_da,_zh,_e_,_e,_s,_t_mz,__,_de,_v,_u,_sh,_ki,_exc,_ret
		.BYTE	_O,_h,_col_,_a,__,_je,_ta,__,_h,_o,_ro,_sh,_en,_mz,_ka,_ja,_exc,_ret
		.BYTE	_ret
		.BYTE	_I,_n,_te,_re,_s,_no,_col_,_ka,_k,__,_e,_jo,__,_z,_o,_v,_u,_t,_dot_dot_dot,_eol
_sc1_msg28:
		.BYTE	_Kanjeda,_ddt__quo,_JE,_j,_col_,_v,_ji,__,_mo,_zh,_e,_te,_ret
		.BYTE	_s,_ka,_za,_t_mz,_col_,_ka,_k,__,_z,_o,_v,_u,_t,__,_je,_t,_u,_ret
		.BYTE	_de,_v,_u,_sh,_k,_u,_que_quo,_eol
_sc1_msg29:
		.BYTE	_Kanjeda,_ddt__quo,_A,__,_g,_de,__,_o,_na,__,_zh,_i,_v,_jo,_t,_que_quo,_eol
_sc1_msg2A:
		.BYTE	_Kanjeda,_ddt__quo,_JE,_j,_col_,_s,_ka,_zh,_i,_te,__,_h,_o,_t,_ja_,_b,_ji,_ret
		.BYTE	_e,_jo,__,_no,_me,_r,__,_te,_l,_e,_f,_o,_na,_col_,_n,_u,__,_i,_li,_ret
		.BYTE	_h,_o,_t_mz,__,_ch,_to,_str,_to,_exc,__,_U,_mo,_l,_ja,_ju,_exc_quo,_eol
_sc1_msg2B:
		.BYTE	_V,_oennji,_j,_ddt__quo,_an0,_E,_s,_li,__b,_ji,__,_u,__,_na,_s,__b,_ji,_li,_ret
		.BYTE	_ta,_ki,_e_,_da,_n,_n,_ji,_e,_col_,_m,_ji,__b,_ji,__,_e,_jo,__,_ne,_ret
		.BYTE	_ra,_z,_ji,_s,_ki,_va,_li,_exc,_aof,_quo,_eol
_sc1_msg2C:
		.BYTE	_S,_e,_k,_re,_ta,_r,_mz,_ddt__quo,_an1,_P,_o,_h,_o,_zh,_e,_col_,_je,_ti,_ret
		.BYTE	_b,_o,_l,_va,_n,_ji,__,_ni,_ka,_k,__,_ne,__s,_v,_ja,_za,_n,_ji,__s,_ret
		.BYTE	_te,_r,_ro,_ri,_st,_a,_m,_i,_dot,_aof,_quo,_eol
_sc1_msg15:
		.BYTE	_V,_oennji,_j,_ddt__quo,_an0,_JE,_to,__i_,_ta,_k,__,_po,_n,_ja,_t,_no,_ret
		.BYTE	_po,__,_i,_h,__v,_i,_d,_u,_dot_dot_dot,__,_D,_o,_p,_ro,_s,__,_o,_ko,_n,_ch,_en,_dot,_ret
		.BYTE	_ret
		.BYTE	_P,_o,_d,_o,_zh,_di,_te,__s,_na,_ru,_zh,_i,_dot,_ret
		.BYTE	_ret
		.BYTE	_S,_l,_e,_d,_u,_ju,_sch,_i,_e,_exc,_aof,_quo,_eol
_sc1_msg2D:
		.BYTE	_Kanjeda,_ddt__quo,_S,_mo,_t,_ri,_str,_ka,_col_,_o,_n,_ret
		.BYTE	_po,_sh,_u,_ti,_l,_exc,__,_H,_a,_str,_h,_a,_str,_h,_a,_dot_dot_dot,_quo,_eol
_sc1_msg10:
		.BYTE	_Kanjeda,_ddt__quo,_JE,_j,_col_,_ja_,_go,_lo,_de,_n,_dot,_quo,_eol
_sc1_msg32:
		.BYTE	_S,_te,_n,_ji,__,_ko,_m,_na,_t,__,_d,_l,_ja_,_d,_o,_p,_ro,_s,_o,_v,_col,_ret
		.BYTE	_s,_to,_ja,_sch,_i,_h,__,_po,_s,_re,_di,__s,_po,_r,_t,_za,_la,_col,_ret
		.BYTE	_s,_o,_o,_ru,_zh,_en,_ji,__,_i,_z,__,_f,_a,_ne,_r,_ji,_dot,_eol
_sc1_msg31:
		.BYTE	_V,_oennji,_j,_ddt__quo,_an0,_JE,_j,_col_,_mo,_l,_ch,_a,_t_mz,_exc,_aof,_quo,_eol
_sc1_msg80:
		.BYTE	_V,_oennji,_j,_ddt__quo,_M,_o,_l,_ch,_a,_t_mz,_exc_quo,_eol
_sc1_msg81:
		.BYTE	_V,_oennji,_j,_ddt__quo,_an0,_JE,_j,_exc,__,_N,_e,_ret
		.BYTE	_po,_d,_g,_l,_ja,_d,_ji,_va,_t_mz,_exc,_aof,_quo,_eol

		SECTION_END		F1
