
		SECTION_START	FB

		MSG_START	_sceneB_msg_lib
		MSG_IDX	_scB_msg00
		MSG_IDX	_scB_msg01
		MSG_IDX	_scB_msg02
		MSG_IDX	_scB_msg03
		MSG_IDX	_scB_msg05
		MSG_IDX	_scB_msg06
		MSG_IDX	_scB_msg07
		MSG_IDX	_scB_msg08
		MSG_IDX	_scB_msg09
		MSG_IDX	_scB_msg0A
		MSG_IDX	_scB_msg0B
		MSG_IDX	_scB_msg0C
		MSG_IDX	_scB_msg0D
		MSG_IDX	_scB_msg0E
		MSG_IDX	_scB_msg0F
		MSG_IDX	_scB_msg10
		MSG_IDX	_scB_msg11
		MSG_IDX	_scB_msg12
		MSG_IDX	_scB_msg13
_scB_msg00:
		.BYTE	_O,_ni,__v,_ji,_ta,_sch,_i,_li,__,_m,_en,_ja_,_i,_z,_ret
		.BYTE	_vo,_z,_d,_u,_h,_o,_vo,_da,_dot,_eol
_scB_msg01:
		.BYTE	_Kanjeda,_ddt__quo,_JE,_j,_col_,_je,_j,_col_,_je,_j,_exc,__,_CH,_to,__v,_ji,_ret
		.BYTE	_de,_la,_e,_te,_que,_exc_quo,_eol
_scB_msg02:
		.BYTE	_Kej,_ddt__quo,_Kanjeda,_dot_dot_dot,_quo,_eol
_scB_msg03:
		.BYTE	_Kanjeda,_ddt__quo,_S,_to,_j,_te,_exc,__,_O,_d,_n,_u,__s,_e,_k,_u,_n,_d,_u,_col,_ret
		.BYTE	_p,_ro,_sh,_u,_col_,_po,_s,_l,_u,_sh,_a,_j,_te,__,_m,_en,_ja,_dot_dot_dot,_quo,_eol
_scB_msg05:
		.BYTE	_Kanjeda,_ddt__quo,_JE,_to,_t,__s,_l,_u,_ch,_a,_j,__v,__,_S,_ta,_ro,_m,_ret
		.BYTE	_go,_ro,_de,__p,_ro,_i,_z,_o,_sh,_jo,_l,__s,__,_mo,_i,_m,_ret
		.BYTE	_d,_ru,_go,_m,_dot,__,_M,_o,_zh,_e,_te,__,_m,_ne,__,_ne,__v,_e,_ri,_t_mz,_col,_ret
		.BYTE	_no,__,_ja_,_b,_ji,_l_,_ta,_m,__i_,_v,_i,_de,_l,__v,_s,_jo,__s,_ret
		.BYTE	_s,_a,_mo,_go,__,_na,_ch,_a,_la,_exc_quo,_eol
_scB_msg06:
		.BYTE	_Kanjeda,_ddt__quo,_P,_o,_zh,_a,_l,_u,_j,_st,_a,_col_,_vo,_z,_mz,_m,_i,_te,_ret
		.BYTE	_m,_en,_ja_,_s,__s,_o,_b,_o,_j,__v,__,_la,_b,_o,_ra,_to,_ri,_ju,_dot,_quo,_eol
_scB_msg07:
		.BYTE	_Kanjeda,_ddt__quo,_N,_e,_m,_no,_go,__,_ne,_lo,_v,_ko,_ret
		.BYTE	_p,_ro,_s,_i,_t_mz,_dot_dot_dot,_quo,_eol
_scB_msg0A:
		.BYTE	_R,_ju,_ddt__quo,_an1,_H,_o,_ro,_sh,_o,_col_,_t,_ji,__,_i,_d,_jo,_sh,_mz_,_s,__,_na,_m,_i,_dot,_ret
		.BYTE	_V,_o,_t,__p,_ro,_p,_u,_s,_k,__v,__,_la,_b,_o,_ra,_to,_ri,_ju,_dot,_aof,_quo,_eol
_scB_msg0E:
		.BYTE	_JA,__,_i,_d,_u,_col_,_Tjecuo,_exc,_eol
_scB_msg09:
		.BYTE	_Kej,__s,_p,_a,_s,_la,__,_m,_en,_ja_,_b,_e,_z,__,_e,_di,_no,_go,_ret
		.BYTE	_s,_lo,_va,__i_,_p,_ri,_ve,_la,__v,__,_i,_h,__,_ko,_m,_na,_t,_u,_dot,_ret
		.BYTE	_O,_ni,__,_ch,_to,_str,_to,__,_o,_b,_s,_u,_zh,_da,_li,_dot,_eol
_scB_msg0C:
		.BYTE	_Kanjeda,_ddt__quo,_V,_ji,__,_go,_vo,_ri,_te,__,_o,__,_Tjecuo,_que_quo,_eol
_scB_msg08:
		.BYTE	_R,_ju,_ddt__quo,_an1,_CH,_to,_que,_exc,__,_O,_t,_k,_u,_da,__,_t,_ji,__,_z,_na,_e,_sh,_mz,_que,_aof,_quo,_eol
_scB_msg0B:
		.BYTE	_S,_o,_m,_ne,_va,_ju,_s,_mz,_col_,_ch,_to,__,_Kej,__,_ra,_s,_s,_ka,_za,_la,_ret
		.BYTE	_s,_vo,_i,_m,__,_d,_ru,_z,_mz,_ja,_m,__,_o,__,_na,_s,_dot,_eol
_scB_msg0D:
		.BYTE	_T,_o,_t,__,_mo,_r,_sch,_i,_ni,_st,_ji,_j,__,_re,_b,_jo,_no,_k,__,_to,_zh,_e,_ret
		.BYTE	_b,_ji,_l_,_ch,_a,_s,_t_mz,_ju,__,_je,_k,_s,_p,_e,_ri,_m,_en,_ta,_que,_ret
		.BYTE	_A,__,_z,_na,_ch,_i,_t,__i_,_Tjecuo,__,_za,_b,_ra,_li,__v,_ret
		.BYTE	_la,_b,_o,_ra,_to,_ri,_ju,__,_d,_l,_ja,_dot_dot_dot,_eol
_scB_msg0F:
		.BYTE	_T,_e,_r,_ro,_ri,_st,_ddt__quo,_an0,_S,_u,_d,_ja_,_po,__v,_s,_e,_m,_u,_col,_ret
		.BYTE	_v,_oennji,_e,__p,_ri,_k,_r,_ji,_va,_ju,_t,__,_ka,_ki,_e,_str,_to,_ret
		.BYTE	_je,_k,_s,_p,_e,_ri,_m,_en,_t,_ji,__,_na,_d,__,_l,_ju,_d,_mz,_m,_i,_dot,_aof,_quo,_eol
_scB_msg10:
		.BYTE	_T,_e,_r,_ro,_ri,_st,_ddt__quo,_an0,_JE,_to,_t,__p,_ro,_p,_u,_s,_k,_ret
		.BYTE	_d,_o,_l,_zh,_en,__,_po,_z,_vo,_li,_t_mz,__,_na,_m,_ret
		.BYTE	_p,_ro,_ni,_k,_n,_u,_t_mz,__v,__,_la,_b,_o,_ra,_to,_ri,_ju,_dot,_aof,_quo,_eol
_scB_msg11:
		.BYTE	_T,_e,_r,_ro,_ri,_st,_ddt__quo,_an0,_L,_ju,_di,__,_da,_zh,_e_,_ne,_ret
		.BYTE	_po,_d,_o,_z,_re,_va,_ju,_t,_col_,_na,__,_ch,_to,__,_i,_d,_u,_t,__,_i,_h,_ret
		.BYTE	_na,_lo,_g,_i,_dot,__,_E,_s,_li,__b,_ji,__,_m,_ji,__,_na,_sh,_li,_ret
		.BYTE	_d,_o,_ka,_za,_te,_l,_mz,_st,_va,__,_to,_go,_col_,_ch,_to,_ret
		.BYTE	_p,_ra,_v,_i,_te,_l,_mz,_st,_vo,__v,_k,_la,_d,_ji,_va,_e,_t,__,_i,_h,_ret
		.BYTE	_v,__s,_vo,_i,__,_je,_k,_s,_p,_e,_ri,_m,_en,_t,_ji,_dot_dot_dot,_aof,_quo,_eol
_scB_msg12:
		.BYTE	_T,_e,_r,_ro,_ri,_st,_ddt__quo,_an0,_A,_h,__,_t,_ji,__,_go,_v,_n,_ju,_k,_exc,_ret
		.BYTE	_T,_ji,__i_,_p,_ra,_v,_da,__,_sh,_p,_i,_o,_n,_exc,_aof,_quo,_eol
_scB_msg13:
		.BYTE	_Kej,_ddt__quo,_an2,_O,_t,_k,_u,_da,__,_u,__,_te,_b,_ja_,_vo,_o,_b,_sch,_e,_ret
		.BYTE	_ka,_me,_ra,_que,_aof,_quo,_eol

		SECTION_END		FB
