
		SECTION_START	F4

		MSG_START	_scene4_msg_lib
		MSG_IDX	_sc4_msg00
		MSG_IDX	_sc4_msg01
		MSG_IDX	_sc4_msg02
		MSG_IDX	_sc4_msg03
		MSG_IDX	_sc4_msg04
		MSG_IDX	_sc4_msg05
		MSG_IDX	_sc4_msg06
		MSG_IDX	_sc4_msg07
		MSG_IDX	_sc4_msg08
_sc4_msg00:
		.BYTE	_P,_o,_s,_l,_e_,_to,_go,_col_,_ka,_k,__,_a,_r,_me,_j,_s,_ki,_e,_ret
		.BYTE	_p,_ri,_d,_u,_r,_ki,__s,_da,_li,__,_na,_s,_col_,_s,_o,_o,_b,_sch,_i,_v,_ret
		.BYTE	_v,__,_sh,_ko,_l,_u,__,_o,__p,_ro,_i,_z,_o,_sh,_e,_d,_sh,_e,_m,_col_,_na,_ret
		.BYTE	_na,_s,__,_o,_b,_ru,_sh,_i,_l,_s_ja,__,_g,_ne,_v,__,_f,_i,_z,_ru,_ka,_ret
		.BYTE	_po,__,_k,_li,_ch,_k,_e_,_quo,_CH,_e,_l,_ju,_s,_t_mz,_quo,_dot,_eol
_sc4_msg01:
		.BYTE	_F,_a,_na,_t,_ka,_ddt__quo,_an1,_CH,_to,__s,_l,_u,_ch,_i,_lo,_s,_mz_,_s,_ret
		.BYTE	_t,_vo,_e,_j,__,_sch,_e,_ko,_j,_que,_aof,_quo,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_O,_t,_va,_li,_exc_quo,_ret
		.BYTE	_ret
		.BYTE	_Kaj,_ddt__quo,_an0,_V,_st,_re,_ti,_la,_s,_mz_,_s,__,_k,_u,_la,_ko,_m,_ret
		.BYTE	_na,_sh,_e,_go,__,_mo,_r,_da,_to,_go,__,_f,_i,_z,_ru,_ka,_exc,_aof,_quo,_eol
_sc4_msg02:
		.BYTE	_F,_a,_na,_t,_ka,_ddt__quo,_an1,_G,_o,_vo,_r,_ja,_t,_col_,_v,_ji,__,_d,_ra,_li,_s,_mz,_ret
		.BYTE	_s,__,_K,_lo,_u,_na,_m,_i,__,_na,__,_sh,_o,_s,_s,_e,__v,__,_S,_ta,_ro,_m,_ret
		.BYTE	_go,_ro,_de,_dot,__,_JE,_ti,__p,_a,_r,_ni,__,_ta,_ki,_e,_ret
		.BYTE	_me,_r,_z,_ki,_e,_col_,_po,_ch,_e,_m,_u,__v,_ji,__,_d,_o,__s,_i,_h,__,_po,_r,_ret
		.BYTE	_i,_h,__v,_s,_e,_h,__,_ne,__p,_e,_re,_b,_i,_li,_que,_aof,_quo,_eol
_sc4_msg03:
		.BYTE	_JA,_m,_a,_g,_a,_ta,_ddt__quo,_an2,_T,_a,_m,__b,_ji,_li,__,_K,_lo,_u,_n,_ji,_col,_ret
		.BYTE	_de,_mo,_n,_st,_ra,_n,_t,_ji,_col_,_ko,_p,_ji,_col_,_vo,_ja,_ki,_dot_dot_dot,_ret
		.BYTE	_D,_a,__,_e,_sch,_jo,__,_je,_to,_t,__,_i,_di,_o,_t,__,_Tjecuo,__,_po,_p,_a,_l,_ret
		.BYTE	_v,__,_a,_va,_ri,_ju,_dot,_aof,_quo,_ret
		.BYTE	_ret
		.BYTE	_F,_a,_na,_t,_ka,_ddt__quo,_an1,_CH,_to,_que,_exc,__,_CH,_to,__s,_l,_u,_ch,_i,_lo,_s,_mz,_ret
		.BYTE	_s,__,_Tjecuo,_que,_exc,_aof,_quo,_eol
_sc4_msg04:
		.BYTE	_Kaj,_ddt__quo,_an0,_P,_o,_la,_g,_a,_ju,_col_,_o,_n,__v,_ret
		.BYTE	_b,_o,_l,_mz,_ni,_c,_e,_dot_dot_dot,__,_N,_o,__,_m,_ji,__,_ne,__,_z,_na,_e,_m,__v,_ret
		.BYTE	_ka,_ko,_j,_dot,_aof,_quo,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_JE,_to,_t,__,_i,_di,_o,_t,__,_za,_h,_o,_te,_l,_ret
		.BYTE	_v,_ji,_p,_en,_d,_ri,_t_mz,_s_ja,_dot_dot_dot,_quo,_eol
_sc4_msg05:
		.BYTE	_Kaj,_ddt__quo,_an0,_Kanjeda,_col_,_s,_mo,_t,_ri,_exc,__,_JE,_to,_ret
		.BYTE	_Tjecuo,_exc,__,_T,_vo,_j,__b,_a,_j,_k,_dot_dot_dot,_aof,_quo,_eol
_sc4_msg06:
		.BYTE	_Tjecuo,__,_e,_h,_a,_l_,_na,__,_M,_O,_E,_M,__b,_a,_j,_k,_e,__s,_ret
		.BYTE	_ka,_ko,_j,_str,_to,__,_de,_v,_u,_sh,_ko,_j,__s,_za,_di,_dot,_eol
_sc4_msg07:
		.BYTE	_Kanjeda,_ddt__quo,_JE,_to,_t,__,_i,_di,_o,_t,__,_d,_u,_m,_a,_e,_t,_col,_ret
		.BYTE	_ch,_to,__,_mo,_zh,_e,_t,__s,_p,_ra,_v,_i,_t_mz,_s_ja,__s,__,_mo,_i,_m,_ret
		.BYTE	_b,_a,_j,_ko,_m,_que_quo,_ret
		.BYTE	_ret
		.BYTE	_Kaj,_ddt__quo,_K,_o,_go,__,_o,_n,__,_d,_u,_m,_a,_e,_t,_ret
		.BYTE	_o,_d,_u,_ra,_ch,_i,_t_mz,_que_quo,_eol
_sc4_msg08:
		.BYTE	_JA,__s,_e,_l_,_na,__b,_a,_j,_k,__,_JA,_m,_a,_g,_a,_t,_ji,__,_i,_ret
		.BYTE	_o,_t,_p,_ra,_v,_i,_l,_s_ja,__,_za,__,_Tjecuo,_col_,_n,_u,_zh,_no,_ret
		.BYTE	_b,_ji,_lo,__p,_re,_po,_da,_t_mz,__,_e,_m,_u,__,_u,_ro,_k,_dot,_eol

		SECTION_END		F4
