
		SECTION_START	F16

		MSG_START	_scene16_msg_lib
		MSG_IDX	_sc16_msg00
		MSG_IDX	_sc16_msg01
		MSG_IDX	_sc16_msg0D
		MSG_IDX	_sc16_msg0E
		MSG_IDX	_sc16_msg0F
		MSG_IDX	_sc16_msg10
		MSG_IDX	_sc16_msg11
		MSG_IDX	_sc16_msg14
		MSG_IDX	_sc16_msg1D
		MSG_IDX	_sc16_msg1E
		MSG_IDX	_sc16_msg1F
		MSG_IDX	_sc16_msg20
		MSG_IDX	_sc16_msg21
		MSG_IDX	_sc16_msg22
		MSG_IDX	_sc16_msg24
		MSG_IDX	_sc16_msg25
		MSG_IDX	_sc16_msg26
		MSG_IDX	_sc16_msg27
		MSG_IDX	_sc16_msg28
		MSG_IDX	_sc16_msg29
		MSG_IDX	_sc16_msg2A
		MSG_IDX	_sc16_msg2B
		MSG_IDX	_sc16_msg7C
		MSG_IDX	_sc16_msg7D
		MSG_IDX	_sc16_msg7E
		MSG_IDX	_sc16_msg9C
		MSG_IDX	_sc16_msgC0
		MSG_IDX	_sc16_msgC2
		MSG_IDX	_sc16_msgC3
		MSG_IDX	_sc16_msgC4
		MSG_IDX	_sc16_msgCC
		MSG_IDX	_sc16_msgCD
		MSG_IDX	_sc16_msgCE
		MSG_IDX	_sc16_msgCF
		MSG_IDX	_sc16_msgD0
		MSG_IDX	_sc16_msgD1
		MSG_IDX	_sc16_msgD2
		MSG_IDX	_sc16_msgD3
		MSG_IDX	_sc16_msgD4
		MSG_IDX	_sc16_msgD5
		MSG_IDX	_sc16_msgD6
		MSG_IDX	_sc16_msgD7
		MSG_IDX	_sc16_msgD8
		MSG_IDX	_sc16_msgD9
		MSG_IDX	_sc16_msgDA
		MSG_IDX	_sc16_msgDB
		MSG_IDX	_sc16_msgDC
		MSG_IDX	_sc16_msgDD
		MSG_IDX	_sc16_msgDE
		MSG_IDX	_sc16_msgDF
		MSG_IDX	_sc16_msgE0
		MSG_IDX	_sc16_msgE1
		MSG_IDX	_sc16_msgE2
		MSG_IDX	_sc16_msgE3
		MSG_IDX	_sc16_msgE4
		MSG_IDX	_sc16_msgE5
		MSG_IDX	_sc16_msgE6
		MSG_IDX	_sc16_msgE7
		MSG_IDX	_sc16_msgE8
		MSG_IDX	_sc16_msgE9
		MSG_IDX	_sc16_msgEA
		MSG_IDX	_sc16_msgEB
		MSG_IDX	_sc16_msgEC
		MSG_IDX	_sc16_msgED
		MSG_IDX	_sc16_msgEE
		MSG_IDX	_sc16_msgEF
_sc16_msgD9:
		.BYTE	_Kaj,__i_,_Kej,__s,_to,_ja,_li,__,_na,__,_sh,_o,_s,_s,_e_,_u,_ret
		.BYTE	_K,_P,_P,_dot,_eol
_sc16_msg7C:
		.BYTE	_O,_ni,__b,_ji,_li,__,_da,_l,_e,_ko,__v,__,_S,_ta,_ro,_m,_ret
		.BYTE	_go,_ro,_de,__i_,_na,_b,_l,_ju,_da,_li,__,_ka,_k,_ret
		.BYTE	_ra,_s,_sh,_i,_r,_ja,_e,_t,_s_ja,__,_ja,_r,_ko,_e,__s,_i,_ja,_ni,_e,_dot,_eol
_sc16_msgDA:
		.BYTE	_Kaj,_ddt__quo,_an1,_N,_e_,_n,_ra,_v,_i,_t,_s_ja,__,_m,_ne,__,_je,_to,_dot_dot_dot,_ret
		.BYTE	_n,_u,_zh,_no,__,_va,_li,_t_mz,_exc,_aof,_quo,_ret
		.BYTE	_ret
		.BYTE	_Kej,_ddt__quo,_an0,_Kanjeda,_dot_dot_dot,__,_Kanjeda,_str,_a,_str,_a,_exc,_aof,_quo,_eol
_sc16_msgDB:
		.BYTE	_S,_ve,_t,__s,__,_r,_jo,_vo,_m,__,_na,_ch,_a,_l_,_ra,_z,_ru,_sh,_a,_t_mz,_ret
		.BYTE	_S,_ta,_r,_ji,_j,__,_go,_ro,_d,_dot,_eol
_sc16_msgDC:
		.BYTE	_O,_n,__,_o,_b,_vo,_lo,_k,__,_z,_da,_ni,_ja,_dot,__,_R,_a,_z,_va,_li,_n,_ji,_col,_ret
		.BYTE	_re,_k,_la,_m,_n,_ji,_e_,_sch,_i,_t,_ji,__i_,_ta,_n,_ki,__b,_ji,_li,_ret
		.BYTE	_po,_g,_lo,_sch,_en,_ji,__i_,_p,_re,_v,_ra,_ti,_li,_s,_mz_,_v,_ret
		.BYTE	_p,_a,_r,_dot,_ret
		.BYTE	_ret
		.BYTE	_B,_o,_l,_mz,_sh,_a,_ja_,_ch,_a,_s,_t_mz,__,_S,_ta,_ro,_go,__,_go,_ro,_da,_ret
		.BYTE	_b,_ji,_la,__,_ra,_z,_ru,_sh,_e,_na,_dot,_eol
_sc16_msgDD:
		.BYTE	_JA,__,_d,_re,_j,_f,_o,_va,_l,__v,__s,_ve,_t,_u,_dot,_ret
		.BYTE	_ret
		.BYTE	_dot_dot_dot,_v,_s_ja,__,_zh,_i,_z,_n,_mz_,_na,_ch,_a,_la,__,_me,_l,_mz,_ka,_t_mz,_ret
		.BYTE	_p,_e,_re,_d,__,_g,_la,_za,_m,_i,_dot,_eol
_sc16_msgDE:
		.BYTE	_Kanjeda,_ddt__quo,_V,_i,_di,_sh,_mz,_col_,_t,_ji,__p,_ro,_s,_to,_ret
		.BYTE	_ne,_d,_o,_st,_a,_to,_ch,_no,__,_na,_d,__,_je,_ti,_m,_ret
		.BYTE	_ra,_b,_o,_ta,_l,_dot_dot_dot,_quo,_ret
		.BYTE	_ret
		.BYTE	_JA,_m,_a,_g,_a,_ta,_ddt__quo,_N,_u,_zh,_no,__,_za,_h,_o,_di,_t_mz,__v,_ret
		.BYTE	_po,_vo,_ro,_t,__,_ta,_k,_col_,_s,_lo,_v,_no,__,_h,_o,_ch,_e,_sh,_mz,_ret
		.BYTE	_u,_me,_re,_t_mz,_dot,__,_V,_o,_t,_col_,_s,_mo,_t,_ri,_dot_dot_dot,_quo,_eol
_sc16_msgDF:
		.BYTE	_Kaj,_ddt__quo,_CH,_to,__,_t,_ji,__,_i,_me,_e,_sh,_mz_,_v,_v,_i,_d,_u,_que_quo,_ret
		.BYTE	_ret
		.BYTE	_JA,_m,_a,_g,_a,_ta,_ddt__quo,_JE,_to,__,_na,_z,_ji,_va,_e,_t,_s_ja,_ret
		.BYTE	_quo,_K,_R,_U,_T,_O,_J,__,_V,_I,_R,_A,_ZH,_quo,_dot,_quo,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_H,_a,_str,_h,_a,_str,_h,_a,_dot_dot_dot,_ret
		.BYTE	_JE,_j,_col_,_Tjecuo,_dot_dot_dot,_quo,_eol
_sc16_msgE0:
		.BYTE	_O,_col_,_s,_mo,_t,_ri,_col_,_o,_n,__v,_e,_r,_n,_u,_l,_s_ja,_dot,_ret
		.BYTE	_ret
		.BYTE	__,__,__,__,_O,_n,__,_u,_ch,_e,_ni,_k,__,_po,__,_o,_b,_m,_en,_u,_que,_ret
		.BYTE	_ret
		.BYTE	_K,_a,_ko,_j,_str,_to,__,_o,_n,__,_ne,_l,_ju,_di,_m,_ji,_j,_dot_dot_dot,_ret
		.BYTE	_ret
		.BYTE	__,_P,_o,_h,_o,_zh,_e,_col_,_o,_n,__,_ch,_e,_re,_z,__,_m,_no,_go,_e,_ret
		.BYTE	_p,_ro,_sh,_jo,_l,_dot,_eol
_sc16_msgE1:
		.BYTE	_Kanjeda,_ddt__quo,_T,_ji,_dot_dot_dot,_ret
		.BYTE	_me,_ch,_ta,_e,_sh,_mz,_col_,_Tjecuo,_que_quo,_eol
_sc16_msgE2:
		.BYTE	_Tjecuo,_ddt__quo,_str,_sh,_m,_ji,_g,_str,_quo,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_N,_o,_v,_ji,_h,__,_re,_b,_ja,_t,__,_z,_de,_s,_mz,_ret
		.BYTE	_v,_s,_e,_g,_da,__,_i,_z,_b,_i,_va,_ju,_t,_dot,__,_S,_e,_go,_d,_n,_ja_,_je,_to,_ret
		.BYTE	_p,_ro,_i,_z,_o,_sh,_lo,__s,_no,_va,_dot,__,_M,_ne,__,_to,_zh,_e,_ret
		.BYTE	_po,_p,_a,_lo,_dot_dot_dot,__,_no,__,_to,_t,__p,_a,_re,_n,_mz_,_s,_o,_v,_s,_e,_m,_ret
		.BYTE	_s,_la,_b,_en,_mz,_ki,_j,_dot,_quo,_eol
_sc16_msgE3:
		.BYTE	_Tjecuo,_ddt__quo,_JA,_dot_dot_dot,__,_Tjecuo,_dot_dot_dot,_ret
		.BYTE	_Tjecuo,__,_S,_i,_m,_a,_dot_dot_dot,_quo,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_H,_e,_h,_col_,_z,_na,_e,_sh,_mz_,_ch,_to,_que,_ret
		.BYTE	_JA,__,_z,_de,_s,_mz_,_to,_zh,_e_,_no,_v,_en,_mz,_ki,_j,_dot,_ret
		.BYTE	_M,_en,_ja_,_z,_o,_v,_u,_t,_dot_dot_dot,_quo,_eol
_sc16_msgE4:
		.BYTE	_N,_e,_o,_zh,_i,_da,_n,_no,_col_,_ja_,_u,_v,_i,_de,_l_,_te,_h,_ret
		.BYTE	_de,_te,_j,_dot,__,_O,_ni,__,_i,_g,_ra,_li,__v,__,_ko,_m,_na,_te,_col,_ret
		.BYTE	_po,_h,_o,_zh,_e,_j,__,_na,__,_la,_b,_o,_ra,_to,_ri,_ju,_dot,_ret
		.BYTE	_N,_a,_p,_ro,_ti,_v,__,_de,_te,_j,__b,_ji,_l_,_e,_sch,_jo,__,_o,_di,_n,_col,_ret
		.BYTE	_ko,_to,_ro,_go,__,_ja_,_ra,_n,_mz,_sh,_e_,_ne,__v,_i,_de,_l,_dot,_ret
		.BYTE	_O,_n,__,_u,_l,_ji,_b,_a,_l,_s_ja,_dot,_eol
_sc16_msgE5:
		.BYTE	_Kanjeda,_ddt__quo,_an0,_T,_a,_k,__,_je,_to,__,_str,__,_A,_ki,_ra,_que,_dot,_dot,_aof,_quo,_eol
_sc16_msg0D:
		.BYTE	_K,_i,_jo,_ko,_ddt__quo,_an0,_D,_a,_dot_dot_dot,__,_je,_to,__,_to,_col_,_ch,_to,__,_m,_ji,_ret
		.BYTE	_p,_re,_d,_v,_i,_de,_li,_dot_dot_dot,_ret
		.BYTE	_D,_l,_ja_,_to,_go,_col_,_ch,_to,_b,_ji,__p,_ri,_ve,_st,_i,_ret
		.BYTE	_Tjecuo,_dot_dot_dot,_aof,_quo,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_P,_ri,_ve,_st,_i,__,_e,_go,_dot_dot_dot,_ret
		.BYTE	_k,_u,_da,_que_quo,_eol
_sc16_msg0E:
		.BYTE	_T,_a,_ka,_s,_i,_ddt__quo,_N,_i,_ch,_to,__,_ne,__,_mo,_g,_lo,__,_po,_mo,_ch,_mz,_ret
		.BYTE	_Tjecuo,_dot_dot_dot,__,_ni,__,_m,_ji,_dot_dot_dot,__,_ni,__,_da,_zh,_e,_ret
		.BYTE	_A,_ki,_ra,_dot_dot_dot,_quo,_ret
		.BYTE	_ret
		.BYTE	_M,_a,_s,_a,_ru,_ddt__quo,_E,_go,__,_vo,_z,_mo,_zh,_no,_st,_i,_ret
		.BYTE	_s,_i,_l,_mz,_no,__p,_re,_vo,_s,_h,_o,_d,_ja,_t,__,_na,_sh,_i,_dot,_quo,_eol
_sc16_msg0F:
		.BYTE	_K,_i,_jo,_ko,_ddt__quo,_an0,_N,_o,__,_ko,_g,_da,_str,_ni,_b,_u,_d,_mz_,_da,_zh,_e,_ret
		.BYTE	_m,_ji,_dot_dot_dot,_aof,_quo,_ret
		.BYTE	_ret
		.BYTE	_M,_a,_s,_a,_ru,_ddt__quo,_JE,_to,__,_e,_sch,_jo,__,_to,_l,_mz,_ko,_ret
		.BYTE	_na,_ch,_a,_lo,_dot_dot_dot,_quo,_eol
_sc16_msg10:
		.BYTE	_K,_i,_jo,_ko,_ddt__quo,_an0,_T,_vo,_ja_,_po,_d,_ru,_g,_a,_dot_dot_dot,_aof,_quo,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_T,_ji,__,_i,_me,_e,_sh,_mz_,_v,__v,_i,_d,_u,_ret
		.BYTE	_Kej,_que_quo,_eol
_sc16_msg11:
		.BYTE	_Kej,_ddt__quo,_Kanjeda,_exc_quo,_ret
		.BYTE	_ret
		.BYTE	_JA,__,_mo,_g,__s,_l,_ji,_sh,_a,_t_mz,__,_go,_lo,_s,__,_Kej,_dot_dot_dot,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_an0,_Kej,_dot_dot_dot,_aof,_quo,_eol
_sc16_msgE7:
		.BYTE	_P,_ro,_st,_ra,_n,_st,_vo,__,_vo,_k,_ru,_g,__,_m,_en,_ja_,_st,_a,_lo,_ret
		.BYTE	_i,_s,_ka,_zh,_a,_t_mz,_s_ja,__i_,_s,_zh,_i,_m,_a,_t_mz,_s_ja,_dot,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_an0,_A,_str,_a,_dot_dot_dot,__,_Kej,_exc,_aof,_quo,_eol
_sc16_msg14:
		.BYTE	_M,_a,_s,_a,_ru,_ddt__quo,_K,_i,_jo,_ko,_col_,_T,_a,_ka,_s,_i,_dot,_quo,_ret
		.BYTE	_ret
		.BYTE	_T,_a,_ka,_s,_i,_ddt__quo,_M,_a,_s,_a,_ru,_col_,_K,_i,_jo,_ko,_dot,_quo,_ret
		.BYTE	_ret
		.BYTE	_K,_i,_jo,_ko,_ddt__quo,_T,_a,_ka,_s,_i,_col_,_M,_a,_s,_a,_ru,_dot,_quo,_eol
_sc16_msgE6:
		.BYTE	_N,_a,_d,__,_N,_e,_o,_str,_T,_o,_ki,_o,__,_po,_ja,_v,_i,_l,_s_ja,_ret
		.BYTE	_o,_g,_ro,_m,_n,_ji,_j,__,_sh,_a,_r,__s,_ve,_ta,_dot,__,_V,_s,_ko,_re,_col,_ret
		.BYTE	_v,_e,_r,_h,_n,_ja,_ja_,_ch,_a,_s,_t_mz,__,_sh,_a,_ra,__,_po,_te,_m,_ne,_la,__,_str,_ret
		.BYTE	_ta,_m,__,_za,_ro,_zh,_da,_la,_s,_mz_,_ch,_jo,_r,_na,_ja_,_d,_ji,_ra,_dot,_eol
_sc16_msgE8:
		.BYTE	_SH,_a,_r,__s,_ve,_ta,__b,_ji,_l_,_po,_l,_no,_s,_t_mz,_ju,_ret
		.BYTE	_o,_k,_ru,_zh,_en,__,_te,_m,_no,_to,_j,_dot,__,_O,_b,_la,_ko,_ret
		.BYTE	_ra,_s,_sh,_i,_r,_ja,_lo,_s,_mz,_col_,_p,_e,_re,_me,_sch,_a,_ja,_s,_mz,_ret
		.BYTE	_k,__,_c,_en,_t,_ru,_dot,_eol
_sc16_msgE9:
		.BYTE	_S,_f,_e,_ra,__,_t_mz,_m,_ji,__,_na,_k,_r,_ji,_la,__,_z,_da,_ni,_ja,_ret
		.BYTE	_N,_e,_o,_str,_T,_o,_ki,_o,__i_,_ra,_z,_ru,_sh,_i,_la,__,_i,_h,_dot,_ret
		.BYTE	_V,__,_ra,_j,_o,_ne,_col_,_ko,_to,_r,_ji,_j,__,_ko,_g,_da,_str,_to,__b,_ji,_l,_ret
		.BYTE	_c,_en,_t,_ro,_m,__,_N,_e,_o,_str,_T,_o,_ki,_o,_col_,_po,_ja,_v,_i,_la,_s,_mz,_ret
		.BYTE	_g,_i,_g,_a,_n,_t,_s,_ka,_ja_,_vo,_ro,_n,_ka,_dot,_eol
_sc16_msgEA:
		.BYTE	_S,_f,_e,_ra,__,_t_mz,_m,_ji,__v,_ji,_ro,_s,_la,__,_na,_d,_ret
		.BYTE	_N,_e,_o,_str,_T,_o,_ki,_o,__i_,_ra,_s,_sh,_i,_ri,_la,_s,_mz_,_v,_p,_lo,_t_mz,_ret
		.BYTE	_d,_o,__,_o,_k,_e,_a,_na,_dot,_eol
_sc16_msgEB:
		.BYTE	_Z,_da,_ni,_ja_,_N,_e,_o,_str,_T,_o,_ki,_o,__b,_ji,_li,_ret
		.BYTE	_za,_to,_p,_l,_en,_ji,__,_mo,_r,_s,_ko,_j,__,_vo,_d,_o,_j,_dot,_eol
_sc16_msgEC:
		.BYTE	_Z,_da,_ni,_ja_,_ru,_sh,_i,_li,_s,_mz_,_o,_di,_n,__,_za,__,_o,_d,_ni,_m,_col,_ret
		.BYTE	_ko,_g,_da,__,_vo,_da,__,_d,_o,_st,_i,_g,_a,_la,__,_i,_h,_dot,_eol
_sc16_msgED:
		.BYTE	_N,_a,_ch,_i,_na,_lo,_s,_mz_,_u,_t,_ro,_col,__i_,_i,_z,__,_c,_en,_t,_ra,_ret
		.BYTE	_g,_i,_g,_a,_n,_t,_s,_ko,_go,__,_o,_b,_la,_ka,__p,_ro,_b,_i,_l,_s_ja,_ret
		.BYTE	_l,_u,_ch,__s,_ve,_ta,_dot,__,_V,_o,_da,__,_na,_ch,_a,_la,_ret
		.BYTE	_o,_t,_st,_u,_p,_a,_t_mz,_dot,_eol
_sc16_msgEE:
		.BYTE	_N,_e,_o,_str,_T,_o,_ki,_o,_col_,_ko,_to,_r,_ji,_j,__,_m,_ji,__,_mo,_g,_li,_ret
		.BYTE	_v,_i,_de,_t_mz,__s,_o,__,_st,_a,_di,_o,_na,_col_,_za,_ti,_h,_dot_dot_dot,_eol
_sc16_msg1D:
		.BYTE	_S,_zh,_a,_v,_sh,_i,_j,_s_ja,__,_sh,_a,_r,__s,_ve,_ta,__,_st,_a,_l,_ret
		.BYTE	_ka,_za,_t_mz,_s_ja,__v,_s,_e_,_m,_en,_mz,_sh,_e_,_po,__,_me,_re,_ret
		.BYTE	_to,_go,_col_,_ka,_k,__,_u,_da,_l,_ja,_l,_s_ja,__p,_ro,_ch,_mz,_dot_dot_dot,_eol
_sc16_msg1E:
		.BYTE	_K,_o,_g,_da,__,_ja_,_p,_ri,_sh,_jo,_l,__v,__s,_e,_b,_ja,_col_,_ja_,_b,_ji,_l,_ret
		.BYTE	_na,__v,_e,_r,_sh,_i,_ne,__,_k,_u,_ch,_i,__,_o,_b,_lo,_m,_ko,_v,__,_na,_ret
		.BYTE	_st,_a,_di,_o,_ne,_dot,_eol
_sc16_msg00:
		.BYTE	_P,_e,_re,_d,__,_mo,_i,_m,_i,__,_g,_la,_za,_m,_i,__,_o,_p,_u,_s,_ka,_l,_s_ja,_ret
		.BYTE	_s,_g,_u,_s,_to,_k,__s,_ve,_ta,_dot,_eol
_sc16_msg1F:
		.BYTE	_N,_e_,_za,_d,_u,_m,_ji,_va,_ja,_s,_mz,_col_,_ja_,_s,_h,_va,_ti,_l,_ret
		.BYTE	_u,_g,_a,_s,_a,_ju,_sch,_i,_j,__s,_g,_u,_s,_to,_k,__s,_ve,_ta,_dot,_eol
_sc16_msg20:
		.BYTE	_Kanjeda,_ddt__quo,_Tjecuo,_dot_dot_dot,_quo,_eol
_sc16_msg21:
		.BYTE	_Kej,_ddt__quo,_Kanjeda,_dot_dot_dot,_quo,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_S,_p,_a,_s,_i,_b,_o,_dot_dot_dot,_ret
		.BYTE	_ch,_to,__,_z,_va,_la,__,_m,_en,_ja_,_po,__,_i,_me,_ni,_dot,_ret
		.BYTE	_JA,__,_u,_s,_l,_ji,_sh,_a,_l_,_te,_b,_ja,_dot_dot_dot,_quo,_eol
_sc16_msg01:
		.BYTE	_JA,__,_o,_b,_e,_r,_n,_u,_l,_s_ja,__i_,_u,_v,_i,_de,_l_,_Kej,_dot,_eol
_sc16_msg22:
		.BYTE	_Kej,_ddt__quo,_Tjecuo,_dot_dot_dot,_quo,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_O,_n,__,_u,_sh,_jo,_l,_dot_dot_dot,_ret
		.BYTE	_v,_me,_st,_e,__s,__,_te,_m,_i,__,_t,_re,_m,_ja,_dot_dot_dot,_ret
		.BYTE	_i,__,_A,_ki,_ro,_j,_dot_dot_dot,_quo,_ret
		.BYTE	_ret
		.BYTE	_Kej,_ddt__quo,_Kanjeda,_dot_dot_dot,__,_ja_,_d,_u,_m,_a,_la,_col,_ret
		.BYTE	_t,_ji,_dot_dot_dot,_quo,_eol
_sc16_msgEF:
		.BYTE	_Kaj,_ddt__quo,_an0,_Kanjeda,_exc,__,_T,_ji,__,_zh,_i,_v,_exc,_ret
		.BYTE	_G,_o,_s,_po,_di,_col_,_ja_,_d,_u,_m,_a,_l,_col_,_t,_ji,__,_po,_g,_i,_b,_dot_dot_dot,_ret
		.BYTE	_A,_str,_a,_col_,_g,_de,__,_Tjecuo,_que,__,_O,_n,__,_u,_me,_r,_que,_aof,_quo,_eol
_sc16_msg2B:
		.BYTE	_Kanjeda,_ddt__quo,_V,_i,_di,_mo,__,_da,_dot_dot_dot,_ret
		.BYTE	_A,_h,_exc,__,_N,_u,__,_ko,_ne,_ch,_no,_exc_quo,_eol
_sc16_msg24:
		.BYTE	_O,_b,_la,_ka,__,_ra,_s,_s,_e,_ja,_li,_s,_mz,__i_,_za,_s,_i,_ja,_lo,_ret
		.BYTE	_s,_o,_l,_n,_c,_e,_dot,_ret
		.BYTE	_ret
		.BYTE	_M,_ji,__b,_ji,_li,__s,_po,_s,_o,_b,_n,_ji,__,_to,_l,_mz,_ko,_ret
		.BYTE	_ta,_ra,_sch,_i,_t_mz,_s_ja,__,_na,__s,_ve,_t,_dot_dot_dot,_eol
_sc16_msg25:
		.BYTE	_Z,_a,_te,_m,_col_,_m,_ji,__s,_e,_li,__,_na,__b,_a,_j,_ki,__,_i,_ret
		.BYTE	_na,_p,_ra,_v,_i,_li,_s,_mz_,_v,__,_N,_e,_o,_str,_T,_o,_ki,_o,_dot,_eol
_sc16_msg26:
		.BYTE	_D,_a,_zh,_e_,_ra,_z,_ru,_sh,_en,_n,_ji,_e_,_z,_da,_ni,_ja,_ret
		.BYTE	_N,_e,_o,_str,_T,_o,_ki,_o,__,_po,_ch,_u,_v,_st,_vo,_va,_li,__v,_s,_ju,_ret
		.BYTE	_s,_i,_l,_u,__,_l,_mz,_ju,_sch,_e,_go,_s_ja,__s,_o,_l,_ne,_ch,_no,_go,_ret
		.BYTE	_s,_ve,_ta,_dot,_eol
_sc16_msg27:
		.BYTE	_dot_dot_dot,_S,_ve,_t,__,_vo,_z,_ni,_k,__,_i,_z,__b,_e,_lo,_j,_ret
		.BYTE	_p,_u,_s,_to,_t,_ji,_dot,__,_P,_o,_st,_e,_p,_en,_no,__,_ro,_di,_li,_s,_mz,_ret
		.BYTE	_a,_to,_m,_ji,_dot_dot_dot,_eol
_sc16_msg28:
		.BYTE	_dot_dot_dot,_A,_to,_m,_ji,__s,_o,_b,_i,_ra,_li,_s,_mz_,_v,_me,_st,_e,_col,_ret
		.BYTE	_o,_b,_ra,_z,_u,_ja_,_g,_a,_z,_o,_v,_ji,_e_,_o,_b,_la,_ka,_dot,__,_T,_a,_k,_ret
		.BYTE	_po,_ja,_v,_i,_l,_s_ja,__,_ko,_s,_mo,_s,_dot_dot_dot,_eol
_sc16_msg29:
		.BYTE	_dot_dot_dot,_Z,_a,_te,_m,__,_g,_a,_la,_k,_ti,_ki,_dot_dot_dot,__,_R,_o,_di,_li,_s,_mz,_ret
		.BYTE	_p,_la,_ne,_t,_ji,__i_,_z,_v,_jo,_z,_d,_ji,_dot_dot_dot,_eol
_sc16_msg2A:
		.BYTE	_Tjecuo,_ddt__quo,_JA,_dot_dot_dot,__,_Tjecuo,_dot_dot_dot,_quo,_eol
_sc16_msgCC:
		.BYTE	_I,_s,_po,_l,_mz,_z,_u,_ja_,_je,_ne,_r,_g,_i,_ju,__,_la,_z,_e,_ra,_col,_ret
		.BYTE	_ra,_st,_u,_sch,_i,_j,__,_Tjecuo,__,_u,_ve,_li,_ch,_i,_l,_s_ja,_ret
		.BYTE	_na,_s,_to,_l,_mz,_ko,_col_,_ch,_to,__,_po,_g,_lo,_ti,_l,__v,_s,_e,_h,_ret
		.BYTE	_t,_ro,_i,_h,__i_,_da,_zh,_e_,_ko,_n,_te,_j,_ne,_r,__s,_ret
		.BYTE	_o,_b,_ra,_z,_c,_a,_m,_i,__,_A,_ki,_r,_ji,_dot,_eol
_sc16_msgCD:
		.BYTE	_K,_i,_jo,_ko,_ddt__quo,_Tjecuo,_dot_dot_dot,__,_A,_str,_a,_exc_quo,_ret
		.BYTE	_ret
		.BYTE	_T,_a,_ka,_s,_i,_ddt__quo,_JE,_to,__b,_e,_s,_po,_l,_e,_z,_no,_exc_quo,_ret
		.BYTE	_ret
		.BYTE	_M,_a,_s,_a,_ru,_ddt__quo,_A,_h,_exc,__,_A,_ki,_ra,_dot_dot_dot,_quo,_eol
_sc16_msgCE:
		.BYTE	_P,_o,_s,_l,_e_,_u,_ni,_ch,_to,_zh,_e,_ni,_ja_,_st,_a,_di,_o,_na,_ret
		.BYTE	_Tjecuo,__,_ra,_s,_sh,_i,_ri,_l,_s_ja,__i_,_po,_g,_lo,_ti,_l,_ret
		.BYTE	_v,_e,_s,_mz_,_S,_ta,_r,_ji,_j,__,_go,_ro,_d,_dot,_eol
_sc16_msgCF:
		.BYTE	_S,__,_o,_b,_ru,_sh,_e,_ni,_e,_m,__,_S,_ta,_ro,_go,__,_go,_ro,_da,__v,_ret
		.BYTE	_N,_e,_o,_str,_T,_o,_ki,_o,__,_h,_l,_ji,_n,_u,_l_,_o,_k,_e,_a,_n,_dot,_eol
_sc16_msgD0:
		.BYTE	_V,__,_N,_e,_o,_str,_T,_o,_ki,_o,__v,_e,_r,_n,_u,_la,_s,_mz_,_ti,_sh,_i,_na,_dot,_ret
		.BYTE	_R,_a,_z,_ru,_sh,_i,_v,__,_S,_ta,_r,_ji,_j,__,_go,_ro,_d,_col_,_Tjecuo,_ret
		.BYTE	_p,_la,_ka,_l,_dot,_eol
_sc16_msgD1:
		.BYTE	_D,_e,_ti,__,_te,_l,_e,_po,_r,_ti,_ro,_va,_li,__,_m,_en,_ja_,_s,_o,_ret
		.BYTE	_st,_a,_di,_o,_na,_dot,_eol
_sc16_msgC4:
		.BYTE	_V,__,_N,_e,_o,_str,_T,_o,_ki,_o,__,_po,_st,_e,_p,_en,_no,_ret
		.BYTE	_vo,_c,_a,_ri,_la,_s,_mz_,_ti,_sh,_i,_na,_dot,_eol
_sc16_msg7E:
		.BYTE	_N,_o,__,_K,_a,_ne,_da,__v,_s,_e,_str,_ta,_ki,__,_ra,_z,_b,_u,_di,_l,_ret
		.BYTE	_A,_ki,_ru,_dot,_eol
_sc16_msg7D:
		.BYTE	_N,_e,_o,_str,_T,_o,_ki,_o,__v,_s,_e,__b,_o,_l,_mz,_sh,_e,__i_,_b,_o,_l,_mz,_sh,_e,_ret
		.BYTE	_po,_g,_ru,_zh,_a,_l,_s_ja,__v,__b,_e,_z,_d,_n,_u,_dot,_eol
_sc16_msg9C:
		.BYTE	_B,_la,_go,_da,_r,_ja_,_ra,_b,_o,_te,__,_K,_a,_n,_je,_d,_ji,_col_,_b,_ji,_lo,_ret
		.BYTE	_p,_re,_d,_o,_t,_v,_ra,_sch,_e,_no,__,_vo,_s,_k,_re,_sh,_e,_ni,_e,_ret
		.BYTE	_A,_ki,_r,_ji,_dot,__,_V,__,_N,_e,_o,_str,_T,_o,_ki,_o,__s,_no,_va,_ret
		.BYTE	_vo,_c,_a,_ri,_l,_s_ja,__,_m,_i,_r,_dot_dot_dot,_eol
_sc16_msgC0:
		.BYTE	_S,_ve,_t,__,_po,_g,_lo,_ti,_l_,_ru,_i,_n,_ji,__,_i,_ret
		.BYTE	_ra,_s,_sh,_i,_ri,_l,_s_ja,_dot,_ret
		.BYTE	_ret
		.BYTE	_Tjecuo,_ddt__quo,_JE,_to,_t,__s,_ve,_t,_dot_dot_dot,_ret
		.BYTE	_ch,_to,__,_je,_to,_que_quo,_ret
		.BYTE	_ret
		.BYTE	_P,_ro,_st,_ra,_n,_st,_vo,__p,_e,_re,_d,_o,__,_m,_no,_j,__,_st,_a,_lo,_ret
		.BYTE	_ja,_r,_ko,__b,_e,_l,_ji,_m,_dot,_eol
_sc16_msgC2:
		.BYTE	_P,_o,_s,_l,_e_,_po,_p,_a,_da,_ni,_ja_,_v,__,_ko,_n,_te,_j,_ne,_r,__s,_ret
		.BYTE	_o,_b,_ra,_z,_c,_o,_m,_col_,_je,_ne,_r,_g,_i,_ja_,_la,_z,_e,_ra,__,_vo,_sh,_la,_ret
		.BYTE	_v,__,_re,_z,_o,_na,_n,_s,__s,__,_s,_i,_lo,_j,__,_Tjecuo,_col,_ret
		.BYTE	_vo,_s,_k,_re,_s,_i,_v,__,_A,_ki,_ru,_dot,_eol
_sc16_msgC3:
		.BYTE	_S,_ve,_t,__,_A,_ki,_r,_ji,__,_ra,_s,_sh,_i,_r,_ja,_l,_s_ja,__v,_s,_jo,_ret
		.BYTE	_b,_o,_l,_mz,_sh,_e,__i_,_b,_o,_l,_mz,_sh,_e,_col_,_o,_d,_no,_v,_re,_m,_en,_no,_ret
		.BYTE	_na,_k,_r,_ji,_va,_ja_,_A,_ki,_ru,__i_,_K,_a,_ne,_d,_u,_dot,_ret
		.BYTE	_ret
		.BYTE	_Tjecuo,_ddt__quo,_A,_h,_col_,_A,_dot_dot_dot,__,_A,_ki,_ra,_dot_dot_dot,_quo,_eol
_sc16_msgD2:
		.BYTE	_K,_o,_g,_da,__,_m,_ji,__,_d,_o,_b,_ra,_li,_s,_mz_,_d,_o,_ret
		.BYTE	_ra,_z,_va,_li,_va,_ju,_sch,_e,_go,_s_ja,__,_st,_a,_di,_o,_na,_col_,_m,_ji,_ret
		.BYTE	_v,_st,_re,_ti,_li,__,_K,_a,_ja,__i_,_Kej,_dot,_eol
_sc16_msgD8:
		.BYTE	_N,_e,_o,_str,_T,_o,_ki,_o,__,_za,_ti,_h,_dot,__,_V,_s,_jo,__b,_ji,_lo,_ret
		.BYTE	_po,_l,_no,_s,_t_mz,_ju,__,_ra,_z,_ru,_sh,_e,_no,_dot,_eol
_sc16_msgD3:
		.BYTE	_dot_dot_dot,_CH,_to,__p,_ro,_i,_z,_o,_sh,_lo,__b,_ji,_col_,_e,_s,_li,_ret
		.BYTE	_b,_ji,__s,_to,_l,_k,_n,_u,_li,_s,_mz_,_d,_ve,__,_je,_ti,__s,_i,_l,_ji,_que,_eol
_sc16_msgD4:
		.BYTE	_A,_ki,_ra,__i_,_Tjecuo,_ret
		.BYTE	_re,_g,_e,_ne,_ri,_ro,_va,_li,__s,_re,_di,__,_ra,_z,_va,_li,_n,_dot,_ret
		.BYTE	_ret
		.BYTE	_Tjecuo,_ddt__quo,_N,_a,_ko,_ne,_c,_str,_to,__,_m,_ji,_ret
		.BYTE	_v,_st,_re,_ti,_li,_s,_mz,_dot_dot_dot,__,_A,_ki,_ra,_dot_dot_dot,_quo,_eol
_sc16_msgD5:
		.BYTE	_S,__,_ra,_z,_ru,_sh,_e,_ni,_ja_,_N,_e,_o,_str,_T,_o,_ki,_o,_ret
		.BYTE	_na,_ch,_a,_la,_s,_mz_,_no,_va,_ja_,_i,_s,_to,_ri,_ja,_ret
		.BYTE	_A,_ki,_r,_ji,_dot_dot_dot,_ret
		.BYTE	_ret
		.BYTE	_V,_e,_li,_ka,_ja_,_T,_o,_ki,_j,_s,_ka,_ja_,_i,_m,_p,_e,_ri,_ja,_dot_dot_dot,_ret
		.BYTE	_ret
		.BYTE	_D,_a,__,_z,_d,_ra,_v,_st,_v,_u,_e,_t,__,_i,_m,_p,_e,_ra,_to,_r,_ret
		.BYTE	_A,_ki,_ra,_dot_dot_dot,_eol
_sc16_msgD6:
		.BYTE	_Kanjeda,__b,_o,_ro,_l,_s_ja,_col_,_no,__,_o,_n,__b,_ji,_l,_ret
		.BYTE	_o,_ko,_n,_ch,_a,_te,_l,_mz,_no,__,_po,_g,_lo,_sch,_jo,_n,__s,_ve,_to,_m,_dot,_eol
_sc16_msgD7:
		.BYTE	_dot_dot_dot,_Kanjeda,__b,_ji,_l_,_o,_k,_u,_ta,_n,__,_A,_ki,_ro,_j,_col_,_i,_ret
		.BYTE	_v,_s,_jo,__,_e,_go,__s,_u,_sch,_e,_st,_vo,__,_u,_ni,_ch,_to,_zh,_a,_lo,_s,_mz,_dot,_eol

		SECTION_END		F16
