
		SECTION_START	FC

		MSG_START	_sceneC_msg_lib
		MSG_IDX	_scC_msg00
		MSG_IDX	_scC_msg01
		MSG_IDX	_scC_msg02
		MSG_IDX	_scC_msg03
		MSG_IDX	_scC_msg04
		MSG_IDX	_scC_msg05
		MSG_IDX	_scC_msg06
		MSG_IDX	_scC_msg07
		MSG_IDX	_scC_msg08
		MSG_IDX	_scC_msg09
		MSG_IDX	_scC_msg0A
		MSG_IDX	_scC_msg0B
		MSG_IDX	_scC_msg0C
		MSG_IDX	_scC_msg0D
		MSG_IDX	_scC_msg0E
		MSG_IDX	_scC_msg0F
		MSG_IDX	_scC_msg10
		MSG_IDX	_scC_msg11
		MSG_IDX	_scC_msg12
		MSG_IDX	_scC_msg13
_scC_msg00:
		.BYTE	_N,_a,__s,_l,_e,_d,_u,_ju,_sch,_i,_j,__,_de,_n,_mz_,_m,_ji,_ret
		.BYTE	_p,_ro,_b,_ra,_li,_s,_mz_,_v,__,_la,_b,_o,_ra,_to,_ri,_ju,__,_ch,_e,_re,_z,_ret
		.BYTE	_s,_vo,_e,_go,__,_ro,_da,__,_d,_re,_na,_zh,_n,_u,_ju,__s,_i,_st,_e,_m,_u,_dot,_eol
_scC_msg01:
		.BYTE	_Kanjeda,_ddt__quo,_K,_a,_ka,_ja_,_vo,_n,_mz,_exc_quo,_ret
		.BYTE	_ret
		.BYTE	_Kej,_ddt__quo,_T,_s,_str,_s,_col_,_ti,_sh,_e,_exc_quo,_eol
_scC_msg02:
		.BYTE	_Kanjeda,_ddt__quo,_CH,_to,_que,__,_N,_o,__,_t,_u,_t,__i_,_p,_ra,_v,_da,_ret
		.BYTE	_vo,_n,_ja,_e,_t,_col_,_u,__,_te,_b,_ja_,_no,_s,__,_ch,_to,__,_li,_ret
		.BYTE	_za,_b,_i,_t,_que_quo,_eol
_scC_msg06:
		.BYTE	_Kej,_ddt__quo,_L,_u,_ch,_sh,_e_,_po,_mo,_l,_ch,_i,__i_,_sh,_e,_ve,_li,_ret
		.BYTE	_no,_g,_a,_m,_i,_exc_quo,_eol
_scC_msg03:
		.BYTE	_T,_e,_r,_ro,_ri,_st,_ddt__quo,_C,_en,_t,_ra,_l,_mz,_na,_ja,_ret
		.BYTE	_s,_i,_st,_e,_m,_a,__,_ra,_s,_p,_re,_de,_l,_e,_ni,_ja_,_je,_ne,_r,_g,_i,_i,_ret
		.BYTE	_na,_h,_o,_di,_t,_s_ja,__p,_r,_ja,_mo,__,_na,_d,__,_na,_m,_i,_dot,__,_E,_s,_li,_ret
		.BYTE	_m,_ji,__,_za,_b,_lo,_ki,_ru,_e,_m,__,_e,_jo,_col_,_to,__s,_mo,_zh,_e,_m,_ret
		.BYTE	_p,_ro,_ni,_k,_n,_u,_t_mz,__,_na,__,_ni,_zh,_ni,_e_,_u,_ro,_v,_ni,_dot,_eol
_scC_msg04:
		.BYTE	_R,_ju,_ddt__quo,_CH,_jo,_r,_t,_exc,__,_N,_a,_s,__,_za,_s,_e,_k,_li,_exc_quo,_ret
		.BYTE	_ret
		.BYTE	_T,_e,_r,_ro,_ri,_st,_ddt__quo,_JE,_to,__,_h,_o,_ve,_r,_ji,_exc_quo,_eol
_scC_msg05:
		.BYTE	_O,_di,_n,__,_i,_z,__,_te,_r,_ro,_ri,_s,_to,_v,__,_u,_b,_i,_t,_exc,_eol
_scC_msg07:
		.BYTE	_JA,__,_po,_d,_n,_ja,_l_,_o,_ru,_zh,_i,_e_,_m,_jo,_r,_t,_vo,_go,_ret
		.BYTE	_te,_r,_ro,_ri,_st,_a,_dot,_eol
_scC_msg13:
		.BYTE	_K,_no,_p,_ka,__,_A,_ddt__quo,_S,_t,_re,_l,_ja,_t_mz,_quo,_ret
		.BYTE	_K,_no,_p,_ka,__,_V,_ddt__quo,_U,_k,_lo,_n,_ja,_t_mz,_s_ja,_quo,_ret
		.BYTE	_S,_e,_l,_e,_k,_t,__,__,_ddt__quo,_R,_a,_z,_ve,_r,_n,_u,_t_mz,_s_ja,_quo,_eol
_scC_msg0F:
		.BYTE	_Kanjeda,_ddt__quo,_U,_a,_str,_a,_dot,_quo,_ret
		.BYTE	_ret
		.BYTE	_Kej,_ddt__quo,_A,_str,_a,_str,_a,_dot,_quo,_eol
_scC_msg08:
		.BYTE	_O,_ru,_di,_e_,_na,__,_h,_o,_ve,_re,__,_po,_ve,_r,_n,_u,_lo,_s,_mz_,_v,_ret
		.BYTE	_mo,_ju,__s,_to,_ro,_n,_u,_dot,__,_P,_u,_li,__,_g,_ra,_d,_o,_m,_ret
		.BYTE	_vo,_sh,_li,__v,__,_g,_r,_ja,_z,_mz,_dot,_eol
_scC_msg10:
		.BYTE	_JA,__v,_c,_e,_p,_i,_l,_s_ja,__v,__,_h,_o,_ve,_r,__i_,_po,_s,_l,_e,_ret
		.BYTE	_u,_po,_r,_no,_j,__b,_o,_r,_mz,_b,_ji,__v,_s,_e,_str,_ta,_ki,_ret
		.BYTE	_za,_b,_ra,_l,_s_ja,__,_na,__,_ne,_go,_dot,_eol
_scC_msg11:
		.BYTE	_Kej,_ddt__quo,_A,_str,_a,_str,_a,_exc_quo,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_Kej,_exc,__,_S,_ju,_da,_col_,_s,_a,_di,_s,_mz,_ret
		.BYTE	_b,_ji,_st,_re,_e,_exc_quo,_eol
_scC_msg09:
		.BYTE	_Kanjeda,_ddt__quo,_A,_que,__,_P,_a,_t,_ro,_n,_ji,_ret
		.BYTE	_ko,_n,_ch,_i,_li,_s,_mz,_exc_quo,_eol
_scC_msg0D:
		.BYTE	_Kanjeda,_ddt__quo,_S,_no,_va,__,_l,_e,_ti,_t,_exc_quo,_eol
_scC_msg0A:
		.BYTE	_Kanjeda,_ddt__quo,_CH,_jo,_r,_t,_exc_quo,_ret
		.BYTE	_ret
		.BYTE	_JA,__v,_ji,_b,_ro,_s,_i,_l_,_o,_ru,_zh,_i,_e,_dot,_eol
_scC_msg0B:
		.BYTE	_Kanjeda,_ddt__quo,_T,_mz,_f,_u,_dot_dot_dot,_quo,_ret
		.BYTE	_ret
		.BYTE	_str,_k,_h,_e,_str,__,_str,_k,_h,_e,_str,_ret
		.BYTE	_ret
		.BYTE	_JA,__,_za,_l,_jo,_g,__v,__,_g,_r,_ja,_z,_mz,_dot,_eol
_scC_msg0C:
		.BYTE	_B,_u,_l,_mz,_k,_exc,_ret
		.BYTE	_ret
		.BYTE	_JA,__v,_ji,_b,_ra,_l,_s_ja,__,_i,_z,__,_vo,_d,_ji,__i_,_za,_l,_e,_z,_ret
		.BYTE	_na,__,_st,_en,_u,__,_ka,_na,_li,_za,_c,_i,_i,_dot,_eol
_scC_msg0E:
		.BYTE	_Kanjeda,_ddt__quo,_K,_i,_str,_i,_j,_ja,_str,_ja,_exc_quo,_ret
		.BYTE	_ret
		.BYTE	_JA,__,_za,_p,_r,_ji,_g,_n,_u,_l_,_na,__,_h,_o,_ve,_r,_dot,_eol
_scC_msg12:
		.BYTE	_Kej,_ddt__quo,_Kanjeda,_exc,__,_O,_ni,__s,_za,_di,__,_na,_s,_exc_quo,_eol

		SECTION_END		FC
