
		SECTION_START	F13

		MSG_START	_scene13_msg_lib
		MSG_IDX	_sc13_msg00
		MSG_IDX	_sc13_msg01
		MSG_IDX	_sc13_msg02
		MSG_IDX	_sc13_msg03
		MSG_IDX	_sc13_msg04
		MSG_IDX	_sc13_msg05
		MSG_IDX	_sc13_msg06
		MSG_IDX	_sc13_msg07
		MSG_IDX	_sc13_msg08
		MSG_IDX	_sc13_msg09
		MSG_IDX	_sc13_msg0A
		MSG_IDX	_sc13_msg0B
		MSG_IDX	_sc13_msg0C
		MSG_IDX	_sc13_msg0D
		MSG_IDX	_sc13_msg0E
		MSG_IDX	_sc13_msg0F
		MSG_IDX	_sc13_msg10
		MSG_IDX	_sc13_msg11
		MSG_IDX	_sc13_msg12
		MSG_IDX	_sc13_msg13
		MSG_IDX	_sc13_msg14
		MSG_IDX	_sc13_msg15
		MSG_IDX	_sc13_msg16
		MSG_IDX	_sc13_msg17
		MSG_IDX	_sc13_msg18
		MSG_IDX	_sc13_msg19
		MSG_IDX	_sc13_msg1A
		MSG_IDX	_sc13_msg1B
		MSG_IDX	_sc13_msg1C
		MSG_IDX	_sc13_msg1D
		MSG_IDX	_sc13_msg1E
		MSG_IDX	_sc13_msg1F
		MSG_IDX	_sc13_msg20
		MSG_IDX	_sc13_msg21
		MSG_IDX	_sc13_msg22
		MSG_IDX	_sc13_msg23
		MSG_IDX	_sc13_msg24
		MSG_IDX	_sc13_msg25
		MSG_IDX	_sc13_msg26
		MSG_IDX	_sc13_msg27
		MSG_IDX	_sc13_msg28
		MSG_IDX	_sc13_msg29
		MSG_IDX	_sc13_msg2A
		MSG_IDX	_sc13_msg2B
		MSG_IDX	_sc13_msg2C
		MSG_IDX	_sc13_msg2D
		MSG_IDX	_sc13_msg2E
_sc13_msg00:
		.BYTE	_JA,__,_za,_b,_ra,_l,_s_ja,__,_na,__,_go,_ru,__,_m,_u,_s,_o,_ra,__,_i,_ret
		.BYTE	_na,_sh,_jo,_l_,_Tjecuo,_dot,_ret
		.BYTE	_ret
		.BYTE	_Tjecuo,_ddt__quo,_an0,_A,_str,_h,_a,_str,_h,_a,_dot_dot_dot,_aof,_quo,_eol
_sc13_msg01:
		.BYTE	_Kanjeda,_ddt__quo,_an0,_CH,_to,__,_t,_u,_t,__p,_ro,_i,_z,_o,_sh,_lo,_que,_aof,_quo,_ret
		.BYTE	_ret
		.BYTE	_Tjecuo,_ddt__quo,_an1,_A,_h,_dot_dot_dot,__,_T,_ji,__p,_ro,_p,_u,_st,_i,_l,_ret
		.BYTE	_v,_s,_e,__s,_a,_mo,_e_,_i,_n,_te,_re,_s,_no,_e,_col_,_no,__s,_ko,_ro,_ret
		.BYTE	_mo,_zh,_e,_t,__b,_u,_de,_t,__,_e,_sch,_jo,__,_i,_n,_te,_re,_s,_ne,_e,_dot,_aof,_quo,_eol
_sc13_msg02:
		.BYTE	_Kanjeda,_ddt,__,_an0,_JA,__,_ne,__p,_e,_re,_st,_a,_va,_l_,_za,_ret
		.BYTE	_te,_b,_ja_,_vo,_l,_no,_va,_t_mz,_s_ja,_dot_dot_dot,__,_D,_u,_m,_a,_l,_col_,_ne,_ret
		.BYTE	_po,_p,_a,_l_,_li,__,_t,_ji,__,_g,_de,__v,__b,_e,_d,_u,__i_,_ne,_ret
		.BYTE	_h,_n,_ji,_ch,_e,_sh,_mz_,_li,_col_,_ka,_k,__,_di,_t,_ja,_dot,_aof,_quo,_eol
_sc13_msg03:
		.BYTE	_Tjecuo,_ddt,__,_an1,_Kanjeda,_dot_dot_dot,__,_T,_ji,__v,_s,_e,_g,_da,__b,_ji,_l,_ret
		.BYTE	_za,_no,_z,_o,_j,__v,__,_za,_d,_ni,_c,_e,_dot,__,_S,__,_te,_h,__,_po,_r,_col,_ret
		.BYTE	_ka,_k,__,_m,_ji,__b,_ji,_li,__,_de,_t_mz,_m,_i,_col_,_t,_ji,__,_m,_no,_j,_ret
		.BYTE	_ko,_m,_a,_n,_d,_u,_e,_sh,_mz,_col_,_v,_s,_e,_g,_da,__,_go,_vo,_ri,_sh,_mz,_ret
		.BYTE	_m,_ne,_col_,_ch,_to,__,_de,_la,_t_mz,_dot,__,_I,__v,_s,_e,_g,_da,_ret
		.BYTE	_v,_e,_de,_sh,_mz_,_s,_e,_b,_ja_,_ka,_k,__,_na,_ch,_a,_l,_mz,_ni,_k,_dot,_aof,_quo,_eol
_sc13_msg04:
		.BYTE	_Kanjeda,_ddt__quo,_an0,_P,_o,_h,_o,_zh,_e,_col_,_te,_p,_e,_r,_mz,__i_,_t,_ji,_ret
		.BYTE	_st,_a,_l_,_na,_ch,_a,_l,_mz,_ni,_ko,_m,_dot_dot_dot,_ret
		.BYTE	_N,_a,_ch,_a,_l,_mz,_ni,_ko,_m,__,_je,_to,_j,__,_k,_u,_ch,_i,__,_m,_u,_s,_o,_ra,_exc,_aof,_quo,_ret
		.BYTE	_ret
		.BYTE	_Tjecuo,_ddt__quo,_an1,_Kanjeda,_exc,_dot,_dot,_aof,_quo,_eol
_sc13_msg1F:
		.BYTE	_Kanjeda,_ddt__quo,_an0,_JE,_j,_col_,_o,_s,_to,_ro,_zh,_ne,_e,_exc,_ret
		.BYTE	_Z,_de,_s,_mz_,_v,_s,_jo,__,_e,_l,_e_,_de,_r,_zh,_i,_t,_s_ja,_exc,_aof,_quo,_ret
		.BYTE	_ret
		.BYTE	_Tjecuo,_ddt__quo,_an1,_U,_m,_ri,_dot_dot_dot,_aof,_quo,_eol
_sc13_msg06:
		.BYTE	_JA,__,_o,_t,_p,_r,_ji,_g,_n,_u,_l,_col_,_no,__s,_po,_t,_k,_n,_u,_l,_s_ja,__,_o,_ret
		.BYTE	_b,_u,_l,_ji,_zh,_ni,_k,_dot,_eol
_sc13_msg0F:
		.BYTE	_Kanjeda,_ddt__quo,_an0,_CH,_jo,_r,_t,_exc,__,_JE,_to,__,_ne,_ch,_e,_st,_no,_col,_ret
		.BYTE	_Tjecuo,_exc,__,_D,_e,_ri,_s,_mz_,_go,_l,_ji,_m,_i,__,_ru,_ka,_m,_i,_exc,_aof,_quo,_eol
_sc13_msg08:
		.BYTE	_Tjecuo,_ddt__quo,_an1,_A,__,_m,_ne,__,_ta,_k,__,_n,_ra,_v,_i,_t,_s_ja,_dot_dot_dot,_ret
		.BYTE	_Kanjeda,_dot_dot_dot,_ret
		.BYTE	_T,_e,_p,_e,_r,_mz_,_t,_ji,__,_po,_ni,_m,_a,_e,_sh,_mz,_col_,_ka,_ko,_vo,_ret
		.BYTE	_je,_to,__,_str,__b,_ji,_t_mz,__,_m,_a,_l,_en,_mz,_ki,_m,__,_i,_ret
		.BYTE	_b,_e,_s,_s,_i,_l,_mz,_n,_ji,_m,_que,_aof,_quo,_eol
_sc13_msg28:
		.BYTE	_Tjecuo,_ddt__quo,_A,_que,__,_CH,_to,__,_je,_to,__,_za,__s,_ve,_t,_que_quo,_eol
_sc13_msg10:
		.BYTE	_V,_o,_k,_ru,_g,__,_Tjecuo,__,_po,_ja,_v,_i,_lo,_s,_mz,_ret
		.BYTE	_s,_ve,_ch,_e,_ni,_e,_col_,_s,__,_ka,_zh,_d,_ji,_m,__,_m,_g,_no,_ve,_ni,_e,_m,_ret
		.BYTE	_ra,_z,_go,_ra,_ja,_s,_mz_,_v,_s,_e_,_ja,_r,_ch,_e,__i_,_ja,_r,_ch,_e,_dot,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_A,_que,_dot,_dot,_quo,_eol
_sc13_msg11:
		.BYTE	_JE,_to,__b,_ji,_l_,_la,_z,_e,_r,_n,_ji,_j,__,_l,_u,_ch,_col,_ret
		.BYTE	_v,_ji,_p,_u,_sch,_en,_n,_ji,_j,__s,_p,_u,_t,_ni,_ko,_m,__,_S,_O,_L,__,_po,_ret
		.BYTE	_p,_ri,_ka,_z,_u,__,_P,_o,_l,_ko,_v,_ni,_ka,_dot,_eol
_sc13_msg12:
		.BYTE	_V,__,_za,_me,_sh,_a,_te,_l,_mz,_st,_ve,_col_,_ja_,_na,_ch,_a,_l,_ret
		.BYTE	_u,_b,_e,_g,_a,_t_mz,_dot,__,_G,_ru,_d,_ji,__,_m,_u,_s,_o,_ra,__,_vo,_k,_ru,_g,_ret
		.BYTE	_m,_en,_ja_,_u,_g,_ro,_zh,_a,_ju,_sch,_e_,_d,_ro,_zh,_a,_li,_dot,_eol
_sc13_msg13:
		.BYTE	_Tjecuo,__v,_ji,_p,_r,_ja,_m,_i,_l,_s_ja,__,_na,__,_go,_re,__,_i,_z,_ret
		.BYTE	_o,_b,_lo,_m,_ko,_v,__,_vo,__v,_e,_s,_mz_,_ro,_st,_dot,_eol
_sc13_msg09:
		.BYTE	_N,_o,_col_,_ka,_k,__,_to,_l,_mz,_ko,__,_o,_n,__,_po,_p,_ja,_ti,_l,_s_ja,_col,_ret
		.BYTE	_la,_z,_e,_r,_n,_ji,_j,__,_l,_u,_ch,__,_o,_t,_re,_za,_l_,_e,_go,_ret
		.BYTE	_p,_ra,_v,_u,_ju,__,_ru,_k,_u,_dot,_eol
_sc13_msg14:
		.BYTE	_K,_a,_ne,_da,_ddt__quo,_JE,_j,_col_,_Tjecuo,_dot_dot_dot,_quo,_ret
		.BYTE	_ret
		.BYTE	_JA,__,_po,_d,_n,_ja,_l_,_o,_di,_n,__,_i,_z,__,_ka,_m,_ne,_j,__,_i,_ret
		.BYTE	_b,_ro,_s,_i,_l_,_e,_go,__v,__,_Tjecuo,_dot,_ret
		.BYTE	_ret
		.BYTE	_K,_a,_ne,_da,_ddt__quo,_U,_f,_exc_quo,_eol
_sc13_msg15:
		.BYTE	_S,_ve,_t,__v,_d,_ru,_g,__s,_no,_va,__,_na,_ch,_a,_l,_ret
		.BYTE	_ko,_n,_c,_en,_t,_ri,_ro,_va,_t_mz,_s_ja,_col_,_de,_la,_ja_,_v,_s,_jo,_ret
		.BYTE	_vo,_k,_ru,_g,__,_ja,_r,_ko,_str,_b,_e,_l,_ji,_m,_dot,_eol
_sc13_msg16:
		.BYTE	_K,_o,_g,_da,__,_ja_,_o,_t,_k,_r,_ji,_l_,_g,_la,_za,_col_,_v,_ret
		.BYTE	_vo,_z,_d,_u,_h,_e,__p,_a,_ri,_li,__,_o,_b,_lo,_m,_ki,_dot,__,_Tjecuo,_ret
		.BYTE	_s,_o,_z,_da,_l,__b,_a,_r,_mz,_e,_r,__i_,_ra,_s,_s,_e,_ja,_l_,_l,_u,_ch,_dot,_eol
_sc13_msg17:
		.BYTE	_Tjecuo,_ddt__quo,_CH,_jo,_r,_t,_dot_dot_dot,_quo,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_CH,_to,__,_je,_to,_que_quo,_eol
_sc13_msg0B:
		.BYTE	_Tjecuo,__p,_r,_ji,_g,_n,_u,_l,__v,_ve,_r,_h,__i_,_po,_ki,_n,_u,_l,_ret
		.BYTE	_a,_t,_mo,_s,_f,_e,_ru,_col_,_na,_me,_re,_va,_ja,_s,_mz,_ret
		.BYTE	_u,_ni,_ch,_to,_zh,_i,_t_mz,__,_S,_O,_L,_dot,_eol
_sc13_msg18:
		.BYTE	_Kanjeda,_ddt__quo,_O,_j,_dot,_quo,_ret
		.BYTE	_ret
		.BYTE	_B,_a,_r,_mz,_e,_r,__,_i,_z,__,_o,_b,_lo,_m,_ko,_v,__,_u,_p,_a,_l,_dot,_eol
_sc13_msg27:
		.BYTE	_Kanjeda,_ddt__quo,_A,_str,_a,_exc_quo,_ret
		.BYTE	_ret
		.BYTE	_JA,__,_po,_b,_e,_zh,_a,_l_,_ch,_e,_re,_z,__,_o,_b,_lo,_m,_ki,_dot,_eol
_sc13_msg19:
		.BYTE	_B,_a,_c,_exc,__,_SH,_str,_sh,_u,_h,_exc,_ret
		.BYTE	_ret
		.BYTE	_N,_e_,_u,_s,_p,_e,_l_,_ja_,_o,_po,_m,_ni,_t_mz,_s_ja,_col_,_o,_b,_lo,_m,_ki,_ret
		.BYTE	_b,_ji,_li,__,_u,_ni,_ch,_to,_zh,_en,_ji,__,_la,_z,_e,_ro,_m,_dot,_eol
_sc13_msg29:
		.BYTE	_L,_a,_z,_e,_r,_n,_ji,_j,__,_l,_u,_ch,__,_u,_da,_ri,_l,__v,__,_g,_ru,_d,_u,_ret
		.BYTE	_ka,_m,_ne,_j,_dot,_eol
_sc13_msg1A:
		.BYTE	_O,_n,__,_po,_d,_o,_sh,_jo,_l_,_u,_zh,_e_,_ne,_ve,_ro,_ja,_t,_no,_ret
		.BYTE	_b,_li,_z,_ko,_dot,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_S,_p,_a,_s,_i,__,_m,_en,_ja,_col_,_Kej,_exc_quo,_eol
_sc13_msg26:
		.BYTE	_Kaj,__i_,_Kej,__,_za,_me,_ti,_li,__,_m,_en,_ja,_dot,_ret
		.BYTE	_ret
		.BYTE	_Kej,_ddt__quo,_Kanjeda,_exc_quo,_ret
		.BYTE	_ret
		.BYTE	_Kaj,_ddt__quo,_S,_a,_di,_s,_mz,_exc_quo,_eol
_sc13_msg1E:
		.BYTE	_Kanjeda,_ddt__quo,_T,_u,_t,__,_ne,_t,__,_me,_st,_a,_dot_dot_dot,_quo,_ret
		.BYTE	_ret
		.BYTE	_Kej,_ddt__quo,_D,_a,_va,_j,_col_,_b,_ji,_st,_ro,_exc_quo,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_N,_u,_col_,_la,_d,_no,_dot_dot_dot,_quo,_eol
_sc13_msg2C:
		.BYTE	_SH,_u,_h,_dot_dot_dot,_ret
		.BYTE	_ret
		.BYTE	_L,_u,_ch,__p,_ro,_n,_jo,_s,_s_ja,__,_na,_d,__,_na,_m,_i,__i_,_po,_to,_m,_ret
		.BYTE	_i,_s,_ch,_e,_z,_dot,_eol
_sc13_msg2A:
		.BYTE	_R,_ja,_d,_o,_m,__s,__,_za,_h,_o,_d,_ja,_sch,_i,_m,__s,_o,_l,_n,_c,_e,_m,_ret
		.BYTE	_mo,_zh,_no,__b,_ji,_lo,__,_u,_v,_i,_de,_t_mz,__s,_ve,_r,_ka,_ju,_sch,_u,_ju,_ret
		.BYTE	_z,_ve,_z,_d,_u,_dot,_ret
		.BYTE	_ret
		.BYTE	_V,_oennji,_j,_ddt__quo,_S,_p,_u,_t,_ni,_ko,_v,_ji,_j,_ret
		.BYTE	_o,_r,_b,_i,_ta,_l,_mz,_n,_ji,_j,__,_la,_z,_e,_r,_dot_dot_dot,_quo,_eol
_sc13_msg2B:
		.BYTE	_P,_o,_l,_ko,_v,_ni,_k,_ddt__quo,_an0,_Tjecuo,__,_u,_ni,_ch,_to,_zh,_i,_l,_ret
		.BYTE	_S,_O,_L,_dot_dot_dot,__,_O,_n,__,_na,_s,_to,_l,_mz,_ko,__s,_i,_l,_jo,_n,_que,_aof,_quo,_eol
_sc13_msg2D:
		.BYTE	_T,_a,_ka,_s,_i,_ddt__quo,_K,_o,_g,_da,__,_mo,_sch,_mz_,_Tjecuo,_ret
		.BYTE	_d,_o,_st,_i,_g,_ne,_t,__s,_vo,_e,_go,__p,_i,_ka,_dot_dot_dot,_quo,_ret
		.BYTE	_ret
		.BYTE	_M,_a,_s,_a,_ru,_ddt__quo,_dot_dot_dot,_m,_ji,__,_po,_p,_ji,_ta,_e,_m,_s_ja,_dot_dot_dot,_ret
		.BYTE	_no,__,_m,_ji,__,_ne,__,_u,_ve,_re,_n,_ji,_col_,_ch,_to,__,_je,_to,_ret
		.BYTE	_s,_ra,_b,_o,_ta,_e,_t,_dot_dot_dot,_quo,_eol
_sc13_msg2E:
		.BYTE	_K,_i,_jo,_ko,_ddt__quo,_an0,_M,_ji,__,_z,_na,_e,_m,_col_,_ch,_to,__b,_u,_d,_u,_sch,_e,_e,_ret
		.BYTE	_ne,__,_o,_b,_ja,_za,_te,_l,_mz,_no,__,_d,_o,_l,_zh,_no,__,_i,_d,_ti,__,_po,_ret
		.BYTE	_o,_d,_no,_m,_u,__,_k,_u,_r,_s,_u,_dot,__,_D,_o,_l,_zh,_no,__b,_ji,_t_mz,__,_to,_ret
		.BYTE	_b,_u,_d,_u,_sch,_e,_e,_col_,_ko,_to,_ro,_e_,_m,_ji,__v,_ji,_b,_e,_re,_m,_ret
		.BYTE	_s,_a,_m,_i,_dot,__,_D,_e,_lo,__,_za,__,_na,_m,_i,_dot,_aof,_quo,_eol
_sc13_msg05:
		.BYTE	_JA,__v,_ji,_st,_re,_li,_l,_col,__i_,_la,_z,_e,_r,__,_po,_p,_a,_l,__v,_ret
		.BYTE	_ko,_n,_te,_j,_ne,_r,__s,__,_o,_b,_ra,_z,_c,_o,_m,_dot,_eol
_sc13_msg24:
		.BYTE	_V,_ne,_za,_p,_no,_col_,_ko,_n,_te,_j,_ne,_r,__s,__,_o,_b,_ra,_z,_c,_o,_m,_ret
		.BYTE	_v,_ji,_p,_u,_st,_i,_l_,_ja,_r,_ki,_j,__s,_ve,_t,_dot,_eol
_sc13_msg0D:
		.BYTE	_JA,__v,_ji,_st,_re,_li,_l_,_i,_z,__,_la,_z,_e,_ra,_col_,_no,_ret
		.BYTE	_ne,__,_po,_p,_a,_l,__v,__,_Tjecuo,_dot_dot_dot,_eol
_sc13_msg0A:
		.BYTE	_B,_sh,_str,_sh,_exc,_ret
		.BYTE	_ret
		.BYTE	_Tjecuo,__,_po,_st,_a,_v,_i,_l,__b,_a,_r,_mz,_e,_r,_dot,_eol
_sc13_msg0C:
		.BYTE	_Kanjeda,_ddt__quo,_JA,__,_po,_p,_a,_l,__v,__,_ne,_go,_dot_dot_dot,__,_N,_o,_ret
		.BYTE	_o,_n,__s,_u,_me,_l_,_po,_st,_a,_v,_i,_t_mz,__b,_a,_r,_mz,_e,_r,_col,_ret
		.BYTE	_z,_na,_ch,_i,_t,__,_o,_n,__v,_s,_jo,__,_e,_sch,_jo,__,_zh,_i,_v,_dot_dot_dot,_quo,_eol
_sc13_msg0E:
		.BYTE	_Kanjeda,_ddt__quo,_H,_m,_que,__,_B,_a,_ta,_re,_ja,_ret
		.BYTE	_s,_d,_o,_h,_la,_que,_exc_quo,_ret
		.BYTE	_ret
		.BYTE	_Tjecuo,_ddt__quo,_V,__,_ch,_jo,_m,__,_de,_lo,_col,_ret
		.BYTE	_Kanjeda,_que,_dot,_dot,_quo,_eol
_sc13_msg07:
		.BYTE	_K,_a,_ne,_da,__p,_r,_ji,_g,_n,_u,_l_,_na,__,_Tjecuo,_col_,_no,_ret
		.BYTE	_b,_ji,_l,__s,_b,_i,_t,__,_u,_da,_r,_no,_j,__,_vo,_l,_no,_j,_dot_dot_dot,_eol
_sc13_msg1B:
		.BYTE	_S,_k,_vo,_z,_mz_,_z,_v,_u,_k,__v,_z,_r,_ji,_va,__,_ja,_ret
		.BYTE	_u,_s,_l,_ji,_sh,_a,_l_,_k,_ri,_k,__,_K,_a,_ja,_dot,_eol
_sc13_msg1C:
		.BYTE	_Kej,__v,_me,_st,_e,__s,__,_K,_a,_e,_m,__,_na,__,_e,_go,__b,_a,_j,_k,_e,_ret
		.BYTE	_vo,_z,_ni,_k,_li,__p,_e,_re,_d,_o,__,_m,_no,_j,_dot,_eol
_sc13_msg1D:
		.BYTE	_Kanjeda,_ddt__quo,_Kaj,_exc,__,_Kej,_exc_quo,_eol
_sc13_msg20:
		.BYTE	_JA,__,_n,_ji,_r,_n,_u,_l,__v,__,_g,_ru,_d,_u,__,_o,_b,_lo,_m,_ko,_v,_dot,_eol
_sc13_msg21:
		.BYTE	_B,_a,_h,_exc,_ret
		.BYTE	_ret
		.BYTE	_L,_u,_ch,__,_u,_da,_ri,_l,__p,_r,_ja,_mo,__v,__,_K,_a,_n,_je,_d,_u,_dot,_eol
_sc13_msg22:
		.BYTE	_Kanjeda,_ddt__quo,_I,_n,_te,_re,_s,_no,_col_,_ka,_k,__,_da,_l,_e,_ko,_ret
		.BYTE	_o,_n,__p,_ro,_j,_d,_jo,_t,_que_quo,_ret
		.BYTE	_ret
		.BYTE	_JA,__,_po,_s,_mo,_t,_re,_l_,_na,__,_l,_u,_ch,_col_,_ch,_to,_b,_ji,_ret
		.BYTE	_v,_ji,_ja,_s,_ni,_t_mz,__,_je,_to,_dot,_eol
_sc13_msg23:
		.BYTE	_Kanjeda,_ddt__quo,_A,_str,_a,_str,_a,_j,_exc_quo,_ret
		.BYTE	_ret
		.BYTE	_JA,__,_za,_k,_ri,_ch,_a,_l,_col_,_ko,_g,_da,__,_l,_u,_ch,_ret
		.BYTE	_p,_ri,_b,_li,_z,_i,_l,_s_ja,_dot,_eol
_sc13_msg25:
		.BYTE	_Kanjeda,_ddt__quo,_Kej,_col_,_ne,__,_h,_o,_ch,_e,_sh,_mz,_ret
		.BYTE	_v,_st,_re,_ch,_a,_t_mz,_s_ja,__s,_o,__,_m,_no,_j,_que_quo,_eol

		SECTION_END		F13
