
		SECTION_START	F15

		MSG_START	_scene15_msg_lib
		MSG_IDX	_sc15_msg00
		MSG_IDX	_sc15_msg01
		MSG_IDX	_sc15_msg02
		MSG_IDX	_sc15_msg03
		MSG_IDX	_sc15_msg04
		MSG_IDX	_sc15_msg05
		MSG_IDX	_sc15_msg06
		MSG_IDX	_sc15_msg07
		MSG_IDX	_sc15_msg08
		MSG_IDX	_sc15_msg09
		MSG_IDX	_sc15_msg0B
		MSG_IDX	_sc15_msg0C
		MSG_IDX	_sc15_msg0D
		MSG_IDX	_sc15_msg0E
		MSG_IDX	_sc15_msg0F
		MSG_IDX	_sc15_msg10
		MSG_IDX	_sc15_msg11
		MSG_IDX	_sc15_msg12
		MSG_IDX	_sc15_msg13
		MSG_IDX	_sc15_msg14
		MSG_IDX	_sc15_msg15
		MSG_IDX	_sc15_msg16
		MSG_IDX	_sc15_msg17
		MSG_IDX	_sc15_msg18
		MSG_IDX	_sc15_msg19
		MSG_IDX	_sc15_msg1A
		MSG_IDX	_sc15_msg1B
		MSG_IDX	_sc15_msg1C
		MSG_IDX	_sc15_msg1D
		MSG_IDX	_sc15_msg1E
		MSG_IDX	_sc15_msg1F
		MSG_IDX	_sc15_msg20
		MSG_IDX	_sc15_msg21
		MSG_IDX	_sc15_msg22
		MSG_IDX	_sc15_msg23
		MSG_IDX	_sc15_msg24
		MSG_IDX	_sc15_msg25
		MSG_IDX	_sc15_msg27
		MSG_IDX	_sc15_msg29
		MSG_IDX	_sc15_msg2A
		MSG_IDX	_sc15_msg2B
		MSG_IDX	_sc15_msg2D
		MSG_IDX	_sc15_msg33
		MSG_IDX	_sc15_msg34
		MSG_IDX	_sc15_msg35
		MSG_IDX	_sc15_msg36
		MSG_IDX	_sc15_msg37
		MSG_IDX	_sc15_msg38
		MSG_IDX	_sc15_msg9D
		MSG_IDX	_sc15_msgAC
_sc15_msg00:
		.BYTE	_V,_r,_str,_ru,_m,_dot,_ret
		.BYTE	_ret
		.BYTE	_S,__,_la,_z,_e,_ro,_m,__,_na,_p,_e,_re,_ve,_s,__,_ja_,_s,_no,_va,_ret
		.BYTE	_po,_e,_h,_a,_l_,_na,__,_O,_li,_m,_p,_i,_j,_s,_ki,_j,__,_st,_a,_di,_o,_n,_dot,_eol
_sc15_msg01:
		.BYTE	_N,_a,_ko,_ne,_c,__,_ja_,_na,_sh,_jo,_l_,_Tjecuo,_exc,_eol
_sc15_msg02:
		.BYTE	_N,_a,__,_me,_st,_e,__p,_ra,_vo,_j,__,_ru,_ki,__,_Tjecuo,_ret
		.BYTE	_b,_ji,_la,__,_st,_ra,_n,_na,_ja_,_m,_a,_s,_s,_a,_col,__i_,_o,_na,_ret
		.BYTE	_a,_ta,_ko,_va,_la,__s,_o,_l,_da,_t,_dot,_eol
_sc15_msg1F:
		.BYTE	_JA,__b,_i,_l,__s,_vo,_i,_m,__,_la,_z,_e,_ro,_m,__,_po,_ret
		.BYTE	_s,_g,_u,_st,_k,_u,_col_,_o,_k,_ru,_zh,_i,_v,_sh,_e,_m,_u,__v,_oennji,_h,_dot,_eol
_sc15_msg9D:
		.BYTE	_Tjecuo,_ddt__quo,_an1,_Kanjeda,_que,_exc,_aof,_quo,_eol
_sc15_msg04:
		.BYTE	_JA,__s,_no,_va,__,_na,_st,_ro,_i,_l_,_la,_z,_e,_r,_n,_ji,_j,__,_l,_u,_ch,_dot,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_an0,_Tjecuo,_col_,_ja_,_po,_lo,_zh,_u,_ret
		.BYTE	_ko,_ne,_c,__,_t,_vo,_i,_m,__,_st,_ra,_da,_ni,_ja,_m,_exc,_aof,_quo,_eol
_sc15_msg07:
		.BYTE	_Kanjeda,_ddt__quo,_M,_en,_ja_,_u,_zh,_e_,_d,_o,_st,_a,_lo,_ret
		.BYTE	_za,_no,_s,_ch,_i,_vo,_e_,_po,_ve,_de,_ni,_e_,_Tjecuo,_dot,_quo,_eol
_sc15_msg09:
		.BYTE	_V,__,_o,_t,_ch,_a,_ja,_ni,_i,__,_ja_,_b,_ro,_s,_i,_l,__v,__,_Tjecuo,_ret
		.BYTE	_s,_vo,_i,_m,__,_la,_z,_e,_ro,_m,_exc,_ret
		.BYTE	_ret
		.BYTE	_I,__p,_ro,_m,_a,_za,_l,_dot_dot_dot,_eol
_sc15_msg0B:
		.BYTE	_S,_t,_ra,_n,_na,_ja_,_sh,_t,_u,_ka,__,_na,__,_e,_go,__,_ru,_k,_e,_ret
		.BYTE	_na,_ch,_a,_la,__,_ra,_st,_i,_dot,__,_O,_na,__,_u,_zh,_e,_ret
		.BYTE	_o,_b,_vo,_lo,_k,_la,__s,_o,_b,_o,_j,__s,_o,_l,_da,_t,_dot,_eol
_sc15_msg0C:
		.BYTE	_R,_a,_z,_ve,__,_e,_m,_u,__,_ne,__,_o,_to,_r,_va,_lo,__,_ru,_k,_u,_ret
		.BYTE	_d,_o,__,_je,_to,_go,_que,_ret
		.BYTE	_ret
		.BYTE	_dot_dot_dot,_ne,__,_mo,_g,_lo,__,_zh,_e_,_m,_ne,__,_po,_ka,_za,_t_mz,_s_ja,_que,_eol
_sc15_msg0D:
		.BYTE	_T,_o,_ch,_no,_dot_dot_dot,__,_U,__,_m,_en,_ja_,_e,_s,_t_mz,__,_z,_e,_r,_ka,_lo,_col,_ret
		.BYTE	_ko,_to,_ro,_e_,_da,_la,__,_m,_ne,__,_Kej,_dot,_eol
_sc15_msg0E:
		.BYTE	_JA,__b,_ro,_s,_i,_l_,_z,_e,_r,_ka,_lo,__,_r,_ja,_d,_o,_m,__s,_ret
		.BYTE	_Tjecuo,_dot,_eol
_sc15_msg0F:
		.BYTE	_JA,__,_po,_sh,_jo,_l,__v,_e,_r,_n,_u,_t_mz,__,_z,_e,_r,_ka,_lo,_col,_ret
		.BYTE	_ko,_to,_ro,_e,__b,_ro,_s,_i,_l,_dot,_eol
_sc15_msg10:
		.BYTE	_L,_a,_z,_e,_r,__,_o,_t,_ra,_z,_i,_l,_s_ja,__,_o,_t,__,_z,_e,_r,_ka,_la,__,_i,_ret
		.BYTE	_p,_ro,_sh,_e,_l_,_m,_i,_mo,__,_te,_la,__,_Tjecuo,_exc,_eol
_sc15_msg05:
		.BYTE	_Kanjeda,_ddt__quo,_H,_o,_ro,_sh,_o,_exc,_ret
		.BYTE	_P,_o,_l,_n,_ji,_j,__v,_p,_e,_r,_jo,_d,_exc_quo,_ret
		.BYTE	_ret
		.BYTE	_JA,__p,_ri,_go,_to,_v,_i,_l,__b,_a,_j,_k,_col_,_ch,_to,_b,_ji,_ret
		.BYTE	_v,_re,_za,_t_mz,_s_ja,__v,__,_Tjecuo,_dot,_eol
_sc15_msg06:
		.BYTE	_N,_o,__,_ko,_l,_e,_s,_o,__,_za,_st,_r,_ja,_lo,__v,__,_m,_u,_s,_o,_re,_ret
		.BYTE	_i,__,_ja_,_s,_l,_e,_te,_l,__s,__b,_a,_j,_ka,_dot,_eol
_sc15_msg08:
		.BYTE	_Tjecuo,_ddt__quo,_an0,_Kanjeda,_exc,__,_T,_e,_p,_e,_r,_mz_,_t,_vo,_i,_m,_ret
		.BYTE	_st,_ra,_da,_ni,_ja,_m,__p,_ri,_sh,_jo,_l_,_ko,_ne,_c,_exc,_aof,_quo,_eol
_sc15_msg11:
		.BYTE	_P,_re,_v,_ra,_ti,_v,_sh,_i,_j,_s_ja,__v,__,_mo,_n,_st,_ra,_ret
		.BYTE	_Tjecuo,__,_m,_u,_ch,_i,_te,_l,_mz,_no,__,_za,_s,_to,_na,_l,_dot,_eol
_sc15_msg12:
		.BYTE	_SH,_str,_sh,_u,_h,_exc,_ret
		.BYTE	_ret
		.BYTE	_L,_a,_z,_e,_r,__,_o,_t,_ra,_z,_i,_l,_s_ja,__,_o,_t,__,_z,_e,_r,_ka,_la,_dot,_eol
_sc15_msg13:
		.BYTE	_L,_a,_z,_e,_r,__,_ne,__,_po,_p,_a,_l,__v,__,_Tjecuo,_exc,_eol
_sc15_msg14:
		.BYTE	_N,_e_,_za,_d,_u,_m,_ji,_va,_ja,_s,_mz,_col_,_ja_,_o,_t,_k,_r,_ji,_l_,_o,_go,_n,_mz,_ret
		.BYTE	_po,__,_Tjecuo,_col_,_p,_re,_v,_ra,_ti,_v,_sh,_e,_go,_s_ja,__v,_ret
		.BYTE	_mo,_n,_st,_ra,_dot,_eol
_sc15_msgAC:
		.BYTE	_L,_a,_z,_e,_r,__,_po,_p,_a,_l,__v,__p,_ra,_v,_u,_ju,__,_ru,_k,_u,_ret
		.BYTE	_Tjecuo,_exc,_eol
_sc15_msg16:
		.BYTE	_N,_o,_col_,_o,_t,_s,_ko,_ch,_i,_v,_col_,_o,_n,__v,_z,_m,_ji,_l,__v,_ret
		.BYTE	_vo,_z,_d,_u,_h,_col_,_za,_te,_m,__,_za,_v,_i,_s,__,_na,_ret
		.BYTE	_m,_g,_no,_v,_en,_mz,_e,__i_,_s,_p,_i,_ki,_ro,_va,_l,__v,_ni,_z,_dot,_eol
_sc15_msg17:
		.BYTE	_N,_a,__,_po,_l,_no,_j,__s,_ko,_ro,_st,_i,__,_ja_,_s,_da,_l,_ret
		.BYTE	_na,_za,_d,__v,__s,_to,_ro,_n,_u,__,_g,_ru,_d,_ji,_ret
		.BYTE	_o,_b,_lo,_m,_ko,_v,_dot,_eol
_sc15_msg18:
		.BYTE	_O,_ka,_za,_v,_sh,_i,_s,_mz_,_v,_b,_li,_z,_i,__,_Tjecuo,_col_,_ja,_ret
		.BYTE	_v,_ji,_n,_u,_di,_l_,_e,_go,__,_a,_ta,_ko,_va,_t_mz,__,_m,_en,_ja,_ret
		.BYTE	_s,_vo,_i,_m,__,_te,_lo,_m,_dot,__,_L,_o,_zh,_e_,_st,_a,_di,_o,_na,_ret
		.BYTE	_b,_ji,_lo,__,_u,_ni,_ch,_to,_zh,_e,_no,__,_po,_l,_no,_s,_t_mz,_ju,_dot,_eol
_sc15_msg19:
		.BYTE	_N,_a,__,_po,_l,_p,_u,_ti,__,_ch,_e,_re,_z,__,_o,_b,_lo,_m,_ki,__,_ja,_ret
		.BYTE	_na,_zh,_a,_l_,_na,__,_to,_r,_mo,_za,_dot,_eol
_sc15_msg2B:
		.BYTE	_JA,__,_po,_p,_ji,_ta,_l,_s_ja,__,_e,_sch,_jo,__,_ra,_z,__,_d,_o,_st,_a,_t_mz,_ret
		.BYTE	_e,_go,__i_,_na,_p,_ra,_v,_i,_l_,_na,__,_ne,_go,__,_la,_z,_e,_r,_dot,_eol
_sc15_msg1A:
		.BYTE	_Tjecuo,__,_ru,_h,_n,_u,_l,__i_,_na,_ch,_a,_l,_ret
		.BYTE	_d,_jo,_r,_g,_a,_t_mz,_s_ja,_dot,_eol
_sc15_msg20:
		.BYTE	_L,_a,_z,_e,_r,__,_po,_p,_a,_l,__v,__,_e,_go,__p,_ra,_v,_u,_ju,__,_ru,_k,_u,_col,_ret
		.BYTE	_i,__,_ta,__,_na,_ch,_a,_la,__,_st,_ra,_n,_no,__,_ra,_z,_b,_u,_h,_a,_t_mz,_dot,_eol
_sc15_msg1B:
		.BYTE	_Tjecuo,__,_st,_a,_l,__p,_re,_v,_ra,_sch,_a,_t_mz,_s_ja,__v,_ret
		.BYTE	_mo,_n,_st,_ra,_dot,__,_O,_n,__,_na,_ch,_a,_l,__b,_ji,_st,_ro,_ret
		.BYTE	_ra,_st,_i,_col_,_ne,__v,__s,_o,_s,_to,_ja,_ni,_i,_ret
		.BYTE	_ko,_n,_t,_ro,_li,_ro,_va,_t_mz,__,_po,_to,_k,__s,_vo,_e,_j,_ret
		.BYTE	_je,_ne,_r,_g,_i,_i,_dot,_eol
_sc15_msg1C:
		.BYTE	_V,_ne,_za,_p,_no,_col_,_ra,_z,_d,_u,_v,_sh,_i,_e,_s_ja,__,_m,_ji,_sh,_c,_ji,_ret
		.BYTE	_p,_ro,_r,_va,_li,_s,_mz_,_ch,_e,_re,_z,__,_e,_go,__,_ko,_zh,_u,_dot,_eol
_sc15_msg1D:
		.BYTE	_Tjecuo,_ddt__quo,_an0,_Kanjeda,_dot_dot_dot,_ret
		.BYTE	_p,_dot_dot_dot,_po,_mo,_g,_i,__,_m,_ne,_dot_dot_dot,_ret
		.BYTE	_po,_zh,_a,_l,_u,_j,_st,_a,_dot_dot_dot,_aof,_quo,_eol
_sc15_msg15:
		.BYTE	_K,_a,_za,_lo,_s,_mz,_col_,_Tjecuo,__p,_re,_v,_ra,_sch,_a,_e,_t,_s_ja,__v,_ret
		.BYTE	_g,_i,_g,_a,_n,_t,_s,_ki,_j,__s,_g,_u,_s,_to,_k,__p,_lo,_ti,_dot,_eol
_sc15_msg1E:
		.BYTE	_Tjecuo,__,_na,_ch,_a,_l_,_po,_g,_lo,_sch,_a,_t_mz,__s,_ve,_t,_dot,_ret
		.BYTE	_ret
		.BYTE	_JA,__,_po,_d,_b,_e,_zh,_a,_l_,_k,__,_ne,_m,_u,_dot,_eol
_sc15_msg2D:
		.BYTE	_N,_o,__,_re,_b,_jo,_no,_k,__s,_h,_va,_ti,_l_,_mo,_ju,__,_ru,_k,_u,_dot,_ret
		.BYTE	_ret
		.BYTE	_T,_a,_ka,_s,_i,_ddt__quo,_N,_e,_t,_col_,_ne,__,_de,_la,_j,__,_je,_to,_go,_exc,_ret
		.BYTE	_E,_s,_li,__,_t,_ji,__s,_e,_j,_ch,_a,_s,__,_po,_j,_de,_sh,_mz,_col_,_p,_u,_ti,_ret
		.BYTE	_na,_za,_d,__,_ne,__b,_u,_de,_t,_dot,_quo,_eol
_sc15_msg21:
		.BYTE	_Kanjeda,_ddt__quo,_P,_re,_k,_ra,_ti,_exc_quo,_ret
		.BYTE	_ret
		.BYTE	_I,_z,__s,_g,_u,_st,_ka,__p,_lo,_ti,__v,_ji,_s,_ko,_ch,_i,_li,_ret
		.BYTE	_sch,_u,_p,_a,_l,_mz,_c,_a,_dot,__,_O,_ni,__,_o,_st,_a,_no,_v,_i,_li,__,_m,_en,_ja,_ret
		.BYTE	_i,__,_na,_ch,_a,_li,__,_za,_t,_ja,_g,_i,_va,_t_mz,__v,_n,_u,_t,_r,_mz,_dot,_eol
_sc15_msg22:
		.BYTE	_V,_n,_u,_t,_ri,__s,_g,_u,_st,_ka,__,_ja_,_s,_l,_ji,_sh,_a,_l,_ret
		.BYTE	_s,_to,_n,_ji,__,_Tjecuo,_dot,_eol
_sc15_msg23:
		.BYTE	_Tjecuo,_ddt__quo,_an0,_N,_e_,_mo,_g,_u,_dot_dot_dot,_ret
		.BYTE	_ko,_n,_t,_ro,_li,_ro,_va,_t_mz,_dot_dot_dot,_ret
		.BYTE	_te,_lo,_dot_dot_dot,_aof,_quo,_eol
_sc15_msg25:
		.BYTE	_K,_o,_n,_te,_j,_ne,_r,__s,__,_o,_b,_ra,_z,_c,_o,_m,__,_t,_re,_s,_n,_u,_l,_col,_ret
		.BYTE	_i,__,_zh,_i,_d,_ko,_s,_t_mz,__,_i,_z,_n,_u,_t,_ri,__s,__,_sh,_i,_p,_e,_ni,_e,_m,_ret
		.BYTE	_v,_ji,_r,_va,_la,_s,_mz_,_na,_ru,_zh,_u,_dot,_eol
_sc15_msg24:
		.BYTE	_R,_a,_st,_jo,_k,_sh,_a,_ja,_s_ja,__,_po,__,_po,_l,_u,__,_zh,_i,_d,_ko,_s,_t_mz,_ret
		.BYTE	_za,_b,_u,_r,_li,_la,_col_,_a,__,_po,_to,_m,__,_na,_ch,_a,_la,_ret
		.BYTE	_i,_z,_l,_u,_ch,_a,_t_mz,__,_st,_ra,_n,_n,_ji,_j,__s,_ve,_t,_dot,_eol
_sc15_msg27:
		.BYTE	_M,_a,_s,_a,_ru,_ddt__quo,_an0,_JE,_to,__,_A,_ki,_ra,_dot_dot_dot,_aof,_quo,_eol
_sc15_msg29:
		.BYTE	_S,_ve,_t,__,_o,_t,__,_A,_ki,_r,_ji,__v,_ji,_r,_va,_l,_s_ja,__,_na,_ru,_zh,_u,_dot,_ret
		.BYTE	_O,_n,__,_ra,_s,_p,_ro,_st,_ra,_n,_ja,_l,_s_ja,__v,_s,_e,__b,_o,_l,_mz,_sh,_e,_ret
		.BYTE	_i,__b,_o,_l,_mz,_sh,_e,_col_,_po,_ka,__,_ne,__,_na,_k,_r,_ji,_l,__v,_s,_ju,_ret
		.BYTE	_t,_ro,_i,_c,_u,_dot,_eol
_sc15_msg33:
		.BYTE	_JA,__,_st,_r,_ja,_h,_n,_u,_l_,_ru,_k,_u,__,_re,_b,_jo,_n,_ka,__,_i,_ret
		.BYTE	_po,_b,_e,_zh,_a,_l_,_k,__s,_ve,_t,_u,_dot,_eol
_sc15_msg34:
		.BYTE	_V,_me,_st,_e,__s,__,_re,_b,_jo,_n,_ko,_m,__,_ja_,_po,_b,_e,_zh,_a,_l,_ret
		.BYTE	_p,_ro,_ch,_mz_,_o,_t,__,_Tjecuo,_dot,_eol
_sc15_msg35:
		.BYTE	_JA,__p,_n,_u,_l_,_re,_b,_jo,_n,_ka,__i_,_po,_b,_e,_zh,_a,_l,_ret
		.BYTE	_v,__s,_to,_ro,_n,_u,__s,_ve,_ta,_dot,_eol
_sc15_msg36:
		.BYTE	_P,_re,_zh,_de,_col_,_ch,_e,_m,__s,_ve,_t,__,_m,_en,_ja,_ret
		.BYTE	_po,_g,_lo,_ti,_l,_col_,_ja_,_u,_v,_i,_de,_l,_col_,_ka,_k,_ret
		.BYTE	_re,_b,_jo,_no,_k,__,_po,_d,_o,_sh,_e,_l,__b,_li,_zh,_e,_dot,_ret
		.BYTE	_ret
		.BYTE	_T,_a,_ka,_s,_i,_ddt__quo,_O,_n,__,_ne,__s,_p,_ra,_v,_i,_t,_s_ja,__s,_a,_m,_exc_quo,_eol
_sc15_msg37:
		.BYTE	_R,_e,_b,_jo,_no,_k,__p,_r,_ji,_g,_n,_u,_l,__v,__s,_ve,_t,_dot,_ret
		.BYTE	_ret
		.BYTE	_M,_a,_s,_a,_ru,_ddt__quo,_T,_a,_ka,_s,_i,_exc_quo,_ret
		.BYTE	_ret
		.BYTE	_K,_i,_jo,_ko,_ddt__quo,_T,_a,_ka,_s,_i,_dot_dot_dot,__,_N,_e,_t,_dot_dot_dot,_quo,_eol
_sc15_msg38:
		.BYTE	_M,_a,_s,_a,_ru,_ddt__quo,_dot_dot_dot,_E,_s,_li,__,_m,_ji,__,_vo,_j,_d,_jo,_m,_ret
		.BYTE	_v,_n,_u,_t,_r,_mz,_col_,_na,_sh,_e,_j,__s,_i,_l,_ji,__,_ne,__,_h,_va,_ti,_t,_col,_ret
		.BYTE	_ch,_to,_b,_ji,__v,_e,_r,_n,_u,_t_mz,_s_ja,_dot,_quo,_eol
_sc15_msg2A:
		.BYTE	_K,_i,_jo,_ko,_ddt__quo,_N,_o,_dot_dot_dot,__,_e,_s,_li,__,_m,_ji,__v,_t,_ro,_jo,_m,_ret
		.BYTE	_s,_de,_la,_e,_m,__,_je,_to,_col_,_to,_g,_da,_dot_dot_dot,_quo,_ret
		.BYTE	_ret
		.BYTE	_M,_a,_s,_a,_ru,_ddt__quo,_V,_e,_r,_no,_dot_dot_dot,__v,_t,_ro,_jo,_m,_dot_dot_dot,_quo,_eol
_sc15_msg03:
		.BYTE	_ZH,_str,_zh,_u,_h,_exc,_ret
		.BYTE	_ret
		.BYTE	_U,_da,_r,_na,_ja_,_vo,_l,_na,__,_po,_ra,_z,_i,_la,__,_K,_a,_n,_je,_d,_u,_dot,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_A,_h,_exc_quo,_eol

		SECTION_END		F15
