
		SECTION_START	F2

		MSG_START	_scene2_msg_lib
		MSG_IDX	_sc2_msg00
		MSG_IDX	_sc2_msg01
		MSG_IDX	_sc2_msg02
		MSG_IDX	_sc2_msg03
		MSG_IDX	_sc2_msg04
		MSG_IDX	_sc2_msg05
		MSG_IDX	_sc2_msg06
		MSG_IDX	_sc2_msg07
		MSG_IDX	_sc2_msg08
		MSG_IDX	_sc2_msg09
		MSG_IDX	_sc2_msg0A
		MSG_IDX	_sc2_msg0B
		MSG_IDX	_sc2_msg0C
		MSG_IDX	_sc2_msg0D
		MSG_IDX	_sc2_msg0E
		MSG_IDX	_sc2_msg0F
		MSG_IDX	_sc2_msg10
		MSG_IDX	_sc2_msg12
		MSG_IDX	_sc2_msg13
		MSG_IDX	_sc2_msg14
		MSG_IDX	_sc2_msg15
		MSG_IDX	_sc2_msg16
		MSG_IDX	_sc2_msg17
		MSG_IDX	_sc2_msg18
		MSG_IDX	_sc2_msg19
		MSG_IDX	_sc2_msg1A
		MSG_IDX	_sc2_msg1C
		MSG_IDX	_sc2_msg1D
		MSG_IDX	_sc2_msg1E
		MSG_IDX	_sc2_msg1F
		MSG_IDX	_sc2_msg20
		MSG_IDX	_sc2_msg21
		MSG_IDX	_sc2_msg22
		MSG_IDX	_sc2_msg23
		MSG_IDX	_sc2_msg24
		MSG_IDX	_sc2_msg25
		MSG_IDX	_sc2_msg26
		MSG_IDX	_sc2_msg27
		MSG_IDX	_sc2_msg28
		MSG_IDX	_sc2_msgA2
		MSG_IDX	_sc2_msgBA
_sc2_msg00:
		.BYTE	_N,_a,_s,__,_o,_st,_a,_v,_i,_li,__,_u,__v,_h,_o,_da,__v,_ret
		.BYTE	_ko,_m,_na,_t,_u,__,_d,_l,_ja_,_d,_o,_p,_ro,_s,_o,_v,_dot,_ret
		.BYTE	_ret
		.BYTE	_V,_oennji,_j,_ddt__quo,_ZH,_di,_te,__,_z,_de,_s,_mz,_dot_dot_dot,_ret
		.BYTE	_S,_l,_e,_d,_u,_ju,_sch,_i,_e,_exc,__,_Z,_a,_h,_o,_di,_te,_exc_quo,_eol
_sc2_msg0E:
		.BYTE	_Kaj,_ddt__quo,_V,_i,_di,_mo,_col_,_v,_oennji,_e_,_i,_ret
		.BYTE	_po,_li,_c,_i,_ja_,_ra,_b,_o,_ta,_ju,_t,__v,_me,_st,_e,_col_,_ch,_to,_b,_ji,_ret
		.BYTE	_v,_ji,_s,_l,_e,_zh,_i,_va,_t_mz,__,_a,_n,_ti,_p,_ra,_v,_i,_te,_l,_mz,_str,_ret
		.BYTE	_st,_v,_en,_n,_ji,_e_,_g,_ru,_p,_p,_ji,_dot,__,_Z,_d,_o,_ro,_vo,_dot,_quo,_eol
_sc2_msg01:
		.BYTE	_O,_t,__,_to,_l,_p,_ji,__p,_ro,_te,_st,_u,_ju,_sch,_i,_h,_ret
		.BYTE	_st,_u,_de,_n,_to,_v,__i_,_te,_r,_ro,_ri,_s,_to,_v,_ret
		.BYTE	_i,_s,_h,_o,_di,_t,__,_g,_ro,_m,_ki,_j,__,_g,_u,_l,_dot,_ret
		.BYTE	_ret
		.BYTE	_JA,_m,_a,_g,_a,_ta,_ddt__quo,_O,_ni,__v,_e,_d,_u,_t,__s,_e,_b,_ja,_col,_ret
		.BYTE	_ka,_k,__b,_u,_d,_to,__p,_ri,_sh,_li,__,_na,__p,_i,_k,_ni,_k,_exc_quo,_eol
_sc2_msg02:
		.BYTE	_P,_o,_h,_o,_zh,_e,_col_,_o,_ni,__,_i,_s,_po,_l,_mz,_z,_u,_ju,_t,_ret
		.BYTE	_s,_po,_r,_t,_za,_l,__v,__,_ka,_ch,_e,_st,_ve,__v,_re,_m,_en,_no,_go,_ret
		.BYTE	_u,_ch,_a,_st,_ka,__,_d,_l,_ja_,_d,_o,_p,_ro,_s,_o,_v,__s,_ret
		.BYTE	_ko,_m,_na,_ta,_m,_i,__,_i,_z,__,_f,_a,_ne,_r,_n,_ji,_h,_ret
		.BYTE	_p,_e,_re,_go,_ro,_d,_o,_k,_dot,_eol
_sc2_msg03:
		.BYTE	_I,__,_to,_g,_da,__,_o,_n,__s,_ka,_za,_l,_dot_dot_dot,_eol
_sc2_msg04:
		.BYTE	_D,_a,_que,__,_A,__,_po,_to,_m,__,_ch,_to,_que,_eol
_sc2_msg05:
		.BYTE	_I,_z,_str,_za,__,_d,_ve,_ri,__,_d,_o,_no,_s,_i,_t,_s_ja,_ret
		.BYTE	_m,_no,_zh,_e,_st,_vo,__,_ra,_z,_n,_ji,_h,__,_z,_v,_u,_ko,_v,_dot,_eol
_sc2_msg06:
		.BYTE	_M,_ji,__,_str,__b,_o,_r,_c,_ji,__,_za,__s,_vo,_b,_o,_d,_u,_dot,_eol
_sc2_msg07:
		.BYTE	_M,_ne,__,_n,_u,_zh,_en,__v,_ra,_ch,_exc,_eol
_sc2_msg08:
		.BYTE	_M,_ne,__,_n,_u,_zh,_no,__,_o,_t,_li,_t_mz,_exc,_eol
_sc2_msg09:
		.BYTE	_JA,__,_h,_o,_ch,_u,__,_e,_s,_t_mz,_exc,_eol
_sc2_msg0F:
		.BYTE	_I,_g,_ra,__,_quo,_A,_ki,_ra,_quo,__,_d,_l,_ja_,_D,_en,_di,__,_te,_p,_e,_r,_mz,_ret
		.BYTE	_i,__,_na,__,_ru,_s,_s,_ko,_m,__,_ja,_z,_ji,_k,_e,_exc,_eol
_sc2_msg16:
		.BYTE	_K,_o,_n,_c,_e,_r,_t,__,_L,_i,_li,__,_M,_a,_c,_u,_za,_ki,__,_1,_2,_str,_go,_ret
		.BYTE	_de,_ka,_b,_r,_ja,_que,__,_V,__s,_po,_r,_t,_za,_l,_e,_que,__,_JE,_to,_ret
		.BYTE	_vo,_o,_b,_sch,_e_,_k,_to,_que,_eol
_sc2_msg14:
		.BYTE	_U,_h,__,_t,_ji,_dot,__,_S,_i,_m,_p,_a,_ti,_ch,_na,_ja_,_de,_v,_u,_sh,_ka,_exc,_ret
		.BYTE	_ret
		.BYTE	_JA,__,_d,_o,_l,_zh,_en,__,_po,_p,_ji,_ta,_t_mz,_s_ja,__p,_ri,_g,_la,_s,_i,_t_mz,_ret
		.BYTE	_e,_jo,__,_na,__s,_v,_i,_da,_ni,_e,_exc,_eol
_sc2_msg28:
		.BYTE	_Kanjeda,_ddt__quo,_O,_na,__,_h,_o,_ch,_e,_t,__,_o,_st,_a,_t_mz,_s_ja,_ret
		.BYTE	_z,_de,_s,_mz,_que_quo,_eol
_sc2_msg0A:
		.BYTE	_Kanjeda,_ddt__quo,_H,_m,_dot_dot_dot,__,_G,_de,_str,_to,__,_ja_,_u,_zh,_e,_ret
		.BYTE	_v,_i,_de,_l_,_je,_to,__,_li,_c,_o,_dot_dot_dot,_quo,_eol
_sc2_msg0B:
		.BYTE	_Kanjeda,_ddt__quo,_O,_exc,__,_JE,_to,__,_ta,__s,_a,_m,_a,_ja,_ret
		.BYTE	_de,_v,_u,_sh,_ka,__,_i,_z,__s,_p,_i,_s,_ka,_exc,__,_JA,__,_d,_o,_l,_zh,_en,_ret
		.BYTE	_p,_ri,_g,_la,_s,_i,_t_mz,__,_e,_jo,__,_ch,_e,_go,_str,_ni,_b,_u,_d,_mz,_ret
		.BYTE	_v,_ji,_p,_i,_t_mz,_dot,_quo,_eol
_sc2_msg0C:
		.BYTE	_K,_a,_k,__,_to,_l,_mz,_ko,__,_ja_,_po,_p,_ji,_ta,_l,_s_ja,_ret
		.BYTE	_za,_go,_vo,_ri,_t_mz,__s,__,_de,_v,_u,_sh,_ko,_j,_col,_ret
		.BYTE	_v,_ji,_s,_ko,_ch,_i,_l_,_te,_r,_ro,_ri,_st,__i_,_v,_ji,_de,_r,_n,_u,_l,_ret
		.BYTE	_ch,_e,_k,_u,__,_o,_t,__,_g,_ra,_na,_t,_ji,_exc,_eol
_sc2_msg0D:
		.BYTE	_V,_oennji,_j,__,_de,_r,_zh,_i,_t,__v,__,_ru,_ka,_h,__,_g,_ra,_na,_t,_u,_ret
		.BYTE	_te,_r,_ro,_ri,_st,_a,_dot,_eol
_sc2_msg10:
		.BYTE	_Kanjeda,_ddt__quo,_JE,_j,_col_,_JA,_m,_a,_g,_a,_ta,_exc,__,_M,_o,_zh,_e,_t,_col,_ret
		.BYTE	_s,_b,_e,_zh,_i,_m,_que_quo,_ret
		.BYTE	_ret
		.BYTE	_JA,_m,_a,_g,_a,_ta,_ddt__quo,_D,_a,_exc,__,_P,_o,_sh,_li,_col_,_re,_b,_ja,_ta,_exc_quo,_ret
		.BYTE	_ret
		.BYTE	_V,_oennji,_j,_ddt__quo,_JE,_j,_col_,_v,_ji,_exc,__,_S,_to,_j,_te,_exc,_ret
		.BYTE	_O,_ni,__,_u,_b,_e,_g,_a,_ju,_t,_exc_quo,_eol
_sc2_msg12:
		.BYTE	_Kanjeda,_ddt__quo,_T,_ji,__,_t,_u,_po,_j,__s,_u,_ki,_n,__s,_ji,_n,_exc,_ret
		.BYTE	_O,_t,_da,_j,_exc_quo,_ret
		.BYTE	_ret
		.BYTE	_JA,__p,_r,_ji,_g,_n,_u,_l_,_na,__,_ne,_go,_col_,_p,_ji,_ta,_ja,_s,_mz,_ret
		.BYTE	_o,_to,_b,_ra,_t_mz,__,_g,_ra,_na,_t,_u,_dot,_eol
_sc2_msg13:
		.BYTE	_N,_o,__,_g,_r,_a,_n,_a,_t,_a,__v,_ne,_za,_p,_no,_ret
		.BYTE	_v,_z,_o,_r,_va,_la,_s,_mz,_dot_dot_dot,_eol
_sc2_msg15:
		.BYTE	_Kanjeda,_ddt__quo,_V,_s,_e,_m,__,_u,_k,_r,_ji,_t_mz,_s_ja,_exc_quo,_ret
		.BYTE	_ret
		.BYTE	_U,_s,_l,_ji,_sh,_a,_v,__,_mo,_j,__,_k,_ri,_k,_col_,_mo,_i,_ret
		.BYTE	_ra,_st,_e,_r,_ja,_v,_sh,_i,_e,_s_ja,__,_d,_ru,_z,_mz,_ja,_ret
		.BYTE	_p,_ri,_g,_n,_u,_li,_s,_mz_,_k,__,_po,_l,_u,__i_,_st,_a,_li,_ret
		.BYTE	_na,_b,_l,_ju,_da,_t_mz,_col_,_ch,_to,__b,_u,_de,_t,__,_da,_l,_mz,_sh,_e,_dot,_eol
_sc2_msg17:
		.BYTE	_V,_oennji,_j,_ddt__quo,_JE,_j,_exc,__,_T,_ji,__,_ta,_m,_col_,_a,__,_n,_u,_str,_ka,_ret
		.BYTE	_s,_to,_ja,_t_mz,_exc_quo,_eol
_sc2_msg18:
		.BYTE	_S,_t,_u,_de,_n,_t,_ddt__quo,_an0,_D,_a,__,_z,_d,_ra,_v,_st,_v,_u,_e,_t,_ret
		.BYTE	_O,_s,_vo,_b,_o,_di,_te,_l,_mz,_na,_ja_,_R,_e,_vo,_l,_ju,_c,_i,_ja,_exc,_ret
		.BYTE	_B,_a,_n,_za,_j,_exc,_ret
		.BYTE	_ret
		.BYTE	_B,_dot_dot_dot,__,_B,_e,_da,_exc,_aof,_quo,_eol
_sc2_msg19:
		.BYTE	_Kanjeda,_ddt__quo,_N,_e,__s,_to,_j,_te,__s,_to,_l,_b,_a,_m,_i,_col,_ret
		.BYTE	_ka,_k,__,_na,__p,_ri,_e,_me,__,_u,__p,_ro,_k,_to,_lo,_g,_a,_exc,_ret
		.BYTE	_V,_s,_e,__v,__,_u,_k,_r,_ji,_ti,_e,_exc_quo,_eol
_sc2_msg1A:
		.BYTE	_V,_oennji,_j,_ddt__quo,_P,_o,_h,_o,_zh,_e,_col_,_t,_ji,__,_o,_di,_n,__,_i,_z,_ret
		.BYTE	_ch,_l,_e,_no,_v,__,_to,_j,__,_no,_vo,_j,__s,_e,_k,_t,_ji,_ret
		.BYTE	_s,_u,_m,_a,_s,_sh,_e,_d,_sh,_i,_h,_exc,__,_S,_l,_e,_d,_u,_j,__,_za,__,_m,_no,_j,_exc_quo,_eol
_sc2_msg1C:
		.BYTE	_V,_oennji,_j,_ddt__quo,_G,_ra,_na,_ta,__,_de,_f,_e,_k,_ti,_v,_na,_ja,_exc,_ret
		.BYTE	_V,_z,_ja,_t_mz,__,_e,_go,_exc_quo,_ret
		.BYTE	_ret
		.BYTE	_S,_t,_u,_de,_n,_t,_ddt__quo,_O,_j,_dot_dot_dot,_ret
		.BYTE	_M,_str,_m,_ne,__,_ta,_k,__,_zh,_a,_l,_mz,_exc_quo,_ret
		.BYTE	_ret
		.BYTE	_S,_t,_u,_de,_n,_t,__b,_ji,_l_,_o,_k,_ru,_zh,_en,_dot,_eol
_sc2_msg1D:
		.BYTE	_B,_u,_h,_exc,__,_U,_f,_exc,__,_H,_l,_ju,_p,_exc,_ret
		.BYTE	_ret
		.BYTE	_V,_oennji,_j,_ddt__quo,_H,_va,_ti,_t,_dot,__,_U,_ve,_di,_te,_dot,_ret
		.BYTE	_M,_ji,__,_na,_u,_ch,_i,_m,__,_e,_go,__,_ro,_di,_n,_u,__,_l,_ju,_b,_i,_t_mz,_dot,_quo,_eol
_sc2_msg1E:
		.BYTE	_JA,_m,_a,_g,_a,_ta,_ddt__quo,_T,_u,_p,_i,_c,_a,_exc,__,_E,_s,_li,__,_h,_o,_ch,_e,_sh,_mz,_ret
		.BYTE	_u,_me,_re,_t_mz,_col_,_po,_ch,_e,_m,_u,__b,_ji,__,_te,_b,_e,__p,_ro,_s,_to,_ret
		.BYTE	_ne,__,_po,_ve,_s,_i,_t_mz,_s_ja,_exc_quo,_eol
_sc2_msg1F:
		.BYTE	_V,_oennji,_j,_ddt__quo,_an0,_V,_ji,__,_mo,_zh,_e,_te,__,_i,_d,_ti,_col,_ret
		.BYTE	_p,_a,_r,_ni,_dot,__,_M,_ji,__,_u,_zh,_e,__s,_o,_o,_b,_sch,_i,_li,__v,__,_va,_sh,_u,_ret
		.BYTE	_sh,_ko,_l,_u,__,_o,__,_va,_s,_dot,_aof,_quo,_ret
		.BYTE	_ret
		.BYTE	_N,_e,_l,_mz,_z,_ja_,_li,__,_za,_b,_ra,_t_mz,__s,__,_s,_o,_b,_o,_j,__,_i,_ret
		.BYTE	_t,_u,__,_de,_v,_u,_sh,_k,_u,__,_to,_zh,_e,_dot_dot_dot,_eol
_sc2_msg20:
		.BYTE	_D,_e,_f,_e,_k,_ti,_v,_na,_ja_,_g,_ra,_na,_ta,__v,_s,_e,_str,_ta,_ki,_ret
		.BYTE	_v,_ne,_za,_p,_no,__v,_z,_o,_r,_va,_la,_s,_mz,_exc,_eol
_sc2_msg21:
		.BYTE	_Kanjeda,_ddt__quo,_O,_j,_str,_o,_j,_dot_dot_dot,__,_K,_a,_zh,_e,_t,_s_ja,_col,_ret
		.BYTE	_po,_d,_h,_o,_di,_t,__,_e,_jo,__,_o,_ch,_e,_re,_d,_mz,_dot,_quo,_eol
_sc2_msg22:
		.BYTE	_V,_i,_di,_mo,_col_,_o,_na,__,_ne,_r,_v,_ni,_ch,_a,_e,_t,_dot,__,_O,_j,_col,_ret
		.BYTE	_i,__,_po,_h,_o,_zh,_e_,_vo,_t,_str,_vo,_t,__,_za,_p,_la,_ch,_e,_t,_dot_dot_dot,_eol
_sc2_msg23:
		.BYTE	_V,_s,_e_,_vo,_k,_ru,_g,__,_ka,_ki,_e,_str,_to,__,_ne,_r,_v,_n,_ji,_e,_dot,_ret
		.BYTE	_P,_o,_ch,_ti,__,_po,_d,_o,_sh,_la,__,_o,_ch,_e,_re,_d,_mz_,_de,_v,_u,_sh,_ki,_dot,_ret
		.BYTE	_JA,__,_h,_o,_ch,_u,__,_po,_p,_ji,_ta,_t_mz,_s_ja,__v,_ji,_ta,_sch,_i,_t_mz,__,_e,_jo,_ret
		.BYTE	_o,_t,_s,_ju,_da,_dot,_eol
_sc2_msg24:
		.BYTE	_Kanjeda,_ddt__quo,_JE,_j,_col_,_de,_d,_u,_l,_ja,_exc,__,_O,_na,__,_to,_zh,_e,_ret
		.BYTE	_o,_d,_na,__,_i,_z,__,_na,_sh,_i,_h,_dot,__,_JA,__,_ne,__,_mo,_g,_u,_ret
		.BYTE	_b,_ro,_s,_i,_t_mz,__,_d,_ru,_g,_a,_dot,_quo,_ret
		.BYTE	_ret
		.BYTE	_V,_oennji,_j,_ddt__quo,_an0,_CH,_to,_que,_exc,_aof,_quo,_eol
_sc2_msg25:
		.BYTE	_V,_oennji,_j,_ddt__quo,_an0,_K,_o,_go,__,_t,_ji,__,_na,_z,_va,_l,_ret
		.BYTE	_de,_d,_u,_l,_e,_j,_col_,_go,_v,_n,_ju,_k,_exc,__,_S,_l,_u,_sh,_a,_j,__s,_ju,_da,_col,_ret
		.BYTE	_p,_a,_c,_a,_n,_dot,__,_M,_ne,__,_to,_l,_mz,_ko,__,_2,_5,__i_,_ja_,_e,_sch,_jo,_ret
		.BYTE	_da,_zh,_e_,_ne,__,_zh,_e,_na,_t,_exc,__,_T,_a,_k,__,_ch,_to,__s,_l,_e,_di,_ret
		.BYTE	_za,__,_ja,_z,_ji,_ko,_m,_exc,_aof,_quo,_eol
_sc2_msg26:
		.BYTE	_V,_oennji,_j,_ddt__quo,_an0,_U,_b,_i,_ra,_j,_s_ja,__,_o,_t,_s,_ju,_da,__,_i,_ret
		.BYTE	_po,_d,_ru,_g,_u,__s,_vo,_ju,__,_za,_b,_e,_ri,_exc,_aof,_quo,_eol
_sc2_msg27:
		.BYTE	_O,_t,_li,_ch,_no,_exc,__,_T,_e,_p,_e,_r,_mz_,_m,_ji,__,_mo,_zh,_e,_m,_ret
		.BYTE	_po,_ki,_n,_u,_t_mz,__s,_po,_r,_t,_za,_l,_col,__i_,_de,_v,_u,_sh,_ka,_ret
		.BYTE	_i,_d,_jo,_t,__s,__,_na,_m,_i,_exc,_eol
_sc2_msgA2:
		.BYTE	_Kanjeda,_ddt__quo,_M,_str,_m,_a,_mo,_ch,_ka,_col_,_s,_p,_a,_s,_i,_ret
		.BYTE	_m,_en,_ja,_exc_quo,_eol
_sc2_msgBA:
		.BYTE	_S,_t,_u,_de,_n,_t,_ddt__quo,_dot_dot_dot,_A,_que_quo,_eol

		SECTION_END		F2
