
		SECTION_START	F8

		MSG_START	_scene8_msg_lib
		MSG_IDX	_sc8_msg00
		MSG_IDX	_sc8_msg01
		MSG_IDX	_sc8_msg03
		MSG_IDX	_sc8_msg04
		MSG_IDX	_sc8_msg05
		MSG_IDX	_sc8_msg06
		MSG_IDX	_sc8_msg07
		MSG_IDX	_sc8_msg08
		MSG_IDX	_sc8_msg0A
		MSG_IDX	_sc8_msg0B
		MSG_IDX	_sc8_msg0C
		MSG_IDX	_sc8_msg0E
		MSG_IDX	_sc8_msg0F
		MSG_IDX	_sc8_msg10
		MSG_IDX	_sc8_msg11
		MSG_IDX	_sc8_msg12
		MSG_IDX	_sc8_msg13
		MSG_IDX	_sc8_msg14
		MSG_IDX	_sc8_msg15
		MSG_IDX	_sc8_msg16
		MSG_IDX	_sc8_msg17
		MSG_IDX	_sc8_msg18
		MSG_IDX	_sc8_msg19
		MSG_IDX	_sc8_msg1A
		MSG_IDX	_sc8_msg1B
		MSG_IDX	_sc8_msg1C
		MSG_IDX	_sc8_msg8A
		MSG_IDX	_sc8_msg8B
_sc8_msg00:
		.BYTE	_Kanjeda,_ddt__quo,_K,_u,_da,__,_o,_na,__,_de,_la,_s,_mz,_que_quo,_eol
_sc8_msg01:
		.BYTE	_P,_o,__,_ka,_na,_li,_za,_c,_i,_i,__p,_ro,_h,_o,_di,_t,__,_t,_ro,_p,_a,_dot,_ret
		.BYTE	_O,_t,__p,_ro,_ti,_vo,_po,_lo,_zh,_no,_go,__b,_e,_re,_g,_a,__,_e,_jo,_ret
		.BYTE	_o,_t,_de,_l,_ja,_e,_t,__,_vo,_da,_dot,_eol
_sc8_msg03:
		.BYTE	_Kanjeda,_ddt__quo,_JA,__s,_l,_ji,_sh,_u,__,_go,_lo,_s,_dot_dot_dot,_quo,_eol
_sc8_msg04:
		.BYTE	_Kanjeda,_ddt__quo,_I,_z,__,_ka,_na,_li,_za,_c,_i,_i,_que_quo,_eol
_sc8_msg05:
		.BYTE	_Kanjeda,_ddt__quo,_JE,_to,__,_o,_na,_exc,__,_V,_oennji,_j,_ret
		.BYTE	_de,_r,_zh,_i,_t,__,_e,_jo,__,_na,__,_m,_u,_sh,_k,_e,_exc,__,_E,_s,_li,__,_ja,_ret
		.BYTE	_s,_mo,_g,_u,__s,_p,_a,_st,_i,__,_e,_jo,_col_,_mo,_zh,_e,_t,__,_o,_na,_ret
		.BYTE	_po,_j,_d,_jo,_t,__s,_o,__,_m,_no,_j,__,_na,__s,_v,_i,_da,_ni,_e,_que_quo,_eol
_sc8_msg06:
		.BYTE	_Kanjeda,_ddt__quo,_H,_m,_col_,_m,_i,_st,_e,_r,_col_,_na,_s,_i,_li,_e,_ret
		.BYTE	_na,_m,__,_ni,__,_k,__,_ch,_e,_m,_u,_exc_quo,_eol
_sc8_msg07:
		.BYTE	_Kanjeda,_ddt__quo,_B,_li,_n,_col_,_m,_en,_ja,_ret
		.BYTE	_p,_ro,_i,_g,_no,_ri,_ro,_va,_li,_exc_quo,_eol
_sc8_msg08:
		.BYTE	_Kanjeda,_ddt__quo,_M,_u,_a,_str,_h,_a,_str,_h,_a,_exc,__,_N,_a,__s,_a,_mo,_m,_ret
		.BYTE	_de,_l,_e_,_te,_r,_ro,_ri,_st,__,_str,__,_je,_to,__,_ja,_exc_quo,_eol
_sc8_msg0B:
		.BYTE	_JA,__p,_ro,_k,_ra,_l,_s_ja,__v,__,_te,_ni,_col_,_st,_a,_ra,_ja,_s,_mz,_ret
		.BYTE	_ne,__,_i,_z,_da,_va,_t_mz,__,_ni,__,_z,_v,_u,_ka,_dot,_eol
_sc8_msg0C:
		.BYTE	_O,_di,_n,__,_i,_z,__s,_o,_l,_da,_t,__,_po,_d,_k,_ra,_l,_s_ja,__,_ko,_ret
		.BYTE	_m,_ne,__s,_za,_di,__i_,_p,_ri,_st,_a,_v,_i,_l_,_st,_vo,_l,_ret
		.BYTE	_k,__,_mo,_e,_j,__s,_p,_i,_ne,_dot,_eol
_sc8_msg0E:
		.BYTE	_Kanjeda,_ddt__quo,_H,_o,_ro,_sh,_o,_col_,_m,_ne,__,_n,_u,_zh,_no,_ret
		.BYTE	_s,_o,_s,_re,_d,_o,_to,_ch,_i,_t_mz,_s_ja,__i_,_za,_va,_li,_t_mz,_ret
		.BYTE	_je,_to,_go,__s,_o,_l,_da,_ta,_dot,_quo,_ret
		.BYTE	_ret
		.BYTE	_JA,__b,_ji,_l_,_go,_to,_v,__p,_e,_re,_l,_e,_z,_t_mz,__,_ch,_e,_re,_z,_ret
		.BYTE	_za,_b,_o,_r,_dot_dot_dot,_eol
_sc8_msg0F:
		.BYTE	_B,_a,_m,_exc,_ret
		.BYTE	_ret
		.BYTE	_JA,__,_ne,_ch,_a,_ja,_n,_no,__p,_n,_u,_l_,_me,_ta,_l,_li,_ch,_e,_s,_ki,_j,_ret
		.BYTE	_za,_b,_o,_r,__,_no,_go,_j,_dot,_eol
_sc8_msg10:
		.BYTE	_P,_a,_re,_n,_mz_,_o,_b,_e,_r,_n,_u,_l,_s_ja,_dot,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_D,_e,_r,_mz,_mo,_exc_quo,_eol
_sc8_msg11:
		.BYTE	_Kanjeda,_ddt__quo,_V,_ji,__,_po,_l,_no,_s,_t_mz,_ju,_ret
		.BYTE	_o,_k,_ru,_zh,_en,_ji,_dot,__,_B,_ro,_s,_mz,_te,__,_o,_ru,_zh,_i,_e_,_i,_ret
		.BYTE	_o,_t,_p,_u,_st,_i,_te,__,_de,_v,_u,_sh,_k,_u,_dot,_quo,_eol
_sc8_msg12:
		.BYTE	_Kanjeda,_ddt__quo,_JE,_str,_je,_col_,_n,_u,_col_,_ja_,_p,_ro,_s,_to,_dot_dot_dot,_quo,_eol
_sc8_msg13:
		.BYTE	_Kanjeda,_ddt__quo,_B,_str,_b,_o,_zh,_e,_que,_exc_quo,_eol
_sc8_msg14:
		.BYTE	_JA,__p,_r,_ji,_g,_n,_u,_l_,_na,__,_t,_u,_p,_i,_c,_u,_str,_vo,_en,_no,_go,_dot,_ret
		.BYTE	_ret
		.BYTE	_dot_dot_dot,_i,__,_u,_p,_a,_l,__v,__,_g,_r,_ja,_z,_mz_,_li,_c,_o,_m,_ret
		.BYTE	_p,_e,_re,_d,__,_ni,_m,_dot,_eol
_sc8_msg15:
		.BYTE	_Kanjeda,_ddt__quo,_JE,_j,_col_,_da,_va,_j,_str,_ka,__,_l,_u,_ch,_sh,_e,_ret
		.BYTE	_o,_st,_ji,_ne,_m,__,_ne,_m,_no,_go,_exc_quo,_ret
		.BYTE	_ret
		.BYTE	_JA,__v,_ji,_s,_ko,_ch,_i,_l,__p,_e,_re,_d,__,_li,_c,_o,_m,_ret
		.BYTE	_a,_r,_me,_j,_s,_ko,_go,__p,_ri,_d,_u,_r,_ka,_dot,_eol
_sc8_msg16:
		.BYTE	_H,_r,_ja,_s,_mz,_dot,_ret
		.BYTE	_ret
		.BYTE	_E,_go,__,_no,_g,_a,__,_o,_b,_ru,_sh,_i,_la,_s,_mz_,_m,_ne,__,_na,_ret
		.BYTE	_s,_p,_i,_n,_u,__i_,_o,_st,_a,_no,_v,_i,_la,__,_m,_en,_ja,_dot,_eol
_sc8_msg17:
		.BYTE	_JA,__,_st,_a,_ra,_l,_s_ja,__,_u,_ve,_r,_n,_u,_t_mz,_s_ja,__,_o,_t,_ret
		.BYTE	_p,_u,_l,_mz,_dot_dot_dot,_ret
		.BYTE	_ret
		.BYTE	_N,_o,__,_mo,_ja_,_no,_g,_a,__s,_o,_s,_ko,_l,_mz,_z,_n,_u,_la,_col,_ret
		.BYTE	_i,__,_ja_,_u,_p,_a,_l,_dot,_eol
_sc8_msg18:
		.BYTE	_Kanjeda,_ddt__quo,_K,_i,_j,_ja,_exc_quo,_ret
		.BYTE	_ret
		.BYTE	_JA,__p,_r,_ji,_g,_n,_u,_l_,_na,__s,_o,_l,_da,_ta,_dot,_eol
_sc8_msg19:
		.BYTE	_JA,__,_u,_p,_a,_l,__v,__,_ka,_na,_v,_u,__v,_me,_st,_e,__s,_ret
		.BYTE	_v,_oennji,_m,_dot,__,_S,_k,_vo,_z,_mz_,_g,_r,_ja,_z,_mz_,_v,__,_mo,_i,_h,_ret
		.BYTE	_g,_la,_za,_h,__,_ja_,_u,_v,_i,_de,_l,__p,_ri,_b,_li,_zh,_e,_ni,_e,_ret
		.BYTE	_e,_sch,_jo,__,_o,_d,_no,_go,_dot,_ret
		.BYTE	_ret
		.BYTE	_O,_n,__,_po,_d,_o,_sh,_jo,_l_,_ko,__,_m,_ne,__i_,_na,_p,_ra,_v,_i,_l,_ret
		.BYTE	_na,__,_m,_en,_ja_,_p,_i,_s,_to,_l,_e,_t,_exc,_eol
_sc8_msg1A:
		.BYTE	_D,_e,_v,_u,_sh,_ka,_ddt__quo,_H,_va,_ti,_t,_exc_quo,_eol
_sc8_msg1B:
		.BYTE	_N,_e,_v,_da,_l,_e,_k,_e,__b,_ji,_li,__s,_l,_ji,_sh,_n,_ji,__,_z,_v,_u,_ki,_ret
		.BYTE	_p,_ri,_b,_li,_zh,_e,_ni,_ja_,_d,_ru,_g,_i,_h,__v,_oennji,_h,_dot,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_an0,_P,_o,_sh,_li,_dot,_aof,_quo,_eol
_sc8_msg0A:
		.BYTE	_O,_sh,_e,_lo,_m,_l,_en,_n,_ji,_j,_col_,_ja_,_po,_h,_lo,_p,_a,_l,_ret
		.BYTE	_e,_jo,__,_po,__p,_l,_e,_ch,_u,_dot,_eol
_sc8_msg1C:
		.BYTE	_Kanjeda,_ddt__quo,_JE,_j,_exc,__,_K,_a,_k,__,_na,_s,_ch,_jo,_t,_ret
		.BYTE	_s,_v,_i,_da,_ni,_ja,_col_,_e,_s,_li,__,_na,_m,__,_u,_da,_st,_s_ja,_ret
		.BYTE	_u,_j,_ti,__,_o,_t,__v,_oennji,_h,_que_quo,_eol
_sc8_msg8A:
		.BYTE	_V,_oennji,_j,_ddt__quo,_JE,_j,_col_,_t,_ji,__s,_li,_sh,_ko,_m,_ret
		.BYTE	_da,_l,_e,_ko,__,_za,_sh,_jo,_l,_exc_quo,_eol
_sc8_msg8B:
		.BYTE	_A,_r,_me,_j,_s,_ki,_j,__v,_e,_r,_t,_u,_h,_a,_j,__v,_ji,_st,_re,_li,_l,_ret
		.BYTE	_i,_z,__s,_vo,_e,_go,__p,_i,_s,_to,_l,_e,_ta,_exc,_eol

		SECTION_END		F8
