
		SECTION_START	F3

		MSG_START	_scene3_msg_lib
		MSG_IDX	_sc3_msg00
		MSG_IDX	_sc3_msg01
		MSG_IDX	_sc3_msg02
		MSG_IDX	_sc3_msg03
		MSG_IDX	_sc3_msg04
		MSG_IDX	_sc3_msg05
		MSG_IDX	_sc3_msg06
		MSG_IDX	_sc3_msg07
		MSG_IDX	_sc3_msg09
_sc3_msg00:
		.BYTE	_M,_ne,__,_u,_da,_lo,_s,_mz_,_e,_jo,__v,_ji,_ta,_sch,_i,_t_mz,_exc,_eol
_sc3_msg01:
		.BYTE	_Kanjeda,_ddt__quo,_an0,_M,_o,_zh,_e,_t,_col_,_m,_ji,__s,__,_to,_b,_o,_j,_ret
		.BYTE	_s,_h,_o,_di,_m,__,_k,_u,_da,_str,_ni,_b,_u,_d,_mz,_col_,_v,_ji,_p,_mz,_e,_m,_que,__,_JA,_ret
		.BYTE	_po,_d,_u,_m,_a,_l,_col_,_m,_ji,__,_mo,_g,_li,__b,_ji,__,_po,_b,_o,_l,_ta,_t_mz,_ret
		.BYTE	_p,_ro,__,_je,_t,_u,_col_,_ti,_p,_a,_col_,_quo,_re,_vo,_l,_ju,_c,_i,_ju,_quo,_dot,_aof,_quo,_eol
_sc3_msg02:
		.BYTE	_D,_e,_v,_u,_sh,_ka,_ddt__quo,_an1,_T,_ji,__b,_o,_l,_mz,_sh,_e_,_po,_h,_o,_zh,__,_na,_ret
		.BYTE	_o,_t,_ch,_a,_ja,_n,_no,_go,__b,_a,_b,_ni,_ka,_dot,__,_T,_ji,__b,_ji,_ret
		.BYTE	_po,_mo,_g,__,_l,_ju,_b,_o,_m,_u,_col_,_to,_l,_mz,_ko,__,_e,_s,_li,__,_o,_n,_ret
		.BYTE	_zh,_en,_s,_ko,_go,__,_po,_la,_col_,_ne,__p,_ra,_v,_da,__,_li,_que,_aof,_quo,_eol
_sc3_msg03:
		.BYTE	_Kanjeda,_ddt__quo,_an0,_A,__,_vo,_t,__i_,_ne,_p,_ra,_v,_da,_exc,_ret
		.BYTE	_JA,__,_d,_o,_vo,_l,_mz,_no,__,_ra,_z,_b,_o,_r,_ch,_i,_v,_dot,__,_N,_o,_ret
		.BYTE	_v,_ne,_sh,_no,_s,_t_mz,__,_d,_l,_ja_,_m,_en,_ja_,_ne,__s,_a,_mo,_e,_ret
		.BYTE	_g,_la,_v,_no,_e,_col_,_va,_zh,_ne,_e,__b,_o,_g,_a,_t,_st,_vo,_ret
		.BYTE	_v,_n,_u,_t,_re,_n,_ne,_go,__,_m,_i,_ra,_dot,_aof,_quo,_eol
_sc3_msg04:
		.BYTE	_D,_e,_v,_u,_sh,_ka,_ddt__quo,_an1,_P,_o,_la,_g,_a,_ju,_col_,_te,_p,_e,_r,_mz_,_ja_,_u,_ret
		.BYTE	_te,_b,_ja_,_v,__,_d,_o,_l,_g,_u,_dot,__,_B,_o,_l,_mz,_sh,_o,_e,__s,_p,_a,_s,_i,_b,_o,_col,_ret
		.BYTE	_m,_str,_m,_dot_dot_dot,_aof,_quo,_eol
_sc3_msg05:
		.BYTE	_Kanjeda,_ddt__quo,_an0,_M,_en,_ja_,_z,_o,_v,_u,_t,__,_Kanjeda,_dot,_ret
		.BYTE	_O,_ch,_en,_mz_,_p,_ri,_ja,_t,_no,_dot,_aof,_quo,_eol
_sc3_msg06:
		.BYTE	_D,_e,_v,_u,_sh,_ka,_ddt__quo,_an1,_P,_ro,_sch,_a,_j,_col_,_Kanjeda,_dot,_aof,_quo,_eol
_sc3_msg07:
		.BYTE	_Kanjeda,_ddt__quo,_an0,_P,_o,_s,_to,_j,_exc,__,_JA,__v,_e,_d,_mz_,_te,_b,_ja,_ret
		.BYTE	_s,_p,_a,_s,_exc,__,_M,_o,_g,_la,__b,_ji,__,_h,_o,_t_mz,__,_i,_m,_ja_,_s,_vo,_jo,_ret
		.BYTE	_s,_ka,_za,_t_mz,_col_,_st,_e,_r,_va,_exc,_aof,_quo,_eol
_sc3_msg09:
		.BYTE	_P,_o,_h,_o,_zh,_e,_col_,_t,_u,_p,_ji,_e_,_vo,_ja,_ki,__v,_s,_jo,_str,_ta,_ki,_ret
		.BYTE	_ne,__s,_mo,_g,_li,__s,_p,_ra,_v,_i,_t_mz,_s_ja,__s,_ret
		.BYTE	_g,_ra,_na,_to,_j,_dot,_eol

		SECTION_END		F3
