

		SECTION_START	F0

		MSG_START	_scene0_msg_lib
		MSG_IDX	_sc0_msgB8
		MSG_IDX	_sc0_msg01
		MSG_IDX	_sc0_msg02
		MSG_IDX	_sc0_msg03
		MSG_IDX	_sc0_msg04
		MSG_IDX	_sc0_msg05
		MSG_IDX	_sc0_msg06
		MSG_IDX	_sc0_msg07
		MSG_IDX	_sc0_msg08
		MSG_IDX	_sc0_msg09
		MSG_IDX	_sc0_msg19
		MSG_IDX	_sc0_msg26
		MSG_IDX	_sc0_msg2E
		MSG_IDX	_sc0_msg2F
		MSG_IDX	_sc0_msg30
_sc0_msgB8:
		.BYTE	_V,__,_t,_u,__,_no,_ch,_mz_,_m,_ji,__p,_re,_s,_l,_e,_d,_o,_va,_li,_ret
		.BYTE	_K,_lo,_u,_no,_v,__,_po,__,_sh,_o,_s,_s,_e_,_S,_ta,_ro,_go,_ret
		.BYTE	_go,_ro,_da,_dot,_eol
_sc0_msg26:
		.BYTE	_V,__,_je,_to,_t,__,_ra,_z,__,_d,_l,_ja_,_ra,_z,_no,_o,_b,_ra,_z,_i,_ja,_ret
		.BYTE	_na,_s,__,_vo,_z,_g,_la,_v,_l,_ja,_l_,_Tjecuo,_dot,_ret
		.BYTE	_ret
		.BYTE	_M,_ji,__,_e,_d,_va,__,_m,_i,_no,_va,_li,__,_K,_P,_P,_col_,_ka,_k,_ret
		.BYTE	_ch,_to,_str,_to,__p,_ro,_i,_z,_o,_sh,_lo,_dot_dot_dot,_eol
_sc0_msg01:
		.BYTE	_V,_ne,_za,_p,_no,_col_,_b,_a,_j,_k,__,_Tjecuo,__,_o,_h,_va,_ti,_lo,_ret
		.BYTE	_p,_la,_m,_ja,_dot,_eol
_sc0_msg02:
		.BYTE	_JA,__,_po,_d,_b,_e,_zh,_a,_l_,_k,__,_Tjecuo,__i_,_po,_mo,_g,_ret
		.BYTE	_e,_m,_u,__p,_ri,_v,_st,_a,_t_mz,_dot,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_D,_e,_r,_zh,_i,_s,_mz,_col_,_Tjecuo,_exc_quo,_ret
		.BYTE	_ret
		.BYTE	_Tjecuo,_ddt__quo,_JE,_str,_je,_to,__,_o,_n,__v,_i,_no,_va,_t,_dot_dot_dot,_quo,_ret
		.BYTE	_ret
		.BYTE	_Tjecuo,__,_u,_ka,_za,_l_,_na,__,_ko,_go,_str,_to,_col_,_no,__,_ja,_ret
		.BYTE	_ne,__b,_ji,_l_,_u,_ve,_re,_n,_col_,_b,_ji,_l_,_je,_to,__,_st,_a,_ri,_k,_ret
		.BYTE	_i,_li,__,_o,_ch,_en,_mz_,_mo,_r,_sch,_i,_ni,_st,_ji,_j,__,_re,_b,_jo,_no,_k,_dot,_eol
_sc0_msg03:
		.BYTE	_Kanjeda,_ddt__quo,_K,_a,_k,_dot_dot_dot,__,_CH,_to,__,_t,_ji,_ret
		.BYTE	_s,_de,_la,_l,_col_,_me,_l,_ki,_j,__,_u,_ro,_de,_c,_dot_dot_dot,_quo,_ret
		.BYTE	_ret
		.BYTE	_SH,_u,_m,__p,_ri,_b,_li,_zh,_a,_ju,_sch,_e,_go,_s_ja,__,_vo,_en,_no,_go,_ret
		.BYTE	_v,_e,_r,_to,_l,_jo,_ta,__,_za,_g,_l,_u,_sh,_i,_l_,_mo,_j,__,_go,_lo,_s,_dot,_ret
		.BYTE	_ret
		.BYTE	_U,_s,_l,_ji,_sh,_a,_v,__,_je,_to,_t,__,_sh,_u,_m,_col_,_mo,_r,_sch,_i,_ni,_st,_ji,_j,_ret
		.BYTE	_re,_b,_jo,_no,_k,__,_na,_ch,_a,_l_,_d,_ro,_zh,_a,_t_mz,_dot,_eol
_sc0_msg04:
		.BYTE	_V,_e,_r,_to,_l,_jo,_t,__p,_ri,_z,_e,_m,_li,_l,_s_ja,__,_r,_ja,_d,_o,_m,__s,_ret
		.BYTE	_na,_m,_i,_col_,_za,__,_o,_t,_k,_r,_ji,_v,_sh,_e,_j,_s_ja,__,_d,_ve,_r,_mz,_ju,_ret
		.BYTE	_po,_ka,_za,_l,_s_ja,__,_m,_u,_zh,_ch,_i,_na,_dot,_eol
_sc0_msg19:
		.BYTE	_M,_u,_zh,_ch,_i,_na,_ddt__quo,_an0,_T,_a,_ka,_s,_i,_col_,_ja_,_p,_ri,_sh,_jo,_l_,_za,_ret
		.BYTE	_to,_b,_o,_j,_dot,__,_D,_a,_va,_j,_col_,_ve,_r,_n,_jo,_m,_s_ja,__,_na,_za,_d,_dot,_ret
		.BYTE	_T,_ji,__,_zh,_e_,_z,_na,_e,_sh,_mz,_col_,_ch,_to,__,_ni,__,_o,_d,_no,_m,_u,__,_i,_z,_ret
		.BYTE	_va,_s,__,_ne,_l,_mz,_z,_ja_,_zh,_i,_t_mz,__s,_na,_ru,_zh,_i,_exc,_aof,_quo,_eol
_sc0_msg05:
		.BYTE	_T,_a,_ka,_s,_i,__,_str,__,_mo,_r,_sch,_i,_ni,_st,_ji,_j,__,_re,_b,_jo,_no,_k,__,_str,_ret
		.BYTE	_u,_st,_a,_v,_i,_l,_s_ja,__,_na,__,_m,_u,_zh,_ch,_i,_n,_u,_col_,_e,_go,__,_li,_c,_o,_ret
		.BYTE	_o,_c,_e,_p,_e,_ne,_lo,__,_o,_t,__,_u,_zh,_a,_s,_a,_dot,_eol
_sc0_msg2E:
		.BYTE	_M,_u,_zh,_ch,_i,_na,_ddt__quo,_an0,_A,_re,_st,_u,_j,_te,__,_je,_ti,_h,_ret
		.BYTE	_s,_o,_p,_l,_ja,_ko,_v,_exc,_aof,_quo,_ret
		.BYTE	_ret
		.BYTE	_V,_oennji,_e_,_po,_d,_o,_sh,_li,__i_,_v,_z,_ja,_li,__,_na,_s,_ret
		.BYTE	_po,_d,__,_st,_ra,_zh,_u,_dot,_eol
_sc0_msg06:
		.BYTE	_V,_oennji,_j,_ddt__quo,_R,_u,_ki,__,_za,__,_go,_lo,_v,_u,_exc,_ret
		.BYTE	_L,_e,_ch,_mz_,_na,__,_z,_e,_m,_l,_ju,_exc_quo,_eol
_sc0_msg07:
		.BYTE	_Kanjeda,_ddt__quo,_P,_str,_po,_s,_to,_j,_te,_col_,_m,_i,_st,_e,_r,_exc,_ret
		.BYTE	_M,_ji,__,_ni,__v,__,_ch,_jo,_m,__,_ne,__v,_i,_no,_va,_t,_ji,_exc_quo,_eol
_sc0_msg08:
		.BYTE	_Kanjeda,_ddt__quo,_M,_o,_j,__,_d,_ru,_g,__,_ra,_ne,_n,_exc_quo,_ret
		.BYTE	_ret
		.BYTE	_V,_oennji,_j,_ddt__quo,_P,_o,_l,_ko,_v,_ni,_k,_exc,__,_U,__,_na,_s,_ret
		.BYTE	_po,_st,_ra,_da,_v,_sh,_i,_j,_exc_quo,_ret
		.BYTE	_ret
		.BYTE	_M,_u,_zh,_ch,_i,_na,_ddt__quo,_an0,_M,_ji,__,_za,_b,_e,_r,_jo,_m,__,_e,_go,__v,_ret
		.BYTE	_la,_b,_o,_ra,_to,_ri,_ju,_dot,__,_P,_o,_e,_h,_a,_li,_dot,_aof,_quo,_eol
_sc0_msg30:
		.BYTE	_K,_a,_zh,_e,_t,_s_ja,_col_,_o,_ni,__,_d,_u,_m,_a,_ju,_t,_col_,_ch,_to,__,_m,_ji,_ret
		.BYTE	_te,_r,_ro,_ri,_st,_ji,_dot,_eol
_sc0_msg2F:
		.BYTE	_V,_e,_r,_to,_l,_jo,_t,__s,__,_re,_b,_jo,_n,_ko,_m,__i_,_Tjecuo,_ret
		.BYTE	_na,__b,_o,_r,_t,_u,__,_me,_d,_l,_en,_no,__v,_z,_l,_e,_te,_l,_dot,_eol
_sc0_msg09:
		.BYTE	_Kanjeda,_ddt__quo,_an1,_T,_u,_p,_ji,_e,__p,_ri,_d,_u,_r,_ki,_exc,_ret
		.BYTE	_K,_a,_ko,_go,__,_ch,_jo,_r,_ta,__v,_ji,__s,_o,_b,_i,_ra,_e,_te,_s,_mz_,_s,_ret
		.BYTE	_na,_m,_i,__,_de,_la,_t_mz,_que,_exc_quo,_eol

		SECTION_END		F0
