
		SECTION_START	F14

		MSG_START	_scene14_msg_lib
		MSG_IDX	_sc14_msg00
		MSG_IDX	_sc14_msg01
		MSG_IDX	_sc14_msg02
		MSG_IDX	_sc14_msg03
		MSG_IDX	_sc14_msg04
		MSG_IDX	_sc14_msg05
		MSG_IDX	_sc14_msg06
		MSG_IDX	_sc14_msg07
		MSG_IDX	_sc14_msg08
		MSG_IDX	_sc14_msg09
		MSG_IDX	_sc14_msg0A
		MSG_IDX	_sc14_msg0B
		MSG_IDX	_sc14_msg0C
		MSG_IDX	_sc14_msg0D
		MSG_IDX	_sc14_msg0E
		MSG_IDX	_sc14_msg0F
		MSG_IDX	_sc14_msg10
		MSG_IDX	_sc14_msg11
		MSG_IDX	_sc14_msg12
		MSG_IDX	_sc14_msg13
		MSG_IDX	_sc14_msg14
_sc14_msg00:
		.BYTE	_M,_ji,__,_re,_sh,_i,_li,__,_ne,_na,_d,_o,_l,_go,_ret
		.BYTE	_o,_st,_a,_no,_v,_i,_t_mz,_s_ja,__,_u,__,_K,_P,_P,__,_na,__,_sh,_o,_s,_s,_e,_dot,_ret
		.BYTE	_U,_zh,_e_,_po,_ch,_ti,__,_na,_st,_u,_p,_i,_la,__,_no,_ch,_mz,_dot_dot_dot,_eol
_sc14_msg01:
		.BYTE	_Kanjeda,_ddt__quo,_K,_a,_ki,_e_,_z,_de,_s,_mz_,_k,_ra,_s,_i,_v,_ji,_e,_ret
		.BYTE	_z,_v,_jo,_z,_d,_ji,_exc_quo,_ret
		.BYTE	_ret
		.BYTE	_Kej,_ddt__quo,_an0,_O,__,_ch,_jo,_m,__,_t,_ji,__b,_o,_r,_mo,_ch,_e,_sh,_mz,_que,_aof,_quo,_eol
_sc14_msg02:
		.BYTE	_Kanjeda,_ddt__quo,_CH,_jo,_r,_t,_col_,_ka,_k,__,_to,_l,_mz,_ko,__,_je,_to,_t,_ret
		.BYTE	_la,_z,_e,_r,__,_st,_a,_l_,_n,_u,_zh,_en,_col_,_o,_n,__,_t,_u,_t,__,_zh,_e,_ret
		.BYTE	_v,_z,_ja,_l,__i_,_s,_lo,_m,_a,_l,_s_ja,_dot,_quo,_eol
_sc14_msg03:
		.BYTE	_Kej,_ddt__quo,_an0,_M,_ne,__,_ka,_zh,_e,_t,_s_ja,_col_,_ja_,_po,_te,_r,_ja,_la,_ret
		.BYTE	_s,_o,_z,_na,_ni,_e,_dot_dot_dot,__,_A,__,_ko,_g,_da,__,_o,_ch,_n,_u,_la,_s,_mz,_col,_ret
		.BYTE	_ja,__b,_ji,_la,__v,_s_ja,__v,__p,_ji,_li,_dot_dot_dot,_aof,_quo,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_U,_ve,_re,_n,_col_,_je,_ti,__,_ch,_jo,_r,_to,_v,_ji,_ret
		.BYTE	_de,_ti,__,_u,_p,_ra,_v,_l,_ja,_li,__,_to,_b,_o,_j,_dot,_quo,_eol
_sc14_msg04:
		.BYTE	_Kej,_ddt__quo,_an0,_JA,__s,_o,_v,_s,_e,_m,__,_ni,_ch,_e,_go,__,_ne,_ret
		.BYTE	_po,_m,_n,_ju,_dot,__,_E,_s,_li,__b,_ji,__,_ne,__,_po,_ja,_v,_i,_l,_s_ja,_ret
		.BYTE	_Kaj,_dot_dot_dot,_aof,_quo,_eol
_sc14_msg05:
		.BYTE	_Kej,_ddt__quo,_an0,_U,__,_te,_b,_ja_,_ne,_t,__,_ni,__,_m,_a,_l,_e,_j,_sh,_e,_go,_ret
		.BYTE	_sh,_a,_n,_s,_a,__p,_ro,_ti,_v,__,_ne,_go,_exc,_aof,_quo,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_N,_e_,_i,_me,_e,_t,__,_z,_na,_ch,_e,_ni,_ja,_dot,_ret
		.BYTE	_JA,__,_ra,_z,_b,_e,_ru,_s,_mz_,_s,__,_Tjecuo,__s,_vo,_i,_m,_i,_ret
		.BYTE	_r,_u,_ka,_m,_i,_exc_quo,_eol
_sc14_msg06:
		.BYTE	_Kej,_ddt__quo,_an0,_T,_a,_m,__b,_ji,_lo,__,_o,_p,_a,_s,_no,_exc,__,_K,_o,_g,_da,_ret
		.BYTE	_t,_ji,__,_u,_p,_a,_l,_col_,_ja_,_po,_d,_u,_m,_a,_la,_col_,_ch,_to,__v,_s,_jo,_ret
		.BYTE	_ko,_n,_ch,_e,_no,_dot,_aof,_quo,_eol
_sc14_msg07:
		.BYTE	_Kaj,_ddt__quo,_K,_o,_g,_da,__,_o,_n,__,_st,_a,_l_,_ta,_ki,_m,_ret
		.BYTE	_mo,_g,_u,_ch,_i,_m,_dot_dot_dot,_ret
		.BYTE	_ret
		.BYTE	_K,_a,_ne,_da,_col_,_t,_ji,__,_u,_ve,_re,_n,_col_,_ch,_to,__s,_mo,_zh,_e,_sh,_mz,_ret
		.BYTE	_o,_to,_m,_st,_i,_t_mz,__,_za,__,_JA,_m,_a,_g,_a,_t,_u,_que_quo,_eol
_sc14_msg08:
		.BYTE	_Kaj,_ddt__quo,_JA,__,_d,_o,_l,_zh,_en,__b,_ji,_l,__s,_p,_a,_st,_i,__,_va,_s,_col,_ret
		.BYTE	_po,_to,_m,_u,__,_ch,_to,__b,_ji,_lo,__,_o,_p,_a,_s,_no,_dot,_quo,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_H,_o,_ro,_sh,_o,_col_,_ja_,_po,_n,_ja,_l,_dot,_quo,_eol
_sc14_msg09:
		.BYTE	_Kaj,_ddt__quo,_R,_a,_z,_ve,__,_ne,_l,_mz,_z,_ja_,_za,_r,_ja,_di,_t_mz,_ret
		.BYTE	_la,_z,_e,_r,__,_o,_t,__b,_a,_j,_ka,_que_quo,_eol
_sc14_msg0A:
		.BYTE	_Kaj,_ddt__quo,_D,_a,_va,_j,__,_ja_,_p,_e,_re,_za,_r,_ja,_zh,_u,__,_e,_go,_exc_quo,_eol
_sc14_msg0B:
		.BYTE	_Kaj,_ddt__quo,_dot_dot_dot,_T,_mz,_f,_u,_dot,__,_V,_o,_t,__,_ch,_e,_r,_t,_exc_quo,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_B,_a,_ta,_re,_ja,_col_,_b,_a,_ta,_re,_ja,_exc,_dot,_dot,_quo,_eol
_sc14_msg12:
		.BYTE	_Kaj,_ddt__quo,_M,_o,_j,__b,_a,_j,_k,__,_go,_ri,_t,_exc_quo,_eol
_sc14_msg0C:
		.BYTE	_Kanjeda,_ddt__quo,_K,_a,_k,__,_t,_ji,__,_d,_u,_m,_a,_e,_sh,_mz,_col,_ret
		.BYTE	_a,__v,_to,_ru,_ju,__,_o,_n,__,_za,_r,_ja,_di,_t,_que_quo,_ret
		.BYTE	_ret
		.BYTE	_Kaj,_ddt__quo,_CH,_to,_que,_exc,__,_S,_vo,_j,__b,_a,_j,_k,__,_l,_u,_ch,_sh,_e,_ret
		.BYTE	_te,_p,_e,_r,_mz_,_lo,_m,_a,_j,_exc_quo,_eol
_sc14_msg13:
		.BYTE	_Kanjeda,_ddt__quo,_S,_l,_ji,_sh,_i,_sh,_mz_,_ch,_to,_str,_ni,_b,_u,_d,_mz,_que_quo,_ret
		.BYTE	_ret
		.BYTE	_Kaj,_ddt__quo,_CH,_to,_str,_to,__s,_l,_ji,_sh,_u,_dot_dot_dot,_quo,_eol
_sc14_msg0D:
		.BYTE	_Kanjeda,_ddt__quo,_O,_j,_col_,_o,_p,_ja,_t_mz,__,_go,_ri,_t,_dot_dot_dot,_quo,_ret
		.BYTE	_ret
		.BYTE	_Kaj,_ddt__quo,_CH,_str,_to,_str,_o,_str,_a,_str,_a,_dot_dot_dot,_quo,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_H,_a,_str,_h,_a,_dot_dot_dot,_quo,_eol
_sc14_msg0E:
		.BYTE	_D,_e,_r,_zh,_u,__p,_a,_ri,_col_,_Tjecuo,__s,_no,_va,_ret
		.BYTE	_i,_g,_ra,_e,_t,__v,__,_quo,_C,_a,_r,_ja_,_go,_r,_ji,_quo,_dot,_eol
_sc14_msg0F:
		.BYTE	_Kej,_col_,_d,_o,__s,_i,_h,__,_po,_r,__,_ti,_h,_o,__s,_to,_ja,_v,_sh,_a,_ja,_ret
		.BYTE	_v,__s,_to,_ro,_ne,_col_,_s,_mo,_t,_r,_ja,_col_,_ch,_e,_m,__,_m,_ji,_ret
		.BYTE	_za,_n,_ja,_t,_ji,_col_,_me,_d,_l,_en,_no,__p,_ro,_go,_vo,_ri,_la,_dot,_ret
		.BYTE	_ret
		.BYTE	_Kej,_ddt__quo,_an0,_V,_o,_t,_col_,_vo,_z,_mz,_m,_i,__,_je,_to,_dot_dot_dot,_aof,_quo,_eol
_sc14_msg14:
		.BYTE	_Kej,__p,_e,_re,_da,_la,__,_m,_ne,__,_z,_e,_r,_ka,_lo,_dot,_ret
		.BYTE	_K,_a,_za,_lo,_s,_mz,_col_,_o,_no,__s,_ve,_r,_ka,_e,_t,__v,_ret
		.BYTE	_te,_m,_no,_te,__,_no,_ch,_i,_dot,_eol
_sc14_msg10:
		.BYTE	_JA,__v,_e,_r,_n,_u,_l,_s_ja,__,_k,__,_O,_li,_m,_p,_i,_j,_s,_ko,_m,_u,_ret
		.BYTE	_st,_a,_di,_o,_n,_u,_dot,_eol
_sc14_msg11:
		.BYTE	_Kej,__s,_mo,_t,_re,_la,__,_na,__p,_la,_m,_ja,_dot,_eol

		SECTION_END		F14