
		SECTION_START	F17

		MSG_START	_scene17_msg_lib
		MSG_IDX_SP	_sc17_msg76
		MSG_IDX_SP	_sc17_msg77
		MSG_IDX_SP	_sc17_msg78
		MSG_IDX_SP	_sc17_msg79
		MSG_IDX_SP	_sc17_msg7A
		MSG_IDX_SP	_sc17_msg7B
		MSG_IDX_SP	_sc17_msg84
		MSG_IDX_SP	_sc17_msg86
		MSG_IDX_SP	_sc17_msg8C
		MSG_IDX_SP	_sc17_msgB6
		MSG_IDX_SP	_sc11_12_13_msg97
		MSG_IDX_SP	_sc11_15_msg96
		MSG_IDX_SP	_sc13_15_msg99
		MSG_IDX_SP	_sc13_15_msg9A
		MSG_IDX_SP	_sc13_15_msg9B
		MSG_IDX_SP	_sc13_15_msg9E
		MSG_IDX_SP	_sc13_15_msg9F
		MSG_IDX_SP	_sc15_16_msgC9
		MSG_IDX_SP	_sc15_16_msgCB
		MSG_IDX_SP	_sc15_16_msgC5
		MSG_IDX_SP	_sc15_16_msgC7
		MSG_IDX_SP	_sc15_16_msgCA
		MSG_IDX_SP	_sc15_16_msgC8
		MSG_IDX_SP	_sc15_16_msgC6
		MSG_IDX_SP	_sc2_13_msgA0
		MSG_IDX_SP	_sc2_13_15_16_msg82
		MSG_IDX_SP	_sc2_15_msgA1
		MSG_IDX_SP	_sc2_6_msg83
		MSG_IDX_SP	_sc2_F_10_12_13_msg85
		MSG_IDX_SP	_sc5_6_msgA4
		MSG_IDX_SP	_sc5_6_15_msgAB
		MSG_IDX_SP	_sc5_A_msg7F
		MSG_IDX_SP	_sc6_15_msg88
		MSG_IDX_SP	_sc6_15_msg89
		MSG_IDX_SP	_sc8_A_msg8F
		MSG_IDX_SP	_scA_10_msg94
		MSG_IDX_SP	_scA_B_msgA8
		MSG_IDX_SP	_scA_B_msgA7
		MSG_IDX_SP	_scA_B_msgA6
		MSG_IDX_SP	_scA_B_msgAA
		MSG_IDX_SP	_scA_B_msgAF
		MSG_IDX_SP	_scA_B_msgB0
		MSG_IDX_SP	_scA_B_msgB1
		MSG_IDX_SP	_scA_B_msgB2
		MSG_IDX_SP	_scA_B_msgA9
		MSG_IDX_SP	_scC_15_msgA5
		MSG_IDX_SP	_scC_D_13_16_msg90
		MSG_IDX_SP	_scD_E_13_msg91
		MSG_IDX_SP	_scF_12_13_15_msg93
_sc17_msg76:
		.BYTE	_M,_i,_ja,_ko,_ddt__quo,_O,_ch,_i,_st,_i,__s,_vo,_jo,__,_te,_lo,_exc,_ret
		.BYTE	_O,_ch,_i,_st,_i,__s,_vo,_ju,__,_d,_u,_sh,_u,__i_,_to,_g,_da,_ret
		.BYTE	_vo,_z,_v,_ra,_sch,_a,_j,_s_ja,_exc_quo,_eol
_sc17_msg77:
		.BYTE	_M,_i,_ja,_ko,_ddt__quo,_T,_a,_k,__,_t,_ji,__,_go,_vo,_ri,_sh,_mz,_col_,_ch,_to,_ret
		.BYTE	_h,_o,_ch,_e,_sh,_mz_,_za,_ko,_n,_ch,_i,_t_mz,_que_quo,_ret
		.BYTE	_ret
		.BYTE	_K,_no,_p,_ka,__,_A,_ddt__quo,_D,_a,_exc_quo,_ret
		.BYTE	_K,_no,_p,_ka,__,_V,_ddt__quo,_N,_e,_t,_exc_quo,_eol
_sc17_msg78:
		.BYTE	_M,_i,_ja,_ko,_ddt__quo,_P,_ro,_b,_u,_zh,_de,_ni,_e_,_po,_ve,_li,_te,_l,_ja,_ret
		.BYTE	_A,_ki,_r,_ji,__,_ta,_k,__b,_li,_z,_ko,_exc,__,_O,_n,__,_n,_u,_zh,_da,_e,_t,_s_ja,_ret
		.BYTE	_v,__,_va,_sh,_e,_j,__s,_i,_l,_e,_exc,__,_V,_o,_s,_p,_r,_ja,_n,_mz,_te,__,_d,_u,_h,_o,_m,_ret
		.BYTE	_i,__p,_ri,_s,_o,_e,_di,_n,_ja,_j,_te,_s,_mz,_exc_quo,_eol
_sc17_msg79:
		.BYTE	_M,_i,_ja,_ko,_ddt__quo,_D,_u,_ra,_k,_exc,__,_JE,_to,__,_ne,__,_to,_exc,_ret
		.BYTE	_P,_o,_p,_ro,_b,_u,_j,__v,_ve,_st,_i,__s,_no,_va,_exc_quo,_eol
_sc17_msg7A:
		.BYTE	_Kanjeda,_ddt__quo,_an0,_M,_o,_j,__p,_a,_ro,_l,_mz,_aof,_quo,_eol
_sc17_msg7B:
		.BYTE	_M,_i,_ja,_ko,_ddt__quo,_O,_col_,_h,_o,_ro,_sh,_o,_col_,_ch,_to,__,_t,_ji,_ret
		.BYTE	_v,_e,_r,_n,_u,_l,_s_ja,_exc,__,_V,_ve,_di,__s,_vo,_j,__p,_a,_ro,_l,_mz,_exc_quo,_eol
_sc5_A_msg7F:
		.BYTE	_Kanjeda,_ddt__quo,_str,_k,_h,_e,_str,_ret
		.BYTE	_B,_u,_l,_mz,_k,_dot,_quo,_eol
_sc2_13_15_16_msg82:
		.BYTE	_Kanjeda,_ddt__quo,_P,_re,_k,_ra,_ti,__,_je,_to,_exc_quo,_eol
_sc2_6_msg83:
		.BYTE	_Kanjeda,_ddt__quo,_O,_h,_col_,_ch,_to,__,_ja_,_de,_la,_ju,_dot_dot_dot,_quo,_eol
_sc17_msg84:
		.BYTE	_Kanjeda,__v,_st,_re,_ti,_l,_ret
		.BYTE	_p,_re,_zh,_de,_v,_re,_m,_en,_n,_ji,_j,__,_ko,_ne,_c,_dot_dot_dot,_eol
_sc2_F_10_12_13_msg85:
		.BYTE	_Kanjeda,_ddt__quo,_dot_dot_dot,_quo,_eol
_sc17_msg86:
		.BYTE	_I,_g,_ra,__,_o,_ko,_n,_ch,_e,_na,_exc,_ret
		.BYTE	_P,_o,_zh,_a,_l,_u,_j,_st,_a,_col_,_po,_p,_ro,_b,_u,_j,__s,_no,_va,_exc,_ret
		.BYTE	_ret
		.BYTE	_K,_no,_p,_ka,__,_A,_ddt__quo,_P,_o,_p,_ro,_b,_u,_e,_m,__,_e,_sch,_jo,_exc_quo,_ret
		.BYTE	_K,_no,_p,_ka,__,_V,_ddt__quo,_S,__,_m,_en,_ja_,_h,_va,_ti,_t,_exc_quo,_eol
_sc6_15_msg88:
		.BYTE	_Kanjeda,_ddt__quo,_Tjecuo,_dot_dot_dot,_ret
		.BYTE	_CH,_to,__,_t,_ji,__s,_de,_la,_l,_que,_exc_quo,_eol
_sc6_15_msg89:
		.BYTE	_Tjecuo,_ddt__quo,_an0,_T,_mz,_f,_u,_dot_dot_dot,_ret
		.BYTE	_str,_p,_f,_str,_f,_str,__,_str,_p,_f,_str,_f,_str,_ret
		.BYTE	_O,_h,_dot_dot_dot,__,_o,_h,_dot,_aof,_quo,_eol
_sc17_msg8C:
		.BYTE	_Kanjeda,__b,_ji,_l_,_po,_j,_m,_a,_n,__v,_oennji,_m,_i,__,_i,_ret
		.BYTE	_o,_t,_p,_ra,_v,_l,_en,__v,__,_ko,_lo,_ni,_ju,__,_d,_l,_ja,_ret
		.BYTE	_ne,_s,_o,_ve,_r,_sh,_en,_no,_l,_e,_t,_ni,_h,_dot,_eol
_sc17_msgB6:
		.BYTE	_M,_i,_ja,_ko,_ddt__quo,_T,_vo,_j,__p,_a,_ro,_l,_mz,_ret
		.BYTE	_ret
		.BYTE	_password,_ret
		.BYTE	_ret
		.BYTE	_L,_u,_ch,_sh,_e_,_te,_b,_e_,_ne,__,_za,_b,_ji,_va,_t_mz,__,_e,_go,_exc_quo,_eol
_sc8_A_msg8F:
		.BYTE	_Kanjeda,_ddt__quo,_A,_exc,__,_CH,_to,__,_je,_to,_que_quo,_eol
_scC_D_13_16_msg90:
		.BYTE	_Kanjeda,_ddt__quo,_A,_h,_exc_quo,_ret
		.BYTE	_str,_b,_u,_l,_mz,_k,_str,_eol
_scD_E_13_msg91:
		.BYTE	_Kej,_ddt__quo,_I,_di,_o,_t,_exc_quo,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_A,_str,_a,_str,_a,_h,_exc_quo,_ret
		.BYTE	_ret
		.BYTE	_Kej,_ddt__quo,_O,_h,_exc_quo,_eol
_scF_12_13_15_msg93:
		.BYTE	_Tjecuo,_ddt__quo,_an0,_A,_g,_r,_h,_dot_dot_dot,__,_O,_h,_exc,_aof,_quo,_eol
_scA_10_msg94:
		.BYTE	_D,_ve,_r,_mz_,_za,_p,_e,_r,_ta,_dot,_eol
_sc11_15_msg96:
		.BYTE	_Kanjeda,_ddt__quo,_an0,_P,_ri,_d,_u,_r,_ki,_exc,_aof,_quo,_eol
_sc11_12_13_msg97:
		.BYTE	_Kaj,_ddt__quo,_Kanjeda,_dot_dot_dot,_quo,_eol
_sc13_15_msg99:
		.BYTE	_JA,__,_na,_s,_t,_ro,_i,_l_,_p,_ri,_c,_e,_l_,_na,__,_mo,_jo,_m,_ret
		.BYTE	_la,_z,_e,_re,_dot_dot_dot,_eol
_sc13_15_msg9A:
		.BYTE	_L,_a,_z,_e,_r,__,_u,_da,_ri,_l,__v,__,_g,_ru,_d,_mz_,_Tjecuo,_exc,_ret
		.BYTE	_ret
		.BYTE	_Tjecuo,_ddt__quo,_A,_h,_dot_dot_dot,_quo,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_JA,__s,_de,_la,_l_,_je,_to,_col,_ret
		.BYTE	_JA,_m,_a,_g,_a,_ta,_exc,__,_T,_o,_l,_mz,_ko,__,_d,_l,_ja_,_te,_b,_ja,_exc_quo,_eol
_sc13_15_msg9B:
		.BYTE	_Tjecuo,__,_m,_jo,_r,_t,_v,_dot_dot_dot,_eol
_sc13_15_msg9E:
		.BYTE	_V,_o,_lo,_s,_ji,__,_Tjecuo,__v,_st,_a,_li,__,_d,_ji,_b,_o,_m,_dot,_ret
		.BYTE	_ret
		.BYTE	_Tjecuo,__p,_ri,_go,_to,_v,_i,_l,_s_ja,__p,_u,_st,_i,_t_mz,_ret
		.BYTE	_u,_da,_r,_n,_u,_ju,__,_vo,_l,_n,_u,_exc,_eol
_sc13_15_msg9F:
		.BYTE	_L,_a,_z,_e,_r,__p,_ro,_m,_a,_za,_l,_exc,_eol
_sc2_13_msgA0:
		.BYTE	_Kanjeda,_ddt__quo,_A,_que,__,_N,_e_,_ra,_b,_o,_ta,_e,_t,_exc_quo,_eol
_sc2_15_msgA1:
		.BYTE	_Kanjeda,_ddt__quo,_N,_a,_u,_dot_dot_dot,__,_m,_a,_k,_u,_dot_dot_dot,__s,_a,_dot_dot_dot,_ret
		.BYTE	_U,_m,_dot_dot_dot,__,_m,_a,_n,_dot_dot_dot,__,_da,_que_quo,_ret
		.BYTE	_JA,__,_ni,_ka,_k,__,_ne,__,_mo,_g,_u,__,_za,_po,_m,_ni,_t_mz,_ret
		.BYTE	_je,_t,_u,__,_m,_a,_n,_t,_ru,_dot,_eol
_sc5_6_msgA4:
		.BYTE	_M,_u,_zh,_ch,_i,_na,_ddt__quo,_dot_dot_dot,_quo,_eol
_scC_15_msgA5:
		.BYTE	_D,_l,_ja_,_je,_to,_go,__,_ne,_t,__v,_re,_me,_ni,_exc,_eol
_scA_B_msgA6:
		.BYTE	_T,_e,_r,_ro,_ri,_st,_ddt__quo,_an0,_M,_ji,__s,_o,_b,_i,_ra,_e,_m,_s_ja,_ret
		.BYTE	_p,_ro,_ni,_k,_n,_u,_t_mz,__v,__,_la,_b,_o,_ra,_to,_ri,_ju,_que,_exc,__,_V,_ji,_ret
		.BYTE	_s,__,_u,_m,_a,__s,_o,_sh,_li,_que,__,_D,_a,__,_e,_sch,_jo,__s,__,_JE,_T,_I,_M,_ret
		.BYTE	_p,_a,_r,_ne,_m,_que,_dot,_dot,_aof,_quo,_eol
_scA_B_msgB0:
		.BYTE	_R,_ju,_ddt__quo,_an1,_JE,_to,__s,_ro,_ch,_n,_ji,_j,__p,_ri,_ka,_z,_dot,__,_M,_ji,_ret
		.BYTE	_u,_zh,_e_,_na,_ch,_a,_li,__,_po,_d,_go,_to,_v,_k,_u,_dot,_aof,_quo,_eol
_scA_B_msgA7:
		.BYTE	_T,_e,_r,_ro,_ri,_st,_ddt__quo,_an0,_JE,_to,__p,_ro,_p,_u,_s,_k,_col_,_s,_ret
		.BYTE	_ko,_to,_r,_ji,_m,__,_m,_ji,__,_mo,_zh,_e,_m,__,_po,_p,_a,_s,_t_mz,__v,_ret
		.BYTE	_la,_b,_o,_ra,_to,_ri,_ju,__v,__,_te,_ch,_e,_ni,_e,_ret
		.BYTE	_ne,_de,_li,_dot_dot_dot,_aof,_quo,_eol
_scA_B_msgB1:
		.BYTE	_Kej,_ddt__quo,_an2,_O,_t,__,_m,_i,_st,_e,_ra,__,_N,_e,_d,_z,_u,_col_,_ve,_r,_no,_que,_ret
		.BYTE	_K,_a,_ko,_va,__,_na,_sh,_a,__,_c,_e,_l,_mz,_que,_aof,_quo,_eol
_scA_B_msgB2:
		.BYTE	_R,_ju,_ddt__quo,_an1,_P,_o,_d,_ro,_b,_n,_ji,_e,__s,_ve,_de,_ni,_ja_,_o,_ret
		.BYTE	_no,_ve,_j,_sh,_e,_m,__,_je,_k,_s,_p,_e,_ri,_m,_en,_te,_dot,_aof,_quo,_eol
_scA_B_msgA8:
		.BYTE	_T,_e,_r,_ro,_ri,_st,_ddt__quo,_an0,_N,_o,_v,_ji,_j,_ret
		.BYTE	_je,_k,_s,_p,_e,_ri,_m,_en,_ta,_l,_mz,_n,_ji,_j,__,_o,_b,_tz,_e,_k,_t,_que,_aof,_quo,_eol
_scA_B_msgAF:
		.BYTE	_R,_ju,_ddt__quo,_an1,_V,_e,_r,_no,_dot,__,_N,_a,__p,_ro,_sh,_lo,_j,__,_ne,_de,_l,_e,_ret
		.BYTE	_no,_ch,_mz,_ju,__,_na,_sh,_i,_m,_i,__s,_i,_la,_m,_i,__b,_ji,_l,_ret
		.BYTE	_o,_s,_vo,_b,_o,_zh,_d,_jo,_n,__,_je,_k,_s,_p,_e,_ri,_m,_en,_t,__,_po,_d,_ret
		.BYTE	_ko,_d,_o,_v,_ji,_m,__,_i,_me,_ne,_m,__,_quo,_N,_o,_me,_r,__,_2,_6,_quo,_dot,_aof,_quo,_eol
_scA_B_msgA9:
		.BYTE	_R,_ju,_ddt__quo,_an1,_T,_o,_t,__s,_a,_m,_ji,_j,__p,_a,_r,_ni,_sh,_ka,_col,_ret
		.BYTE	_ko,_to,_r,_ji,_j,__v,_ji,_z,_va,_l,__p,_e,_re,_po,_lo,_h,__v,_ret
		.BYTE	_S,_ta,_ro,_m,__,_go,_ro,_de,__i_,_b,_ji,_l,__s,_no,_va,__v,_z,_ja,_t,_ret
		.BYTE	_po,_d,__,_st,_ra,_zh,_u,__v,__,_la,_b,_o,_ra,_to,_ri,_i,_dot,_aof,_quo,_eol
_scA_B_msgAA:
		.BYTE	_R,_ju,_ddt__quo,_an1,_O,_na,__v,_ji,_g,_l,_ja,_di,_t,__,_ka,_k,_ret
		.BYTE	_u,_ch,_e,_b,_n,_ji,_j,__,_c,_en,_t,_r,_col_,_no,__,_na,__s,_a,_mo,_m,_ret
		.BYTE	_de,_l,_e_,_str,__,_je,_to,__,_la,_b,_o,_ra,_to,_ri,_ja_,_d,_l,_ja,_ret
		.BYTE	_je,_k,_s,_p,_e,_ri,_m,_en,_to,_v,__,_na,_d,__,_l,_ju,_d,_mz,_m,_i,_dot,_aof,_quo,_eol
_sc5_6_15_msgAB:
		.BYTE	_Kanjeda,_ddt__quo,_Tjecuo,_exc_quo,_eol
_sc15_16_msgC5:
		.BYTE	_Tjecuo,_ddt__quo,_an0,_A,_str,_a,_str,_a,_str,_a,_exc,_aof,_quo,_ret
		.BYTE	_ret
		.BYTE	_T,_o,_l,_mz,_ko,__,_li,_c,_o,__,_Tjecuo,__,_o,_st,_a,_lo,_s,_mz,_ret
		.BYTE	_ch,_e,_lo,_ve,_ch,_e,_s,_ki,_m,_col_,_a,__,_o,_st,_a,_l,_mz,_na,_ja_,_e,_go,_ret
		.BYTE	_ch,_a,_s,_t_mz,__p,_re,_v,_ra,_ti,_la,_s,_mz_,_v,_ret
		.BYTE	_b,_e,_s,_f,_o,_r,_m,_en,_n,_u,_ju,__p,_lo,_t_mz,_dot,_eol
_sc15_16_msgC6:
		.BYTE	_Tjecuo,_ddt__quo,_an0,_G,_ra,_str,_a,_exc,_aof,_quo,_ret
		.BYTE	_ret
		.BYTE	_B,_e,_s,_f,_o,_r,_m,_en,_na,_ja_,_p,_lo,_t_mz,__,_i,_s,_p,_u,_st,_i,_la,_ret
		.BYTE	_vo,_p,_l,_mz,_dot,_eol
_sc15_16_msgC7:
		.BYTE	_Tjecuo,_ddt__quo,_an0,_Kanjeda,_col_,_b,_e,_g,_i,_exc,_aof,_quo,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_D,_e,_r,_mz,_mo,_dot_dot_dot,_quo,_ret
		.BYTE	_ret
		.BYTE	_Tjecuo,_ddt__quo,_an0,_G,_a,_str,_a,_exc,_aof,_quo,_eol
_sc15_16_msgC8:
		.BYTE	_K,_i,_jo,_ko,_col_,_M,_a,_s,_a,_ru,__i_,_T,_a,_ka,_s,_i,__,_t,_v,_jo,_r,_d,_o,_ret
		.BYTE	_s,_to,_ja,_li,__,_na,__,_k,_ra,_ju,__,_st,_a,_di,_o,_na,_col_,_ko,_g,_da,_ret
		.BYTE	_p,_lo,_t_mz,__,_na,_ch,_a,_la,__,_za,_po,_l,_n,_ja,_t_mz,__,_e,_go,_dot,_ret
		.BYTE	_P,_e,_re,_d,__,_ni,_m,_i,__b,_ji,_l_,_ko,_n,_te,_j,_ne,_r,__s,_ret
		.BYTE	_o,_b,_ra,_z,_c,_o,_m,_dot,_eol
_sc15_16_msgC9:
		.BYTE	_S,_ve,_t,__,_za,_po,_l,_ni,_l,__v,_e,_s,_mz_,_st,_a,_di,_o,_n,_dot,_eol
_sc15_16_msgCA:
		.BYTE	_K,_a,_k,__,_to,_l,_mz,_ko,__s,_ve,_t,__,_d,_o,_st,_i,_g,__,_z,_da,_ni,_j,_col,_ret
		.BYTE	_na,_ch,_a,_lo,_s,_mz_,_ra,_z,_ru,_sh,_e,_ni,_e_,_S,_ta,_ro,_go,_ret
		.BYTE	_go,_ro,_da,_dot,_eol
_sc15_16_msgCB:
		.BYTE	_S,_ve,_t,__p,_re,_v,_ra,_ti,_l,_s_ja,__v,__,_o,_g,_ro,_m,_n,_u,_ju,_ret
		.BYTE	_s,_f,_e,_ru,_dot,__,_B,_o,_l,_mz,_sh,_a,_ja_,_ch,_a,_s,_t_mz,__,_S,_ta,_ro,_go,_ret
		.BYTE	_go,_ro,_da,__b,_ji,_la,__,_po,_g,_lo,_sch,_e,_na,__,_i,_m,_dot_dot_dot,_eol

		SECTION_END		F17