
		SECTION_START	FD

		MSG_START	_sceneD_msg_lib
		MSG_IDX	_scD_msg00
		MSG_IDX	_scD_msg01
		MSG_IDX	_scD_msg02
		MSG_IDX	_scD_msg03
		MSG_IDX	_scD_msg04
		MSG_IDX	_scD_msg05
		MSG_IDX	_scD_msg06
		MSG_IDX	_scD_msg07
		MSG_IDX	_scD_msg08
		MSG_IDX	_scD_msg09
		MSG_IDX	_scD_msg0A
		MSG_IDX	_scD_msg0C
		MSG_IDX	_scD_msg0D
		MSG_IDX	_scD_msg0E
_scD_msg00:
		.BYTE	_JA,__,_u,_g,_na,_l_,_h,_o,_ve,_r,__i_,_s,__,_Kej,__,_na,__b,_o,_r,_t,_u,_ret
		.BYTE	_po,_l,_e,_te,_l,__v,__,_la,_b,_o,_ra,_to,_ri,_ju,_dot,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_O,_t,_li,_ch,_no,_col_,_m,_ji,__v,_s,_jo,_str,_ta,_ki,_ret
		.BYTE	_s,_p,_ra,_v,_i,_li,_s,_mz,_dot,_quo,_eol
_scD_msg01:
		.BYTE	_Kej,_ddt__quo,_V,_oennji,_e,_exc_quo,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_D,_a,_va,_j,_str,_ka,__,_u,_b,_e,_re,_m,__,_i,_h,_ret
		.BYTE	_s,__,_d,_o,_ro,_g,_i,_exc_quo,_eol
_scD_msg0E:
		.BYTE	_K,_no,_p,_ka,__,_A,_ddt__quo,_S,_t,_re,_l,_ja,_t_mz,_quo,_ret
		.BYTE	_K,_no,_p,_ka,__,_V,_ddt__quo,_U,_k,_lo,_n,_ja,_t_mz,_s_ja,_quo,_eol
_scD_msg02:
		.BYTE	_R,_a,_c,_i,_ja,_ddt__quo,_str,_b,_z,_str,__,_str,_g,_z,_z,_t,_str,_ret
		.BYTE	_dot_dot_dot,_da,_ju,__,_ra,_z,_re,_sh,_e,_ni,_e_,_na,__,_t,_ja,_zh,_e,_lo,_e,_ret
		.BYTE	_vo,_o,_ru,_zh,_e,_ni,_e,_dot_dot_dot,_ret
		.BYTE	_str,_p,_sh,_str,_ret
		.BYTE	_dot_dot_dot,_ka,_p,_i,_ta,_n,_dot_dot_dot,_quo,_ret
		.BYTE	_ret
		.BYTE	_K,_a,_zh,_e,_t,_s_ja,_col_,_ja_,_s,_l,_u,_ch,_a,_j,_no,__v,_k,_l,_ju,_ch,_i,_l,_ret
		.BYTE	_ra,_c,_i,_ju,_dot,_eol
_scD_msg03:
		.BYTE	_R,_a,_c,_i,_ja,_ddt__quo,_str,_b,_z,_t,_str,_ret
		.BYTE	_dot_dot_dot,_je,_to,_t,__p,_a,_c,_a,_n,__v,_i,_di,_mo,__b,_ji,_l,_ret
		.BYTE	_p,_a,_c,_i,_en,_to,_m,__v,__b,_o,_l,_mz,_ni,_ch,_no,_m,__,_k,_r,_ji,_l,_e,_ret
		.BYTE	_la,_b,_o,_ra,_to,_ri,_i,_dot_dot_dot,_quo,_eol
_scD_msg04:
		.BYTE	_Kanjeda,_ddt__quo,_G,_de,__,_Tjecuo,_que,_exc_quo,_ret
		.BYTE	_ret
		.BYTE	_Kej,_ddt__quo,_T,_i,_h,_o,_exc,__,_P,_ri,_b,_a,_v,_mz,_ret
		.BYTE	_g,_ro,_m,_ko,_s,_t_mz,_exc_quo,_eol
_scD_msg05:
		.BYTE	_R,_a,_c,_i,_ja,_ddt__quo,_str,_g,_z,_str,_z,_str,_ret
		.BYTE	_dot_dot_dot,_s,_b,_e,_zh,_a,_l_,_i,_z,__s,_vo,_e,_j,__,_ka,_me,_r,_ji,_dot_dot_dot,_ret
		.BYTE	_str,_p,_sh,_str,_ret
		.BYTE	_dot_dot_dot,_Tjecuo,__,_S,_i,_m,_a,_dot_dot_dot,_quo,_eol
_scD_msg06:
		.BYTE	_R,_a,_c,_i,_ja,_ddt__quo,_dot_dot_dot,_o,_n,__,_na,_p,_ra,_v,_i,_l,_s_ja,__v,_ret
		.BYTE	_de,_t,_s,_k,_u,_ju,_dot_dot_dot,__,_dot_dot_dot,_v,_ji,_dot_dot_dot,_ret
		.BYTE	_str,_p,_sh,_str,_quo,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_Tjecuo,_que,_exc_quo,_eol
_scD_msg07:
		.BYTE	_R,_a,_c,_i,_ja,_ddt__quo,_str,_p,_sh,_str,_ret
		.BYTE	_dot_dot_dot,_s,_i,_t,_u,_a,_c,_i,_ja_,_k,_ra,_j,_ne,__,_o,_p,_a,_s,_na,_exc,_ret
		.BYTE	_o,_go,_n,_mz_,_na,__,_po,_ra,_zh,_e,_ni,_e,_exc,__,_po,_v,_to,_r,_ja,_ju,_col,_ret
		.BYTE	_o,_go,_n,_mz_,_na,__,_po,_ra,_zh,_e,_ni,_e,_exc,_dot,_dot,_quo,_eol
_scD_msg0C:
		.BYTE	_K,_i,_jo,_ko,_ddt__quo,_N,_a,_j,_di,_te,__v,_h,_o,_d,_no,_j,__,_li,_f,_t,_dot,_ret
		.BYTE	_I,_s,_po,_l,_mz,_z,_u,_j,_te,__,_e,_go,_col_,_ch,_to,_b,_ji,_ret
		.BYTE	_s,_p,_u,_st,_i,_t_mz,_s_ja,__,_na,__,_po,_d,_u,_ro,_v,_en,_mz_,_8,_dot,_quo,_eol
_scD_msg0D:
		.BYTE	_N,_a,_ko,_ne,_c,__,_m,_ji,__,_d,_o,_b,_ra,_li,_s,_mz_,_d,_o,_ret
		.BYTE	_vo,_s,_mz,_mo,_go,__,_po,_d,_u,_ro,_v,_n,_ja,_dot,_eol
_scD_msg08:
		.BYTE	_Kej,_ddt__quo,_D,_e,_t,_s,_ka,_ja_,_v,__,_to,_j,__s,_to,_ro,_ne,_dot,_quo,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_CH,_to,_que_quo,_ret
		.BYTE	_ret
		.BYTE	_Kej,_ddt__quo,_P,_o,_vo,_ra,_ch,_i,_va,_j,__,_t,_u,_da,_exc_quo,_eol
_scD_msg09:
		.BYTE	_Kanjeda,_ddt__quo,_K,_o,_m,_na,_ta,__,_quo,_A,_quo,_que_quo,_ret
		.BYTE	_ret
		.BYTE	_Kej,_ddt__quo,_CH,_to,__,_t,_ji,__,_de,_la,_e,_sh,_mz,_col_,_je,_to,_ret
		.BYTE	_de,_t,_s,_ka,_ja,_exc_quo,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_JA,__,_ne,__,_mo,_g,_u,_ret
		.BYTE	_o,_st,_a,_no,_v,_i,_t_mz,_s_ja,_exc_quo,_eol
_scD_msg0A:
		.BYTE	_Kej,_ddt__quo,_T,_o,_r,_mo,_za,_exc,__,_T,_ji,__,_ne,__,_z,_na,_e,_sh,_mz,_ret
		.BYTE	_p,_ro,__,_to,_r,_mo,_za,_que,_exc_quo,_ret
		.BYTE	_ret
		.BYTE	_K,_a,_ne,_da,_ddt__quo,_JA,__,_ne,__v,_z,_ja,_l,__s,__,_s,_o,_b,_o,_j,_ret
		.BYTE	_p,_ra,_va,_exc_quo,_eol

		SECTION_END		FD
