
		SECTION_START	F9

		MSG_START	_scene9_msg_lib
		MSG_IDX	_sc9_msg01
		MSG_IDX	_sc9_msg02
		MSG_IDX	_sc9_msg03
		MSG_IDX	_sc9_msg04
		MSG_IDX	_sc9_msg05
		MSG_IDX	_sc9_msg06
		MSG_IDX	_sc9_msg07
		MSG_IDX	_sc9_msg08
		MSG_IDX	_sc9_msg09
		MSG_IDX	_sc9_msg0A
		MSG_IDX	_sc9_msg0B
		MSG_IDX	_sc9_msg0C
		MSG_IDX	_sc9_msg0D
		MSG_IDX	_sc9_msg0E
		MSG_IDX	_sc9_msg0F
		MSG_IDX	_sc9_msg10
		MSG_IDX	_sc9_msg11
		MSG_IDX	_sc9_msg12
		MSG_IDX	_sc9_msg13
		MSG_IDX	_sc9_msg14
		MSG_IDX	_sc9_msg15
		MSG_IDX	_sc9_msg8D
		MSG_IDX	_sc9_msg8E
		MSG_IDX	_sc9_msgAE
		MSG_IDX	_sc9_msgB7
_sc9_msgB7:
		.BYTE	_N,_a,_m,__,_ka,_ki,_m,_str,_to,__,_ch,_u,_d,_o,_m,__,_u,_da,_lo,_s,_mz,_ret
		.BYTE	_u,_b,_e,_zh,_a,_t_mz,__,_o,_t,__v,_oennji,_h,_dot,__,_O,_na,_ret
		.BYTE	_po,_ka,_z,_ji,_va,_la,__,_d,_o,_ro,_g,_u,__i_,_m,_ji,__p,_ri,_sh,_li,_ret
		.BYTE	_v,__,_je,_to,__,_me,_s,_to,_dot,_eol
_sc9_msg13:
		.BYTE	_P,_o,_h,_o,_zh,_e_,_na,__,_u,_b,_e,_zh,_i,_sch,_e_,_te,_r,_ro,_ri,_s,_to,_v,_dot,_eol
_sc9_msg01:
		.BYTE	_Kanjeda,_ddt__quo,_M,_ji,__,_mo,_lo,_d,_ji,__i_,_v,_s,_jo,__,_e,_sch,_jo,_ret
		.BYTE	_mo,_zh,_e,_m,__,_o,_zh,_i,_v,_i,_t_mz,__,_na,_sh,_i,__,_o,_t,_no,_sh,_e,_ni,_ja,_dot,_ret
		.BYTE	_T,_a,_k,__,_ka,_k,__,_na,_s,_ch,_jo,_t,__,_na,_m,__s,__,_to,_b,_o,_j,_dot_dot_dot,_quo,_eol
_sc9_msg02:
		.BYTE	_D,_e,_v,_u,_sh,_ka,_ddt__quo,_an0,_R,_ju,_exc,_aof,_quo,_eol
_sc9_msg03:
		.BYTE	_Kanjeda,_ddt__quo,_JE,_j,_col_,_ne,__,_u,_b,_e,_g,_a,_j,_exc,__,_V,_i,_d,_no,_col,_ret
		.BYTE	_ch,_to,__,_t,_ji,__v,__p,_e,_r,_v,_ji,_j,__,_ra,_z,__,_u,_b,_i,_va,_e,_sh,_mz,_ret
		.BYTE	_ch,_e,_lo,_ve,_ka,_dot,_quo,_eol
_sc9_msg14:
		.BYTE	_D,_e,_v,_u,_sh,_ka,_ddt__quo,_an0,_dot_dot_dot,_R,_ju,_col_,_g,_de,__,_t,_ji,_que,_aof,_quo,_eol
_sc9_msg04:
		.BYTE	_Kanjeda,_ddt__quo,_K,_o,_g,_da,__,_t,_ji,__,_u,_s,_po,_ko,_i,_sh,_mz,_s_ja,_ret
		.BYTE	_i,__p,_e,_re,_st,_a,_ne,_sh,_mz_,_d,_u,_m,_a,_t_mz,__,_o,_b,__,_je,_to,_m,_col,_ret
		.BYTE	_m,_ji,__,_mo,_g,_li,__b,_ji,__,_g,_de,_str,_ni,_b,_u,_d,_mz,_ret
		.BYTE	_p,_e,_re,_k,_u,_s,_i,_t_mz,_dot_dot_dot,_eol
_sc9_msg05:
		.BYTE	_Kanjeda,_ddt__quo,_R,_a,_s,_s,_la,_b,_mz,_s_ja,_col_,_ch,_to,_ret
		.BYTE	_s,_de,_la,_no,_col_,_to,__s,_de,_la,_no,_col_,_ni,_ch,_e,_go,_ret
		.BYTE	_u,_zh,_e_,_ne,__,_i,_z,_me,_ni,_t_mz,_dot,_quo,_eol
_sc9_msg0E:
		.BYTE	_Kanjeda,_ddt__quo,_Kej,_col_,_k,_to,__,_je,_ti,__,_st,_ra,_sh,_n,_ji,_e,_ret
		.BYTE	_st,_a,_r,_ji,_e,__p,_a,_r,_ni,_que_quo,_eol
_sc9_msg06:
		.BYTE	_T,_e,_r,_ro,_ri,_st,_ddt__quo,_an0,_K,_to,__,_t,_ji,_que,_exc,_aof,_quo,_ret
		.BYTE	_ret
		.BYTE	_R,_ju,_ddt__quo,_an1,_Kej,_que,_exc,_aof,_quo,_ret
		.BYTE	_ret
		.BYTE	_Kej,_ddt__quo,_R,_ju,_col_,_t,_ji,__s,_p,_a,_s,_s_ja,_exc_quo,_eol
_sc9_msg07:
		.BYTE	_JE,_to,_go,__,_ch,_e,_lo,_ve,_ka,__v,_i,_di,_mo,__,_z,_o,_v,_u,_t,_ret
		.BYTE	_R,_ju,_dot,_eol
_sc9_msg08:
		.BYTE	_O,_ni,__,_po,_h,_o,_zh,_i,__,_na,__,_l,_ju,_de,_j,_col,_ret
		.BYTE	_po,_v,_i,_da,_v,_sh,_i,_h,__,_m,_no,_go,__,_k,_ro,_v,_i,_dot,_eol
_sc9_msg09:
		.BYTE	_T,_e,_r,_ro,_ri,_st,_ddt__quo,_an0,_K,_to,__,_i,_d,_jo,_t,_que,_exc,_aof,_quo,_eol
_sc9_msg0A:
		.BYTE	_Z,_na,_ch,_i,_t,_col_,_je,_to,__,_Kej,_dot_dot_dot,__,_H,_a,_col_,_te,_p,_e,_r,_mz,_ret
		.BYTE	_ja,__,_z,_na,_ju,__,_e,_jo,__,_i,_m,_ja,_dot,__,_N,_e_,_z,_na,_ju,_col_,_k,_to,_ret
		.BYTE	_v,_s,_e_,_je,_ti,__,_l,_ju,_di,_col_,_no,__,_o,_na,__,_ka,_zh,_e,_t,_s_ja,_ret
		.BYTE	_z,_na,_ko,_m,_a,__s,__,_o,_d,_ni,_m,__,_i,_z,__,_ni,_h,_dot,_eol
_sc9_msg0B:
		.BYTE	_T,_e,_r,_ro,_ri,_st,_ddt__quo,_an0,_SH,_p,_i,_o,_n,_que,_exc,_aof,_quo,_eol
_sc9_msg0C:
		.BYTE	_Kanjeda,_ddt__quo,_V,_o,_o,_b,_sch,_e,_str,_to,__v,_oennji,_e,_ret
		.BYTE	_po,_j,_m,_a,_li,__,_Kej,__v,__,_ka,_na,_li,_za,_c,_i,_i,_col_,_a,_ret
		.BYTE	_ja,__s,_p,_a,_s,__,_e,_jo,_dot,__,_R,_a,_z,_ve,__,_ja_,_ne,_ret
		.BYTE	_za,_s,_l,_u,_zh,_i,_va,_ju,__b,_la,_go,_da,_r,_no,_st,_i,_que_quo,_eol
_sc9_msg0D:
		.BYTE	_Kanjeda,_ddt__quo,_JA,_que,__,_N,_u,_dot_dot_dot,__,_je,_str,_je,_str,_je,_col_,_ka,_k,_ret
		.BYTE	_b,_ji,__,_je,_to,__s,_ka,_za,_t_mz,_dot_dot_dot,__,_JA,__p,_a,_re,_n,_mz,_ret
		.BYTE	_Kej,_dot,__,_H,_o,_t,_ja,_col_,_je,_to,_col_,_na,_ve,_r,_no,_e,_col,_ret
		.BYTE	_g,_ro,_m,_ko,__s,_ka,_za,_no,_dot_dot_dot,_quo,_eol
_sc9_msg0F:
		.BYTE	_Kej,_ddt__quo,_JE,_to,__p,_ra,_v,_da,_dot_dot_dot,__,_JE,_to,_t,_ret
		.BYTE	_p,_a,_re,_n,_mz_,_s,_o,_ve,_r,_sh,_en,_no,__,_to,_ch,_no,__,_ne,_ret
		.BYTE	_sh,_p,_i,_o,_n,_dot,_quo,_eol
_sc9_msg10:
		.BYTE	_Kej,_ddt__quo,_T,_ji,__,_ne,__,_z,_na,_e,_sh,_mz_,_m,_en,_ja,_exc_quo,_eol
_sc9_msg11:
		.BYTE	_JE,_to,__p,_a,_re,_n,_mz,_col_,_ko,_to,_ro,_go,__,_ja_,_v,_i,_de,_l,_ret
		.BYTE	_na,__,_a,_l,_l,_e,_e,_dot,_eol
_sc9_msg12:
		.BYTE	_Kanjeda,_ddt__quo,_CH,_e,_st,_no,_que,__,_JA,__v,_oennji,_j,_ret
		.BYTE	_sh,_p,_i,_o,_n,_col_,_o,_t,_p,_ra,_v,_l,_en,_n,_ji,_j,_col_,_ch,_to,_b,_ji,_ret
		.BYTE	_u,_z,_na,_t_mz,__v,_s,_e_,_va,_sh,_i,__p,_la,_n,_ji,_dot_dot_dot,_quo,_eol
_sc9_msg15:
		.BYTE	_Kanjeda,_ddt__quo,_JE,_m,_col_,_no,_dot_dot_dot,__,_u,__,_na,_s,__,_e,_sch,_jo,_ret
		.BYTE	_ne,__b,_ji,_lo,__s,_e,_k,_s,_a,_col_,_po,_ni,_m,_a,_e,_te,_que_quo,_eol
_sc9_msg8D:
		.BYTE	_Kanjeda,_ddt__quo,_JE,_j,_dot_dot_dot,_quo,_eol
_sc9_msg8E:
		.BYTE	_T,_e,_r,_ro,_ri,_st,_ddt__quo,_an0,_CH,_to,__,_t,_ji,__s,_ka,_za,_l,_que,_exc,_aof,_quo,_eol
_sc9_msgAE:
		.BYTE	_B,_a,_m,_exc,_ret
		.BYTE	_ret
		.BYTE	_T,_e,_r,_ro,_ri,_st,__v,_ji,_st,_re,_li,_l_,_i,_z,__s,_vo,_e,_go,_ret
		.BYTE	_p,_i,_s,_to,_l,_e,_ta,_dot,_eol

		SECTION_END		F9
