
		SECTION_START	FE

		MSG_START	_sceneE_msg_lib
		MSG_IDX	_scE_msg00
		MSG_IDX	_scE_msg02
		MSG_IDX	_scE_msg03
		MSG_IDX	_scE_msg04
_scE_msg00:
		.BYTE	_Kanjeda,_ddt__quo,_B,_e,_re,_g,_i,_s,_mz,_exc_quo,_eol
_scE_msg02:
		.BYTE	_SH,_u,_h,_exc,__,_H,_r,_ja,_s,_mz,_exc,_ret
		.BYTE	_ret
		.BYTE	_K,_a,_ne,_da,_ddt__quo,_O,_j,_str,_j,_str,_j,_dot,_quo,_eol
_scE_msg03:
		.BYTE	_M,_ji,__,_d,_o,_st,_i,_g,_li,__,_ko,_m,_na,_t,_ji,__,_quo,_A,_quo,_dot,_ret
		.BYTE	_N,_o,__,_h,_o,_ve,_r,__v,_z,_o,_r,_va,_l,_s_ja,__i_,_m,_ji,__,_u,_p,_a,_li,_ret
		.BYTE	_na,__,_po,_l,_dot,_eol
_scE_msg04:
		.BYTE	_V,_n,_u,_t,_ri,__b,_ji,_li,__,_ne,_s,_ko,_l,_mz,_ko,_ret
		.BYTE	_mo,_r,_sch,_i,_ni,_st,_ji,_h,__,_de,_te,_j,_col_,_v,_oennji,_e,_ret
		.BYTE	_i,_dot_dot_dot,__,_Tjecuo,_dot,_eol

		SECTION_END		FE
