
		SECTION_START	F6

		MSG_START	_scene6_msg_lib
		MSG_IDX	_sc6_msg00
		MSG_IDX	_sc6_msg01
		MSG_IDX	_sc6_msg02
		MSG_IDX	_sc6_msg03
		MSG_IDX	_sc6_msg04
		MSG_IDX	_sc6_msg05
		MSG_IDX	_sc6_msg06
		MSG_IDX	_sc6_msg07
		MSG_IDX	_sc6_msg08
		MSG_IDX	_sc6_msg09
		MSG_IDX	_sc6_msg0A
		MSG_IDX	_sc6_msg0B
		MSG_IDX	_sc6_msg0C
		MSG_IDX	_sc6_msg0D
		MSG_IDX	_sc6_msg0E
		MSG_IDX	_sc6_msg0F
		MSG_IDX	_sc6_msg10
		MSG_IDX	_sc6_msg11
		MSG_IDX	_sc6_msg12
		MSG_IDX	_sc6_msg13
		MSG_IDX	_sc6_msg14
		MSG_IDX	_sc6_msg15
		MSG_IDX	_sc6_msg16
		MSG_IDX	_sc6_msg17
		MSG_IDX	_sc6_msg18
		MSG_IDX	_sc6_msg19
		MSG_IDX	_sc6_msg1A
		MSG_IDX	_sc6_msg1B
		MSG_IDX	_sc6_msg1C
		MSG_IDX	_sc6_msg1D
		MSG_IDX	_sc6_msg1E
		MSG_IDX	_sc6_msg1F
		MSG_IDX	_sc6_msg20
		MSG_IDX	_sc6_msg21
		MSG_IDX	_sc6_msg22
		MSG_IDX	_sc6_msg23
		MSG_IDX	_sc6_msg24
		MSG_IDX	_sc6_msg25
		MSG_IDX	_sc6_msg26
		MSG_IDX	_sc6_msg27
		MSG_IDX	_sc6_msg28
		MSG_IDX	_sc6_msg29
		MSG_IDX	_sc6_msg2A
		MSG_IDX	_sc6_msg2B
		MSG_IDX	_sc6_msg2C
		MSG_IDX	_sc6_msg2D
		MSG_IDX	_sc6_msg2E
		MSG_IDX	_sc6_msg87
		MSG_IDX	_sc6_msgAD
_sc6_msg00:
		.BYTE	_Kanjeda,_ddt__quo,_P,_o,_d,_o,_zh,_di,_exc_quo,_ret
		.BYTE	_ret
		.BYTE	_M,_ji,__,_na,_ko,_ne,_c,__,_na,_sh,_li,__,_Tjecuo,_ret
		.BYTE	_ne,_da,_l,_e,_ko,__,_o,_t,__p,_ro,_m,_z,_o,_n,_ji,_dot,_eol
_sc6_msg01:
		.BYTE	_O,_d,_na,_ko,_col_,_na,__,_Tjecuo,__i_,_de,_v,_u,_sh,_k,_u,_ret
		.BYTE	_na,_p,_a,_li,__,_K,_lo,_u,_n,_ji,_exc,__,_JA,__b,_ji,_st,_ro,_ret
		.BYTE	_s,_p,_r,_ji,_g,_n,_u,_l,__s,_o,__s,_vo,_e,_go,__b,_a,_j,_ka,_dot,_ret
		.BYTE	_ret
		.BYTE	_Kaj,_ddt__quo,_Kanjeda,_col_,_b,_e,_re,_g,_i,_s,_mz,_exc_quo,_eol
_sc6_msg02:
		.BYTE	_ZH,_str,_zh,_u,_h,_exc,_ret
		.BYTE	_ret
		.BYTE	_ZH,_e,_l,_e,_z,_na,_ja_,_t,_ru,_b,_a,__p,_ro,_s,_v,_i,_st,_e,_la,_ret
		.BYTE	_vo,_z,_l,_e_,_go,_lo,_v,_ji,__,_K,_a,_n,_je,_d,_ji,_dot,_eol
_sc6_msg03:
		.BYTE	_S,_v,_i,_sch,_exc,_ret
		.BYTE	_ret
		.BYTE	_ZH,_e,_l,_e,_z,_na,_ja_,_t,_ru,_b,_a,__,_K,_lo,_u,_na,__,_ra,_s,_s,_e,_k,_la,_ret
		.BYTE	_vo,_z,_d,_u,_h,_dot,_eol
_sc6_msg87:
		.BYTE	_Kanjeda,_ddt__quo,_O,_j,_str,_o,_j,_exc_quo,_eol
_sc6_msg04:
		.BYTE	_Kaj,_ddt__quo,_T,_ji,__,_ch,_to,_col_,_s,_o,_b,_i,_ra,_e,_sh,_mz,_s_ja,_ret
		.BYTE	_p,_ro,_s,_to,__b,_ro,_s,_i,_t_mz,__,_Tjecuo,_que,_exc_quo,_eol
_sc6_msg05:
		.BYTE	_T,_u,_k,_exc,_ret
		.BYTE	_ret
		.BYTE	_ZH,_e,_l,_e,_z,_na,_ja_,_t,_ru,_b,_a,__,_K,_a,_ja_,_o,_b,_ru,_sh,_i,_la,_s,_mz,_ret
		.BYTE	_na,__,_go,_lo,_v,_u,__,_K,_lo,_u,_na,_dot,_eol
_sc6_msg06:
		.BYTE	_N,_a,_m,__,_u,_da,_lo,_s,_mz_,_s,_p,_a,_st,_i,__,_Tjecuo,_ret
		.BYTE	_i,__,_o,_k,_ru,_zh,_i,_t_mz,__,_K,_lo,_u,_no,_v,_dot,_eol
_sc6_msg07:
		.BYTE	_Tjecuo,__p,_ri,_sh,_jo,_l,__v,__,_ja,_ro,_s,_t_mz,__i_,_na,_p,_a,_l,_ret
		.BYTE	_na,__,_K,_lo,_u,_na,_col_,_ko,_to,_r,_ji,_j,__,_u,_da,_ri,_l,_ret
		.BYTE	_de,_v,_u,_sh,_k,_u,_dot,_eol
_sc6_msg08:
		.BYTE	_Kanjeda,_ddt__quo,_an0,_P,_re,_k,_ra,_ti,_col_,_Tjecuo,_exc,_ret
		.BYTE	_T,_ji,__,_u,_b,_mz,_jo,_sh,_mz_,_e,_go,_exc,__,_CH,_e,_go,__,_te,_b,_e_,_e,_sch,_jo,_ret
		.BYTE	_na,_d,_o,_que,_aof,_quo,_eol
_sc6_msg09:
		.BYTE	_Tjecuo,_ddt__quo,_an1,_JA,__,_ne,__p,_ro,_s,_to,__,_u,_b,_mz,_ju,__,_e,_go,_col,_ret
		.BYTE	_ja,__,_ra,_s,_k,_ro,_ju,__,_e,_go,__,_g,_r,_jo,_b,_a,_n,_n,_u,_ju,_ret
		.BYTE	_b,_a,_sh,_k,_u,_exc,_aof,_quo,_eol
_sc6_msg2C:
		.BYTE	_Kanjeda,_ddt__quo,_an0,_P,_re,_k,_ra,_ti,__s,_e,_j,_ch,_a,_s,__,_zh,_e,_exc,_ret
		.BYTE	_V,_s,_jo,__,_je,_to,__,_to,_l,_mz,_ko,__,_i,_z,_str,_za,__,_to,_go,_col_,_ch,_to,_ret
		.BYTE	_t,_ji,__,_u,_g,_na,_l_,_mo,_j,__b,_a,_j,_k,_exc,__,_H,_va,_ti,_t,_exc,_aof,_quo,_eol
_sc6_msg0A:
		.BYTE	_Tjecuo,_ddt__quo,_an1,_Z,_a,_mo,_l,_ch,_i,_exc,__,_N,_e,__s,_me,_j,__,_m,_ne,_ret
		.BYTE	_p,_ri,_ka,_z,_ji,_va,_t_mz,_exc,_aof,_quo,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_an0,_M,_ji,__b,_e,_s,_po,_ko,_i,_li,_s,_mz_,_za,_ret
		.BYTE	_te,_b,_ja,_dot,_aof,_quo,_eol
_sc6_msg2D:
		.BYTE	_Tjecuo,_ddt__quo,_an1,_P,_o,_ch,_e,_m,_u,__,_t,_ji,__v,_s,_e,_g,_da,_ret
		.BYTE	_p,_ji,_ta,_e,_sh,_mz,_s_ja,__,_m,_en,_ja_,_o,_p,_e,_ka,_t_mz,_que,_aof,_quo,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_an0,_JE,_str,_je,_str,_je,_dot_dot_dot,_aof,_quo,_eol
_sc6_msg0B:
		.BYTE	_Tjecuo,_ddt__quo,_an1,_JA,__b,_ji,__s,_p,_ra,_v,_i,_l,_s_ja,__s,_a,_m,_exc,_ret
		.BYTE	_M,_en,_ja,__i_,_ra,_n,_mz,_sh,_e_,_ch,_a,_s,_to,__b,_i,_li,_dot_dot_dot,_ret
		.BYTE	_N,_o,__,_ja_,_ne,__s,_o,_b,_i,_ra,_ju,_s,_mz_,_te,_r,_p,_e,_t_mz,_ret
		.BYTE	_u,_ni,_zh,_e,_ni,_ja_,_ve,_ch,_no,_exc,_aof,_quo,_ret
		.BYTE	_ret
		.BYTE	_D,_e,_v,_u,_sh,_ka,_ddt__quo,_Tjecuo,_dot_dot_dot,_quo,_eol
_sc6_msg0C:
		.BYTE	_Tjecuo,_ddt__quo,_an1,_Z,_a,_t,_k,_ni,_s,_mz,_exc,__,_P,_ro,_va,_li,_va,_j,_exc,_aof,_quo,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_an0,_JE,_j,_col_,_po,_s,_to,_j,_exc,__,_K,_u,_da,__,_t,_ji,_ret
		.BYTE	_s,_o,_b,_ra,_l,_s_ja,_que,_aof,_quo,_ret
		.BYTE	_ret
		.BYTE	_Tjecuo,_ddt__quo,_an0,_O,_st,_a,_v,_mz,_te,__,_m,_en,_ja_,_v,_ret
		.BYTE	_po,_ko,_e,_exc,_aof,_quo,_eol
_sc6_msg0D:
		.BYTE	_Tjecuo,__,_ra,_s,_to,_l,_ka,_l_,_na,_s,__i_,_po,_sh,_jo,_l,_ret
		.BYTE	_p,_ro,_ch,_mz,_dot,_ret
		.BYTE	_ret
		.BYTE	_Tjecuo,_ddt__quo,_A,_j,_exc_quo,_eol
_sc6_msg2E:
		.BYTE	_Tjecuo,__v,_d,_ru,_g,__s,_h,_va,_ti,_l,_s_ja,__,_za,_ret
		.BYTE	_go,_lo,_v,_u,__i_,_na,_ch,_a,_l,__s,_to,_na,_t_mz,__,_o,_t,_ret
		.BYTE	_b,_o,_li,_dot,_ret
		.BYTE	_ret
		.BYTE	_Tjecuo,_ddt__quo,_A,_str,_a,_dot_dot_dot,_quo,_eol
_sc6_msg0F:
		.BYTE	_A,_K,_I,_R,_A,_exc,_eol
_sc6_msg0E:
		.BYTE	_Tjecuo,_ddt__quo,_an1,_A,_K,_I,_R,_A,_que,_exc,_ret
		.BYTE	_CH,_to,__p,_ro,_i,_s,_h,_o,_dot_dot_dot,_ret
		.BYTE	_A,_str,_a,_str,_a,_exc,_aof,_quo,_eol
_sc6_msgAD:
		.BYTE	_A,_K,_I,_R,_A,_exc,_exc,_exc,_eol
_sc6_msg10:
		.BYTE	_Kanjeda,_ddt__quo,_Tjecuo,_dot_dot_dot,_quo,_ret
		.BYTE	_ret
		.BYTE	_Kaj,_ddt__quo,_JE,_j,_dot_dot_dot,_quo,_ret
		.BYTE	_ret
		.BYTE	_Tjecuo,__,_na,_ch,_a,_la,__b,_i,_t_mz,__,_d,_ro,_zh,_mz,_dot_dot_dot,_eol
_sc6_msg11:
		.BYTE	_V,_ne,_za,_p,_no,_col_,_po,_d,_tz,_e,_h,_a,_la,__,_ch,_jo,_r,_na,_ja,_ret
		.BYTE	_to,_ni,_ro,_va,_n,_na,_ja_,_m,_a,_sh,_i,_na,__i_,_P,_C,_U,_dot,_eol
_sc6_msg12:
		.BYTE	_P,_o,_h,_o,_zh,_e,_col_,_je,_to,__,_m,_a,_sh,_i,_na,__v,_oennji,_h,_dot,_eol
_sc6_msg13:
		.BYTE	_P,_o,__v,_i,_d,_u,__,_je,_to,__,_po,_h,_o,_zh,_e_,_na,__,_P,_C,_U,__,_str,_ret
		.BYTE	_P,_e,_re,_d,_v,_i,_zh,_no,_j,__,_C,_en,_t,_r,__,_U,_p,_ra,_v,_l,_e,_ni,_ja_,_str,_ret
		.BYTE	_la,_b,_o,_ra,_to,_ri,_ju,__,_na,__,_ko,_l,_jo,_s,_a,_h,_dot,_eol
_sc6_msg14:
		.BYTE	_K,_o,_g,_da,__,_ja_,_po,_d,_o,_sh,_jo,_l_,_k,__,_P,_C,_U,_col_,_o,_t,_t,_u,_da,_ret
		.BYTE	_v,_ji,_sh,_li,__,_ne,_s,_ko,_l,_mz,_ko,__,_ch,_e,_lo,_ve,_k,__v,_ret
		.BYTE	_la,_b,_o,_ra,_to,_r,_n,_ji,_h,__,_h,_a,_la,_ta,_h,_dot,_eol
_sc6_msg15:
		.BYTE	_L,_ju,_di,__,_o,_k,_ru,_zh,_i,_li,__,_Tjecuo,__,_i,_ret
		.BYTE	_o,_s,_mo,_t,_re,_li,__,_e,_go,_dot,_eol
_sc6_msg16:
		.BYTE	_A,_s,_s,_i,_st,_en,_t,__,_A,_ddt__quo,_O,_ch,_en,_mz_,_st,_ra,_n,_no,_exc_quo,_ret
		.BYTE	_ret
		.BYTE	_A,_s,_s,_i,_st,_en,_t,__,_B,_ddt__quo,_U,__,_m,_en,_ja_,_s,_i,_n,_ja,_ja,_ret
		.BYTE	_o,_t,_me,_t,_ka,__,_na,__,_t,_re,_t_mz,_e,_m,__,_je,_k,_ra,_ne,_dot,_quo,_ret
		.BYTE	_ret
		.BYTE	_D,_o,_k,_to,_r,_ddt__quo,_CH,_to,_que,__,_N,_e,_t,_exc,__,_Z,_a,_b,_e,_ri,_te,_ret
		.BYTE	_o,_b,_tz,_e,_k,_t,_exc,__,_S,_ko,_re,_e,_exc_quo,_eol
_sc6_msg17:
		.BYTE	_P,_o,_h,_o,_zh,_e,_col_,_o,_ni,__,_ch,_to,_str,_to,__v,_ko,_lo,_li,_ret
		.BYTE	_Tjecuo,_dot,_eol
_sc6_msg18:
		.BYTE	_K,_a,_zh,_e,_t,_s_ja,_col_,_Tjecuo,__,_o,_ch,_en,_mz_,_n,_u,_zh,_en,_ret
		.BYTE	_l,_ju,_d,_ja,_m,__v,__b,_e,_lo,_m,__,_i,_z,__,_P,_C,_U,_dot,_eol
_sc6_msg19:
		.BYTE	_Kanjeda,_ddt__quo,_O,_st,_a,_v,_mz,_te,__,_mo,_e,_go,__,_d,_ru,_g,_a,_ret
		.BYTE	_v,__,_po,_ko,_e,_exc_quo,_eol
_sc6_msg1A:
		.BYTE	_Kanjeda,_ddt__quo,_JE,_j,_exc,__,_CH,_to,__,_e,_sch,_jo,__,_za,_ret
		.BYTE	_quo,_o,_b,_tz,_e,_k,_t,_quo,_que_quo,_eol
_sc6_msg1B:
		.BYTE	_K,_o,_g,_da,__,_ja_,_po,_p,_ji,_ta,_l,_s_ja,__,_po,_d,_b,_e,_zh,_a,_t_mz,__,_k,_ret
		.BYTE	_Tjecuo,_col_,_ch,_e,_lo,_ve,_k,__v,__,_ch,_jo,_r,_no,_m,_ret
		.BYTE	_p,_re,_g,_ra,_di,_l_,_m,_ne,__p,_u,_t_mz,_dot,_eol
_sc6_msg1C:
		.BYTE	_Kanjeda,_ddt__quo,_CH,_to,__s,__,_t,_vo,_i,_m,__p,_ri,_ki,_d,_o,_m,_que,_ret
		.BYTE	_N,_a,__,_po,_h,_o,_ro,_n,_ji,__s,_o,_b,_ra,_l,_s_ja,_que_quo,_eol
_sc6_msg1D:
		.BYTE	_M,_u,_zh,_ch,_i,_na,_ddt__quo,_an1,_JE,_j,_col_,_ne,__,_t,_ro,_g,_a,_j,__,_mo,_i,_ret
		.BYTE	_ka,_r,_m,_a,_n,_ji,_exc,_aof,_quo,_eol
_sc6_msg1E:
		.BYTE	_P,_o,_ch,_e,_m,_u,__,_z,_de,_s,_mz_,_v,_oennji,_e,_que,_eol
_sc6_msg1F:
		.BYTE	_M,_u,_zh,_ch,_i,_na,_ddt__quo,_an1,_P,_re,_k,_ra,_ti,_te,_ret
		.BYTE	_p,_re,_p,_ja,_t,_st,_vo,_va,_t_mz,__,_za,_de,_r,_zh,_a,_ni,_ju,_exc,_aof,_quo,_eol
_sc6_msg20:
		.BYTE	_P,_ro,_ch,_mz_,_s,__,_d,_o,_ro,_g,_i,_exc,_ret
		.BYTE	_ret
		.BYTE	_M,_u,_zh,_ch,_i,_na,__v,_ji,_st,_re,_li,_l_,_i,_z,__s,_vo,_e,_go,_ret
		.BYTE	_p,_i,_s,_to,_l,_e,_ta,_dot,_eol
_sc6_msg21:
		.BYTE	_Kanjeda,_ddt__quo,_M,_f,_str,_f,_col_,_h,_f,_str,_f,_dot_dot_dot,_quo,_ret
		.BYTE	_ret
		.BYTE	_JA,__p,_ji,_ta,_l,_s_ja,__,_k,_ri,_ch,_a,_t_mz,_col_,_no,__,_mo,_j,__,_ro,_t,_ret
		.BYTE	_b,_ji,_l_,_za,_zh,_a,_t,_dot,_eol
_sc6_msg22:
		.BYTE	_Kanjeda,_ddt__quo,_P,_a,_r,_ni,_col_,_v,_ji,__s,_l,_u,_ch,_a,_j,_no,_ret
		.BYTE	_ne,__v,_oennji,_e,_que_quo,_eol
_sc6_msg23:
		.BYTE	_Kanjeda,_ddt__quo,_K,_u,_da,__v,_ji,__,_za,_b,_i,_ra,_e,_te,_ret
		.BYTE	_Tjecuo,_que,_exc_quo,_eol
_sc6_msg24:
		.BYTE	_Kanjeda,_ddt__quo,_CH,_jo,_r,_t,__,_vo,_z,_mz,_m,_i,_col_,_ve,_r,_ni,_te,_ret
		.BYTE	_Tjecuo,__,_na,_za,_d,_exc_quo,_eol
_sc6_msg25:
		.BYTE	_SH,_m,_ja,_k,_exc,_ret
		.BYTE	_ret
		.BYTE	_Kanjeda,_ddt__quo,_O,_j,_exc_quo,_ret
		.BYTE	_ret
		.BYTE	_M,_u,_zh,_ch,_i,_na,__s,_b,_i,_l_,_m,_en,_ja_,_s,__,_no,_g,_dot,_eol
_sc6_msg27:
		.BYTE	_E,_d,_va,__,_ja_,_na,_ch,_a,_l_,_po,_d,_ni,_m,_a,_t_mz,_s_ja,_col_,_ka,_k,_ret
		.BYTE	_m,_u,_zh,_ch,_i,_na,__s,_e,_l,__v,__,_m,_a,_sh,_i,_n,_u,_dot,_eol
_sc6_msg26:
		.BYTE	_Kanjeda,_ddt__quo,_N,_e,_t,_exc,__,_P,_o,_d,_o,_zh,_di,_te,_exc_quo,_ret
		.BYTE	_ret
		.BYTE	_P,_C,_U,__i_,_m,_a,_sh,_i,_na,__v,_oennji,_h,__,_u,_e,_h,_a,_li,_dot,_eol
_sc6_msg28:
		.BYTE	_D,_o,_k,_to,_r,_ddt__quo,_JE,_k,_s,_p,_e,_ri,_m,_en,_ta,_l,_mz,_n,_ji,_j,_ret
		.BYTE	_o,_b,_tz,_e,_k,_t,__s,_no,_va,__,_u,__,_na,_s,_dot,__,_O,_t,_ne,_s,_i,_te,_ret
		.BYTE	_e,_go,__v,__,_P,_C,_U,_dot,__,_M,_ji,__,_vo,_z,_v,_ra,_sch,_a,_e,_m,_s_ja,_dot,_quo,_eol
_sc6_msg29:
		.BYTE	_CH,_e,_lo,_ve,_k,__v,__,_ch,_jo,_r,_no,_m,__v,_ji,_sh,_e,_l_,_i,_z,_ret
		.BYTE	_a,_r,_me,_j,_s,_ko,_j,__,_m,_a,_sh,_i,_n,_ji,_col_,_ch,_to,_b,_ji,_ret
		.BYTE	_za,_sch,_i,_ti,_t_mz,__,_l,_ju,_de,_j,__v,_ret
		.BYTE	_la,_b,_o,_ra,_to,_r,_n,_ji,_h,__,_h,_a,_la,_ta,_h,_dot,_eol
_sc6_msg2A:
		.BYTE	_L,_ju,_di,__v,__,_la,_b,_o,_ra,_to,_r,_n,_ji,_h,__,_h,_a,_la,_ta,_h,_ret
		.BYTE	_vo,_z,_v,_ra,_ti,_li,_s,_mz_,_na,_za,_d,__v,__,_P,_C,_U,_dot,_eol
_sc6_msg2B:
		.BYTE	_M,_u,_zh,_ch,_i,_na,_ddt__quo,_an0,_N,_e_,_na,_g,_l,_e,_j,_col_,_p,_a,_c,_a,_n,_exc,_aof,_quo,_ret
		.BYTE	_ret
		.BYTE	_M,_u,_zh,_ch,_i,_na,__s,_k,_ru,_ti,_l_,_m,_ne,__,_ru,_ki,__,_za,_ret
		.BYTE	_s,_p,_i,_no,_j,_dot,_eol

		SECTION_END		F6
