
		SECTION_START	F12

		MSG_START	_scene12_msg_lib
		MSG_IDX	_sc12_msg00
		MSG_IDX	_sc12_msg01
		MSG_IDX	_sc12_msg02
		MSG_IDX	_sc12_msg03
		MSG_IDX	_sc12_msg04
		MSG_IDX	_sc12_msg05
		MSG_IDX	_sc12_msg06
		MSG_IDX	_sc12_msg07
		MSG_IDX	_sc12_msg08
		MSG_IDX	_sc12_msg09
		MSG_IDX	_sc12_msg0A
		MSG_IDX	_sc12_msg0B
		MSG_IDX	_sc12_msg0C
		MSG_IDX	_sc12_msg0D
		MSG_IDX	_sc12_msg0E
		MSG_IDX	_sc12_msg0F
		MSG_IDX	_sc12_msg10
		MSG_IDX	_sc12_msg11
		MSG_IDX	_sc12_msg12
		MSG_IDX	_sc12_msg13
		MSG_IDX	_sc12_msg14
		MSG_IDX	_sc12_msg15
		MSG_IDX	_sc12_msg16
		MSG_IDX	_sc12_msg17
		MSG_IDX	_sc12_msg18
		MSG_IDX	_sc12_msg19
		MSG_IDX	_sc12_msg1A
		MSG_IDX	_sc12_msg1B
		MSG_IDX	_sc12_msg1C
		MSG_IDX	_sc12_msg1D
		MSG_IDX	_sc12_msg1E
		MSG_IDX	_sc12_msg1F
		MSG_IDX	_sc12_msg20
		MSG_IDX	_sc12_msg21
		MSG_IDX	_sc12_msg22
		MSG_IDX	_sc12_msg23
		MSG_IDX	_sc12_msg24
		MSG_IDX	_sc12_msg25
		MSG_IDX	_sc12_msg26
		MSG_IDX	_sc12_msg27
		MSG_IDX	_sc12_msg28
		MSG_IDX	_sc12_msg29
_sc12_msg00:
		.BYTE	_K,_o,_g,_da,__,_ja_,_p,_ro,_h,_o,_di,_l_,_m,_i,_mo,__,_m,_a,_g,_a,_z,_i,_na,_ret
		.BYTE	_je,_l,_e,_k,_t,_ro,_ni,_ki,_col_,_po,__,_te,_l,_e,_v,_i,_z,_o,_ru,_ret
		.BYTE	_sh,_jo,_l_,_re,_po,_r,_ta,_zh,__i_,_po,_ka,_z,_ji,_va,_li,_ret
		.BYTE	_v,_oennji,_e,__v,_e,_r,_to,_l,_jo,_t,_ji,_dot,_eol
_sc12_msg01:
		.BYTE	_R,_e,_po,_r,_t,_jo,_r,_ddt__quo,_an0,_CH,_to,__p,_ro,_i,_s,_h,_o,_di,_t,__v,_ret
		.BYTE	_N,_e,_o,_str,_T,_o,_ki,_o,_que,_dot,_dot,__,_K,_a,_k,__v,_ji,__,_mo,_zh,_e,_te,_ret
		.BYTE	_v,_i,_de,_t_mz,__,_na,__,_je,_ti,_h,__,_ka,_d,_ra,_h,_col_,_go,_ro,_d,_ret
		.BYTE	_o,_h,_va,_ch,_en,__p,_la,_me,_ne,_m,_exc,__,_T,_a,_k,_zh,_e_,_m,_ji,_ret
		.BYTE	_v,_i,_di,_m,__,_m,_no,_zh,_e,_st,_vo,__,_vo,_en,_no,_j,_ret
		.BYTE	_te,_h,_ni,_ki,_exc,_aof,_quo,_eol
_sc12_msg02:
		.BYTE	_R,_e,_po,_r,_t,_jo,_r,_ddt__quo,_an0,_N,_o,__,_k,_to,__,_zh,_e_,_je,_to,_t,_ret
		.BYTE	_mo,_lo,_d,_o,_j,__,_ch,_e,_lo,_ve,_k,_que,__,_N,_e,_u,_zh,_e,_li,__,_o,_n,_ret
		.BYTE	_v,__,_o,_di,_no,_ch,_k,_u,__p,_ro,_ti,_vo,_s,_to,_i,_t,_ret
		.BYTE	_p,_u,_t,_ch,_i,_st,_a,_m,_que,_aof,_quo,_eol
_sc12_msg03:
		.BYTE	_R,_e,_po,_r,_t,_jo,_r,_ddt__quo,_an0,_D,_o,_ro,_g,_i,_e,__s,_l,_u,_sh,_a,_te,_li,_col,_ret
		.BYTE	_m,_u,_zh,_a,_j,_te,_s,_mz,_col_,_v,_oennji,_e,__p,_ji,_ta,_ju,_t,_s_ja,_ret
		.BYTE	_ne,_za,_ko,_n,_no,__p,_re,_r,_va,_t_mz,__,_na,_sh,_u,_ret
		.BYTE	_p,_e,_re,_da,_ch,_u,_exc,__,_S,_vo,_b,_o,_da,__s,_lo,_va,__v,_ret
		.BYTE	_o,_p,_a,_s,_no,_st,_i,_exc,_aof,_quo,_eol
_sc12_msg04:
		.BYTE	_mo,_st,_col_,_o,_n,__p,_e,_re,_s,_e,_ka,_e,_t,__,_mo,_st,_dot_dot_dot,_ret
		.BYTE	_ret
		.BYTE	__,__,__,__,_dot_dot_dot,_v,_oennji,_e,__s,_l,_e,_d,_u,_ju,_t,__,_za,__,_ni,_m,_dot,_ret
		.BYTE	_ret
		.BYTE	_dot_dot_dot,_o,_ni,__,_na,_p,_ra,_v,_l,_ja,_ju,_t,_s_ja,__,_k,_ret
		.BYTE	_O,_li,_m,_p,_i,_j,_s,_ko,_j,__,_st,_ro,_j,_k,_e,_exc,_dot,_dot,_eol
_sc12_msg05:
		.BYTE	_O,_sh,_e,_lo,_m,_l,_jo,_n,_n,_ji,_e_,_z,_e,_va,_ki,_ret
		.BYTE	_p,_e,_re,_sh,_jo,_p,_t,_ji,_va,_li,_s,_mz_,_me,_zh,_d,_u,__s,_o,_b,_o,_j,_ret
		.BYTE	_i,__,_u,_h,_o,_di,_li,__p,_ro,_ch,_mz,_dot,_eol
_sc12_msg06:
		.BYTE	_JA,__p,_ri,_sh,_jo,_l_,_na,__,_mo,_to,_s,_to,_ja,_n,_k,_u,_ret
		.BYTE	_u,__,_sh,_ko,_l,_ji,_dot,_eol
_sc12_msg07:
		.BYTE	_Kaj,_ddt__quo,_T,_ji,__,_de,_j,_st,_v,_i,_te,_l,_mz,_no,__,_h,_o,_ch,_e,_sh,_mz,_ret
		.BYTE	_po,_j,_ti,__,_o,_di,_n,_que_quo,_eol
_sc12_msg25:
		.BYTE	_Kanjeda,_ddt__quo,_CH,_u,_ju,_col_,_i,_m,_en,_no,__,_je,_to,_go,__,_o,_n,_ret
		.BYTE	_i,__,_h,_o,_ch,_e,_t,_dot_dot_dot,_quo,_eol
_sc12_msg24:
		.BYTE	_Kaj,_ddt__quo,_M,_o,_zh,_e,_t,__,_l,_u,_ch,_sh,_e_,_po,_d,_o,_zh,_da,_t_mz,__,_i,_ret
		.BYTE	_po,_s,_mo,_t,_re,_t_mz,_col_,_ch,_to,__b,_u,_de,_t,__,_da,_l,_mz,_sh,_e,_dot,_ret
		.BYTE	_JE,_j,_col_,_Kanjeda,_exc_quo,_eol
_sc12_msg08:
		.BYTE	_Kaj,_ddt__quo,_Kanjeda,_col_,_k,_u,_da,__,_t,_ji,__,_po,_e,_de,_sh,_mz,_que,_ret
		.BYTE	_JA,__,_po,_ni,_m,_a,_ju,_col_,_t,_ji,__,_h,_o,_ch,_e,_sh,_mz_,_o,_to,_m,_st,_i,_t_mz,_ret
		.BYTE	_za,__,_JA,_m,_a,_g,_a,_t,_u,_col_,_no,__,_m,_ji,__,_da,_zh,_e_,_ne,_ret
		.BYTE	_z,_na,_e,_m,_col_,_g,_de,__,_Tjecuo,_exc_quo,_eol
_sc12_msg09:
		.BYTE	_JA,__,_na,_p,_ra,_v,_i,_l,_s_ja,__v,__s,_to,_ro,_n,_u,_ret
		.BYTE	_O,_li,_m,_p,_i,_j,_s,_ko,_j,__,_st,_ro,_j,_ki,_dot,_eol
_sc12_msg1F:
		.BYTE	_JA,__,_o,_st,_a,_no,_v,_i,_l,__s,_vo,_j,__b,_a,_j,_k,__,_i,_ret
		.BYTE	_o,_s,_mo,_t,_re,_l_,_o,_k,_re,_st,_no,_st,_i,_dot,_eol
_sc12_msg21:
		.BYTE	_JA,__,_za,_k,_re,_p,_i,_l_,_la,_z,_e,_r,__,_na,__b,_a,_j,_k,_e,_ret
		.BYTE	_r,_ja,_d,_o,_m,__s,__,_s,_o,_b,_o,_j,__i_,_na,_zh,_a,_l_,_na,_ret
		.BYTE	_k,_no,_p,_k,_u,__,_st,_a,_r,_t,_jo,_ra,_dot,_eol
_sc12_msg23:
		.BYTE	_S,_mo,_t,_r,_ja_,_vo,__v,_s,_e_,_g,_la,_za,_col_,_ja,_ret
		.BYTE	_p,_ro,_d,_o,_l,_zh,_i,_l,__s,_vo,_j,__p,_u,_t_mz,_dot,_eol
_sc12_msg0A:
		.BYTE	_V,_d,_o,_l,_mz_,_sh,_o,_s,_s,_e_,_ja_,_v,_i,_de,_l_,_o,_b,_lo,_m,_ki,_ret
		.BYTE	_v,_oennji,_h,__,_ta,_n,_ko,_v,_col_,_u,_ni,_ch,_to,_zh,_en,_n,_ji,_h,_ret
		.BYTE	_Tjecuo,_dot,_eol
_sc12_msg0B:
		.BYTE	_R,_a,_c,_i,_ja,_ddt__quo,_O,_b,_tz,_e,_k,_t,__,_o,_st,_a,_no,_v,_i,_l,_s_ja,__v,_ret
		.BYTE	_2,__,_k,_m,__,_ju,_zh,_ne,_e_,_O,_li,_m,_p,_i,_j,_s,_ko,_j,_ret
		.BYTE	_st,_ro,_j,_p,_lo,_sch,_a,_d,_ki,_exc,__,_N,_a,_sh,_i,__,_vo,_j,_s,_ka,_ret
		.BYTE	_po,_ch,_ti,__,_po,_l,_no,_s,_t_mz,_ju,__,_u,_ni,_ch,_to,_zh,_en,_ji,_dot_dot_dot,_quo,_eol
_sc12_msg0C:
		.BYTE	_P,_o,_h,_o,_zh,_e,_col_,_ra,_z,_ru,_sh,_e,_no,__,_u,_da,_r,_no,_j,_ret
		.BYTE	_vo,_l,_no,_j,__,_Tjecuo,_dot,__,_T,_a,_m,_col_,_g,_de,__,_o,_na,_ret
		.BYTE	_p,_ro,_ka,_ti,_la,_s,_mz,_col_,_z,_e,_m,_l,_ju,__,_u,_st,_i,_la,_li,_ret
		.BYTE	_t,_ru,_p,_ji,_dot,_eol
_sc12_msg0D:
		.BYTE	_JE,_to,__p,_e,_re,_no,_s,_na,_ja_,_mo,_de,_l,_mz_,_la,_z,_e,_ra,_ret
		.BYTE	_d,_l,_ja_,_p,_e,_h,_o,_t,_ji,_dot,_eol
_sc12_msg0E:
		.BYTE	_Kanjeda,_ddt__quo,_JE,_ta,__,_sh,_t,_u,_ka,_col,_ret
		.BYTE	_ne,_s,_o,_m,_ne,_n,_no,_col_,_s,_mo,_zh,_e,_t,__,_za,_va,_li,_t_mz,_ret
		.BYTE	_Tjecuo,_exc_quo,_eol
_sc12_msg0F:
		.BYTE	_JE,_to,__,_u,_ni,_ch,_to,_zh,_en,_n,_ji,_j,__,_o,_t,_r,_ja,_d,_ret
		.BYTE	_la,_z,_e,_r,_no,_j,__p,_e,_h,_o,_t,_ji,_dot,_eol
_sc12_msg10:
		.BYTE	_O,_li,_m,_p,_i,_j,_s,_ka,_ja_,_st,_ro,_j,_ka,__s,_o,_v,_s,_e,_m,_ret
		.BYTE	_b,_li,_z,_ko,_dot,_eol
_sc12_msg11:
		.BYTE	_P,_o,_d,__,_o,_d,_ni,_m,__,_i,_z,__,_u,_ch,_a,_st,_ko,_v,_ret
		.BYTE	_st,_ro,_ja,_sch,_e,_go,_s_ja,__,_st,_a,_di,_o,_na,__,_o,_t,_k,_r,_ji,_lo,_s,_mz,_ret
		.BYTE	_s,_e,_k,_re,_t,_no,_e_,_po,_d,_z,_e,_m,_no,_e_,_vo,_en,_no,_e,_ret
		.BYTE	_h,_ra,_ni,_li,_sch,_e,_dot,_eol
_sc12_msg26:
		.BYTE	_V,_n,_u,_t,_ri,__,_na,_h,_o,_di,_la,_s,_mz_,_g,_i,_g,_a,_n,_t,_s,_ka,_ja,_ret
		.BYTE	_s,_f,_e,_ra,_str,_h,_o,_lo,_di,_l,_mz,_ni,_k,_dot,_eol
_sc12_msg12:
		.BYTE	_N,_a,_d,__s,_f,_e,_ro,_j,__,_li,_c,_o,_m,__,_k,__,_li,_c,_u,__s,_to,_ja,_li,_ret
		.BYTE	_Tjecuo,__i_,_Kej,_dot,_eol
_sc12_msg13:
		.BYTE	_Tjecuo,_ddt__quo,_T,_ji,__,_ta,_col_,_k,_to,__p,_ri,_sh,_jo,_l,__s,_ret
		.BYTE	_K,_a,_n,_je,_d,_o,_j,_dot_dot_dot,_quo,_eol
_sc12_msg14:
		.BYTE	_Kej,_ddt__quo,_JA,__b,_o,_l,_mz,_sh,_e_,_ne,__,_mo,_g,_u,_ret
		.BYTE	_s,_de,_r,_zh,_i,_va,_t_mz,__,_e,_go,__s,_i,_l,_u,_dot_dot_dot,_quo,_eol
_sc12_msg15:
		.BYTE	_D,_ve,__,_u,_da,_r,_n,_ji,_e_,_vo,_l,_n,_ji,__p,_ro,_re,_za,_li,_ret
		.BYTE	_mo,_ro,_z,_n,_ji,_j,__,_vo,_z,_d,_u,_h,__,_na,_v,_st,_re,_ch,_u,_ret
		.BYTE	_d,_ru,_g,__,_d,_ru,_g,_u,_dot,_ret
		.BYTE	_ret
		.BYTE	_S,__,_o,_b,_e,_i,_h,__s,_to,_ro,_n,__,_po,_s,_ji,_p,_a,_li,_s,_mz,_ret
		.BYTE	_i,_s,_k,_r,_ji,_dot_dot_dot,_eol
_sc12_msg27:
		.BYTE	_Kej,__,_o,_t,_ra,_z,_i,_la,__,_o,_d,_n,_u,__,_i,_z,__,_u,_da,_r,_n,_ji,_h,_ret
		.BYTE	_vo,_l,_n,_dot,_eol
_sc12_msg16:
		.BYTE	_N,_o,__,_a,_u,_ra,__,_vo,_k,_ru,_g,__,_Kej,__,_i,_s,_ch,_e,_z,_la,__,_i,_ret
		.BYTE	_o,_na,__,_u,_p,_a,_la,__,_na,__,_z,_e,_m,_l,_ju,_dot,_eol
_sc12_msg28:
		.BYTE	_V,_ne,_za,_p,_no,_col_,_o,_g,_ro,_m,_na,_ja_,_s,_f,_e,_ra,_ret
		.BYTE	_ra,_z,_va,_li,_la,_s,_mz,__i_,_i,_z,__,_ne,_jo,__,_na,_ch,_a,_l,_ret
		.BYTE	_v,_ji,_h,_o,_di,_t_mz,__,_l,_e,_d,_ja,_no,_j,__,_vo,_z,_d,_u,_h,_dot,_eol
_sc12_msg17:
		.BYTE	_M,_ji,__,_u,_v,_i,_de,_li,__s,_o,_de,_r,_zh,_i,_mo,_e,__s,_f,_e,_r,_ji,_dot,_ret
		.BYTE	_V,_n,_u,_t,_ri,__,_ne,_jo,__,_l,_e,_zh,_a,_l_,_ka,_ko,_j,_str,_to,_ret
		.BYTE	_ko,_n,_te,_j,_ne,_r,_dot,_eol
_sc12_msg22:
		.BYTE	_Tjecuo,_ddt__quo,_an0,_O,_t,_k,_ji,_va,_j,_s_ja,_exc,_aof,_quo,_eol
_sc12_msg18:
		.BYTE	_U,_da,_r,_na,_ja_,_vo,_l,_na,__,_Tjecuo,__,_ra,_z,_b,_i,_la,_ret
		.BYTE	_ko,_n,_te,_j,_ne,_r,_col,__i_,_i,_z,__,_ne,_go,_ret
		.BYTE	_v,_ji,_va,_li,_la,_s,_mz_,_ka,_p,_s,_u,_la,__s,__,_o,_b,_ra,_z,_c,_o,_m,_dot,_ret
		.BYTE	_ret
		.BYTE	_Tjecuo,_ddt__quo,_CH,_to,__,_je,_to,_que_quo,_eol
_sc12_msg19:
		.BYTE	_P,_o,_l,_ko,_v,_ni,_k,_ddt__quo,_JE,_to,__,_A,_ki,_ra,_dot_dot_dot,_ret
		.BYTE	_ko,_to,_ro,_go,__,_t,_ji,__,_ta,_k,__,_h,_o,_te,_l_,_na,_j,_ti,_exc,_ret
		.BYTE	_JE,_to,__,_t,_vo,_j,__,_M,_e,_s,_s,_i,_ja,_exc_quo,_eol
_sc12_msg20:
		.BYTE	_G,_o,_lo,_s,__,_P,_o,_l,_ko,_v,_ni,_ka,__,_ra,_z,_da,_va,_l,_s_ja,_ret
		.BYTE	_ch,_e,_re,_z,__,_me,_g,_a,_f,_o,_n,__,_i,_z,__,_u,_k,_re,_p,_l,_en,_no,_go,_ret
		.BYTE	_ko,_m,_a,_n,_d,_no,_go,__b,_u,_n,_k,_e,_ra,_col_,_ta,_j,_no,_ret
		.BYTE	_po,_st,_ro,_en,_no,_go,__,_na,__,_st,_a,_di,_o,_ne,_dot,_eol
_sc12_msg1A:
		.BYTE	_P,_o,_l,_ko,_v,_ni,_k,_ddt__quo,_P,_o,_s,_l,_e_,_e,_go,_ret
		.BYTE	_ne,_o,_b,_tz,_ja,_s,_ni,_mo,_go,__p,_ro,_b,_u,_zh,_de,_ni,_ja,_col_,_e,_go,_ret
		.BYTE	_te,_lo,__b,_ji,_lo,__,_po,_d,_ve,_r,_g,_n,_u,_to,__v,_s,_e,_m,_ret
		.BYTE	_vo,_z,_mo,_zh,_n,_ji,_m,__,_i,_s,_s,_l,_e,_d,_o,_va,_ni,_ja,_m,_dot_dot_dot,_quo,_eol
_sc12_msg29:
		.BYTE	_P,_o,_l,_ko,_v,_ni,_k,_ddt__quo,_dot_dot_dot,_je,_to,__v,_s,_jo,_col_,_ch,_to,__,_o,_t,_ret
		.BYTE	_ne,_go,__,_o,_st,_a,_lo,_s,_mz,_dot,_quo,_eol
_sc12_msg1B:
		.BYTE	_P,_o,_l,_ko,_v,_ni,_k,_ddt__quo,_U,_ch,_jo,_n,_ji,_e_,_ne,__s,_mo,_g,_li,_ret
		.BYTE	_ra,_z,_g,_a,_da,_t_mz,__,_e,_go,__,_ta,_j,_n,_u,_dot_dot_dot,__,_I,_ret
		.BYTE	_po,_je,_to,_m,_u,_col_,_v,_s,_e,__s,_o,_b,_ra,_n,_n,_ji,_e_,_da,_n,_n,_ji,_e,_ret
		.BYTE	_i,__,_te,_s,_to,_v,_ji,_e_,_o,_b,_ra,_z,_c,_ji,__b,_ji,_li,_ret
		.BYTE	_za,_p,_e,_ch,_a,_ta,_n,_ji,__v,__,_k,_ri,_o,_g,_en,_n,_ji,_h,_ret
		.BYTE	_ka,_p,_s,_u,_la,_h,__,_d,_l,_ja_,_b,_u,_d,_u,_sch,_i,_h,_ret
		.BYTE	_po,_ko,_l,_e,_ni,_j,_dot,_quo,_eol
_sc12_msg1C:
		.BYTE	_P,_o,_l,_ko,_v,_ni,_k,_ddt__quo,_an0,_A,_ki,_ra,__,_da,_v,_no,__,_m,_jo,_r,_t,_v,_dot,_ret
		.BYTE	_N,_u,_col_,_te,_p,_e,_r,_mz_,_t,_ji,__,_d,_o,_vo,_l,_en,_col,_ret
		.BYTE	_Tjecuo,_que,_exc,_aof,_quo,_eol
_sc12_msg1E:
		.BYTE	_P,_o,_l,_ko,_v,_ni,_k,_ddt__quo,_an0,_A,__,_te,_p,_e,_r,_mz,_col_,_po,_j,_d,_jo,_m,_ret
		.BYTE	_s,__,_na,_m,_i,_exc,_aof,_quo,_eol
_sc12_msg1D:
		.BYTE	_Tjecuo,_ddt__quo,_an0,_Z,_a,_t,_k,_ni,_s,_mz,_exc,__,_S,_e,_j,_ch,_a,_s,__,_ne,_ret
		.BYTE	_v,_re,_m,_ja_,_d,_l,_ja_,_t,_vo,_e,_j,__,_na,_u,_ch,_no,_j,_ret
		.BYTE	_e,_ru,_n,_d,_ji,_exc,_aof,_quo,_eol

		SECTION_END		F12
