
		.WORD 0
		.WORD _dictC0
		.WORD _dictC1
		.WORD _dictC2
		.WORD _dictC3
		.WORD _dictC4
		.WORD _dictC5
		.WORD _dictC6
		.WORD _dictC7
		.WORD _dictC8
		.WORD _dictC9
		.WORD _dictCA
		.WORD _dictCB
		.WORD _dictCC
		.WORD _dictCD
		.WORD _dictCE
		.WORD _dictCF							; 10
		.WORD _dictD0
		.WORD _dictD1
		.WORD _dictD2
		.WORD _dictD3
		.WORD _dictD4
		.WORD _dictD5
		.WORD _dictD6
		.WORD _dictD7
		.WORD _dictD8
		.WORD _dictD9
		.WORD _dictDA
		.WORD _dictDB
		.WORD _dictDC
		.WORD _dictDD
		.WORD _dictDE
		.WORD _dictDF							; 20
		.WORD _dictE0
		.WORD _dictE1
		.WORD _dictE2
		.WORD _dictE3
		.WORD _dictE4
		.WORD _dictE5
		.WORD _dictE6
		.WORD _dictE7
		.WORD _dictE8
		.WORD _dictE9
		.WORD _dictEA
		.WORD _dictEB
		.WORD _dictEC
		.WORD _dictED
		.WORD _dictEE
		.WORD _dictEF							; 30
		.WORD _dictF0
		.WORD _dictF1
		.WORD _dictF2
		.WORD _dictF3
		.WORD _dictF4
		.WORD _dictF5
		.WORD _dictF6
		.WORD _dictF7
		.WORD _dictF8
		.WORD _dictF9
		.WORD _dictFA
		.WORD _format_buf						; FB code

		.WORD _dict80							; 3D
		.WORD _dict81
		.WORD _dict82
		.WORD _dict83
		.WORD _dict84
		.WORD _dict85
		.WORD _dict86
		.WORD _dict87
		.WORD _dict88
		.WORD _dict89
		.WORD _dict8A
		.WORD _dict8B
		.WORD _dict8C
		.WORD _dict8D
		.WORD _dict8E
		.WORD _dict8F
		.WORD _dict90
		.WORD _dict91
		.WORD _dict92
		.WORD _dict93
		.WORD _dict94
		.WORD _dict95
		.WORD _dict96
		.WORD _dict97
		.WORD _dict98
		.WORD _dict99
		.WORD _dict9A
		.WORD _dict9B
		.WORD _dict9C
		.WORD _dict9D
		.WORD _dict9E
		.WORD _dict9F

_dict80:		.BYTE	_l,_e,_eol
_dict81:		.BYTE	_m,_e,_eol
_dict82:		.BYTE	_r,_e,_eol
_dict83:		.BYTE	_v,_e,_eol
_dict84:		.BYTE	_i,_t,_eol
_dict85:		.BYTE	_s,_t,_eol
_dict86:		.BYTE	_e,_n,_eol
_dict87:		.BYTE	_e,_r,_eol
_dict88:		.BYTE	_h,_e,_eol
_dict89:		.BYTE	_s,_e,_eol
_dict8A:		.BYTE	_b,_e,_eol
_dict8B:		.BYTE	_l,_l,_eol
_dict8C:		.BYTE	_e,__,_eol
_dict8D:		.BYTE	__,_t,_eol
_dict8E:		.BYTE	__,_a,_eol
_dict8F:		.BYTE	_d,__,_eol
_dict90:		.BYTE	_o,_u,_eol
_dict91:		.BYTE	__,_i,_eol
_dict92:		.BYTE	__,_g,_eol
_dict93:		.BYTE	__,_s,_eol
_dict94:		.BYTE	_t,__,_eol
_dict95:		.BYTE	_s,__,_eol
_dict96:		.BYTE	__,_w,_eol
_dict97:		.BYTE	__,_o,_f,_eol
_dict98:		.BYTE	_a,_n,_eol
_dict99:		.BYTE	_o,_w,_eol
_dict9A:		.BYTE	_r,_o,_eol
_dict9B:		.BYTE	_a,_r,_eol
_dict9C:		.BYTE	_a,_t,_eol
_dict9D:		.BYTE	_o,_o,_eol
_dict9E:		.BYTE	_o,_r,_eol
_dict9F:		.BYTE	_a,_d,_eol

_dictC0:		.BYTE	_Y,_a,_m,_a,_g,_a,_t,_a,_eol
_dictC1:		.BYTE	_T,_e,_r,_r,_o,_r,_i,_s,_t,_eol
_dictC2:		.BYTE	_T,_a,_k,_a,_s,_h,_i,_eol
_dictC3:		.BYTE	_A,_k,_i,_r,_a,_eol
_dictC4:		.BYTE	_C,_o,_l,_o,_n,_e,_l,_eol
_dictC5:		.BYTE	_I,_apo,_eol
_dictC6:		.BYTE	_G,_r,_o,_u,_p,_i,_e,_eol
_dictC7:		.BYTE	_C,_l,_o,_w,_n,_eol
_dictC8:		.BYTE	_Y,_o,_u,_apo,_r,_e,_eol
_dictC9:		.BYTE	_e,_d,_eol
_dictCA:		.BYTE	_l,_a,_s,_e,_r,_eol
_dictCB:		.BYTE	_N,_e,_o,__,_T,_o,_k,_y,_o,_eol
_dictCC:		.BYTE	_b,_e,_f,_o,_r,_e,_eol
_dictCD:		.BYTE	_b,_u,_i,_l,_d,_i,_n,_g,_eol
_dictCE:		.BYTE	_v,_e,_r,_y,_o,_n,_e,_eol
_dictCF:		.BYTE	_a,_r,_o,_u,_n,_d,_eol
_dictD0:		.BYTE	_M,_a,_s,_a,_r,_u,_eol
_dictD1:		.BYTE	_D,_a,_m,_n,_eol
_dictD2:		.BYTE	_h,_e,_r,_eol
_dictD3:		.BYTE	_R,_y,_u,_eol
_dictD4:		.BYTE	_i,_n,_eol
_dictD5:		.BYTE	_s,_e,_w,_e,_r,_eol
_dictD6:		.BYTE	_t,_o,_l,_l,_b,_o,_o,_t,_h,_eol
_dictD7:		.BYTE	_N,_u,_r,_s,_e,_r,_y,_eol
_dictD8:		.BYTE	_x,_p,_e,_r,_i,_m,_e,_n,_t,_a,_l,_eol
_dictD9:		.BYTE	__,_t,_h,_e,_eol
_dictDA:		.BYTE	_T,_e,_t,_s,_u,_o,_eol
_dictDB:		.BYTE	_K,_a,_n,_e,_d,_a,_eol
_dictDC:		.BYTE	_o,_k,_eol
_dictDD:		.BYTE	_o,_f,_eol
_dictDE:		.BYTE	_i,_d,_eol
_dictDF:		.BYTE	_h,_a,_eol
_dictE0:		.BYTE	_w,_e,_r,_e,__,_eol
_dictE1:		.BYTE	_A,_r,_m,_y,_eol
_dictE2:		.BYTE	_t,_o,__,_eol
_dictE3:		.BYTE	_ddt,__,_eol
_dictE4:		.BYTE	_dot,_dot,_dot,_eol
_dictE5:		.BYTE	_apo,_s,_eol
_dictE6:		.BYTE	_h,_a,_t,_eol
_dictE7:		.BYTE	_K,_e,_i,_eol
_dictE8:		.BYTE	_K,_i,_y,_o,_k,_o,_eol
_dictE9:		.BYTE	_T,_h,_e,_eol
_dictEA:		.BYTE	_K,_a,_i,_eol
_dictEB:		.BYTE	_I,_t,_apo,_s,_eol
_dictEC:		.BYTE	_w,_a,_s,_eol
_dictED:		.BYTE	_i,_n,_g,_eol
_dictEE:		.BYTE	_i,_r,_l,_eol
_dictEF:		.BYTE	_f,_o,_r,_eol
_dictF0:		.BYTE	_w,_i,_t,_h,_eol
_dictF1:		.BYTE	_a,_r,_e,_eol
_dictF2:		.BYTE	_i,_g,_h,_t,_eol
_dictF3:		.BYTE	_I,__,_eol
_dictF4:		.BYTE	_t,_h,_i,_s,_eol
_dictF5:		.BYTE	_B,_u,_t,_eol
_dictF6:		.BYTE	_o,_n,_eol,
_dictF7:		.BYTE	_M,_a,_n,_eol
_dictF8:		.BYTE	_h,_i,_s,_eol
_dictF9:		.BYTE	_a,_n,_d,_eol
_dictFA:		.BYTE	_y,_o,_u,_eol
;_dictFB:		; used as RAM offset
;_dictFC:										; spare
;_dictFD:										; spare