
		SECTION_START	FE

		MSG_START	_sceneE_msg_lib
		MSG_IDX	_scE_msg00
;		.WORD	0
		MSG_IDX	_scE_msg02
		MSG_IDX	_scE_msg03
		MSG_IDX	_scE_msg04
_scE_msg00:
		.BYTE	_Kaneda,_ddt_,_O,_u,_t,_t,_a,__the,__w,_a,_y,_exc,_eol
_scE_msg02:
		.BYTE	_F,_w,_s,_h,_exc,__,_C,_r,_u,_n,_c,_h,_exc,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_O,_w,_w,_w,_w,_dot,_eol
_scE_msg03:
		.BYTE	_W,_e_,_m,_ad,_e_,_it,__i,_n,_to_,_R,_oo,_m,__,_A,_dot,_ret
		.BYTE	_The,__,_F,_dot,_P,_dot,_H,_dot,__,_e,_x,_p,_l,_o,_d,_ed,_col,__,_and,__w,_e,_ret
		.BYTE	_were_,_t,_h,_r,_ow,_n,__,_on,_to_,_t,_he,__,_f,_l,_oo,_r,_dot,_eol
_scE_msg04:
		.BYTE	_I,_n,_s,_id,_e_,_were_,_a,__,_f,_e,_w,__w,_r,_in,_k,_l,_y,_ret
		.BYTE	_k,_id,_s,_col,__s,_o,_me,__,_Army,__,_j,_er,_k,_s,_col,__,_and,_dot_dot_dot,_ret
		.BYTE	_Tetsuo,_dot,_eol

		SECTION_END		FE
