
		SECTION_START	F16

		MSG_START	_scene16_msg_lib
		MSG_IDX	_sc16_msg00
		MSG_IDX	_sc16_msg01
		MSG_IDX	_sc16_msg0D
		MSG_IDX	_sc16_msg0E
		MSG_IDX	_sc16_msg0F
		MSG_IDX	_sc16_msg10
		MSG_IDX	_sc16_msg11
		MSG_IDX	_sc16_msg14
		MSG_IDX	_sc16_msg1D
		MSG_IDX	_sc16_msg1E
		MSG_IDX	_sc16_msg1F
		MSG_IDX	_sc16_msg20
		MSG_IDX	_sc16_msg21
		MSG_IDX	_sc16_msg22
		MSG_IDX	_sc16_msg24
		MSG_IDX	_sc16_msg25
		MSG_IDX	_sc16_msg26
		MSG_IDX	_sc16_msg27
		MSG_IDX	_sc16_msg28
		MSG_IDX	_sc16_msg29
		MSG_IDX	_sc16_msg2A
		MSG_IDX	_sc16_msg2B
		MSG_IDX	_sc16_msg7C					; scene 16 msg
		MSG_IDX	_sc16_msg7D					; scene 16 msg
		MSG_IDX	_sc16_msg7E					; scene 16 msg
		MSG_IDX	_sc16_msg9C					; scene 16 msg
		MSG_IDX	_sc16_msgC0					; scene 16 msg
		MSG_IDX	_sc16_msgC2					; scene 16 msg
		MSG_IDX	_sc16_msgC3					; scene 16 msg
		MSG_IDX	_sc16_msgC4					; scene 16 msg
		MSG_IDX	_sc16_msgCC					; scene 16 msg
		MSG_IDX	_sc16_msgCD					; scene 16 msg
		MSG_IDX	_sc16_msgCE					; scene 16 msg
		MSG_IDX	_sc16_msgCF					; scene 16 msg
		MSG_IDX	_sc16_msgD0					; scene 16 msg
		MSG_IDX	_sc16_msgD1					; scene 16 msg
		MSG_IDX	_sc16_msgD2					; scene 16 msg
		MSG_IDX	_sc16_msgD3					; scene 16 msg
		MSG_IDX	_sc16_msgD4					; scene 16 msg
		MSG_IDX	_sc16_msgD5					; scene 16 msg
		MSG_IDX	_sc16_msgD6					; scene 16 msg
		MSG_IDX	_sc16_msgD7					; scene 16 msg
		MSG_IDX	_sc16_msgD8					; scene 16 msg
		MSG_IDX	_sc16_msgD9					; scene 16 msg
		MSG_IDX	_sc16_msgDA					; scene 16 msg
		MSG_IDX	_sc16_msgDB					; scene 16 msg
		MSG_IDX	_sc16_msgDC					; scene 16 msg
		MSG_IDX	_sc16_msgDD					; scene 16 msg
		MSG_IDX	_sc16_msgDE					; scene 16 msg
		MSG_IDX	_sc16_msgDF					; scene 16 msg
		MSG_IDX	_sc16_msgE0					; scene 16 msg
		MSG_IDX	_sc16_msgE1					; scene 16 msg
		MSG_IDX	_sc16_msgE2					; scene 16 msg
		MSG_IDX	_sc16_msgE3					; scene 16 msg
		MSG_IDX	_sc16_msgE4					; scene 16 msg
		MSG_IDX	_sc16_msgE5					; scene 16 msg
		MSG_IDX	_sc16_msgE6					; scene 16 msg
		MSG_IDX	_sc16_msgE7					; scene 16 msg
		MSG_IDX	_sc16_msgE8					; scene 16 msg
		MSG_IDX	_sc16_msgE9					; scene 16 msg
		MSG_IDX	_sc16_msgEA					; scene 16 msg
		MSG_IDX	_sc16_msgEB					; scene 16 msg
		MSG_IDX	_sc16_msgEC					; scene 16 msg
		MSG_IDX	_sc16_msgED					; scene 16 msg
		MSG_IDX	_sc16_msgEE					; scene 16 msg
		MSG_IDX	_sc16_msgEF					; scene 16 msg
_sc16_msg00:
		.BYTE	_I,_n,__,_f,_r,_on,_t_,_of,__,_m,_y,__,_e,_y,_e,_s_,_was,__the,_ret
		.BYTE	_s,_h,_r,_u,_n,_k,_en,__,_b,_a,_ll,__of,__,_l,_ight,_dot,_eol
_sc16_msg01:
		.BYTE	_I_,_t,_u,_r,_n,_ed,__,_around,__,_and,__,_f,_ou,_n,_d_,_Kei,_dot,_eol
_sc16_msg0D:
		.BYTE	_Kiyoko,_ddt_,_an0,_Y,_e,_s,_dot_dot_dot,__,_it,__i,_s_,_w,_hat,__w,_e,_ret
		.BYTE	_ha,_ve,__,_for,_e,_se,_en,_dot_dot_dot,_ret
		.BYTE	_I,_n,__,_or,_d,_er,__,_to_,_b,_r,_ing,__,_Tetsuo,_dot_dot_dot,_aof,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_B,_r,_ing,__,_h,_i,_m,_dot_dot_dot,__w,_her,_e,_que,_eol
_sc16_msg0E:
		.BYTE	_Takashi,_ddt_,_Tetsuo,__,_was,__,_be,_y,_on,_d,_ret
		.BYTE	_he,_l,_p,_dot_dot_dot,__,_O,_u,_r,__,_he,_l,_p,_dot_dot_dot,__,_and,__,_e,_ve,_n,_ret
		.BYTE	_Akira,_apo_s,_dot_dot_dot,_ret
		.BYTE	_ret
		.BYTE	_Masaru,_ddt_,_H,_e_,_was,__,_j,_u,_st,__t,_oo,__,_m,_u,_c,_h,_ret
		.BYTE	_for,__,_u,_s,__a,_s_,_w,_e_,_are,__,_n,_ow,_dot,_eol
_sc16_msg0F:
		.BYTE	_Kiyoko,_ddt_,_an0,_But,__s,_o,_m,_ed,_a,_y,__,_e,_ve,_n,__w,_e,_dot_dot_dot,_aof,_ret
		.BYTE	_ret
		.BYTE	_Masaru,_ddt_,_It_apo_s,__,_st,_i,_ll,__,_j,_u,_st,_ret
		.BYTE	_be,_g,_in,_n,_ing,_dot_dot_dot,_eol
_sc16_msg10:
		.BYTE	_Kiyoko,_ddt_,_an0,_Y,_ou,_r,__,_f,_r,_i,_en,_d,_dot_dot_dot,_aof,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_Y,_ou,__,_me,_an,__,_Kei,_que,_eol
_sc16_msg11:
		.BYTE	_Kei,_ddt_,_Kaneda,_exc,_ret
		.BYTE	_ret
		.BYTE	_I_,_c,_ou,_l,_d_,_he,_ar,__,_Kei,_apo_s,__,_v,_o,_i,_c,_e,_dot_dot_dot,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_an0,_Kei,_dot_dot_dot,_aof,_eol
_sc16_msg14:
		.BYTE	_Masaru,_ddt_,_Kiyoko,_col,__,_Takashi,_dot,_ret
		.BYTE	_ret
		.BYTE	_Takashi,_ddt_,_Masaru,_col,__,_Kiyoko,_dot,_ret
		.BYTE	_ret
		.BYTE	_Kiyoko,_ddt_,_Takashi,_col,__,_Masaru,_dot,_eol
_sc16_msg1D:
		.BYTE	_The,__s,_h,_r,_u,_n,_k,_en,__,_b,_a,_ll,__of,__,_l,_ight,_ret
		.BYTE	_a,_p,_p,_e,_are,_d_,_to_,_f,_ad,_e_,_a,_s_,_it,__,_f,_le,_w,_ret
		.BYTE	_a,_w,_a,_y,_dot_dot_dot,_eol
_sc16_msg1E:
		.BYTE	_W,_h,_en,__,_I_,_c,_a,_me,__t,_o,_col,__,_I_,_was,__,_on,__t,_o,_p,_ret
		.BYTE	_of,__the,__,_p,_i,_le,__of,__,_r,_u,_b,_b,_le,__i,_n,_ret
		.BYTE	_t,_he,__,_st,_ad,_i,_u,_m,_dot,_eol
_sc16_msg1F:
		.BYTE	_I_,_g,_r,_a,_b,_b,_ed,__the,__,_f,_ad,_ing,__,_b,_a,_ll,__of,_ret
		.BYTE	_l,_ight,__,_with,_ou,_t,__t,_h,_in,_k,_ing,_dot,_eol
_sc16_msg20:
		.BYTE	_Kaneda,_ddt_,_Tetsuo,_dot_dot_dot,_eol
_sc16_msg21:
		.BYTE	_Kei,_ddt_,_Kaneda,_dot_dot_dot,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_T,_h,_an,_k,__,_you,_dot_dot_dot,_ret
		.BYTE	_for,__,_c,_a,_ll,_ing,__,_m,_y,__,_n,_a,_me,_dot,_ret
		.BYTE	_I_,_he,_ar,_d_,_you,_dot_dot_dot,_eol
_sc16_msg22:
		.BYTE	_Kei,_ddt_,_Tetsuo,_dot_dot_dot,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_H,_e,_apo_s,__g,_on,_e,_dot_dot_dot,_ret
		.BYTE	_a,_l,_on,_g,__,_with,__t,_h,_o,_se,__t,_h,_re,_e,_dot_dot_dot,_ret
		.BYTE	_and,__,_Akira,_dot_dot_dot,_ret
		.BYTE	_ret
		.BYTE	_Kei,_ddt_,_Kaneda,_dot_dot_dot,__,_e,_ar,_l,_i,_er,_col,__,_you,_dot_dot_dot,_eol
_sc16_msg24:
		.BYTE	_The,__,_c,_l,_ou,_d,_s_,_were_,_was,_h,_ed,__a,_w,_a,_y,_col,_ret
		.BYTE	_and,__the,__s,_u,_n,__s,_h,_on,_e,_dot,_ret
		.BYTE	_ret
		.BYTE	_W,_e_,_c,_ou,_l,_d_,_on,_l,_y,__g,_a,_z,_e_,_at,__the,_ret
		.BYTE	_l,_ight,_dot_dot_dot,_eol
_sc16_msg25:
		.BYTE	_The,_n,_col,__w,_e_,_g,_o,_t_,_on,__the,__,_b,_i,_k,_e_,_and,_ret
		.BYTE	_he,_ad,_ed,__,_for,__,_N,_e,_o,_str,_T,_ok,_y,_o,_dot,_eol
_sc16_msg26:
		.BYTE	_E,_ve,_n,__the,__,_b,_ro,_k,_en,__,_building,_s,_ret
		.BYTE	_of,__,_N,_e,_o,_str,_T,_ok,_y,_o,__,_f,_e,_l,_t,__a,__,_f,_u,_ll,_ret
		.BYTE	_s,_h,_ow,_er,_ing,__of,__s,_u,_n,_l,_ight,_dot,_eol
_sc16_msg27:
		.BYTE	_dot_dot_dot,_L,_ight,__s,_p,_r,_u,_n,_g,__,_f,_ro,_m,__the,__w,_h,_it,_e,_ret
		.BYTE	_e,_m,_p,_t,_in,_e,_s,_s,_dot,__,_G,_r,_ad,_u,_a,_ll,_y,_col,__a,_t,_o,_m,_s,_ret
		.BYTE	_were_,_b,_or,_n,_dot,__,_The,__a,_t,_o,_m,_s,_dot_dot_dot,_eol
_sc16_msg28:
		.BYTE	_G,_re,_w,_col,__,_and,__,_be,_c,_a,_me,__g,_a,_se,_ou,_s,_ret
		.BYTE	_for,_m,_s,_dot,__,_S,_o,_on,_col,__s,_p,_a,_c,_e_,_a,_p,_p,_e,_are,_d,_dot_dot_dot,_ret
		.BYTE	_and,__g,_a,_l,_a,_x,_i,_e,_s,_dot_dot_dot,_eol
_sc16_msg29:
		.BYTE	_P,_l,_an,_e,_t,_s_,_and,__,_st,_ar,_s_,_were_,_b,_or,_n,_dot_dot_dot,_eol
_sc16_msg2A:
		.BYTE	_Tetsuo,_ddt_,_I_,_a,_m,_dot_dot_dot,__,_Tetsuo,_dot_dot_dot,_eol
_sc16_msg2B:
		.BYTE	_Kaneda,_ddt_,_I_,_w,_on,_d,_er,_dot_dot_dot,_ret
		.BYTE	_A,_h,_exc,__,_O,_f,__,_c,_ou,_r,_se,_exc,_eol
_sc16_msg7C:
		.BYTE	_The,_y,__,_were_,_a,_ll,__i,_n,__the,__,_O,_l,_d_,_T,_ow,_n,_col,_ret
		.BYTE	_st,_ar,_ing,__a,_t,__the,__,_e,_x,_p,_and,_ing,_ret
		.BYTE	_b,_r,_ight,__,_l,_ight,_dot,_eol
_sc16_msg7D:
		.BYTE	_N,_e,_o,_str,_T,_ok,_y,_o,__,_was,__,_m,_o,_v,_ing,__,_m,_o,_re,__,_and,_ret
		.BYTE	_m,_o,_re,__t,_ow,_ar,_d,_s,__the,__w,_or,_st,__of,_ret
		.BYTE	_e,_ve,_r,_y,_t,_h,_ing,_dot,_eol
_sc16_msg7E:
		.BYTE	_But,__,_it,__,_was,__,_Kaneda,__t,_hat,__,_f,_in,_a,_ll,_y,_ret
		.BYTE	_a,_w,_ok,_e_,_Akira,_dot,_eol
_sc16_msg9C:
		.BYTE	_T,_h,_r,_ou,_g,_h,__,_Kaneda,_apo_s,__w,_or,_k,_col,__,_Akira,_apo_s,_ret
		.BYTE	_re,_s,_u,_r,_re,_c,_t,_i,_on,__,_was,__,_p,_re,_ve,_n,_t,_ed,_dot,_ret
		.BYTE	_N,_e,_o,_str,_T,_ok,_y,_o,__,_be,_c,_a,_me,__,_p,_e,_a,_c,_e,_f,_u,_l,__,_on,_c,_e,_ret
		.BYTE	_m,_o,_re,_dot_dot_dot,_eol
_sc16_msgC0:
		.BYTE	_The,__,_l,_ight,__a,_b,_s,_or,_b,_ed,__the,__,_r,_u,_b,_b,_le,_ret
		.BYTE	_and,__s,_p,_re,_a,_d_,_ou,_t,_dot,_ret
		.BYTE	_ret
		.BYTE	_Tetsuo,_ddt_,_T,_his,__,_l,_ight,_dot_dot_dot,_ret
		.BYTE	_w,_hat,__i,_s_,_it,_que,_ret
		.BYTE	_ret
		.BYTE	_The,__,_are,_a,__i,_n,__,_f,_r,_on,_t_,_of,__,_me,__,_be,_c,_a,_me,_ret
		.BYTE	_a,__,_b,_r,_ight,__w,_h,_it,_e,_dot,_eol
_sc16_msgC2:
		.BYTE	_A,_f,_t,_er,__,_h,_it,_t,_ing,__the,__s,_a,_m,_p,_le,__,_c,_a,_se,_col,_ret
		.BYTE	_t,_he,__,_laser,_apo_s,__,_en,_er,_g,_y,__,_re,_s,_on,_at,_ed,_ret
		.BYTE	_with,__,_Tetsuo,_apo_s,__,_p,_ow,_er,_col,_ret
		.BYTE	_re,_s,_u,_r,_re,_c,_t,_ing,__,_Akira,_dot,_eol
_sc16_msgC3:
		.BYTE	_Akira,_apo_s,__,_l,_ight,__,_e,_x,_p,_and,_ed,__,_m,_o,_re,_ret
		.BYTE	_and,__,_m,_o,_re,_col,__,_en,_ve,_l,_o,_p,_ing,__,_b,_o,_t,_h,_ret
		.BYTE	_Akira,__,_and,__,_Kaneda,_dot,_ret
		.BYTE	_ret
		.BYTE	_Tetsuo,_ddt_,_A,_g,_h,_col,__,_A,_dot_dot_dot,__,_Akira,_dot_dot_dot,_eol
_sc16_msgC4:
		.BYTE	_N,_e,_o,_str,_T,_ok,_y,_o,__g,_r,_ad,_u,_a,_ll,_y,__,_re,_t,_u,_r,_n,_ed,_ret
		.BYTE	_to_,_s,_i,_le,_n,_c,_e,_dot,_eol
_sc16_msgCC:
		.BYTE	_W,_it,_h,__the,__,_laser,_apo_s,__,_en,_er,_g,_y,_col,__the,_ret
		.BYTE	_e,_x,_p,_and,_ing,__,_Tetsuo,__,_e,_x,_t,_en,_d,_ed,__t,_o,_ret
		.BYTE	_en,_ve,_l,_o,_p,__the,__,_3,__of,__the,_m,__,_and,__,_e,_ve,_n,_ret
		.BYTE	_Akira,_apo_s,__s,_a,_m,_p,_le,__,_c,_a,_se,_dot,_eol
_sc16_msgCD:
		.BYTE	_Kiyoko,_ddt_,_Tetsuo,_dot_dot_dot,__,_A,_h,_exc,_ret
		.BYTE	_ret
		.BYTE	_Takashi,_ddt_,_It_apo_s,__,_n,_o,__,_u,_se,_exc,_ret
		.BYTE	_ret
		.BYTE	_Masaru,_ddt_,_A,_g,_h,_exc,__,_Akira,_dot_dot_dot,_eol
_sc16_msgCE:
		.BYTE	_A,_f,_t,_er,__,_d,_e,_st,_ro,_y,_ing,__the,__,_st,_ad,_i,_u,_m,_col,_ret
		.BYTE	_Tetsuo,__,_e,_x,_p,_and,_ed,__,_and,__,_c,_on,_s,_u,_m,_ed,_ret
		.BYTE	_t,_he,__,_en,_t,_i,_re,_t,_y,__of,__the,__,_O,_l,_d_,_T,_ow,_n,_dot,_eol
_sc16_msgCF:
		.BYTE	_W,_it,_h,__the,__,_c,_o,_ll,_a,_p,_se,__of,__the,__,_O,_l,_d,_ret
		.BYTE	_T,_ow,_n,_col,__the,__,_o,_c,_e,_an,__,_it,_se,_l,_f,__,_p,_ou,_r,_ed,_ret
		.BYTE	_in,_to_,_N,_e,_o,_str,_T,_ok,_y,_o,_dot,_eol
_sc16_msgD0:
		.BYTE	_N,_e,_o,_str,_T,_ok,_y,_o,__,_re,_t,_u,_r,_n,_ed,__,_to_,_s,_i,_le,_n,_c,_e,_dot,_ret
		.BYTE	_H,_a,_v,_ing,__,_d,_e,_st,_ro,_y,_ed,__the,__,_O,_l,_d_,_T,_ow,_n,_col,_ret
		.BYTE	_Tetsuo,__,_was,__,_c,_r,_y,_ing,_dot,_eol
_sc16_msgD1:
		.BYTE	_The,__,_k,_id,_s,__t,_e,_le,_p,_or,_t,_ed,__,_me,__,_ou,_t_,_of,_ret
		.BYTE	_t,_he,__,_st,_ad,_i,_u,_m,_dot,_eol
_sc16_msgD2:
		.BYTE	_W,_h,_en,__w,_e_,_m,_ad,_e_,_it,__,_b,_a,_c,_k,__,_to_,_t,_he,_ret
		.BYTE	_c,_r,_u,_m,_b,_l,_ing,__,_st,_ad,_i,_u,_m,_col,__w,_e_,_me,_t_,_Kei,_ret
		.BYTE	_and,__,_Kai,_dot,_eol
_sc16_msgD3:
		.BYTE	_dot_dot_dot,_W,_hat,__w,_ou,_l,_d_,_ha,_p,_p,_en,__i,_f,__the,_ret
		.BYTE	_t,_w,_o,__,_p,_ow,_er,_s_,_c,_o,_ll,_id,_ed,_que,_eol
_sc16_msgD4:
		.BYTE	_Akira,__,_and,__,_Tetsuo,__,_re,_g,_en,_er,_at,_ed,_ret
		.BYTE	_in,_s,_id,_e,__the,__,_r,_u,_b,_b,_le,_dot,_ret
		.BYTE	_ret
		.BYTE	_Tetsuo,_ddt_,_S,_o,__w,_e_,_f,_in,_a,_ll,_y,__,_me,_e,_t,_dot_dot_dot,_ret
		.BYTE	_Akira,_dot_dot_dot,_eol
_sc16_msgD5:
		.BYTE	_W,_it,_h,__the,__,_d,_e,_st,_r,_u,_c,_t,_i,_on,__of,_ret
		.BYTE	_N,_e,_o,_str,_T,_ok,_y,_o,_col,__the,__,_n,_e,_w,__,_st,_or,_y,__of,_ret
		.BYTE	_Akira,__,_ha,_d_,_be,_g,_u,_n,_dot_dot_dot,_ret
		.BYTE	_ret
		.BYTE	_The,__,_G,_re,_a,_t_,_T,_ok,_y,_o,__,_E,_m,_p,_i,_re,_dot_dot_dot,_ret
		.BYTE	_ret
		.BYTE	_A,_ll,__,_ha,_i,_l,__,_E,_m,_p,_er,_or,__,_Akira,_dot_dot_dot,_eol
_sc16_msgD6:
		.BYTE	_Kaneda,__,_st,_r,_u,_g,_g,_l,_ed,_col,__,_b,_u,_t_,_he,__,_was,_ret
		.BYTE	_f,_in,_a,_ll,_y,__,_c,_on,_s,_u,_m,_ed,__,_b,_y,__the,__,_l,_ight,_dot,_eol
_sc16_msgD7:
		.BYTE	_dot_dot_dot,_Kaneda,__,_was,__,_en,_ve,_l,_o,_p,_ed,__,_b,_y,_ret
		.BYTE	_Akira,__,_and,__,_his,__,_ve,_r,_y,__,_be,_ing,_ret
		.BYTE	_a,_n,_n,_i,_h,_i,_l,_at,_ed,_dot,_eol
_sc16_msgD8:
		.BYTE	_N,_e,_o,_str,_T,_ok,_y,_o,__,_re,_t,_u,_r,_n,_ed,__,_to_,_s,_i,_le,_n,_c,_e,_dot,_ret
		.BYTE	_E,_ve,_r,_y,_t,_h,_ing,__,_was,__,_c,_o,_m,_p,_le,_t,_e,_l,_y,_ret
		.BYTE	_d,_e,_st,_ro,_y,_ed,_dot,_eol
_sc16_msgD9:
		.BYTE	_Kai,__,_and,__,_Kei,__,_were_,_at,__the,_ret
		.BYTE	_h,_i,_g,_h,_w,_a,_y,_apo_s,__,_tollbooth,_dot,_eol
_sc16_msgDA:
		.BYTE	_Kai,_ddt_,_an1,_T,_his,__i,_s_,_b,_ad,_dot_dot_dot,__,_W,_e,_apo,_ve,_ret
		.BYTE	_g,_o,_t,_t,_a,__g,_e,_t_,_ou,_t,_t,_a,__,_her,_e,_exc,_aof,_ret
		.BYTE	_ret
		.BYTE	_Kei,_ddt_,_an0,_Kaneda,_dot_dot_dot,__,_Kaneda,_a,_a,_exc,_aof,_eol
_sc16_msgDB:
		.BYTE	_The,__,_l,_ight,__g,_a,_ve,__of,_f,__a,__g,_ro,_an,_col,_ret
		.BYTE	_and,__,_be,_g,_an,__,_to_,_er,_o,_d,_e,__the,__,_O,_l,_d,_ret
		.BYTE	_T,_ow,_n,_dot,_eol
_sc16_msgDC:
		.BYTE	_The,__,_building,_s_,_were_,_en,_ve,_l,_o,_p,_ed,_col,_ret
		.BYTE	_and,__,_r,_u,_b,_b,_le,_col,__,_b,_i,_ll,_b,_o,_ar,_d,_s,_col,__,_and,_ret
		.BYTE	_Army,__t,_an,_k,_s,__a,_l,_i,_k,_e_,_were_,_a,_b,_s,_or,_b,_ed,_ret
		.BYTE	_and,__,_v,_a,_p,_or,_i,_z,_ed,_dot,_ret
		.BYTE	_ret
		.BYTE	_The,__,_O,_l,_d_,_T,_ow,_n,__,_ha,_d_,_be,_en,__,_m,_o,_st,_l,_y,_ret
		.BYTE	_d,_e,_st,_ro,_y,_ed,_dot,_eol
_sc16_msgDD:
		.BYTE	_I_,_d,_r,_i,_f,_t,_ed,__a,_b,_ou,_t,__i,_n,__the,__,_l,_ight,_dot,_ret
		.BYTE	_ret
		.BYTE	_dot_dot_dot,_M,_y,__,_l,_i,_f,_e_,_be,_g,_an,__,_to_,_f,_l,_a,_s,_h,_ret
		.BYTE	_before,__,_m,_y,__,_e,_y,_e,_s,_dot,_eol
_sc16_msgDE:
		.BYTE	_Kaneda,_ddt_,_Y,_ou,__,_se,_e,_col,__,_you,_apo,_re,__,_j,_u,_st,_ret
		.BYTE	_n,_o,_t_,_d,_i,_g,_g,_ing,__i,_n,__,_en,_ou,_g,_h,_dot_dot_dot,_ret
		.BYTE	_ret
		.BYTE	_Yamagata,_ddt_,_Y,_ou,__t,_a,_k,_e,__the,__,_c,_or,_n,_er,_ret
		.BYTE	_l,_i,_k,_e_,_you,__w,_an,_n,_a,__,_d,_i,_e,_dot,_ret
		.BYTE	_H,_e,_re,_col,__w,_at,_c,_h,_dot_dot_dot,_eol
_sc16_msgDF:
		.BYTE	_Kai,_ddt_,_W,_h,_ad,_d,_a,_y,_a,__,_me,_an,_que,_ret
		.BYTE	_ret
		.BYTE	_Yamagata,_ddt_,_It_apo_s,__,_c,_or,_n,_er,_ing,_dot,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_H,_a,_ha,_ha,_dot_dot_dot,_ret
		.BYTE	_H,_e,_y,_col,__,_Tetsuo,_dot_dot_dot,_eol
_sc16_msgE0:
		.BYTE	_O,_h,__,_l,_oo,_k,_col,__,_he,_apo_s,__,_b,_a,_c,_k,_dot,_ret
		.BYTE	_ret
		.BYTE	__,__,__,__,_I,_s_,_he,__a,__t,_r,_an,_s,_f,_er,__,_st,_u,_d,_en,_t,_que,_ret
		.BYTE	_ret
		.BYTE	_H,_e_,_was,__,_j,_u,_st,__,_c,_a,_st,__a,_s,_id,_e,_dot_dot_dot,_ret
		.BYTE	_ret
		.BYTE	__,_H,_e_,_l,_oo,_k,_s_,_l,_i,_k,_e_,_he,_apo_s,__,_be,_en,_ret
		.BYTE	__t,_h,_r,_ou,_g,_h,__a,__,_l,_o,_t,_dot,_eol
_sc16_msgE1:
		.BYTE	_Kaneda,_ddt_,_A,_re,__,_you,_dot_dot_dot,_ret
		.BYTE	_d,_re,_a,_m,_ing,_col,__,_Tetsuo,_que,_eol
_sc16_msgE2:
		.BYTE	_Tetsuo,_ddt_,_str,_s,_n,_i,_f,_f,_le,_str,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_The,__,_n,_e,_w,__g,_u,_y,_s_,_around,_ret
		.BYTE	_her,_e_,_are,__a,_l,_w,_a,_y,_s,__g,_e,_t,_t,_ing,__,_be,_at,_ret
		.BYTE	_u,_p,_dot,__,_I,_t_,_ha,_p,_p,_en,_ed,__a,_g,_a,_in,__t,_o,_d,_a,_y,_dot,_ret
		.BYTE	_I_,_g,_o,_t_,_h,_it,_col,__t,_oo,_dot_dot_dot,__,_b,_u,_t,__t,_hat,_ret
		.BYTE	_o,_t,_her,__g,_u,_y,__,_was,__,_re,_a,_ll,_y,__w,_e,_a,_k,_dot,_eol
_sc16_msgE3:
		.BYTE	_Tetsuo,_ddt_,_I_apo,_m,_dot_dot_dot,__,_Tetsuo,_dot_dot_dot,_ret
		.BYTE	_Tetsuo,__,_S,_h,_i,_m,_a,_dot_dot_dot,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_H,_e,_h,_col,__,_you,__,_k,_n,_ow,__w,_hat,_que,_ret
		.BYTE	_I_apo,_m,__,_n,_e,_w,__,_her,_e_,_t,_oo,_dot,_ret
		.BYTE	_M,_y,__,_n,_a,_me,__i,_s,_dot_dot_dot,_eol
_sc16_msgE4:
		.BYTE	_S,_u,_d,_d,_en,_l,_y,_col,__,_I_,_s,_a,_w,__t,_h,_o,_se,__,_k,_id,_s,_dot,_ret
		.BYTE	_The,_y,__,_were_,_p,_l,_a,_y,_ing,__i,_n,__a,__,_ro,_o,_m,_ret
		.BYTE	_t,_hat,__,_l,_oo,_k,_ed,__,_l,_i,_k,_e_,_a,__,_l,_a,_b,_or,_at,_or,_y,_dot,_ret
		.BYTE	_A,_c,_ro,_s,_s_,_f,_ro,_m,__the,__,_k,_id,_s_,_was,_ret
		.BYTE	_a,_n,_o,_t,_her,__,_on,_e_,_I_,_h,_ad,_n,_apo,_t_,_se,_en,_ret
		.BYTE	_before,_dot,_ret
		.BYTE	_H,_e_,_was,__s,_m,_i,_l,_ing,_dot,_eol
_sc16_msgE5:
		.BYTE	_Kaneda,_ddt_,_an0,_S,_o,__,_this,__i,_s_,_Akira,_dot_dot_dot,_que,_aof,_eol
_sc16_msgE6:
		.BYTE	_A,_n,__,_en,_or,_m,_ou,_s_,_b,_a,_ll,__of,__,_l,_ight,_ret
		.BYTE	_a,_p,_p,_e,_are,_d_,_o,_ve,_r,__,_N,_e,_o,_str,_T,_ok,_y,_o,_dot,__,_S,_o,_on,_col,_ret
		.BYTE	_t,_he,__t,_o,_p,__of,__the,__,_b,_a,_ll,__g,_re,_w,__,_d,_ar,_k,_dot,_ret
		.BYTE	_I,_t_,_re,_se,_m,_b,_l,_ed,__a,__,_b,_l,_a,_c,_k,__,_h,_o,_le,_dot,_eol
_sc16_msgE7:
		.BYTE	_The,__,_are,_a,__,_around,__,_me,__,_be,_g,_an,__t,_o,_ret
		.BYTE	_d,_i,_st,_or,_t_,_and,__w,_ar,_p,_dot,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_an0,_A,_g,_h,_dot_dot_dot,__,_Kei,_exc,_aof,_eol
_sc16_msgE8:
		.BYTE	_The,__,_b,_a,_ll,__of,__,_l,_ight,__,_was,_ret
		.BYTE	_c,_o,_m,_p,_le,_t,_e,_l,_y,__s,_u,_r,_r,_ou,_n,_d,_ed,__,_b,_y,__the,_ret
		.BYTE	_d,_ar,_k,_n,_e,_s,_s,_dot,__,_The,__,_c,_l,_ou,_d_,_ad,_v,_an,_c,_ing,_ret
		.BYTE	_t,_ow,_ar,_d,__the,__,_c,_en,_t,_er,__,_e,_x,_p,_and,_ed,_dot,_eol
_sc16_msgE9:
		.BYTE	_The,__s,_p,_her,_e_,_of,__,_d,_ar,_k,_n,_e,_s,_s_,_c,_o,_ve,_r,_ed,_ret
		.BYTE	_N,_e,_o,_str,_T,_ok,_y,_o,_apo_s,__,_building,_s_,_and,_ret
		.BYTE	_d,_e,_st,_ro,_y,_ed,__the,_m,_dot,__,_A,__g,_i,_an,_t_,_c,_r,_at,_er,_ret
		.BYTE	_a,_p,_p,_e,_are,_d_,_in,__the,__,_are,_a,__t,_hat,__,_h,_ad,_ret
		.BYTE	_on,_c,_e_,_be,_en,__,_N,_e,_o,_str,_T,_ok,_y,_o,_apo_s,__,_c,_en,_t,_er,_dot,_eol
_sc16_msgEA:
		.BYTE	_The,__s,_p,_her,_e_,_of,__,_d,_ar,_k,_n,_e,_s,_s,__g,_re,_w,_ret
		.BYTE	_o,_ve,_r,__,_N,_e,_o,_str,_T,_ok,_y,_o,_col,__,_and,__,_e,_x,_p,_and,_ed,_ret
		.BYTE	_u,_p,__,_to_,_t,_he,__,_o,_c,_e,_an,_dot,_eol
_sc16_msgEB:
		.BYTE	_N,_e,_o,_str,_T,_ok,_y,_o,_apo_s,__,_building,_s_,_w,_e,_re,_ret
		.BYTE	_f,_l,_oo,_d,_ed,__,_b,_y,__the,__,_se,_a,__w,_at,_er,_dot,_eol
_sc16_msgEC:
		.BYTE	_The,__,_building,_s_,_f,_e,_ll,__,_on,_e_,_b,_y,__,_on,_e,_ret
		.BYTE	_a,_s,__the,__w,_at,_er,__,_re,_a,_c,_h,_ed,__the,_m,_dot,_eol
_sc16_msgED:
		.BYTE	_G,_r,_ad,_u,_a,_ll,_y,_col,__,_m,_or,_n,_ing,__,_c,_a,_me,_col,_ret
		.BYTE	_and,__i,_n,__the,__,_m,_id,_d,_le,__of,__the,_ret
		.BYTE	_g,_i,_an,_t_,_c,_l,_ou,_d,_col,__a,__,_l,_ight,__s,_h,_on,_e,_ret
		.BYTE	_t,_h,_r,_ou,_g,_h,_dot,__,_The,__w,_at,_er,__,_be,_g,_an,_ret
		.BYTE	_to_,_re,_c,_ed,_e,_dot,_eol
_sc16_msgEE:
		.BYTE	_N,_e,_o,_str,_T,_ok,_y,_o,_col,__w,_h,_i,_c,_h,__w,_e,_ret
		.BYTE	_c,_ou,_l,_d_,_se,_e_,_f,_ro,_m,__the,__,_st,_ad,_i,_u,_m,_col,_ret
		.BYTE	_g,_re,_w,__,_st,_i,_ll,_dot_dot_dot,_eol
_sc16_msgEF:
		.BYTE	_Kai,_ddt_,_an0,_Kaneda,_exc,__,_You_apo_re,__a,_l,_i,_ve,_exc,_ret
		.BYTE	_J,_e,_e,_z,_col,__,_I_,_t,_h,_ou,_g,_h,_t_,_you,_apo,_d_,_be,__a,_ret
		.BYTE	_g,_on,_er,_dot_dot_dot,__,_H,_u,_h,_col,__w,_her,_e,_apo_s,__,_Tetsuo,_que,_ret
		.BYTE	_D,_i,_d_,_he,__,_d,_i,_e,_que,_aof,_eol

		SECTION_END		F16
