
		SECTION_START	F7

		MSG_START	_scene7_msg_lib
		MSG_IDX	_sc7_msg04
		MSG_IDX	_sc7_msg05
		MSG_IDX	_sc7_msg06
		MSG_IDX	_sc7_msg07
		MSG_IDX	_sc7_msg08
		MSG_IDX	_sc7_msg09
		MSG_IDX	_sc7_msg0A
		MSG_IDX	_sc7_msg0B
		MSG_IDX	_sc7_msg0C
		MSG_IDX	_sc7_msg0D
		MSG_IDX	_sc7_msg0E
		MSG_IDX	_sc7_msg0F
		MSG_IDX	_sc7_msg10
		MSG_IDX	_sc7_msg11
		MSG_IDX	_sc7_msg12
		MSG_IDX	_sc7_msg13
		MSG_IDX	_sc7_msg14
		MSG_IDX	_sc7_msg15
		MSG_IDX	_sc7_msg16
		MSG_IDX	_sc7_msg17
		MSG_IDX	_sc7_msg18
		MSG_IDX	_sc7_msg19
		MSG_IDX	_sc7_msg1A
		MSG_IDX	_sc7_msg1B
		MSG_IDX	_sc7_msg1C
		MSG_IDX	_sc7_msg1D
		MSG_IDX	_sc7_msg1E
		MSG_IDX	_sc7_msg1F
		MSG_IDX	_sc7_msg20
		MSG_IDX	_sc7_msg21
		MSG_IDX	_sc7_msg22
		MSG_IDX	_sc7_msg23
		MSG_IDX	_sc7_msg24
		MSG_IDX	_sc7_msg25
		MSG_IDX	_sc7_msg26
		MSG_IDX	_sc7_msg27
		MSG_IDX	_sc7_msg28
		MSG_IDX	_sc7_msg29
		MSG_IDX	_sc7_msg2A
		MSG_IDX	_sc7_msgBB					; scene 7 msg
		MSG_IDX	_sc7_msgBC					; scene 7 msg
		MSG_IDX	_sc7_msgBD					; scene 7 msg
		MSG_IDX	_sc7_msgBE					; scene 7 msg
_sc7_msg04:
		.BYTE	_Yamagata,_ddt_,_an2,_Tetsuo,__,_m,_u,_st,_apo,_ve,_ret
		.BYTE	_b,_an,_g,_ed,__,_his,__,_he,_a,_d_,_p,_re,_t,_t,_y,__,_h,_ar,_d_,_in,_ret
		.BYTE	_t,_hat,__a,_c,_c,_id,_en,_t,_dot,__,_H,_e,_apo_s,__,_j,_u,_st,__,_n,_o,_t,_ret
		.BYTE	_t,_he,__s,_a,_me,_dot,_aof,_eol
_sc7_msg05:
		.BYTE	_Yamagata,_ddt_,_an2,_T,_h,_o,_se,__,_Army,__g,_o,_on,_s,_ret
		.BYTE	_g,_o,_t,_t,_a,__,_be,__,_h,_id,_ing,__s,_o,_me,_t,_h,_ing,_dot,_aof,_eol
_sc7_msg06:
		.BYTE	_Yamagata,_ddt_,_an2,_T,_hat,__,_b,_r,_at,_apo_s,__g,_o,_t,_ret
		.BYTE	_s,_o,_me,_t,_h,_ing,__,_to_,_d,_o,__,_with,__the,__,_Army,_dot,_aof,_eol
_sc7_msg07:
		.BYTE	_Yamagata,_ddt_,_an2,_The,__,_Army,_apo_s,__t,_re,_at,_ing,_ret
		.BYTE	_Tetsuo,__,_l,_i,_k,_e,__the,_y,__t,_re,_at,__t,_hat,_ret
		.BYTE	_k,_id,_dot,_aof,_eol
_sc7_msg08:
		.BYTE	_Yamagata,_ddt_,_an2,_W,_a,_s,__the,_re,__a,__g,_u,_y,__,_l,_i,_k,_e,_ret
		.BYTE	_t,_hat,__a,_t,__s,_c,_h,_oo,_l,_que,_aof,_eol
_sc7_msg09:
		.BYTE	_Kai,_ddt_,_an1,_I_,_be,_t_,_he,__s,_a,_w,__a,_n,__,_Army,_ret
		.BYTE	_se,_c,_re,_t_,_or,__s,_o,_me,_t,_h,_ing,_dot,_aof,_eol
_sc7_msg0A:
		.BYTE	_Kai,_ddt_,_an1,_D,_id,_n,_apo,_t,__the,_y,__,_c,_a,_ll,__,_Tetsuo,_ret
		.BYTE	_a,_n,__,_bra,_e,_xperimental,__s,_u,_b,_j,_e,_c,_t,_bra,__,_or,_ret
		.BYTE	_s,_o,_me,_t,_h,_ing,_que,_aof,_eol
_sc7_msg0B:
		.BYTE	_Kai,_ddt_,_an1,_M,_a,_y,_be,__,_Tetsuo,_apo_s,__,_be,_en,_ret
		.BYTE	_t,_u,_r,_n,_ed,__i,_n,_to_,_s,_o,_me,__s,_or,_t_,_of,__,_Army,_ret
		.BYTE	_e,_x,_p,_er,_i,_me,_n,_t,_dot,_aof,_eol
_sc7_msg0C:
		.BYTE	_Kai,_ddt_,_an1,_I_,_d,_on,_apo,_t_,_re,_a,_ll,_y,__g,_e,_t_,_it,_dot,_aof,_eol
_sc7_msg0D:
		.BYTE	_Kai,_ddt_,_an1,_H,_u,_h,_que,__,_W,_h,_o,_apo_s,__t,_hat,_que,_aof,_eol
_sc7_msg0E:
		.BYTE	_Groupie,_ddt_,_an0,_I_,_d,_u,_n,_n,_o,_dot,_aof,_eol
_sc7_msg0F:
		.BYTE	_Groupie,_ddt_,_an0,_L,_e,_t,_apo_s,__,_j,_u,_st,__,_st,_o,_p,_ret
		.BYTE	_t,_h,_in,_k,_ing,__a,_b,_ou,_t_,_it,__,_and,__g,_o,__,_h,_o,_me,_dot,_ret
		.BYTE	_W,_it,_h,_ou,_t_,_you,_r,__,_b,_i,_k,_e,_s,_col,__,_you,_apo,_re,_ret
		.BYTE	_n,_o,_t,_h,_ing,__,_b,_u,_t_,_l,_o,_s,_er,__,_p,_er,_ve,_r,_t,_s,_dot,_aof,_eol
_sc7_msg10:
		.BYTE	_Kai,_ddt_,_an1,_S,_k,_i,_r,_t,_str,_c,_ha,_s,_er,_s,_col,_ret
		.BYTE	_a,_c,_t,_u,_a,_ll,_y,_dot,_aof,_eol
_sc7_msg11:
		.BYTE	_J,_u,_st,__a,_f,_t,_er,__the,__,_Groupie,_s_,_le,_f,_t,_col,_ret
		.BYTE	_t,_her,_e_,_was,__a,_n,__,_e,_x,_p,_l,_o,_s,_i,_on,__,_b,_y,__the,_ret
		.BYTE	_w,_a,_l,_k,_w,_a,_y,_dot_dot_dot,_eol
_sc7_msg12:
		.BYTE	_W,_hat,__,_was,__t,_hat,_que,_exc,_ret
		.BYTE	_ret
		.BYTE	__,__,__,__,__,__,_str,_c,_ou,_g,_h,_str,_ret
		.BYTE	_ret
		.BYTE	__,__,_H,_e,_l,_p,_exc,_ret
		.BYTE	_ret
		.BYTE	__,__,__,__,__,__,__,__,__,_R,_u,_n,__,_for,__,_it,_exc,_ret
		.BYTE	_ret
		.BYTE	_C,_a,_ll,__the,__,_p,_o,_l,_i,_c,_e,_exc,_eol
_sc7_msg13:
		.BYTE	_Yamagata,_ddt_,_an2,_Damn,_col,__the,_ret
		.BYTE	_Terrorist,_s,__a,_g,_a,_in,_dot,__,_L,_e,_t,_apo_s,__,_c,_he,_c,_k,_ret
		.BYTE	_it,__,_ou,_t,_exc,_aof,_eol
_sc7_msg14:
		.BYTE	_A,_s_,_I_,_m,_ad,_e_,_m,_y,__w,_a,_y,__t,_h,_r,_ou,_g,_h,__the,_ret
		.BYTE	_f,_le,_e,_ing,__,_p,_e,_o,_p,_le,_col,__the,__,_Terrorist,_s,_ret
		.BYTE	_e,_me,_r,_g,_ed,__,_f,_ro,_m,__the,__s,_m,_ok,_e,_dot,_eol
_sc7_msg15:
		.BYTE	_M,_y,__,_f,_r,_i,_en,_d,_s_,_were_,_l,_o,_st,__i,_n,__the,_ret
		.BYTE	_c,_r,_ow,_d,_dot,_eol
_sc7_msg16:
		.BYTE	_The,_re,__,_were_,_4,__,_or,__,_5,__of,__the,_m,_dot,_ret
		.BYTE	_The,_y,__,_c,_a,_me,__,_ou,_t_,_of,__the,__s,_m,_ok,_e,_col,_ret
		.BYTE	_g,_u,_n,_s_,_b,_l,_a,_z,_ing,_exc,__,_The,__,_Terrorist,_s,_ret
		.BYTE	_at,_t,_a,_c,_k,_ed,__the,__,_Army,_exc,_eol
_sc7_msg17:
		.BYTE	_The,_re,_apo_s,__a,__g,_irl,__a,_m,_on,_g,__the,_m,_dot,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_T,_hat,_apo_s,__the,__g,_irl,__,_f,_ro,_m,_ret
		.BYTE	_before,_exc,_eol
_sc7_msg18:
		.BYTE	_It_apo_s,__s,_o,__s,_m,_ok,_e,_y,_dot_dot_dot,_eol
_sc7_msg19:
		.BYTE	_The,__,_Army,__,_c,_ha,_s,_ed,__the,_ret
		.BYTE	_Terrorist,_s,_col,__,_le,_a,_v,_ing,__the,_ret
		.BYTE	_w,_a,_l,_k,_w,_a,_y,_dot,_eol
_sc7_msg1A:
		.BYTE	_I_,_c,_an,__,_he,_ar,__the,__,_Army,__s,_h,_ou,_t,_ing,_dot,_eol
_sc7_msg1B:
		.BYTE	_Army,_ddt_,_The,_y,__w,_en,_t_,_for,__the,_ret
		.BYTE	_sewer,_s,_exc,_eol
_sc7_msg1C:
		.BYTE	_The,__,_Army,__,_le,_t,__the,_m,__,_r,_u,_n,_dot,_eol
_sc7_msg1D:
		.BYTE	_Groupie,_ddt_,_an0,_You_apo_re,__g,_o,_ing,__,_to_,_s,_a,_ve,_ret
		.BYTE	_Tetsuo,_col,__,_r,_ight,__,_Kaneda,_que,_aof,_eol
_sc7_msg1E:
		.BYTE	_Groupie,_ddt_,_an0,_F,_in,_e,_dot,__,_C,_apo,_m,_on,_col,__,_le,_t,_apo_s,_ret
		.BYTE	_g,_o,_exc,__,_L,_e,_t,_apo_s,__,_d,_it,_c,_h,__the,__,_p,_er,_v,_s,_dot,_aof,_eol
_sc7_msg1F:
		.BYTE	_Kaneda,_ddt_,_I_,_w,_an,_t,_ed,__,_to_,_a,_s,_k,__,_you,_ret
		.BYTE	_g,_u,_y,_s,__s,_o,_me,_t,_h,_ing,_dot_dot_dot,_eol
_sc7_msg20:
		.BYTE	_The,__,_h,_an,_g,_ou,_t,_dot_dot_dot,__,_A,_s_,_u,_s,_u,_a,_l,_col,__,_n,_o,_ret
		.BYTE	_on,_e,_apo_s,__,_her,_e,_dot,_eol
_sc7_msg21:
		.BYTE	_I_,_en,_d,_ed,__,_u,_p,__i,_n,__the,__,_sewer,_s,_dot,_eol
_sc7_msg22:
		.BYTE	_Man,_ddt_,_an0,_A,__g,_irl,_que,__,_The,__,_Army,__,_was,_ret
		.BYTE	_c,_ha,_s,_ing,__,_on,_e_,_d,_ow,_n,__the,_re,_dot_dot_dot,_aof,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_T,_h,_an,_k,_s,_exc,_ret
		.BYTE	_ret
		.BYTE	_I_,_r,_an,__,_to_,_t,_he,__,_sewer,_s,_dot,_eol
_sc7_msg23:
		.BYTE	_I_,_p,_a,_s,_s,_ed,__,_b,_y,__the,__,_O,_l,_d_,_T,_ow,_n,_col,__the,_ret
		.BYTE	_n,_oo,_d,_le,__s,_h,_o,_p,_col,__,_and,__the,__,_d,_or,_m,_s,_dot,_eol
_sc7_msg24:
		.BYTE	_Man,_ddt_,_an0,_A,__g,_irl,_col,__,_e,_h,_que,__,_H,_a,_ve,_n,_apo,_t,_ret
		.BYTE	_se,_en,__,_her,_dot,_aof,_eol
_sc7_msg25:
		.BYTE	_I_,_w,_en,_t,__t,_ow,_ar,_d,_s,__the,__,_f,_a,_c,_t,_or,_i,_e,_s,_dot,_eol
_sc7_msg26:
		.BYTE	_Man,_ddt_,_an0,_A,__,_G,_irl,_que,_exc,__,_W,_h,_o,__,_c,_are,_s,_que,_ret
		.BYTE	_G,_i,_m,_me,__s,_o,_me,__,_p,_i,_ll,_s,_exc,_aof,_eol
_sc7_msg27:
		.BYTE	_Kaneda,_ddt_,_A,_h,_exc,_ret
		.BYTE	_ret
		.BYTE	_The,__,_d,_r,_u,_g,__a,_d,_d,_i,_c,_t_,_p,_u,_ll,_ed,__,_ou,_t,__a,_ret
		.BYTE	_k,_n,_i,_f,_e_,_and,__s,_p,_r,_u,_n,_g,__a,_t_,_me,_exc,_eol
_sc7_msg28:
		.BYTE	_But,__,_I_apo,_ve,__g,_o,_t,__a,_ll,__,_k,_in,_d,_s_,_of,__w,_a,_y,_s,_ret
		.BYTE	_to_,_d,_e,_a,_l,__,_with,__s,_h,_it,__,_l,_i,_k,_e_,_this,_ret
		.BYTE	_b,_y,__,_n,_ow,_dot,_eol
_sc7_msg29:
		.BYTE	_W,_a,_s,__the,__,_Army,__,_c,_ha,_s,_ing,__t,_hat,_ret
		.BYTE	_g,_irl,_que,_eol
_sc7_msg2A:
		.BYTE	_I,_f,__the,__,_Army,__i,_s_,_b,_u,_s,_y,__,_with,__the,_ret
		.BYTE	_Terrorist,_s,_col,__a,_ll,__the,__,_be,_t,_t,_er,_ret
		.BYTE	_for,__,_u,_s,_dot,_eol
_sc7_msgBB:
		.BYTE	_T,_hat,__,_n,_ight,_col,__w,_e_,_were_,_on,__the,_ret
		.BYTE	_ro,_of,_t,_o,_p,__g,_ar,_d,_en,__i,_n,__,_f,_r,_on,_t_,_of,_ret
		.BYTE	_t,_he,__,_f,_ou,_n,_t,_a,_in,_dot,__,_A,__,_f,_e,_w,__,_c,_ou,_p,_le,_s,_ret
		.BYTE	_were_,_h,_an,_g,_ing,__,_ou,_t,_dot,_eol
_sc7_msgBC:
		.BYTE	_dot_dot_dot,_W,_hat,__,_was,__t,_hat,__w,_r,_in,_k,_l,_y,__,_k,_id,_ret
		.BYTE	_f,_ro,_m,__t,_hat,__,_n,_ight,_col,__a,_n,_y,_w,_a,_y,_que,_eol
_sc7_msgBD:
		.BYTE	_The,_re,_apo_s,__,_n,_o,__w,_a,_y,__,_Tetsuo,__,_ha,_s,__a,_n,_y,_ret
		.BYTE	_c,_on,_n,_e,_c,_t,_i,_on,__,_to_,_t,_hat,__,_k,_id,_col,__,_r,_ight,_que,_ret
		.BYTE	_W,_her,_e,__the,__,_he,_ll,__,_d,_id,__t,_h,_o,_se,__,_Army,_ret
		.BYTE	_g,_u,_y,_s,__t,_a,_k,_e_,_Tetsuo,_que,_eol
_sc7_msgBE:
		.BYTE	_Kai,_ddt_,_an1,_S,_o,_col,__w,_hat,_apo,_re,__,_you,__t,_h,_in,_k,_in,_apo,_ret
		.BYTE	_a,_b,_ou,_t,_que,_aof,_ret
		.BYTE	_ret
		.BYTE	_Groupie,_ddt_,_an0,_T,_his,__i,_s,_col,__,_l,_i,_k,_e,_col,_ret
		.BYTE	_b,_or,_ing,_exc,_aof,_ret
		.BYTE	_ret
		.BYTE	_Yamagata,_ddt_,_an2,_S,_h,_u,_t_,_u,_p,_exc,_aof,_ret
		.BYTE	_ret
		.BYTE	_Groupie,_ddt_,_an0,_H,_m,_p,_h,_dot_dot_dot,__i,_d,_i,_o,_t,_exc,_aof,_eol

		SECTION_END		F7
