
		SECTION_START	F0

		MSG_START	_scene0_msg_lib
		MSG_IDX _sc0_msgB8
		MSG_IDX	_sc0_msg01
		MSG_IDX	_sc0_msg02
		MSG_IDX	_sc0_msg03
		MSG_IDX	_sc0_msg04
		MSG_IDX	_sc0_msg05
		MSG_IDX	_sc0_msg06
		MSG_IDX	_sc0_msg07
		MSG_IDX	_sc0_msg08
		MSG_IDX	_sc0_msg09
		MSG_IDX	_sc0_msg19
		MSG_IDX	_sc0_msg26
		MSG_IDX	_sc0_msg2E
		MSG_IDX	_sc0_msg2F
		MSG_IDX	_sc0_msg30
_sc0_msgB8:
		.BYTE	_T,_hat,__,_n,_ight,_col,__w,_e_,_were_,_c,_ha,_s,_ing,_ret
		.BYTE	_t,_he,__,_Clown,_s,__a,_l,_on,_g,__the,__,_h,_i,_g,_h,_w,_a,_y,_s,_ret
		.BYTE	_of,__the,__,_O,_l,_d_,_T,_ow,_n,_dot,_eol
_sc0_msg01:
		.BYTE	_S,_u,_d,_d,_en,_l,_y,_col,__,_Tetsuo,_apo_s,__,_b,_i,_k,_e_,_b,_u,_r,_st,_ret
		.BYTE	_in,_to_,_f,_l,_a,_me,_s,_dot,_eol
_sc0_msg02:
		.BYTE	_I_,_r,_an,__,_to_,_Tetsuo,_col,__,_and,__,_he,_l,_p,_ed,_ret
		.BYTE	_s,_it,__,_h,_i,_m,__,_u,_p,_dot,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_H,_an,_g,__i,_n,__the,_re,_col,__,_Tetsuo,_exc,_ret
		.BYTE	_ret
		.BYTE	_Tetsuo,_ddt_,_H,_str,_str,_he,__,_d,_i,_d_,_this,_dot_dot_dot,_ret
		.BYTE	_ret
		.BYTE	_Tetsuo,__,_p,_o,_in,_t,_ed,__,_to_,_s,_o,_me,_on,_e,_col,__,_b,_u,_t,_ret
		.BYTE	_I_,_was,_n,_apo,_t,__s,_u,_re,__i,_f,__,_it,__,_was,__a,_n,__,_o,_l,_d,_ret
		.BYTE	_m,_an,_col,__,_or,__a,__,_ve,_r,_y,__w,_r,_in,_k,_l,_y,__,_k,_id,_dot,_eol
_sc0_msg03:
		.BYTE	_Kaneda,_ddt_,_W,_h,_y,__,_you,_dot_dot_dot,__,_W,_hat,__,_d,_id,_ret
		.BYTE	_you,__,_d,_o,_col,__,_you,__w,_e,_i,_r,_d_,_l,_it,_t,_le,_dot_dot_dot,_ret
		.BYTE	_ret
		.BYTE	_A,_n,__a,_p,_p,_ro,_a,_c,_h,_ing,__,_he,_l,_i,_c,_o,_p,_t,_er,_ret
		.BYTE	_d,_r,_ow,_n,_ed,__,_ou,_t_,_m,_y,__,_v,_o,_i,_c,_e,_dot,__,_I,_t_,_was,_ret
		.BYTE	_t,_he,__,_Army,_dot,_ret
		.BYTE	_ret
		.BYTE	_H,_e,_ar,_ing,__,_it,_col,__the,__w,_r,_in,_k,_l,_y,__,_k,_id,_ret
		.BYTE	_be,_g,_an,__,_to_,_t,_re,_m,_b,_le,_dot,_eol
_sc0_msg04:
		.BYTE	_The,__,_he,_l,_i,_c,_o,_p,_t,_er,__,_l,_and,_ed,__,_n,_e,_x,_t,__t,_o,_ret
		.BYTE	_u,_s,_col,__,_it,_s_,_d,_oo,_r,__,_o,_p,_en,_ing,__,_to_,_re,_ve,_a,_l,_ret
		.BYTE	_a,__,_m,_an,_dot,_eol
_sc0_msg05:
		.BYTE	_Takashi,_col,__the,__w,_r,_in,_k,_l,_y,__,_k,_id,_col,_ret
		.BYTE	_st,_are,_d_,_at,__the,__,_m,_an,_col,__,_his,__,_f,_a,_c,_e,_ret
		.BYTE	_st,_i,_f,_f,_en,_ing,__,_with,__,_f,_e,_ar,_dot,_eol
_sc0_msg06:
		.BYTE	_Army,_ddt_,_H,_and,_s_,_be,_h,_in,_d_,_you,_r,__,_he,_ad,_exc,_ret
		.BYTE	_E,_l,_b,_ow,_s_,_on,__the,__g,_r,_ou,_n,_d,_exc,_eol
_sc0_msg07:
		.BYTE	_Kaneda,_ddt_,_H,_o,_str,_str,_h,_o,_l,_d_,_on,__,_m,_i,_st,_er,_exc,_ret
		.BYTE	_W,_e_,_d,_id,_n,_apo,_t_,_d,_o,__,_n,_o,_t,_h,_ing,_exc,_eol
_sc0_msg08:
		.BYTE	_Kaneda,_ddt_,_M,_y,__,_f,_r,_i,_en,_d,_apo_s,__,_h,_u,_r,_t,_exc,_ret
		.BYTE	_ret
		.BYTE	_Army,_ddt_,_Colonel,_exc,__,_The,_re,_apo_s,__a,_n,_ret
		.BYTE	_in,_j,_u,_r,_ed,__,_p,_er,_s,_on,__,_her,_e,_exc,_ret
		.BYTE	_ret
		.BYTE	_Man,_ddt_,_an0,_W,_e_,_w,_i,_ll,__t,_a,_k,_e_,_h,_i,_m,__t,_o,_ret
		.BYTE	_t,_he,__,_l,_a,_b,_dot,__,_L,_e,_t,_apo_s,__g,_o,_dot,_aof,_eol
_sc0_msg09:
		.BYTE	_Kaneda,_ddt_,_an1,_Y,_ou,__,_st,_u,_p,_i,_d_,_j,_er,_k,_s,_exc,_ret
		.BYTE	_W,_hat,__the,__,_he,_ll,__,_are,__,_you,__g,_o,_ing,__t,_o,_ret
		.BYTE	_d,_o,__,_with,__,_u,_s,_exc,_que,_aof,_eol
_sc0_msg19:
		.BYTE	_Man,_ddt_,_an0,_Takashi,_col,__,_I_apo,_ve,__,_c,_o,_me,__,_for,_ret
		.BYTE	_you,_dot,__,_C,_o,_me,__,_on,_col,__,_le,_t,_apo_s,__g,_o,__,_b,_a,_c,_k,_dot,_ret
		.BYTE	_N,_on,_e_,_of,__,_you,__,_are,__a,_ll,_ow,_ed,__t,_o,_ret
		.BYTE	_l,_i,_ve,__,_ou,_t,_s,_id,_e,_col,__,_you,__,_k,_n,_ow,__t,_hat,_exc,_aof,_eol
_sc0_msg26:
		.BYTE	_Tetsuo,__,_ha,_p,_p,_en,_ed,__,_to_,_t,_a,_k,_e,__the,_ret
		.BYTE	_le,_a,_d_,_for,__a,__,_c,_h,_an,_g,_e_,_this,__t,_i,_me,_dot,_ret
		.BYTE	_ret
		.BYTE	_W,_e_,_ha,_d_,_j,_u,_st,__,_p,_a,_s,_s,_ed,__a,__,_tollbooth,_ret
		.BYTE	_w,_h,_en,__,_it,__,_ha,_p,_p,_en,_ed,_dot_dot_dot,_eol
_sc0_msg2E:
		.BYTE	_Man,_ddt_,_an0,_A,_r,_re,_st,__the,_se,__,_p,_u,_n,_k,_s,_exc,_aof,_ret
		.BYTE	_ret
		.BYTE	_The,__,_Army,__,_c,_a,_me,__,_and,__t,_oo,_k,__,_u,_s,__i,_n,_t,_o,_ret
		.BYTE	_c,_u,_st,_o,_d,_y,_dot,_eol
_sc0_msg2F:
		.BYTE	_The,__,_he,_l,_i,_c,_o,_p,_t,_er,__,_c,_ar,_r,_y,_ing,__the,_ret
		.BYTE	_k,_i,_d_,_and,__,_Tetsuo,__s,_l,_ow,_l,_y,__,_l,_i,_f,_t,_ed,_ret
		.BYTE	_of,_f,_dot,_eol
_sc0_msg30:
		.BYTE	_L,_oo,_k,_s_,_l,_i,_k,_e,__the,_y,__t,_h,_in,_k,__w,_e,_apo,_re,_ret
		.BYTE	_Terrorist,_s,_dot,_eol

		SECTION_END		F0
