
		SECTION_START	FC

		MSG_START	_sceneC_msg_lib
		MSG_IDX	_scC_msg00
		MSG_IDX	_scC_msg01
		MSG_IDX	_scC_msg02
		MSG_IDX	_scC_msg03
		MSG_IDX	_scC_msg04
		MSG_IDX	_scC_msg05
		MSG_IDX	_scC_msg06
		MSG_IDX	_scC_msg07
		MSG_IDX	_scC_msg08
		MSG_IDX	_scC_msg09
		MSG_IDX	_scC_msg0A
		MSG_IDX	_scC_msg0B
		MSG_IDX	_scC_msg0C
		MSG_IDX	_scC_msg0D
		MSG_IDX	_scC_msg0E
		MSG_IDX	_scC_msg0F
		MSG_IDX	_scC_msg10
		MSG_IDX	_scC_msg11
		MSG_IDX	_scC_msg12
		MSG_IDX	_scC_msg13
_scC_msg00:
		.BYTE	_The,__,_n,_e,_x,_t_,_d,_a,_y,_col,__w,_e_,_s,_n,_u,_c,_k,__i,_n,_t,_o,_ret
		.BYTE	_t,_he,__,_l,_a,_b,__t,_h,_r,_ou,_g,_h,__w,_hat,__a,_p,_p,_e,_are,_d,_ret
		.BYTE	_to_,_be,__the,__,_d,_r,_a,_in,_a,_g,_e_,_s,_y,_st,_e,_m,_dot_dot_dot,_eol
_scC_msg01:
		.BYTE	_Kaneda,_ddt_,_Man,_col,__,_this,__,_st,_in,_k,_s,_exc,_ret
		.BYTE	_ret
		.BYTE	_Kei,_ddt_,_S,_h,_h,_col,__,_q,_u,_i,_e,_t,_exc,_eol
_scC_msg02:
		.BYTE	_Kaneda,_ddt_,_W,_hat,_que,__,_I_apo,_m,__s,_a,_y,_ing,__,_it,_ret
		.BYTE	_st,_in,_k,_s,_col,__,_be,_c,_a,_u,_se,__,_it,__,_d,_o,_e,_s,_exc,__,_Y,_ou,_r,_ret
		.BYTE	_s,_me,_ll,__,_m,_u,_st,__,_be,__of,_f,_dot,_eol
_scC_msg03:
		.BYTE	_Terrorist,_ddt_,_U,_p,__a,_he,_a,_d_,_i,_s,__the,_ret
		.BYTE	_c,_en,_t,_r,_a,_l,__w,_i,_r,_ing,__s,_y,_st,_e,_m,_dot,__,_I,_f,_ret
		.BYTE	_w,_e,_apo,_re,__a,_b,_le,__,_to_,_b,_l,_o,_c,_k,__,_it,_col,__w,_e,_ret
		.BYTE	_s,_h,_ou,_l,_d_,_be,__a,_b,_le,__,_to_,_s,_n,_e,_a,_k,__i,_n,_t,_o,_ret
		.BYTE	_t,_he,__,_b,_a,_se,_me,_n,_t,_dot,_eol
_scC_msg04:
		.BYTE	_Ryu,_ddt_,_Damn,_exc,__,_The,_y,_apo,_ve,__s,_p,_o,_t,_t,_ed,_ret
		.BYTE	_u,_s,_exc,_ret
		.BYTE	_ret
		.BYTE	_Terrorist,_ddt_,_The,_y,_apo,_re,__,_F,_dot,_P,_dot,_H,_dot,_s,_exc,_eol
_scC_msg05:
		.BYTE	_O,_n,_e_,_of,__the,__,_Terrorist,_s_,_was,__,_h,_it,_exc,_eol
_scC_msg06:
		.BYTE	_Kei,_ddt_,_D,_o,__,_it,__,_q,_u,_i,_c,_k,_l,_y,__,_and,_ret
		.BYTE	_q,_u,_i,_e,_t,_l,_y,_exc,_eol
_scC_msg07:
		.BYTE	_I_,_p,_i,_c,_k,_ed,__,_u,_p,__the,__,_d,_e,_ad,_ret
		.BYTE	_Terrorist,_apo_s,__g,_u,_n,_dot,_eol
_scC_msg08:
		.BYTE	_But,__the,__g,_u,_n,__,_on,__the,_ret
		.BYTE	_F,_dot,_P,_dot,_H,_dot,__s,_w,_i,_ve,_l,_ed,__t,_ow,_ar,_d_,_me,_dot,_ret
		.BYTE	_V,_u,_l,_c,_an,_i,_z,_ed,__,_b,_u,_l,_le,_t,_s_,_d,_ro,_ve,__i,_n,_t,_o,_ret
		.BYTE	_t,_he,__,_m,_u,_d,_dot,_eol
_scC_msg09:
		.BYTE	_Kaneda,_ddt_,_H,_u,_h,_que,__,_It_apo_s,__,_ou,_t_,_of,__a,_m,_m,_o,_exc,_eol
_scC_msg0A:
		.BYTE	_Kaneda,_ddt_,_Damn,_exc,_ret
		.BYTE	_ret
		.BYTE	_I_,_t,_h,_re,_w,__the,__g,_u,_n,__a,_w,_a,_y,_dot,_eol
_scC_msg0B:
		.BYTE	_Kaneda,_ddt_,_U,_g,_h,_dot_dot_dot,_ret
		.BYTE	_ret
		.BYTE	_str,_c,_ou,_g,_h,_str,__,_str,_c,_ou,_g,_h,_str,_ret
		.BYTE	_ret
		.BYTE	_I_,_l,_a,_i,_d_,_in,__the,__,_m,_u,_d,_dot,_eol
_scC_msg0C:
		.BYTE	_S,_p,_l,_a,_s,_h,_exc,_ret
		.BYTE	_ret
		.BYTE	_I_,_s,_p,_r,_u,_n,_g,__,_ou,_t_,_of,__the,__w,_at,_er,__,_and,_ret
		.BYTE	_c,_l,_i,_m,_b,_ed,__,_on,_to_,_t,_he,__w,_a,_ll,__of,__the,_ret
		.BYTE	_sewer,_dot,_eol
_scC_msg0D:
		.BYTE	_Kaneda,_ddt_,_It_apo_s,__,_c,_o,_m,_ing,_exc,_eol
_scC_msg0E:
		.BYTE	_Kaneda,_ddt_,_H,_i,_i,_y,_a,_a,_h,_exc,_ret
		.BYTE	_ret
		.BYTE	_I_,_le,_a,_p,_t,__t,_ow,_ar,_d,__the,__,_F,_dot,_P,_dot,_H,_dot,_eol
_scC_msg0F:
		.BYTE	_Kaneda,_ddt_,_W,_a,_h,_dot,_ret
		.BYTE	_ret
		.BYTE	_Kei,_ddt_,_A,_a,_a,_h,_dot,_eol
_scC_msg10:
		.BYTE	_I_,_g,_r,_a,_b,_b,_ed,__the,__,_F,_dot,_P,_dot,_H,_dot,_col,__,_and,_ret
		.BYTE	_a,_f,_t,_er,__a,__,_l,_o,_t_,_of,__,_st,_r,_u,_g,_g,_l,_ing,_col,_ret
		.BYTE	_I_,_m,_an,_a,_g,_ed,__,_to_,_g,_e,_t_,_on,_to_,_it,_dot,_eol
_scC_msg11:
		.BYTE	_Kei,_ddt_,_A,_a,_a,_h,_exc,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_Kei,_exc,__,_O,_ve,_r,__,_her,_e,_col,__g,_e,_t,_ret
		.BYTE	_on,__,_q,_u,_i,_c,_k,_exc,_eol
_scC_msg12:
		.BYTE	_Kei,_ddt_,_Kaneda,_exc,__,_The,_y,_apo,_re,__,_be,_h,_in,_d,_ret
		.BYTE	_u,_s,_exc,_eol
_scC_msg13:
		.BYTE	_A,__,_But,_t,_on,_ddt_,_F,_i,_re,_ret
		.BYTE	_B,__,_But,_t,_on,_ddt_,_D,_o,_d,_g,_e,_ret
		.BYTE	_S,_e,_le,_c,_t,_ddt_,__,__,_T,_u,_r,_n,__,_around,_eol

		SECTION_END		FC
