
		SECTION_START	FA

		MSG_START	_sceneA_msg_lib
		MSG_IDX	_scA_msg00
		MSG_IDX	_scA_msg01
		MSG_IDX	_scA_msg02
		MSG_IDX	_scA_msg03
		MSG_IDX	_scA_msg04
		MSG_IDX	_scA_msg05
		MSG_IDX	_scA_msg06
		MSG_IDX	_scA_msg07
		MSG_IDX	_scA_msg08
		MSG_IDX	_scA_msg09
		MSG_IDX	_scA_msg0A
		MSG_IDX	_scA_msg0B
		MSG_IDX	_scA_msg0C
		MSG_IDX	_scA_msg0D
		MSG_IDX	_scA_msg0E
		MSG_IDX	_scA_msg0F
		MSG_IDX	_scA_msg10
		MSG_IDX	_scA_msg11
		MSG_IDX	_scA_msg12
		MSG_IDX	_scA_msg13
		MSG_IDX	_scA_msg14
		MSG_IDX	_scA_msg15
;		MSG_IDX	_scA_msg16					; unused
		MSG_IDX	_scA_msg17
		MSG_IDX	_scA_msg18
		MSG_IDX	_scA_msg19
		MSG_IDX	_scA_msg1A
_scA_msg00:
		.BYTE	_The,_y,__,_l,_o,_c,_k,_ed,__,_me,__i,_n,__a,_ret
		.BYTE	_c,_r,_a,_m,_p,_ed,__,_ro,_o,_m,_dot,_eol
_scA_msg01:
		.BYTE	_It_apo_s,__a,__,_b,_at,_h,_ro,_o,_m,_dot,_eol
_scA_msg02:
		.BYTE	_J,_er,_k,_s,_col,__w,_hat,__,_m,_ad,_e_,_you,__t,_h,_in,_k,_ret
		.BYTE	_I_apo,_m,__a,__s,_p,_y,_que,_exc,_eol
_scA_msg03:
		.BYTE	_Kei,_col,__,_this,__t,_i,_me,__,_I_apo,_ll,__,_d,_e,_f,_in,_it,_e,_l,_y,_ret
		.BYTE	_a,_s,_k,__,_you,__,_ou,_t,_dot,_eol
_scA_msg04:
		.BYTE	_The,_i,_r,__a,_t,_t,_it,_u,_d,_e_,_c,_h,_an,_g,_ed,__,_and,_ret
		.BYTE	_t,_he,_y,__,_b,_l,_a,_m,_ed,__,_Kei,_dot,__,_M,_a,_y,_be,__the,_ret
		.BYTE	_Terrorist,_s,_apo,__g,_o,_a,_l,_s_,_were_,_se,_t,_ret
		.BYTE	_t,_oo,__,_h,_i,_g,_h,_dot_dot_dot,_eol
_scA_msg05:
		.BYTE	_bra,_E,_xperimental,__,_S,_u,_b,_j,_e,_c,_t,_bra,_que,__,_W,_her,_e,_ret
		.BYTE	_t,_he,__,_he,_ll,__,_d,_id,__the,_y,__t,_a,_k,_e_,_Tetsuo,_que,_eol
_scA_msg06:
		.BYTE	_It_apo_s,__a,__,_b,_at,_h,_t,_u,_b,_dot,_eol
_scA_msg07:
		.BYTE	_Kaneda,_ddt_,_It_apo_s,__a,_b,_ou,_t_,_Tetsuo,_exc,_eol
_scA_msg08:
		.BYTE	_The,_re,_apo_s,__a,__,_n,_e,_t,_w,_or,_k,__of,_ret
		.BYTE	_a,_i,_r,__,_d,_u,_c,_t,_s,_dot,_eol
_scA_msg09:
		.BYTE	_Kaneda,_ddt_,_B,_e,_er,_exc,__,_A,_n,_d_,_it,_apo_s,__,_c,_o,_l,_d,_exc,_eol
_scA_msg0A:
		.BYTE	_Kaneda,_ddt_,_It_apo_s,__t,_h,_o,_se,__,_j,_er,_k,_s,_apo,_ret
		.BYTE	_be,_er,_col,__s,_o,__,_b,_o,_t,_t,_o,_m,_s_,_u,_p,_exc,_ret
		.BYTE	_B,_o,_t,_t,_le,__,_o,_p,_en,_er,_dot_dot_dot,_ret
		.BYTE	_dot_dot_dot,_The,_re,_apo_s,__,_n,_o,__,_o,_p,_en,_er,_dot_dot_dot,_ret
		.BYTE	_W,_on,_d,_er,__i,_f,__,_I_,_c,_an,__,_k,_n,_o,_c,_k,__the,_ret
		.BYTE	_c,_a,_p,__of,_f,_dot_dot_dot,_eol
_scA_msg0B:
		.BYTE	_Kaneda,_ddt_,_T,_his,__,_l,_oo,_k,_s_,_l,_i,_k,_e_,_a,__g,_oo,_d,_ret
		.BYTE	_s,_p,_o,_t_,_to_,_o,_p,_en,__,_it,_exc,__,_O,_k,__,_n,_ow,_dot_dot_dot,_eol
_scA_msg0C:
		.BYTE	_S,_h,_p,_on,_exc,__,_G,_t,_an,_g,_exc,_ret
		.BYTE	_ret
		.BYTE	_The,__,_ve,_n,_t_,_o,_p,_en,_ed,_exc,_ret
		.BYTE	_ret
		.BYTE	_L,_oo,_k,_s_,_l,_i,_k,_e_,_I_,_c,_an,__g,_e,_t_,_ou,_t,_ret
		.BYTE	_of,__,_her,_e,_dot,_eol
_scA_msg0D:
		.BYTE	_C,_l,_in,_k,__,_C,_l,_an,_k,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_H,_m,_m,_col,__,_l,_oo,_k,_s_,_l,_i,_k,_e_,_it,_ret
		.BYTE	_w,_on,_apo,_t_,_o,_p,_en,__,_her,_e,_dot,_eol
_scA_msg0E:
		.BYTE	_I_,_c,_r,_a,_w,_l,_ed,__i,_n,_to_,_t,_he,__a,_i,_r,__,_d,_u,_c,_t,_dot,_eol
_scA_msg0F:
		.BYTE	_dot_dot_dot,_I_,_f,_e,_ll,__a,_s,_le,_e,_p,_dot,_eol
_scA_msg10:
		.BYTE	_It_apo_s,__a,__,_c,_a,_se,__of,__,_be,_er,_dot,_eol
_scA_msg11:
		.BYTE	_Kaneda,_ddt_,_J,_e,_e,_z,_col,__the,_re,_apo_s,__,_n,_o,_t,_h,_ing,_ret
		.BYTE	_in,__,_her,_e,_dot,_eol
_scA_msg12:
		.BYTE	_Kaneda,_ddt_,_I,_t_,_l,_oo,_k,_s_,_c,_r,_a,_m,_p,_ed,_dot,_eol
_scA_msg13:
		.BYTE	_Kaneda,_ddt_,_I_apo,_ve,__,_m,_ad,_e_,_it,__,_to_,_t,_he,_ret
		.BYTE	_ve,_n,_t,__i,_n,__the,__,_n,_e,_x,_t_,_ro,_o,_m,_dot_dot_dot,_eol
_scA_msg14:
		.BYTE	_I_,_he,_ar,__,_v,_o,_i,_c,_e,_s,_dot,__,_It_apo_s,__,_Ryu,__,_and,_ret
		.BYTE	_t,_he,__,_Terrorist,_s,_dot_dot_dot,_eol
_scA_msg15:
		.BYTE	_I_,_c,_an,__g,_e,_t_,_ou,_t_,_this,__w,_a,_y,_dot,_eol
;_scA_msg16:
;		.BYTE	_W,_at,_er,_apo_s,__,_d,_r,_i,_p,_p,_ing,__,_f,_ro,_m,_ret
;		.BYTE	_t,_he,__,_c,_e,_i,_l,_ing,_dot,_eol
_scA_msg17:
		.BYTE	_Kei,_col,__,_you,__s,_h,_ou,_l,_d_,_j,_o,_in,__,_me,__i,_n,_ret
		.BYTE	_her,_e_,_n,_e,_x,_t,__t,_i,_me,_exc,__,_R,_a,_w,_r,_dot,_eol
_scA_msg18:
		.BYTE	_T,_h,_u,_d,_exc,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_Damn,_exc,_eol
_scA_msg19:
		.BYTE	_Terrorist,_ddt_,_W,_h,_o,__g,_o,_e,_s,__the,_re,_exc,_que,_eol
_scA_msg1A:
		.BYTE	_I,_s,__the,_re,__a,__w,_a,_y,__,_to_,_he,_ar,_ret
		.BYTE	_t,_he,_i,_r,__,_c,_on,_ve,_r,_s,_at,_i,_on,_que,_eol

		SECTION_END		FA
