
		SECTION_START	F4

		MSG_START	_scene4_msg_lib
		MSG_IDX	_sc4_msg00
		MSG_IDX	_sc4_msg01
		MSG_IDX	_sc4_msg02
		MSG_IDX	_sc4_msg03
		MSG_IDX	_sc4_msg04
		MSG_IDX	_sc4_msg05
		MSG_IDX	_sc4_msg06
		MSG_IDX	_sc4_msg07
		MSG_IDX	_sc4_msg08
_sc4_msg00:
		.BYTE	_T,_h,_o,_se,__,_Army,__,_j,_er,_k,_s_,_j,_u,_st,__,_h,_ad,__t,_o,_ret
		.BYTE	_g,_o,__t,_e,_ll,__,_ou,_r,__s,_c,_h,_oo,_l,__a,_b,_ou,_t_,_it,_exc,_ret
		.BYTE	_S,_o,__w,_e_,_g,_o,_t_,_to_,_f,_e,_e,_l,__the,__w,_r,_at,_h,_ret
		.BYTE	_of,__,_bra,_J,_a,_w,_s,_bra,_col,__the,__,_P,_dot,_E,_dot,__t,_e,_a,_c,_her,_dot,_eol
_sc4_msg01:
		.BYTE	_Groupie,_ddt_,_an1,_W,_hat,__,_ha,_p,_p,_en,_ed,__,_to_,_you,_r,_ret
		.BYTE	_c,_he,_e,_k,_que,_aof,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_S,_h,_u,_t,__the,__,_he,_ll,__,_u,_p,_exc,_ret
		.BYTE	_ret
		.BYTE	_Kai,_ddt_,_an0,_T,_hat,__,_b,_i,_g,_str,_j,_a,_w,_ed,__,_b,_a,_st,_ar,_d,_ret
		.BYTE	_w,_h,_o,__t,_e,_a,_c,_he,_s_,_P,_dot,_E,_dot,_col,__t,_hat,_apo_s,__w,_hat,_exc,_aof,_eol
_sc4_msg02:
		.BYTE	_Groupie,_ddt_,_an1,_The,_y,__s,_a,_y,__,_you,__g,_u,_y,_s,_ret
		.BYTE	_f,_ou,_g,_h,_t,__the,__,_Clown,_s_,_on,__the,_ret
		.BYTE	_h,_i,_g,_h,_w,_a,_y,__i,_n,__the,__,_O,_l,_d_,_T,_ow,_n,_dot,_ret
		.BYTE	_W,_h,_y,__,_d,_id,_n,_apo,_t_,_you,__,_j,_u,_st,__w,_i,_p,_e_,_apo,_e,_m,_ret
		.BYTE	_ou,_t,_que,__,_T,_h,_o,_se,__g,_u,_y,_s_,_are,_col,_ret
		.BYTE	_l,_i,_k,_e,_col,__s,_o,__g,_ro,_s,_s,_dot,_aof,_eol
_sc4_msg03:
		.BYTE	_Yamagata,_ddt_,_an2,_The,_re,__,_were_,_Clown,_s,_col,_ret
		.BYTE	_d,_e,_m,_on,_st,_r,_at,_or,_s,_col,__,_c,_o,_p,_s,_col,__the,__,_d,_a,_m,_n,_ret
		.BYTE	_Army,_dot_dot_dot,__,_A,_n,_d,__t,_hat,__i,_d,_i,_o,_t_,_Tetsuo,_ret
		.BYTE	_ha,_d_,_to_,_g,_o,__,_and,__,_ha,_ve,__t,_hat,_ret
		.BYTE	_a,_c,_c,_id,_en,_t,_dot,_aof,_ret
		.BYTE	_ret
		.BYTE	_Groupie,_ddt_,_an1,_W,_hat,_exc,_que,__,_W,_hat,_ret
		.BYTE	_ha,_p,_p,_en,_ed,__,_to_,_Tetsuo,_que,_exc,_aof,_eol
_sc4_msg04:
		.BYTE	_Kai,_ddt_,_an0,_H,_e,_apo_s,__i,_n,__the,__,_h,_o,_s,_p,_it,_a,_l,_col,_ret
		.BYTE	_I_,_g,_u,_e,_s,_s,_dot_dot_dot,__,_But,__w,_e_,_d,_on,_apo,_t_,_k,_n,_ow,_ret
		.BYTE	_w,_her,_e,_dot,_aof,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_The,__i,_d,_i,_o,_t_,_was,__t,_r,_y,_ing,_ret
		.BYTE	_to_,_s,_h,_ow,__of,_f,_dot_dot_dot,_eol
_sc4_msg05:
		.BYTE	_Kai,_ddt_,_an0,_It_apo_s,__,_Tetsuo,_exc,__,_Kaneda,_col,_ret
		.BYTE	_l,_oo,_k,_exc,__,_Y,_ou,_r,__,_b,_i,_k,_e,_dot_dot_dot,_aof,_eol
_sc4_msg06:
		.BYTE	_Tetsuo,__,_was,__,_r,_id,_ing,__,_M,_Y,__,_b,_i,_k,_e_,_with,_ret
		.BYTE	_a,__g,_irl,__,_be,_h,_in,_d_,_h,_i,_m,_dot,_eol
_sc4_msg07:
		.BYTE	_Kaneda,_ddt_,_T,_hat,__i,_d,_i,_o,_t,__t,_h,_in,_k,_s_,_he,_ret
		.BYTE	_c,_an,__,_h,_and,_le,__,_m,_y,__,_b,_i,_k,_e,_que,_ret
		.BYTE	_ret
		.BYTE	_Kai,_ddt_,_W,_h,_o,__,_d,_o,_e,_s_,_he,__t,_h,_in,_k,__,_he,_apo_s,_ret
		.BYTE	_f,_oo,_l,_ing,_que,_eol
_sc4_msg08:
		.BYTE	_I_,_g,_o,_t_,_on,__,_Yamagata,_apo_s,__,_b,_i,_k,_e_,_and,_ret
		.BYTE	_w,_en,_t,__a,_f,_t,_er,__,_h,_i,_m,_dot,__,_H,_a,_d_,_to_,_t,_e,_a,_c,_h,_ret
		.BYTE	_Tetsuo,__a,__,_le,_s,_s,_on,_dot,_eol

		SECTION_END		F4
