
		SECTION_START	FF

		MSG_START	_sceneF_msg_lib
		MSG_IDX	_scF_msg00
		MSG_IDX	_scF_msg01
		MSG_IDX	_scF_msg02
		MSG_IDX	_scF_msg03
		MSG_IDX	_scF_msg04
		MSG_IDX	_scF_msg05
		MSG_IDX	_scF_msg06
		MSG_IDX	_scF_msg07
		MSG_IDX	_scF_msg08
		MSG_IDX	_scF_msg09
		MSG_IDX	_scF_msg0A
		MSG_IDX	_scF_msg0C
		MSG_IDX	_scF_msg0D
		MSG_IDX	_scF_msg0E
		MSG_IDX	_scF_msg0F
		MSG_IDX	_scF_msg10
		MSG_IDX	_scF_msg11
		MSG_IDX	_scF_msg12
		MSG_IDX	_scF_msg13
		MSG_IDX	_scF_msg14
		MSG_IDX	_scF_msg15
		MSG_IDX	_scF_msg16
		MSG_IDX	_scF_msg17
		MSG_IDX	_scF_msg18
		MSG_IDX	_scF_msg19
		MSG_IDX	_scF_msg1A
		MSG_IDX	_scF_msg1B
		MSG_IDX	_scF_msg1C
		MSG_IDX	_scF_msg1D
		MSG_IDX	_scF_msg1E
		MSG_IDX	_scF_msg1F
		MSG_IDX	_scF_msg92					; scene F msg
_scF_msg00:
		.BYTE	_The,__,_Nursery,__,_l,_oo,_k,_ed,__,_l,_i,_k,_e_,_it,_apo,_d,_ret
		.BYTE	_be,_en,__t,_h,_r,_ou,_g,_h,__a,_n,__,_e,_ar,_t,_h,_q,_u,_a,_k,_e,_dot,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_H,_e,_y,_col,__,_you,__t,_h,_in,_k,__,_it,_apo_s,_ret
		.BYTE	_M,_Y,__,_f,_a,_u,_l,_t,_que,_exc,_eol
_scF_msg01:
		.BYTE	_Kaneda,_ddt_,_S,_o,__,_this,__i,_s,__the,_ret
		.BYTE	_Nursery,_que,_eol
_scF_msg02:
		.BYTE	_It_apo_s,__the,__,_k,_i,_d_,_f,_ro,_m,__,_before,_exc,_eol
_scF_msg03:
		.BYTE	_The,__,_k,_id,_apo_s,__,_f,_r,_i,_en,_d,_s,_que,_eol
_scF_msg04:
		.BYTE	_Colonel,_ddt_,_G,_e,_t,__the,_se,__,_k,_id,_s_,_ou,_t,_ret
		.BYTE	_of,__,_her,_e_,_n,_ow,_exc,_eol
_scF_msg05:
		.BYTE	_Tetsuo,_ddt_,_Kaneda,_que,_ret
		.BYTE	_dot_dot_dot,_W,_h,_y,__,_are,__,_you,__,_her,_e,_que,_eol
_scF_msg06:
		.BYTE	_Kaneda,_ddt_,_an0,_Tetsuo,_col,__,_you,__,_ok,_que,_ret
		.BYTE	_I_,_c,_a,_me,__,_to_,_s,_a,_ve,__,_you,_exc,_aof,_eol
_scF_msg07:
		.BYTE	_Tetsuo,_ddt_,_an1,_It_apo_s,__,_ok,_col,__,_Kaneda,_dot,_ret
		.BYTE	_Y,_ou,__,_d,_on,_apo,_t_,_n,_e,_ed,__,_to_,_s,_a,_ve,__,_me,_ret
		.BYTE	_a,_n,_y,_m,_o,_re,_dot,__,_F,_ro,_m,__,_n,_ow,__,_on,_col,__,_I_apo,_ll,__,_be,_ret
		.BYTE	_t,_he,__,_on,_e_,_s,_a,_v,_ing,__,_you,_dot_dot_dot,_aof,_eol
_scF_msg08:
		.BYTE	_Tetsuo,_ddt_,_Kaneda,_col,__w,_hat,_apo,_re,__,_you,_ret
		.BYTE	_y,_a,_p,_p,_ing,__a,_b,_ou,_t_,_n,_ow,_que,_eol
_scF_msg09:
		.BYTE	_Tetsuo,_ddt_,_an1,_W,_hat,_apo,_re,__,_you,__,_d,_o,_ing,_que,_exc,_aof,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_an0,_U,_g,_h,_dot_dot_dot,__,_A,_u,_g,_h,_exc,_aof,_ret
		.BYTE	_ret
		.BYTE	_B,_oo,_m,_exc,_eol
_scF_msg0A:
		.BYTE	_Kaneda,__,_f,_a,_in,_t,_ed,_dot_dot_dot,_ret
		.BYTE	_ret
		.BYTE	_Kei,_ddt_,_Kaneda,_dot_dot_dot,_eol
_scF_msg0C:
		.BYTE	_Tetsuo,_ddt_,_B,_u,_r,_i,_ed,_dot_dot_dot,__,_b,_en,_e,_at,_h,__the,_ret
		.BYTE	_O,_l,_y,_m,_p,_i,_c,__,_G,_r,_ou,_n,_d,_s,_que,_exc,_ret
		.BYTE	_ret
		.BYTE	_Kiyoko,_ddt_,_an0,_N,_o,_exc,__,_Akira,_apo_s,_dot_dot_dot,_ret
		.BYTE	_W,_a,_it,_exc,__,_A,_a,_h,_exc,_aof,_eol
_scF_msg0D:
		.BYTE	_Tetsuo,__,_d,_e,_st,_ro,_y,_ed,__the,__,_c,_e,_i,_l,_ing,_ret
		.BYTE	_of,__the,__,_Nursery,__,_and,__,_f,_le,_w,__,_ou,_t,_col,_ret
		.BYTE	_le,_a,_v,_ing,__,_on,_l,_y,__,_his,__,_e,_c,_h,_o,_ing,_ret
		.BYTE	_l,_a,_u,_g,_h,_t,_er,__,_be,_h,_in,_d,_dot,_eol
_scF_msg0E:
		.BYTE	_Kiyoko,_ddt_,_an0,_T,_his,__i,_s_,_h,_or,_r,_i,_b,_le,_exc,_ret
		.BYTE	_T,_o,__t,_h,_in,_k,__,_he,_apo_s,__t,_hat,__,_st,_r,_on,_g,_dot_dot_dot,_aof,_eol
_scF_msg0F:
		.BYTE	_Colonel,_ddt_,_an0,_T,_o,__g,_a,_in,__s,_o,__,_m,_u,_c,_h,_ret
		.BYTE	_p,_ow,_er,__i,_n,__s,_o,__,_l,_it,_t,_le,__t,_i,_me,_exc,__,_W,_hat,_ret
		.BYTE	_c,_ou,_l,_d_,_this,__,_me,_an,_dot_dot_dot,__,_F,_in,_d_,_h,_i,_m,_exc,_aof,_eol
_scF_msg10:
		.BYTE	_Kiyoko,_ddt_,_an0,_S,_t,_o,_p,__,_it,_dot_dot_dot,__,_D,_on,_apo,_t,_ret
		.BYTE	_h,_u,_r,_t,__a,_n,_y,__,_m,_o,_re,__,_p,_e,_o,_p,_le,_dot_dot_dot,_aof,_ret
		.BYTE	_ret
		.BYTE	_Tetsuo,_ddt_,_W,_her,_e_,_i,_s_,_Akira,_que,_exc,_ret
		.BYTE	_ret
		.BYTE	_Kiyoko,_ddt_,_an0,_W,_e,_ll,_dot_dot_dot,_aof,_eol
_scF_msg11:
		.BYTE	_Kei,__,_l,_oo,_k,_ed,__,_o,_ve,_r,__a,_t,__the,__,_k,_id,_s,_col,_ret
		.BYTE	_st,_ar,_ing,__,_b,_l,_an,_k,_l,_y,_dot,_eol
_scF_msg12:
		.BYTE	_Kaneda,_ddt_,_H,_e,_h,_col,__,_it,_apo_s,__a,__,_d,_e,_a,_d_,_r,_at,_dot,_ret
		.BYTE	_M,_u,_st,__,_ha,_ve,__,_p,_i,_c,_k,_ed,__,_it,__,_u,_p,__w,_h,_en,__,_I,_ret
		.BYTE	_d,_o,_ve,__i,_n,_to_,_t,_he,__,_sewer,__,_d,_r,_a,_in,_dot,_eol
_scF_msg13:
		.BYTE	_Colonel,_ddt_,_H,_e,_y,_col,__,_k,_id,_exc,__,_H,_ow,__,_d,_i,_d_,_you,_ret
		.BYTE	_g,_e,_t_,_you,_r,__,_h,_and,_s_,_on,__t,_hat,_que,_exc,_eol
_scF_msg14:
		.BYTE	_Colonel,_ddt_,_W,_hat,_apo,_re,__,_you,__,_d,_o,_ing,_que,_ret
		.BYTE	_H,_u,_r,_r,_y,__,_u,_p,__,_and,__,_c,_a,_p,_t,_u,_re,__,_h,_i,_m,_exc,_eol
_scF_msg15:
		.BYTE	_Colonel,_ddt_,_H,_e,_y,_col,__,_k,_id,_exc,__,_H,_ow,__,_d,_i,_d_,_you,_ret
		.BYTE	_g,_e,_t_,_this,__,_f,_ar,_que,_exc,_eol
_scF_msg16:
		.BYTE	_I_,_t,_r,_i,_ed,__,_to_,_t,_a,_l,_k,__,_to_,_t,_he,__,_k,_id,_dot_dot_dot,_eol
_scF_msg17:
		.BYTE	_But,__the,__,_k,_i,_d_,_w,_ou,_l,_d,_n,_apo,_t,__t,_a,_l,_k,_dot,_eol
_scF_msg18:
		.BYTE	_But,__the,__,_k,_i,_d_,_on,_l,_y,__,_st,_are,_d_,_at,_ret
		.BYTE	_Kei,_col,__,_re,_f,_u,_s,_ing,__,_to_,_an,_s,_w,_er,_dot,_ret
		.BYTE	_ret
		.BYTE	_Kei,_ddt_,_Y,_ou,__,_are,_dot_dot_dot,_eol
_scF_msg19:
		.BYTE	_Kiyoko,_ddt_,_an0,_T,_hat,_apo_s,__,_r,_ight,_dot,_aof,_eol
_scF_msg1A:
		.BYTE	_Kaneda,_ddt_,_an0,_H,_u,_r,_r,_y,__,_u,_p,__,_and,__,_d,_o,__,_it,_col,_ret
		.BYTE	_id,_i,_o,_t,_exc,_aof,_eol
_scF_msg1B:
		.BYTE	_Kaneda,_ddt_,_an0,_W,_hat,_que,__,_W,_h,_o,_apo_s,_ret
		.BYTE	_l,_i,_st,_en,_ing,__,_to_,_you,_col,__a,_n,_y,_w,_a,_y,_que,_aof,_eol
_scF_msg1C:
		.BYTE	_Tetsuo,_ddt_,_an1,_H,_e,_h,_dot_dot_dot,__,_S,_o,__,_you,__,_d,_on,_apo,_t,_ret
		.BYTE	_f,_e,_e,_l,__,_l,_i,_k,_e_,_l,_i,_st,_en,_ing,_dot_dot_dot,_ret
		.BYTE	_A,_re,__,_you,__,_m,_ad,_que,__,_S,_o,__w,_hat,_apo,_ll,__,_you,__,_d,_o,_ret
		.BYTE	_t,_h,_en,_col,__,_Kaneda,_que,_aof,_eol
_scF_msg1D:
		.BYTE	_Tetsuo,_ddt_,_W,_hat,_apo_s,__,_this,_que,__,_I,_s_,_this,_ret
		.BYTE	_p,_ow,_er,__,_re,_a,_ll,_y,__,_m,_in,_e,_que,_exc,_eol
_scF_msg1E:
		.BYTE	_Colonel,_ddt_,_an0,_D,_e,_st,_ro,_y,__,_h,_i,_m,_exc,_aof,_eol
_scF_msg1F:
		.BYTE	_Colonel,_ddt_,_an0,_H,_e,_apo_s,__,_he,_ad,_ed,__,_W,_e,_st,_ret
		.BYTE	_t,_ow,_ar,_d,__the,__,_O,_l,_y,_m,_p,_i,_c,__,_G,_r,_ou,_n,_d,_s,_exc,_ret
		.BYTE	_M,_o,_b,_i,_l,_i,_z,_e_,_a,_ll,__,_u,_n,_it,_s_,_to_,_o,_b,_s,_er,_ve,_ret
		.BYTE	_h,_i,_m,_dot,__,_W,_e,_apo,_re,__g,_o,_ing,__,_to_,_c,_at,_c,_h,__,_h,_i,_m,_exc,_aof,_eol
_scF_msg92:
		.BYTE	_Tetsuo,_ddt_,_an1,_A,_ha,_ha,_ha,_ha,_dot_dot_dot,_aof,_eol

		SECTION_END		FF

