
		SECTION_START	F9

		MSG_START	_scene9_msg_lib
;		MSG_IDX	_sc9_msg00					; unused seems this is a previous version of _sc9_msgB7
		MSG_IDX	_sc9_msg01
		MSG_IDX	_sc9_msg02
		MSG_IDX	_sc9_msg03
		MSG_IDX	_sc9_msg04
		MSG_IDX	_sc9_msg05
		MSG_IDX	_sc9_msg06
		MSG_IDX	_sc9_msg07
		MSG_IDX	_sc9_msg08
		MSG_IDX	_sc9_msg09
		MSG_IDX	_sc9_msg0A
		MSG_IDX	_sc9_msg0B
		MSG_IDX	_sc9_msg0C
		MSG_IDX	_sc9_msg0D
		MSG_IDX	_sc9_msg0E
		MSG_IDX	_sc9_msg0F
		MSG_IDX	_sc9_msg10
		MSG_IDX	_sc9_msg11
		MSG_IDX	_sc9_msg12
		MSG_IDX	_sc9_msg13
		MSG_IDX	_sc9_msg14
		MSG_IDX	_sc9_msg15
		MSG_IDX	_sc9_msg8D					; scene 9 msg
		MSG_IDX	_sc9_msg8E					; scene 9 msg
		MSG_IDX	_sc9_msgAE					; scene 9 msg
		MSG_IDX	_sc9_msgB7					; scene 9 msg
;_sc9_msg00:
;		.BYTE	_I_,_f,_o,_ll,_ow,_ed,__,_her,_col,__,_and,__w,_e_,_en,_d,_ed,_ret
;		.BYTE	_u,_p,__i,_n,__the,__,_b,_a,_se,_me,_n,_t_,_of,__a,_n,__,_o,_l,_d,_ret
;		.BYTE	_building,_dot,_eol
_sc9_msg01:
		.BYTE	_Kaneda,_ddt_,_W,_e,_apo,_re,__,_st,_i,_ll,__,_you,_n,_g,__,_and,_ret
		.BYTE	_I_,_k,_n,_ow,__w,_e_,_c,_an,__,_re,_b,_u,_i,_l,_d_,_ou,_r,_ret
		.BYTE	_re,_l,_at,_i,_on,_s,_h,_i,_p,_dot,__,_S,_o,__,_h,_ow,__a,_b,_ou,_t,_ret
		.BYTE	_w,_e,_dot_dot_dot,_eol
_sc9_msg02:
		.BYTE	_G,_irl,_ddt_,_an0,_Ryu,_exc,_aof,_eol
_sc9_msg03:
		.BYTE	_Kaneda,_ddt_,_H,_e,_y,_col,__,_d,_on,_apo,_t_,_r,_u,_n,__of,_f,_exc,_ret
		.BYTE	_T,_hat,__,_m,_u,_st,_apo,_ve,__,_be,_en,__,_you,_r,__,_f,_i,_r,_st,_ret
		.BYTE	_t,_i,_me,__,_k,_i,_ll,_ing,__s,_o,_me,_on,_e,_dot_dot_dot,_eol
_sc9_msg04:
		.BYTE	_Kaneda,_ddt_,_O,_n,_c,_e_,_you,__,_c,_a,_l,_m,__,_d,_ow,_n,__,_and,_ret
		.BYTE	_c,_le,_ar,__,_you,_r,__,_m,_in,_d,_col,__,_m,_a,_y,_be,__w,_e_,_c,_an,_ret
		.BYTE	_g,_r,_a,_b,__a,__,_b,_it,_e_,_to_,_e,_at,_dot_dot_dot,_eol
_sc9_msg05:
		.BYTE	_Kaneda,_ddt_,_D,_on,_apo,_t_,_st,_re,_s,_s_,_o,_ve,_r,__,_it,_dot,_ret
		.BYTE	_W,_hat,_apo_s,__,_d,_on,_e_,_i,_s_,_d,_on,_e,_dot,_ret
		.BYTE	_C,_an,_apo,_t_,_c,_h,_an,_g,_e_,_it,_dot,_eol
_sc9_msg06:
		.BYTE	_Terrorist,_ddt_,_an0,_W,_h,_o,_apo,_re,__,_you,_que,_exc,_aof,_ret
		.BYTE	_ret
		.BYTE	_Ryu,_ddt_,_an1,_Kei,_que,_exc,_aof,_ret
		.BYTE	_ret
		.BYTE	_Kei,_ddt_,_Ryu,_col,__,_you,_apo,_re,__s,_a,_f,_e,_exc,_eol
_sc9_msg07:
		.BYTE	_T,_his,__,_m,_an,__,_se,_e,_m,_s_,_to_,_be,__,_Ryu,_dot,_eol
_sc9_msg08:
		.BYTE	_The,_y,__,_l,_oo,_k,__,_l,_i,_k,_e,__the,_y,_apo,_ve,__,_se,_en,__a,_ret
		.BYTE	_l,_o,_t_,_of,__,_b,_l,_oo,_d,_dot,_eol
_sc9_msg09:
		.BYTE	_Terrorist,_ddt_,_an0,_W,_h,_o,__g,_o,_e,_s,__the,_re,_exc,_aof,_eol
_sc9_msg0A:
		.BYTE	_S,_o,__s,_he,_apo_s,__,_Kei,_dot_dot_dot,__,_H,_a,_col,__,_f,_ou,_n,_d_,_ou,_t,_ret
		.BYTE	_her,__,_n,_a,_me,_dot,__,_D,_on,_apo,_t_,_k,_n,_ow,__w,_h,_o,__,_her,_ret
		.BYTE	_f,_r,_i,_en,_d,_s_,_are,_col,__,_b,_u,_t,__s,_he,__,_se,_e,_m,_s,__t,_o,_ret
		.BYTE	_k,_n,_ow,__,_this,__,_o,_l,_d_,_g,_u,_y,_dot,_eol
_sc9_msg0B:
		.BYTE	_Terrorist,_ddt_,_an0,_A,__s,_p,_y,_que,_exc,_aof,_eol
_sc9_msg0C:
		.BYTE	_Kaneda,_ddt_,_A,_c,_t,_u,_a,_ll,_y,_col,__,_Kei,__,_was,_ret
		.BYTE	_t,_r,_a,_p,_p,_ed,__i,_n,__the,__,_sewer,_s_,_b,_y,__the,_ret
		.BYTE	_Army,_dot_dot_dot,__,_I_,_s,_a,_v,_ed,__,_her,_dot,__,_D,_on,_apo,_t_,_I,_ret
		.BYTE	_d,_e,_s,_er,_ve,__s,_o,_me,__t,_h,_an,_k,_s,_que,_eol
_sc9_msg0D:
		.BYTE	_Kaneda,_ddt_,_M,_e,_que,__,_W,_e,_ll,_dot_dot_dot,__,_u,_h,_col,__,_h,_ow,__t,_o,_ret
		.BYTE	_s,_a,_y,__,_this,_dot_dot_dot,__,_I_apo,_m,__,_Kei,_apo_s,_ret
		.BYTE	_b,_o,_y,_f,_r,_i,_en,_d,_dot,__,_W,_e,_ll,_col,__t,_hat,__,_m,_ight,__,_be,_ret
		.BYTE	_p,_u,_s,_h,_ing,__,_it,_dot_dot_dot,_eol
_sc9_msg0E:
		.BYTE	_Kaneda,_ddt_,_Kei,_col,__w,_h,_o,_apo,_re,__the,_se,_ret
		.BYTE	_s,_c,_ar,_y,__,_o,_l,_d_,_g,_u,_y,_s,_que,_eol
_sc9_msg0F:
		.BYTE	_Kei,_ddt_,_It_apo_s,__t,_r,_u,_e,_dot_dot_dot,__,_The,_re,_apo_s,__,_n,_o,_ret
		.BYTE	_w,_a,_y,__,_this,__g,_u,_y,_apo_s,__a,__s,_p,_y,_dot,_eol
_sc9_msg10:
		.BYTE	_Kei,_ddt_,_Y,_ou,__,_d,_on,_apo,_t_,_k,_n,_ow,__,_me,_exc,_eol
_sc9_msg11:
		.BYTE	_It_apo_s,__the,__g,_u,_y,__,_I_,_s,_a,_w,__,_on,__the,_ret
		.BYTE	_w,_a,_l,_k,_w,_a,_y,_dot,_eol
_sc9_msg12:
		.BYTE	_Kaneda,_ddt_,_H,_on,_e,_st,_l,_y,_que,__,_I_apo,_m,__a,_n,__,_Army,_ret
		.BYTE	_s,_p,_y,__s,_en,_t_,_to_,_f,_in,_d_,_ou,_t,__a,_ll,__,_you,_r,_ret
		.BYTE	_p,_l,_an,_s,_dot_dot_dot,_eol
_sc9_msg13:
		.BYTE	_T,_his,__,_l,_oo,_k,_s_,_l,_i,_k,_e,__the,_ret
		.BYTE	_Terrorist,_s,_apo,__,_b,_a,_se,_dot,_eol
_sc9_msg14:
		.BYTE	_G,_irl,_ddt_,_an0,_dot_dot_dot,_Ryu,_col,__w,_her,_e_,_are,__,_you,_que,_aof,_eol
_sc9_msg15:
		.BYTE	_Kaneda,_ddt_,_A,_h,_col,__,_b,_u,_t,_dot_dot_dot,__w,_e_,_ha,_ve,_n,_apo,_t,_ret
		.BYTE	_ha,_d_,_se,_x,__,_y,_e,_t,_col,__,_y,_apo,_k,_n,_ow,_que,_eol
_sc9_msg8D:
		.BYTE	_Kaneda,_ddt_,_H,_e,_y,__,_n,_ow,_dot_dot_dot,_eol
_sc9_msg8E:
		.BYTE	_Terrorist,_ddt_,_an0,_W,_hat,_apo,_d_,_you,__s,_a,_y,_que,_exc,_aof,_eol
_sc9_msgAE:
		.BYTE	_B,_an,_g,_exc,_ret
		.BYTE	_ret
		.BYTE	_The,__,_Terrorist,__,_f,_i,_r,_ed,__,_his,__g,_u,_n,_dot,_eol
_sc9_msgB7:
		.BYTE	_W,_e_,_s,_o,_me,_h,_ow,__,_m,_an,_a,_g,_ed,__,_to_,_a,_v,_o,_id,_ret
		.BYTE	_t,_he,__,_Army,__g,_u,_y,_s,_dot,__,_A,_n,_d,_col,__,_with,__,_her,_ret
		.BYTE	_le,_ad,_ing,__the,__w,_a,_y,_col,__w,_e_,_c,_a,_me,__t,_o,_ret
		.BYTE	_this,__,_p,_l,_a,_c,_e,_dot,_eol

		SECTION_END		F9
