
		SECTION_START	F3

		MSG_START	_scene3_msg_lib
		MSG_IDX	_sc3_msg00
		MSG_IDX	_sc3_msg01
		MSG_IDX	_sc3_msg02
		MSG_IDX	_sc3_msg03
		MSG_IDX	_sc3_msg04
		MSG_IDX	_sc3_msg05
		MSG_IDX	_sc3_msg06
		MSG_IDX	_sc3_msg07
;		.WORD	0									; dummy
		MSG_IDX	_sc3_msg09
_sc3_msg00:
		.BYTE	_I_,_m,_an,_a,_g,_ed,__,_to_,_g,_e,_t_,_her,__,_ou,_t,_exc,_eol
_sc3_msg01:
		.BYTE	_Kaneda,_ddt_,_an0,_M,_a,_y,_be,__w,_e_,_c,_ou,_l,_d_,_g,_o,__,_for,_ret
		.BYTE	_d,_r,_in,_k,_s,__s,_o,_me,_w,_her,_e_,_around,__,_her,_e,_dot,_ret
		.BYTE	_A,_n,_d_,_I_,_t,_h,_ou,_g,_h,_t,__t,_hat,__w,_e_,_c,_ou,_l,_d,_ret
		.BYTE	_t,_a,_l,_k,__a,_b,_ou,_t,__t,_hat,__w,_h,_o,_le,_ret
		.BYTE	_bra,_re,_v,_o,_l,_u,_t,_i,_on,_bra,__t,_h,_ing,_dot,_aof,_eol
_sc3_msg02:
		.BYTE	_G,_irl,_ddt_,_an1,_I_,_t,_h,_in,_k,__,_you,_apo,_re,__a,__s,_k,_i,_r,_t,_ret
		.BYTE	_c,_ha,_s,_er,__w,_h,_o,_apo,_ll,__t,_r,_y,__a,_n,_y,_t,_h,_ing,__,_he,_ret
		.BYTE	_c,_an,_dot,__,_Y,_ou,_apo,_ll,__,_he,_l,_p,__a,_n,_y,_on,_e,_col,__s,_o,_ret
		.BYTE	_l,_on,_g,__a,_s_,_it,_apo_s,__a,__g,_irl,_col,__,_r,_ight,_que,_aof,_eol
_sc3_msg03:
		.BYTE	_Kaneda,_ddt_,_an0,_You_apo_re,__w,_r,_on,_g,_exc,__,_I_,_ha,_ve,_ret
		.BYTE	_ve,_r,_y,__,_h,_i,_g,_h,__,_st,_and,_ar,_d,_s,_col,__,_you,__,_k,_n,_ow,_dot,_ret
		.BYTE	_It_apo_s,__,_n,_o,_t,__the,_i,_r,__,_l,_oo,_k,_s,__t,_hat,_ret
		.BYTE	_c,_ou,_n,_t,_col,__,_it,_apo_s,__the,_i,_r,__s,_en,_s,_it,_i,_v,_it,_y,_dot,_aof,_eol
_sc3_msg04:
		.BYTE	_G,_irl,_ddt_,_an1,_I_,_s,_u,_p,_p,_o,_se,__,_I_,_ow,_e_,_you,__,_on,_e,_dot,_ret
		.BYTE	_T,_h,_an,_k,__,_you,__,_ve,_r,_y,__,_m,_u,_c,_h,_col,__,_u,_h,_dot_dot_dot,_aof,_eol
_sc3_msg05:
		.BYTE	_Kaneda,_ddt_,_an0,_I_apo,_m,__,_Kaneda,_dot,__,_N,_i,_c,_e_,_t,_o,_ret
		.BYTE	_me,_e,_t_,_you,_dot,_aof,_eol
_sc3_msg06:
		.BYTE	_G,_irl,_ddt_,_an1,_G,_oo,_d,_b,_y,_e,_col,__,_Kaneda,_dot,_aof,_eol
_sc3_msg07:
		.BYTE	_Kaneda,_ddt_,_an0,_H,_o,_l,_d_,_on,_exc,__,_I_apo,_m,__the,__g,_u,_y,_ret
		.BYTE	_t,_hat,__s,_a,_v,_ed,__,_you,__,_b,_a,_c,_k,__the,_re,_exc,__,_Y,_ou,_ret
		.BYTE	_c,_ou,_l,_d_,_a,_t_,_le,_a,_st,__t,_e,_ll,__,_me,__,_you,_r,_ret
		.BYTE	_n,_a,_me,_col,__,_you,__,_c,_o,_l,_d_,_b,_it,_c,_h,_exc,_aof,_eol
_sc3_msg09:
		.BYTE	_S,_e,_e,_m,_s,__the,__,_st,_u,_p,_i,_d_,_Army,__,_f,_a,_i,_l,_ed,_ret
		.BYTE	_a,_t_,_h,_and,_l,_ing,__the,__g,_re,_n,_ad,_e,_dot,_eol

		SECTION_END		F3
