
		SECTION_START	FB

		MSG_START	_sceneB_msg_lib
		MSG_IDX	_scB_msg00
		MSG_IDX	_scB_msg01
		MSG_IDX	_scB_msg02
		MSG_IDX	_scB_msg03
;		MSG_IDX	_scB_msg04				; unused
		MSG_IDX	_scB_msg05
		MSG_IDX	_scB_msg06
		MSG_IDX	_scB_msg07
		MSG_IDX	_scB_msg08
		MSG_IDX	_scB_msg09
		MSG_IDX	_scB_msg0A
		MSG_IDX	_scB_msg0B
		MSG_IDX	_scB_msg0C
		MSG_IDX	_scB_msg0D
		MSG_IDX	_scB_msg0E
		MSG_IDX	_scB_msg0F
		MSG_IDX	_scB_msg10
		MSG_IDX	_scB_msg11
		MSG_IDX	_scB_msg12
		MSG_IDX	_scB_msg13
_scB_msg00:
		.BYTE	_The,_y,__,_p,_u,_ll,_ed,__,_me,__,_ou,_t_,_of,__the,_ret
		.BYTE	_a,_i,_r,__,_d,_u,_c,_t,_dot,_eol
_scB_msg01:
		.BYTE	_Kaneda,_ddt_,_O,_w,_col,__,_ow,_col,__,_ow,_exc,__,_W,_hat,_apo,_re,_ret
		.BYTE	_you,__,_d,_o,_ing,__t,_hat,__,_for,_que,_eol
_scB_msg02:
		.BYTE	_Kei,_ddt_,_Kaneda,_dot_dot_dot,_eol
_scB_msg03:
		.BYTE	_Kaneda,_ddt_,_W,_a,_it,__a,__,_se,_c,_dot_dot_dot,__,_P,_le,_a,_se,_exc,_ret
		.BYTE	_L,_i,_st,_en,__,_to_,_w,_hat,__,_I_,_ha,_ve,__,_to_,_s,_a,_y,_dot,_eol
;_scB_msg04:
;		.BYTE	_Kei,_ddt_,_an2,_H,_e_,_s,_a,_v,_ed,__,_m,_y,__,_l,_i,_f,_e,_exc,_aof,_ret
;		.BYTE	_ret
;		.BYTE	_Kaneda,_ddt_,_T,_w,_i,_c,_e,_exc,_ret
;		.BYTE	_ret
;		.BYTE	_Ryu,_ddt_,_an1,_T,_hat,__,_c,_ou,_l,_d,_apo,_ve,__,_be,_en,__,_j,_u,_st,_ret
;		.BYTE	_to_,_s,_p,_y,__,_on,__,_u,_s,_dot,_aof,_eol
_scB_msg05:
		.BYTE	_Kaneda,_ddt_,_M,_y,__,_f,_r,_i,_en,_d_,_was,__i,_n,__t,_hat,_ret
		.BYTE	_in,_c,_id,_en,_t,__i,_n,__the,__,_O,_l,_d_,_T,_ow,_n,_exc,__,_Y,_ou,_ret
		.BYTE	_p,_ro,_b,_a,_b,_l,_y,__,_d,_on,_apo,_t_,_be,_l,_i,_e,_ve,__,_me,_col,__,_b,_u,_t,_ret
		.BYTE	_it,_apo_s,__t,_r,_u,_e,_dot,__,_I_,_was,__,_with,__,_h,_i,_m,_exc,_ret
		.BYTE	_I_,_s,_a,_w,__the,__w,_h,_o,_le,__t,_h,_ing,_exc,_eol
_scB_msg06:
		.BYTE	_Kaneda,_ddt_,_P,_le,_a,_se,__t,_a,_k,_e_,_me,__,_with,_ret
		.BYTE	_you,__,_to_,_t,_he,__,_l,_a,_b,_dot,_eol
_scB_msg07:
		.BYTE	_Kaneda,_ddt_,_It_apo_s,__a,__,_l,_it,_t,_le,_ret
		.BYTE	_e,_m,_b,_ar,_r,_a,_s,_s,_ing,__,_to_,_a,_s,_k,_dot_dot_dot,_eol
_scB_msg08:
		.BYTE	_Ryu,_ddt_,_an1,_W,_hat,_que,_exc,__,_Y,_ou,__,_k,_n,_ow,__a,_b,_ou,_t,_ret
		.BYTE	_t,_hat,_que,_aof,_eol
_scB_msg09:
		.BYTE	_Kei,__s,_a,_v,_ed,__,_me,__,_with,__,_b,_u,_t,__a,__s,_ing,_le,_ret
		.BYTE	_w,_or,_d,_col,__,_and,__t,_oo,_k,__,_me,__,_to_,_t,_he,_i,_r,_ret
		.BYTE	_ro,_o,_m,_dot,__,_The,_y,__,_were_,_ha,_v,_ing,__s,_o,_me,_ret
		.BYTE	_k,_in,_d_,_of,__,_d,_i,_s,_c,_u,_s,_s,_i,_on,_dot,_eol
_scB_msg0A:
		.BYTE	_Ryu,_ddt_,_an1,_R,_ight,_col,__,_you,__,_c,_o,_me,__,_with,__,_u,_s,_dot,_ret
		.BYTE	_H,_e,_re,_apo_s,__the,__,_p,_a,_s,_s_,_to_,_t,_he,__,_l,_a,_b,_dot,_aof,_eol
_scB_msg0B:
		.BYTE	_K,_n,_ow,_ing,__,_Kei,_col,__s,_he,__,_d,_id,_n,_apo,_t,__t,_e,_ll,_ret
		.BYTE	_t,_he,_m,__a,_b,_ou,_t_,_u,_s,_dot,_eol
_scB_msg0C:
		.BYTE	_Kaneda,_ddt_,_The,_y,_apo,_re,__t,_a,_l,_k,_ing,__a,_b,_ou,_t,_ret
		.BYTE	_Tetsuo,_dot,_eol
_scB_msg0D:
		.BYTE	_The,__w,_r,_in,_k,_l,_y,__,_k,_id,__t,_hat,__,_n,_ight,_que,_ret
		.BYTE	_T,_hat,__,_was,__,_f,_ro,_m,__,_be,_ing,__a,_n,_ret
		.BYTE	_e,_x,_p,_er,_i,_me,_n,_t,_que,__,_I,_f,__,_Tetsuo,_apo_s,__a,_t,__the,_ret
		.BYTE	_l,_a,_b,__t,_oo,_col,__the,_n,_dot_dot_dot,_eol
_scB_msg0E:
		.BYTE	_I_apo,_m,__,_c,_o,_m,_ing,_col,__,_Tetsuo,_exc,_eol
_scB_msg0F:
		.BYTE	_Terrorist,_ddt_,_an0,_The,__,_Army,__,_se,_e,_m,_s,__t,_o,_ret
		.BYTE	_be,__w,_or,_k,_ing,__,_to_,_p,_ro,_t,_e,_c,_t_,_h,_u,_m,_an,_ret
		.BYTE	_e,_x,_p,_er,_i,_me,_n,_t,_at,_i,_on,_dot,_aof,_eol
_scB_msg10:
		.BYTE	_Terrorist,_ddt_,_an0,_W,_e_,_s,_h,_ou,_l,_d_,_be,__a,_b,_le,_ret
		.BYTE	_to_,_s,_n,_e,_a,_k,__i,_n,_to_,_t,_he,__,_l,_a,_b,__,_u,_s,_ing,_ret
		.BYTE	_t,_hat,__,_p,_a,_s,_s,_dot,_aof,_eol
_scB_msg11:
		.BYTE	_Terrorist,_ddt_,_an0,_P,_e,_o,_p,_le,__,_d,_on,_apo,_t,_ret
		.BYTE	_k,_n,_ow,__w,_hat,__the,_i,_r,__,_h,_i,_g,_h,__t,_a,_x,_e,_s_,_are,_ret
		.BYTE	_u,_s,_ed,__,_for,_dot,__,_I,_f,__w,_e_,_f,_ou,_n,_d_,_p,_ro,_of,_ret
		.BYTE	_t,_he,_y,_apo,_re,__,_p,_u,_t,_t,_ing,__,_it,__t,_ow,_ar,_d,_ret
		.BYTE	_t,_he,_se,__,_l,_a,_b,_s,_dot_dot_dot,_aof,_eol
_scB_msg12:
		.BYTE	_Terrorist,_ddt_,_an0,_Y,_ou,__,_l,_it,_t,_le,__s,_h,_it,_exc,_ret
		.BYTE	_Y,_ou,__,_re,_a,_ll,_y,__,_are,__a,__s,_p,_y,_exc,_aof,_eol
_scB_msg13:
		.BYTE	_Kei,_ddt_,_an2,_H,_ow,__,_d,_i,_d_,_you,__,_e,_ve,_n,__,_ha,_ve,_ret
		.BYTE	_a,__,_c,_a,_me,_r,_a,_que,_aof,_eol

		SECTION_END		FB
