
		SECTION_START	F13

		MSG_START	_scene13_msg_lib
		MSG_IDX	_sc13_msg00
		MSG_IDX	_sc13_msg01
		MSG_IDX	_sc13_msg02
		MSG_IDX	_sc13_msg03
		MSG_IDX	_sc13_msg04
		MSG_IDX	_sc13_msg05
		MSG_IDX	_sc13_msg06
		MSG_IDX	_sc13_msg07
		MSG_IDX	_sc13_msg08
		MSG_IDX	_sc13_msg09
		MSG_IDX	_sc13_msg0A
		MSG_IDX	_sc13_msg0B
		MSG_IDX	_sc13_msg0C
		MSG_IDX	_sc13_msg0D
		MSG_IDX	_sc13_msg0E
		MSG_IDX	_sc13_msg0F
		MSG_IDX	_sc13_msg10
		MSG_IDX	_sc13_msg11
		MSG_IDX	_sc13_msg12
		MSG_IDX	_sc13_msg13
		MSG_IDX	_sc13_msg14
		MSG_IDX	_sc13_msg15
		MSG_IDX	_sc13_msg16
		MSG_IDX	_sc13_msg17
		MSG_IDX	_sc13_msg18
		MSG_IDX	_sc13_msg19
		MSG_IDX	_sc13_msg1A
		MSG_IDX	_sc13_msg1B
		MSG_IDX	_sc13_msg1C
		MSG_IDX	_sc13_msg1D
		MSG_IDX	_sc13_msg1E
		MSG_IDX	_sc13_msg1F
		MSG_IDX	_sc13_msg20
		MSG_IDX	_sc13_msg21
		MSG_IDX	_sc13_msg22
		MSG_IDX	_sc13_msg23
		MSG_IDX	_sc13_msg24
		MSG_IDX	_sc13_msg25
		MSG_IDX	_sc13_msg26
		MSG_IDX	_sc13_msg27
		MSG_IDX	_sc13_msg28
		MSG_IDX	_sc13_msg29
		MSG_IDX	_sc13_msg2A
		MSG_IDX	_sc13_msg2B
		MSG_IDX	_sc13_msg2C
		MSG_IDX	_sc13_msg2D
		MSG_IDX	_sc13_msg2E
_sc13_msg00:
		.BYTE	_I_,_c,_l,_i,_m,_b,_ed,__the,__,_m,_ou,_n,_t,_a,_in,__of,_ret
		.BYTE	_r,_u,_b,_b,_le,_col,__,_and,__,_f,_ou,_n,_d_,_Tetsuo,_dot,_ret
		.BYTE	_ret
		.BYTE	_Tetsuo,_ddt_,_an0,_A,_ha,_ha,_dot_dot_dot,_aof,_eol
_sc13_msg01:
		.BYTE	_Kaneda,_ddt_,_an0,_I,_s,__the,_re,__s,_o,_me,__,_k,_in,_d,_ret
		.BYTE	_of,__t,_r,_ou,_b,_le,__,_her,_e,_que,_aof,_ret
		.BYTE	_ret
		.BYTE	_Tetsuo,_ddt_,_an1,_A,_h,_h,_dot_dot_dot,__,_it,_apo_s,__a,_ll,_ret
		.BYTE	_f,_in,_i,_s,_h,_ed,__,_n,_ow,_dot,__,_The,_re,__,_m,_ight,__,_be,__a,_ret
		.BYTE	_b,_it,__,_m,_o,_re,__s,_o,_on,_col,__t,_h,_ou,_g,_h,_dot,_aof,_eol
_sc13_msg02:
		.BYTE	_Kaneda,_ddt_,_an0,_I_,_was,__,_st,_i,_ll,__w,_or,_r,_i,_ed,_ret
		.BYTE	_a,_b,_ou,_t_,_you,_dot_dot_dot,__,_T,_h,_ou,_g,_h,_t_,_you,__,_m,_ight,_ret
		.BYTE	_g,_e,_t,__i,_n,__t,_r,_ou,_b,_le,__,_and,__,_c,_r,_y,__,_l,_i,_k,_e_,_a,_ret
		.BYTE	_b,_a,_b,_y,_dot,_aof,_eol
_sc13_msg03:
		.BYTE	_Tetsuo,_ddt_,_an1,_Kaneda,_dot_dot_dot,__,_Man,_col,__,_ha,_ve,_ret
		.BYTE	_you,__,_be,_en,__a,__,_p,_a,_in,_dot,__,_E,_ve,_r,__s,_in,_c,_e_,_w,_e,_ret
		.BYTE	_were_,_k,_id,_s,_col,__,_you,_apo,_ve,__,_be,_en,_ret
		.BYTE	_or,_d,_er,_ing,__,_me,__,_around,_dot,__,_A,_l,_w,_a,_y,_s,_ret
		.BYTE	_t,_e,_ll,_ing,__,_me,__w,_hat,__,_to_,_d,_o,_dot,__,_B,_e,_ing,_ret
		.BYTE	_t,_he,__,_b,_o,_s,_s,__a,_ll,__the,__t,_i,_me,_dot,_aof,_eol
_sc13_msg04:
		.BYTE	_Kaneda,_ddt_,_an0,_N,_ow,__,_it,__,_l,_oo,_k,_s_,_l,_i,_k,_e,_ret
		.BYTE	_you,_apo,_ve,__,_be,_c,_o,_me,__a,__,_b,_o,_s,_s,_col,__t,_oo,_dot,__,_The,_ret
		.BYTE	_b,_o,_s,_s_,_of,__,_this,__,_p,_i,_le,__of,__t,_r,_a,_s,_h,_exc,_aof,_ret
		.BYTE	_ret
		.BYTE	_Tetsuo,_ddt_,_an1,_Kaneda,_dot_dot_dot,_exc,_aof,_eol
_sc13_msg05:
		.BYTE	_The,__,_laser,__,_I_,_f,_i,_r,_ed,__,_h,_it,__the,_ret
		.BYTE	_s,_a,_m,_p,_le,__,_c,_a,_se,_dot,_eol
_sc13_msg06:
		.BYTE	_A,_s_,_I_,_f,_i,_r,_ed,_col,__,_I_,_t,_r,_i,_p,_p,_ed,__,_on,__a,_ret
		.BYTE	_p,_i,_e,_c,_e_,_of,__,_r,_u,_b,_b,_le,_dot,_eol
_sc13_msg07:
		.BYTE	_Kaneda,__,_j,_u,_m,_p,_ed,__a,_t_,_Tetsuo,_col,__,_b,_u,_t,_ret
		.BYTE	_was,__,_h,_it,__,_b,_y,__the,__s,_h,_o,_c,_k,__w,_a,_ve,_dot_dot_dot,_eol
_sc13_msg08:
		.BYTE	_Tetsuo,_ddt_,_an1,_It_apo_s,__,_n,_o,_t,__s,_o,__,_b,_a,_d_,_this,_ret
		.BYTE	_w,_a,_y,_dot_dot_dot,_ret
		.BYTE	_Kaneda,_dot_dot_dot,_ret
		.BYTE	_N,_ow,__,_I_,_u,_n,_d,_er,_st,_and,__the,__,_me,_an,_ing,_ret
		.BYTE	_of,__,_re,_g,_re,_t,_dot_dot_dot,_aof,_eol
_sc13_msg09:
		.BYTE	_The,_n,_col,__a,_s_,_Tetsuo,__,_was,__g,_e,_t,_t,_ing,_ret
		.BYTE	_b,_a,_c,_k,__,_u,_p,_col,__,_his,__,_r,_ight,__a,_r,_m,__,_was,_ret
		.BYTE	_se,_ve,_r,_ed,__,_b,_y,__the,__,_be,_a,_m,_dot,_eol
_sc13_msg0A:
		.BYTE	_B,_s,_s,_h,_exc,_ret
		.BYTE	_ret
		.BYTE	_Tetsuo,__s,_u,_d,_d,_en,_l,_y,__,_se,_t_,_u,_p,__a,_ret
		.BYTE	_b,_ar,_r,_i,_er,_dot,_eol
_sc13_msg0B:
		.BYTE	_Tetsuo,__,_j,_u,_m,_p,_ed,__,_u,_p,_col,__,_le,_a,_v,_ing,__the,_ret
		.BYTE	_at,_m,_o,_s,_p,_her,_e,_dot,__,_Tetsuo,__,_ha,_d_,_le,_f,_t,__t,_o,_ret
		.BYTE	_d,_e,_st,_ro,_y,__the,__,_S,_O,_L,__s,_at,_e,_ll,_it,_e,_dot,_eol
_sc13_msg0C:
		.BYTE	_Kaneda,_ddt_,_G,_o,_t_,_apo,_i,_m,_dot_dot_dot,__,_But,__,_he,__,_was,_ret
		.BYTE	_a,_b,_le,__,_to_,_p,_u,_t_,_u,_p,__t,_hat,__,_b,_ar,_r,_i,_er,_col,_ret
		.BYTE	_s,_o,__,_he,__,_m,_u,_st,__,_st,_i,_ll,__,_ha,_ve,__s,_o,_me,_ret
		.BYTE	_l,_i,_f,_e_,_in,__,_h,_i,_m,_dot_dot_dot,_eol
_sc13_msg0D:
		.BYTE	_I_,_f,_i,_r,_ed,__the,__,_laser,_col,__,_b,_u,_t_,_it,_ret
		.BYTE	_d,_id,_n,_apo,_t_,_re,_a,_c,_h,__,_Tetsuo,_dot_dot_dot,_eol
_sc13_msg0E:
		.BYTE	_Kaneda,_ddt_,_H,_u,_h,_que,__,_It_apo_s,__,_d,_e,_ad,_que,_exc,_ret
		.BYTE	_ret
		.BYTE	_Tetsuo,_ddt_,_W,_hat,_apo_s,__w,_r,_on,_g,_col,_ret
		.BYTE	_Kaneda,_dot_dot_dot,_que,_eol
_sc13_msg0F:
		.BYTE	_Kaneda,_ddt_,_an0,_D,_a,_m,_m,_it,_exc,__,_T,_hat,_apo_s,__,_d,_i,_r,_t,_y,_col,_ret
		.BYTE	_Tetsuo,_exc,__,_L,_e,_t,_apo_s,__,_ha,_ve,__a,__,_f,_a,_i,_r,_ret
		.BYTE	_f,_ight,_exc,_aof,_eol
_sc13_msg10:
		.BYTE	_Tetsuo,_apo_s,__s,_u,_r,_r,_ou,_n,_d,_ing,_s_,_be,_g,_an,__t,_o,_ret
		.BYTE	_g,_l,_ow,_col,__,_and,__g,_r,_ad,_u,_a,_ll,_y,__s,_h,_on,_e,_ret
		.BYTE	_b,_r,_ight,_l,_y,_dot,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_H,_u,_h,_dot_dot_dot,_que,_eol
_sc13_msg11:
		.BYTE	_I,_t_,_was,__the,__,_laser,__,_be,_a,_m,__,_f,_i,_r,_ed,_ret
		.BYTE	_f,_ro,_m,__,_S,_O,_L,__,_on,__the,__,_or,_d,_er,_s_,_of,__the,_ret
		.BYTE	_Colonel,_dot,_eol
_sc13_msg12:
		.BYTE	_C,_on,_f,_u,_s,_ed,_col,__,_I_,_be,_g,_an,__,_to_,_r,_u,_n,__a,_w,_a,_y,_dot,_ret
		.BYTE	_The,__,_r,_u,_b,_b,_le,__,_around,__,_me,__s,_h,_oo,_k,_ret
		.BYTE	_v,_i,_o,_le,_n,_t,_l,_y,_dot,_eol
_sc13_msg13:
		.BYTE	_Tetsuo,__,_d,_re,_w,__,_u,_p,__the,__,_m,_ou,_n,_t,_a,_in,__of,_ret
		.BYTE	_r,_u,_b,_b,_le,_dot,_eol
_sc13_msg14:
		.BYTE	_Kaneda,_ddt_,_W,_h,_o,_a,_col,__,_Tetsuo,_dot_dot_dot,_ret
		.BYTE	_ret
		.BYTE	_I_,_l,_i,_f,_t,_ed,__,_on,_e_,_of,__the,__,_ro,_c,_k,_s_,_and,_ret
		.BYTE	_t,_h,_re,_w,__,_it,__a,_t_,_Tetsuo,_dot,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_U,_n,_f,_exc,_eol
_sc13_msg15:
		.BYTE	_A,_g,_a,_in,_col,__the,__,_l,_ight,__,_be,_g,_an,__t,_o,_ret
		.BYTE	_g,_at,_her,_dot,__,_E,_ve,_r,_y,_t,_h,_ing,__i,_n,__,_v,_i,_e,_w,_ret
		.BYTE	_s,_h,_on,_e_,_a,__,_b,_r,_ight,__w,_h,_it,_e,_dot,_eol
_sc13_msg16:
		.BYTE	_W,_h,_en,__,_I_,_o,_p,_en,_ed,__,_m,_y,__,_e,_y,_e,_s,_col,__,_r,_u,_b,_b,_le,_ret
		.BYTE	_was,__,_f,_l,_o,_at,_ing,__i,_n,__the,__a,_i,_r,_dot,_ret
		.BYTE	_Tetsuo,__,_ha,_d_,_se,_t_,_u,_p,__a,__,_b,_ar,_r,_i,_er,_col,_ret
		.BYTE	_and,__,_d,_i,_s,_p,_er,_s,_ed,__the,__,_be,_a,_m,_dot,_eol
_sc13_msg17:
		.BYTE	_Tetsuo,_ddt_,_Damn,_dot_dot_dot,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_W,_hat,__i,_s_,_it,_que,_eol
_sc13_msg18:
		.BYTE	_Kaneda,_ddt_,_O,_w,_dot,_ret
		.BYTE	_ret
		.BYTE	_The,__,_b,_ar,_r,_i,_er,__of,__,_r,_u,_b,_b,_le,__,_h,_ad,_ret
		.BYTE	_f,_a,_l,_le,_n,_dot,_eol
_sc13_msg19:
		.BYTE	_Z,_a,_p,_exc,__,_F,_s,_s,_h,_t,_exc,_ret
		.BYTE	_ret
		.BYTE	_But,__,_before,__,_I_,_e,_ve,_n,__,_n,_o,_t,_i,_c,_ed,_col,__the,_ret
		.BYTE	_r,_u,_b,_b,_le,__,_ha,_d_,_be,_en,__,_d,_e,_st,_ro,_y,_ed,__,_b,_y,_ret
		.BYTE	_a,__,_be,_a,_m,_dot,_eol
_sc13_msg1A:
		.BYTE	_The,__,_be,_a,_m,__,_ha,_d_,_c,_o,_me,__i,_n,_c,_r,_ed,_i,_b,_l,_y,_ret
		.BYTE	_c,_l,_o,_se,__a,_l,_re,_ad,_y,_dot,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_S,_a,_ve,__,_me,_col,__,_Kei,_exc,_eol
_sc13_msg1B:
		.BYTE	_T,_h,_r,_ou,_g,_h,__the,__s,_ou,_n,_d_,_of,__the,_ret
		.BYTE	_e,_x,_p,_l,_o,_s,_i,_on,_col,__,_I_,_c,_ou,_l,_d_,_he,_ar,_ret
		.BYTE	_Kai,_apo_s,__s,_c,_re,_a,_m,_dot,_eol
_sc13_msg1C:
		.BYTE	_Kei,__,_was,__,_on,__,_Kai,_apo_s,__,_b,_i,_k,_e_,_and,_ret
		.BYTE	_t,_he,_y,__,_c,_a,_me,__,_u,_p,__i,_n,__,_f,_r,_on,_t_,_of,__,_me,_dot,_eol
_sc13_msg1D:
		.BYTE	_Kaneda,_ddt_,_Kai,_exc,__,_Kei,_exc,_eol
_sc13_msg1E:
		.BYTE	_Kaneda,_ddt_,_The,_re,_apo_s,__,_n,_o,__,_ro,_o,_m,_dot_dot_dot,_ret
		.BYTE	_ret
		.BYTE	_Kei,_ddt_,_C,_o,_me,__,_on,_col,__,_q,_u,_i,_c,_k,_exc,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_U,_h,_col,__,_O,_k,_dot_dot_dot,_eol
_sc13_msg1F:
		.BYTE	_Kaneda,_ddt_,_an0,_H,_e,_y,_col,__w,_at,_c,_h,__,_it,_exc,__,_It_apo_s,_ret
		.BYTE	_ro,_c,_k,_y,__,_around,__,_her,_e,_exc,_aof,_ret
		.BYTE	_ret
		.BYTE	_Tetsuo,_ddt_,_an1,_D,_i,_e,_dot_dot_dot,_aof,_eol
_sc13_msg20:
		.BYTE	_I_,_d,_u,_c,_k,_ed,__i,_n,__,_be,_t,_w,_e,_en,__the,_ret
		.BYTE	_r,_u,_b,_b,_le,_dot,_eol
_sc13_msg21:
		.BYTE	_Z,_a,_p,_exc,_ret
		.BYTE	_ret
		.BYTE	_The,__,_be,_a,_m,__,_h,_it,__,_Kaneda,__,_d,_i,_re,_c,_t,_l,_y,_dot,_eol
_sc13_msg22:
		.BYTE	_Kaneda,_ddt_,_W,_on,_d,_er,__,_h,_ow,__,_f,_ar,__,_it,_apo,_ll,_ret
		.BYTE	_c,_o,_me,_que,_ret
		.BYTE	_ret
		.BYTE	_I_,_l,_oo,_k,_ed,__,_o,_ve,_r,__a,_t,__the,__,_be,_a,_m,__t,_o,_ret
		.BYTE	_f,_i,_g,_u,_re,__,_it,__,_ou,_t,_dot,_eol
_sc13_msg23:
		.BYTE	_Kaneda,_ddt_,_A,_u,_g,_h,_exc,_ret
		.BYTE	_ret
		.BYTE	_I_,_s,_c,_re,_a,_m,_ed,__a,_s,__the,__,_be,_a,_m,_ret
		.BYTE	_a,_p,_p,_ro,_a,_c,_h,_ed,_dot,_eol
_sc13_msg24:
		.BYTE	_S,_u,_d,_d,_en,_l,_y,_col,__the,__s,_a,_m,_p,_le,__,_c,_a,_se,_ret
		.BYTE	_re,_le,_a,_s,_ed,__a,__,_b,_r,_ight,__,_l,_ight,_dot,_eol
_sc13_msg25:
		.BYTE	_Kaneda,_ddt_,_Kei,_col,__w,_an,_t_,_to_,_g,_o,__,_ou,_t,_que,_eol
_sc13_msg26:
		.BYTE	_Kai,__,_and,__,_Kei,__,_n,_o,_t,_i,_c,_ed,__,_me,_dot,_ret
		.BYTE	_ret
		.BYTE	_Kei,_ddt_,_Kaneda,_exc,_ret
		.BYTE	_ret
		.BYTE	_Kai,_ddt_,_H,_o,_p,__,_on,_exc,_eol
_sc13_msg27:
		.BYTE	_Kaneda,_ddt_,_A,_u,_g,_h,_exc,_ret
		.BYTE	_ret
		.BYTE	_I_,_r,_an,__,_m,_y,__w,_a,_y,__t,_h,_r,_ou,_g,_h,__the,_ret
		.BYTE	_r,_u,_b,_b,_le,_dot,_eol
_sc13_msg28:
		.BYTE	_Tetsuo,_ddt_,_H,_u,_h,_que,__,_W,_hat,_apo_s,__,_this,_ret
		.BYTE	_l,_ight,_que,_eol
_sc13_msg29:
		.BYTE	_The,__,_p,_i,_le,__of,__,_r,_u,_b,_b,_le,__,_was,__,_h,_it,__,_b,_y,_ret
		.BYTE	_t,_he,__,_be,_a,_m,_dot,_eol
_sc13_msg2A:
		.BYTE	_N,_e,_ar,__the,__,_se,_t,_t,_ing,__s,_u,_n,_col,__a,_ret
		.BYTE	_g,_l,_i,_st,_en,_ing,__,_st,_ar,__,_c,_ou,_l,_d_,_be,__,_se,_en,_dot,_ret
		.BYTE	_ret
		.BYTE	_Army,_ddt_,_The,__,_S,_O,_L,__s,_at,_e,_ll,_it,_e,_dot_dot_dot,_eol
_sc13_msg2B:
		.BYTE	_Colonel,_ddt_,_an0,_Tetsuo,__,_d,_e,_st,_ro,_y,_ed,__the,_ret
		.BYTE	_S,_O,_L,__s,_at,_e,_ll,_it,_e,_dot_dot_dot,__,_H,_e,_apo_s,__t,_hat,_ret
		.BYTE	_p,_ow,_er,_f,_u,_l,__a,_l,_re,_ad,_y,_que,_aof,_eol
_sc13_msg2C:
		.BYTE	_S,_h,_w,_oo,_dot_dot_dot,_ret
		.BYTE	_ret
		.BYTE	_The,__,_be,_a,_m,__s,_w,_e,_p,_t_,_o,_ve,_r,__,_u,_s,_col,__the,_n,_ret
		.BYTE	_d,_i,_s,_a,_p,_p,_e,_are,_d,_dot,_eol
_sc13_msg2D:
		.BYTE	_Takashi,_ddt_,_W,_h,_en,__,_Tetsuo,_apo_s,_ret
		.BYTE	_st,_re,_n,_g,_t,_h,__,_ha,_s_,_re,_a,_c,_h,_ed,__,_it,_s,_ret
		.BYTE	_p,_e,_a,_k,_dot_dot_dot,_ret
		.BYTE	_ret
		.BYTE	_Masaru,_ddt_,_The,_n,__w,_e_,_w,_i,_ll,__t,_r,_y,_dot_dot_dot,_ret
		.BYTE	_b,_u,_t_,_I_,_w,_on,_d,_er,__i,_f,__,_it,__w,_i,_ll,_ret
		.BYTE	_w,_or,_k,_dot_dot_dot,_eol
_sc13_msg2E:
		.BYTE	_Kiyoko,_ddt_,_an0,_The,_re,__i,_s_,_n,_o,_t_,_on,_l,_y,__,_on,_e,_ret
		.BYTE	_p,_at,_h,__,_to_,_t,_he,__,_f,_u,_t,_u,_re,_dot_dot_dot,__,_S,_u,_re,_l,_y,_ret
		.BYTE	_t,_her,_e_,_i,_s,__a,__,_f,_u,_t,_u,_re,__t,_hat,__w,_e_,_c,_an,_ret
		.BYTE	_c,_h,_oo,_se,__,_to_,_w,_or,_k,__t,_ow,_ar,_d,_s,_dot,_aof,_eol

		SECTION_END		F13
