
		SECTION_START	F15

		MSG_START	_scene15_msg_lib
		MSG_IDX	_sc15_msg00
		MSG_IDX	_sc15_msg01
		MSG_IDX	_sc15_msg02
		MSG_IDX	_sc15_msg03
		MSG_IDX	_sc15_msg04
		MSG_IDX	_sc15_msg05
		MSG_IDX	_sc15_msg06
		MSG_IDX	_sc15_msg07
		MSG_IDX	_sc15_msg08
		MSG_IDX	_sc15_msg09
;		MSG_IDX	_sc15_msg0A						; unused
		MSG_IDX	_sc15_msg0B
		MSG_IDX	_sc15_msg0C
		MSG_IDX	_sc15_msg0D
		MSG_IDX	_sc15_msg0E
		MSG_IDX	_sc15_msg0F
		MSG_IDX	_sc15_msg10
		MSG_IDX	_sc15_msg11
		MSG_IDX	_sc15_msg12
		MSG_IDX	_sc15_msg13
		MSG_IDX	_sc15_msg14
		MSG_IDX	_sc15_msg15
		MSG_IDX	_sc15_msg16
		MSG_IDX	_sc15_msg17
		MSG_IDX	_sc15_msg18
		MSG_IDX	_sc15_msg19
		MSG_IDX	_sc15_msg1A
		MSG_IDX	_sc15_msg1B
		MSG_IDX	_sc15_msg1C
		MSG_IDX	_sc15_msg1D
		MSG_IDX	_sc15_msg1E
		MSG_IDX	_sc15_msg1F
		MSG_IDX	_sc15_msg20
		MSG_IDX	_sc15_msg21
		MSG_IDX	_sc15_msg22
		MSG_IDX	_sc15_msg23
		MSG_IDX	_sc15_msg24
		MSG_IDX	_sc15_msg25
		MSG_IDX	_sc15_msg27
		MSG_IDX	_sc15_msg29
		MSG_IDX	_sc15_msg2A
		MSG_IDX	_sc15_msg2B
		MSG_IDX	_sc15_msg2D
		MSG_IDX	_sc15_msg33
		MSG_IDX	_sc15_msg34
		MSG_IDX	_sc15_msg35
		MSG_IDX	_sc15_msg36
		MSG_IDX	_sc15_msg37
		MSG_IDX	_sc15_msg38
		MSG_IDX	_sc15_msg9D					; scene 15 msg
		MSG_IDX	_sc15_msgAC					; scene 15 msg
_sc15_msg00:
		.BYTE	_V,_r,_r,_m,_dot,_ret
		.BYTE	_ret
		.BYTE	_W,_h,_i,_le,__,_h,_o,_l,_d,_ing,__the,__,_laser,_col,__,_I,_ret
		.BYTE	_d,_ro,_ve,__t,_ow,_ar,_d,__the,__,_O,_l,_y,_m,_p,_i,_c,_ret
		.BYTE	_S,_t,_ad,_i,_u,_m,_dot,_eol
_sc15_msg01:
		.BYTE	_I_,_f,_in,_a,_ll,_y,__,_f,_ou,_n,_d_,_Tetsuo,_exc,_eol
_sc15_msg02:
		.BYTE	_A,__,_b,_i,_z,_ar,_re,__,_m,_a,_s,_s_,_was,__w,_her,_e,_ret
		.BYTE	_Tetsuo,_apo_s,__,_r,_ight,__a,_r,_m,__,_ha,_d_,_be,_en,_col,_ret
		.BYTE	_and,__,_it,__,_was,__a,_t,_t,_a,_c,_k,_ing,__the,__,_Army,_ret
		.BYTE	_l,_a,_c,_k,_e,_y,_s,_dot,_eol
_sc15_msg03:
		.BYTE	_W,_h,_oo,_s,_h,_exc,_ret
		.BYTE	_ret
		.BYTE	_The,__s,_h,_o,_c,_k,__w,_a,_ve,__,_h,_it,__,_Kaneda,_dot,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_A,_g,_h,_exc,_eol
_sc15_msg04:
		.BYTE	_I_,_se,_t_,_u,_p,__the,__,_laser,__,_be,_a,_m,__a,_g,_a,_in,_dot,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_an0,_Tetsuo,_col,__,_I_apo,_ll,__,_p,_u,_t_,_you,_ret
		.BYTE	_ou,_t_,_of,__,_you,_r,__,_m,_i,_s,_er,_y,_exc,_aof,_eol
_sc15_msg05:
		.BYTE	_Kaneda,_ddt_,_A,_l,_r,_ight,_exc,_ret
		.BYTE	_F,_u,_ll,__t,_h,_ro,_t,_t,_le,_exc,_ret
		.BYTE	_ret
		.BYTE	_I_,_re,_ad,_i,_ed,__the,__,_b,_i,_k,_e_,_to_,_r,_a,_m,_ret
		.BYTE	_in,_to_,_Tetsuo,_dot,_eol
_sc15_msg06:
		.BYTE	_But,__,_m,_y,__t,_i,_re,__g,_o,_t_,_c,_a,_u,_g,_h,_t,__i,_n,__the,_ret
		.BYTE	_r,_u,_b,_b,_le,_col,__,_and,__,_I_,_t,_u,_m,_b,_l,_ed,__of,_f,__the,_ret
		.BYTE	_b,_i,_k,_e,_dot,_eol
_sc15_msg07:
		.BYTE	_Kaneda,_ddt_,_I_apo,_ve,__,_ha,_d_,_en,_ou,_g,_h,__of,_ret
		.BYTE	_Tetsuo,_apo_s,__,_b,_o,_s,_s,_y,__a,_t,_t,_it,_u,_d,_e,_dot,_eol
_sc15_msg08:
		.BYTE	_Tetsuo,_ddt_,_an0,_Kaneda,_exc,__,_You_apo_re,__the,_ret
		.BYTE	_on,_e_,_w,_h,_o,_apo,_ll,__,_be,__,_p,_u,_t_,_ou,_t_,_of,__,_his,_ret
		.BYTE	_m,_i,_s,_er,_y,_exc,_aof,_eol
_sc15_msg09:
		.BYTE	_I,_n,__,_d,_e,_s,_p,_er,_at,_i,_on,_col,__,_I_,_t,_h,_re,_w,__the,_ret
		.BYTE	_laser,__a,_t_,_Tetsuo,_dot,_ret
		.BYTE	_ret
		.BYTE	_I_,_m,_i,_s,_s,_ed,_dot,_eol
;_sc15_msg0A:
;		.BYTE	_I_,_t,_h,_re,_w,__the,__,_m,_i,_r,_ro,_r,__,_n,_e,_ar,_ret
;		.BYTE	_Tetsuo,_apo_s,__,_r,_ight,__a,_r,_m,_dot,_eol
_sc15_msg0B:
		.BYTE	_The,__w,_e,_i,_r,_d,__t,_h,_ing,__,_on,__,_his,__a,_r,_m,_ret
		.BYTE	_st,_ar,_t,_ed,__g,_r,_ow,_ing,_dot,__,_I,_t,__a,_l,_re,_ad,_y,_ret
		.BYTE	_g,_re,_w,__,_around,__the,__,_Army,__,_l,_a,_c,_k,_e,_y,_s,_ret
		.BYTE	_f,_ro,_m,__,_before,_dot,_eol
_sc15_msg0C:
		.BYTE	_W,_a,_s,_n,_apo,_t_,_his,__,_r,_ight,__a,_r,_m,__,_se,_ve,_r,_ed,_ret
		.BYTE	_before,_que,_ret
		.BYTE	_ret
		.BYTE	_dot_dot_dot,_C,_ou,_l,_d_,_it,__,_ha,_ve,__,_m,_i,_s,_s,_ed,_que,_eol
_sc15_msg0D:
		.BYTE	_T,_hat,_apo_s,__,_r,_ight,_dot_dot_dot,__,_I_,_ha,_ve,__the,_ret
		.BYTE	_m,_i,_r,_ro,_r,__t,_hat,__,_Kei,__g,_a,_ve,__,_me,_ret
		.BYTE	_e,_ar,_l,_i,_er,_dot,_eol
_sc15_msg0E:
		.BYTE	_I_,_t,_o,_s,_s,_ed,__the,__,_m,_i,_r,_ro,_r,__,_n,_e,_x,_t,__t,_o,_ret
		.BYTE	_Tetsuo,_dot,_eol
_sc15_msg0F:
		.BYTE	_I_,_w,_en,_t_,_to_,_re,_t,_r,_i,_e,_ve,__the,__,_m,_i,_r,_ro,_r,_ret
		.BYTE	_I_,_t,_h,_re,_w,_dot,_eol
_sc15_msg10:
		.BYTE	_The,__,_laser,__,_re,_f,_le,_c,_t,_ed,__of,_f,__the,_ret
		.BYTE	_m,_i,_r,_ro,_r,__,_and,__,_m,_i,_s,_s,_ed,__,_Tetsuo,_apo_s,_ret
		.BYTE	_b,_o,_d,_y,_exc,_eol
_sc15_msg11:
		.BYTE	_Tetsuo,_col,__w,_h,_o,__,_ha,_d_,_c,_h,_an,_g,_ed,__i,_n,_to_,_a,_ret
		.BYTE	_m,_on,_st,_er,_col,__,_m,_o,_an,_ed,__,_p,_a,_in,_f,_u,_ll,_y,_dot,_eol
_sc15_msg12:
		.BYTE	_K,_s,_h,_oo,_m,_exc,_ret
		.BYTE	_ret
		.BYTE	_The,__,_laser,__,_re,_f,_le,_c,_t,_ed,__of,_f,__the,_ret
		.BYTE	_m,_i,_r,_ro,_r,_dot,_eol
_sc15_msg13:
		.BYTE	_The,__,_laser,__,_m,_i,_s,_s,_ed,__,_Tetsuo,_exc,_eol
_sc15_msg14:
		.BYTE	_W,_it,_h,_ou,_t,__t,_h,_in,_k,_ing,_col,__,_I_,_f,_i,_r,_ed,__a,_t,_ret
		.BYTE	_Tetsuo,_col,__w,_h,_o,__,_ha,_d_,_c,_h,_an,_g,_ed,__i,_n,_t,_o,_ret
		.BYTE	_a,__,_m,_on,_st,_er,_dot,_eol
_sc15_msg15:
		.BYTE	_Tetsuo,__,_se,_e,_m,_ed,__,_to_,_be,__t,_u,_r,_n,_ing,_ret
		.BYTE	_in,_to_,_a,__g,_i,_an,_t_,_b,_l,_o,_b,__of,__,_f,_le,_s,_h,_dot,_eol
_sc15_msg16:
		.BYTE	_But,__,_Tetsuo,__s,_p,_r,_an,_g,__,_u,_p,__a,_f,_t,_er,__the,_ret
		.BYTE	_re,_c,_o,_i,_l,_dot,__,_A,_f,_t,_er,__,_le,_v,_it,_at,_ing,__i,_n,_ret
		.BYTE	_t,_he,__a,_i,_r,_col,__,_he,__w,_en,_t,__i,_n,_to_,_a,__,_d,_i,_ve,_dot,_eol
_sc15_msg17:
		.BYTE	_I_,_w,_en,_t_,_f,_u,_ll,__s,_p,_e,_ed,__i,_n,__,_re,_ve,_r,_se,_ret
		.BYTE	_u,_p,__the,__,_p,_i,_le,__of,__,_r,_u,_b,_b,_le,_dot,_eol
_sc15_msg18:
		.BYTE	_W,_it,_h,__,_me,__s,_o,__,_c,_l,_o,_se,_col,__,_Tetsuo,_ret
		.BYTE	_at,_t,_a,_c,_k,_ed,__,_me,__,_with,__,_his,__,_b,_o,_d,_y,_dot,_ret
		.BYTE	_The,__,_f,_l,_oo,_r,__of,__the,__,_st,_ad,_i,_u,_m,__,_was,_ret
		.BYTE	_d,_e,_st,_ro,_y,_ed,_dot,_eol
_sc15_msg19:
		.BYTE	_I_,_h,_it,__the,__,_b,_r,_a,_k,_e,_s_,_p,_ar,_t,_w,_a,_y,_ret
		.BYTE	_t,_h,_r,_ou,_g,_h,__the,__,_r,_u,_b,_b,_le,_dot,_eol
_sc15_msg1A:
		.BYTE	_Tetsuo,__,_c,_o,_ll,_a,_p,_s,_ed,__,_and,__,_st,_ar,_t,_ed,_ret
		.BYTE	_to_,_t,_w,_it,_c,_h,_dot,_eol
_sc15_msg1B:
		.BYTE	_Tetsuo,__,_be,_g,_an,__t,_r,_an,_s,_for,_m,_ing,__i,_n,_t,_o,_ret
		.BYTE	_a,__,_m,_on,_st,_er,_dot,__,_H,_e_,_be,_g,_an,__,_to_,_g,_r,_ow,_ret
		.BYTE	_r,_a,_p,_id,_l,_y,_col,__,_u,_n,_a,_b,_le,__,_to_,_c,_on,_t,_ro,_l,__the,_ret
		.BYTE	_f,_l,_ow,__of,__,_his,__,_en,_er,_g,_y,_dot,_eol
_sc15_msg1C:
		.BYTE	_A,__s,_u,_d,_d,_en,__s,_w,_e,_ll,__of,__,_m,_u,_s,_c,_le,__,_b,_u,_r,_st,_ret
		.BYTE	_t,_h,_r,_ou,_g,_h,__,_his,__s,_k,_in,_dot,_eol
_sc15_msg1D:
		.BYTE	_Tetsuo,_ddt_,_an0,_Kaneda,_dot_dot_dot,_ret
		.BYTE	_h,_dot_dot_dot,_he,_l,_p,__,_me,_dot_dot_dot,_ret
		.BYTE	_p,_le,_a,_se,_dot_dot_dot,_aof,_eol
_sc15_msg1E:
		.BYTE	_Tetsuo,__,_be,_g,_an,__,_to_,_a,_b,_s,_or,_b,__the,_ret
		.BYTE	_l,_ight,_dot,_ret
		.BYTE	_ret
		.BYTE	_I_,_r,_an,__,_o,_ve,_r,__t,_ow,_ar,_d,_s_,_h,_i,_m,_dot,_eol
_sc15_msg1F:
		.BYTE	_I_,_p,_u,_n,_c,_h,_ed,__t,_h,_r,_ou,_g,_h,__the,__,_b,_l,_o,_b,_ret
		.BYTE	_s,_u,_r,_r,_ou,_n,_d,_ing,__t,_h,_o,_se,__,_Army,__,_j,_er,_k,_s,_ret
		.BYTE	_with,__,_m,_y,__,_laser,_dot,_eol
_sc15_msg20:
		.BYTE	_The,__,_laser,__,_h,_it,__,_his,__,_r,_ight,__a,_r,_m,_col,_ret
		.BYTE	_and,__the,__,_are,_a,__,_be,_g,_an,__,_to_,_s,_w,_e,_ll,_ret
		.BYTE	_o,_d,_d,_l,_y,_dot,_eol
_sc15_msg21:
		.BYTE	_Kaneda,_ddt_,_S,_t,_o,_p,__,_it,_exc,_ret
		.BYTE	_ret
		.BYTE	_T,_en,_t,_a,_c,_le,_s,__s,_p,_r,_u,_n,_g,__,_for,_t,_h,__,_f,_ro,_m,_ret
		.BYTE	_t,_he,__,_b,_l,_o,_b,__of,__,_f,_le,_s,_h,_dot,__,_The,_y,_ret
		.BYTE	_st,_o,_p,_p,_ed,__,_me,__i,_n,__,_m,_y,__t,_r,_a,_c,_k,_s,_col,_ret
		.BYTE	_d,_r,_a,_g,_g,_ing,__,_me,__i,_n,_dot,_eol
_sc15_msg22:
		.BYTE	_I,_n,_s,_id,_e,__the,__,_b,_l,_o,_b,_col,__,_I_,_he,_ar,_d,_ret
		.BYTE	_Tetsuo,_apo_s,__,_m,_o,_an,_ing,_dot,_eol
_sc15_msg23:
		.BYTE	_Tetsuo,_ddt_,_an0,_C,_an,_apo,_t,_dot_dot_dot,_ret
		.BYTE	_c,_on,_t,_ro,_l,_dot_dot_dot,_ret
		.BYTE	_b,_o,_d,_y,_dot_dot_dot,_aof,_eol
_sc15_msg24:
		.BYTE	_The,__,_f,_l,_u,_id,__t,_hat,__,_ha,_d_,_s,_p,_re,_a,_d_,_on,_ret
		.BYTE	_t,_he,__,_f,_l,_oo,_r,__,_se,_e,_t,_h,_ed,_col,__the,_n,__,_be,_g,_an,_ret
		.BYTE	_to_,_e,_m,_it,__a,__,_st,_r,_an,_g,_e_,_l,_ight,_dot,_eol
_sc15_msg25:
		.BYTE	_The,__s,_a,_m,_p,_le,__,_c,_a,_se,__,_c,_r,_a,_c,_k,_ed,_col,__,_and,_ret
		.BYTE	_a,__,_f,_l,_u,_i,_d_,_b,_o,_i,_l,_ed,__,_for,_t,_h,__,_f,_ro,_m,_ret
		.BYTE	_in,_s,_id,_e,_dot,_eol
_sc15_msg27:
		.BYTE	_Masaru,_ddt_,_an0,_It_apo_s,__,_Akira,_dot_dot_dot,_aof,_eol
_sc15_msg29:
		.BYTE	_The,__,_l,_ight,__,_f,_ro,_m,__,_Akira,__s,_p,_r,_an,_g,_ret
		.BYTE	_for,_t,_h,_dot,__,_I,_t,__s,_p,_re,_a,_d_,_m,_o,_re,__,_and,_ret
		.BYTE	_m,_o,_re,_col,__,_u,_n,_t,_i,_l,__,_it,__,_c,_o,_ve,_r,_ed,__the,_ret
		.BYTE	_t,_h,_re,_e_,_of,__the,_m,_dot,_eol
_sc15_msg2A:
		.BYTE	_Kiyoko,_ddt_,_But,_dot_dot_dot,__i,_f,__w,_e_,_t,_h,_re,_e_,_d,_o,_ret
		.BYTE	_it,_col,__the,_n,__,_he,_dot_dot_dot,_ret
		.BYTE	_ret
		.BYTE	_Masaru,_ddt_,_T,_hat,_apo_s,__,_r,_ight,_dot_dot_dot,_ret
		.BYTE	_with,__t,_h,_re,_e_,_of,__,_u,_s,_dot_dot_dot,_eol
_sc15_msg2B:
		.BYTE	_I_,_t,_r,_i,_ed,__,_to_,_m,_a,_k,_e_,_an,_o,_t,_her,_ret
		.BYTE	_d,_e,_c,_i,_s,_i,_on,_col,__,_and,__a,_i,_m,_ed,__the,__,_laser,_ret
		.BYTE	_a,_t_,_his,__,_b,_o,_d,_y,_dot,_eol
_sc15_msg2D:
		.BYTE	_But,__a,__,_k,_i,_d_,_g,_r,_a,_b,_b,_ed,__,_m,_y,__,_h,_and,_dot,_ret
		.BYTE	_ret
		.BYTE	_Takashi,_ddt_,_N,_o,_col,__,_d,_on,_apo,_t_,_d,_o,__,_it,_exc,_ret
		.BYTE	_I,_f,__,_you,__g,_o,__,_n,_ow,_col,__the,_re,__w,_i,_ll,__,_be,_ret
		.BYTE	_n,_o,__w,_a,_y,__,_to_,_re,_t,_u,_r,_n,_dot,_eol
_sc15_msg33:
		.BYTE	_I_,_s,_h,_oo,_k,__of,_f,__the,__,_k,_id,_apo_s,__,_h,_and,_col,_ret
		.BYTE	_and,__,_r,_an,__t,_ow,_ar,_d,__the,__,_l,_ight,_dot,_eol
_sc15_msg34:
		.BYTE	_I_,_r,_an,__,_with,__the,__,_k,_i,_d_,_a,_w,_a,_y,__,_f,_ro,_m,_ret
		.BYTE	_Tetsuo,_dot,_eol
_sc15_msg35:
		.BYTE	_I_,_k,_n,_o,_c,_k,_ed,__the,__,_k,_i,_d_,_d,_ow,_n,_col,_ret
		.BYTE	_and,__,_r,_an,__t,_ow,_ar,_d,__the,__,_l,_ight,_dot,_eol
_sc15_msg36:
		.BYTE	_J,_u,_st,__a,_s,__the,__,_l,_ight,__,_was,__a,_b,_ou,_t,__t,_o,_ret
		.BYTE	_c,_on,_s,_u,_me,__,_me,_col,__,_I_,_s,_a,_w,__the,__,_k,_i,_d_,_f,_ro,_m,_ret
		.BYTE	_before,__,_r,_u,_n,__,_u,_p,_dot,_ret
		.BYTE	_ret
		.BYTE	_Takashi,_ddt_,_H,_e_,_ha,_s_,_n,_o,_t,_h,_ing,__,_to_,_d,_o,_ret
		.BYTE	_with,__,_this,_exc,_eol
_sc15_msg37:
		.BYTE	_The,__,_k,_i,_d_,_j,_u,_m,_p,_ed,__i,_n,_to_,_t,_he,__,_l,_ight,_dot,_ret
		.BYTE	_ret
		.BYTE	_Masaru,_ddt_,_Takashi,_exc,_ret
		.BYTE	_ret
		.BYTE	_Kiyoko,_ddt_,_Takashi,_dot_dot_dot,__,_N,_o,_dot_dot_dot,_eol
_sc15_msg38:
		.BYTE	_Masaru,_ddt_,_dot_dot_dot,_I,_f,__w,_e_,_g,_o,__i,_n,_s,_id,_e,_col,__w,_e,_ret
		.BYTE	_w,_on,_apo,_t_,_be,__a,_b,_le,__,_to_,_g,_e,_t_,_b,_a,_c,_k,__,_ou,_t,_ret
		.BYTE	_with,__,_ou,_r,__,_p,_ow,_er,_dot,_eol
_sc15_msg9D:
		.BYTE	_Tetsuo,_ddt_,_an1,_Kaneda,_que,_exc,_aof,_eol
_sc15_msgAC:
		.BYTE	_The,__,_laser,__,_h,_it,__,_Tetsuo,_apo_s,__,_r,_ight,_ret
		.BYTE	_ar,_m,_exc,_eol

		SECTION_END		F15
