
		SECTION_START	F10

		MSG_START	_scene10_msg_lib
		MSG_IDX	_sc10_msg00
		MSG_IDX	_sc10_msg01
		MSG_IDX	_sc10_msg02
		MSG_IDX	_sc10_msg03
		MSG_IDX	_sc10_msg04
		MSG_IDX	_sc10_msg05
		MSG_IDX	_sc10_msg06
		MSG_IDX	_sc10_msg07
		MSG_IDX	_sc10_msg08
		MSG_IDX	_sc10_msg09
		MSG_IDX	_sc10_msg0A
		MSG_IDX	_sc10_msg0B
		MSG_IDX	_sc10_msg0C
		MSG_IDX	_sc10_msg0D
		MSG_IDX	_sc10_msg0E
		MSG_IDX	_sc10_msg0F
		MSG_IDX	_sc10_msg10
		MSG_IDX	_sc10_msg11
		MSG_IDX	_sc10_msg12
		MSG_IDX	_sc10_msg13
		MSG_IDX	_sc10_msg14
		MSG_IDX	_sc10_msg15
		MSG_IDX	_sc10_msg16
		MSG_IDX	_sc10_msg17
		MSG_IDX	_sc10_msg18
		MSG_IDX	_sc10_msg19
		MSG_IDX	_sc10_msg1A
		MSG_IDX	_sc10_msg1B
_sc10_msg00:
		.BYTE	_Kaneda,_ddt_,_H,_m,_col,__,_l,_oo,_k,_s_,_l,_i,_k,_e,__the,_ret
		.BYTE	_l,_a,_b,_apo_s,__,_c,_on,_f,_in,_e,_me,_n,_t_,_ro,_o,_m,_dot,_ret
		.BYTE	_W,_her,_e,_apo_s,__,_Kei,_que,_eol
_sc10_msg01:
		.BYTE	_Kei,_ddt_,_an0,_V,_er,_y,__,_o,_b,_s,_er,_v,_an,_t,_dot,_ret
		.BYTE	_H,_ow,__,_d,_o,__,_you,__,_f,_e,_e,_l,_que,_aof,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_T,_er,_r,_i,_b,_le,_dot,_eol
_sc10_msg02:
		.BYTE	_Kei,_ddt_,_an0,_A,_f,_t,_er,__a,_ll,_col,__,_you,_apo,_re,_ret
		.BYTE	_n,_o,_t,_h,_ing,__,_b,_u,_t,__a,__,_b,_u,_r,_d,_en,__,_to_,_u,_s,_exc,_aof,_eol
_sc10_msg03:
		.BYTE	_Kei,_ddt_,_an0,_I,_t_,_d,_o,_e,_s,_n,_apo,_t_,_l,_oo,_k,_ret
		.BYTE	_b,_re,_a,_k,_a,_b,_le,_dot_dot_dot,_aof,_eol
_sc10_msg04:
		.BYTE	_Kaneda,_ddt_,_Damn,__,_you,__a,_s,_s,_h,_o,_le,_s,_exc,_ret
		.BYTE	_L,_o,_c,_k,_ing,__,_me,__,_u,_p,__,_l,_i,_k,_e_,_this,_exc,_eol
_sc10_msg05:
		.BYTE	_Kaneda,_ddt_,_The,__,_Army,_apo_s,__,_l,_oo,_k,_ing,__,_for,_ret
		.BYTE	_this,__,_Akira,__g,_u,_y,_col,__t,_oo,_dot_dot_dot,_ret
		.BYTE	_ret
		.BYTE	_Kei,_ddt_,_an0,_The,__,_Army,_apo_s,__a,_f,_r,_a,_i,_d_,_of,__,_h,_i,_m,_dot,_ret
		.BYTE	_L,_oo,_k,_s_,_l,_i,_k,_e,__the,_y,_apo,_ve,__,_l,_o,_c,_k,_ed,__a,_w,_a,_y,_ret
		.BYTE	_his,__,_p,_ow,_er,__s,_o,_me,_h,_ow,_dot,_aof,_eol
_sc10_msg06:
		.BYTE	_Kaneda,_ddt_,_H,_e,_apo_s,__g,_on,_e_,_to_,_Akira,_dot_dot_dot,_que,_ret
		.BYTE	_ret
		.BYTE	_Kei,_ddt_,_an0,_T,_hat,_apo_s,__w,_hat,__the,_ret
		.BYTE	_k,_i,_d_,_s,_a,_id,_dot_dot_dot,_aof,_eol
_sc10_msg07:
		.BYTE	_Kei,_ddt_,_an0,_O,_u,_r,__,_b,_o,_s,_s,_col,__,_M,_r,_dot,__,_N,_e,_z,_u,_col,__s,_a,_id,_ret
		.BYTE	_Akira,__i,_s_,_ou,_r,__t,_r,_u,_m,_p,__,_c,_ar,_d,_dot,__,_W,_e,_ret
		.BYTE	_c,_an,__,_b,_r,_ing,__,_d,_ow,_n,__the,__,_c,_or,_r,_u,_p,_t,_ret
		.BYTE	_g,_o,_ve,_r,_n,_me,_n,_t_,_with,__,_h,_i,_m,_dot_dot_dot,_aof,_eol
_sc10_msg08:
		.BYTE	_Kei,_ddt_,_an0,_Ryu,__t,_o,_l,_d_,_me,__,_Akira,__i,_s_,_p,_u,_re,_ret
		.BYTE	_en,_er,_g,_y,_dot_dot_dot,__,_T,_h,_r,_ou,_g,_h,_ou,_t,__the,_i,_r,_ret
		.BYTE	_his,_t,_or,_y,_col,__,_h,_u,_m,_an,_s_,_ha,_ve,__,_d,_on,_e_,_a,_ret
		.BYTE	_l,_o,_t_,_of,__t,_h,_ing,_s,_col,__,_r,_ight,_que,_aof,_eol
_sc10_msg09:
		.BYTE	_Kei,_ddt_,_an0,_E,_x,_p,_l,_or,_ing,_col,__,_c,_re,_at,_ing,_dot_dot_dot,_ret
		.BYTE	_A,_ll,__t,_hat,__,_k,_n,_ow,_l,_ed,_g,_e_,_and,__,_en,_er,_g,_y,_dot,_ret
		.BYTE	_W,_her,_e_,_d,_o,_e,_s_,_it,__,_c,_o,_me,__,_f,_ro,_m,_que,_ret
		.BYTE	_S,_u,_re,_l,_y,__w,_e_,_were_,_j,_u,_st,__,_l,_i,_k,_e,_ret
		.BYTE	_m,_on,_k,_e,_y,_s_,_on,_c,_e,_dot_dot_dot,_aof,_eol
_sc10_msg0A:
		.BYTE	_Kei,_ddt_,_an0,_A,_n,_d_,_before,__t,_hat,_col,_ret
		.BYTE	_re,_p,_t,_i,_le,_s_,_and,__,_f,_i,_s,_h,_dot,__,_E,_ve,_n,_ret
		.BYTE	_e,_ar,_l,_i,_er,_col,__,_p,_l,_an,_k,_t,_on,__,_and,_ret
		.BYTE	_a,_m,_o,_e,_b,_a,_s,_dot_dot_dot,__,_I,_s,_n,_apo,_t,__the,_re,__a,_n,_ret
		.BYTE	_in,_c,_r,_ed,_i,_b,_le,__,_en,_er,_g,_y,__i,_n,_s,_id,_e_,_a,_ll,_ret
		.BYTE	_t,_he,_se,__,_for,_m,_s_,_of,__,_l,_i,_f,_e,_que,_aof,_eol
_sc10_msg0B:
		.BYTE	_Kaneda,_ddt_,_It_apo_s,__,_be,_c,_a,_u,_se,__of,_ret
		.BYTE	_g,_en,_e,_s,_dot_dot_dot,_eol
_sc10_msg17:
		.BYTE	_Kei,_ddt_,_an0,_I_,_w,_on,_d,_er,_col,__,_e,_ve,_n,__,_before,_ret
		.BYTE	_t,_hat,_col,__i,_f,__w,_at,_er,__,_and,__a,_i,_r,__,_h,_ad,_ret
		.BYTE	_g,_en,_e,_s,_dot_dot_dot,__,_O,_r,__,_e,_ve,_n,__the,__,_d,_u,_st,__,_f,_ro,_m,_ret
		.BYTE	_s,_p,_a,_c,_e,_dot,_aof,_eol
_sc10_msg0C:
		.BYTE	_Kei,_ddt_,_an0,_I_,_w,_on,_d,_er,__w,_hat,__,_me,_m,_or,_i,_e,_s,_ret
		.BYTE	_t,_he,_y,__,_m,_ight,__,_be,__,_h,_id,_ing,_dot,__,_The,_ret
		.BYTE	_be,_g,_in,_n,_ing,__of,__,_e,_x,_i,_st,_en,_c,_e,_col,__the,_ret
		.BYTE	_t,_i,_me,_s_,_e,_ve,_n,__,_before,__,_it,_dot_dot_dot,_ret
		.BYTE	_E,_veryone,__,_m,_ight,__,_h,_o,_l,_d,__the,_se,_ret
		.BYTE	_ve,_r,_y,__,_me,_m,_or,_i,_e,_s,_dot_dot_dot,_aof,_eol
_sc10_msg0D:
		.BYTE	_Kei,_ddt_,_an0,_I,_m,_a,_g,_in,_e_,_i,_f,__the,_re,__,_was,__a,_ret
		.BYTE	_m,_i,_st,_a,_k,_e_,_in,__the,__,_or,_d,_er,__of,__,_l,_i,_f,_e,_col,_ret
		.BYTE	_and,__a,_n,__a,_m,_o,_e,_b,_a,__,_o,_b,_t,_a,_in,_ed,__the,_ret
		.BYTE	_p,_ow,_er,__of,__a,__,_h,_u,_m,_an,__,_be,_ing,_dot_dot_dot,_aof,_eol
_sc10_msg18:
		.BYTE	_Kaneda,_ddt_,_S,_o,__t,_hat,_apo_s,__w,_hat,__,_Akira,_ret
		.BYTE	_i,_s_,_l,_i,_k,_e,_que,_eol
_sc10_msg0E:
		.BYTE	_Kei,_ddt_,_an0,_T,_his,__a,_m,_o,_e,_b,_a,__w,_ou,_l,_d,_n,_apo,_t,_ret
		.BYTE	_w,_or,_r,_y,__a,_b,_ou,_t,__a,__,_h,_ou,_se,_col,__,_or,_ret
		.BYTE	_c,_l,_o,_t,_he,_s,_dot_dot_dot,__,_it,__w,_ou,_l,_d_,_s,_i,_m,_p,_l,_y,_ret
		.BYTE	_c,_on,_s,_u,_me,__a,_ll,__of,__,_it,_s,_ret
		.BYTE	_s,_u,_r,_r,_ou,_n,_d,_ing,_s,_dot,_aof,_eol
_sc10_msg19:
		.BYTE	_Kaneda,_ddt_,_Tetsuo,_que,__,_H,_e_,_c,_an,__w,_i,_e,_l,_d,_ret
		.BYTE	_t,_hat,__,_k,_in,_d_,_of,__,_p,_ow,_er,_que,_exc,_eol
_sc10_msg0F:
		.BYTE	_Y,_ou,__,_me,_an,__w,_hat,__,_d,_e,_st,_ro,_y,_ed,__,_this,_ret
		.BYTE	_Nursery,__,_was,__,_Tetsuo,_apo_s,__,_en,_er,_g,_y,_que,_exc,_ret
		.BYTE	_H,_i,_s_,_p,_ow,_er,_que,_eol
_sc10_msg10:
		.BYTE	_I,_f,__w,_e_,_d,_on,_apo,_t_,_f,_in,_d_,_Akira,__,_before,_ret
		.BYTE	_Tetsuo,__,_d,_o,_e,_s,_col,__w,_e,_apo,_re,__i,_n,__,_b,_i,_g,_ret
		.BYTE	_t,_r,_ou,_b,_le,_exc,_eol
_sc10_msg11:
		.BYTE	_Kei,_ddt_,_an0,_A,__,_l,_on,_g,__t,_i,_me,__a,_g,_o,_col,__the,_re,_ret
		.BYTE	_were_,_p,_e,_o,_p,_le,__w,_h,_o,__a,_i,_m,_ed,__t,_o,_ret
		.BYTE	_c,_on,_t,_ro,_l,__t,_hat,__,_p,_ow,_er,_dot_dot_dot,__,_The,_ret
		.BYTE	_g,_o,_ve,_r,_n,_me,_n,_t_,_st,_ar,_t,_ed,__a,__,_re,_se,_ar,_c,_h,_ret
		.BYTE	_c,_en,_t,_er,_dot_dot_dot,_aof,_eol
_sc10_msg1A:
		.BYTE	_Kei,__s,_u,_d,_d,_en,_l,_y,__,_be,_g,_an,__s,_p,_e,_a,_k,_ing,__i,_n,_ret
		.BYTE	_a,__,_st,_r,_an,_g,_e_,_v,_o,_i,_c,_e,_dot,_eol
_sc10_msg12:
		.BYTE	_Kei,_ddt_,_an0,_But,__the,_y,__,_f,_a,_i,_l,_ed,_col,__,_and,_ret
		.BYTE	_a,_w,_a,_k,_en,_ed,__the,__,_d,_e,_st,_r,_u,_c,_t,_i,_on,__of,_ret
		.BYTE	_T,_ok,_y,_o,_dot,_aof,_eol
_sc10_msg1B:
		.BYTE	_Kei,_ddt_,_an0,_W,_e_,_st,_i,_ll,__,_l,_a,_c,_k,__t,_hat,__,_k,_in,_d,_ret
		.BYTE	_of,__,_p,_ow,_er,_dot_dot_dot,_aof,_eol
_sc10_msg13:
		.BYTE	_Kaneda,_ddt_,_O,_h,_col,__the,__,_d,_oo,_r,_exc,_eol
_sc10_msg14:
		.BYTE	_Kei,__,_and,__,_I_,_e,_s,_c,_a,_p,_ed,__,_f,_ro,_m,__the,_ret
		.BYTE	_l,_a,_b,_dot,_eol
_sc10_msg15:
		.BYTE	_Kei,_ddt_,_an0,_W,_hat,_apo,_re,__,_you,__,_d,_o,_ing,_que,_exc,_aof,_eol
_sc10_msg16:
		.BYTE	_H,_ow,__,_c,_an,__,_I_,_o,_p,_en,__the,__,_d,_oo,_r,_que,_eol

		SECTION_END		F10
