
		SECTION_START	F12

		MSG_START	_scene12_msg_lib
		MSG_IDX	_sc12_msg00
		MSG_IDX	_sc12_msg01
		MSG_IDX	_sc12_msg02
		MSG_IDX	_sc12_msg03
		MSG_IDX	_sc12_msg04
		MSG_IDX	_sc12_msg05
		MSG_IDX	_sc12_msg06
		MSG_IDX	_sc12_msg07
		MSG_IDX	_sc12_msg08
		MSG_IDX	_sc12_msg09
		MSG_IDX	_sc12_msg0A
		MSG_IDX	_sc12_msg0B
		MSG_IDX	_sc12_msg0C
		MSG_IDX	_sc12_msg0D
		MSG_IDX	_sc12_msg0E
		MSG_IDX	_sc12_msg0F
		MSG_IDX	_sc12_msg10
		MSG_IDX	_sc12_msg11
		MSG_IDX	_sc12_msg12
		MSG_IDX	_sc12_msg13
		MSG_IDX	_sc12_msg14
		MSG_IDX	_sc12_msg15
		MSG_IDX	_sc12_msg16
		MSG_IDX	_sc12_msg17
		MSG_IDX	_sc12_msg18
		MSG_IDX	_sc12_msg19
		MSG_IDX	_sc12_msg1A
		MSG_IDX	_sc12_msg1B
		MSG_IDX	_sc12_msg1C
		MSG_IDX	_sc12_msg1D
		MSG_IDX	_sc12_msg1E
		MSG_IDX	_sc12_msg1F
		MSG_IDX	_sc12_msg20
		MSG_IDX	_sc12_msg21
		MSG_IDX	_sc12_msg22
		MSG_IDX	_sc12_msg23
		MSG_IDX	_sc12_msg24
		MSG_IDX	_sc12_msg25
		MSG_IDX	_sc12_msg26
		MSG_IDX	_sc12_msg27
		MSG_IDX	_sc12_msg28
		MSG_IDX	_sc12_msg29
;		MSG_IDX	_sc12_msg2A						; _sc13_msg2A alt version
;		MSG_IDX	_sc12_msg2B						; _sc13_msg2B alt version
;		MSG_IDX	_sc12_msg2C						; -unused-
;		MSG_IDX	_sc12_msg2D						; -unused-
;		MSG_IDX	_sc12_msg2E						; -unused-
_sc12_msg00:
		.BYTE	_A,_s_,_I_,_w,_a,_l,_k,_ed,__,_p,_a,_st,__a,_n,_ret
		.BYTE	_e,_le,_c,_t,_r,_on,_i,_c,_s_,_st,_o,_re,_col,__the,__,_T,_V,__,_was,_ret
		.BYTE	_s,_h,_ow,_ing,__,_Army,__,_he,_l,_i,_c,_o,_p,_t,_er,_s_,_and,__a,_ret
		.BYTE	_re,_p,_or,_t,_er,__,_was,__t,_a,_l,_k,_ing,_dot,_eol
_sc12_msg01:
		.BYTE	_R,_e,_p,_or,_t,_er,_ddt_,_an0,_W,_hat,__,_c,_ou,_l,_d_,_be,_ret
		.BYTE	_ha,_p,_p,_en,_ing,__,_to_,_N,_e,_o,_str,_T,_ok,_y,_o,_que,__,_F,_ro,_m,_ret
		.BYTE	_t,_he,_se,__i,_m,_a,_g,_e,_s,_col,__w,_e_,_se,_e_,_w,_hat,_ret
		.BYTE	_a,_p,_p,_e,_ar,_s_,_to_,_be,__a,__,_h,_o,_st,__of,_ret
		.BYTE	_m,_i,_l,_it,_ar,_y,__,_ve,_h,_i,_c,_le,_s_,_and,__a,__,_f,_i,_re,_dot,_aof,_eol
_sc12_msg02:
		.BYTE	_R,_e,_p,_or,_t,_er,_ddt_,_an0,_A,_n,_d,_dot_dot_dot,__w,_h,_o,__,_c,_ou,_l,_d,_ret
		.BYTE	_this,__,_you,_n,_g,__,_m,_an,__,_be,_que,__,_I,_s_,_he,_ret
		.BYTE	_f,_ight,_ing,__a,_g,_a,_in,_st,__the,_ret
		.BYTE	_c,_ou,_p,__,_d,_apo,_e,_t,_at,_apo_s,__t,_ro,_o,_p,_s,__a,_ll,__,_b,_y,_ret
		.BYTE	_h,_i,_m,_se,_l,_f,_que,_aof,_eol
_sc12_msg03:
		.BYTE	_R,_e,_p,_or,_t,_er,_ddt_,_an0,_L,_i,_st,_en,_er,_s,_col,__t,_r,_y,__t,_o,_ret
		.BYTE	_be,__,_st,_r,_on,_g,_er,__t,_h,_an,__the,_se,_ret
		.BYTE	_s,_o,_l,_d,_i,_er,_s,_col,__w,_h,_o,__,_are,__,_f,_o,_ll,_ow,_ing,_ret
		.BYTE	_u,_n,_j,_u,_st,__,_or,_d,_er,_s_,_to_,_s,_h,_u,_t_,_u,_s_,_d,_ow,_n,_dot,_ret
		.BYTE	_The,_y,__,_are,__t,_r,_a,_m,_p,_l,_ing,__the,__,_f,_re,_ed,_o,_m,_ret
		.BYTE	_of,__the,__,_p,_re,_s,_s,_exc,_aof,_eol
_sc12_msg04:
		.BYTE	_It_apo_s,__the,__,_b,_r,_id,_g,_e,_col,__,_he,_apo_s,__,_c,_ro,_s,_s,_ing,_ret
		.BYTE	_t,_he,__,_b,_r,_id,_g,_e,_dot,_ret
		.BYTE	_ret
		.BYTE	__,__,__,__,__,__,__,_The,__,_Army,_apo_s,__,_her,_e_,_t,_oo,_dot,_ret
		.BYTE	_ret
		.BYTE	_The,_y,_apo,_re,__,_he,_ad,_ed,__,_for,__the,__,_O,_l,_y,_m,_p,_i,_c,_ret
		.BYTE	_G,_r,_ou,_n,_d,_s,_exc,_eol
_sc12_msg05:
		.BYTE	_S,_t,_u,_n,_n,_ed,__,_on,_l,_oo,_k,_er,_s_,_w,_e,_re,_ret
		.BYTE	_s,_p,_e,_a,_k,_ing,__a,_m,_on,_g,_st,__the,_m,_se,_l,_ve,_s,_col,_ret
		.BYTE	_w,_a,_l,_k,_ing,__of,_f,__i,_n,__g,_r,_ou,_p,_s,_dot,_eol
_sc12_msg06:
		.BYTE	_I_,_c,_a,_me,__,_to_,_t,_he,__,_b,_i,_k,_e_,_st,_or,_a,_g,_e,_ret
		.BYTE	_are,_a,__a,_t,__s,_c,_h,_oo,_l,_dot,_eol
_sc12_msg07:
		.BYTE	_Kai,_ddt_,_You_apo_re,__,_re,_a,_ll,_y,__g,_on,_n,_a,__g,_o,_ret
		.BYTE	_b,_y,__,_you,_r,_se,_l,_f,_que,_eol
_sc12_msg08:
		.BYTE	_Kai,_ddt_,_Kaneda,_col,__w,_her,_e_,_are,__,_you,_ret
		.BYTE	_e,_ve,_n,__g,_o,_ing,_que,__,_I_,_k,_n,_ow,__,_you,__w,_an,_t,__t,_o,_ret
		.BYTE	_a,_ve,_n,_g,_e_,_Yamagata,_col,__,_b,_u,_t_,_w,_e_,_d,_on,_apo,_t,_ret
		.BYTE	_e,_ve,_n,__,_k,_n,_ow,__w,_her,_e_,_Tetsuo,__i,_s,_exc,_eol
_sc12_msg09:
		.BYTE	_I_,_he,_ad,_ed,__,_for,__the,__,_O,_l,_y,_m,_p,_i,_c,_ret
		.BYTE	_G,_r,_ou,_n,_d,_s,_dot,_eol
_sc12_msg0A:
		.BYTE	_A,_l,_on,_g,__the,__,_h,_i,_g,_h,_w,_a,_y,_col,__,_I_,_s,_a,_w,__,_r,_u,_in,_s,_ret
		.BYTE	_of,__,_Army,__t,_an,_k,_s,__t,_hat,__,_ha,_d_,_be,_en,_ret
		.BYTE	_d,_e,_m,_o,_l,_i,_s,_h,_ed,__,_b,_y,__,_Tetsuo,_dot,_eol
_sc12_msg0B:
		.BYTE	_R,_ad,_i,_o,_ddt_,_The,__s,_u,_b,_j,_e,_c,_t_,_ha,_s,__a,_r,_r,_i,_v,_ed,_ret
		.BYTE	_2,__,_m,_i,_le,_s,__s,_ou,_t,_h,__of,__the,__,_O,_l,_y,_m,_p,_i,_c,_ret
		.BYTE	_C,_on,_st,_r,_u,_c,_t,_i,_on,__,_S,_it,_e,_exc,__,_O,_u,_r,__,_for,_c,_e,_s,_ret
		.BYTE	_ha,_ve,__,_be,_en,__a,_l,_m,_o,_st,__,_c,_o,_m,_p,_le,_t,_e,_l,_y,_ret
		.BYTE	_w,_i,_p,_ed,__,_ou,_t,_dot_dot_dot,_eol
_sc12_msg0C:
		.BYTE	_L,_oo,_k,_s_,_l,_i,_k,_e_,_it,__,_was,__,_d,_e,_st,_ro,_y,_ed,__,_b,_y,_ret
		.BYTE	_Tetsuo,_apo_s,__s,_h,_o,_c,_k,__w,_a,_ve,_dot,__,_C,_or,_p,_se,_s,_ret
		.BYTE	_l,_it,_t,_er,_ed,__the,__g,_r,_ou,_n,_d_,_w,_her,_e_,_it,_ret
		.BYTE	_ha,_d_,_ro,_ll,_ed,_dot,_eol
_sc12_msg0D:
		.BYTE	_It_apo_s,__a,_n,__i,_n,_f,_an,_t,_r,_y,_str,_m,_o,_d,_e,_l,__,_laser,_ret
		.BYTE	_be,_a,_m,_dot,_eol
_sc12_msg0E:
		.BYTE	_Kaneda,_ddt_,_W,_it,_h,__,_this,__t,_h,_ing,_col,_ret
		.BYTE	_I_,_be,_t_,_I_,_c,_an,__,_be,_a,_t_,_Tetsuo,_exc,_eol
_sc12_msg0F:
		.BYTE	_It_apo_s,__a,__,_d,_e,_st,_ro,_y,_ed,__,_laser,_ret
		.BYTE	_b,_r,_i,_g,_ad,_e,_dot,_eol
_sc12_msg10:
		.BYTE	_The,__,_O,_l,_y,_m,_p,_i,_c,__,_G,_r,_ou,_n,_d,_s_,_are,__,_j,_u,_st,_ret
		.BYTE	_a,__,_b,_it,__,_f,_u,_r,_t,_her,_dot,_eol
_sc12_msg11:
		.BYTE	_A,_l,_on,_g,__,_on,_e_,_s,_id,_e_,_of,__the,__,_O,_l,_y,_m,_p,_i,_c,_ret
		.BYTE	_G,_r,_ou,_n,_d,_s,__i,_s,__a,__,_se,_c,_re,_t_,_en,_t,_r,_an,_c,_e,_ret
		.BYTE	_for,__the,__,_Army,_dot,_eol
_sc12_msg12:
		.BYTE	_A,_b,_o,_ve,__t,_hat,__g,_i,_an,_t_,_f,_ro,_z,_en,_ret
		.BYTE	_c,_a,_p,_s,_u,_le,_col,__,_Tetsuo,__,_and,__,_Kei,__w,_e,_re,_ret
		.BYTE	_f,_a,_c,_ing,__of,_f,_dot,_eol
_sc12_msg13:
		.BYTE	_Tetsuo,_ddt_,_an0,_Y,_ou,__,_were_,_t,_he,__,_on,_e_,_w,_h,_o,_ret
		.BYTE	_c,_a,_me,__,_with,__,_Kaneda,_dot_dot_dot,_aof,_eol
_sc12_msg14:
		.BYTE	_Kei,_ddt_,_I_,_w,_on,_apo,_t_,_be,__a,_b,_le,__t,_o,_ret
		.BYTE	_c,_on,_t,_a,_in,__,_his,__,_p,_ow,_er,__,_m,_u,_c,_h,_ret
		.BYTE	_l,_on,_g,_er,_dot_dot_dot,_eol
_sc12_msg15:
		.BYTE	_I,_n,__the,__,_c,_o,_l,_d_,_w,_in,_d,_s,_col,__the,__t,_w,_o,_ret
		.BYTE	_u,_n,_le,_a,_s,_h,_ed,__s,_h,_o,_c,_k,__w,_a,_ve,_s,_exc,_ret
		.BYTE	_ret
		.BYTE	_S,_p,_ar,_k,_s_,_f,_le,_w,__of,_f,__,_b,_o,_t,_h,__of,__the,_m,_dot,_eol
_sc12_msg16:
		.BYTE	_The,__a,_u,_r,_a,__,_around,__,_Kei,__,_v,_an,_i,_s,_h,_ed,_col,_ret
		.BYTE	_and,__s,_he,__,_f,_e,_ll,_dot,_eol
_sc12_msg17:
		.BYTE	_W,_e_,_c,_ou,_l,_d_,_se,_e,__the,__,_c,_on,_t,_en,_t,_s_,_of,_ret
		.BYTE	_t,_he,__,_c,_a,_p,_s,_u,_le,_dot,__,_I,_n,_s,_id,_e_,_it,__w,_e,_re,_ret
		.BYTE	_s,_p,_her,_e,_s_,_ro,_ll,_ing,__,_around,_dot,_eol
_sc12_msg18:
		.BYTE	_Tetsuo,_apo_s,__s,_h,_o,_c,_k,__w,_a,_ve,__,_c,_a,_u,_s,_ed,__a,_ret
		.BYTE	_s,_a,_m,_p,_le,__,_c,_a,_se,__,_to_,_f,_a,_ll,__,_ou,_t_,_of,__a,_ret
		.BYTE	_s,_p,_her,_e,_dot,_ret
		.BYTE	_ret
		.BYTE	_Tetsuo,_ddt_,_W,_hat,_apo_s,__,_this,_que,_eol
_sc12_msg19:
		.BYTE	_Colonel,_ddt_,_T,_hat,__i,_s_,_Akira,_dot_dot_dot,_ret
		.BYTE	_The,__,_ve,_r,_y,__s,_a,_me,__,_Akira,__,_you,__w,_an,_t,_ed,_ret
		.BYTE	_to_,_me,_e,_t,_exc,_eol
_sc12_msg1A:
		.BYTE	_Colonel,_ddt_,_A,_f,_t,_er,__,_he,__a,_w,_a,_k,_en,_ed,_col,__w,_e,_ret
		.BYTE	_t,_oo,_k,__,_his,__,_b,_o,_d,_y,__,_and,__,_r,_an,__,_e,_ve,_r,_y,_ret
		.BYTE	_c,_on,_c,_e,_i,_v,_a,_b,_le,__t,_e,_st,__,_and,_ret
		.BYTE	_e,_x,_p,_er,_i,_me,_n,_t_,_on,__,_it,_dot,_eol
_sc12_msg1B:
		.BYTE	_Colonel,_ddt_,_The,__s,_c,_i,_en,_t,_i,_st,_s,_ret
		.BYTE	_in,_v,_o,_l,_v,_ed,__i,_n,__,_this,__,_en,_i,_g,_m,_a,_ret
		.BYTE	_en,_c,_l,_o,_s,_ed,__a,_ll,__,_d,_at,_a,__the,_y,_ret
		.BYTE	_g,_at,_her,_ed,_col,__a,_l,_on,_g,__,_with,__s,_a,_m,_p,_le,_s,_col,_ret
		.BYTE	_and,__,_en,_t,_r,_u,_st,_ed,__the,_m,__,_to_,_f,_u,_t,_u,_re,_ret
		.BYTE	_g,_en,_er,_at,_i,_on,_s_,_b,_y,__,_p,_re,_s,_er,_v,_ing,__the,_m,_ret
		.BYTE	_in,__,_c,_r,_y,_o,_g,_en,_i,_c,__,_c,_a,_p,_s,_u,_le,_s,_dot,_eol
_sc12_msg1C:
		.BYTE	_Colonel,_ddt_,_an0,_Akira,__i,_s,__a,_l,_re,_ad,_y,_ret
		.BYTE	_d,_e,_ad,_dot,__,_A,_re,__,_you,__s,_at,_i,_s,_f,_i,_ed,_col,_ret
		.BYTE	_Tetsuo,_que,_exc,_aof,_eol
_sc12_msg1D:
		.BYTE	_Tetsuo,_ddt_,_an0,_S,_h,_u,_t_,_u,_p,_exc,__,_T,_his,__i,_s,_n,_apo,_t,_ret
		.BYTE	_t,_he,__t,_i,_me,__,_for,__,_you,_r,_ret
		.BYTE	_s,_c,_i,_en,_c,_e_,_b,_u,_ll,_s,_h,_it,_exc,_aof,_eol
_sc12_msg1E:
		.BYTE	_Colonel,_ddt_,_an0,_N,_ow,_col,__,_c,_o,_me,__,_b,_a,_c,_k,_ret
		.BYTE	_with,__,_u,_s,_exc,_aof,_eol
_sc12_msg1F:
		.BYTE	_I_,_st,_o,_p,_p,_ed,__,_m,_y,__,_b,_i,_k,_e,_col,__,_and,__,_l,_oo,_k,_ed,_ret
		.BYTE	_o,_ve,_r,__the,__,_are,_a,_dot,_eol
_sc12_msg20:
		.BYTE	_A,_r,_m,_or,_ed,__,_ve,_h,_i,_c,_le,_s_,_were_,_a,_l,_on,_g,_ret
		.BYTE	_on,_e_,_s,_id,_e_,_of,__the,__,_st,_ad,_i,_u,_m,_col,__,_and,_ret
		.BYTE	_t,_he,_i,_r,__,_c,_o,_m,_m,_and,_er,_apo_s,__,_v,_o,_i,_c,_e_,_e,_c,_h,_o,_ed,_ret
		.BYTE	_t,_h,_r,_ou,_g,_h,__the,__,_are,_a,__,_v,_i,_a,__a,_ret
		.BYTE	_me,_g,_a,_p,_h,_on,_e,_dot,_eol
_sc12_msg21:
		.BYTE	_I_,_he,_l,_d,__the,__,_laser,__,_be,_a,_m,__a,_t_,_m,_y,_ret
		.BYTE	_s,_id,_e,_col,__,_and,__,_p,_re,_s,_s,_ed,__the,__,_p,_ow,_er,_ret
		.BYTE	_s,_w,_it,_c,_h,__,_on,__the,__,_b,_i,_k,_e,_dot,_eol
_sc12_msg22:
		.BYTE	_Tetsuo,_ddt_,_an0,_D,_i,_e,_exc,_aof,_eol
_sc12_msg23:
		.BYTE	_W,_h,_i,_le,__w,_at,_c,_h,_ing,__,_m,_y,__s,_id,_e,_col,__,_I_,_m,_ad,_e,_ret
		.BYTE	_m,_y,__w,_a,_y,__,_for,_w,_ar,_d,_dot,_eol
_sc12_msg24:
		.BYTE	_Kai,_ddt_,_B,_e,_t,_t,_er,__w,_a,_it,__,_and,__,_se,_e_,_w,_hat,_ret
		.BYTE	_ha,_p,_p,_en,_s,_dot,_ret
		.BYTE	_H,_e,_y,_col,__,_Kaneda,_dot_dot_dot,_eol
_sc12_msg25:
		.BYTE	_Kaneda,_ddt_,_I_,_be,_t_,_he,__w,_an,_t,_s_,_this,_dot_dot_dot,_eol
_sc12_msg26:
		.BYTE	_A,__s,_u,_s,_p,_i,_c,_i,_ou,_s,_l,_y,__,_l,_ar,_g,_e_,_c,_a,_p,_s,_u,_le,_ret
		.BYTE	_c,_a,_me,__i,_n,_to_,_v,_i,_e,_w,_dot,_eol
_sc12_msg27:
		.BYTE	_Kei,__,_was,__the,__,_on,_e_,_w,_h,_o,__,_h,_ad,_ret
		.BYTE	_st,_o,_p,_p,_ed,__the,__s,_h,_o,_c,_k,__w,_a,_ve,_dot,_eol
_sc12_msg28:
		.BYTE	_B,_e,_for,_e_,_l,_on,_g,_col,__,_on,_e_,_of,__the,_ret
		.BYTE	_c,_a,_p,_s,_u,_le,_s_,_c,_r,_a,_c,_k,_ed,__,_and,__,_be,_g,_an,_ret
		.BYTE	_le,_a,_k,_ing,__,_c,_o,_l,_d_,_a,_i,_r,_dot,_eol
_sc12_msg29:
		.BYTE	_Colonel,_ddt_,_dot_dot_dot,_a,_ll,__t,_hat,_apo_s,__,_le,_f,_t,_ret
		.BYTE	_of,__,_h,_i,_m,__i,_s,__i,_n,__the,_re,_dot,_eol
;_sc12_msg2A:
;		.BYTE	_N,_e,_ar,__the,__,_se,_t,_t,_ing,__s,_u,_n,_col,__a,_ret
;		.BYTE	_g,_l,_i,_st,_en,_ing,__,_st,_ar,__,_c,_ou,_l,_d_,_be,__,_se,_en,_dot,_ret
;		.BYTE	_ret
;		.BYTE	_Army,_ddt_,_The,__,_S,_O,_L,__s,_at,_e,_ll,_it,_e,_dot_dot_dot,_eol
;_sc12_msg2B:
;		.BYTE	_Colonel,_ddt_,_an0,_Tetsuo,__,_d,_e,_st,_ro,_y,_ed,__the,_ret
;		.BYTE	_S,_O,_L,__s,_at,_e,_ll,_it,_e,_dot_dot_dot,__,_H,_e,_apo_s,__t,_hat,_ret
;		.BYTE	_p,_ow,_er,_f,_u,_l,__a,_l,_re,_ad,_y,_que,_aof,_eol
;_sc12_msg2C:
;		.BYTE	_Kei,_ddt_,_The,__,_k,_in,_d_,_of,__,_p,_ow,_er,__,_you,_ret
;		.BYTE	_ha,_ve,__,_m,_u,_st,_n,_apo,_t_,_be,__,_u,_s,_ed,_exc,_eol
;_sc12_msg2D:
;		.BYTE	_Tetsuo,_ddt_,_W,_hat,_que,_eol
;_sc12_msg2E:
;		.BYTE	_Tetsuo,_ddt_,_Damn,__,_k,_id,_s,_dot_dot_dot,__,_you,_apo,_re,_ret
;		.BYTE	_a,_ll,__,_j,_u,_st,__,_k,_id,_s,_dot_dot_dot,_eol

		SECTION_END		F12
