
		SECTION_START	F5

		MSG_START	_scene5_msg_lib
		MSG_IDX	_sc5_msg00
		MSG_IDX	_sc5_msg01
		MSG_IDX	_sc5_msg02						; reused
		MSG_IDX	_sc5_msg03
		MSG_IDX	_sc5_msg04
		MSG_IDX	_sc5_msg05
		MSG_IDX	_sc5_msg06
;		MSG_IDX	_sc5_msg07						; -unused-
		MSG_IDX	_sc5_msg08
		MSG_IDX	_sc5_msg09
		MSG_IDX	_sc5_msg0A
		MSG_IDX	_sc5_msg0B
		MSG_IDX	_sc5_msg0C
		MSG_IDX	_sc5_msg0D
		MSG_IDX	_sc5_msg0E
		MSG_IDX	_sc5_msg0F
		MSG_IDX	_sc5_msg10
		MSG_IDX	_sc5_msg11
		MSG_IDX	_sc5_msg12
		MSG_IDX	_sc5_msg13
		MSG_IDX	_sc5_msg14
		MSG_IDX	_sc5_msg15
		MSG_IDX	_sc5_msg16						; reused
		MSG_IDX	_sc5_msg17						; reused
		MSG_IDX	_sc5_msg18						; reused
		MSG_IDX	_sc5_msg19
		MSG_IDX	_sc5_msg1A
		MSG_IDX	_sc5_msgB3						; scene 5 msg
_sc5_msg00:
		.BYTE	_F,_i,_r,_st,_col,__w,_e_,_c,_he,_c,_k,_ed,__,_ou,_r,__,_h,_an,_g,_ou,_t,_dot,_ret
		.BYTE	_ret
		.BYTE	_O,_w,_n,_er,_ddt_,_an0,_O,_h,_col,__,_you,__s,_c,_are,_d_,_me,_dot,_ret
		.BYTE	_W,_hat,__,_d,_o,__,_you,__g,_u,_y,_s_,_w,_an,_t,_que,_aof,_eol
_sc5_msg01:
		.BYTE	_O,_w,_n,_er,_ddt_,_an0,_H,_e,_y,_col,__,_you,_apo,_re,__,_b,_a,_c,_k,_ret
		.BYTE	_a,_l,_re,_ad,_y,_dot,__,_D,_i,_d_,_you,__,_f,_in,_d_,_Tetsuo,_que,_aof,_eol
_sc5_msg02:
		.BYTE	_O,_w,_n,_er,_ddt_,_an0,_H,_e,_y,_exc,__,_W,_a,_it,_exc,_aof,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_N,_o,__w,_a,_y,_exc,_eol
_sc5_msg03:
		.BYTE	_W,_e_,_re,_a,_c,_h,_ed,__,_se,_c,_t,_or,__,_num,_dot,_eol
_sc5_msg04:
		.BYTE	_B,_e,_for,_e_,_re,_t,_u,_r,_n,_ing,_col,__w,_e_,_t,_r,_i,_ed,__t,_o,_ret
		.BYTE	_f,_in,_d_,_Tetsuo,_apo_s,__,_l,_o,_c,_at,_i,_on,_dot,_eol
_sc5_msg05:
		.BYTE	_Man,_ddt_,_an0,_O,_h,_col,__,_Tetsuo,_que,__,_H,_e_,_w,_en,_t,_ret
		.BYTE	_t,_ow,_ar,_d_,_se,_c,_t,_or,__,_2,_dot,_aof,_eol
_sc5_msg06:
		.BYTE	_Man,_ddt_,_an0,_Y,_ou,__,_j,_er,_k,_s_,_are,__w,_a,_y,_ret
		.BYTE	_t,_oo,__,_l,_ou,_d,_exc,_aof,_eol
;_sc5_msg07:
;		.BYTE	_Man,_ddt_,_an0,_Tetsuo,_que,__,_N,_o,__i,_d,_e,_a,_dot,_aof,_eol
_sc5_msg08:
		.BYTE	_Man,_ddt_,_an0,_Tetsuo,_que,__,_H,_e_,_j,_u,_st,__w,_en,_t,_ret
		.BYTE	_t,_ow,_ar,_d_,_se,_c,_t,_or,__,_3,_dot,_aof,_eol
_sc5_msg09:
		.BYTE	_Man,_ddt_,_an0,_W,_hat,_apo_s,__,_you,_r,__,_r,_u,_s,_h,_que,_aof,_eol
_sc5_msg0A:
		.BYTE	_Man,_ddt_,_an0,_I,_f,__,_you,_apo,_re,__,_l,_oo,_k,_ing,__,_for,_ret
		.BYTE	_Tetsuo,_col,__,_I_,_t,_h,_in,_k,__,_he,__w,_en,_t,__t,_ow,_ar,_d,_ret
		.BYTE	_se,_c,_t,_or,__,_4,_dot,_aof,_eol
_sc5_msg0B:
		.BYTE	_Man,_ddt_,_an0,_H,_e,_y,_col,__g,_o,__a,_w,_a,_y,_exc,_ret
		.BYTE	_dot_dot_dot,_U,_n,_le,_s,_s_,_you,__g,_o,_t,__s,_o,_me,__,_p,_i,_ll,_s,_exc,_aof,_eol
_sc5_msg0C:
		.BYTE	_Man,_ddt_,_an0,_T,_str,_t,_h,_an,_k,_s,_dot,__,_Y,_str,_you,_apo,_re,_ret
		.BYTE	_se,_ar,_c,_h,_in,_apo,__,_for,__s,_o,_me,_on,_e,_que,_aof,_eol
_sc5_msg0D:
		.BYTE	_W,_at,_er,_apo_s,__,_r,_u,_n,_n,_ing,__t,_h,_r,_ou,_g,_h,__the,_ret
		.BYTE	_c,_h,_an,_n,_e,_l,_col,__,_se,_p,_ar,_at,_ing,__the,__,_O,_l,_d,_ret
		.BYTE	_T,_ow,_n,__,_f,_ro,_m,__,_N,_e,_o,_str,_T,_ok,_y,_o,_dot,_eol
_sc5_msg0E:
		.BYTE	_It_apo_s,__,_N,_e,_o,_str,_T,_ok,_y,_o,_apo_s,__s,_l,_u,_m,_dot,__,_The,_re,_apo_s,_ret
		.BYTE	_a,__,_n,_oo,_d,_le,__s,_h,_o,_p,__,_and,__a,__,_d,_or,_m,_dot,_eol
_sc5_msg0F:
		.BYTE	_It_apo_s,__the,__,_ou,_t,_s,_k,_i,_r,_t,_s_,_of,_ret
		.BYTE	_N,_e,_o,_str,_T,_ok,_y,_o,_dot,__,_The,_re,__,_are,__,_l,_o,_t,_s,_ret
		.BYTE	_of,__,_f,_a,_c,_t,_or,_i,_e,_s_,_n,_e,_ar,_b,_y,_dot,_eol
_sc5_msg10:
		.BYTE	_Kaneda,_ddt_,_Y,_ou,__w,_ou,_l,_d,_n,_apo,_t_,_be,__s,_o,_ret
		.BYTE	_j,_u,_m,_p,_y,__i,_f,__,_you,__,_d,_id,_n,_apo,_t_,_ha,_ve,_ret
		.BYTE	_s,_o,_me,_t,_h,_ing,__,_to_,_h,_id,_e,_dot,__,_W,_h,_y,__,_d,_on,_apo,_t,_ret
		.BYTE	_you,__,_se,_ll,__,_n,_or,_m,_a,_l,__,_d,_r,_in,_k,_s_,_for,__a,_ret
		.BYTE	_c,_h,_an,_g,_e,_que,_eol
_sc5_msg11:
		.BYTE	_O,_w,_n,_er,_ddt_,_an0,_H,_ow,__,_apo,_b,_ou,_t_,_b,_u,_y,_ing,_ret
		.BYTE	_s,_o,_me,_t,_h,_ing,__,_for,__,_on,_c,_e,_exc,__,_T,_his,__i,_s,_n,_apo,_t,_ret
		.BYTE	_a,__,_d,_a,_m,_n,__,_h,_an,_g,_ou,_t,_exc,_aof,_ret
		.BYTE	_ret
		.BYTE	_Yamagata,_ddt_,_Y,_e,_a,_h,__,_r,_ight,_exc,__,_D,_r,_in,_k,_ret
		.BYTE	_you,_r,__,_d,_o,_g,__,_p,_i,_s,_s,_que,_eol
_sc5_msg12:
		.BYTE	_T,_hat,__,_b,_a,_st,_ar,_d_,_i,_s_,_h,_id,_ing,__,_p,_i,_ll,_s,_ret
		.BYTE	_u,_n,_d,_er,__,_his,__,_r,_ight,__,_h,_and,_dot,_eol
_sc5_msg13:
		.BYTE	_O,_w,_n,_er,_ddt_,_an0,_H,_e,_y,_col,__i,_f,__,_you,_apo,_re,_ret
		.BYTE	_l,_oo,_k,_ing,__,_for,__,_p,_i,_ll,_s,_col,__,_I_,_d,_on,_apo,_t,_ret
		.BYTE	_ha,_ve,__a,_n,_y,__,_m,_o,_re,_dot,_aof,_eol
_sc5_msg14:
		.BYTE	_O,_w,_n,_er,_ddt_,_an0,_I_,_t,_h,_in,_k,__,_Tetsuo,_ret
		.BYTE	_he,_ad,_ed,__t,_ow,_ar,_d_,_se,_c,_t,_or,__,_num,_dot,_aof,_eol
_sc5_msg15:
		.BYTE	_The,_re,_apo_s,__,_n,_o,__s,_i,_g,_n,__of,__,_Tetsuo,_dot,_eol
_sc5_msg16:
		.BYTE	_Man,_ddt_,_an0,_Y,_ou,__w,_a,_l,_t,_z,__i,_n,__,_her,_e,_ret
		.BYTE	_re,_e,_k,_ing,__of,__a,_l,_c,_o,_h,_o,_l,__,_with,__a,_ret
		.BYTE	_p,_o,_m,_p,_ou,_s,__a,_t,_t,_it,_u,_d,_e,_dot_dot_dot,__,_S,_h,_ow,__s,_o,_me,_ret
		.BYTE	_re,_s,_p,_e,_c,_t,_exc,_aof,_ret
		.BYTE	_ret
		.BYTE	_The,__,_m,_an,__s,_u,_d,_d,_en,_l,_y,__,_st,_r,_u,_c,_k,__,_m,_y,_ret
		.BYTE	_f,_a,_c,_e,_dot,__,_I,_t,__t,_u,_r,_n,_ed,__i,_n,_to_,_a,__,_b,_r,_a,_w,_l,_dot,_eol
_sc5_msg17:
		.BYTE	_Kai,_ddt_,_Kaneda,_exc,__,_It_apo_s,__the,__,_c,_o,_p,_s,_exc,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_R,_u,_n,__,_for,__,_it,_exc,_ret
		.BYTE	_ret
		.BYTE	_But,__w,_e_,_were_,_c,_a,_u,_g,_h,_t_,_b,_y,__the,_ret
		.BYTE	_p,_o,_l,_i,_c,_e,_dot,_eol
_sc5_msgB3:
		.BYTE	_O,_w,_n,_er,_ddt_,_an0,_Tetsuo,__,_he,_ad,_ed,__t,_ow,_ar,_d,_ret
		.BYTE	_S,_e,_c,_t,_or,__,_num,_dot,_aof,_ret
		.BYTE	_ret
		.BYTE	_Kai,_ddt_,_H,_u,_r,_r,_y,__,_u,_p,_col,__w,_e,_apo,_re,__,_was,_t,_ing,_ret
		.BYTE	_t,_i,_me,_exc,_eol
;		.BYTE	_ret											; let's change here some quest logic, will ask for pills when needed it
;		.BYTE	_Kaneda,_ddt_,_S,_or,_r,_y,_dot,__,_H,_e,_y,_col,__,_c,_an,__,_I_,_ha,_ve,_ret
;		.BYTE	_t,_h,_o,_se,__,_p,_i,_ll,_s,_que,_eol
_sc5_msg18:
;		.BYTE	_Kaneda,__,_was,__s,_en,_t_,_to_,_a,__,_re,_for,_m,_ret
;		.BYTE	_s,_c,_h,_oo,_l,_dot,_eol
		.BYTE	_Kaneda,_ddt_,_S,_or,_r,_y,_dot,__,_H,_e,_y,_col,__,_c,_an,__,_I_,_ha,_ve,_ret		; reuse this unused message to not to break something by now
		.BYTE	_t,_h,_o,_se,__,_p,_i,_ll,_s,_que,_eol
_sc5_msg19:
		.BYTE	_Man,_ddt_,_an0,_You_apo_re,__,_l,_oo,_k,_ing,__,_for,__t,_hat,_ret
		.BYTE	_g,_u,_y,_que,__,_H,_e_,_w,_en,_t,__t,_ow,_ar,_d,__the,_ret
		.BYTE	_f,_a,_c,_t,_or,_i,_e,_s,_dot,_aof,_eol
_sc5_msg1A:
		.BYTE	_Man,_ddt_,_an0,_H,_e,_he,_dot_dot_dot,__,_S,_o,__,_you,__,_b,_r,_ou,_g,_h,_t,_ret
		.BYTE	_me,__s,_o,_me,__,_p,_i,_ll,_s,_que,_aof,_eol

		SECTION_END		F5
