
		SECTION_START	F11

		MSG_START	_scene11_msg_lib
		MSG_IDX	_sc11_msg00
		MSG_IDX	_sc11_msg01
		MSG_IDX	_sc11_msg02
		MSG_IDX	_sc11_msg03
		MSG_IDX	_sc11_msg04
		MSG_IDX	_sc11_msg05
		MSG_IDX	_sc11_msg06
		MSG_IDX	_sc11_msg07
		MSG_IDX	_sc11_msg08
		MSG_IDX	_sc11_msg09
		MSG_IDX	_sc11_msg0A
		MSG_IDX	_sc11_msg0B
		MSG_IDX	_sc11_msg0C
		MSG_IDX	_sc11_msg0D
		MSG_IDX	_sc11_msg0E
		MSG_IDX	_sc11_msg0F
		MSG_IDX	_sc11_msg10
		MSG_IDX	_sc11_msg11
		MSG_IDX	_sc11_msg12
		MSG_IDX	_sc11_msg13
		MSG_IDX	_sc11_msg14
		MSG_IDX	_sc11_msg15
		MSG_IDX	_sc11_msg16
		MSG_IDX	_sc11_msg17
		MSG_IDX	_sc11_msg18
		MSG_IDX	_sc11_msg19
		MSG_IDX	_sc11_msg1A
		MSG_IDX	_sc11_msg1B
		MSG_IDX	_sc11_msg1C
		MSG_IDX	_sc11_msg1D
		MSG_IDX	_sc11_msg1E
		MSG_IDX	_sc11_msg1F
		MSG_IDX	_sc11_msg20
		MSG_IDX	_sc11_msg21
		MSG_IDX	_sc11_msg22
		MSG_IDX	_sc11_msg23
		MSG_IDX	_sc11_msg24
		MSG_IDX	_sc11_msg25
		MSG_IDX	_sc11_msg26
		MSG_IDX	_sc11_msg27
		MSG_IDX	_sc11_msg28
		MSG_IDX	_sc11_msg95					; scene 11 msg
		MSG_IDX	_sc11_msg98					; scene 11 msg
_sc11_msg00:
		.BYTE	_L,_e,_a,_v,_ing,__the,__,_l,_a,_b,_col,__,_Kei,__,_and,__,_I,_ret
		.BYTE	_w,_en,_t_,_to_,_t,_he,__,_h,_an,_g,_ou,_t,_dot,_eol
_sc11_msg01:
		.BYTE	_W,_e_,_w,_en,_t_,_with,__,_Kai,__,_to_,_t,_he,_ret
		.BYTE	_r,_i,_ve,_r,__,_b,_an,_k,_dot,_eol
_sc11_msg02:
		.BYTE	_Kai,_ddt_,_an0,_I_,_w,_en,_t_,_to_,_t,_he,__,_u,_s,_u,_a,_l,_ret
		.BYTE	_h,_an,_g,_ou,_t_,_with,__,_Yamagata,_dot,__,_T,_hat,_apo_s,_ret
		.BYTE	_w,_h,_en,__w,_e_,_f,_ou,_n,_d_,_it,_dot_dot_dot,__,_The,__i,_n,_s,_id,_e,_ret
		.BYTE	_of,__the,__,_b,_ar,__,_was,__t,_r,_a,_s,_h,_ed,_col,__,_and,_ret
		.BYTE	_t,_he,__,_ow,_n,_er,__,_was,__,_d,_e,_ad,_dot_dot_dot,_aof,_eol
_sc11_msg03:
		.BYTE	_Kai,_ddt_,_an0,_T,_hat,__,_b,_a,_st,_ar,_d_,_Tetsuo,__,_j,_u,_st,_ret
		.BYTE	_s,_at,__the,_re,__i,_n,__the,__,_r,_u,_b,_b,_le,_col,_ret
		.BYTE	_l,_a,_u,_g,_h,_ing,__,_his,__a,_s,_s_,_of,_f,_exc,_aof,_eol
_sc11_msg04:
		.BYTE	_Kai,_ddt_,_an0,_H,_e_,_was,__,_l,_a,_u,_g,_h,_ing,__,_l,_i,_k,_e,_ret
		.BYTE	_n,_o,_t,_h,_ing,__,_ha,_p,_p,_en,_ed,_exc,__,_A,_n,_d_,_he,_ret
		.BYTE	_re,_a,_ll,_y,__w,_an,_t,_ed,__,_to_,_k,_n,_ow,__w,_her,_e,_ret
		.BYTE	_you,_r,__,_b,_i,_k,_e_,_was,_dot,_aof,_eol
_sc11_msg05:
		.BYTE	_Kai,_ddt_,_an0,_S,_o,__,_Yamagata,__,_y,_e,_ll,_ed,__a,_t,_ret
		.BYTE	_h,_i,_m,_col,__,_c,_l,_i,_m,_b,_ing,__i,_n,_to_,_t,_he,__,_p,_i,_le,__of,_ret
		.BYTE	_r,_u,_b,_b,_le,_dot,__,_But,__the,_n,__,_Tetsuo,_apo_s,__,_ha,_i,_r,_ret
		.BYTE	_st,_oo,_d_,_u,_p,__,_on,__,_en,_d,_dot_dot_dot,_aof,_eol
_sc11_msg06:
		.BYTE	_Kai,_ddt_,_an0,_Tetsuo,__,_u,_s,_ed,__s,_o,_me,__,_k,_in,_d_,_of,_ret
		.BYTE	_w,_e,_i,_r,_d_,_p,_ow,_er,__,_to_,_h,_o,_l,_d_,_Yamagata,_dot,_ret
		.BYTE	_H,_e_,_c,_r,_i,_ed,__,_ou,_t,__i,_n,__,_p,_a,_in,_dot_dot_dot,__,_and,_ret
		.BYTE	_Tetsuo,__,_c,_r,_u,_s,_h,_ed,__,_his,__s,_k,_u,_ll,_dot,_aof,_eol
_sc11_msg07:
		.BYTE	_Kaneda,_ddt_,_W,_e,_apo,_ve,__a,_l,_w,_a,_y,_s_,_be,_en,_ret
		.BYTE	_t,_o,_g,_e,_t,_her,_dot,__,_I_,_k,_n,_ow,__,_e,_ve,_r,_y,_t,_h,_ing,_ret
		.BYTE	_a,_b,_ou,_t_,_h,_i,_m,_dot,_ret
		.BYTE	_dot_dot_dot,_A,_n,_d_,_I_apo,_ve,__a,_l,_w,_a,_y,_s_,_f,_e,_l,_t,__s,_or,_r,_y,_ret
		.BYTE	_for,__,_his,__s,_c,_re,_w,_str,_u,_p,_s,_dot_dot_dot,_eol
_sc11_msg08:
		.BYTE	_Kai,_ddt_,_an0,_T,_hat,_apo_s,__,_r,_ight,_dot_dot_dot,__,_H,_e_,_t,_oo,_k,_ret
		.BYTE	_you,_r,__,_b,_i,_k,_e_,_s,_o,_me,_p,_l,_a,_c,_e,_dot,_aof,_eol
_sc11_msg09:
		.BYTE	_I_,_g,_o,_t_,_on,_to_,_Yamagata,_apo_s,__,_b,_i,_k,_e,_col,_ret
		.BYTE	_w,_h,_i,_c,_h,__,_Kai,__,_ha,_d_,_b,_r,_ou,_g,_h,_t,_dot,_eol
_sc11_msg0A:
		.BYTE	_Kiyoko,_ddt_,_an0,_W,_e_,_w,_an,_t_,_you,__t,_o,_ret
		.BYTE	_he,_l,_p,__,_u,_s,_dot,_aof,_eol
_sc11_msg0B:
		.BYTE	_W,_h,_y,__i,_s_,_Kei,__i,_n,_v,_o,_l,_v,_ed,__,_with,_ret
		.BYTE	_t,_h,_o,_se,__,_k,_id,_s,_dot_dot_dot,_eol
_sc11_msg0C:
		.BYTE	_Kaneda,_ddt_,_an0,_T,_hat,_apo_s,__,_en,_ou,_g,_h,_dot,__,_C,_a,_ll,_ing,_ret
		.BYTE	_in,__,_p,_e,_o,_p,_le,__,_to_,_at,_t,_a,_c,_k,__,_Tetsuo,__i,_s,_ret
		.BYTE	_j,_u,_st,__s,_en,_d,_ing,__the,_m,__,_to_,_d,_i,_e,_dot_dot_dot,_aof,_eol
_sc11_msg0D:
		.BYTE	_Kei,_ddt_,_Y,_ou,_dot_dot_dot,__,_are,_dot_dot_dot,__,_A,_a,_h,_exc,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_an0,_Kei,_col,__w,_hat,__,_ha,_p,_p,_en,_ed,_que,_exc,_aof,_eol
_sc11_msg0E:
		.BYTE	_Kaneda,_ddt_,_You_apo_re,_dot_dot_dot,__,_f,_ro,_m,_ret
		.BYTE	_t,_hat,__,_n,_ight,_dot_dot_dot,_eol
_sc11_msg0F:
		.BYTE	_The,__,_k,_i,_d_,_e,_me,_r,_g,_ed,__,_f,_ro,_m,__the,__w,_at,_er,_ret
		.BYTE	_and,__a,_p,_p,_ro,_a,_c,_h,_ed,__,_Kei,_dot,_eol
_sc11_msg10:
		.BYTE	_Kaneda,_ddt_,_W,_hat,_apo,_re,__,_you,__,_d,_o,_ing,_ret
		.BYTE	_to_,_Kei,_que,_exc,_eol
_sc11_msg11:
		.BYTE	_I_,_w,_an,_t,_ed,__,_to_,_r,_u,_n,__,_u,_p,__,_to_,_h,_i,_m,_col,_ret
		.BYTE	_b,_u,_t,__s,_o,_me,_h,_ow,__,_m,_y,__,_b,_o,_d,_y,__,_re,_f,_u,_s,_ed,_ret
		.BYTE	_to_,_m,_o,_ve,_dot,_eol
_sc11_msg12:
		.BYTE	_Kaneda,_ddt_,_W,_a,_it,_exc,__,_Kei,_exc,_eol
_sc11_msg13:
		.BYTE	_Kai,_ddt_,_The,_y,__,_v,_an,_i,_s,_h,_ed,_dot,_eol
_sc11_msg14:
		.BYTE	_Kaneda,_ddt_,_T,_hat,__s,_on,__of,__a,__,_b,_it,_c,_h,_col,_ret
		.BYTE	_w,_her,_e,_apo,_d_,_he,__g,_o,_que,_eol
_sc11_msg15:
		.BYTE	_Kei,__,_and,__the,__,_k,_i,_d_,_ha,_d_,_b,_o,_t,_h,_ret
		.BYTE	_d,_i,_s,_a,_p,_p,_e,_are,_d,_dot,_eol
_sc11_msg16:
		.BYTE	_The,__w,_at,_er,__,_was,__,_c,_a,_l,_m,_dot_dot_dot,_eol
_sc11_msg17:
		.BYTE	_Kaneda,_ddt_,_It_apo_s,__a,_ll,__,_you,_r,__,_f,_a,_u,_l,_t,_ret
		.BYTE	_t,_hat,__,_Tetsuo,__,_c,_h,_an,_g,_ed,_exc,_ret
		.BYTE	_ret
		.BYTE	_I_,_be,_g,_an,__,_d,_ow,_n,__the,__s,_l,_o,_p,_e,_col,__,_b,_u,_t,_ret
		.BYTE	_s,_u,_d,_d,_en,_l,_y,__,_he,_ar,_d_,_a,__,_v,_o,_i,_c,_e,_dot,_eol
_sc11_msg18:
		.BYTE	_Kiyoko,_ddt_,_an0,_The,__,_p,_ow,_er,__i,_n,__,_Akira,__,_c,_an,_ret
		.BYTE	_e,_x,_i,_st,__i,_n,__a,_n,_y,_on,_e,_dot_dot_dot,_aof,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_H,_u,_h,_que,__,_W,_h,_o,_apo_s,__t,_hat,_que,_exc,_eol
_sc11_msg19:
		.BYTE	_Kiyoko,_ddt_,_an0,_But,__w,_h,_en,__t,_hat,__,_p,_ow,_er,_ret
		.BYTE	_a,_w,_a,_k,_en,_s,_dot_dot_dot,__,_W,_it,_h,_ou,_t,__a,_n,_y,_ret
		.BYTE	_w,_ar,_n,_ing,_col,__,_on,_e_,_m,_u,_st,__,_d,_e,_c,_id,_e_,_h,_ow,_ret
		.BYTE	_to_,_u,_se,__,_it,_dot_dot_dot,__,_T,_hat,__,_p,_er,_s,_on,__,_ha,_s,_ret
		.BYTE	_m,_ad,_e_,_his,__,_c,_h,_o,_i,_c,_e,_dot,_aof,_eol
_sc11_msg1A:
		.BYTE	_Kiyoko,_ddt_,_an0,_Tetsuo,__i,_s_,_ou,_r,_ret
		.BYTE	_n,_e,_w,_e,_st,__,_me,_m,_b,_er,_dot_dot_dot,_ret
		.BYTE	_H,_e,_apo_s,__,_on,_e_,_of,__,_u,_s,_dot_dot_dot,_aof,_eol
_sc11_msg1B:
		.BYTE	_Kaneda,_ddt_,_S,_o,__w,_h,_y,__i,_n,__the,__,_he,_ll,__,_d,_id,_ret
		.BYTE	_you,__t,_a,_k,_e_,_Kei,_que,_exc,_eol
_sc11_msg1C:
		.BYTE	_Kaneda,_ddt_,_an0,_B,_r,_ing,__,_Kei,__,_b,_a,_c,_k,_exc,_ret
		.BYTE	_Tetsuo,_apo_s,__,_N,_O,_T,__,_on,_e_,_of,__,_you,_exc,_ret
		.BYTE	_H,_e,_apo_s,__,_m,_y,__,_f,_r,_i,_en,_d,_exc,__,_I_apo,_ll,__,_d,_e,_a,_l,__,_with,_ret
		.BYTE	_h,_i,_m,__,_m,_y,_se,_l,_f,_exc,_aof,_eol
_sc11_msg1D:
		.BYTE	_Damn,__t,_hat,__,_Tetsuo,_col,_ret
		.BYTE	_w,_her,_e,_apo,_d_,_he,__g,_o,_que,_exc,_eol
_sc11_msg1E:
		.BYTE	_T,_his,__i,_s_,_for,__,_Yamagata,_dot,__,_J,_u,_st,__,_you,_ret
		.BYTE	_w,_a,_it,_col,__a,_l,_on,_g,__,_with,__,_m,_y,__,_b,_i,_k,_e_,_t,_hat,_ret
		.BYTE	_you,__w,_an,_t,_ed,__s,_o,__,_m,_u,_c,_h,_dot_dot_dot,_eol
_sc11_msg1F:
		.BYTE	_But,_col,__,_Kai,__,_was,__,_st,_and,_ing,__,_j,_u,_st,_ret
		.BYTE	_ou,_t,_s,_id,_e_,_of,__the,__,_h,_an,_g,_ou,_t,_dot,__,_H,_e_,_was,_ret
		.BYTE	_f,_r,_ight,_en,_ed,__a,_b,_ou,_t,__s,_o,_me,_t,_h,_ing,_dot_dot_dot,_eol
_sc11_msg20:
		.BYTE	_Kaneda,_ddt_,_W,_hat,_que,__,_Yamagata,_dot_dot_dot,_que,_eol
_sc11_msg21:
		.BYTE	_Kaneda,_ddt_,_M,_y,__,_b,_i,_k,_e,_dot_dot_dot,_que,_ret
		.BYTE	_Kai,_col,__,_c,_ou,_l,_d_,_you,__,_b,_r,_ing,_ret
		.BYTE	_Yamagata,_apo_s,__,_b,_i,_k,_e_,_for,__,_me,_que,_eol
_sc11_msg22:
		.BYTE	_Kai,_ddt_,_an0,_W,_hat,_apo,_re,__,_you,__,_d,_o,_ing,_que,_aof,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_I_apo,_m,__g,_o,_ing,__,_to_,_t,_a,_k,_e,_ret
		.BYTE	_this,__,_to_,_h,_i,_m,_dot_dot_dot,_eol
_sc11_msg23:
		.BYTE	_I_,_j,_u,_m,_p,_ed,__of,_f,__,_and,__,_st,_ar,_t,_ed,_ret
		.BYTE	_r,_u,_n,_n,_ing,_dot,_eol
_sc11_msg24:
		.BYTE	_I_,_he,_ar,_d_,_Kei,__s,_c,_re,_a,_m,__s,_o,_me,_w,_her,_e,_ret
		.BYTE	_u,_n,_d,_er,_g,_r,_ou,_n,_d,_dot,_eol
_sc11_msg25:
		.BYTE	_Kaneda,_ddt_,_an0,_D,_a,_m,_m,_it,_exc,_aof,_eol
_sc11_msg26:
		.BYTE	_Kai,_ddt_,_an0,_W,_h,_en,__,_I_,_s,_a,_w,__,_h,_i,_m,_col,__,_I_,_k,_n,_e,_w,_ret
		.BYTE	_s,_o,_me,_t,_h,_ing,__,_was,__w,_r,_on,_g,_dot,__,_H,_e_,_was,_ret
		.BYTE	_w,_e,_ar,_ing,__s,_o,_me,__,_k,_in,_d_,_of,__,_h,_o,_s,_p,_it,_a,_l,_ret
		.BYTE	_g,_ow,_n,_dot,__,_Yamagata,__,_ha,_d_,_a,_l,_s,_o,__,_he,_ar,_d,_ret
		.BYTE	_you,__,_were_,_g,_on,_n,_a,__g,_o,__,_and,__,_re,_s,_c,_u,_e,_ret
		.BYTE	_h,_i,_m,_dot,_aof,_eol
_sc11_msg27:
		.BYTE	_Kai,_ddt_,_R,_ight,__a,_f,_t,_er,__t,_hat,_col,_ret
		.BYTE	_Y,_a,_m,_a,_g,_a,_str,_str,_str,_eol
_sc11_msg28:
		.BYTE	_Kiyoko,_ddt_,_an0,_W,_hat,__t,_hat,__,_p,_er,_s,_on,__,_k,_n,_ow,_s,_ret
		.BYTE	_i,_s,__a,_l,_s,_o,__,_ou,_r,__,_re,_s,_p,_on,_s,_i,_b,_i,_l,_it,_y,_dot_dot_dot,_aof,_eol
_sc11_msg95:
		.BYTE	_Kai,_ddt_,_Kaneda,_dot_dot_dot,_eol
_sc11_msg98:
		.BYTE	_I_,_l,_oo,_k,_ed,__i,_n,_to_,_t,_he,__,_r,_i,_ve,_r,_ret
		.BYTE	_be,_l,_ow,_dot_dot_dot,_eol

		SECTION_END		F11
