
		SECTION_START	F8

		MSG_START	_scene8_msg_lib
		MSG_IDX	_sc8_msg00
		MSG_IDX	_sc8_msg01
;		MSG_IDX	_sc8_msg02							; -unused-
		MSG_IDX	_sc8_msg03
		MSG_IDX	_sc8_msg04
		MSG_IDX	_sc8_msg05
		MSG_IDX	_sc8_msg06
		MSG_IDX	_sc8_msg07
		MSG_IDX	_sc8_msg08
		MSG_IDX	_sc8_msg0A
		MSG_IDX	_sc8_msg0B
		MSG_IDX	_sc8_msg0C
		MSG_IDX	_sc8_msg0E
		MSG_IDX	_sc8_msg0F
		MSG_IDX	_sc8_msg10
		MSG_IDX	_sc8_msg11
		MSG_IDX	_sc8_msg12
		MSG_IDX	_sc8_msg13
		MSG_IDX	_sc8_msg14
		MSG_IDX	_sc8_msg15
		MSG_IDX	_sc8_msg16
		MSG_IDX	_sc8_msg17
		MSG_IDX	_sc8_msg18
		MSG_IDX	_sc8_msg19
		MSG_IDX	_sc8_msg1A
		MSG_IDX	_sc8_msg1B
		MSG_IDX	_sc8_msg1C
		MSG_IDX	_sc8_msg8A					; scene 8 msg
		MSG_IDX	_sc8_msg8B					; scene 8 msg
_sc8_msg00:
		.BYTE	_Kaneda,_ddt_,_W,_her,_e,_apo,_d_,_s,_he,__g,_o,_que,_eol
_sc8_msg01:
		.BYTE	_The,_re,_apo_s,__a,__,_p,_at,_h,_w,_a,_y,__a,_l,_on,_g,__the,_ret
		.BYTE	_sewer,_dot,__,_The,__w,_at,_er,__,_se,_p,_ar,_at,_e,_s,_ret
		.BYTE	_this,__,_p,_at,_h,__,_f,_ro,_m,__the,__,_o,_t,_her,__s,_id,_e,_dot,_eol
;_sc8_msg02:
;		.BYTE	_Kaneda,_ddt_,_S,_h,_it,_col,__the,_y,__,_n,_o,_t,_i,_c,_ed,__,_me,_exc,_eol
_sc8_msg03:
		.BYTE	_Kaneda,_ddt_,_I_,_he,_ar,__a,__,_v,_o,_i,_c,_e,_dot_dot_dot,_eol
_sc8_msg04:
		.BYTE	_Kaneda,_ddt_,_F,_ro,_m,__the,__,_sewer,_que,_eol
_sc8_msg05:
		.BYTE	_Kaneda,_ddt_,_It_apo_s,__,_her,_exc,__,_The,__,_Army,_apo_s,_ret
		.BYTE	_h,_o,_l,_d,_ing,__,_her,__a,_t,__g,_u,_n,_p,_o,_in,_t,_exc,__,_I,_f,__,_I,_ret
		.BYTE	_s,_o,_me,_h,_ow,__s,_a,_ve,__,_her,_col,__,_m,_a,_y,_be,__s,_he,_apo,_ll,_ret
		.BYTE	_g,_o,__,_ou,_t_,_with,__,_me,_que,_eol
_sc8_msg06:
		.BYTE	_Kaneda,_ddt_,_U,_m,_col,__,_m,_i,_st,_er,_que,__,_I,_s,_n,_apo,_t,_ret
		.BYTE	_v,_i,_o,_le,_n,_c,_e_,_w,_r,_on,_g,_que,_eol
_sc8_msg07:
		.BYTE	_Kaneda,_ddt_,_Damn,_col,__,_I_,_g,_o,_t,__i,_g,_n,_or,_ed,_exc,_eol
_sc8_msg08:
		.BYTE	_Kaneda,_ddt_,_M,_w,_a,__,_ha,__,_ha,_exc,__,_I_apo,_m,__the,_ret
		.BYTE	_a,_c,_t,_u,_a,_l,__,_Terrorist,_exc,_eol
_sc8_msg0A:
		.BYTE	_D,_a,_z,_ed,_col,__,_I_,_t,_a,_p,_p,_ed,__,_her,__,_on,__the,_ret
		.BYTE	_s,_h,_ou,_l,_d,_er,_dot,_eol
_sc8_msg0B:
		.BYTE	_I_,_c,_re,_p,_t,__a,_l,_on,_g,__the,__s,_h,_ad,_ow,_s,_col,_ret
		.BYTE	_c,_are,_f,_u,_l,__,_n,_o,_t_,_to_,_m,_a,_k,_e_,_a,__s,_ou,_n,_d,_dot,_eol
_sc8_msg0C:
		.BYTE	_O,_n,_e_,_of,__the,__,_Army,__g,_u,_y,_s,__s,_n,_u,_c,_k,__,_u,_p,_ret
		.BYTE	_be,_h,_in,_d_,_me,__,_and,__,_p,_u,_t_,_m,_y,__g,_u,_n,_ret
		.BYTE	_a,_g,_a,_in,_st,__,_m,_y,__,_b,_a,_c,_k,_dot,_eol
_sc8_msg0E:
		.BYTE	_Kaneda,_ddt_,_O,_k,_col,__,_I_,_n,_e,_ed,__,_to_,_f,_o,_c,_u,_s,_ret
		.BYTE	_and,__,_be,_a,_t_,_this,__,_Army,__g,_u,_y,_dot,_ret
		.BYTE	_ret
		.BYTE	_I_,_g,_o,_t_,_re,_ad,_y,__,_to_,_c,_l,_i,_m,_b,__,_o,_ve,_r,_ret
		.BYTE	_t,_he,__,_f,_en,_c,_e,_dot_dot_dot,_eol
_sc8_msg0F:
		.BYTE	_S,_m,_a,_s,_h,_exc,_ret
		.BYTE	_ret
		.BYTE	_I_,_k,_i,_c,_k,_ed,__the,__,_me,_t,_a,_l,__,_f,_en,_c,_e,_ret
		.BYTE	_on,__a,_c,_c,_id,_en,_t,_dot,_eol
_sc8_msg10:
		.BYTE	_The,__g,_u,_y,__t,_u,_r,_n,_ed,__,_around,_dot,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_S,_h,_it,_exc,_eol
_sc8_msg11:
		.BYTE	_Kaneda,_ddt_,_You_apo_re,__,_c,_o,_m,_p,_le,_t,_e,_l,_y,_ret
		.BYTE	_s,_u,_r,_r,_ou,_n,_d,_ed,_dot,__,_D,_ro,_p,__,_you,_r,__w,_e,_a,_p,_on,_s,_ret
		.BYTE	_and,__,_le,_t,__the,__g,_irl,__g,_o,_dot,_eol
_sc8_msg12:
		.BYTE	_Kaneda,_ddt_,_E,_r,_col,__a,_h,_dot_dot_dot,__,_I_,_j,_u,_st,_dot_dot_dot,_eol
_sc8_msg13:
		.BYTE	_Kaneda,_ddt_,_G,_str,_g,_o,_d,_que,_exc,_eol
_sc8_msg14:
		.BYTE	_I_,_s,_p,_r,_u,_n,_g,__a,_t,__the,__,_Army,__g,_o,_on,_dot_dot_dot,_ret
		.BYTE	_ret
		.BYTE	_ret
		.BYTE	_dot_dot_dot,_and,__,_l,_and,_ed,__,_f,_l,_a,_t_,_on,__,_m,_y,__,_f,_a,_c,_e,_ret
		.BYTE	_in,__,_f,_r,_on,_t_,_of,__,_h,_i,_m,_dot,_eol
_sc8_msg15:
		.BYTE	_Kaneda,_ddt_,_B,_e,_t,_t,_er,__,_m,_a,_k,_e_,_a,__,_b,_re,_a,_k,_ret
		.BYTE	_for,__,_it,_exc,_ret
		.BYTE	_ret
		.BYTE	_I_,_d,_a,_s,_h,_ed,__i,_n,__,_f,_r,_on,_t_,_of,__the,_ret
		.BYTE	_Army,__,_j,_er,_k,_dot,_eol
_sc8_msg16:
		.BYTE	_C,_r,_u,_n,_c,_h,_dot,_ret
		.BYTE	_ret
		.BYTE	_H,_i,_s_,_f,_oo,_t_,_c,_a,_me,__,_d,_ow,_n,__,_on,__,_m,_y,__,_b,_a,_c,_k,_ret
		.BYTE	_and,__,_st,_o,_p,_p,_ed,__,_me,_dot,_eol
_sc8_msg17:
		.BYTE	_I_,_t,_r,_i,_ed,__,_to_,_a,_v,_o,_id,__the,_ret
		.BYTE	_b,_u,_l,_le,_t,_s,_dot_dot_dot,_ret
		.BYTE	_ret
		.BYTE	_But,__,_m,_y,__,_f,_oo,_t,__s,_l,_i,_p,_p,_ed,_col,_ret
		.BYTE	_and,__,_I_,_f,_e,_ll,_dot,_eol
_sc8_msg18:
		.BYTE	_Kaneda,_ddt_,_H,_i,_i,_y,_a,_a,_h,_exc,_ret
		.BYTE	_ret
		.BYTE	_I_,_s,_p,_r,_u,_n,_g,__a,_t,__the,__,_Army,__g,_u,_y,_dot,_eol
_sc8_msg19:
		.BYTE	_I_,_f,_e,_ll,__a,_l,_on,_g,__,_with,__the,__,_Army,_ret
		.BYTE	_g,_u,_y,__i,_n,_to_,_t,_he,__,_d,_it,_c,_h,_dot,__,_T,_h,_r,_ou,_g,_h,_ret
		.BYTE	_t,_he,__,_m,_u,_d_,_in,__,_m,_y,__,_e,_y,_e,_s,_col,__,_I_,_s,_a,_w,_ret
		.BYTE	_a,_n,_o,_t,_her,__,_on,_e_,_a,_p,_p,_ro,_a,_c,_h,_dot,_ret
		.BYTE	_ret
		.BYTE	_H,_e_,_w,_a,_l,_k,_ed,__t,_ow,_ar,_d_,_me,__,_and,_ret
		.BYTE	_re,_ad,_i,_ed,__,_his,__g,_u,_n,_exc,_eol
_sc8_msg1A:
		.BYTE	_G,_irl,_ddt_,_S,_t,_o,_p,__,_it,_exc,_eol
_sc8_msg1B:
		.BYTE	_But,__the,_re,__,_were_,_s,_i,_g,_n,_s_,_of,__,_m,_o,_re,_ret
		.BYTE	_Army,__g,_o,_on,_s_,_around,_dot,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_an0,_L,_e,_t,_apo_s,__g,_o,_dot,_aof,_eol
_sc8_msg1C:
		.BYTE	_Kaneda,_ddt_,_H,_e,_y,_exc,__,_S,_o,_col,__i,_f,__w,_e_,_m,_an,_a,_g,_e,_ret
		.BYTE	_to_,_g,_e,_t,__a,_w,_a,_y,__,_f,_ro,_m,__the,_se,__,_Army,_ret
		.BYTE	_g,_u,_y,_s,_col,__,_h,_ow,__a,_b,_ou,_t,__a,__,_d,_at,_e,_que,_eol
_sc8_msg8A:
		.BYTE	_Army,_ddt_,_H,_e,_y,_col,__t,_hat,_apo_s,__a,_s_,_f,_ar,__a,_s,_ret
		.BYTE	_you,__g,_o,_exc,_eol
_sc8_msg8B:
		.BYTE	_The,__,_Army,__g,_o,_on,__,_f,_i,_r,_ed,__,_his,__g,_u,_n,_exc,_eol

		SECTION_END		F8
