
		SECTION_START	F1

		MSG_START	_scene1_msg_lib
		MSG_IDX	_sc1_msg0B
		MSG_IDX	_sc1_msg0C
		MSG_IDX	_sc1_msg0D
		MSG_IDX	_sc1_msg0E
		MSG_IDX	_sc1_msg0F
		MSG_IDX	_sc1_msg10
		MSG_IDX	_sc1_msg11
		MSG_IDX	_sc1_msg12
		MSG_IDX	_sc1_msg13
		MSG_IDX	_sc1_msg14
		MSG_IDX	_sc1_msg15
		MSG_IDX	_sc1_msg16
		MSG_IDX	_sc1_msg17
		MSG_IDX	_sc1_msg18
		MSG_IDX	_sc1_msg1A
		MSG_IDX	_sc1_msg1B
		MSG_IDX	_sc1_msg1C
		MSG_IDX	_sc1_msg1D
		MSG_IDX	_sc1_msg1E
		MSG_IDX	_sc1_msg1F
		MSG_IDX	_sc1_msg20
		MSG_IDX	_sc1_msg21
		MSG_IDX	_sc1_msg22
		MSG_IDX	_sc1_msg23
		MSG_IDX	_sc1_msg24
		MSG_IDX	_sc1_msg25
		MSG_IDX	_sc1_msg27
		MSG_IDX	_sc1_msg28
		MSG_IDX	_sc1_msg29
		MSG_IDX	_sc1_msg2A
		MSG_IDX	_sc1_msg2B
		MSG_IDX	_sc1_msg2C
		MSG_IDX	_sc1_msg2D
		MSG_IDX	_sc1_msg31
		MSG_IDX	_sc1_msg32
		MSG_IDX	_sc1_msg80
		MSG_IDX	_sc1_msg81
		MSG_IDX	_sc1_msgB9
_sc1_msg80:
		.BYTE	_Army,_ddt_,_S,_h,_u,_t_,_u,_p,_exc,_eol
_sc1_msg81:
		.BYTE	_Army,_ddt_,_an0,_H,_e,_y,_exc,__,_N,_o,__s,_n,_oo,_p,_ing,_exc,_aof,_eol
_sc1_msgB9:
		.BYTE	_The,__,_n,_e,_x,_t_,_d,_a,_y,_col,__w,_e_,_were_,_b,_r,_ou,_g,_h,_t,_ret
		.BYTE	_in,__,_for,__a,_n,__,_Army,__i,_n,_ve,_st,_i,_g,_at,_i,_on,_dot,_eol
_sc1_msg0B:
		.BYTE	_Army,_ddt_,_an0,_W,_hat,__,_were_,_you,__,_d,_o,_ing,__i,_n,_ret
		.BYTE	_a,__,_p,_l,_a,_c,_e_,_l,_i,_k,_e_,_t,_hat,_col,__a,_n,_y,_w,_a,_y,_que,_aof,_eol
_sc1_msg0C:
		.BYTE	_Kaneda,_ddt_,_W,_e_,_were_,_t,_r,_a,_ve,_l,_ing,__,_on,_ret
		.BYTE	_ou,_r,__,_b,_i,_k,_e,_s,__i,_n,__the,__,_m,_id,_d,_le,__of,__the,_ret
		.BYTE	_n,_ight,__,_to_,_se,_e_,_m,_y,__,_d,_e,_at,_h,_l,_y,__i,_ll,_ret
		.BYTE	_m,_o,_t,_her,_dot,__,_W,_e_,_were_,_at,_t,_a,_c,_k,_ed,__,_b,_y,_ret
		.BYTE	_t,_he,__,_Clown,_s,_col,__,_and,__,_on,_e_,_of,__,_m,_y,_ret
		.BYTE	_f,_r,_i,_en,_d,_s,__g,_o,_t_,_h,_u,_r,_t,_col,__s,_o,__,_I_,_g,_o,_t,_ret
		.BYTE	_a,__,_l,_it,_t,_le,__,_p,_i,_s,_s,_ed,__of,_f,_dot_dot_dot,_eol
_sc1_msg0D:
		.BYTE	_Army,_ddt_,_an0,_Y,_ou,__g,_o,_t_,_p,_i,_s,_s,_ed,__of,_f,_col,__,_and,_ret
		.BYTE	_t,_hat,_apo_s,__w,_h,_y,__,_8,__of,__the,_se,__,_Clown,_s,_ret
		.BYTE	_are,__,_n,_ow,__i,_n,__the,__,_h,_o,_s,_p,_it,_a,_l,_que,_ret
		.BYTE	_R,_ight,_dot,__,_A,_n,_d_,_you,_r,__,_bra,_d,_e,_at,_h,_l,_y,__i,_ll,_bra,_ret
		.BYTE	_m,_o,_t,_her,_dot,__,_H,_ow,__i,_s,__s,_he,__,_d,_o,_ing,_que,_aof,_eol
_sc1_msg0E:
		.BYTE	_Kaneda,_ddt_,_F,_or,_t,_u,_n,_at,_e,_l,_y,_col,__,_l,_a,_st,_ret
		.BYTE	_n,_ight,_col,__s,_he,__,_c,_le,_are,_d,__the,__,_h,_u,_m,_p,_dot,_eol
_sc1_msg0F:
		.BYTE	_Army,_ddt_,_an0,_S,_he,__,_c,_le,_are,_d,__the,__,_h,_u,_m,_p,_col,_ret
		.BYTE	_h,_u,_h,_que,__,_W,_hat,__,_n,_e,_x,_t,_col,__a,__t,_r,_i,_at,_h,_l,_on,_que,_aof,_eol
_sc1_msg10:
		.BYTE	_Kaneda,_ddt_,_Man,_col,__,_I_apo,_m,__,_h,_u,_n,_g,_r,_y,_dot,_eol
_sc1_msg11:
		.BYTE	_It_apo_s,__the,__,_Army,__i,_n,_ve,_st,_i,_g,_at,_or,_dot,_eol
_sc1_msg12:
		.BYTE	_It_apo_s,__,_me,_exc,_eol
_sc1_msg13:
		.BYTE	_T,_h,_o,_se,__,_are,__,_ou,_r,__,_l,_i,_c,_en,_se,_s,_dot,__,_B,_e,_ret
		.BYTE	_c,_are,_f,_u,_l,__,_with,__the,_m,_dot,_eol
_sc1_msg14:
		.BYTE	_I,_t_,_l,_oo,_k,_s_,_l,_i,_k,_e_,_a,__,_l,_i,_st,__of,__,_k,_n,_ow,_n,_ret
		.BYTE	_Terrorist,_s,_dot,_ret
		.BYTE	_ret
		.BYTE	_The,_y,__s,_h,_ou,_l,_d,_n,_apo,_t_,_was,_t,_e,__the,_i,_r,_ret
		.BYTE	_t,_i,_me,__,_l,_oo,_k,_ing,__t,_h,_r,_ou,_g,_h,__,_it,_dot_dot_dot,_ret
		.BYTE	_The,_re,_apo_s,__,_n,_o,__w,_a,_y,__w,_e,_apo,_d_,_be,__,_on,__,_it,_dot,_eol
_sc1_msg15:
		.BYTE	_Army,_ddt_,_an0,_I_,_c,_an,__t,_e,_ll,__,_j,_u,_st,__,_b,_y,_ret
		.BYTE	_l,_oo,_k,_ing,__a,_t_,_you,_dot_dot_dot,__,_T,_his,_ret
		.BYTE	_in,_t,_er,_ro,_g,_at,_i,_on,__i,_s_,_o,_ve,_r,_dot,_ret
		.BYTE	_ret
		.BYTE	_G,_o,__w,_a,_it,__,_ou,_t,_s,_id,_e,_dot,_ret
		.BYTE	_ret
		.BYTE	_N,_e,_x,_t,_exc,_aof,_eol
_sc1_msg16:
		.BYTE	_M,_y,__,_f,_r,_i,_en,_d,_s,_exc,__,_W,_e,_apo,_re,__a,_ll,__,_b,_ad,_a,_s,_se,_s,_ret
		.BYTE	_at,__the,__t,_o,_p,__of,__,_ou,_r,__g,_a,_me,_exc,_eol
_sc1_msg17:
		.BYTE	_It_apo_s,__,_m,_y,__,_f,_a,_c,_e,_dot,_eol
_sc1_msg18:
		.BYTE	_Kaneda,_ddt_,_G,_e,_e,_z,_col,__,_m,_i,_st,_er,_dot_dot_dot,__,_W,_hat,_ret
		.BYTE	_were_,_Y,_O,_U,__,_d,_o,_ing,__i,_n,__a,__,_p,_l,_a,_c,_e_,_l,_i,_k,_e,_ret
		.BYTE	_t,_hat,__,_l,_a,_st,__,_n,_ight,_que,_eol
_sc1_msg1A:
		.BYTE	_It_apo_s,__,_Yamagata,_dot,_eol
_sc1_msg1B:
		.BYTE	_It_apo_s,__,_Kai,_dot,_eol
_sc1_msg1C:
		.BYTE	_It_apo_s,__,_K,_u,_w,_at,_a,_dot,_eol
_sc1_msg1D:
		.BYTE	_It_apo_s,__,_W,_at,_an,_a,_be,_dot,_eol
_sc1_msg1E:
		.BYTE	_It_apo_s,__,_T,_a,_k,_e,_y,_a,_m,_a,_dot,_eol
_sc1_msg1F:
		.BYTE	_Yamagata,_ddt_,_Man,_col,__i,_f,__w,_e_,_ha,_d_,_a,__,_b,_it,_ret
		.BYTE	_l,_on,_g,_er,__,_l,_a,_st,__,_n,_ight,_col,__w,_e_,_c,_ou,_l,_d,_apo,_ve,_ret
		.BYTE	_c,_r,_u,_s,_h,_ed,__t,_h,_o,_se,__,_Clown,_s,_dot,_eol
_sc1_msg20:
		.BYTE	_Kai,_ddt_,_Y,_e,_a,_h,__t,_hat,_apo_s,__,_n,_i,_c,_e,_col,__,_m,_i,_st,_er,_dot,_ret
		.BYTE	_S,_o,__w,_her,_e,_apo,_d_,_you,__t,_a,_k,_e_,_Tetsuo,_que,_eol
_sc1_msg21:
		.BYTE	_Army,_ddt_,_an0,_H,_e,_y,_exc,__,_D,_on,_apo,_t_,_l,_oo,_k,__a,_w,_a,_y,_exc,_aof,_eol
_sc1_msg22:
		.BYTE	_Army,_ddt_,_an0,_You_apo_re,__,_n,_o,_t_,_with,__the,_ret
		.BYTE	_Terrorist,_s,_col,__,_are,__,_you,_que,_aof,_eol
_sc1_msg23:
		.BYTE	_Kaneda,_ddt_,_N,_o,_t_,_e,_ve,_n,_exc,__,_W,_e,_apo,_re,__a,_ll,_ret
		.BYTE	_b,_ad,_a,_s,_se,_s,__a,_t,__the,__t,_o,_p,__of,__,_ou,_r,_ret
		.BYTE	_g,_a,_me,_exc,_eol
_sc1_msg24:
		.BYTE	_Kaneda,_ddt_,_H,_e,_y,__,_m,_i,_st,_er,_col,__,_you,_apo,_re,__a,_ret
		.BYTE	_p,_re,_t,_t,_y,__,_h,_and,_s,_o,_me,__g,_u,_y,_exc,_eol
_sc1_msg25:
		.BYTE	_Kaneda,_ddt_,_H,_e,_y,__,_m,_i,_st,_er,_col,__,_you,_r,_ret
		.BYTE	_z,_i,_p,_p,_er,_apo_s,__,_d,_ow,_n,_dot,_eol
_sc1_msg27:
		.BYTE	_I,_t_,_m,_u,_st,__,_be,__a,__,_l,_i,_st,__of,__,_k,_n,_ow,_n,_ret
		.BYTE	_Terrorist,_s,_dot_dot_dot,_ret
		.BYTE	_ret
		.BYTE	_O,_h,_col,__the,_re,__,_are,__,_e,_ve,_n,__s,_o,_me,__g,_irl,_s,_ret
		.BYTE	_on,__,_her,_e,_exc,__,_W,_ow,_col,__,_this,__,_on,_e,_apo_s,__,_c,_u,_t,_e,_exc,_ret
		.BYTE	_ret
		.BYTE	_W,_on,_d,_er,__w,_hat,__,_her,__,_n,_a,_me,__i,_s,_dot_dot_dot,_eol
_sc1_msg28:
		.BYTE	_Kaneda,_ddt_,_H,_e,_y,_col,__,_c,_an,__,_you,__t,_e,_ll,__,_me,_ret
		.BYTE	_w,_hat,__,_this,__g,_irl,_apo_s,__,_n,_a,_me,__i,_s,_que,_eol
_sc1_msg29:
		.BYTE	_Kaneda,_ddt_,_W,_her,_e,_apo_s,__,_this,__g,_irl,_ret
		.BYTE	_l,_i,_ve,_que,_eol
_sc1_msg2A:
		.BYTE	_Kaneda,_ddt_,_H,_e,_y,_col,__a,_t_,_le,_a,_st,__t,_e,_ll,__,_me,_ret
		.BYTE	_her,__,_p,_h,_on,_e_,_n,_u,_m,_b,_er,__,_or,__s,_o,_me,_t,_h,_ing,_exc,_ret
		.BYTE	_I_apo,_m,__,_be,_g,_g,_ing,__,_you,_exc,_eol
_sc1_msg2B:
		.BYTE	_Army,_ddt_,_an0,_I,_f,__w,_e_,_k,_n,_e,_w,__t,_hat,__,_k,_in,_d_,_of,_ret
		.BYTE	_in,_for,_m,_at,_i,_on,_col,__w,_e_,_w,_ou,_l,_d,_n,_apo,_t_,_be,_ret
		.BYTE	_se,_ar,_c,_h,_ing,__,_for,__,_her,_exc,_aof,_eol
_sc1_msg2C:
		.BYTE	_L,_a,_c,_k,_e,_y,_ddt_,_an1,_I,_t_,_l,_oo,_k,_s_,_l,_i,_k,_e,__the,_se,_ret
		.BYTE	_g,_u,_y,_s_,_ha,_ve,__,_n,_o,__,_c,_on,_n,_e,_c,_t,_i,_on,_ret
		.BYTE	_to_,_t,_he,__,_Terrorist,_s,_dot,_aof,_eol
_sc1_msg2D:
		.BYTE	_Kaneda,_ddt_,_H,_e,_y,_col,__,_he,__,_m,_ad,_e_,_a,__,_j,_ok,_e,_exc,_ret
		.BYTE	_H,_a,_ha,_ha,_dot_dot_dot,_eol
_sc1_msg31:
		.BYTE	_Army,_ddt_,_an0,_H,_e,_y,_col,__s,_h,_u,_t_,_u,_p,_exc,_aof,_eol
_sc1_msg32:
		.BYTE	_I,_n,_t,_er,_ro,_g,_at,_i,_on,__,_ro,_o,_m,_s_,_were_,_se,_t,_ret
		.BYTE	_u,_p,__i,_n,__the,__g,_y,_m,__,_u,_s,_ing,__,_p,_l,_y,_w,_oo,_d,_ret
		.BYTE	_w,_a,_ll,_s_,_to_,_se,_p,_ar,_at,_e,__the,_m,_dot,_eol

		SECTION_END		F1
