
		SECTION_START	F17

		MSG_START	_scene17_msg_lib
		MSG_IDX_SP	_sc17_msg76					; scene 17 msg
		MSG_IDX_SP	_sc17_msg77					; scene 17 msg
		MSG_IDX_SP	_sc17_msg78					; scene 17 msg
		MSG_IDX_SP	_sc17_msg79					; scene 17 msg
		MSG_IDX_SP	_sc17_msg7A					; scene 17 msg
		MSG_IDX_SP	_sc17_msg7B					; scene 17 msg
		MSG_IDX_SP	_sc17_msg84					; scene 17 msg
		MSG_IDX_SP	_sc17_msg86					; scene 17 msg
		MSG_IDX_SP	_sc17_msg8C					; scene 17 msg
		MSG_IDX_SP	_sc17_msgB6					; scene 17 msg
		MSG_IDX_SP	_sc11_12_13_msg97			; scenes 11,12,13 msg
		MSG_IDX_SP	_sc11_15_msg96				; scenes 11,15 msg
		MSG_IDX_SP	_sc13_15_msg99				; scenes 13,15 msg
		MSG_IDX_SP	_sc13_15_msg9A				; scenes 13,15 msg
		MSG_IDX_SP	_sc13_15_msg9B				; scenes 13,15 msg
		MSG_IDX_SP	_sc13_15_msg9E				; scenes 13,15 msg
		MSG_IDX_SP	_sc13_15_msg9F				; scenes 13,15 msg
		MSG_IDX_SP	_sc15_16_msgC9				; scenes 15,16 msg
		MSG_IDX_SP	_sc15_16_msgCB				; scenes 15,16 msg
		MSG_IDX_SP	_sc15_16_msgC5				; scenes 15,16 msg
		MSG_IDX_SP	_sc15_16_msgC7				; scenes 15,16 msg
		MSG_IDX_SP	_sc15_16_msgCA				; scenes 15,16 msg
		MSG_IDX_SP	_sc15_16_msgC8				; scenes 15,16 msg
		MSG_IDX_SP	_sc15_16_msgC6				; scenes 15,16 msg
		MSG_IDX_SP	_sc2_13_msgA0				; scenes 2,13 msg
		MSG_IDX_SP	_sc2_13_15_16_msg82			; scenes 2,13,15,16 msg
		MSG_IDX_SP	_sc2_15_msgA1				; scenes 2,15 msg
		MSG_IDX_SP	_sc2_6_msg83				; scenes 2,6 msg
		MSG_IDX_SP	_sc2_F_10_12_13_msg85		; scenes 2,F,10,12,13 msg
		MSG_IDX_SP	_sc5_6_msgA4				; scenes 5,6 msg
		MSG_IDX_SP	_sc5_6_15_msgAB				; scenes 5,6,15 msg
		MSG_IDX_SP	_sc5_A_msg7F				; scenes 5,A msg
		MSG_IDX_SP	_sc6_15_msg88				; scenes 6,15 msg
		MSG_IDX_SP	_sc6_15_msg89				; scenes 6,15 msg
		MSG_IDX_SP	_sc8_A_msg8F				; scenes 8,A msg
		MSG_IDX_SP	_scA_10_msg94				; scenes A,10 msg
		MSG_IDX_SP	_scA_B_msgA8				; scenes A,B msg
		MSG_IDX_SP	_scA_B_msgA7				; scenes A,B msg
		MSG_IDX_SP	_scA_B_msgA6				; scenes A,B msg
		MSG_IDX_SP	_scA_B_msgAA				; scenes A,B msg
		MSG_IDX_SP	_scA_B_msgAF				; scenes A,B msg
		MSG_IDX_SP	_scA_B_msgB0				; scenes A,B msg
		MSG_IDX_SP	_scA_B_msgB1				; scenes A,B msg
		MSG_IDX_SP	_scA_B_msgB2				; scenes A,B msg
		MSG_IDX_SP	_scA_B_msgA9				; scenes A,B msg
		MSG_IDX_SP	_scC_15_msgA5				; scenes C,15 msg
		MSG_IDX_SP	_scC_D_13_16_msg90			; scenes C,D,13,16 msg
		MSG_IDX_SP	_scD_E_13_msg91				; scenes D,E,13 msg
		MSG_IDX_SP	_scF_12_13_15_msg93			; scenes F,12,13,15 msg
;		MSG_IDX_SP	_sc17_msgA3					; -unused-
_sc17_msg76:
		.BYTE	_M,_i,_y,_a,_k,_o,_ddt_,_C,_le,_an,_se,__,_you,_r,__,_b,_o,_d,_y,_exc,_ret
		.BYTE	_P,_u,_r,_i,_f,_y,__,_you,_r,__s,_ou,_l,_col,_ret
		.BYTE	_and,__the,_n,__,_re,_t,_u,_r,_n,_exc,_eol
_sc17_msg77:
		.BYTE	_M,_i,_y,_a,_k,_o,_ddt_,_Y,_ou,__s,_a,_y,__,_you,__w,_an,_t,__t,_o,_ret
		.BYTE	_st,_o,_p,_que,_ret
		.BYTE	_ret
		.BYTE	_A,__,_But,_t,_on,_ddt_,_Y,_e,_s,_exc,_ret
		.BYTE	_B,__,_But,_t,_on,_ddt_,_N,_o,_exc,_eol
_sc17_msg78:
		.BYTE	_M,_i,_y,_a,_k,_o,_ddt_,_L,_or,_d_,_Akira,_apo_s,__a,_w,_a,_k,_en,_ing,_ret
		.BYTE	_i,_s_,_n,_i,_g,_h,_exc,__,_H,_e_,_ha,_s_,_n,_e,_ed,__of,__,_you,_r,_ret
		.BYTE	_st,_re,_n,_g,_t,_h,_exc,__,_T,_a,_k,_e_,_he,_ar,_t_,_and,__,_j,_o,_in,_ret
		.BYTE	_in,_exc,_eol
_sc17_msg79:
		.BYTE	_M,_i,_y,_a,_k,_o,_ddt_,_F,_oo,_l,_exc,__,_T,_hat,_apo_s,__,_n,_o,_t_,_it,_exc,_ret
		.BYTE	_T,_r,_y,__i,_n,_p,_u,_t,_t,_ing,__,_it,__a,_g,_a,_in,_exc,_eol
_sc17_msg7A:
		.BYTE	_Kaneda,_ddt_,_an0,_M,_y,__,_p,_a,_s,_s,_w,_or,_d_,_i,_s,_aof,_eol
_sc17_msg7B:
		.BYTE	_M,_i,_y,_a,_k,_o,_ddt_,_O,_h,_col,__g,_oo,_d,_col,__,_you,_apo,_ve,_ret
		.BYTE	_re,_t,_u,_r,_n,_ed,_exc,__,_E,_n,_t,_er,__,_you,_r,__,_p,_a,_s,_s,_w,_or,_d,_exc,_eol
_sc5_A_msg7F:
		.BYTE	_Kaneda,_ddt_,_str,_c,_ou,_g,_h,_str,_ret
		.BYTE	_B,_le,_c,_h,_dot,_eol
_sc2_13_15_16_msg82:
		.BYTE	_Kaneda,_ddt_,_S,_t,_o,_p,__,_it,_exc,_eol
_sc2_6_msg83:
		.BYTE	_Kaneda,_ddt_,_U,_h,_col,__w,_hat,__,_d,_o,__,_I_,_d,_o,_dot_dot_dot,_eol
_sc17_msg84:
		.BYTE	_Kaneda,__,_me,_t,__a,_n,__,_u,_n,_t,_i,_me,_l,_y,__,_en,_d,_dot_dot_dot,_eol
_sc2_F_10_12_13_msg85:
		.BYTE	_Kaneda,_ddt_,_dot_dot_dot,_eol
_sc17_msg86:
		.BYTE	_T,_his,__i,_s_,_G,_a,_me,__,_O,_ve,_r,_exc,_ret
		.BYTE	_P,_le,_a,_se,__t,_r,_y,__a,_g,_a,_in,_exc,_ret
		.BYTE	_ret
		.BYTE	_A,__,_But,_t,_on,_ddt_,_L,_e,_t,_apo_s,__t,_r,_y,_exc,_ret
		.BYTE	_B,__,_But,_t,_on,_ddt_,_I_apo,_m,__,_d,_on,_e,_exc,_eol
_sc6_15_msg88:
		.BYTE	_Kaneda,_ddt_,_Tetsuo,_dot_dot_dot,_ret
		.BYTE	_W,_hat,__,_d,_i,_d_,_you,__,_d,_o,_que,_exc,_eol
_sc6_15_msg89:
		.BYTE	_Tetsuo,_ddt_,_an0,_U,_g,_h,_dot_dot_dot,_ret
		.BYTE	_str,_h,_u,_f,_f,_str,__,_str,_h,_u,_f,_f,_str,_ret
		.BYTE	_O,_h,_dot_dot_dot,__,_O,_h,_dot,_aof,_eol
_sc17_msg8C:
		.BYTE	_Kaneda,__,_was,__,_c,_a,_u,_g,_h,_t_,_b,_y,__the,__,_Army,_ret
		.BYTE	_and,__s,_en,_t_,_to_,_j,_u,_v,_i,_e,_dot,_eol
_sc17_msgB6:
		.BYTE	_M,_i,_y,_a,_k,_o,_ddt_,_Y,_ou,_r,__,_p,_a,_s,_s,_w,_or,_d_,_i,_s,_ret
		.BYTE	_password,_ret
		.BYTE	_ret
		.BYTE	_It_apo_s,__,_be,_st,__,_you,__,_d,_on,_apo,_t_,_for,_g,_e,_t_,_it,_exc,_eol
_sc8_A_msg8F:
		.BYTE	_Kaneda,_ddt_,_A,_h,_exc,__,_W,_hat,_apo_s,__,_this,_que,_eol
_scC_D_13_16_msg90:
		.BYTE	_Kaneda,_ddt_,_U,_g,_h,_exc,_ret
		.BYTE	_str,_g,_l,_u,_b,_str,_eol
_scD_E_13_msg91:
		.BYTE	_Kei,_ddt_,_I,_d,_i,_o,_t,_exc,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_U,_u,_g,_h,_exc,_ret
		.BYTE	_ret
		.BYTE	_Kei,_ddt_,_A,_h,_exc,_eol
_scF_12_13_15_msg93:
		.BYTE	_Tetsuo,_ddt_,_an0,_A,_g,_h,_dot_dot_dot,__,_A,_h,_exc,_aof,_eol
_scA_10_msg94:
		.BYTE	_The,__,_d,_oo,_r,__,_was,__,_l,_o,_c,_k,_ed,_dot,_eol
_sc11_15_msg96:
		.BYTE	_Kaneda,_ddt_,_an0,_D,_u,_m,_b,_a,_s,_se,_s,_exc,_aof,_eol
_sc11_12_13_msg97:
		.BYTE	_Kai,_ddt_,_Kaneda,_exc,_exc,_eol
_sc13_15_msg99:
		.BYTE	_I_,_re,_ad,_i,_ed,__the,__a,_i,_m,__,_on,__,_m,_y,__,_laser,_dot,_eol
_sc13_15_msg9A:
		.BYTE	_The,__,_laser,__,_h,_it,__,_Tetsuo,_apo_s,__,_c,_he,_st,_exc,_ret
		.BYTE	_ret
		.BYTE	_Tetsuo,_ddt_,_U,_g,_h,_dot_dot_dot,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_I_,_d,_i,_d_,_it,_col,__,_Yamagata,_exc,_ret
		.BYTE	_J,_u,_st,__,_for,__,_you,_exc,_eol
_sc13_15_msg9B:
		.BYTE	_Tetsuo,__,_d,_i,_ed,_dot_dot_dot,_eol
_sc13_15_msg9E:
		.BYTE	_Tetsuo,_apo_s,__,_ha,_i,_r,__i,_s_,_st,_and,_ing,__,_on,_ret
		.BYTE	_en,_d,_dot,_ret
		.BYTE	_ret
		.BYTE	_Tetsuo,_apo_s,__,_p,_l,_an,_n,_ing,__,_to_,_u,_n,_le,_a,_s,_h,_ret
		.BYTE	_a,__s,_h,_o,_c,_k,__w,_a,_ve,_exc,_eol
_sc13_15_msg9F:
		.BYTE	_The,__,_laser,__,_m,_i,_s,_s,_ed,_exc,_eol
_sc2_13_msgA0:
		.BYTE	_Kaneda,_ddt_,_H,_u,_h,_que,__,_I,_t_,_w,_on,_apo,_t_,_w,_or,_k,_exc,_eol
_sc2_15_msgA1:
		.BYTE	_Kaneda,_ddt_,_N,_a,_u,_dot_dot_dot,__,_m,_a,_k,_u,_dot_dot_dot,__s,_a,_dot_dot_dot,_ret
		.BYTE	_U,_m,_dot_dot_dot,__,_m,_an,_dot_dot_dot,__,_d,_a,_que,_ret
		.BYTE	_I_,_c,_an,__,_n,_e,_ve,_r,__,_re,_me,_m,_b,_er,__t,_hat,_ret
		.BYTE	_m,_an,_t,_r,_a,_dot,_eol
_sc5_6_msgA4:
		.BYTE	_Man,_ddt_,_dot_dot_dot,_eol
_scC_15_msgA5:
		.BYTE	_The,_re,__i,_s,_n,_apo,_t,__t,_i,_me,__,_for,__t,_hat,_exc,_eol
_scA_B_msgA6:
		.BYTE	_Terrorist,_ddt_,_an0,_W,_e,_apo,_re,__g,_on,_n,_a,__s,_n,_e,_a,_k,_ret
		.BYTE	_in,_to_,_t,_he,__,_l,_a,_b,_que,_exc,__,_A,_re,__,_you,__,_c,_r,_a,_z,_y,_que,_ret
		.BYTE	_A,_n,_d_,_with,__,_T,_H,_I,_S,__,_k,_id,_dot_dot_dot,_que,_aof,_eol
_scA_B_msgA7:
		.BYTE	_Terrorist,_ddt_,_an0,_T,_his,__i,_s,__a,__,_p,_a,_s,_s,_ret
		.BYTE	_t,_hat,_apo,_ll,__g,_e,_t_,_u,_s,__i,_n,_to_,_t,_he,__,_l,_a,_b,_ret
		.BYTE	_for,__a,__w,_e,_e,_k,_dot_dot_dot,_aof,_eol
_scA_B_msgA8:
		.BYTE	_Terrorist,_ddt_,_an0,_N,_e,_w,__,_e,_xperimental,_ret
		.BYTE	_s,_u,_b,_j,_e,_c,_t,_que,_aof,_eol
_scA_B_msgA9:
		.BYTE	_Ryu,_ddt_,_an1,_The,__,_b,_o,_y,__w,_h,_o,__,_c,_a,_u,_s,_ed,__a,_ll,__of,_ret
		.BYTE	_t,_hat,__,_c,_o,_m,_m,_o,_t,_i,_on,__i,_n,__the,__,_O,_l,_d_,_T,_ow,_n,_ret
		.BYTE	_was,__t,_a,_k,_en,__i,_n,_to_,_c,_u,_st,_o,_d,_y,__i,_n,__the,_ret
		.BYTE	_l,_a,_b,_dot_dot_dot,_aof,_eol
_scA_B_msgAA:
		.BYTE	_Ryu,_ddt_,_an1,_I,_t_,_l,_oo,_k,_s_,_l,_i,_k,_e_,_it,_apo_s,__a,_ret
		.BYTE	_t,_r,_a,_in,_ing,__,_c,_en,_t,_er,_col,__,_b,_u,_t_,_it,_apo_s,_ret
		.BYTE	_re,_a,_ll,_y,__a,__,_h,_u,_m,_an,__,_e,_x,_p,_er,_i,_me,_n,_t,_at,_i,_on,_ret
		.BYTE	_l,_a,_b,_dot_dot_dot,_aof,_eol
_sc5_6_15_msgAB:
		.BYTE	_Kaneda,_ddt_,_an0,_Tetsuo,_exc,_aof,_eol
_scA_B_msgAF:
		.BYTE	_Ryu,_ddt_,_an1,_T,_hat,_apo_s,__,_r,_ight,_dot,__,_L,_a,_st,__w,_e,_e,_k,_col,_ret
		.BYTE	_ou,_r,__,_for,_c,_e,_s_,_l,_i,_b,_er,_at,_ed,__the,_ret
		.BYTE	_e,_x,_p,_er,_i,_me,_n,_t_,_k,_n,_ow,_n,__a,_s_,_bra,_N,_o,_dot,__,_2,_6,_bra,_ret
		.BYTE	_d,_u,_r,_ing,__the,__,_n,_ight,_dot,_aof,_eol
_scA_B_msgB0:
		.BYTE	_Ryu,_ddt_,_an1,_It_apo_s,__a,_n,__,_u,_r,_g,_en,_t_,_or,_d,_er,_dot,_ret
		.BYTE	_W,_e,_apo,_re,__a,_l,_re,_ad,_y,__,_m,_a,_k,_ing,_ret
		.BYTE	_ar,_r,_an,_g,_e,_me,_n,_t,_s,_dot,_aof,_eol
_scA_B_msgB1:
		.BYTE	_Kei,_ddt_,_an2,_F,_ro,_m,__,_M,_r,_dot,__,_N,_e,_z,_u,_col,__,_r,_ight,_que,_ret
		.BYTE	_W,_hat,_apo_s,__the,__,_o,_b,_j,_e,_c,_t,_i,_ve,_que,_aof,_eol
_scA_B_msgB2:
		.BYTE	_Ryu,_ddt_,_an1,_S,_o,_me,__,_d,_e,_t,_a,_i,_l,_ed,__,_d,_at,_a,__,_on,__the,_ret
		.BYTE	_n,_e,_w,_e,_st,__,_e,_x,_p,_er,_i,_me,_n,_t,_dot,_aof,_eol
_sc15_16_msgC5:
		.BYTE	_Tetsuo,_ddt_,_an0,_A,_a,_a,_a,_h,_exc,_aof,_ret
		.BYTE	_ret
		.BYTE	_O,_n,_l,_y,__,_Tetsuo,_apo_s,__,_f,_a,_c,_e_,_re,_m,_a,_in,_ed,_ret
		.BYTE	_h,_u,_m,_an,_col,__a,_s,__the,__,_re,_st,__of,__,_h,_i,_m,_ret
		.BYTE	_t,_u,_r,_n,_ed,__i,_n,_to_,_a,__,_f,_le,_s,_h,_y,__,_b,_l,_o,_b,_dot,_eol
_sc15_16_msgC6:
		.BYTE	_Tetsuo,_ddt_,_an0,_G,_r,_a,_h,_exc,_aof,_ret
		.BYTE	_ret
		.BYTE	_The,__,_f,_le,_s,_h,_y,__,_b,_l,_o,_b,__,_le,_t_,_ou,_t,__a,_ret
		.BYTE __s,_c,_re,_a,_m,_dot,_eol
_sc15_16_msgC7:
		.BYTE	_Tetsuo,_ddt_,_an0,_Kaneda,_col,__,_r,_u,_n,_exc,_aof,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_S,_h,_it,_dot_dot_dot,_ret
		.BYTE	_ret
		.BYTE	_Tetsuo,_ddt_,_an0,_G,_a,_h,_exc,_aof,_eol
_sc15_16_msgC8:
		.BYTE	_Kiyoko,_col,__,_Masaru,_col,__,_and,__,_Takashi,_ret
		.BYTE	_were_,_st,_and,_ing,__,_f,_i,_r,_m,__a,_t,__the,_ret
		.BYTE	_ed,_g,_e_,_of,__the,__,_st,_ad,_i,_u,_m,__a,_s,__the,_ret
		.BYTE	_b,_l,_o,_b,__,_be,_g,_an,__,_to_,_f,_i,_ll,__,_it,_dot,__,_I,_n,_ret
		.BYTE	_f,_r,_on,_t_,_of,__the,_m,_col,__the,_re,__,_was,__a,_ret
		.BYTE	_s,_a,_m,_p,_le,__,_c,_a,_se,_dot,_eol
_sc15_16_msgC9:
		.BYTE	_The,__,_l,_ight,__,_f,_i,_ll,_ed,__the,__,_en,_t,_i,_re,_ret
		.BYTE	_st,_ad,_i,_u,_m,_dot,_eol
_sc15_16_msgCA:
		.BYTE	_A,_s,__the,__,_l,_ight,__,_was,__,_re,_a,_c,_h,_ing,_ret
		.BYTE	_t,_he,__,_building,_s,_col,__the,__,_d,_e,_st,_r,_u,_c,_t,_i,_on,_ret
		.BYTE	_of,__the,__,_O,_l,_d_,_T,_ow,_n,__,_be,_g,_an,_dot,_eol
_sc15_16_msgCB:
		.BYTE	_The,__,_l,_ight,__g,_re,_w,__i,_n,_to_,_a,__,_m,_a,_s,_s,_i,_ve,_ret
		.BYTE	_s,_p,_her,_e,_dot,__,_M,_o,_st,__of,__the,__,_O,_l,_d_,_T,_ow,_n,_ret
		.BYTE	_ha,_d_,_be,_en,__,_en,_ve,_l,_o,_p,_ed,__,_b,_y,__the,_ret
		.BYTE	_l,_ight,_dot_dot_dot,_eol
;_sc17_msgA3:
;		.BYTE	_T,_h,_u,_d,_exc,_eol

		SECTION_END		F17