
		SECTION_START	F14

		MSG_START	_scene14_msg_lib
		MSG_IDX	_sc14_msg00
		MSG_IDX	_sc14_msg01
		MSG_IDX	_sc14_msg02
		MSG_IDX	_sc14_msg03
		MSG_IDX	_sc14_msg04
		MSG_IDX	_sc14_msg05
		MSG_IDX	_sc14_msg06
		MSG_IDX	_sc14_msg07
		MSG_IDX	_sc14_msg08
		MSG_IDX	_sc14_msg09
		MSG_IDX	_sc14_msg0A
		MSG_IDX	_sc14_msg0B
		MSG_IDX	_sc14_msg0C
		MSG_IDX	_sc14_msg0D
		MSG_IDX	_sc14_msg0E
		MSG_IDX	_sc14_msg0F
		MSG_IDX	_sc14_msg10
		MSG_IDX	_sc14_msg11
		MSG_IDX	_sc14_msg12
		MSG_IDX	_sc14_msg13
		MSG_IDX	_sc14_msg14
_sc14_msg00:
		.BYTE	_W,_e_,_t,_oo,_k,__a,__,_b,_r,_i,_e,_f,__,_b,_re,_a,_k,__,_n,_e,_ar,__the,_ret
		.BYTE	_tollbooth,__,_on,__the,__,_h,_i,_g,_h,_w,_a,_y,_dot,__,_I,_t,_ret
		.BYTE	_was,__a,_l,_re,_ad,_y,__,_n,_ight,_t,_i,_me,_dot_dot_dot,_eol
_sc14_msg01:
		.BYTE	_Kaneda,_ddt_,_The,__,_st,_ar,_s_,_u,_p,__the,_re,__,_are,_ret
		.BYTE	_re,_a,_ll,_y,__,_p,_re,_t,_t,_y,_exc,_ret
		.BYTE	_ret
		.BYTE	_Kei,_ddt_,_an0,_W,_hat,_apo,_re,__,_you,__,_b,_a,_b,_b,_l,_ing,_ret
		.BYTE	_a,_b,_ou,_t_,_n,_ow,_que,_aof,_eol
_sc14_msg02:
		.BYTE	_Kaneda,_ddt_,_Damn,_col,__,_j,_u,_st,__w,_h,_en,__,_this,_ret
		.BYTE	_laser,__,_be,_a,_m,__,_was,__,_be,_c,_o,_m,_ing,_ret
		.BYTE	_u,_se,_f,_u,_l,_col,__,_it,__w,_en,_t_,_and,__,_b,_ro,_k,_e_,_on,_ret
		.BYTE	_me,_dot,_eol
_sc14_msg03:
		.BYTE	_Kei,_ddt_,_an0,_I_,_t,_h,_in,_k,__,_I_,_f,_a,_in,_t,_ed,_dot_dot_dot,_ret
		.BYTE	_W,_h,_en,__,_I_,_w,_ok,_e_,_u,_p,_col,__,_I_,_was,__,_c,_o,_ve,_r,_ed,_ret
		.BYTE	_in,__,_d,_u,_st,_dot_dot_dot,_aof,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_I_,_be,_t_,_it,__,_was,__t,_h,_o,_se,_ret
		.BYTE	_d,_a,_m,_n,__,_k,_id,_s_,_c,_on,_t,_ro,_ll,_ing,__,_you,_dot,_eol
_sc14_msg04:
		.BYTE	_Kei,_ddt_,_an0,_I_,_d,_id,_n,_apo,_t_,_e,_ve,_n,__,_re,_me,_m,_b,_er,_ret
		.BYTE	_a,_n,_y,_t,_h,_ing,_col,__t,_h,_ou,_g,_h,_dot,__,_I,_f,__,_Kai,_ret
		.BYTE	_h,_ad,_n,_apo,_t_,_c,_o,_me,__a,_l,_on,_g,_dot_dot_dot,_aof,_eol
_sc14_msg05:
		.BYTE	_Kei,_ddt_,_an0,_Y,_ou,__,_d,_on,_apo,_t_,_e,_ve,_n,__,_st,_and,_ret
		.BYTE	_a,__,_c,_h,_an,_c,_e,_exc,_aof,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_It_apo_s,__,_n,_o,__,_u,_se,_dot,__,_I_apo,_m,__g,_on,_n,_a,_ret
		.BYTE	_t,_a,_k,_e_,_c,_are,__of,__,_Tetsuo,__,_with,__,_m,_y,_ret
		.BYTE	_o,_w,_n,__t,_w,_o,__,_h,_and,_s,_exc,_eol
_sc14_msg06:
		.BYTE	_Kei,_ddt_,_an0,_T,_hat,__,_was,__,_d,_an,_g,_er,_ou,_s_,_b,_a,_c,_k,_ret
		.BYTE	_t,_her,_e,_exc,__,_W,_h,_en,__,_you,__,_f,_e,_ll,_col,__,_I,_ret
		.BYTE	_t,_h,_ou,_g,_h,_t_,_it,__,_was,__a,_ll,__,_o,_ve,_r,_dot,_aof,_eol
_sc14_msg07:
		.BYTE	_Kai,_ddt_,_W,_h,_en,__,_d,_i,_d_,_he,__g,_e,_t,__s,_o,_ret
		.BYTE	_p,_ow,_er,_f,_u,_l,_dot_dot_dot,_ret
		.BYTE	_Kaneda,_col,__,_are,__,_you,__s,_u,_re,__,_you,__,_c,_an,_ret
		.BYTE	_a,_ve,_n,_g,_e_,_Yamagata,_que,_eol
_sc14_msg08:
		.BYTE	_Kai,_ddt_,_I_,_ha,_d_,_to_,_s,_a,_ve,__,_you,__g,_u,_y,_s,_col,_ret
		.BYTE	_apo,_c,_a,_u,_se,__,_it,__,_was,__,_d,_an,_g,_er,_ou,_s,_dot,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_O,_k,_col,__,_I_,_g,_e,_t_,_it,_dot,_eol
_sc14_msg09:
		.BYTE	_Kai,_ddt_,_I,_s,_n,_apo,_t,__the,_re,__a,__w,_a,_y,__,_you,__,_c,_an,_ret
		.BYTE	_re,_c,_h,_ar,_g,_e,__the,__,_laser,__,_u,_s,_ing,__the,_ret
		.BYTE	_b,_i,_k,_e,_que,_eol
_sc14_msg0A:
		.BYTE	_Kai,_ddt_,_I,_f,__,_you,__w,_an,_t_,_to_,_re,_c,_h,_ar,_g,_e,_ret
		.BYTE	_it,_col,__,_le,_a,_ve,__,_it,__,_to_,_me,_exc,_eol
_sc14_msg0B:
		.BYTE	_Kai,_ddt_,_dot_dot_dot,_U,_g,_h,_dot,__,_Damn,__,_it,__a,_ll,_exc,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_B,_at,_t,_er,_y,_col,__,_b,_at,_t,_er,_y,_dot,_eol
_sc14_msg0C:
		.BYTE	_Kaneda,_ddt_,_W,_hat,_col,__s,_h,_ou,_l,_d_,_w,_e_,_d,_o,__,_it,_ret
		.BYTE	_with,__,_on,_e_,_or,__t,_w,_o,__of,__,_apo,_e,_m,_que,_ret
		.BYTE	_ret
		.BYTE	_Kai,_ddt_,_W,_ou,_l,_d,_n,_apo,_t_,_it,__,_be,__,_be,_t,_t,_er,__t,_o,_ret
		.BYTE	_j,_u,_st,__,_u,_se,__,_m,_y,__,_b,_i,_k,_e_,_i,_f,__,_you,_apo,_re,__,_n,_o,_t,_ret
		.BYTE	_s,_u,_re,_que,_eol
_sc14_msg0D:
		.BYTE	_Kaneda,_ddt_,_A,_h,_col,__the,__,_b,_i,_k,_e,_apo_s,__a,_l,_re,_ad,_y,_ret
		.BYTE	_r,_u,_n,_n,_ing,_dot_dot_dot,_ret
		.BYTE	_ret
		.BYTE	_Kai,_ddt_,_P,_f,_f,_t,_dot_dot_dot,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_H,_a,_ha,_dot_dot_dot,_eol
_sc14_msg0E:
		.BYTE	_I_,_be,_t_,_Tetsuo,_apo_s,__,_b,_a,_c,_k,__,_to_,_p,_l,_a,_y,_ing,_ret
		.BYTE	_bra,_K,_ing,__of,__the,__,_M,_ou,_n,_t,_a,_in,_bra,__a,_g,_a,_in,_dot,_eol
_sc14_msg0F:
		.BYTE	_Kei,_col,__w,_h,_o,__,_ha,_d_,_w,_at,_c,_h,_ed,__,_u,_s,__g,_e,_t,_ret
		.BYTE	_t,_hat,__,_f,_ar,_col,__s,_l,_ow,_l,_y,__,_o,_p,_en,_ed,__,_her,_ret
		.BYTE	_m,_ou,_t,_h,_dot,_ret
		.BYTE	_ret
		.BYTE	_Kei,_ddt_,_an0,_H,_e,_re,_col,__t,_a,_k,_e_,_this,_dot_dot_dot,_aof,_eol
_sc14_msg10:
		.BYTE	_I_,_w,_en,_t_,_b,_a,_c,_k,__,_to_,_t,_he,__,_O,_l,_y,_m,_p,_i,_c,_ret
		.BYTE	_G,_r,_ou,_n,_d,_s,_dot,_eol
_sc14_msg11:
		.BYTE	_Kei,__w,_at,_c,_h,_ed,__the,__,_f,_l,_a,_me,_s,_dot,_eol
_sc14_msg12:
		.BYTE	_Kai,_ddt_,_M,_y,__,_b,_i,_k,_e,_apo_s,__,_b,_u,_r,_n,_ing,__,_u,_p,_exc,_eol
_sc14_msg13:
		.BYTE	_Kaneda,_ddt_,_O,_h,_col,__,_you,__,_he,_ar,_d,__t,_hat,_dot_dot_dot,_ret
		.BYTE	_ret
		.BYTE	_Kai,_ddt_,_I_apo,_ve,__,_be,_en,__,_l,_i,_st,_en,_ing,__,_for,_ret
		.BYTE	_a,__w,_h,_i,_le,_dot,_eol
_sc14_msg14:
		.BYTE	_Kei,__,_h,_and,_ed,__,_me,__a,__,_m,_i,_r,_ro,_r,_dot,__,_I,_t,_ret
		.BYTE	_se,_e,_m,_ed,__,_to_,_s,_p,_ar,_k,_le,__i,_n,__the,__,_d,_ar,_k,_ret
		.BYTE	_of,__,_n,_ight,_dot,_eol

		SECTION_END		F14