
		SECTION_START	FD

		MSG_START	_sceneD_msg_lib
		MSG_IDX	_scD_msg00
		MSG_IDX	_scD_msg01
		MSG_IDX	_scD_msg02
		MSG_IDX	_scD_msg03
		MSG_IDX	_scD_msg04
		MSG_IDX	_scD_msg05
		MSG_IDX	_scD_msg06
		MSG_IDX	_scD_msg07
		MSG_IDX	_scD_msg08
		MSG_IDX	_scD_msg09
		MSG_IDX	_scD_msg0A
;		MSG_IDX	_scD_msg0B					; unused
		MSG_IDX	_scD_msg0C
		MSG_IDX	_scD_msg0D
		MSG_IDX	_scD_msg0E
_scD_msg00:
		.BYTE	_I_,_st,_o,_le,__the,__,_F,_dot,_P,_dot,_H,_dot,_col,__,_and,__,_with,_ret
		.BYTE	_Kei,__,_on,__,_b,_o,_ar,_d,_col,__,_f,_l,_ed,__,_to_,_t,_he,__,_l,_a,_b,_dot,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_G,_re,_at,_col,__w,_e_,_f,_in,_a,_ll,_y,_ret
		.BYTE	_m,_ad,_e_,_it,_dot,_eol
_scD_msg01:
		.BYTE	_Kei,_ddt_,_The,__,_Army,_apo_s,__,_her,_e,_exc,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_L,_e,_t,_apo_s,__,_b,_l,_ow,__the,_m,__,_ou,_t,_ret
		.BYTE	_of,__the,__w,_a,_y,_exc,_eol
_scD_msg02:
		.BYTE	_R,_ad,_i,_o,_ddt_,_str,_b,_z,_str,__,_str,_g,_z,_z,_t,_str,_ret
		.BYTE	_g,_i,_ve,__,_he,_a,_v,_y,__w,_e,_a,_p,_on,_s_,_l,_i,_c,_en,_se,_ret
		.BYTE	_str,_b,_z,_str,_ret
		.BYTE	_C,_a,_p,_t,_a,_in,_dot,_ret
		.BYTE	_ret
		.BYTE	_S,_e,_e,_m,_s_,_I_,_a,_c,_c,_id,_en,_t,_a,_ll,_y,__t,_u,_r,_n,_ed,_ret
		.BYTE	_on,__the,__,_r,_ad,_i,_o,_dot,_eol
_scD_msg03:
		.BYTE	_R,_ad,_i,_o,_ddt_,_str,_b,_z,_t,_str,_ret
		.BYTE	_t,_hat,__,_b,_o,_y,__,_m,_u,_st,__,_ha,_ve,__,_be,_en,__a,_ret
		.BYTE	_p,_at,_i,_en,_t,__i,_n,__the,__,_h,_o,_s,_p,_it,_a,_l,__w,_ing,_ret
		.BYTE	_of,__the,__,_l,_a,_b,_dot,_eol
_scD_msg04:
		.BYTE	_Kaneda,_ddt_,_W,_her,_e,_apo_s,__,_Tetsuo,_que,_exc,_ret
		.BYTE	_ret
		.BYTE	_Kei,_ddt_,_Q,_u,_i,_e,_t,_exc,__,_T,_u,_r,_n,__,_u,_p,__the,_ret
		.BYTE	_v,_o,_l,_u,_me,_exc,_eol
_scD_msg05:
		.BYTE	_R,_ad,_i,_o,_ddt_,_str,_g,_z,_z,_t,_str,_ret
		.BYTE	_e,_s,_c,_a,_p,_ed,__,_f,_ro,_m,__,_his,__,_c,_e,_ll,_dot,_ret
		.BYTE	_str,_b,_z,_t,_str,_ret
		.BYTE	_Tetsuo,__,_S,_h,_i,_m,_a,_dot,_eol
_scD_msg06:
		.BYTE	_R,_ad,_i,_o,_ddt_,_H,_e,_apo_s,__,_he,_ad,_ed,__,_for,__the,_ret
		.BYTE	_Nursery,_col,__,_you,_ret
		.BYTE	_str,_g,_z,_t,_str,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_Tetsuo,_que,_exc,_eol
_scD_msg07:
		.BYTE	_R,_ad,_i,_o,_ddt_,_str,_g,_z,_t,_str,_ret
		.BYTE	_s,_it,_u,_at,_i,_on,__i,_s_,_e,_x,_t,_re,_me,_l,_y,_ret
		.BYTE	_d,_an,_g,_er,_ou,_s,_exc,__,_P,_er,_m,_i,_s,_s,_i,_on,__,_to_,_k,_i,_ll,_exc,_ret
		.BYTE	_R,_e,_p,_e,_at,_col,__,_p,_er,_m,_i,_s,_s,_i,_on,__,_to_,_k,_i,_ll,_exc,_eol
_scD_msg08:
		.BYTE	_Kei,_ddt_,_The,__,_Nursery,__i,_s_,_o,_ve,_r,__t,_hat,_ret
		.BYTE	_w,_a,_y,_dot,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_W,_hat,_que,_ret
		.BYTE	_ret
		.BYTE	_Kei,_ddt_,_T,_u,_r,_n,__t,_hat,__w,_a,_y,_exc,_eol
_scD_msg09:
		.BYTE	_Kaneda,_ddt_,_R,_oo,_m,__,_A,_que,_ret
		.BYTE	_ret
		.BYTE	_Kei,_ddt_,_W,_hat,_apo,_re,__,_you,__,_d,_o,_ing,_col,__t,_hat,_apo_s,_ret
		.BYTE	_t,_he,__,_Nursery,_exc,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_I_,_c,_an,_apo,_t_,_st,_o,_p,_exc,_eol
_scD_msg0A:
		.BYTE	_Kei,_ddt_,_The,__,_b,_r,_a,_k,_e,_s,_exc,__,_D,_on,_apo,_t_,_you,_ret
		.BYTE	_u,_n,_d,_er,_st,_and,__,_b,_r,_a,_k,_e,_s,_que,_exc,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_I_,_d,_on,_apo,_t_,_ha,_ve,__,_m,_y,_ret
		.BYTE	_l,_i,_c,_en,_se,__,_with,__,_me,__t,_o,_d,_a,_y,_exc,_eol
;_scD_msg0B:
;		.BYTE	_Kaneda,_ddt_,_W,_her,_e,__the,__,_he,_ll,__,_d,_o,__w,_e,_ret
;		.BYTE	_g,_o,__,_f,_ro,_m,__,_her,_e,_que,_ret
;		.BYTE	_ret
;		.BYTE	_Kei,_ddt_,_S,_t,_r,_a,_ight,__a,_he,_ad,_dot_dot_dot,__,_or,_dot_dot_dot,_ret
;		.BYTE	_T,_hat,__w,_a,_y,_dot_dot_dot,_ret
;		.BYTE	_ret
;		.BYTE	_Kaneda,_ddt_,_E,_r,_dot_dot_dot,_eol
_scD_msg0C:
		.BYTE	_Kiyoko,_ddt_,_The,_re,_apo_s,__a,_n,__,_en,_t,_r,_y,_ret
		.BYTE	_e,_le,_v,_at,_or,_dot,__,_U,_se,__,_it,__,_to_,_g,_o,__,_d,_ow,_n,_ret
		.BYTE	_to_,_s,_u,_b,_le,_ve,_l,__,_8,_dot,_eol
_scD_msg0D:
		.BYTE	_W,_e_,_e,_ve,_n,_t,_u,_a,_ll,_y,__,_m,_ad,_e_,_it,__a,_ll,__the,_ret
		.BYTE	_w,_a,_y,__,_to_,_s,_u,_b,_le,_ve,_l,__,_8,_dot,_eol
_scD_msg0E:
		.BYTE	_A,__,_But,_t,_on,_ddt_,_F,_i,_re,_ret
		.BYTE	_B,__,_But,_t,_on,_ddt_,_D,_o,_d,_g,_e,_eol

		SECTION_END		FD
