
		SECTION_START	F6

		MSG_START	_scene6_msg_lib
		MSG_IDX	_sc6_msg00
		MSG_IDX	_sc6_msg01
		MSG_IDX	_sc6_msg02
		MSG_IDX	_sc6_msg03
		MSG_IDX	_sc6_msg04
		MSG_IDX	_sc6_msg05
		MSG_IDX	_sc6_msg06
		MSG_IDX	_sc6_msg07
		MSG_IDX	_sc6_msg08
		MSG_IDX	_sc6_msg09
		MSG_IDX	_sc6_msg0A
		MSG_IDX	_sc6_msg0B
		MSG_IDX	_sc6_msg0C
		MSG_IDX	_sc6_msg0D
		MSG_IDX	_sc6_msg0E
		MSG_IDX	_sc6_msg0F
		MSG_IDX	_sc6_msg10
		MSG_IDX	_sc6_msg11
		MSG_IDX	_sc6_msg12
		MSG_IDX	_sc6_msg13
		MSG_IDX	_sc6_msg14
		MSG_IDX	_sc6_msg15
		MSG_IDX	_sc6_msg16
		MSG_IDX	_sc6_msg17
		MSG_IDX	_sc6_msg18
		MSG_IDX	_sc6_msg19
		MSG_IDX	_sc6_msg1A
		MSG_IDX	_sc6_msg1B
		MSG_IDX	_sc6_msg1C
		MSG_IDX	_sc6_msg1D
		MSG_IDX	_sc6_msg1E
		MSG_IDX	_sc6_msg1F
		MSG_IDX	_sc6_msg20
		MSG_IDX	_sc6_msg21
		MSG_IDX	_sc6_msg22
		MSG_IDX	_sc6_msg23
		MSG_IDX	_sc6_msg24
		MSG_IDX	_sc6_msg25
		MSG_IDX	_sc6_msg26
		MSG_IDX	_sc6_msg27
		MSG_IDX	_sc6_msg28
		MSG_IDX	_sc6_msg29
		MSG_IDX	_sc6_msg2A
		MSG_IDX	_sc6_msg2B
		MSG_IDX	_sc6_msg2C
		MSG_IDX	_sc6_msg2D
		MSG_IDX	_sc6_msg2E
		MSG_IDX	_sc6_msg87					; scene 6 msg
		MSG_IDX	_sc6_msgAD					; scene 6 msg
_sc6_msg00:
		.BYTE	_Kaneda,_ddt_,_an1,_W,_a,_it,_exc,_aof,_ret
		.BYTE	_ret
		.BYTE	_W,_e_,_f,_in,_a,_ll,_y,__,_f,_ou,_n,_d_,_Tetsuo,_ret
		.BYTE	_ou,_t,_s,_id,_e,__the,__,_f,_a,_c,_t,_or,_i,_e,_s,_dot,_eol
_sc6_msg01:
		.BYTE	_H,_ow,_e,_ve,_r,_col,__,_Tetsuo,__,_and,__the,__g,_irl,_ret
		.BYTE	_were_,_be,_ing,__a,_t,_t,_a,_c,_k,_ed,__,_b,_y,__the,_ret
		.BYTE	_Clown,_s,_exc,__,_I_,_q,_u,_i,_c,_k,_l,_y,__,_j,_u,_m,_p,_ed,__of,_f,_ret
		.BYTE	_m,_y,__,_b,_i,_k,_e,_dot,_ret
		.BYTE	_ret
		.BYTE	_Kai,_ddt_,_Kaneda,_col,__w,_at,_c,_h,__,_ou,_t,_exc,_eol
_sc6_msg02:
		.BYTE	_W,_h,_oo,_s,_h,_exc,_ret
		.BYTE	_ret
		.BYTE	_A,_n,__i,_r,_on,__,_p,_i,_p,_e_,_s,_w,_u,_n,_g,__t,_ow,_ar,_d,_ret
		.BYTE	_Kaneda,_apo_s,__,_he,_ad,_dot,_eol
_sc6_msg03:
		.BYTE	_S,_w,_i,_s,_h,_exc,_ret
		.BYTE	_ret
		.BYTE	_The,__,_Clown,_apo_s,__i,_r,_on,__,_p,_i,_p,_e_,_c,_u,_t,_ret
		.BYTE	_t,_h,_r,_ou,_g,_h,__the,__a,_i,_r,_dot,_eol
_sc6_msg04:
		.BYTE	_Kai,_ddt_,_A,_re,__,_you,__,_j,_u,_st,__g,_o,_ing,__t,_o,_ret
		.BYTE	_a,_b,_and,_on,__,_Tetsuo,__,_l,_i,_k,_e_,_t,_hat,_que,_exc,_eol
_sc6_msg05:
		.BYTE	_T,_h,_u,_d,_exc,_ret
		.BYTE	_ret
		.BYTE	_Kai,_apo_s,__i,_r,_on,__,_p,_i,_p,_e_,_s,_l,_a,_m,_m,_ed,__i,_n,_t,_o,_ret
		.BYTE	_t,_he,__,_Clown,_apo_s,__,_he,_ad,_dot,_eol
_sc6_msg06:
		.BYTE	_W,_e_,_m,_an,_a,_g,_ed,__,_to_,_s,_a,_ve,__,_Tetsuo,_ret
		.BYTE	_and,__s,_u,_r,_r,_ou,_n,_d,_ed,__the,__,_Clown,_s,_dot,_eol
_sc6_msg07:
		.BYTE	_Tetsuo,__,_be,_c,_a,_me,__,_f,_u,_r,_i,_ou,_s_,_and,_ret
		.BYTE	_st,_ar,_t,_ed,__a,_t,_t,_a,_c,_k,_ing,__the,__,_Clown,_ret
		.BYTE	_w,_h,_o,__,_h,_u,_r,_t,__the,__g,_irl,_dot,_eol
_sc6_msg08:
		.BYTE	_Kaneda,_ddt_,_an0,_S,_t,_o,_p,__,_it,__a,_l,_re,_ad,_y,_col,_ret
		.BYTE	_Tetsuo,_exc,__,_You_apo_re,__g,_on,_n,_a,__,_k,_i,_ll,__,_h,_i,_m,_exc,_ret
		.BYTE	_Y,_ou,__w,_an,_t,__t,_hat,_que,_aof,_eol
_sc6_msg09:
		.BYTE	_Tetsuo,_ddt_,_an1,_I_,_w,_an,_t_,_h,_i,_m,__,_m,_o,_re,__t,_h,_an,_ret
		.BYTE	_d,_e,_ad,_exc,__,_I_apo,_ll,__s,_p,_l,_it,__,_his,__,_f,_u,_c,_k,_ing,_ret
		.BYTE	_he,_a,_d_,_o,_p,_en,_exc,_aof,_eol
_sc6_msg0A:
		.BYTE	_Tetsuo,_ddt_,_an1,_S,_h,_u,_t_,_u,_p,_exc,__,_D,_on,_apo,_t_,_or,_d,_er,_ret
		.BYTE	_me,__,_around,_exc,_aof,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_an0,_W,_e_,_were_,_j,_u,_st,__w,_or,_r,_i,_ed,_ret
		.BYTE	_a,_b,_ou,_t_,_you,_dot,_aof,_eol
_sc6_msg0B:
		.BYTE	_Tetsuo,_ddt_,_an1,_I_,_c,_ou,_l,_d,_apo,_ve,__,_h,_and,_l,_ed,__,_it,_ret
		.BYTE	_on,__,_m,_y,__,_ow,_n,_exc,__,_I_,_ad,_m,_it,__,_I_apo,_ve,_ret
		.BYTE	_be,_en,__,_be,_at,_en,__,_before,_dot_dot_dot,__,_But,__,_I,_ret
		.BYTE	_w,_on,_apo,_t,__a,_l,_w,_a,_y,_s_,_be,__,_on,__the,_ret
		.BYTE	_re,_c,_e,_i,_v,_ing,__,_en,_d,_exc,_aof,_ret
		.BYTE	_ret
		.BYTE	_G,_irl,_ddt_,_Tetsuo,_dot_dot_dot,_eol
_sc6_msg0C:
		.BYTE	_Tetsuo,_ddt_,_an1,_S,_h,_u,_t_,_u,_p,_exc,__,_G,_o,__a,_w,_a,_y,_exc,_aof,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_an0,_H,_e,_y,_col,__w,_a,_it,_exc,__,_W,_her,_e,_ret
		.BYTE	_are,__,_you,__g,_o,_ing,_que,_aof,_ret
		.BYTE	_ret
		.BYTE	_Tetsuo,_ddt_,_an0,_J,_u,_st,__,_le,_a,_ve,__,_me,__a,_l,_on,_e,_exc,_aof,_eol
_sc6_msg0D:
		.BYTE	_Tetsuo,__,_p,_u,_s,_h,_ed,__,_u,_s,__a,_w,_a,_y,__,_and,_ret
		.BYTE	_w,_a,_l,_k,_ed,__of,_f,_dot,_ret
		.BYTE	_ret
		.BYTE	_Tetsuo,_ddt_,_A,_g,_h,_exc,_eol
_sc6_msg0E:
		.BYTE	_Tetsuo,_ddt_,_an1,_A,_K,_I,_R,_A,_que,_exc,_ret
		.BYTE	_I_,_d,_on,_apo,_t_,_k,_n,_ow,__w,_h,_dot_dot_dot,_ret
		.BYTE	_A,_a,_a,_g,_h,_exc,_aof,_eol
_sc6_msg0F:
		.BYTE	_A,_K,_I,_R,_A,_exc,_eol
_sc6_msg10:
		.BYTE	_Kaneda,_ddt_,_Tetsuo,_dot_dot_dot,__,_you,_dot_dot_dot,_ret
		.BYTE	_ret
		.BYTE	_Kai,_ddt_,_H,_e,_y,_dot_dot_dot,_ret
		.BYTE	_ret
		.BYTE	_Tetsuo,__,_be,_g,_an,__,_to_,_t,_re,_m,_b,_le,_dot,_eol
_sc6_msg11:
		.BYTE	_S,_u,_d,_d,_en,_l,_y,_col,__,_b,_l,_a,_c,_k,_en,_ed,__,_c,_ar,_s_,_and,_ret
		.BYTE	_a,__,_C,_R,_C,__a,_p,_p,_ro,_a,_c,_h,_ed,_dot,_eol
_sc6_msg12:
		.BYTE	_I,_t_,_l,_oo,_k,_s_,_l,_i,_k,_e_,_an,__,_Army,__,_c,_ar,_dot,_eol
_sc6_msg13:
		.BYTE	_It_apo_s,__the,__,_C,_on,_t,_ro,_l,__,_R,_oo,_m,__,_C,_ar,_col,_ret
		.BYTE	_a,__,_l,_a,_b,_str,_on,_str,_w,_he,_e,_l,_s_,_f,_ro,_m,__the,_ret
		.BYTE	_l,_oo,_k,_s_,_of,__,_it,_dot,_eol
_sc6_msg14:
		.BYTE	_A,_s_,_I_,_a,_p,_p,_ro,_a,_c,_h,_ed,__the,__,_C,_R,_C,_col,_ret
		.BYTE	_se,_ve,_r,_a,_l,__,_me,_n,__i,_n,__,_l,_a,_b,__,_c,_o,_at,_s,_ret
		.BYTE	_c,_a,_me,__,_ou,_t,_dot,_eol
_sc6_msg15:
		.BYTE	_The,__,_me,_n,__s,_u,_r,_r,_ou,_n,_d,_ed,__,_Tetsuo,_ret
		.BYTE	_and,__,_e,_x,_a,_m,_in,_ed,__,_h,_i,_m,_dot,_eol
_sc6_msg16:
		.BYTE	_A,_s,_s,_i,_st,_an,_t_,_A,_ddt_,_T,_his,__i,_s_,_re,_a,_ll,_y,_ret
		.BYTE	_st,_r,_an,_g,_e,_exc,_ret
		.BYTE	_ret
		.BYTE	_A,_s,_s,_i,_st,_an,_t_,_B,_ddt_,_I_apo,_m,__g,_e,_t,_t,_ing,__a,_ret
		.BYTE	_b,_l,_u,_e_,_p,_at,_t,_er,_n,__,_on,__s,_c,_o,_p,_e_,_N,_o,_dot,__,_3,_dot,_ret
		.BYTE	_ret
		.BYTE	_D,_o,_c,_t,_or,_ddt_,_W,_hat,_que,__,_N,_o,_exc,__,_R,_e,_t,_r,_i,_e,_ve,__the,_ret
		.BYTE	_s,_u,_b,_j,_e,_c,_t_,_n,_ow,_exc,__,_H,_u,_r,_r,_y,_exc,_eol
_sc6_msg17:
		.BYTE	_L,_oo,_k,_s_,_l,_i,_k,_e,__the,_y,__g,_a,_ve,__,_Tetsuo,_ret
		.BYTE	_s,_o,_me,__s,_or,_t_,_of,__i,_n,_j,_e,_c,_t,_i,_on,_dot,_eol
_sc6_msg18:
		.BYTE	_S,_e,_e,_m,_s,__the,__,_me,_n,__i,_n,__w,_h,_it,_e_,_f,_ro,_m,_ret
		.BYTE	_t,_he,__,_C,_R,_C,__,_were_,_a,_f,_t,_er,__,_Tetsuo,_apo_s,_ret
		.BYTE	_b,_o,_d,_y,_dot,_eol
_sc6_msg19:
		.BYTE	_Kaneda,_ddt_,_L,_e,_a,_ve,__,_m,_y,__,_f,_r,_i,_en,_d_,_a,_l,_on,_e,_exc,_eol
_sc6_msg1A:
		.BYTE	_Kaneda,_ddt_,_H,_e,_y,_exc,__,_W,_hat,__,_d,_o,__,_you,__,_me,_an,_ret
		.BYTE	_b,_y,__,_bra,_s,_u,_b,_j,_e,_c,_t,_bra,_que,_eol
_sc6_msg1B:
		.BYTE	_A,_s_,_I_,_t,_r,_i,_ed,__,_to_,_r,_u,_n,__,_to_,_h,_i,_m,_col,__a,_ret
		.BYTE	_m,_an,__i,_n,__,_b,_l,_a,_c,_k,__,_b,_l,_o,_c,_k,_ed,__,_m,_y,__,_p,_at,_h,_dot,_eol
_sc6_msg1C:
		.BYTE	_Kaneda,_ddt_,_W,_hat,_apo_s,__,_with,__the,_ret
		.BYTE	_g,_e,_t,_str,_u,_p,_que,__,_Y,_ou,__g,_o,_ing,__,_to_,_a,_ret
		.BYTE	_f,_u,_n,_er,_a,_l,_que,_eol
_sc6_msg1D:
		.BYTE	_Man,_ddt_,_an1,_H,_e,_y,_col,__,_d,_on,_apo,_t_,_me,_s,_s_,_with,_ret
		.BYTE	_m,_y,__,_p,_o,_c,_k,_e,_t,_s,_exc,_aof,_eol
_sc6_msg1E:
		.BYTE	_W,_h,_y,_apo_s,__the,__,_Army,__,_her,_e,_que,_eol
_sc6_msg1F:
		.BYTE	_Man,_ddt_,_an1,_S,_t,_o,_p,__,_re,_s,_i,_st,_ing,__a,_r,_re,_st,_exc,_aof,_eol
_sc6_msg20:
		.BYTE	_O,_u,_t_,_of,__the,__w,_a,_y,_exc,_ret
		.BYTE	_ret
		.BYTE	_The,__,_m,_an,__,_f,_i,_r,_ed,__,_his,__,_p,_i,_st,_o,_l,_dot,_eol
_sc6_msg21:
		.BYTE	_Kaneda,_ddt_,_M,_f,_f,_col,__,_h,_u,_f,_f,_dot_dot_dot,_ret
		.BYTE	_ret
		.BYTE	_I_,_t,_r,_i,_ed,__,_to_,_y,_e,_ll,_col,__,_b,_u,_t_,_m,_y,_ret
		.BYTE	_m,_ou,_t,_h,__,_was,__,_c,_o,_ve,_r,_ed,_dot,_eol
_sc6_msg22:
		.BYTE	_Kaneda,_ddt_,_Y,_ou,__g,_u,_y,_s_,_are,__,_f,_ro,_m,__the,_ret
		.BYTE	_Army,_col,__,_r,_ight,_que,_eol
_sc6_msg23:
		.BYTE	_Kaneda,_ddt_,_W,_her,_e_,_are,__,_you,__t,_a,_k,_ing,_ret
		.BYTE	_Tetsuo,_que,_exc,_eol
_sc6_msg24:
		.BYTE	_Kaneda,_ddt_,_Damn,__,_it,_col,__g,_i,_ve,__,_Tetsuo,_ret
		.BYTE	_b,_a,_c,_k,_exc,_eol
_sc6_msg25:
		.BYTE	_T,_h,_w,_a,_c,_k,_exc,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_O,_w,_exc,_ret
		.BYTE	_ret
		.BYTE	_I_,_was,__,_k,_n,_o,_c,_k,_ed,__,_to_,_t,_he,__g,_r,_ou,_n,_d,_ret
		.BYTE	_b,_y,__the,__,_m,_an,_dot,_eol
_sc6_msg26:
		.BYTE	_Kaneda,_ddt_,_an0,_N,_o,_exc,__,_W,_a,_it,_exc,_aof,_ret
		.BYTE	_ret
		.BYTE	_The,__,_C,_R,_C,__,_and,__the,__,_Army,__,_c,_ar,_s,_ret
		.BYTE	_d,_ro,_ve,__a,_w,_a,_y,_dot,_eol
_sc6_msg27:
		.BYTE	_J,_u,_st,__a,_s_,_I_,_was,__g,_e,_t,_t,_ing,__,_u,_p,_col,__the,_ret
		.BYTE	_m,_an,__g,_o,_t,__i,_n,_to_,_t,_he,__,_c,_ar,_dot,_eol
_sc6_msg28:
		.BYTE	_D,_o,_c,_t,_or,_ddt_,_W,_e,_apo,_ve,__,_re,_c,_o,_ve,_r,_ed,__the,_ret
		.BYTE	_e,_xperimental,__s,_u,_b,_j,_e,_c,_t,_dot,__,_W,_e,_apo,_re,_ret
		.BYTE	_b,_a,_c,_k,__,_on,__t,_r,_a,_c,_k,__,_n,_ow,_dot,__,_B,_r,_ing,__,_h,_i,_m,_ret
		.BYTE	_in,_to_,_t,_he,__,_C,_R,_C,_dot,_eol
_sc6_msg29:
		.BYTE	_A,__,_m,_an,__i,_n,__,_b,_l,_a,_c,_k,__,_st,_e,_p,_p,_ed,__,_ou,_t_,_of,_ret
		.BYTE	_t,_he,__,_Army,__,_c,_ar,__,_to_,_p,_ro,_t,_e,_c,_t,__the,_ret
		.BYTE	_me,_n,__i,_n,__,_l,_a,_b,__,_c,_o,_at,_s,_dot,_eol
_sc6_msg2A:
		.BYTE	_The,__,_me,_n,__i,_n,__,_l,_a,_b,__,_c,_o,_at,_s_,_w,_e,_re,_ret
		.BYTE	_g,_e,_t,_t,_ing,__,_b,_a,_c,_k,__i,_n,_to_,_t,_he,__,_C,_R,_C,_dot,_eol
_sc6_msg2B:
		.BYTE	_Man,_ddt_,_an0,_D,_on,_apo,_t,__g,_e,_t,__a,_ll,_ret
		.BYTE	_u,_p,_p,_it,_y,_col,__,_k,_id,_exc,_aof,_ret
		.BYTE	_ret
		.BYTE	_The,__,_m,_an,__,_p,_in,_n,_ed,__,_m,_y,__a,_r,_m,_s,_ret
		.BYTE	_be,_h,_in,_d_,_m,_y,__,_b,_a,_c,_k,_dot,_eol
_sc6_msg2C:
		.BYTE	_Kaneda,_ddt_,_an0,_J,_u,_st,__,_k,_n,_o,_c,_k,__,_it,__of,_f,__,_n,_ow,_exc,_ret
		.BYTE	_T,_his,__w,_h,_o,_le,__t,_h,_ing,__,_ha,_p,_p,_en,_ed,_ret
		.BYTE	_be,_c,_a,_u,_se,__,_you,__t,_oo,_k,__,_m,_y,__,_b,_i,_k,_e_,_for,_ret
		.BYTE	_a,__s,_p,_in,_dot,__,_E,_n,_ou,_g,_h,__a,_l,_re,_ad,_y,_dot,_aof,_eol
_sc6_msg2D:
		.BYTE	_Tetsuo,_ddt_,_an1,_W,_h,_y,__,_d,_o,__,_you,__a,_l,_w,_a,_y,_s,_ret
		.BYTE	_ha,_ve,__,_to_,_t,_r,_y,__,_to_,_s,_a,_ve,__,_me,_que,_aof,_ret
		.BYTE	_ret
		.BYTE	_Kaneda,_ddt_,_an0,_U,_h,_dot_dot_dot,_aof,_eol
_sc6_msg2E:
		.BYTE	_Tetsuo,__s,_u,_d,_d,_en,_l,_y,__g,_r,_a,_b,_b,_ed,_ret
		.BYTE	_his,__,_he,_a,_d_,_and,__,_be,_g,_an,__t,_o,_ret
		.BYTE	_g,_ro,_an,__i,_n,__,_p,_a,_in,_dot,_ret
		.BYTE	_ret
		.BYTE	_Tetsuo,_ddt_,_an1,_A,_a,_h,_dot_dot_dot,_aof,_eol
_sc6_msg87:
		.BYTE	_Kaneda,_ddt_,_W,_h,_o,_a,_exc,_eol
_sc6_msgAD:
		.BYTE	_A,_K,_I,_R,_A,_exc,_exc,_exc,_eol

		SECTION_END		F6
