
		SECTION_START	F6

		MSG_START	_scene6_msg_lib
		MSG_IDX	_sc6_msg00
		MSG_IDX	_sc6_msg01
		MSG_IDX	_sc6_msg02
		MSG_IDX	_sc6_msg03
		MSG_IDX	_sc6_msg04
		MSG_IDX	_sc6_msg05
		MSG_IDX	_sc6_msg06
		MSG_IDX	_sc6_msg07
		MSG_IDX	_sc6_msg08
		MSG_IDX	_sc6_msg09
		MSG_IDX	_sc6_msg0A
		MSG_IDX	_sc6_msg0B
		MSG_IDX	_sc6_msg0C
		MSG_IDX	_sc6_msg0D
		MSG_IDX	_sc6_msg0E
		MSG_IDX	_sc6_msg0F
		MSG_IDX	_sc6_msg10
		MSG_IDX	_sc6_msg11
		MSG_IDX	_sc6_msg12
		MSG_IDX	_sc6_msg13
		MSG_IDX	_sc6_msg14
		MSG_IDX	_sc6_msg15
		MSG_IDX	_sc6_msg16
		MSG_IDX	_sc6_msg17
		MSG_IDX	_sc6_msg18
		MSG_IDX	_sc6_msg19
		MSG_IDX	_sc6_msg1A
		MSG_IDX	_sc6_msg1B
		MSG_IDX	_sc6_msg1C
		MSG_IDX	_sc6_msg1D
		MSG_IDX	_sc6_msg1E
		MSG_IDX	_sc6_msg1F
		MSG_IDX	_sc6_msg20
		MSG_IDX	_sc6_msg21
		MSG_IDX	_sc6_msg22
		MSG_IDX	_sc6_msg23
		MSG_IDX	_sc6_msg24
		MSG_IDX	_sc6_msg25
		MSG_IDX	_sc6_msg26
		MSG_IDX	_sc6_msg27
		MSG_IDX	_sc6_msg28
		MSG_IDX	_sc6_msg29
		MSG_IDX	_sc6_msg2A
		MSG_IDX	_sc6_msg2B
		MSG_IDX	_sc6_msg2C
		MSG_IDX	_sc6_msg2D
		MSG_IDX	_sc6_msg2E
		MSG_IDX	_sc6_msg87					; scene 6 msg
		MSG_IDX	_sc6_msgAD					; scene 6 msg
_sc6_msg00:
		.BYTE	_______,_ka__ne__da,_lt,_an1,_ma,_te,_ex,_ex,_aof,_ret
		.BYTE	_KO,_N_,_BI,_NA,_str,_TO,_no,___,_ha,_zu,_re,_de,___,_O_,_RE,_ta,_ti,_ha,___,_to,_u_,_to,_u_,_ret
		.BYTE	_te_tsu__o_,_wo,___,_mi,_tu,_ke,_ta,_ze,_cr,_eol
_sc6_msg01:
		.BYTE	_da,_ga,_col,_te_tsu__o_,_to,___,_o_,_n_,_na,_ha,___,_KU,_RA,_U_,_N_,_no,_ya,_tu,_ra,_ni,_ret
		.BYTE	_bu,_ti,_no,_me,_sa,_re,_te,_i_,_ta,_cr,_ret
		.BYTE	_O_,_RE,_ha,_a_,_wa,_te,_te,___,_BA,_I_,_KU,_wo,___,_to,_bi,_o_,_ri,_ta,_cr,_ret
		.BYTE	___________,_ka,_i_,_lt,_ka__ne__da,_col,_a_,_bu,_ne,_e_,_ex,_eol
_sc6_msg02:
		.BYTE	_DO,_SU,_TT,_ex,_ex,___,_te,_tu,_PA,_I_,_PU,_ga,___,_ka__ne__da,_no,___,_a_,_ta,_ma,_ni,_ret
		.BYTE	_hu,_ri,_o_,_ro,_sa,_re,_ta,_cr,_eol
_sc6_msg03:
		.BYTE	_SI,_UU,_TT,_ex,___,_KU,_RA,_U_,_N_,_no,___,_te,_tu,_PA,_I_,_PU,_ha,___,_ku,_u_,_wo,_ki,_tt,_ta,_cr,_eol
_sc6_msg04:
		.BYTE	___________,_ka,_i_,_lt,_ka__ne__da,_AA,_col,___,_te_tsu__o_,_wo,___,_mi,_su,_te,_ru,_ki,_ka,_ex,_eol
_sc6_msg05:
		.BYTE	_BO,_KA,_TT,___,_ex,___,_ka,_i_,_no,___,_te,_tu,_PA,_I_,_PU,_ga,___,_KU,_RA,_U_,_N_,_no,_ret
		.BYTE	_ko,_u_,_to,_u_,_bu,_wo,___,_ti,_oo,_ku,_ge,_ki,_si,_ta,_cr,_eol
_sc6_msg06:
		.BYTE	_O_,_RE,_ta,_ti,_ha,___,_te_tsu__o_,_wo,___,_ta,_su,_ke,_da,_si,_col,_KU,_RA,_U_,_N_,_wo,_ret
		.BYTE	_to,_o_,_ma,_ki,_ni,_si,_ta,_cr,_eol
_sc6_msg07:
		.BYTE	_o_,_n_,_na,_wo,___,_ya,_ra,_re,_ta,___,_te_tsu__o_,_ha,___,_MU,_KI,_ni,_na,_tt,_te,_ret
		.BYTE	_KU,_RA,_U_,_N_,_ni,___,_na,_gu,_ri,_ka,_ka,_tt,_ta,_cr,_eol
_sc6_msg08:
		.BYTE	_ka__ne__da,_lt,_an0,_mo,_u_,_yo,_se,_tt,_col,___,_te_tsu__o_,_TT,_ex,___,_ko,_ro,_su,_ki,_ka,_ex,_aof,_eol
_sc6_msg09:
		.BYTE	_______,_te_tsu__o_,_lt,_an1,_so,_u_,_da,_yo,_col,_ko,_ro,_su,_n_,_da,_yo,_cr,_ret
		.BYTE	_______________________,_a_,_ta,_ma,_wo,___,_wa,_tt,_te,$89,_cr,_aof,_eol
_sc6_msg0A:
		.BYTE	_______,_te_tsu__o_,_lt,_an1,_u_,_ru,_sa,_i_,_col,___,_O_,_RE,_ni,_me,_i_,_re,_i_,_su,_n_,_na,_str,_ex,_aof,_ret
		.BYTE	_______,_ka__ne__da,_lt,_an0,_si,_n_,_pa,_i_,___,_si,_te,_ta,_n_,_da,_zo,_cr,_aof,_eol
_sc6_msg0B:
		.BYTE	_______,_te_tsu__o_,_lt,_an1,_O_,_RE,_hi,_to,_ri,_da,_tt,_te,___,_ya,_re,_ta,_n_,_da,_AA,_cr,_ret
		.BYTE	_______________________,_so,_ri,_yy,___,_a_,_n_,_to,_ki,_ha,___,_ya,_ra,_re,_ta,_sa,_cr,_ret
		.BYTE	_______________________,_de,_mo,___,_O_,_RE,_da,_tt,_te,___,_i_,_tu,_ma,_de,_mo,_ret
		.BYTE	_______________________,_ya,_ra,_re,_te,_n_,_zi,_yy,___,_ne,$89,_n_,_da,_yo,_OO,_cr,_aof,_ret
		.BYTE	_______,_o_,_n_,_na,_lt,_te_tsu__o_,_ku,_n_,_dot,_dot,_dot,_eol
_sc6_msg0C:
		.BYTE	_______,_te_tsu__o_,_lt,_an1,_u_,_ru,_se,$89,_col,___,_ku,_ru,_na,_AA,_cr,_aof,_ret
		.BYTE	_______,_ka__ne__da,_lt,_an0,_o_,_i_,___,_ma,_te,_col,___,_do,_ko,_ni,___,_i_,_ku,_n_,_da,_cr,_aof,_ret
		.BYTE	_______,_te_tsu__o_,_lt,_an1,_O_,_RE,_ni,___,_ka,_ma,_u_,_na,_ex,_aof,_eol
_sc6_msg0D:
		.BYTE	_O_,_RE,_ta,_ti,_wo,___,_hu,_ri,_ha,_ra,_tt,_te,_col,___,_te_tsu__o_,_ha,___,_a_,_ru,_ki,_da,_si,_ta,_cr,_ret
		.BYTE	_______,_te_tsu__o_,_lt,_u_,_tt,_ex,_eol
_sc6_msg0E:
		.BYTE	_______,_te_tsu__o_,_lt,_an1,_A_,_KI,_RA,_qe,_ex,___,_so,_n_,_na,_ya,_tu,_ha,___,_si,_ra,_na,_dot,_dot,_dot,_ret
		.BYTE	_______________________,_u_,_wa,_AA,_str,_TT,_ex,_aof,_eol
_sc6_msg0F:
		.BYTE	___________________,_lt,_A_,_KI,_RA,_ex,_ex,_ex,_eol
_sc6_msg10:
		.BYTE	_______,_ka__ne__da,_lt,_te_tsu__o_,_dot,_dot,_dot,___,_o_,_ma,_e_,_dot,_dot,_dot,_ret
		.BYTE	___________,_ka,_i_,_lt,_o_,_i_,_dot,_dot,_dot,_ret
		.BYTE	_te_tsu__o_,_ha,___,_u_,_zu,_ku,_ma,_tt,_te,_si,_ma,_tt,_ta,_cr,_eol
_sc6_msg11:
		.BYTE	_to,_tu,_ze,_n_,___,_ro,_zi,_no,_mu,_ko,_u_,_ni,___,_C,_dot,_R,_dot,_C,_to,___,_ku,_ro,_nu,_ri,_no,_ret
		.BYTE	_ku,_ru,_ma,_ga,___,_su,_ga,_ta,_wo,___,_a_,_ra,_wa,_si,_ta,_cr,_eol
_sc6_msg12:
		.BYTE	_A_,_str,_MI,_str,_no,___,_ku,_ru,_ma,_no,_yo,_u_,_da,_ze,_cr,_eol
_sc6_msg13:
		.BYTE	_KO,_N_,_TO,_RO,_str,_RU,_dot,_RU,_str,_MU,_dot,_KA,_str,_col,___,_i_,_do,_u_,_ke,_n_,_ki,_uu,_u_,_si,_tu,_no,_ret
		.BYTE	_yo,_u_,_na,_mo,_no,_da,_ze,_cr,_eol
_sc6_msg14:
		.BYTE	_O_,_RE,_ga,___,_ka,_ke,_yo,_ro,_u_,_to,___,_su,_ru,_to,_col,___,_C,_dot,_R,_dot,_C,_ka,_ra,_ret
		.BYTE	_ha,_ku,_i_,_no,___,_o_,_to,_ko,_ta,_ti,_ga,___,_to,_bi,_da,_si,_te,_ki,_ta,_cr,_eol
_sc6_msg15:
		.BYTE	_o_,_to,_ko,_ta,_ti,_ha,___,_te_tsu__o_,_wo,___,_to,_ri,_ka,_ko,_mi,_col,_ka,_ra,_da,_wo,_ret
		.BYTE	_si,_ra,_be,_ha,_zi,_me,_ta,_cr,_eol
_sc6_msg16:
		.BYTE	_zi,_oo,_si,_uu,_A,_lt,_ti,_yo,_tt,_to,___,_yo,_u_,_su,_ga,___,_o_,_ka,_si,_i_,_de,_su,_ne,_cr,_ret
		.BYTE	_zi,_oo,_si,_uu,_B,_lt,_3,_no,_SU,_KO,_str,_PU,_ni,___,_a_,_o_,_no,_PA,_TA,_str,_N_,_ga,_ret
		.BYTE	_______________________,_de,_te,_i_,_ma,_su,_ex,_ret
		.BYTE	___,_DO,_KU,_TA,_str,_lt,_i_,_tt,_col,___,_i_,_ka,_n_,_ex,___,_ZI,_TT,_KE,_N_,_TA,_I_,_wo,_ret
		.BYTE	_______________________,_ka,_i_,_si,_uu,_u_,___,_su,_ru,_n_,_da,_cr,___,_i_,_so,_ge,_ex,_ex,_eol
_sc6_msg17:
		.BYTE	_te_tsu__o_,_ha,___,_u_,_de,_ni,___,_na,_ni,_ka,_no,___,_ti,_uu,_u_,_si,_yy,_wo,_ret
		.BYTE	_u_,_ta,_re,_ta,_mi,_ta,_i_,_da,_ze,_cr,_eol
_sc6_msg18:
		.BYTE	_C,_dot,_R,_dot,_C,_no,___,_ha,_ku,_i_,_no,_o_,_to,_ko,_ta,_ti,_ga,___,_ya,_tt,_te,_ki,_ta,_no,_ha,_ret
		.BYTE	_te_tsu__o_,_no,_ka,_ra,_da,_ga,___,_mo,_ku,_te,_ki,_ra,_si,_i_,_ze,_cr,_eol
_sc6_msg19:
		.BYTE	_______,_ka__ne__da,_lt,_te_tsu__o_,_wo,___,_do,_u_,_su,_ru,_tu,_mo,_ri,_da,_cr,_ret
		.BYTE	_______________________,_te_tsu__o_,_OO,_col,_to,_ri,_ka,_e_,_si,_te,_ya,_ru,_ka,_ra,_na,_AA,_cr,_eol
_sc6_msg1A:
		.BYTE	_______,_ka__ne__da,_lt,_ZI,_TT,_KE,_N_,_TA,_I_,_tt,_te,___,_na,_n_,_da,_yo,_OO,_col,___,_O_,_I_,_TT,_ex,_eol
_sc6_msg1B:
		.BYTE	_ka,_ke,_yo,_ro,_u_,_to,_si,_ta,___,_O_,_RE,_no,_ma,_e_,_ni,___,_ku,_ro,_hu,_ku,_no,___,_o_,_to,_ko,_ga,_ret
		.BYTE	_ta,_ti,_hu,_sa,_ga,_tt,_ta,_cr,_eol
_sc6_msg1C:
		.BYTE	_______,_ka__ne__da,_lt,_na,_n_,_da,_yo,___,_o_,_me,_str,_ha,_col,___,_so,_u_,_si,_ki,_ga,_e_,_ri,_ka,_qe,_eol
_sc6_msg1D:
		.BYTE	_______,_o_,_to,_ko,_lt,_an1,_ko,_ra,_tt,_col,___,_u_,_ti,_PO,_KE,_TT,_TO,_wo,_ret
		.BYTE	_______________________,_sa,_wa,_ru,_n_,_zi,_yy,_na,_i_,_tt,_ex,_aof,_eol
_sc6_msg1E:
		.BYTE	_na,_n_,_de,___,_A_,_str,_MI,_str,_ga,___,_ko,_n_,_na,_to,_ko,_ro,_he,_qe,_eol
_sc6_msg1F:
		.BYTE	_______,_o_,_to,_ko,_lt,_an1,_ko,_ra,_tt,_col,___,_ki,_sa,_ma,___,_te,_i_,_ko,_u_,_su,_ru,_no,_ka,_ex,_aof,_eol
_sc6_msg20:
		.BYTE	_DO,$88,_GI,_UU,_str,_N_,_ex,_ret
		.BYTE	_o_,_to,_ko,_no,___,_PI,_SU,_TO,_RU,_ga,___,_hi,_wo,_hu,_i_,_ta,_cr,_eol
_sc6_msg21:
		.BYTE	_______,_ka__ne__da,_lt,_HU,_GA,_str,___,_HU,_GA,_str,_cr,_ret
		.BYTE	_sa,_ke,_bo,_u_,_to,_si,_ta,_ga,_col,___,_O_,_RE,_ha,___,_o_,_to,_ko,_ni,___,_ku,_ti,_wo,_ret
		.BYTE	_hu,_sa,_ga,_re,_te,_si,_ma,_tt,_ta,_cr,_eol
_sc6_msg22:
		.BYTE	_______,_ka__ne__da,_lt,_O_,_I_,___,_o_,_me,_str,_col,___,_A_,_str,_MI,_str,_da,_ro,_u_,_qe,_eol
_sc6_msg23:
		.BYTE	_______,_ka__ne__da,_lt,_te_tsu__o_,_wo,___,_do,_ko,_ni,___,_tu,_re,_te,_i_,_ku,_n_,_da,_yo,_OO,_str,_ex,_eol
_sc6_msg24:
		.BYTE	_______,_ka__ne__da,_lt,_ku,_so,_tt,___,_te_tsu__o_,_wo,___,_ka,_e_,_se,_str,_ex,_eol
_sc6_msg25:
		.BYTE	_BO,_KA,_TT,_ex,_ret
		.BYTE	_______,_ka__ne__da,_lt,_U_,_TT,_ex,_ret
		.BYTE	_O_,_RE,_ha,___,_o_,_to,_ko,_ni,___,_na,_gu,_ri,_ta,_o_,_sa,_re,_te,_si,_ma,_tt,_ta,_cr,_eol
_sc6_msg26:
		.BYTE	_______,_ka__ne__da,_lt,_an0,_ku,_so,_u_,_str,___,_a_,_tt,___,_ma,_te,$89,_ex,_aof,_ret
		.BYTE	_C,_dot,_R,_dot,_C,_to,___,_A_,_str,_MI,_str,_no,_ku,_ru,_ma,_ha,___,_ha,_si,_ri,_sa,_tt,_te,_ret
		.BYTE	_si,_ma,_tt,_ta,_cr,_eol
_sc6_msg27:
		.BYTE	_o_,_re,_ga,___,_yo,_u_,_ya,_ku,___,_ta,_ti,_a_,_ga,_tt,_ta,_to,_ki,_ni,_ha,_ret
		.BYTE	_o_,_to,_ko,_ha,___,_ku,_ru,_ma,_ni,___,_no,_ri,_ko,_mi,_ka,_ke,_te,_i_,_ta,_cr,_eol
_sc6_msg28:
		.BYTE	___,_DO,_KU,_TA,_str,_lt,_ZI,_TT,_KE,_N_,_TA,_I_,_ha,___,_ka,_i_,_si,_uu,_u_,_si,_ta,_cr,_ret
		.BYTE	_______________________,_ho,_u_,_i_,_mo,_u_,_ha,___,_to,_i_,_te,_i_,_i_,_zo,_col,_ret
		.BYTE	_______________________,_C,_dot,_R,_dot,_C,_wo,___,_da,_si,_te,_ku,_re,_cr,_eol
_sc6_msg29:
		.BYTE	_ku,_ro,_hu,_ku,_no,_A_,_str,_MI,_str,_ga,___,_ku,_ru,_ma,_ka,_ra,___,_de,_te,_ki,_te,_col,_ret
		.BYTE	_ha,_ku,_i_,_no,_o_,_to,_ko,_ta,_ti,_wo,___,_ma,_mo,_tt,_te,_i_,_ru,_cr,_eol
_sc6_msg2A:
		.BYTE	_ha,_ku,_i_,_no,_o_,_to,_ko,_ta,_ti,_ga,___,_C,_dot,_R,_dot,_C,_ni,___,_no,_ri,_ko,_mo,_u_,_to,_ret
		.BYTE	_si,_te,_i_,_ru,_cr,_eol
_sc6_msg2B:
		.BYTE	_______,_o_,_to,_ko,_lt,_an0,_ko,_zo,_u_,_col,___,_i_,_i_,_ki,_ni,_na,_ru,_na,_yo,_ex,_aof,_ret
		.BYTE	_o_,_to,_ko,_ha,___,_O_,_RE,_wo,___,_ha,_ga,_i_,_zi,_me,_ni,_si,_ta,_cr,_eol
_sc6_msg2C:
		.BYTE	_______,_ka__ne__da,_lt,_an0,_i_,_i_,_ka,_ge,_n_,_ni,_si,_ro,_ex,_ret
		.BYTE	_______________________,_mo,_to,_ha,_to,_i_,_e_,_ba,_col,_o_,_ma,_e_,_ga,___,_hi,_to,_no,_ret
		.BYTE	_______________________,_BA,_I_,_KU,_wo,___,_ka,_tt,_te,_ni,___,_no,_ri,_ma,_wa,_si,_ta,_no,_ga,_ret
		.BYTE	_______________________,_wa,_ru,_i_,_n_,_da,_cr,___,_ya,_me,_ro,_ex,_aof,_eol
_sc6_msg2D:
		.BYTE	_______,_te_tsu__o_,_lt,_an1,_do,_u_,_si,_te,___,_i_,_tu,_mo,___,_ta,_su,_ke,_ni,___,_ku,_ru,_n_,_da,_cr,_aof,_ret
		.BYTE	_______,_ka__ne__da,_lt,_an0,_e_,_tt,_dot,_dot,_dot,_aof,_eol
_sc6_msg2E:
		.BYTE	_te_tsu__o_,_ha,___,_ki,_uu,_u_,_ni,___,_a_,_ta,_ma,_wo,___,_ka,_ka,_e_,_te,_col,_ret
		.BYTE	_u_,_me,_ki,_ha,_zi,_me,_ta,_cr,_ret
		.BYTE	_______,_te_tsu__o_,_lt,_an1,_u_,_u_,_str,_tt,_cr,_aof,_eol
_sc6_msg87:
		.BYTE	_______,_ka__ne__da,_lt,_o_,_tt,_to,_ex,_eol
_sc6_msgAD:
		.BYTE	___________________,_lt,_A_,_KI,_RA,_ex,_ex,_ex,_eol

		SECTION_END		F6
