
		SECTION_START	F11

		MSG_START	_scene11_msg_lib
		MSG_IDX	_sc11_msg00
		MSG_IDX	_sc11_msg01
		MSG_IDX	_sc11_msg02
		MSG_IDX	_sc11_msg03
		MSG_IDX	_sc11_msg04
		MSG_IDX	_sc11_msg05
		MSG_IDX	_sc11_msg06
		MSG_IDX	_sc11_msg07
		MSG_IDX	_sc11_msg08
		MSG_IDX	_sc11_msg09
		MSG_IDX	_sc11_msg0A
		MSG_IDX	_sc11_msg0B
		MSG_IDX	_sc11_msg0C
		MSG_IDX	_sc11_msg0D
		MSG_IDX	_sc11_msg0E
		MSG_IDX	_sc11_msg0F
		MSG_IDX	_sc11_msg10
		MSG_IDX	_sc11_msg11
		MSG_IDX	_sc11_msg12
		MSG_IDX	_sc11_msg13
		MSG_IDX	_sc11_msg14
		MSG_IDX	_sc11_msg15
		MSG_IDX	_sc11_msg16
		MSG_IDX	_sc11_msg17
		MSG_IDX	_sc11_msg18
		MSG_IDX	_sc11_msg19
		MSG_IDX	_sc11_msg1A
		MSG_IDX	_sc11_msg1B
		MSG_IDX	_sc11_msg1C
		MSG_IDX	_sc11_msg1D
		MSG_IDX	_sc11_msg1E
		MSG_IDX	_sc11_msg1F
		MSG_IDX	_sc11_msg20
		MSG_IDX	_sc11_msg21
		MSG_IDX	_sc11_msg22
		MSG_IDX	_sc11_msg23
		MSG_IDX	_sc11_msg24
		MSG_IDX	_sc11_msg25
		MSG_IDX	_sc11_msg26
		MSG_IDX	_sc11_msg27
		MSG_IDX	_sc11_msg28
		MSG_IDX	_sc11_msg95					; scene 11 msg
		MSG_IDX	_sc11_msg98					; scene 11 msg
_sc11_msg00:
		.BYTE	_RA,_BO,_wo,___,_da,_tt,_so,_u_,_si,_ta,___,_O_,_RE,_to,_KE,_I_,_ha,___,_ha,_ru,_ki,_ya,_ni,_ret
		.BYTE	_mu,_ka,_tt,_ta,_cr,_eol
_sc11_msg01:
		.BYTE	_O_,_RE,_ta,_ti,_ha,___,_ka,_i_,_to,___,_te,_i_,_bo,_u_,_ni,___,_ya,_tt,_te,_ki,_ta,_cr,_eol
_sc11_msg02:
		.BYTE	___________,_ka,_i_,_lt,_an0,_O_,_RE,_ha,___,_ya,_ma,_ga,_ta,_to,___,_ha,_ru,_ki,_ya,_ni,___,_i_,_tt,_ta,_cr,_ret
		.BYTE	_______________________,_so,_n_,_de,___,_mi,_tu,_ke,_ta,_n_,_da,_col,_ret
		.BYTE	_______________________,_GU,_TI,_YY,_GU,_TI,_YY,_ni,___,_ko,_wa,_sa,_re,_ta,___,_mi,_se,_no,_na,_ka,_de,_ret
		.BYTE	_______________________,_te,_n_,_ti,_oo,_u_,_ga,___,_si,_n_,_de,_te,_dot,_dot,_dot,_aof,_eol
_sc11_msg03:
		.BYTE	___________,_ka,_i_,_lt,_an0,_GA,_RA,_KU,_TA,_no,_u_,_e_,_de,_ret
		.BYTE	_______________________,_te_tsu__o_,_no,_ya,_tu,_ga,___,_wa,_ra,_tt,_te,_ya,_ga,_ru,_no,_wo,_cr,_aof,_eol
_sc11_msg04:
		.BYTE	___________,_ka,_i_,_lt,_an0,_te_tsu__o_,_ha,___,_a_,_i_,_ka,_wa,_ra,_zu,___,_wa,_ra,_tt,_te,_ta,_cr,_ret
		.BYTE	_______________________,_de,_mo,_col,___,_te_tsu__o_,_ga,___,_ka__ne__da,_no,_BA,_I_,_KU,_wo,_ret
		.BYTE	_______________________,_do,_u_,_de,_mo,_i_,_i_,_ya,_dot,_dot,_dot,_to,___,_i_,_tt,_ta,_to,_ki,_ret
		.BYTE	_______________________,_da,_tt,_ta,_cr,_aof,_eol
_sc11_msg05:
		.BYTE	___________,_ka,_i_,_lt,_an0,_te,_me,$89,_dot,_dot,_dot,_ex,_to,___,_ya,_ma,_ga,_ta,_ga,___,_sa,_ke,_n_,_de,_ret
		.BYTE	_______________________,_GA,_RA,_KU,_TA,_wo,___,_no,_bo,_tt,_te,_i_,_tt,_ta,_cr,_ret
		.BYTE	_______________________,_te_tsu__o_,_no,_ka,_mi,_no,_ke,_ga,___,_sa,_ka,_da,_tt,_te,_tt,_ta,_dot,_dot,_dot,_aof,_eol
_sc11_msg06:
		.BYTE	___________,_ka,_i_,_lt,_an0,_te_tsu__o_,_ha,___,_na,_n_,_ka,___,_wa,_ke,_no,_wa,_ka,_n_,_na,_i_,_ret
		.BYTE	_______________________,_ti,_ka,_ra,_de,___,_ya,_ma,_ga,_ta,_wo,___,_si,_me,_tu,_ke,_ta,_cr,_ret
		.BYTE	_______________________,_ya,_ma,_ga,_ta,_ha,___,_ku,_ru,_si,_so,_u_,_ni,___,_u_,_me,_i_,_te,_ret
		.BYTE	_______________________,_a_,_ta,_ma,_wo,___,_o_,_sa,_e_,_ta,_dot,_dot,_dot,_aof,_eol
_sc11_msg07:
		.BYTE	_______,_ka__ne__da,_lt,_zu,_tt,_to,___,_i_,_tt,_si,_oo,_da,_tt,_ta,_n_,_da,_cr,_ret
		.BYTE	_______________________,_a_,_i_,_tu,_no,_ko,_to,_na,_ra,___,_na,_n_,_de,_mo,___,_si,_tt,_te,_i_,_ru,_ret
		.BYTE	_______________________,_dot,_dot,_dot,___,_DO,_ZI,_de,___,_i_,_tu,_mo,___,_mi,_n_,_na,_ni,_ret
		.BYTE	_______________________,_na,_ka,_sa,_re,_te,_ta,_dot,_dot,_dot,_eol
_sc11_msg08:
		.BYTE	___________,_ka,_i_,_lt,_an0,_so,_u_,_da,_dot,_dot,_dot,___,_o_,_ma,_e_,_no,_BA,_I_,_KU,_ha,_ret
		.BYTE	_______________________,_do,_ko,_ka,_tt,_te,___,_ki,_i_,_te,_ta,_ze,_cr,_aof,_eol
_sc11_msg09:
		.BYTE	_O_,_RE,_ha,___,_ka,_i_,_ga,___,_to,_tt,_te,_ki,_ta,___,_ya,_ma,_ga,_ta,_no,_BA,_I_,_KU,_ni,_ret
		.BYTE	_ma,_ta,_ga,_tt,_ta,_cr,_eol
_sc11_msg0A:
		.BYTE	_______,_KI,_YO,_KO,_lt,_an0,_wa,_ta,_si,_ta,_ti,_no,___,_te,_tu,_da,_i_,_wo,___,_si,_te,_mo,_ra,_u_,_WA,_cr,_aof,_eol
_sc11_msg0B:
		.BYTE	_na,_ze,___,_KE,_I_,_ga,___,_GA,_KI,_do,_mo,_na,_n_,_ka,_ni,_dot,_dot,_dot,_eol
_sc11_msg0C:
		.BYTE	_______,_ka__ne__da,_lt,_an0,_da,_i_,_zi,_oo,_u_,_bu,_da,_cr,___,_te_tsu__o_,_no,_ya,_tu,_wo,_ret
		.BYTE	_______________________,_ta,_ta,_ki,_no,_me,_su,_ma,_de,_ha,___,_ku,_ta,_ba,_ru,_wa,_ke,_ni,_ha,_ret
		.BYTE	_______________________,_i_,_ka,_ne,$89,_dot,_dot,_dot,_aof,_eol
_sc11_msg0D:
		.BYTE	___________,_KE,_I_,_lt,_a_,___,_a_,_na,_ta,_dot,_dot,_dot,___,_ki,_yy,_a_,_str,_tt,_cr,_ret
		.BYTE	_______,_ka__ne__da,_lt,_an0,_KE,_I_,_TT,___,_do,_u_,_si,_ta,_AA,_str,_TT,_ex,_aof,_eol
_sc11_msg0E:
		.BYTE	_______,_ka__ne__da,_lt,_o_,_ma,_e_,_dot,_dot,_dot,___,_a_,_no,_yo,_ru,_no,_dot,_dot,_dot,_eol
_sc11_msg0F:
		.BYTE	_GA,_KI,_ha,___,_su,_i_,_me,_n_,_wo,___,_u_,_ka,_bi,_na,_ga,_ra,___,_KE,_I_,_ni,_ret
		.BYTE	_ti,_ka,_du,_i_,_te,_i_,_tt,_ta,_cr,_eol
_sc11_msg10:
		.BYTE	_______,_ka__ne__da,_lt,_KE,_I_,_wo,___,_do,_u_,_su,_ru,_n_,_da,_yo,_OO,_ex,_eol
_sc11_msg11:
		.BYTE	_O_,_RE,_ha,___,_ka,_ke,_yo,_ro,_u_,_to,_si,_ta,_ga,___,_ka,_ra,_da,_ga,___,_do,_u_,_si,_te,_mo,_ret
		.BYTE	_u_,_go,_ka,_na,_i_,_cr,_eol
_sc11_msg12:
		.BYTE	_______,_ka__ne__da,_lt,_ma,_te,$89,_ex,___,_KE,$89,_I_,_TT,_ex,_eol
_sc11_msg13:
		.BYTE	___________,_ka,_i_,_lt,_ki,_e_,_ta,_AA,_cr,_eol
_sc11_msg14:
		.BYTE	_______,_ka__ne__da,_lt,_ko,_no,_ya,_ro,_u_,_col,___,_do,_ko,_he,___,_i_,_tt,_ta,_AA,_str,_cr,_eol
_sc11_msg15:
		.BYTE	_KE,_I_,_to,_GA,_KI,_no,_su,_ga,_ta,_ha,___,_do,_ko,_ni,_mo,_na,_ka,_tt,_ta,_cr,_eol
_sc11_msg16:
		.BYTE	_su,_i_,_me,_n_,_ha,___,_si,_zu,_ka,_da,_tt,_ta,_dot,_dot,_dot,_eol
_sc11_msg17:
		.BYTE	_______,_ka__ne__da,_lt,_te_tsu__o_,_wo,___,_ka,_e_,_ta,_no,_mo,___,_o_,_ma,_e_,_no,_si,_wa,_za,_ret
		.BYTE	_______________________,_da,_na,_AA,_ex,_ret
		.BYTE	_O_,_RE,_ga,___,_si,_yy,_me,_n_,_wo,___,_ka,_ke,_o_,_ri,_yo,_u_,_to,_si,_ta,_to,_ki,___,_hu,_i_,_ni,_ret
		.BYTE	_ko,_e_,_ga,___,_ki,_ko,_e_,_te,_ki,_ta,_cr,_eol
_sc11_msg18:
		.BYTE	_______,_KI,_YO,_KO,_lt,_an0,_A_,_KI,_RA,_no,_ti,_ka,_ra,_ha,___,_da,_re,_no,_na,_ka,_ni,_mo,_ret
		.BYTE	_______________________,_so,_n_,_za,_i_,_su,_ru,_WA,_dot,_dot,_dot,_aof,_ret
		.BYTE	_______,_ka__ne__da,_lt,_MU,_TT,_ex,___,_da,_re,_da,_AA,_cr,_eol
_sc11_msg19:
		.BYTE	_______,_KI,_YO,_KO,_lt,_an0,_de,_mo,___,_so,_no,_ti,_ka,_ra,_ga,___,_me,_za,_me,_ta,_to,_ki,_dot,_dot,_dot,_ret
		.BYTE	_______________________,_ta,_to,_e_,___,_so,_no,_zi,_uu,_n_,_bi,_ga,___,_de,_ki,_te,_i_,_na,_ku,_te,_mo,_ret
		.BYTE	_______________________,_so,_no,_hi,_to,_ha,___,_tu,_ka,_i_,_ka,_ta,_wo,___,_se,_n_,_ta,_ku,_ret
		.BYTE	_______________________,_si,_na,_ku,_te,_ha,_na,_ra,_na,_i_,_no,_dot,_dot,_dot,___,_so,_si,_te,_col,_ret
		.BYTE	_______________________,_a_,_no,_hi,_to,_ha,___,_se,_n_,_ta,_ku,_si,_ta,_dot,_dot,_dot,_aof,_eol
_sc11_msg1A:
		.BYTE	_______,_KI,_YO,_KO,_lt,_an0,_te_tsu__o_,_ku,_n_,_ha,___,_wa,_ta,_si,_ta,_ti,_no,___,_i_,_ti,_ba,_n_,_ret
		.BYTE	_______________________,_a_,_ta,_ra,_si,_i_,_na,_ka,_ma,_dot,_dot,_dot,_aof,_eol
_sc11_msg1B:
		.BYTE	_______,_ka__ne__da,_lt,_zi,_yy,_a_,_ex,___,_na,_n_,_no,_ta,_me,_ni,___,_KE,_I_,_wo,_ret
		.BYTE	_______________________,_tu,_re,_te,_i_,_ku,_ex,_eol
_sc11_msg1C:
		.BYTE	_______,_ka__ne__da,_lt,_an0,_KE,_I_,_wo,___,_mo,_do,_se,$89,_ex,_ret
		.BYTE	_______________________,_te_tsu__o_,_ha,___,_O_,_RE,_ta,_ti,_no,_na,_ka,_ma,_da,_ex,_ret
		.BYTE	_______________________,_ya,_tu,_wo,___,_si,_ma,_tu,_su,_n_,_no,_ha,___,_O_,_RE,_ta,_ti,_da,_AA,_ex,_aof,_eol
_sc11_msg1D:
		.BYTE	_ku,_so,_OO,___,_te_tsu__o_,_no,_ya,_tu,_col,___,_do,_ko,_he,___,_i_,_ki,_ya,_ga,_tt,_ta,_AA,_ex,_ret
		.BYTE	_GA,_KI,_do,_mo,_yo,_ri,___,_ha,_ya,_ku,___,_mi,_tu,_ke,_na,_i_,_to,_dot,_dot,_dot,_eol
_sc11_msg1E:
		.BYTE	_ya,_ma,_ga,_ta,_no,___,_hu,_ku,_si,_uu,_u_,_se,_n_,_da,_ze,_cr,___,_ma,_tt,_te,_ro,_yo,_OO,_col,_ret
		.BYTE	_o_,_ma,_e_,_ga,___,_ki,_ni,_ka,_ke,_te,_i_,_ta,___,_O_,_RE,_no,_BA,_I_,_KU,_de,_dot,_dot,_dot,_eol
_sc11_msg1F:
		.BYTE	_ke,_do,_col,___,_ha,_ru,_ki,_ya,_no,_ro,_zi,_de,___,_de,_a_,_tt,_ta,_no,_ha,___,_ka,_i_,_da,_tt,_ta,_cr,_ret
		.BYTE	_ka,_i_,_ha,___,_na,_ni,_ka,_ni,___,_o_,_bi,_e_,_te,_i_,_ta,_dot,_dot,_dot,_eol
_sc11_msg20:
		.BYTE	_______,_ka__ne__da,_lt,_na,_ni,_II,_col,___,_ya,_ma,_ga,_ta,_ga,_AA,_str,_tt,_cr,_eol
_sc11_msg21:
		.BYTE	_______,_ka__ne__da,_lt,_O_,_RE,_no,_BA,_I_,_KU,_dot,_dot,_dot,_qe,_ret
		.BYTE	_______________________,_dot,_dot,_dot,_ka,_i_,_col,___,_ya,_ma,_ga,_ta,_no,_BA,_I_,_KU,_wo,_ret
		.BYTE	_______________________,_to,_tt,_te,_ki,_te,_ku,_re,_na,_i_,_ka,_cr,_eol
_sc11_msg22:
		.BYTE	___________,_ka,_i_,_lt,_an0,_do,_u_,_su,_ru,_n_,_da,_qe,_aof,_ret
		.BYTE	_______,_ka__ne__da,_lt,_ko,_i_,_tu,_wo,___,_to,_do,_ke,_te,_ya,_ru,_no,_sa,_dot,_dot,_dot,_eol
_sc11_msg23:
		.BYTE	_O_,_RE,_ga,___,_to,_bi,_o_,_ri,_te,_col,___,_mo,_do,_ri,_ka,_ke,_ta,_to,_ki,_da,_cr,_eol
_sc11_msg24:
		.BYTE	_te,_i_,_bo,_u_,_no,_si,_ta,_ka,_ra,___,_KE,_I_,_no,_sa,_ke,_bi,_go,_e_,_ga,_ret
		.BYTE	_ki,_ko,_e_,_ta,_cr,_eol
_sc11_msg25:
		.BYTE	_______,_ka__ne__da,_lt,_an0,_o_,_str,_i_,_col,___,_TI,_KU,_SI,$6A,_U_,_ex,_ex,_aof,_eol
_sc11_msg26:
		.BYTE	___________,_ka,_i_,_lt,_an0,_mi,_ta,_to,_ki,_ka,_ra,___,_he,_n_,_na,_ka,_n_,_zi,___,_da,_tt,_ta,_n_,_da,_cr,_ret
		.BYTE	_______________________,_bi,_oo,_u_,_i_,_n_,_no,_ha,_ku,_i_,_mi,_te,$89,_no,___,_ki,_te,_ru,_si,_yo,_OO,_cr,_ret
		.BYTE	_______________________,_ya,_ma,_ga,_ta,_mo,_col,___,_ho,_n_,_to,_u_,_ni,___,_o_,_ma,_e_,_ha,_ret
		.BYTE	_______________________,_te_tsu__o_,_ka,_tt,_te,___,_ki,_i_,_ta,_n_,_da,_cr,_aof,_eol
_sc11_msg27:
		.BYTE	___________,_ka,_i_,_lt,_so,_no,_a_,_to,___,_ya,_ma,_ga,_ta,_ga,_dot,_dot,_dot,_eol
_sc11_msg28:
		.BYTE	_______,_KI,_YO,_KO,_lt,_an0,_a_,_no,_hi,_to,_no,___,_si,_te,_i_,_ru,_ko,_to,_ha,___,_wa,_ta,_si,_ta,_ti,_no,_ret
		.BYTE	_______________________,_se,_ki,_ni,_n_,_de,_mo,___,_a_,_ru,_no,_dot,_dot,_dot,_aof,_eol
_sc11_msg95:
		.BYTE	___________,_ka,_i_,_lt,_ka__ne__da,_AA,_dot,_dot,_dot,_eol
_sc11_msg98:
		.BYTE	_O_,_RE,_ha,___,_te,_i_,_bo,_u_,_no,_mu,_ko,_u_,_ga,_wa,_wo,___,_no,_zo,_i_,_ta,_cr,_eol

		SECTION_END		F11
