
		SECTION_START	F4

		MSG_START	_scene4_msg_lib
		MSG_IDX	_sc4_msg00
		MSG_IDX	_sc4_msg01
		MSG_IDX	_sc4_msg02
		MSG_IDX	_sc4_msg03
		MSG_IDX	_sc4_msg04
		MSG_IDX	_sc4_msg05
		MSG_IDX	_sc4_msg06
		MSG_IDX	_sc4_msg07
		MSG_IDX	_sc4_msg08
_sc4_msg00:
		.BYTE	_ku,_so,_OO,___,_A_,_str,_MI,_str,_no,_ya,_tu,_ra,___,_GA,_TT,_KO,_ni,_ma,_de,___,_re,_n_,_ra,_ku,_ret
		.BYTE	_si,_ya,_ga,_tt,_te,_str,_cr,_ret
		.BYTE	_A_,_GO,_ya,_ro,_u_,_col,___,_na,_ni,_ga,___,_si,_do,_u_,_OO,_ex,_da,_yo,_cr,_eol
_sc4_msg01:
		.BYTE	_GU,_RU,_str,_PI,_str,_lt,_an1,_do,_u_,_si,_ta,_no,_OO,___,_so,_no,_HO,_TT,_PE,_str,_cr,_aof,_ret
		.BYTE	_______,_ka__ne__da,_lt,_u_,_ru,_se,$89,_n_,_da,_yo,_OO,_ex,_ret
		.BYTE	___________,_ka,_i_,_lt,_an0,_ta,_i_,_i_,_ku,_no,___,_A_,_GO,_ya,_ro,_u_,_str,_ex,_aof,_eol
_sc4_msg02:
		.BYTE	_GU,_RU,_str,_PI,_str,_lt,_an1,_ki,_uu,_u_,_si,_ga,_i_,_no,___,_ko,_u_,_so,_ku,_de,___,_KU,_RA,_U_,_N_,_no,_ret
		.BYTE	_______________________,_ya,_tu,_ra,_to,___,_ya,_tt,_ta,_n_,_da,_tt,_te,_str,_cr,_ret
		.BYTE	_______________________,_mo,_u_,___,_mi,_na,_go,_ro,_si,_ni,___,_si,_ti,_yy,_tt,_ta,_ra,_str,_cr,_ret
		.BYTE	_______________________,_a_,_i_,_tu,_ra,___,_ki,_ta,_na,_i_,_si,_str,_cr,_aof,_eol
_sc4_msg03:
		.BYTE	___,_ya,_ma,_ga,_ta,_lt,_an2,_so,_re,_ga,___,_yu,_u_,_be,_ha,_yo,_OO,_col,_DE,_MO,_da,_wa,_col,_ret
		.BYTE	_______________________,_PO,_RI,_da,_wa,_col,___,_A_,_str,_MI,_str,_da,_wa,_dot,_dot,_dot,___,_o_,_ma,_ke,_ni,_ret
		.BYTE	_______________________,_te_tsu__o_,_no,___,_BA,_KA,_ha,___,_zi,_ko,_tt,_ti,_ma,_u_,_si,_yo,_str,_tt,_cr,_aof,_ret
		.BYTE	_GU,_RU,_str,_PI,_str,_lt,_an1,_te_tsu__o_,_ku,_n_,_col,___,_do,_u_,_na,_tt,_ta,_no,_cr,_aof,_eol
_sc4_msg04:
		.BYTE	___________,_ka,_i_,_lt,_an0,_si,_ro,_BI,_RU,___,_o_,_ku,_ri,_da,_ro,_cr,_ret
		.BYTE	_______________________,_do,_tt,_ka,___,_si,_ra,_ne,_e_,_ke,_do,_dot,_dot,_dot,_aof,_ret
		.BYTE	_______,_ka__ne__da,_lt,_a_,_no,_ba,_ka,_dot,_dot,_dot,_eol
_sc4_msg05:
		.BYTE	___________,_ka,_i_,_lt,_an0,_a_,_tt,___,_te_tsu__o_,_da,_str,_ex,_ret
		.BYTE	_______________________,_ka,_col,___,_ka__ne__da,_col,___,_o_,_ma,_e_,_no,___,_BA,_I_,_KU,_ga,_dot,_dot,_dot,_aof,_eol
_sc4_msg06:
		.BYTE	_te_tsu__o_,_ha,___,_u_,_si,_ro,_ni,___,_o_,_n_,_na,_wo,_no,_se,_col,___,_O_,_RE,_no,___,_BA,_I_,_KU,_de,_ret
		.BYTE	_ha,_si,_ri,_sa,_tt,_te,_tt,_ta,_cr,_eol
_sc4_msg07:
		.BYTE	_______,_ka__ne__da,_lt,_a_,_n_,_no,___,_BA,_KA,_TT,_ex,___,_O_,_RE,_no,___,_BA,_I_,_KU,_ga,_ret
		.BYTE	_______________________,_no,_ri,_ko,_na,_se,_ru,_to,___,_o_,_mo,_tt,_te,_ru,_no,_ka,_dot,_dot,_dot,_ret
		.BYTE	___________,_ka,_i_,_lt,_i_,_ma,_ma,_de,___,_na,_ni,___,_si,_te,_ya,_ga,_tt,_ta,_n_,_da,_col,_ret
		.BYTE	_______________________,_a_,_i_,_tu,_cr,_eol
_sc4_msg08:
		.BYTE	_O_,_RE,_ha,___,_ya,_ma,_ga,_ta,_no,___,_BA,_I_,_KU,_ni,___,_ma,_ta,_ga,_tt,_ta,_cr,_ret
		.BYTE	_O_,_RE,_ta,_ti,_ha,___,_te_tsu__o_,_wo,___,_o_,_u_,_ko,_to,_ni,___,_si,_ta,_ze,_cr,_eol

		SECTION_END		F4
