
		SECTION_START	F13

		MSG_START	_scene13_msg_lib
		MSG_IDX	_sc13_msg00
		MSG_IDX	_sc13_msg01
		MSG_IDX	_sc13_msg02
		MSG_IDX	_sc13_msg03
		MSG_IDX	_sc13_msg04
		MSG_IDX	_sc13_msg05
		MSG_IDX	_sc13_msg06
		MSG_IDX	_sc13_msg07
		MSG_IDX	_sc13_msg08
		MSG_IDX	_sc13_msg09
		MSG_IDX	_sc13_msg0A
		MSG_IDX	_sc13_msg0B
		MSG_IDX	_sc13_msg0C
		MSG_IDX	_sc13_msg0D
		MSG_IDX	_sc13_msg0E
		MSG_IDX	_sc13_msg0F
		MSG_IDX	_sc13_msg10
		MSG_IDX	_sc13_msg11
		MSG_IDX	_sc13_msg12
		MSG_IDX	_sc13_msg13
		MSG_IDX	_sc13_msg14
		MSG_IDX	_sc13_msg15
		MSG_IDX	_sc13_msg16
		MSG_IDX	_sc13_msg17
		MSG_IDX	_sc13_msg18
		MSG_IDX	_sc13_msg19
		MSG_IDX	_sc13_msg1A
		MSG_IDX	_sc13_msg1B
		MSG_IDX	_sc13_msg1C
		MSG_IDX	_sc13_msg1D
		MSG_IDX	_sc13_msg1E
		MSG_IDX	_sc13_msg1F
		MSG_IDX	_sc13_msg20
		MSG_IDX	_sc13_msg21
		MSG_IDX	_sc13_msg22
		MSG_IDX	_sc13_msg23
		MSG_IDX	_sc13_msg24
		MSG_IDX	_sc13_msg25
		MSG_IDX	_sc13_msg26
		MSG_IDX	_sc13_msg27
		MSG_IDX	_sc13_msg28
		MSG_IDX	_sc13_msg29
		MSG_IDX	_sc13_msg2A
		MSG_IDX	_sc13_msg2B
		MSG_IDX	_sc13_msg2C
		MSG_IDX	_sc13_msg2D
		MSG_IDX	_sc13_msg2E
_sc13_msg00:
		.BYTE	_O_,_RE,_ha,___,_GA,_RE,_KI,_no,_ya,_ma,_wo,___,_no,_bo,_tt,_te,_i_,_tt,_ta,_cr,_ret
		.BYTE	_so,_si,_te,___,_te_tsu__o_,_wo,___,_mi,_tu,_ke,_ta,_cr,_ret
		.BYTE	_______,_te_tsu__o_,_lt,_an0,_HO,_U_,_dot,_dot,_dot,_aof,_eol
_sc13_msg01:
		.BYTE	_______,_ka__ne__da,_lt,_an0,_do,_u_,_si,_ta,_yo,___,_mo,_me,_go,_to,_ka,_cr,_aof,_ret
		.BYTE	_______,_te_tsu__o_,_lt,_an1,_a_,_a_,_dot,_dot,_dot,___,_de,_mo,_mo,_u_,___,_su,_n_,_da,_n_,_da,_cr,_ret
		.BYTE	_______________________,_mo,_u_,_su,_ko,_si,___,_ha,_ya,_ke,_ri,_yy,___,_mi,_re,_ta,_no,_ni,_na,_cr,_aof,_eol
_sc13_msg02:
		.BYTE	_______,_ka__ne__da,_lt,_an0,_O_,_RE,_ha,___,_ma,_ta,___,_si,_n_,_pa,_i_,_si,_ti,_ma,_tt,_ta,_ze,_dot,_dot,_dot,_ret
		.BYTE	_______________________,_BE,_SO,_ka,_i_,_te,___,_na,_i_,_te,_n_,_zi,_yy,_NE,$89,_ka,_to,_ret
		.BYTE	_______________________,_o_,_mo,_tt,_te,_yo,_OO,_cr,_aof,_eol
_sc13_msg03:
		.BYTE	_______,_te_tsu__o_,_lt,_an1,_ka__ne__da,_AA,_dot,_dot,_dot,___,_o_,_me,_e_,_ga,___,_me,_za,_wa,_ri,_ret
		.BYTE	_______________________,_da,_tt,_ta,_n_,_da,_yo,_OO,_cr,___,_GA,_KI,_no,_ko,_ro,_ka,_ra,___,_na,_ni,_wo,_ret
		.BYTE	_______________________,_su,_ru,_no,_mo,___,_o_,_ma,_e_,_ga,___,_sa,_si,_zu,_si,_ya,_ga,_ru,_cr,_ret
		.BYTE	_______________________,_i_,_tu,_mo,___,_ko,_do,_mo,_a_,_tu,_ka,_i_,_da,_cr,___,_do,_ko,_ni,_de,_mo,_ret
		.BYTE	_______________________,_de,_te,_ki,_te,___,_BO,_SU,_du,_ra,_si,_ya,_ga,_ru,_cr,_aof,_eol
_sc13_msg04:
		.BYTE	_______,_ka__ne__da,_lt,_an0,_o_,_ma,_e_,_mo,___,_BO,_SU,_ni,___,_na,_tt,_ta,_n_,_da,_ro,_OO,_cr,_ret
		.BYTE	_______________________,_ko,_no,_GA,_RE,_KI,_no,_ya,_ma,_de,_yo,_OO,_ex,_aof,_ret
		.BYTE	_______,_te_tsu__o_,_lt,_an1,_ka__ne__da,_AA,_ex,_aof,_eol
_sc13_msg05:
		.BYTE	_O_,_RE,_no,___,_u_,_tt,_ta,_RE,_str,_ZA,_str,_ha,___,_SA,_N_,_PU,_RU,_KE,_str,_SU,_ni,_ret
		.BYTE	_a_,_ta,_tt,_ta,_cr,_eol
_sc13_msg06:
		.BYTE	_O_,_RE,_ha,___,_ka,_wa,_so,_u_,_to,_si,_ta,___,_to,_ta,_n_,_ni,___,_GA,_RE,_KI,_ni,_ret
		.BYTE	_tu,_ma,_du,_i_,_te,_si,_ma,_tt,_ta,_cr,_eol
_sc13_msg07:
		.BYTE	_ka__ne__da,_ha,___,_te_tsu__o_,_ni,___,_to,_bi,_ka,_ka,_tt,_ta,_ga,___,_to,_ti,_uu,_u_,_de,_ret
		.BYTE	_si,_oo,_u_,_ge,_ki,_ha,_ni,___,_ya,_ra,_re,_te,_si,_ma,_tt,_ta,_dot,_dot,_dot,_eol
_sc13_msg08:
		.BYTE	_______,_te_tsu__o_,_lt,_an1,_ko,_ri,_yy,___,_i_,_i_,_ya,_dot,_dot,_dot,_ret
		.BYTE	_______________________,_ka__ne__da,_AA,_dot,_dot,_dot,___,_ku,_ya,_si,_i_,_tt,_te,_no,_ga,_ret
		.BYTE	_______________________,_do,_n_,_na,_ki,_mo,_ti,_ka,___,_wa,_ka,_tt,_ta,_ka,_yo,_dot,_dot,_dot,_aof,_eol
_sc13_msg09:
		.BYTE	_so,_si,_te,_col,___,_te_tsu__o_,_ga,___,_ta,_ti,_a_,_ga,_tt,_ta,_to,_ki,___,_mi,_gi,_u_,_de,_ha,_ret
		.BYTE	_BI,_str,_MU,_ni,___,_se,_tu,_da,_n_,_sa,_re,_te,_i_,_ta,_cr,_eol
_sc13_msg0A:
		.BYTE	_BA,_SI,_TT,_ex,_ex,_ret
		.BYTE	_te_tsu__o_,_ha,___,_su,_de,_ni,___,_BA,_RI,_YA,_str,_wo,___,_ha,_tt,_te,_i_,_ta,_cr,_eol
_sc13_msg0B:
		.BYTE	_te_tsu__o_,_ha,___,_ZI,_YY,_N_,_PU,_su,_ru,_to,_col,___,_so,_no,_ma,_ma,___,_so,_ra,_he,_ret
		.BYTE	_to,_n_,_de,_i_,_tt,_te,_si,_ma,_tt,_ta,_cr,_ret
		.BYTE	_te_tsu__o_,_ha,___,_S,_O,_L,_wo,___,_ha,_ka,_i_,_si,_ni,_col,___,_mu,_ka,_tt,_ta,_no,_da,_tt,_ta,_cr,_eol
_sc13_msg0C:
		.BYTE	_______,_ka__ne__da,_lt,_ya,_tt,_ta,_AA,_dot,_dot,_dot,_ret
		.BYTE	_ke,_do,___,_te_tsu__o_,_no,_ya,_tu,___,_BA,_RI,_YA,_str,_no,_a_,_i_,_da,_wo,___,_tu,_ki,_nu,_ke,_ta,_ret
		.BYTE	_ha,_zu,_na,_no,_ni,___,_PI,_N_,_PI,_N_,___,_si,_te,_ya,_ga,_tt,_ta,_dot,_dot,_dot,_eol
_sc13_msg0D:
		.BYTE	_O_,_RE,_ha,___,_RE,_str,_ZA,_str,_wo,___,_u_,_tt,_ta,_ga,___,_te_tsu__o_,_ma,_de,_ret
		.BYTE	_to,_do,_ka,_na,_ka,_tt,_ta,_dot,_dot,_dot,_eol
_sc13_msg0E:
		.BYTE	_______,_ka__ne__da,_lt,_a_,_re,_qe,___,_BA,_TT,_TE,_RI,_str,_ga,_qe,_ex,_ret
		.BYTE	_______,_te_tsu__o_,_lt,_do,_u_,_si,_ta,_AA,___,_ka__ne__da,_AA,_dot,_dot,_dot,_eol
_sc13_msg0F:
		.BYTE	_______,_ka__ne__da,_lt,_an0,_ti,_ku,_si,_oo,_u_,_ex,___,_ki,_ta,_ne,$89,_zo,___,_te_tsu__o_,_OO,_ex,_ret
		.BYTE	_______________________,_su,_de,_de,___,_si,_oo,_u_,_bu,_si,_ro,_OO,_ex,_aof,_eol
_sc13_msg10:
		.BYTE	_te_tsu__o_,_no,_ma,_wa,_ri,_ga,___,_ka,_ga,_ya,_ki,_ha,_zi,_me,_col,___,_si,_da,_i_,_ni,___,_tu,_yo,_ku,_ret
		.BYTE	_hi,_ka,_tt,_te,_i_,_tt,_ta,_cr,_ret
		.BYTE	_______,_ka__ne__da,_lt,_a_,_str,_tt,_qe,_eol
_sc13_msg11:
		.BYTE	_so,_re,_ha,_col,___,_ta,_i_,_sa,_no,_me,_i_,_re,_i_,_de,_col,___,_te_tsu__o_,_me,_ga,_ke,_te,_ret
		.BYTE	_ha,_tt,_si,_yy,_sa,_re,_ta,___,_S,_O,_L,_no,_BI,_str,_MU,_da,_tt,_ta,_cr,_eol
_sc13_msg12:
		.BYTE	_O_,_RE,_ha,___,_a_,_wa,_te,_te,_col,___,_ni,_ge,_da,_si,_ta,_cr,_ret
		.BYTE	_ma,_wa,_ri,_no,_GA,_RE,_KI,_ga,___,_hu,_tt,_to,_n_,_de,_ta,_cr,_eol
_sc13_msg13:
		.BYTE	_te_tsu__o_,_ha,___,_GA,_RE,_KI,_no,_ya,_ma,_go,_to,___,_hu,_ki,_a_,_ge,_ra,_re,_ta,_cr,_eol
_sc13_msg14:
		.BYTE	_______,_ka__ne__da,_lt,_u_,_o_,_str,_tt,___,_TE,$89,_str,_TU,_str,_O_,_str,_TT,_cr,_ret
		.BYTE	_O_,_RE,_ha,___,_i_,_wa,_wo,___,_mo,_ti,_a_,_ge,_te,___,_te_tsu__o_,_ni,_ret
		.BYTE	_na,_ge,_tu,_ke,_yo,_u_,_to,_si,_ta,_cr,_ret
		.BYTE	_______,_ka__ne__da,_lt,_a_,_tt,_ex,_eol
_sc13_msg15:
		.BYTE	_ma,_ta,___,_hi,_ka,_ri,_ga,___,_a_,_tu,_ma,_tt,_te,_ki,_te,_i_,_ta,_cr,_ret
		.BYTE	_me,_no,_ma,_e_,_ga,___,_i_,_tt,_si,_uu,_n_,___,_ma,_tt,_si,_ro,_ni,_na,_tt,_ta,_cr,_eol
_sc13_msg16:
		.BYTE	_me,_wo,_a_,_ke,_ta,_to,_ki,___,_ku,_u_,_ti,_uu,_u_,_wo,___,_GA,_RE,_KI,_ga,_ret
		.BYTE	_ta,_da,_yo,_tt,_te,_i_,_ta,_cr,_ret
		.BYTE	_te_tsu__o_,_ga,___,_BA,_RI,_YA,_str,_wo,_ha,_tt,_te,_col,___,_BI,_str,_MU,_wo,___,_hu,_se,_i_,_de,_i_,_ta,_cr,_eol
_sc13_msg17:
		.BYTE	_______,_te_tsu__o_,_lt,_ku,_so,_u_,_dot,_dot,_dot,_ret
		.BYTE	_______,_ka__ne__da,_lt,_na,_n_,_da,_AA,_cr,_eol
_sc13_msg18:
		.BYTE	_______,_ka__ne__da,_lt,_u_,_wa,_AA,_cr,_ret
		.BYTE	_BA,_RI,_YA,_str,_ga,___,_to,_me,_te,_i_,_ta,___,_GA,_RE,_KI,_ga,___,_hu,_tt,_te,_ki,_ta,_cr,_eol
_sc13_msg19:
		.BYTE	_DO,_TT,_DO,_str,_N_,_ex,___,_DO,_TT,_KA,_str,_N_,_ex,_ret
		.BYTE	_si,_ka,_si,___,_i_,_tu,_no,_ma,_ni,_ka,___,_GA,_RE,_KI,_ga,___,_BI,_str,_MU,_ni,_ret
		.BYTE	_ka,_wa,_tt,_te,_i_,_ta,_cr,_eol
_sc13_msg1A:
		.BYTE	_mo,_u_,_so,_ko,_ma,_de,___,_BI,_str,_MU,_ha,___,_se,_ma,_tt,_te,_ki,_te,_i_,_ta,_cr,_ret
		.BYTE	_______,_ka__ne__da,_lt,_ta,_su,_ke,_te,$89,___,_KE,_I_,_ti,_yy,_str,_n_,_ex,_eol
_sc13_msg1B:
		.BYTE	_ba,_ku,_ha,_tu,_o_,_n_,_no,_na,_ka,_ka,_ra,___,_ka,_i_,_no,___,_sa,_ke,_bi,_go,_e_,_ga,_ret
		.BYTE	_ki,_ko,_e_,_te,_ki,_ta,_cr,_eol
_sc13_msg1C:
		.BYTE	_KE,_I_,_wo,_no,_se,_ta,___,_ka,_i_,_no,_BA,_I_,_KU,_ga,___,_O_,_RE,_no,_ma,_e_,_ni,_ret
		.BYTE	_ya,_tt,_te,_ki,_ta,_cr,_eol
_sc13_msg1D:
		.BYTE	_______,_ka__ne__da,_lt,_ka,_i_,_ex,___,_KE,_I_,_ex,_eol
_sc13_msg1E:
		.BYTE	_______,_ka__ne__da,_lt,_no,_re,_tt,_te,_dot,_dot,_dot,___,_do,_ko,_ni,_II,_cr,_ret
		.BYTE	___________,_KE,_I_,_lt,_a_,_str,_tt,___,_ha,_ya,_ku,$88,_cr,_ret
		.BYTE	_______,_ka__ne__da,_lt,_e_,_e_,_i_,___,_mo,_OO,_cr,_eol
_sc13_msg1F:
		.BYTE	_______,_ka__ne__da,_lt,_an0,_sa,_n_,_wo,___,_tu,_ke,_ro,_yo,_col,___,_DE,_KO,_su,_ke,_ya,_ro,_u_,_OO,_ex,_aof,_ret
		.BYTE	_______,_te_tsu__o_,_lt,_an1,_si,_II,_ne,$89,$89,_dot,_dot,_dot,_dot,_dot,_dot,_aof,_eol
_sc13_msg20:
		.BYTE	_O_,_RE,_ha,___,_GA,_RE,_KI,_no,_a_,_i_,_da,_ni,___,_hu,_se,_ta,_cr,_eol
_sc13_msg21:
		.BYTE	_DO,_TT,_KA,_str,_N_,_ex,_ex,_ret
		.BYTE	_ka__ne__da,_wo,___,_BI,_str,_MU,_ga,___,_ti,_oo,_ku,_ge,_ki,_si,_ta,_cr,_eol
_sc13_msg22:
		.BYTE	_______,_ka__ne__da,_lt,_do,_ko,_ma,_de,___,_ki,_te,_ru,_ka,_na,_a_,_tt,_to,_cr,_ret
		.BYTE	_O_,_RE,_ha,___,_BI,_str,_MU,_wo,___,_ta,_si,_ka,_me,_ru,_ta,_me,_ni,___,_hu,_ri,_mu,_i_,_ta,_cr,_eol
_sc13_msg23:
		.BYTE	_______,_ka__ne__da,_lt,_u_,_wa,_a_,_str,_cr,_ret
		.BYTE	_O_,_RE,_ha,___,_BI,_str,_MU,_ni,_mu,_ka,_tt,_te,___,_o_,_mo,_i_,_tt,_ki,_ri,___,_sa,_ke,_n_,_da,_cr,_eol
_sc13_msg24:
		.BYTE	_to,_tu,_ze,_n_,_col,_ret
		.BYTE	_SA,_N_,_PU,_RU,_KE,_str,_SU,_ga,___,_hi,_ka,_ri,_wo,___,_ha,_na,_ti,_ha,_zi,_me,_ta,_cr,_eol
_sc13_msg25:
		.BYTE	_______,_ka__ne__da,_lt,_KE,_I_,_ti,_yy,_str,_n_,_col,___,_o_,_ti,_yy,_ni,___,_i_,_ka,_na,_str,_i_,_qe,_eol
_sc13_msg26:
		.BYTE	_ka,_i_,_to,_KE,_I_,_ha,___,_O_,_RE,_ni,___,_ki,_du,_i_,_ta,_cr,_ret
		.BYTE	___________,_KE,_I_,_lt,_ka__ne__da,_ku,_str,_n_,_cr,_ret
		.BYTE	___________,_ka,_i_,_lt,_no,_re,$89,_ex,_ret
		.BYTE	_ret,_eol
_sc13_msg27:
		.BYTE	_______,_ka__ne__da,_lt,_u_,_wa,_AA,_str,_cr,_ret
		.BYTE	_O_,_RE,_ha,___,_GA,_RE,_KI,_no,_a_,_i_,_da,_wo,___,_ha,_si,_ri,_nu,_ke,_ta,_cr,_eol
_sc13_msg28:
		.BYTE	_______,_te_tsu__o_,_lt,_n_,_qe,___,_na,_n_,_da,_AA,___,_ko,_no,_hi,_ka,_ri,_ha,_qe,_eol
_sc13_msg29:
		.BYTE	_BI,_str,_MU,_ha,___,_me,_ti,_yy,_ku,_ti,_yy,_ni,___,_GA,_RE,_KI,_no,_ya,_ma,_wo,_ret
		.BYTE	_ti,_oo,_ku,_ge,_ki,_si,_te,_i_,_ta,_cr,_eol
_sc13_msg2A:
		.BYTE	_yu,_u_,_ya,_ke,_no,_so,_ra,_ni,___,_na,_ga,_re,_bo,_si,_ga,___,_ki,_ra,_me,_i_,_te,_i_,_ta,_cr,_ret
		.BYTE	_______,_A_,_str,_MI,_str,_lt,_S,_O,_L,_da,_so,_u_,_de,_su,_dot,_dot,_dot,_eol
_sc13_msg2B:
		.BYTE	_______,_ta,_i_,_sa,_lt,_an0,_a_,_no,_te_tsu__o_,_ga,___,_S,_O,_L,_wo,_dot,_dot,_dot,_ret
		.BYTE	_______________________,_ko,_ko,_ma,_de,___,_PA,_WA,_str,_wo,___,_mi,_ni,_tu,_ke,_ta,_to,_ret
		.BYTE	_______________________,_i_,_u_,_no,_ka,_AA,_aof,_eol
_sc13_msg2C:
		.BYTE	_SI,_UU,_U_,_U_,_U_,_dot,_dot,_dot,_ret
		.BYTE	_BI,_str,_MU,_ha,___,_O_,_RE,_ta,_ti,_wo,___,_ka,_su,_me,_col,___,_ki,_e_,_te,_i_,_tt,_ta,_dot,_dot,_dot,_eol
_sc13_msg2D:
		.BYTE	_______,_TA,_KA,_SI,_lt,_te_tsu__o_,_ku,_n_,_no,_ti,_ka,_ra,_ga,___,_PI,_str,_KU,_ni,_ret
		.BYTE	_______________________,_ta,_tt,_si,_ta,_to,_ki,_dot,_dot,_dot,_ret
		.BYTE	_______,_MA,_SA,_RU,_lt,_so,_no,_to,_ki,_da,_ne,_dot,_dot,_dot,___,_de,_mo,_ret
		.BYTE	_______________________,_u_,_ma,_ku,_i_,_ku,_ka,_na,_AA,_dot,_dot,_dot,_eol
_sc13_msg2E:
		.BYTE	_______,_KI,_YO,_KO,_lt,_an0,_mi,_ra,_i_,_ha,___,_i_,_ti,_ho,_u_,_ko,_u_,_da,_ke,_ni,_ret
		.BYTE	_______________________,_su,_su,_n_,_de,_i_,_ru,___,_wa,_ke,_zi,_yy,_a_,_na,_i_,_wa,_dot,_dot,_dot,_ret
		.BYTE	_______________________,_wa,_ta,_si,_ta,_ti,_ni,_mo,___,_e_,_ra,_be,_ru,___,_mi,_ra,_i_,_ga,_ret
		.BYTE	_______________________,_a_,_ru,_ha,_zu,_yo,_cr,_aof,_eol

		SECTION_END		F13
