
		SECTION_START	F10

		MSG_START	_scene10_msg_lib
		MSG_IDX	_sc10_msg00
		MSG_IDX	_sc10_msg01
		MSG_IDX	_sc10_msg02
		MSG_IDX	_sc10_msg03
		MSG_IDX	_sc10_msg04
		MSG_IDX	_sc10_msg05
		MSG_IDX	_sc10_msg06
		MSG_IDX	_sc10_msg07
		MSG_IDX	_sc10_msg08
		MSG_IDX	_sc10_msg09
		MSG_IDX	_sc10_msg0A
		MSG_IDX	_sc10_msg0B
		MSG_IDX	_sc10_msg0C
		MSG_IDX	_sc10_msg0D
		MSG_IDX	_sc10_msg0E
		MSG_IDX	_sc10_msg0F
		MSG_IDX	_sc10_msg10
		MSG_IDX	_sc10_msg11
		MSG_IDX	_sc10_msg12
		MSG_IDX	_sc10_msg13
		MSG_IDX	_sc10_msg14
		MSG_IDX	_sc10_msg15
		MSG_IDX	_sc10_msg16
		MSG_IDX	_sc10_msg17
		MSG_IDX	_sc10_msg18
		MSG_IDX	_sc10_msg19
		MSG_IDX	_sc10_msg1A
		MSG_IDX	_sc10_msg1B
_sc10_msg00:
		.BYTE	_______,_ka__ne__da,_lt,_n_,_qe,_ret
		.BYTE	_______________________,_do,_u_,_ya,_ra,___,_RA,_BO,_no,___,_ka,_n_,_ki,_n_,_si,_tu,_no,_yo,_u_,_da,_cr,_ret
		.BYTE	_______________________,_KE,_I_,_ha,___,_do,_ko,_da,_qe,_eol
_sc10_msg01:
		.BYTE	___________,_KE,_I_,_lt,_an0,_ki,_ga,_tu,_i_,_ta,_no,_ne,_cr,___,_ki,_bu,_n_,_ha,_qe,_aof,_ret
		.BYTE	_______,_ka__ne__da,_lt,_sa,_i_,_te,_i_,_da,_ze,_cr,_eol
_sc10_msg02:
		.BYTE	___________,_KE,_I_,_lt,_an0,_ke,_tt,_ki,_oo,_ku,___,_A_,_N_,_TA,_ha,_ret
		.BYTE	_______________________,_a_,_si,_de,_ma,_to,_i_,_ni,___,_na,_tt,_ta,_da,_ke,_zi,_yy,_na,_i_,_ex,_aof,_eol
_sc10_msg03:
		.BYTE	___________,_KE,_I_,_lt,_an0,_ha,_zu,_re,_so,_u_,_mo,___,_na,_i_,_wa,_cr,_aof,_eol
_sc10_msg04:
		.BYTE	_______,_ka__ne__da,_lt,_ku,_so,_tt,___,_ko,_n_,_na,_to,_ko,_ni,___,_to,_zi,_ko,_me,_ya,_ga,_tt,_te,_ex,_eol
_sc10_msg05:
		.BYTE	_______,_ka__ne__da,_lt,_A_,_str,_MI,_str,_mo,___,_A_,_KI,_RA,_tt,_te,_ya,_tu,_wo,_ret
		.BYTE	_______________________,_sa,_ga,_si,_te,_te,_dot,_dot,_dot,_ret
		.BYTE	___________,_KE,_I_,_lt,_an0,_A_,_str,_MI,_str,_ha,___,_A_,_KI,_RA,_wo,___,_o_,_so,_re,_te,_ru,_wa,_cr,_ret
		.BYTE	_______________________,_ti,_ka,_ra,_wo,___,_hu,_u_,_zi,_ko,_me,_yo,_u_,_to,___,_si,_te,_ru,_mi,_ta,_i_,_yo,_cr,_aof,_eol
_sc10_msg06:
		.BYTE	_______,_ka__ne__da,_lt,_A_,_KI,_RA,_no,_to,_ko,_he,___,_i_,_tt,_ta,_AA,_dot,_dot,_dot,_qe,_ret
		.BYTE	___________,_KE,_I_,_lt,_an0,_so,_u_,___,_i_,_tt,_te,_ta,_wa,_col,_a_,_no,_ko,_ga,_dot,_dot,_dot,_aof,_eol
_sc10_msg07:
		.BYTE	___________,_KE,_I_,_lt,_an0,_wa,_ta,_si,_ta,_ti,_ha,___,_ne,_du,_sa,_ma,_ga,___,_se,_i_,_hu,_wo,_ret
		.BYTE	_______________________,_ta,_o_,_su,_ta,_me,_no,___,_ki,_ri,_hu,_da,_to,_si,_te,_ret
		.BYTE	_______________________,_A_,_KI,_RA,_wo,___,_o_,_tt,_te,_i_,_ru,_no,_yo,_dot,_dot,_dot,_aof,_eol
_sc10_msg08:
		.BYTE	___________,_KE,_I_,_lt,_an0,_RI,_UU,_U_,_ga,___,_i_,_tt,_te,_ta,_wa,_col,_ret
		.BYTE	_______________________,_A_,_KI,_RA,_tt,_te,___,_ze,_tt,_ta,_i_,_no,_E_,_NE,_RU,_GI,_str,_ret
		.BYTE	_______________________,_na,_n_,_da,_tt,_te,_dot,_dot,_dot,_ret
		.BYTE	_______________________,_ni,_n_,_ge,_n_,_tt,_te,_sa,_AA,_col,_i_,_tt,_si,_oo,_u_,_no,_a_,_i_,_da,_ni,_ret
		.BYTE	_______________________,_i_,_ro,_n_,_na,_ko,_to,_wo,___,_su,_ru,_de,_si,_oo,_u_,_cr,_aof,_eol
_sc10_msg09:
		.BYTE	___________,_KE,_I_,_lt,_an0,_ha,_tt,_ke,_n_,_si,_ta,_ri,_col,_tu,_ku,_tt,_ta,_ri,_col,_ret
		.BYTE	_______________________,_so,_n_,_na,_ti,_si,_ki,_to,_ka,___,_E_,_NE,_RU,_GI,_str,_tt,_te,_col,_ret
		.BYTE	_______________________,_do,_ko,_ka,_ra,___,_ku,_ru,_no,_ka,_si,_ra,_qe,_ret
		.BYTE	_______________________,_sa,_ru,_mi,_ta,_i_,_na,_mo,_no,___,_da,_tt,_ta,_de,_si,_oo,_u_,_col,_ret
		.BYTE	_______________________,_ni,_n_,_ge,_n_,_tt,_te,_cr,_aof,_eol
_sc10_msg0A:
		.BYTE	___________,_KE,_I_,_lt,_an0,_so,_no,_ma,_e_,_ha,___,_ha,_ti,_uu,_u_,_ru,_i_,_ya,___,_sa,_ka,_na,_col,_ret
		.BYTE	_______________________,_so,_no,___,_mo,_tt,_to,_ma,_e_,_ha,___,_PU,_RA,_N_,_KU,_TO,_N_,_ya,_ret
		.BYTE	_______________________,_A_,_ME,_str,_BA,_to,_ka,_dot,_dot,_dot,___,_so,_n_,_na,_se,_i_,_bu,_tu,_no,_ret
		.BYTE	_______________________,_na,_ka,_ni,_mo,___,_su,_go,_i_,_E_,_NE,_RU,_GI,_str,_ga,___,_a_,_ru,_tt,_te,_ret
		.BYTE	_______________________,_ko,_to,_de,_si,_oo,_u_,_qe,_ex,_aof,_eol
_sc10_msg0B:
		.BYTE	_______,_ka__ne__da,_lt,_so,_ri,_yy,_a_,___,_i_,_de,_n_,_si,_no,_se,_i_,_da,_na,_dot,_dot,_dot,_eol
_sc10_msg0C:
		.BYTE	___________,_KE,_I_,_lt,_an0,_mo,_si,_a_,_ru,_to,_si,_ta,_ra,_col,___,_do,_n_,_na,_ki,_o_,_ku,_wo,_ret
		.BYTE	_______________________,_hi,_me,_te,_i_,_ru,_no,_ka,_si,_ra,_cr,___,_u_,_ti,_uu,_u_,_no,_ret
		.BYTE	_______________________,_ha,_zi,_ma,_ri,_no,_col,___,_so,_no,_mo,_tt,_to,_ma,_e_,_no,_dot,_dot,_dot,_ret
		.BYTE	_______________________,_da,_re,_de,_mo,___,_so,_n_,_na,_ki,_o_,_ku,_wo,___,_mo,_tt,_te,_i_,_ru,_no,_ret
		.BYTE	_______________________,_ka,_mo,_si,_re,_na,_i_,_wa,_ne,_dot,_dot,_dot,_aof,_eol
_sc10_msg0D:
		.BYTE	___________,_KE,_I_,_lt,_an0,_mo,_si,___,_na,_ni,_ka,_no,_ma,_ti,_ga,_i_,_de,___,_zi,_uu,_n_,_ba,_n_,_ga,_ret
		.BYTE	_______________________,_ku,_ru,_tt,_te,_col,___,_so,_n_,_na,_A_,_ME,_str,_BA,_mi,_ta,_i_,_na,_ret
		.BYTE	_______________________,_mo,_no,_ga,___,_ni,_n_,_ge,_n_,_mi,_ta,_i_,_na,___,_ti,_ka,_ra,_wo,_ret
		.BYTE	_______________________,_mo,_tu,_ko,_to,_ni,___,_na,_tt,_ta,_ra,_dot,_dot,_dot,_aof,_eol
_sc10_msg0E:
		.BYTE	___________,_KE,_I_,_lt,_an0,_A_,_ME,_str,_BA,_ha,___,_i_,_e_,_ya,_ha,_si,_wo,___,_tu,_ku,_tt,_te,_ha,_ret
		.BYTE	_______________________,_ku,_re,_na,_i_,_wa,_dot,_dot,_dot,___,_zi,_bu,_n_,_no,_ma,_wa,_ri,_no,_ret
		.BYTE	_______________________,_E_,_SA,_wo,___,_ku,_i_,_tu,_ku,_su,_da,_ke,_dot,_dot,_dot,_aof,_eol
_sc10_msg0F:
		.BYTE	_BE,_BI,_str,_RU,_str,_MU,_wo,___,_ha,_ka,_i_,_si,_ta,_no,_ha,___,_su,_be,_te,_ret
		.BYTE	_te_tsu__o_,_no,_ti,_ka,_ra,_na,_no,_ka,_qe,_ex,_eol
_sc10_msg10:
		.BYTE	_te_tsu__o_,_yo,_ri,_sa,_ki,_ni,___,_A_,_KI,_RA,_tt,_te,_ya,_tu,_wo,_ret
		.BYTE	_mi,_tu,_ke,_na,_i_,_to,___,_ya,_ba,_i_,_ze,_ex,_ex,_eol
_sc10_msg11:
		.BYTE	___________,_KE,_I_,_lt,_an0,_mu,_ka,_si,___,_so,_no,_ti,_ka,_ra,_wo,___,_KO,_N_,_TO,_RO,_str,_RU,_ret
		.BYTE	_______________________,_si,_yo,_u_,_to,_si,_ta,___,_hi,_to,_ta,_ti,_ga,___,_i_,_ta,_no,_dot,_dot,_dot,_ret
		.BYTE	_______________________,_se,_i_,_hu,_no,_yo,_u_,_se,_i_,_wo,___,_u_,_ke,_te,_ne,_dot,_dot,_dot,_aof,_eol
_sc10_msg12:
		.BYTE	_______,_KE,_I_,_lt,_an0,_so,_re,_ga,___,_si,_tt,_pa,_i_,_si,_te,_col,___,_a_,_no,___,_to,_u_,_ki,_oo,_u_,_ret
		.BYTE	___________________,_ha,_ka,_i_,_ga,___,_o_,_ko,_tt,_ta,_no,_dot,_dot,_dot,_aof,_eol
_sc10_msg13:
		.BYTE	_______,_ka__ne__da,_lt,_a_,_tt,___,_to,_bi,_ra,_ga,_ex,_eol
_sc10_msg14:
		.BYTE	_O_,_RE,_to,_KE,_I_,_ha,___,_RA,_BO,_ka,_ra,___,_da,_tt,_si,_uu,_tu,_si,_ta,_cr,_eol
_sc10_msg15:
		.BYTE	___________,_KE,_I_,_lt,_an0,_na,_ni,___,_ya,_tt,_te,_ru,_no,_yo,_ex,_aof,_eol
_sc10_msg16:
		.BYTE	_do,_u_,_ya,_tt,_te,___,_DO,_A_,_wo,___,_a_,_ke,_re,_ba,_i_,_i_,_n_,_da,_qe,_eol
_sc10_msg17:
		.BYTE	___________,_KE,_I_,_lt,_an0,_so,_no,_mo,_tt,_to,_ma,_e_,_no,_col,___,_mi,_zu,_ya,___,_ku,_u_,_ki,_ni,_mo,_ret
		.BYTE	_______________________,_i_,_de,_n_,_si,_ha,___,_a_,_ru,_no,_ka,_si,_ra,_dot,_dot,_dot,_ret
		.BYTE	_______________________,_u_,_ti,_uu,_u_,_no,_TI,_RI,_da,_tt,_te,___,_so,_u_,_de,_si,_oo,_u_,_cr,_aof,_eol
_sc10_msg18:
		.BYTE	_______,_ka__ne__da,_lt,_so,_re,_ga,___,_A_,_KI,_RA,_tt,_te,_wa,_ke,_ka,_qe,_eol
_sc10_msg19:
		.BYTE	_______,_ka__ne__da,_lt,_te_tsu__o_,_no,_ko,_to,_ka,_qe,___,_so,_n_,_na,_E_,_NE,_RU,_GI,_str,_wo,_ret
		.BYTE	_______________________,_mo,_tt,_ta,_tt,_te,_no,_ka,_qe,_ex,_eol
_sc10_msg1A:
		.BYTE	_KE,_I_,_ga,___,_hu,_i_,_ni,___,_he,_n_,_na,_ko,_e_,_de,___,_ha,_na,_si,_ha,_zi,_me,_ta,_cr,_eol
_sc10_msg1B:
		.BYTE	___________,_KE,_I_,_lt,_an0,_a_,_no,_ti,_ka,_ra,_ha,___,_wa,_ta,_si,_ta,_ti,_ni,_ha,___,_ma,_da,_dot,_dot,_dot,_aof,_eol

		SECTION_END		F10
