
		SECTION_START	F7

		MSG_START	_scene7_msg_lib
		MSG_IDX	_sc7_msg04
		MSG_IDX	_sc7_msg05
		MSG_IDX	_sc7_msg06
		MSG_IDX	_sc7_msg07
		MSG_IDX	_sc7_msg08
		MSG_IDX	_sc7_msg09
		MSG_IDX	_sc7_msg0A
		MSG_IDX	_sc7_msg0B
		MSG_IDX	_sc7_msg0C
		MSG_IDX	_sc7_msg0D
		MSG_IDX	_sc7_msg0E
		MSG_IDX	_sc7_msg0F
		MSG_IDX	_sc7_msg10
		MSG_IDX	_sc7_msg11
		MSG_IDX	_sc7_msg12
		MSG_IDX	_sc7_msg13
		MSG_IDX	_sc7_msg14
		MSG_IDX	_sc7_msg15
		MSG_IDX	_sc7_msg16
		MSG_IDX	_sc7_msg17
		MSG_IDX	_sc7_msg18
		MSG_IDX	_sc7_msg19
		MSG_IDX	_sc7_msg1A
		MSG_IDX	_sc7_msg1B
		MSG_IDX	_sc7_msg1C
		MSG_IDX	_sc7_msg1D
		MSG_IDX	_sc7_msg1E
		MSG_IDX	_sc7_msg1F
		MSG_IDX	_sc7_msg20
		MSG_IDX	_sc7_msg21
		MSG_IDX	_sc7_msg22
		MSG_IDX	_sc7_msg23
		MSG_IDX	_sc7_msg24
		MSG_IDX	_sc7_msg25
		MSG_IDX	_sc7_msg26
		MSG_IDX	_sc7_msg27
		MSG_IDX	_sc7_msg28
		MSG_IDX	_sc7_msg29
		MSG_IDX	_sc7_msg2A
		MSG_IDX	_sc7_msgBB					; scene 7 msg
		MSG_IDX	_sc7_msgBC					; scene 7 msg
		MSG_IDX	_sc7_msgBD					; scene 7 msg
		MSG_IDX	_sc7_msgBE					; scene 7 msg
_sc7_msg04:
		.BYTE	___,_ya,_ma,_ga,_ta,_lt,_an2,_te_tsu__o_,_no,_ya,_tu,___,_zi,_ko,_tt,_ta,_to,_ki,_ni,___,_a_,_ta,_ma,_ret
		.BYTE	_______________________,_u_,_tt,_te,_col,___,_PA,_str,_ni,___,_na,_tt,_ta,_n_,_zi,_yy,_ne,_e_,_no,_cr,_aof,_eol
_sc7_msg05:
		.BYTE	___,_ya,_ma,_ga,_ta,_lt,_an2,_A_,_str,_MI,_str,_no,_ya,_tu,_ra,_col,___,_na,_ni,_ka,___,_ka,_ku,_si,_te,_ret
		.BYTE	_______________________,_ya,_ga,_ru,_ze,_cr,_aof,_eol
_sc7_msg06:
		.BYTE	___,_ya,_ma,_ga,_ta,_lt,_an2,_a_,_no,_GA,_KI,_col,___,_A_,_str,_MI,_str,_to,___,_ka,_n_,_ke,_i_,_a_,_ru,_ni,_ret
		.BYTE	_______________________,_ti,_ga,_i_,_na,_i_,_ze,_cr,_aof,_eol
_sc7_msg07:
		.BYTE	___,_ya,_ma,_ga,_ta,_lt,_an2,_dot,_dot,_dot,_te_tsu__o_,_mo,___,_A_,_str,_MI,_str,_no,_ya,_tu,_ra,_ni,_ret
		.BYTE	_______________________,_a_,_no,_GA,_KI,_mi,_ta,_i_,_ni,___,_sa,_re,_ti,_ma,_u_,_ka,_mo,_na,_cr,_aof,_eol
_sc7_msg08:
		.BYTE	___,_ya,_ma,_ga,_ta,_lt,_an2,_so,_n_,_na,_ya,_tu,_col,_GA,_TT,_KO,_ni,___,_i_,_ta,_tt,_ke,_qe,_aof,_eol
_sc7_msg09:
		.BYTE	___________,_ka,_i_,_lt,_an1,_A_,_str,_MI,_str,_no,___,_hi,_mi,_tu,_ka,_na,_n_,_ka,___,_mi,_ta,_no,_ka,_mo,_ret
		.BYTE	_______________________,_si,_re,_na,_i_,_ze,_cr,_aof,_eol
_sc7_msg0A:
		.BYTE	___________,_ka,_i_,_lt,_an1,_ya,_tu,_ra,___,_te_tsu__o_,_no,_ko,_to,_wo,___,_ZI,_TT,_KE,_N_,_TA,_I_,_tt,_te,_ret
		.BYTE	_______________________,_i_,_tt,_te,_na,_ka,_tt,_ta,_tt,_ke,_qe,_aof,_eol
_sc7_msg0B:
		.BYTE	___________,_ka,_i_,_lt,_an1,_mo,_si,_ka,_si,_ta,_ra,___,_te_tsu__o_,_ha,___,_A_,_str,_MI,_str,_ni,_ret
		.BYTE	_______________________,_na,_ni,_ka,_no,___,_zi,_tt,_ke,_n_,_za,_i_,_ri,_oo,_u_,_ni,_ret
		.BYTE	_______________________,_sa,_re,_ti,_ma,_tt,_ta,_no,_ka,_mo,___,_si,_re,_na,_i_,_ze,_cr,_aof,_eol
_sc7_msg0C:
		.BYTE	___________,_ka,_i_,_lt,_an1,_yo,_ku,___,_wa,_ka,_n_,_ne,_str,_na,_cr,_aof,_eol
_sc7_msg0D:
		.BYTE	___________,_ka,_i_,_lt,_an1,_sa,_a_,_qe,___,_da,_re,___,_na,_n_,_da,_ro,_str,_na,_cr,_aof,_eol
_sc7_msg0E:
		.BYTE	_GU,_RU,_str,_PI,_str,_lt,_an0,_wa,_ka,_n_,_na,_str,_i_,_cr,_aof,_eol
_sc7_msg0F:
		.BYTE	_GU,_RU,_str,_PI,_str,_lt,_an0,_so,_n_,_na,_ko,_to,_yo,_ri,_col,___,_ne,$89,___,_ka,_e_,_ro,_str,_yo,_str,_cr,_ret
		.BYTE	_______________________,_a_,_tt,_col,___,_de,_mo,___,_BA,_I_,_KU,_ga,___,_na,_i_,_n_,_zi,_yy,_ret
		.BYTE	_______________________,_o_,_ka,_ni,___,_a_,_ga,_tt,_ta,___,_NA,_N_,_PA,_yo,_ne,$89,_cr,_aof,_eol
_sc7_msg10:
		.BYTE	___________,_ka,_i_,_lt,_an1,_so,_ri,_yy,___,_KA,_TT,_PA,_cr,_aof,_eol
_sc7_msg11:
		.BYTE	_GU,_RU,_str,_PI,_str,_ta,_ti,_ga,___,_ka,_e_,_ri,_ka,_ke,_ta,_to,_ki,_col,___,_to,_tu,_ze,_n_,_col,_ret
		.BYTE	_o_,_ku,_zi,_oo,_u_,_te,_i_,_e_,_n_,_ka,_ra,___,_tu,_du,_ku,___,_PU,_RO,_MU,_NA,_str,_DO,_de,_ret
		.BYTE	_ba,_ku,_ha,_tu,_ga,_o_,_ko,_tt,_ta,_dot,_dot,_dot,_eol
_sc7_msg12:
		.BYTE	___________________,_lt,_do,_u_,_si,_ta,_str,_ret
		.BYTE	___________________,_lt,_GO,_HO,_TT,___,_GO,_HO,_TT,_cr,_ret
		.BYTE	___________________,_lt,_ta,_su,_ke,_te,_ku,_re,_str,_ret
		.BYTE	___________________,_lt,_ni,_ge,_ro,_OO,_ex,_ret
		.BYTE	___________________,_lt,_ke,_i_,_sa,_tu,_wo,___,_yo,_be,_str,_eol
_sc7_msg13:
		.BYTE	___,_ya,_ma,_ga,_ta,_lt,_an2,_ya,_be,$89,___,_ma,_ta,___,_TE,_RO,_da,_ze,_cr,_ret
		.BYTE	_______________________,_o_,_i_,___,_zu,_ra,_ka,_ro,_u_,_ze,_ex,_aof,_eol
_sc7_msg14:
		.BYTE	_ni,_ge,_ma,_to,_u_,_hi,_to,_bi,_to,_wo,___,_ka,_ki,_wa,_ke,_te,_col,___,_ke,_mu,_ri,_no,_na,_ka,_ka,_ra,_ret
		.BYTE	_TE,_RO,_RI,_SU,_TO,_ga,___,_to,_bi,_da,_si,_te,_ki,_ta,_dot,_dot,_dot,_eol
_sc7_msg15:
		.BYTE	_na,_ka,_ma,_ha,___,_mo,_u_,___,_i_,_na,_i_,_cr,_eol
_sc7_msg16:
		.BYTE	_4,_str,_5,_ni,_n_,_no,___,_GU,_RU,_str,_PU,_ra,_si,_i_,_ze,_cr,_ret
		.BYTE	_ke,_mu,_ri,_ni,_mu,_ka,_tt,_te,___,_zi,_uu,_u_,_wo,___,_ha,_tt,_po,_u_,_si,_te,_i_,_ta,_ret
		.BYTE	_TE,_RO,_RI,_SU,_TO,_ga,___,_A_,_str,_MI,_str,_ni,___,_ya,_ra,_re,_ta,_ex,_eol
_sc7_msg17:
		.BYTE	_o_,_n_,_na,_mo,___,_i_,_ru,_mi,_ta,_i_,_da,_ze,_cr,_ret
		.BYTE	_______,_ka__ne__da,_lt,_a_,_re,_ha,_dot,_dot,_dot,___,_ko,_no,_ma,_e_,_no,_ka,_no,_zi,_oo,_qe,_ex,_eol
_sc7_msg18:
		.BYTE	_su,_go,_i_,_ke,_mu,_ri,_da,_dot,_dot,_dot,_eol
_sc7_msg19:
		.BYTE	_A_,_str,_MI,_str,_ga,___,_TE,_RO,_RI,_SU,_TO,_wo,___,_o_,_tt,_te,_col,___,_PU,_RO,_MU,_NA,_str,_DO,_ka,_ra,_ret
		.BYTE	_de,_te,_ki,_ta,_cr,_eol
_sc7_msg1A:
		.BYTE	_A_,_str,_MI,_str,_no,_sa,_ke,_bu,_ko,_e_,_ga,___,_ki,_ko,_e_,_ru,_cr,_eol
_sc7_msg1B:
		.BYTE	___,_A_,_str,_MI,_str,_lt,_su,_i_,_ro,_no,_ho,_u_,_he,___,_i_,_tt,_ta,_zo,_ex,_ex,_eol
_sc7_msg1C:
		.BYTE	_A_,_str,_MI,_str,_ha,___,_so,_no,_ma,_ma,___,_ha,_si,_ri,_sa,_tt,_te,_si,_ma,_tt,_ta,_ze,_cr,_eol
_sc7_msg1D:
		.BYTE	_GU,_RU,_str,_PI,_str,_lt,_an0,_te_tsu__o_,_ku,_n_,_wo,___,_ta,_su,_ke,_ru,_tu,_mo,_ri,_ne,_col,_ret
		.BYTE	_______________________,_ka__ne__da,_ku,_n_,_cr,_aof,_eol
_sc7_msg1E:
		.BYTE	_GU,_RU,_str,_PI,_str,_lt,_an0,_mo,_u_,___,_i_,_i_,_wa,_cr,___,_i_,_ko,_u_,___,_i_,_ko,_u_,_tt,_cr,_ret
		.BYTE	_______________________,_KA,_TT,_PA,_na,_n_,_ka,___,_ho,_tt,_to,_i_,_te,_ex,_aof,_eol
_sc7_msg1F:
		.BYTE	_______,_ka__ne__da,_lt,_na,_a_,_dot,_dot,_dot,___,_o_,_ma,_e_,_ra,_ni,_mo,_ret
		.BYTE	_______________________,_ki,_ki,_ta,_i_,_n_,_da,_ke,_do,_dot,_dot,_dot,_eol
_sc7_msg20:
		.BYTE	_ha,_ru,_ki,_ya,_no,_ma,_e_,_da,_cr,___,_a_,_ta,_ri,_ni,_ha,___,_da,_re,_mo,_i_,_na,_i_,_cr,_eol
_sc7_msg21:
		.BYTE	_O_,_RE,_ha,___,_su,_i_,_ro,_ni,___,_ya,_tt,_te,_ki,_ta,_cr,_eol
_sc7_msg22:
		.BYTE	_______,_o_,_to,_ko,_lt,_an0,_o_,_n_,_na,_AA,_qe,___,_A_,_str,_MI,_str,_na,_ra,___,_sa,_tt,_ki,_ret
		.BYTE	_______________________,_mu,_ko,_u_,_he,___,_ha,_si,_tt,_te,_tt,_ta,_ke,_do,_na,_cr,_aof,_ret
		.BYTE	_______,_ka__ne__da,_lt,_a_,_ri,_ga,_to,_yo,_str,_TT,_cr,_ret
		.BYTE	_O_,_RE,_ha,___,_su,_i_,_ro,_ni,_so,_tt,_te,___,_ha,_si,_ri,_da,_si,_ta,_cr,_eol
_sc7_msg23:
		.BYTE	_O_,_RE,_ha,___,_ki,_uu,_u_,_si,_ga,_i_,_col,___,_u_,_do,_n_,_ya,___,_DO,_str,_MU,_no,_ma,_e_,_ni,_ret
		.BYTE	_ya,_tt,_te,_ki,_ta,_cr,_eol
_sc7_msg24:
		.BYTE	_______,_o_,_to,_ko,_lt,_an0,_e_,_tt,___,_o_,_n_,_na,_AA,_qe,___,_si,_ra,_ne,_e_,_ze,_cr,_aof,_eol
_sc7_msg25:
		.BYTE	_O_,_RE,_ha,___,_KO,_N_,_BI,_NA,_str,_TO,_no,_ti,_ka,_ku,_ni,___,_ya,_tt,_te,_ki,_ta,_cr,_eol
_sc7_msg26:
		.BYTE	_______,_o_,_to,_ko,_lt,_an0,_o_,_n_,_na,_AA,_qe,_ex,___,_dot,_dot,_dot,_so,_re,_yo,_ri,_mo,___,_he,_he,_tt,_ret
		.BYTE	_______________________,_PI,_str,_NA,_TU,_ku,_re,_yo,_str,_cr,___,_he,_tt,_col,___,_he,_he,_he,_he,_cr,_aof,_eol
_sc7_msg27:
		.BYTE	_______,_ka__ne__da,_lt,_u_,_wa,_AA,_ex,_ret
		.BYTE	_DO,_RA,_TT,_GU,_de,___,_RA,_RI,_tt,_ta,_o_,_to,_ko,_ga,___,_NA,_I_,_HU,_wo,___,_to,_ri,_da,_si,_te,_ret
		.BYTE	_to,_bi,_ka,_ka,_tt,_te,_ki,_ta,_ex,_eol
_sc7_msg28:
		.BYTE	_ke,_do,___,_O_,_RE,_no,_a_,_ta,_ma,_no,_na,_ka,_ha,___,_ko,_re,_ma,_de,_no,___,_de,_ki,_go,_to,_de,_ret
		.BYTE	_i_,_tt,_pa,_i_,_da,_tt,_ta,_cr,_eol
_sc7_msg29:
		.BYTE	_A_,_str,_MI,_str,_no,_ya,_tu,_ra,_col,___,_a_,_no,_GA,_KI,_wo,___,_o_,_tt,_ka,_ke,_te,_ta,_n_,_zi,_yy,_ret
		.BYTE	_na,_ka,_tt,_ta,_no,_ka,_qe,_eol
_sc7_msg2A:
		.BYTE	_A_,_str,_MI,_str,_no,_ya,_tu,_ra,_col,___,_ha,_n_,_se,_i_,_hu,_bu,_n_,_si,_ga,_ri,_ni,_ret
		.BYTE	_se,_i_,___,_da,_si,_to,_ki,_yy,___,_i_,_i_,_n_,_da,_yo,_OO,_cr,_eol
_sc7_msgBB:
		.BYTE	_so,_no,_yo,_ru,___,_O_,_RE,_ta,_ti,_ha,___,_o_,_ku,_zi,_oo,_u_,_te,_i_,_e_,_n_,_no,_ret
		.BYTE	_hu,_n_,_su,_i_,_ma,_e_,_ni,___,_i_,_ta,_cr,_ret
		.BYTE	_A_,_BE,_TT,_KU,_ta,_ti,_ga,___,_ta,_mu,_ro,_si,_te,_i_,_ta,_cr,_eol
_sc7_msgBC:
		.BYTE	_dot,_dot,_dot,_a_,_no,_yo,_ru,_no,___,_si,_wa,_da,_ra,_ke,_no,_GA,_KI,_ha,_ret
		.BYTE	_na,_ni,_mo,_no,_na,_n_,_da,_qe,_eol
_sc7_msgBD:
		.BYTE	_ma,_sa,_ka,___,_te_tsu__o_,_ga,___,_a_,_no,_GA,_KI,_ni,___,_ka,_n_,_ke,_i_,_a_,_ru,_n_,_zi,_yy,_ret
		.BYTE	_ne,$89,_da,_ro,_na,_qe,_ret
		.BYTE	_A_,_str,_MI,_str,_no,_ya,_tu,_ra,___,_te_tsu__o_,_wo,___,_do,_ko,_ni,___,_tu,_re,_te,_tt,_ta,_n_,_da,_qe,_eol
_sc7_msgBE:
		.BYTE	___________,_ka,_i_,_lt,_an1,_o_,_str,_o_,_col,___,_na,_ni,___,_ka,_n_,_ga,_e_,_ko,_n_,_de,_n_,_da,_qe,_ex,_aof,_ret
		.BYTE	_GU,_RU,_str,_PI,_str,_lt,_an0,_ka__ne__da,_ku,_str,_n_,_col,___,_ne,_e_,___,_tu,_ma,_n_,_na,_str,_i_,_cr,_aof,_ret
		.BYTE	___,_ya,_ma,_ga,_ta,_lt,_an2,_da,_ma,_tt,_te,_ro,_ex,_aof,_ret
		.BYTE	_GU,_RU,_str,_PI,_str,_lt,_an0,_mo,_u_,_dot,_dot,_dot,_dot,_dot,_dot,_ti,$A1,_ex,_aof,_eol

		SECTION_END		F7
