
		SECTION_START	FF

		MSG_START	_sceneF_msg_lib
		MSG_IDX	_scF_msg00
		MSG_IDX	_scF_msg01
		MSG_IDX	_scF_msg02
		MSG_IDX	_scF_msg03
		MSG_IDX	_scF_msg04
		MSG_IDX	_scF_msg05
		MSG_IDX	_scF_msg06
		MSG_IDX	_scF_msg07
		MSG_IDX	_scF_msg08
		MSG_IDX	_scF_msg09
		MSG_IDX	_scF_msg0A
		MSG_IDX	_scF_msg0C
		MSG_IDX	_scF_msg0D
		MSG_IDX	_scF_msg0E
		MSG_IDX	_scF_msg0F
		MSG_IDX	_scF_msg10
		MSG_IDX	_scF_msg11
		MSG_IDX	_scF_msg12
		MSG_IDX	_scF_msg13
		MSG_IDX	_scF_msg14
		MSG_IDX	_scF_msg15
		MSG_IDX	_scF_msg16
		MSG_IDX	_scF_msg17
		MSG_IDX	_scF_msg18
		MSG_IDX	_scF_msg19
		MSG_IDX	_scF_msg1A
		MSG_IDX	_scF_msg1B
		MSG_IDX	_scF_msg1C
		MSG_IDX	_scF_msg1D
		MSG_IDX	_scF_msg1E
		MSG_IDX	_scF_msg1F
		MSG_IDX	_scF_msg92					; scene F msg
_scF_msg00:
		.BYTE	_BE,_BI,_str,_RU,_str,_MU,_no,_na,_ka,_ha,___,_ma,_ru,_de,___,_zi,_si,_n_,_ni,_de,_mo,_ret
		.BYTE	_a_,_tt,_ta,_yo,_u_,_da,_tt,_ta,_ze,_cr,_ret
		.BYTE	_______,_ka__ne__da,_lt,_o_,_i_,_o_,_i_,_col,___,_O_,_RE,_no,_se,_i_,_ka,_AA,_qe,_ex,_eol
_scF_msg01:
		.BYTE	_______,_ka__ne__da,_lt,_ko,_re,_ga,___,_BE,_BI,_str,_RU,_str,_MU,_tt,_tu,_u_,_no,_ka,_qe,_eol
_scF_msg02:
		.BYTE	_a_,_n_,_to,_ki,_no,___,_GA,_KI,_da,_ex,_eol
_scF_msg03:
		.BYTE	_GA,_KI,_no,___,_na,_ka,_ma,_ka,_qe,_eol
_scF_msg04:
		.BYTE	_______,_ta,_i_,_sa,_lt,_o_,_i_,_tt,___,_ha,_ya,_ku,___,_ko,_no,_BA,_KA,_mo,_no,_wo,_ret
		.BYTE	_______________________,_tu,_ma,_mi,_da,_se,_tt,_ex,_eol
_scF_msg05:
		.BYTE	_______,_te_tsu__o_,_lt,_ka__ne__da,_qe,_ret
		.BYTE	_______________________,_dot,_dot,_dot,_na,_n_,_de,___,_ko,_n_,_na,_to,_ko,_ro,_ni,_dot,_dot,_dot,_qe,_eol
_scF_msg06:
		.BYTE	_______,_ka__ne__da,_lt,_an0,_te_tsu__o_,_OO,___,_da,_i_,_zi,_oo,_u_,_bu,_ka,_AA,_cr,_ret
		.BYTE	_______________________,_ta,_su,_ke,_ni,___,_ki,_ta,_zo,_OO,_ex,_aof,_ret
		.BYTE	_______,_te_tsu__o_,_lt,_dot,_dot,_dot,_dot,_dot,_dot,_eol
_scF_msg07:
		.BYTE	_______,_te_tsu__o_,_lt,_an1,_i_,_i_,_n_,_da,_yo,___,_ka__ne__da,_AA,_col,___,_O_,_RE,_ha,___,_mo,_u_,_ret
		.BYTE	_______________________,_o_,_ma,_e_,_ni,___,_ta,_su,_ke,_te,___,_mo,_ra,_wa,_na,_ku,_tt,_te,_mo,_ret
		.BYTE	_______________________,_i_,_i_,_n_,_da,_yo,_dot,_dot,_dot,___,_ko,_re,_ka,_ra,_ha,___,_O_,_RE,_ga,_ret
		.BYTE	_______________________,_o_,_ma,_e_,_wo,___,_ta,_su,_ke,_te,_ya,_ru,_dot,_dot,_dot,___,_so,_n_,_to,_ki,_ha,_ret
		.BYTE	_______________________,_i_,_i_,_na,_col,___,_KA,_NE,_ti,_yy,_n_,_yo,_OO,_cr,_aof,_eol
_scF_msg08:
		.BYTE	_______,_te_tsu__o_,_lt,_ka__ne__da,_AA,_col,___,_na,_ni,___,_bi,_bi,_tt,_te,_n_,_da,_yo,_ex,_eol
_scF_msg09:
		.BYTE	_______,_te_tsu__o_,_lt,_an1,_do,_u_,_su,_N_,_da,_yo,_OO,_str,_TT,_ex,_ex,_aof,_ret
		.BYTE	_______,_ka__ne__da,_lt,_an0,_u_,_wa,_tt,___,_u_,_wa,$9E,_str,_tt,_ex,_aof,_ret
		.BYTE	_BA,_TT,_SI,_TT,_str,_N_,_ex,_ex,_eol
_scF_msg0A:
		.BYTE	_ka__ne__da,_si,_oo,_u_,_ne,_n_,_ha,___,_ki,_ze,_tu,___,_si,_te,_si,_ma,_i_,_ma,_si,_ta,_dot,_dot,_dot,_ret
		.BYTE	___________,_KE,_I_,_lt,_ka__ne__da,_ku,_n_,_dot,_dot,_dot,_eol
_scF_msg0C:
		.BYTE	_______,_te_tsu__o_,_lt,_O_,_RI,_N_,_PI,_TT,_KU,_ka,_i_,_zi,_oo,_u_,_dot,_dot,_dot,_ret
		.BYTE	_______________________,_ti,_ka,_si,_se,_tu,$88,_qe,_ex,_ret
		.BYTE	_______,_KI,_YO,_KO,_lt,_an0,_ti,_ga,_u_,_wa,_ex,___,_A_,_KI,_RA,_ku,_n_,_ha,_ex,_ret
		.BYTE	_______________________,_a_,_col,___,_ma,_tt,_te,$89,_ex,___,_ki,_yy,_a_,_ex,_aof,_eol
_scF_msg0D:
		.BYTE	_te_tsu__o_,_ha,___,_BE,_BI,_str,_RU,_str,_MU,_no,___,_te,_n_,_zi,_oo,_u_,_wo,___,_ha,_ka,_i_,_si,_te,_col,_ret
		.BYTE	_to,_bi,_ta,_tt,_ta,_cr,_ret
		.BYTE	_te_tsu__o_,_no,_ko,_e_,_da,_ke,_ga,___,_hi,_bi,_i_,_te,_ki,_ta,_cr,_eol
_scF_msg0E:
		.BYTE	_______,_KI,_YO,_KO,_lt,_an0,_to,_n_,_da,_WA,_dot,_dot,_dot,_ret
		.BYTE	_______________________,_so,_n_,_na,_ti,_ka,_ra,_ma,_de,___,_a_,_ru,_na,_n_,_te,_dot,_dot,_dot,_aof,_eol
_scF_msg0F:
		.BYTE	_______,_ta,_i_,_sa,_lt,_an0,_a_,_no,_ta,_n_,_ki,_ka,_n_,_ni,___,_ko,_ko,_ma,_de,_no,___,_ti,_ka,_ra,_wo,_ex,_ret
		.BYTE	_______________________,_na,_n_,_to,_i_,_u_,_ko,_to,_da,_dot,_dot,_dot,_ret
		.BYTE	_______________________,_da,_re,_ka,___,_o_,_ra,_n_,_no,_ka,_a_,_ex,_ret
		.BYTE	_______________________,_sa,_ga,_se,_ex,___,_te_tsu__o_,_wo,___,_sa,_ga,_su,_n_,_da,_AA,_ex,_aof,_eol
_scF_msg10:
		.BYTE	_______,_KI,_YO,_KO,_lt,_an0,_mo,_u_,___,_ya,_me,_te,_dot,_dot,_dot,___,_ko,_re,_i_,_zi,_oo,_u_,_ret
		.BYTE	_______________________,_hi,_to,_wo,___,_ki,_zu,_tu,_ke,_na,_i_,_de,_dot,_dot,_dot,_aof,_ret
		.BYTE	_______,_te_tsu__o_,_lt,_A_,_KI,_RA,_tt,_te,_no,_ha,___,_do,_ko,_ni,_i_,_ru,_ex,_ret
		.BYTE	_______,_KI,_YO,_KO,_lt,_an0,_so,_re,_ha,_dot,_dot,_dot,_aof,_eol
_scF_msg11:
		.BYTE	_KE,_I_,_ha,___,_GA,_KI,_do,_mo,_no,_ho,_u_,_wo,___,_mi,_te,_col,___,_bo,_u_,_ze,_n_,_to,_ret
		.BYTE	_si,_te,_i_,_ru,_cr,_eol
_scF_msg12:
		.BYTE	_______,_ka__ne__da,_lt,_u_,_he,_tt,___,_NE,_ZU,_MI,_no,_si,_ga,_i_,_da,_str,_cr,_ret
		.BYTE	_ha,_i_,_su,_i_,_ko,_u_,_de,___,_DO,_BU,_ni,___,_mo,_gu,_tt,_ta,_to,_ki,___,_ha,_i_,_tt,_ta,_n_,_da,_cr,_eol
_scF_msg13:
		.BYTE	_______,_ta,_i_,_sa,_lt,_ko,_zo,_u_,_ex,___,_do,_u_,_ya,_tt,_te,___,_te,_ni,_i_,_re,_ta,_AA,_ex,_eol
_scF_msg14:
		.BYTE	_______,_ta,_i_,_sa,_lt,_na,_ni,_wo,___,_si,_te,_i_,_ru,_col,___,_ha,_ya,_ku,___,_tu,_ka,_ma,_e_,_ro,_ex,_eol
_scF_msg15:
		.BYTE	_______,_ta,_i_,_sa,_lt,_ko,_zo,_u_,_ex,___,_do,_u_,_ya,_tt,_te,___,_ko,_ko,_ma,_de,___,_ki,_ta,_ex,_eol
_scF_msg16:
		.BYTE	_O_,_RE,_ha,___,_ha,_na,_si,_ka,_ke,_yo,_u_,_to,___,_si,_ta,_cr,_eol
_scF_msg17:
		.BYTE	_si,_ka,_si,___,_GA,_KI,_ha,___,_da,_ma,_tt,_ta,_ma,_ma,_da,_tt,_ta,_cr,_eol
_scF_msg18:
		.BYTE	_si,_ka,_si,___,_GA,_KI,_ha,___,_KE,_I_,_wo,___,_mi,_tu,_me,_ta,_ma,_ma,_de,_col,_ret
		.BYTE	_ko,_ta,_e_,_yo,_u_,_to,___,_si,_na,_ka,_tt,_ta,_cr,_ret
		.BYTE	___________,_KE,_I_,_lt,_a_,_na,_ta,_ha,_dot,_dot,_dot,_eol
_scF_msg19:
		.BYTE	_______,_KI,_YO,_KO,_lt,_an0,_so,_u_,_yo,_cr,_aof,_eol
_scF_msg1A:
		.BYTE	_______,_ka__ne__da,_lt,_an0,_ha,_ya,_ku,___,_si,_ro,_yo,_col,___,_BA,_KA,_TT,_ex,_aof,_eol
_scF_msg1B:
		.BYTE	_______,_ka__ne__da,_lt,_an0,_na,_n_,_da,_to,_OO,_ex,___,_te,_me,_e_,___,_da,_re,_ni,_mu,_ka,_tt,_te,_ret
		.BYTE	_______________________,_ku,_ti,___,_ki,_i_,_te,_n_,_da,_AA,_cr,_aof,_eol
_scF_msg1C:
		.BYTE	_______,_te_tsu__o_,_lt,_an1,_he,_tt,_dot,_dot,_dot,___,_ku,_ti,_no,___,_ki,_ki,_ka,_ta,_ga,_ret
		.BYTE	_______________________,_ki,_ni,_i_,_ra,_ne,$89,_ka,_dot,_dot,_dot,___,_a_,_ta,_ma,_ni,___,_ki,_ta,_ka,_qe,_ret
		.BYTE	_______________________,_na,_ra,_do,_u_,_su,_ru,_col,___,_o_,_i_,_ex,___,_ka__ne__da,_AA,_cr,_aof,_eol
_scF_msg1D:
		.BYTE	_______,_te_tsu__o_,_lt,_na,_n_,_da,___,_ko,_ri,_yy,_a_,_col,___,_ko,_re,_mo,_ret
		.BYTE	_______________________,_O_,_RE,_no,_ti,_ka,_ra,_na,_no,_ka,_str,_tt,_ex,_ex,_eol
_scF_msg1E:
		.BYTE	_______,_ta,_i_,_sa,_lt,_an0,_so,_i_,_tu,_ha,___,_BU,_TI,_ko,_n_,_de,_o_,_ke,_ex,_aof,_eol
_scF_msg1F:
		.BYTE	_______,_ta,_i_,_sa,_lt,_an0,_ni,_si,_da,_col,___,_O_,_RI,_N_,_PI,_TT,_KU,_ke,_n_,_se,_tu,_ge,_n_,_ba,_ni,_ret
		.BYTE	_______________________,_mu,_ka,_tt,_te,_i_,_ru,_zo,_ex,_ret
		.BYTE	_______________________,_su,_be,_te,_no,___,_ka,_n_,_se,_n_,_ni,___,_ke,_n_,_mo,_n_,_wo,___,_hi,_ke,_col,_ret
		.BYTE	_______________________,_ka,_na,_ra,_zu,___,_to,_ra,_e_,_ru,_n_,_da,_col,___,_i_,_i_,_na,_AA,_ex,_aof,_eol
_scF_msg92:
		.BYTE	_______,_te_tsu__o_,_lt,_an1,_a_,_tt,_ha,_tt,_ha,_tt,_ha,_tt,___,_ha,_tt,_ha,_tt,_ha,_tt,_dot,_dot,_dot,_aof,_eol

		SECTION_END		FF