
		SECTION_START	F9

		MSG_START	_scene9_msg_lib
;		MSG_IDX	_sc9_msg00							; -unused-
		MSG_IDX	_sc9_msg01
		MSG_IDX	_sc9_msg02
		MSG_IDX	_sc9_msg03
		MSG_IDX	_sc9_msg04
		MSG_IDX	_sc9_msg05
		MSG_IDX	_sc9_msg06
		MSG_IDX	_sc9_msg07
		MSG_IDX	_sc9_msg08
		MSG_IDX	_sc9_msg09
		MSG_IDX	_sc9_msg0A
		MSG_IDX	_sc9_msg0B
		MSG_IDX	_sc9_msg0C
		MSG_IDX	_sc9_msg0D
		MSG_IDX	_sc9_msg0E
		MSG_IDX	_sc9_msg0F
		MSG_IDX	_sc9_msg10
		MSG_IDX	_sc9_msg11
		MSG_IDX	_sc9_msg12
		MSG_IDX	_sc9_msg13
		MSG_IDX	_sc9_msg14
		MSG_IDX	_sc9_msg15
		MSG_IDX	_sc9_msg8D					; scene 9 msg
		MSG_IDX	_sc9_msg8E					; scene 9 msg
		MSG_IDX	_sc9_msgAE					; scene 9 msg
		MSG_IDX	_sc9_msgB7					; scene 9 msg
;_sc9_msg00:
;		.BYTE	_ka,_no,_zi,_oo,_ni,___,_tu,_i_,_te,_tt,_te,_col,___,_BO,_RO,_TT,_ti,_i_,_BI,_RU,_no,_ret
;		.BYTE	_ti,_ka,_si,_tu,_ma,_de,___,_ki,_ti,_ma,_tt,_ta,_cr,_eol
_sc9_msg01:
		.BYTE	_______,_ka__ne__da,_lt,_bo,_ku,_ta,_ti,_ha,___,_ma,_da,___,_wa,_ka,_i_,_n_,_da,_si,_col,_ret
		.BYTE	_______________________,_ya,_ri,_na,_o_,_se,_ru,_to,___,_o_,_mo,_u_,_n_,_da,_yo,_ne,_cr,_ret
		.BYTE	_______________________,_tu,_i_,_te,_tt,_te,___,_ya,_ru,_ka,_ra,_sa,_AA,_dot,_dot,_dot,_eol
_sc9_msg02:
		.BYTE	_______,_o_,_n_,_na,_no,_ko,_lt,_an0,_RI,_UU,_U_,$88,_ex,_aof,_eol
_sc9_msg03:
		.BYTE	_______,_ka__ne__da,_lt,_zi,_si,_uu,___,_si,_na,_yo,_str,_cr,_ret
		.BYTE	_______________________,_ha,_zi,_me,_te,___,_da,_tt,_ta,_n_,_da,_ro,_OO,_col,___,_HI,_TO,_ret
		.BYTE	_______________________,_ko,_ro,_si,_ta,_no,_dot,_dot,_dot,_eol
_sc9_msg04:
		.BYTE	_______,_ka__ne__da,_lt,_de,_sa,_AA,_col,___,_mi,_mo,___,_ko,_ko,_ro,_mo,___,_ki,_re,_i_,_ni,_ret
		.BYTE	_______________________,_na,_tt,_ta,_ra,_col,___,_o_,_ti,_yy,_de,_mo,___,_no,_mi,_ni,_i_,_ko,_u_,_yo,_cr,_eol
_sc9_msg05:
		.BYTE	_______,_ka__ne__da,_lt,_ku,_yo,_ku,_yo,___,_su,_N_,_na,_yo,_OO,_col,___,_ya,_tt,_ti,_ma,_tt,_ta,_ret
		.BYTE	_______________________,_mo,_no,_ha,___,_si,_oo,_str,_ga,_ne,_str,_da,_ro,_u_,_col,_ret
		.BYTE	_______________________,_ya,_tt,_ti,_ma,_tt,_ta,_mo,_no,_ha,_sa,_str,_tt,_cr,_eol
_sc9_msg06:
		.BYTE	_TE,_RO,_RI,_SU,_TO,_lt,_an0,_da,_re,_da,_AA,_ex,_aof,_ret
		.BYTE	_______,_RI,_UU,_U_,_lt,_an1,_KE,_I_,_ka,_qe,_ex,_aof,_ret
		.BYTE	___________,_KE,_I_,_lt,_RI,_UU,_U_,_TT,_col,_bu,_zi,_da,_tt,_ta,_no,_ne,_ex,_eol
_sc9_msg07:
		.BYTE	_ko,_no,_o_,_to,_ko,_ga,___,_RI,_UU,_U_,_ra,_si,_i_,_cr,_eol
_sc9_msg08:
		.BYTE	_ti,_no,_ke,_no,___,_o_,_o_,_so,_u_,_na,_ya,_tu,_ra,_da,_ze,_cr,_eol
_sc9_msg09:
		.BYTE	_TE,_RO,_RI,_SU,_TO,_lt,_an0,_na,_ni,_mo,_no,_da,_ex,_aof,_eol
_sc9_msg0A:
		.BYTE	_KE,_I_,_ti,_yy,_n_,_ka,_dot,_dot,_dot,___,_he,_he,_tt,___,_na,_ma,_e_,_ma,_de,_ret
		.BYTE	_wa,_ka,_tt,_ti,_yy,_tt,_ta,_mo,_n_,_NE,_str,_cr,___,_na,_ka,_ma,_ka,_do,_u_,_ka,_ret
		.BYTE	_si,_N_,_ne,_e_,_ke,_do,_col,___,_o_,_tt,_sa,_n_,_ha,___,_i_,_ra,_na,_i_,_tt,_tu,_str,_no,_cr,_eol
_sc9_msg0B:
		.BYTE	_TE,_RO,_RI,_SU,_TO,_lt,_an0,_SU,_PA,_I_,_ka,_qe,_ex,_aof,_eol
_sc9_msg0C:
		.BYTE	_______,_ka__ne__da,_lt,_zi,_tu,_ha,___,_KE,_I_,_ti,_yy,_n_,_ga,___,_A_,_str,_MI,_str,_ni,_ret
		.BYTE	_______________________,_su,_i_,_ro,_de,___,_o_,_so,_wa,_re,_te,_ta,_n_,_de,_su,_yo,_ne,$89,_dot,_dot,_dot,_ret
		.BYTE	_______________________,_ma,_a_,_col,___,_O_,_RE,_ga,___,_KE,_I_,_ti,_yy,_n_,_no,___,_PI,_N_,_TI,_wo,_ret
		.BYTE	_______________________,_su,_ku,_tt,_ta,_wa,_ke,_de,_dot,_dot,_dot,___,_ka,_n_,_si,_yy,_ret
		.BYTE	_______________________,_si,_te,_mo,_ra,_tt,_te,_mo,___,_i_,_i_,_n_,_zi,_yy,_na,_i_,_SU,_ka,_qe,_eol
_sc9_msg0D:
		.BYTE	_______,_ka__ne__da,_lt,_O_,_TT,___,_O_,_RE,_de,_su,_ka,_AA,_qe,_______,_i_,_ya,_a_,_col,___,_na,_n_,_te,_ret
		.BYTE	_______________________,_i_,_i_,_ma,_su,_ka,___,_KE,_I_,_ti,_yy,_n_,_no,___,_ko,_i_,_bi,_to,_dot,_dot,_dot,_ret
		.BYTE	_______________________,_te,_i_,_u_,_to,_col,___,_ti,_oo,_tt,_to,___,_i_,_i_,_su,_gi,_ni,_ret
		.BYTE	_______________________,_na,_tt,_ti,_yy,_u_,_n_,_de,_su,_ke,_do,_dot,_dot,_dot,_eol
_sc9_msg0E:
		.BYTE	_______,_ka__ne__da,_lt,_KE,_I_,_ti,_yy,_n_,_col,___,_ko,_no,_ko,_wa,_i_,_o_,_zi,_sa,_n_,_ta,_ti,_ret
		.BYTE	_______________________,_da,_str,_re,_qe,_eol
_sc9_msg0F:
		.BYTE	___________,_KE,_I_,_lt,_ho,_n_,_to,_u_,_yo,_dot,_dot,_dot,_ret
		.BYTE	_______________________,_so,_re,_ni,___,_SU,_PA,_I_,_zi,_yy,___,_na,_i_,_ko,_to,_da,_ke,_ha,_ret
		.BYTE	_______________________,_ta,_si,_ka,_yo,_dot,_dot,_dot,_eol
_sc9_msg10:
		.BYTE	___________,_KE,_I_,_lt,_wa,_ta,_si,_col,___,_si,_ra,_na,_i_,_ex,_eol
_sc9_msg11:
		.BYTE	_PU,_RO,_MU,_NA,_str,_DO,_de,___,_mi,_ta,___,_o_,_to,_ko,_da,_cr,_eol
_sc9_msg12:
		.BYTE	_______,_ka__ne__da,_lt,_zi,_tu,_ha,___,_se,_i_,_hu,_no,___,_ha,_n_,_se,_i_,_hu,_bu,_n_,_si,_ga,_ri,_no,_ret
		.BYTE	_______________________,_SU,_PA,_I_,_da,_tt,_ta,_ri,___,_si,_ti,_yy,_u_,_n_,_de,_su,_yo,_ne,_dot,_dot,_dot,_eol
_sc9_msg13:
		.BYTE	_do,_u_,_ya,_ra,___,_TE,_RO,_RI,_SU,_TO,_ta,_ti,_no,___,_A_,_ZI,_TO,_ra,_si,_i_,_cr,_eol
_sc9_msg14:
		.BYTE	_o_,_n_,_na,_no,_ko,_lt,_an0,_dot,_dot,_dot,_RI,_UU,_U_,_col,___,_do,_ko,_na,_no,_ex,_aof,_eol
_sc9_msg15:
		.BYTE	_______,_ka__ne__da,_lt,_a_,_tt,___,_de,_mo,_dot,_dot,_dot,___,_ni,_ku,_ta,_i_,_ka,_n_,_ke,_i_,_ha,_ret
		.BYTE	_______________________,_ma,_da,_na,_n_,_de,_su,_yo,_ne,$89,_dot,_dot,_dot,_eol
_sc9_msg8D:
		.BYTE	_______,_ka__ne__da,_lt,_so,_col,___,_so,_n_,_na,_a_,_dot,_dot,_dot,_eol
_sc9_msg8E:
		.BYTE	_TE,_RO,_RI,_SU,_TO,_lt,_an0,_na,_n_,_da,_to,_o_,_str,_ex,_ex,_aof,_eol
_sc9_msgAE:
		.BYTE	_DO,_TT,_GI,_UU,_str,_N_,_ex,_ret
		.BYTE	_TE,_RO,_RI,_SU,_TO,_ga,___,_zi,_uu,_u_,_wo,___,_ha,_tt,_po,_u_,_si,_ta,_cr,_eol
_sc9_msgB7:
		.BYTE	_O_,_RE,_ta,_ti,_ha,___,_A_,_str,_MI,_str,_no,_ya,_tu,_ra,_wo,___,_na,_n_,_to,_ka,___,_ma,_i_,_ta,_cr,_ret
		.BYTE	_so,_re,_de,___,_ka,_no,_zi,_oo,_no,_a_,_n_,_na,_i_,_de,___,_ko,_n_,_na,_to,_ko,_ro,_ni,_ret
		.BYTE	_ki,_ti,_ma,_tt,_ta,_cr,_eol

		SECTION_END		F9
