
		SECTION_START	F3

		MSG_START	_scene3_msg_lib
		MSG_IDX	_sc3_msg00
		MSG_IDX	_sc3_msg01
		MSG_IDX	_sc3_msg02
		MSG_IDX	_sc3_msg03
		MSG_IDX	_sc3_msg04
		MSG_IDX	_sc3_msg05
		MSG_IDX	_sc3_msg06
		MSG_IDX	_sc3_msg07
;		.WORD	0									; dummy
		MSG_IDX	_sc3_msg09
_sc3_msg00:
		.BYTE	_O_,_RE,_ha,___,_o_,_n_,_na,_no,_KO,_wo,___,_sa,_so,_i_,_da,_su,_no,_ni,___,_ma,_n_,_ma,_to,_ret
		.BYTE	_se,_i_,_ko,_u_,_si,_ta,_ze,_cr,_eol
_sc3_msg01:
		.BYTE	_______,_ka__ne__da,_lt,_an0,_da,_ka,_ra,_AA,___,_so,_no,_he,_n_,_de,___,_o_,_ti,_yy,_de,_mo,_ret
		.BYTE	_______________________,_do,_str,_ka,_na,_AA,_to,___,_o_,_mo,_tt,_te,_sa,_dot,_dot,_dot,_dot,_ret
		.BYTE	_______________________,_so,_no,_dot,_dot,_dot,_dot,___,_ka,_ku,_me,_i_,___,_to,_i_,_u_,_ko,_to,_ni,_ret
		.BYTE	_______________________,_tu,_i_,_te,___,_ki,_mi,_to,___,_zi,_tt,_ku,_ri,___,_ha,_na,_si,_ta,_i_,_to,_ret
		.BYTE	_______________________,_o_,_mo,_tt,_te,_ne,$89,_str,_cr,_aof,_eol
_sc3_msg02:
		.BYTE	_o_,_n_,_na,_no,_ko,_lt,_an1,_HU,_TT,___,_ti,_ka,_go,_ro,_no,___,_NA,_N_,_PA,_mo,___,_te,_ga,_ret
		.BYTE	_______________________,_ko,_n_,_de,_ki,_ta,_mo,_no,_ne,_dot,_dot,_dot,_ret
		.BYTE	_______________________,_o_,_n_,_na,_no,_KO,_na,_ra,___,_da,_re,_de,_mo,___,_ta,_su,_ke,_te,_ku,_re,_ru,_ret
		.BYTE	_______________________,_wa,_ke,_ne,_dot,_dot,_dot,___,_mi,_sa,_ka,_i_,_na,_si,_ni,_dot,_dot,_dot,_aof,_eol
_sc3_msg03:
		.BYTE	_______,_ka__ne__da,_lt,_an0,_O_,_RE,_no,___,_ka,_ti,_ki,_zi,_uu,_n_,_ha,___,_SI,_BI,_A_,_da,_yo,_str,_cr,_ret
		.BYTE	_______________________,_i_,_ya,_col,___,_so,_no,_col,___,_me,_n_,_ku,_i_,_tt,_te,_wa,_ke,_zi,_yy,_ret
		.BYTE	_______________________,_na,_i_,_n_,_da,_yo,_ne,_cr,_ret
		.BYTE	_______________________,_na,_n_,_te,_yu,_str,_ka,_col,___,_SE,_N_,_SU,_ne,_col,___,_SE,_N_,_SU,_ga,_ret
		.BYTE	_______________________,_O_,_RE,_wo,___,_so,_u_,_sa,_se,_te,_ru,_n_,_da,_na,_AA,_cr,_aof,_eol
_sc3_msg04:
		.BYTE	_o_,_n_,_na,_no,_ko,_lt,_an1,_i_,_ti,_o_,_u_,___,_re,_i_,_ha,___,_i_,_tt,_to,_ku,_wa,_cr,_ret
		.BYTE	_______________________,_do,_u_,_mo,___,_a_,_ri,_ga,_to,_u_,_cr,___,_e_,_str,_to,_dot,_dot,_dot,_aof,_eol
_sc3_msg05:
		.BYTE	_______,_ka__ne__da,_lt,_an0,_ka__ne__da,_de,_su,_col,___,_yo,_ro,_si,_ku,_cr,_aof,_eol
_sc3_msg06:
		.BYTE	_o_,_n_,_na,_no,_ko,_lt,_an1,_zi,_yy,_a_,_ne,_col,___,_ka__ne__da,_ku,_n_,_cr,_aof,_eol
_sc3_msg07:
		.BYTE	_______,_ka__ne__da,_lt,_an0,_e_,_tt,_col,___,_mo,_u_,___,_i_,_tt,_ti,_yy,_u_,_no,_cr,_ret
		.BYTE	_______________________,_so,_ri,_yy,_col,_na,_i_,_yo,_OO,_cr,___,_ne,$89,_col,___,_ti,_oo,_tt,_to,_cr,_ret
		.BYTE	_______________________,_se,_tt,_ka,_ku,___,_ta,_su,_ke,_te,___,_ya,_tt,_ta,_no,_ni,_sa,_AA,_cr,_ret
		.BYTE	_______________________,_KU,_SO,_TT,_ex,___,_na,_ma,_e_,_gu,_ra,_i_,___,_o_,_si,_e_,_te,_ke,_str,_cr,_aof,_eol
_sc3_msg09:
		.BYTE	_ma,_nu,_ke,_na,_A_,_str,_MI,_str,_ga,___,_si,_uu,_ri,_uu,_u_,_da,_n_,_no,___,_to,_ri,_a_,_tu,_ka,_i_,_ni,_ret
		.BYTE	_si,_tt,_pa,_i_,___,_si,_ya,_ga,_tt,_ta,_n_,_da,_cr,___,_he,_he,_tt,_col,___,_BA,_str,_KA,_cr,_eol

		SECTION_END		F3
