
		SECTION_START	F15

		MSG_START	_scene15_msg_lib
		MSG_IDX	_sc15_msg00
		MSG_IDX	_sc15_msg01
		MSG_IDX	_sc15_msg02
		MSG_IDX	_sc15_msg03
		MSG_IDX	_sc15_msg04
		MSG_IDX	_sc15_msg05
		MSG_IDX	_sc15_msg06
		MSG_IDX	_sc15_msg07
		MSG_IDX	_sc15_msg08
		MSG_IDX	_sc15_msg09
;		MSG_IDX	_sc15_msg0A						; -unused-
		MSG_IDX	_sc15_msg0B
		MSG_IDX	_sc15_msg0C
		MSG_IDX	_sc15_msg0D
		MSG_IDX	_sc15_msg0E
		MSG_IDX	_sc15_msg0F
		MSG_IDX	_sc15_msg10
		MSG_IDX	_sc15_msg11
		MSG_IDX	_sc15_msg12
		MSG_IDX	_sc15_msg13
		MSG_IDX	_sc15_msg14
		MSG_IDX	_sc15_msg15
		MSG_IDX	_sc15_msg16
		MSG_IDX	_sc15_msg17
		MSG_IDX	_sc15_msg18
		MSG_IDX	_sc15_msg19
		MSG_IDX	_sc15_msg1A
		MSG_IDX	_sc15_msg1B
		MSG_IDX	_sc15_msg1C
		MSG_IDX	_sc15_msg1D
		MSG_IDX	_sc15_msg1E
		MSG_IDX	_sc15_msg1F
		MSG_IDX	_sc15_msg20
		MSG_IDX	_sc15_msg21
		MSG_IDX	_sc15_msg22
		MSG_IDX	_sc15_msg23
		MSG_IDX	_sc15_msg24
		MSG_IDX	_sc15_msg25
		MSG_IDX	_sc15_msg27
		MSG_IDX	_sc15_msg29
		MSG_IDX	_sc15_msg2A
		MSG_IDX	_sc15_msg2B
		MSG_IDX	_sc15_msg2D
		MSG_IDX	_sc15_msg33
		MSG_IDX	_sc15_msg34
		MSG_IDX	_sc15_msg35
		MSG_IDX	_sc15_msg36
		MSG_IDX	_sc15_msg37
		MSG_IDX	_sc15_msg38
		MSG_IDX	_sc15_msg9D					; scene 15 msg
		MSG_IDX	_sc15_msgAC					; scene 15 msg
_sc15_msg00:
		.BYTE	_GA,_TT,_GA,_GA,_GA,_GA,_dot,_dot,_dot,_ret
		.BYTE	_O_,_RE,_ha,___,_RE,_str,_ZA,_str,_BI,_str,_MU,_wo,___,_mo,_ti,_a_,_ge,_na,_ga,_ra,___,_GA,_RE,_KI,_no,_ret
		.BYTE	_SU,_TA,_ZI,_A_,_MU,_wo,___,_ha,_si,_tt,_ta,_cr,_eol
_sc15_msg01:
		.BYTE	_so,_si,_te,___,_O_,_RE,_ha,___,_tu,_i_,_ni,___,_te_tsu__o_,_wo,___,_mi,_tu,_ke,_ta,_ex,_eol
_sc15_msg02:
		.BYTE	_te_tsu__o_,_no,_mi,_gi,_u_,_de,_ka,_ra,___,_no,_bi,_ta,___,_bu,_ki,_mi,_na,_ka,_ta,_ma,_ri,_ga,_ret
		.BYTE	_A_,_str,_MI,_str,_no,_TA,_KO,_ya,_ro,_u_,_wo,___,_o_,_so,_tt,_te,_i_,_ta,_cr,_eol
_sc15_msg03:
		.BYTE	_BA,_SI,_TT,_II,_str,_ex,_ret
		.BYTE	_si,_oo,_u_,_ge,_ki,_ha,_ga,___,_ka__ne__da,_wo,___,_ti,_oo,_ku,_ge,_ki,_si,_ta,_cr,_ret
		.BYTE	_______,_ka__ne__da,_lt,_u_,_wa,_a_,_str,_ex,_ex,_eol
_sc15_msg04:
		.BYTE	_O_,_RE,_ha,___,_ma,_ta,___,_RE,_str,_ZA,_str,_BI,_str,_MU,_wo,___,_ka,_ma,_e_,_ta,_cr,_ret
		.BYTE	_______,_ka__ne__da,_lt,_an0,_te_tsu__o_,_col,___,_zi,_oo,_u_,_bu,_tu,___,_sa,_se,_te,_ya,_ru,_ka,_ra,_na,_ex,_aof,_eol
_sc15_msg05:
		.BYTE	_______,_ka__ne__da,_lt,_O_,_U_,_TT,___,_A_,_KU,_SE,_RU,___,_HU,_RU,_SU,_RO,_TT,_TO,_RU,_da,_ze,_str,_ex,_ret
		.BYTE	_O_,_RE,_ha,___,_BA,_I_,_KU,_go,_to,___,_te_tsu__o_,_ni,___,_ta,_i_,_a_,_ta,_ri,_ret
		.BYTE	_si,_yo,_u_,_to,_si,_ta,_cr,_eol
_sc15_msg06:
		.BYTE	_si,_ka,_si,___,_GA,_RE,_KI,_ni,___,_TA,_I_,_YA,_ga,___,_ha,_sa,_ma,_tt,_te,_si,_ma,_i_,_col,_ret
		.BYTE	_O_,_RE,_ha,___,_te,_n_,_to,_u_,___,_si,_te,_si,_ma,_tt,_ta,_cr,_eol
_sc15_msg07:
		.BYTE	_______,_ka__ne__da,_lt,_te_tsu__o_,_no,_ya,_tu,___,_BO,_SU,_ki,_do,_ri,_mo,_ret
		.BYTE	_______________________,_o_,_si,_ma,_i_,_da,_ze,_cr,_eol
_sc15_msg08:
		.BYTE	_______,_te_tsu__o_,_lt,_an0,_ka__ne__da,_AA,___,_zi,_oo,_u_,_bu,_tu,_su,_n_,_no,_ha,_ret
		.BYTE	_______________________,_te,_me,_e_,_no,_ho,_u_,_da,_yo,_ex,_aof,_eol
_sc15_msg09:
		.BYTE	_O_,_RE,_ha,___,_ya,_ke,_ku,_so,_ni,_na,_tt,_te,___,_RE,_str,_ZA,_str,_wo,___,_na,_ge,_tu,_ke,_ta,_cr,_ret
		.BYTE	_RE,_str,_ZA,_str,_ha,___,_te_tsu__o_,_ni,___,_a_,_ta,_ra,_na,_ka,_tt,_ta,_cr,_eol
;_sc15_msg0A:
;		.BYTE	_O_,_RE,_ha,___,_te_tsu__o_,_no,_mi,_gi,_u_,_de,_no,_yo,_ko,_he,___,_ka,_ga,_mi,_wo,___,_na,_ge,_ta,_cr,_eol
_sc15_msg0B:
		.BYTE	_mi,_gi,_u_,_de,_ni,___,_mi,_oo,_u_,_na,_mo,_no,_wo,___,_ha,_ya,_si,_te,_ya,_ga,_ru,_cr,_ret
		.BYTE	_sa,_tt,_ki,___,_A_,_str,_MI,_str,_no,___,_TA,_KO,_ya,_ro,_u_,_ni,_ret
		.BYTE	_ma,_ki,_tu,_i_,_te,_i_,_ta,_ya,_tu,_da,_ze,_cr,_eol
_sc15_msg0C:
		.BYTE	_mi,_gi,_u_,_de,_ha,___,_se,_tu,_da,_n_,_sa,_re,_ta,_n_,_zi,_yy,___,_na,_ka,_ta,_tt,_ke,_qe,_ret
		.BYTE	_dot,_dot,_dot,_u_,_ma,_ku,___,_ne,_ra,_e_,_ne,$89,_ka,_qe,_eol
_sc15_msg0D:
		.BYTE	_so,_u_,_da,_dot,_dot,_dot,___,_KE,_I_,_ka,_ra,___,_wa,_ta,_sa,_re,_ta,___,_ka,_ga,_mi,_ga,_ret
		.BYTE	_a_,_tt,_ta,_ha,_zu,_da,_cr,_eol
_sc15_msg0E:
		.BYTE	_O_,_RE,_ha,___,_te_tsu__o_,_no,_yo,_ko,_he,___,_ka,_ga,_mi,_wo,___,_na,_ge,_ta,_cr,_eol
_sc15_msg0F:
		.BYTE	_O_,_RE,_ha,___,_na,_ge,_tu,_ke,_ta,_ka,_ga,_mi,_wo,___,_to,_ri,_ni,_i_,_tt,_ta,_cr,_eol
_sc15_msg10:
		.BYTE	_ka,_ga,_mi,_ni,___,_ha,_n_,_si,_yy,_si,_ta,___,_RE,_str,_ZA,_str,_ha,___,_te_tsu__o_,_no,_ka,_ra,_da,_wo,_ret
		.BYTE	_ha,_zu,_re,_ta,_ex,_eol
_sc15_msg11:
		.BYTE	_ba,_ke,_mo,_no,_ni,___,_ka,_wa,_tt,_te,_si,_ma,_tt,_ta,_te_tsu__o_,_ha,___,_ku,_ru,_si,_so,_u_,_ni,_ret
		.BYTE	_u_,_me,_i_,_te,_i_,_ta,_cr,_eol
_sc15_msg12:
		.BYTE	_KI,_UU,_KI,_str,_N_,_ex,_ret
		.BYTE	_RE,_str,_ZA,_str,_ga,___,_ka,_ga,_mi,_ni,_a_,_ta,_tt,_te,___,_ha,_n_,_si,_yy,_si,_ta,_cr,_eol
_sc15_msg13:
		.BYTE	_RE,_str,_ZA,_str,_ga,___,_te_tsu__o_,_ni,___,_ka,_wa,_sa,_re,_ta,_ex,_eol
_sc15_msg14:
		.BYTE	_ba,_ke,_mo,_no,_ni,___,_ka,_wa,_tt,_te,_si,_ma,_tt,_ta,_te_tsu__o_,_ni,___,_O_,_RE,_ha,_ret
		.BYTE	_o_,_mo,_wa,_zu,___,_RE,_str,_ZA,_str,_wo,___,_bu,_tt,_pa,_na,_si,_te,_i_,_ta,_cr,_eol
_sc15_msg15:
		.BYTE	_te_tsu__o_,_no,_ze,_n_,_si,_n_,_ga,___,_bu,_ki,_mi,_na,___,_ni,_ku,_no,_ka,_ta,_ma,_ri,_ni,_ret
		.BYTE	_na,_ro,_u_,_to,___,_si,_te,_i_,_ta,_cr,_eol
_sc15_msg16:
		.BYTE	_si,_ka,_si,___,_te_tsu__o_,_ha,___,_ta,_o_,_re,_ta,___,_ha,_n_,_do,_u_,_de,_ret
		.BYTE	_to,_bi,_a_,_ga,_tt,_ta,_cr,_ret
		.BYTE	_te_tsu__o_,_ha,___,_ku,_u_,_ti,_uu,_u_,_ni,___,_te,_i_,_si,_si,_ta,_a_,_to,___,_ki,_uu,_u_,_ko,_u_,_ka,_ret
		.BYTE	_si,_te,_ki,_ta,_cr,_eol
_sc15_msg17:
		.BYTE	_O_,_RE,_ha,___,_HU,_RU,_A_,_KU,_SE,_RU,_de,___,_BA,_TT,_KU,_si,_te,_ret
		.BYTE	_GA,_RE,_KI,_no,_ya,_ma,_wo,___,_no,_bo,_tt,_ta,_cr,_eol
_sc15_msg18:
		.BYTE	_te_tsu__o_,_ha,___,_O_,_RE,_ga,___,_i_,_ta,_a_,_ta,_ri,_wo,___,_ka,_ra,_da,_go,_to,_ret
		.BYTE	_ti,_oo,_ku,_ge,_ki,_si,_ta,_cr,_ret
		.BYTE	_SU,_TA,_ZI,_A_,_MU,_no,_yu,_ka,_ga,___,_me,_ku,_re,_a_,_ga,_tt,_ta,_cr,_eol
_sc15_msg19:
		.BYTE	_O_,_RE,_ha,___,_GA,_RE,_KI,_no,_to,_ti,_uu,_u_,_de,___,_BU,_RE,_str,_KI,_wo,___,_ka,_ke,_ta,_cr,_eol
_sc15_msg1A:
		.BYTE	_si,_ka,_si,___,_te_tsu__o_,_ha,___,_ki,_uu,_u_,_ni,___,_ta,_o_,_re,_ru,_to,_ret
		.BYTE	_mo,_ga,_ki,_ha,_zi,_me,_ta,_cr,_eol
_sc15_msg1B:
		.BYTE	_te_tsu__o_,_ha,___,_ba,_ke,_mo,_no,_ni,___,_he,_n_,_ke,_i_,_si,_yo,_u_,_to,___,_si,_te,_i_,_ta,_cr,_ret
		.BYTE	_tu,_i_,_ni,___,_te_tsu__o_,_ha,___,_bo,_u_,_ti,_oo,_u_,_su,_ru,___,_E_,_NE,_RU,_GI,_str,_wo,_ret
		.BYTE	_o_,_sa,_e_,_ki,_re,_na,_ku,_na,_tt,_ta,_no,_da,_tt,_ta,_cr,_eol
_sc15_msg1C:
		.BYTE	_ki,_n_,_ni,_ku,_ga,___,_i_,_yo,_u_,_ni,___,_mo,_ri,_a_,_ga,_ri,_col,___,_hi,_hu,_wo,_ret
		.BYTE	_tu,_ki,_ya,_bu,_tt,_te,_i_,_ta,_cr,_eol
_sc15_msg1D:
		.BYTE	_______,_te_tsu__o_,_lt,_an0,_ka__ne__da,_AA,_dot,_dot,_dot,___,_ta,_tt,___,_ta,_su,_ke,_te,_dot,_dot,_dot,_ret
		.BYTE	_______________________,_ku,_re,_dot,_dot,_dot,_dot,_dot,_dot,_aof,_eol
_sc15_msg1E:
		.BYTE	_te_tsu__o_,_ha,___,_hi,_ka,_ri,_ni,___,_no,_mi,_ko,_ma,_re,_ka,_ke,_te,_i_,_ta,_cr,_ret
		.BYTE	_O_,_RE,_ha,___,_te_tsu__o_,_ni,_mu,_ka,_tt,_te,___,_ka,_ke,_da,_si,_ta,_cr,_eol
_sc15_msg1F:
		.BYTE	_O_,_RE,_ha,___,_TA,_KO,_ya,_ro,_u_,_ni,___,_ma,_ki,_tu,_i_,_te,_i_,_ru,___,_ka,_ta,_ma,_ri,_wo,_ret
		.BYTE	_RE,_str,_ZA,_str,_de,___,_u_,_ti,_nu,_i_,_ta,_cr,_eol
_sc15_msg20:
		.BYTE	_RE,_str,_ZA,_str,_ga,___,_HI,_TT,_TO,_si,_ta,___,_mi,_gi,_u_,_de,_no,_a_,_ta,_ri,_ga,_ret
		.BYTE	_i_,_yo,_u_,_ni,___,_hu,_ku,_ra,_n_,_de,_i_,_ta,_cr,_eol
_sc15_msg21:
		.BYTE	_______,_ka__ne__da,_lt,_ya,_me,_ro,_str,_TT,___,_u_,_wa,_str,_tt,_cr,_ret
		.BYTE	_ni,_ku,_no,_ka,_ta,_ma,_ri,_ka,_ra,___,_si,_oo,_ku,_si,_ga,___,_no,_bi,_te,_ki,_ta,_cr,_ret
		.BYTE	_O_,_RE,_ha,___,_si,_oo,_ku,_si,_ni,___,_tu,_ka,_ma,_ri,___,_to,_ri,_ko,_ma,_re,_te,_si,_ma,_tt,_ta,_cr,_eol
_sc15_msg22:
		.BYTE	_O_,_RE,_ha,___,_ka,_ta,_ma,_ri,_no,_na,_ka,_de,___,_te_tsu__o_,_no,___,_u_,_me,_ki,_go,_e_,_wo,_ret
		.BYTE	_ki,_i_,_ta,_cr,_eol
_sc15_msg23:
		.BYTE	_______,_te_tsu__o_,_lt,_an0,_ka,_ra,_da,_ga,_dot,_dot,_dot,___,_i_,_u_,_ko,_to,_wo,_dot,_dot,_dot,_ret
		.BYTE	_______________________,_ti,_ka,_ra,_ga,___,_ka,_tt,_te,_ni,_dot,_dot,_dot,_aof,_eol
_sc15_msg24:
		.BYTE	_ya,_ga,_te,___,_yu,_ka,_ni,_na,_ga,_re,_ta,___,_YO,_U_,_SU,_I_,_ga,___,_hu,_tt,_to,_u_,_si,_col,_ret
		.BYTE	_hi,_ka,_ri,_ha,_zi,_me,_ta,_cr,_eol
_sc15_msg25:
		.BYTE	_SA,_N_,_PU,_RU,_KE,_str,_SU,_ni,___,_hi,_bi,_ga,_ha,_i_,_ri,_col,___,_na,_ka,_ka,_ra,_ret
		.BYTE	_YO,_U_,_SU,_I_,_ga,___,_hu,_ki,_ko,_bo,_re,_te,_ki,_ta,_cr,_eol
_sc15_msg27:
		.BYTE	_______,_MA,_SA,_RU,_lt,_an0,_ya,_a_,_dot,_dot,_dot,___,_A_,_KI,_RA,_ku,_n_,_dot,_dot,_dot,_aof,_eol
_sc15_msg29:
		.BYTE	_hi,_ka,_ri,_ha,___,_A_,_KI,_RA,_no,_ze,_n_,_si,_n_,_ka,_ra,___,_ha,_tt,_se,_ra,_re,_te,_i_,_ta,_cr,_ret
		.BYTE	_so,_si,_te,___,_hi,_ka,_ri,_ha,___,_ma,_su,_ma,_su,___,_hi,_ro,_ga,_ri,_col,___,_3,_ni,_n_,_wo,_ret
		.BYTE	_tu,_tu,_mi,_ha,_zi,_me,_ta,_cr,_eol
_sc15_msg2A:
		.BYTE	_______,_KI,_YO,_KO,_lt,_de,_mo,_dot,_dot,_dot,___,_3,_ni,_n_,_de,_ya,_re,_ba,_col,_ret
		.BYTE	_______________________,_a_,_no,_hi,_to,_da,_ke,_de,_mo,_dot,_dot,_dot,_ret
		.BYTE	_______,_MA,_SA,_RU,_lt,_so,_u_,_da,_ne,_dot,_dot,_dot,___,_3,_ni,_n_,_na,_ra,_dot,_dot,_dot,_eol
_sc15_msg2B:
		.BYTE	_O_,_RE,_ha,___,_2,_ha,_tu,_me,_wo,___,_ki,_me,_yo,_u_,_to,_col,___,_RE,_str,_ZA,_str,_wo,_ret
		.BYTE	_ka,_ta,_ni,___,_o_,_i_,_ta,_cr,_eol
_sc15_msg2D:
		.BYTE	_si,_ka,_si,___,_O_,_RE,_no,_te,_wo,___,_GA,_KI,_ga,___,_tu,_ka,_n_,_da,_cr,_ret
		.BYTE	_______,_TA,_KA,_SI,_lt,_i_,_tt,_ti,_yy,_col,___,_da,_me,_da,_ex,_ret
		.BYTE	_______________________,_i_,_ma,___,_i_,_tt,_ta,_ra,_col,___,_de,_ra,_re,_na,_ku,_na,_ru,_yo,_cr,_eol
_sc15_msg33:
		.BYTE	_O_,_RE,_ha,___,_GA,_KI,_no,_te,_wo,___,_hu,_ri,_ha,_na,_si,_col,___,_hi,_ka,_ri,_ni,_mu,_ka,_tt,_te,_ret
		.BYTE	_ha,_si,_tt,_ta,_cr,_eol
_sc15_msg34:
		.BYTE	_O_,_RE,_ha,___,_GA,_KI,_to,_i_,_tt,_si,_oo,_ni,___,_te_tsu__o_,_ka,_ra,___,_ni,_ge,_ta,_cr,_eol
_sc15_msg35:
		.BYTE	_O_,_RE,_ha,___,_GA,_KI,_wo,___,_na,_gu,_ri,_ta,_o_,_si,_col,___,_hi,_ka,_ri,_ni,_mu,_ka,_tt,_te,_ret
		.BYTE	_ha,_si,_tt,_ta,_cr,_eol
_sc15_msg36:
		.BYTE	_O_,_RE,_ga,___,_hi,_ka,_ri,_ni,___,_no,_mi,_ko,_ma,_re,_ka,_ke,_ta,_to,_ki,_col,___,_sa,_tt,_ki,_no,_ret
		.BYTE	_GA,_KI,_ga,___,_ha,_si,_tt,_te,_ku,_ru,_no,_ga,___,_mi,_e_,_ta,_cr,_ret
		.BYTE	_______,_TA,_KA,_SI,_lt,_a_,_no,_hi,_to,_ha,___,_ka,_n_,_ke,_i_,_na,_i_,_n_,_da,_ex,_eol
_sc15_msg37:
		.BYTE	_GA,_KI,_ha,___,_hi,_ka,_ri,_no,_na,_ka,_ni,___,_to,_bi,_ko,_n_,_da,_cr,_ret
		.BYTE	_______,_MA,_SA,_RU,_lt,_TA,_KA,_SI,_II,_str,_TT,_cr,_ret
		.BYTE	_______,_KI,_YO,_KO,_lt,_TA,_KA,_SI,_ku,_str,_n_,_cr,_eol
_sc15_msg38:
		.BYTE	_______,_MA,_SA,_RU,_lt,_dot,_dot,_dot,_na,_ka,_ni,___,_ha,_i_,_tt,_ta,_ra,_col,___,_mo,_u_,_ret
		.BYTE	_______________________,_bo,_ku,_ra,_no,_ti,_ka,_ra,_zi,_yy,___,_de,_te,_ko,_re,_na,_i_,_yo,_cr,_eol
_sc15_msg9D:
		.BYTE	_______,_te_tsu__o_,_lt,_an1,_ka,_col,___,_ka__ne__da,_AA,_qe,_ex,_aof,_eol
_sc15_msgAC:
		.BYTE	_RE,_str,_ZA,_str,_ga,___,_te_tsu__o_,_no,_mi,_gi,_u_,_de,_ni,___,_HI,_TT,_TO,_si,_ta,_ex,_eol

		SECTION_END		F15
