
		SECTION_START	F14

		MSG_START	_scene14_msg_lib
		MSG_IDX	_sc14_msg00
		MSG_IDX	_sc14_msg01
		MSG_IDX	_sc14_msg02
		MSG_IDX	_sc14_msg03
		MSG_IDX	_sc14_msg04
		MSG_IDX	_sc14_msg05
		MSG_IDX	_sc14_msg06
		MSG_IDX	_sc14_msg07
		MSG_IDX	_sc14_msg08
		MSG_IDX	_sc14_msg09
		MSG_IDX	_sc14_msg0A
		MSG_IDX	_sc14_msg0B
		MSG_IDX	_sc14_msg0C
		MSG_IDX	_sc14_msg0D
		MSG_IDX	_sc14_msg0E
		MSG_IDX	_sc14_msg0F
		MSG_IDX	_sc14_msg10
		MSG_IDX	_sc14_msg11
		MSG_IDX	_sc14_msg12
		MSG_IDX	_sc14_msg13
		MSG_IDX	_sc14_msg14
_sc14_msg00:
		.BYTE	_ko,_u_,_so,_ku,_do,_u_,_ro,_no,___,_si,_yo,_u_,_sa,_re,_te,_i_,_na,_i_,___,_ri,_oo,_u_,_ki,_n_,_zi,_oo,_ret
		.BYTE	_ti,_ka,_ku,_de,___,_hi,_to,_i_,_ki,___,_tu,_i_,_te,_i_,_ta,_cr,_ret
		.BYTE	_to,_tt,_ku,_ni,___,_yo,_ru,_ni,___,_na,_tt,_te,_si,_ma,_tt,_te,_i_,_ta,_dot,_dot,_dot,_eol
_sc14_msg01:
		.BYTE	_______,_ka__ne__da,_lt,_KE,_I_,_TT,___,_ho,_si,_zo,_ra,_ga,___,_ki,_re,_i_,_da,_yo,_str,_tt,_ex,_ret
		.BYTE	___________,_KE,_I_,_lt,_an0,_mo,_u_,_tt,___,_na,_ni,___,_i_,_tt,_te,_n_,_no,_yo,_cr,_aof,_eol
_sc14_msg02:
		.BYTE	_______,_ka__ne__da,_lt,_ku,_so,_tt,___,_ko,_no,_RE,_str,_ZA,_str,_BI,_str,_MU,_ret
		.BYTE	_______________________,_ka,_n_,_zi,_n_,_na,_to,_ki,_ni,___,_ki,_re,_ya,_ga,_tt,_te,_yo,_OO,_cr,_eol
_sc14_msg03:
		.BYTE	___________,_KE,_I_,_lt,_an0,_ki,_ze,_tu,_si,_te,_i_,_ta,_mi,_ta,_i_,_de,_dot,_dot,_dot,___,_me,_za,_me,_ta,_ra,_ret
		.BYTE	_______________________,_GA,_RE,_KI,_no,_ya,_ma,_de,___,_ho,_ko,_ri,_da,_ra,_ke,_ni,_ret
		.BYTE	_______________________,_na,_tt,_te,_i_,_ta,_wa,_dot,_dot,_dot,_aof,_ret
		.BYTE	_______,_ka__ne__da,_lt,_a_,_no,_GA,_KI,_do,_mo,_ni,___,_a_,_ya,_tu,_ra,_re,_te,_i_,_ta,_n_,_da,_ze,_cr,_ret
		.BYTE	_______________________,_ki,_tt,_to,_dot,_dot,_dot,_eol
_sc14_msg04:
		.BYTE	___________,_KE,_I_,_lt,_an0,_de,_mo,___,_na,_ni,_mo,___,_o_,_bo,_e_,_te,_na,_i_,_no,_yo,_cr,_ret
		.BYTE	_______________________,_ka,_i_,_ku,_n_,_ga,___,_ki,_te,_ku,_re,_na,_ka,_tt,_ta,_ra,_dot,_dot,_dot,_aof,_eol
_sc14_msg05:
		.BYTE	___________,_KE,_I_,_lt,_an0,_a_,_na,_ta,_zi,_yy,___,_ka,_ti,_me,_ha,_na,_i_,_wa,_yo,_cr,_aof,_ret
		.BYTE	_______,_ka__ne__da,_lt,_da,_me,_da,_tt,_cr,___,_te_tsu__o_,_no,_ya,_tu,_ha,___,_O_,_RE,_no,_te,_de,_ret
		.BYTE	_______________________,_si,_ma,_tu,_wo,___,_tu,_ke,_te,_ya,_ru,_tt,_cr,_eol
_sc14_msg06:
		.BYTE	___________,_KE,_I_,_lt,_an0,_a_,_bu,_na,_ka,_tt,_ta,_WA,_col,___,_ko,_ro,_n_,_da,_to,_ki,_ha,_ret
		.BYTE	_______________________,_da,_me,_da,_tt,_te,___,_o_,_mo,_tt,_ta,_ke,_do,_cr,_aof,_eol
_sc14_msg07:
		.BYTE	___________,_ka,_i_,_lt,_i_,_tu,_no,_ma,_ni,___,_a_,_n_,_na,_ti,_ka,_ra,_wo,_dot,_dot,_dot,_ret
		.BYTE	_______________________,_ka__ne__da,_AA,_col,___,_ya,_ma,_ga,_ta,_no,_ret
		.BYTE	_______________________,_o_,_to,_si,_ma,_e_,_na,_n_,_te,___,_tu,_ke,_ra,_re,_ru,_no,_ka,_yo,_OO,_cr,_eol
_sc14_msg08:
		.BYTE	___________,_ka,_i_,_lt,_O_,_RE,_ga,___,_ta,_su,_ke,_na,_ki,_yy,_col,___,_a_,_bu,_na,_ka,_tt,_ta,_ze,_cr,_ret
		.BYTE	_______,_ka__ne__da,_lt,_wa,_ka,_AA,_str,_ta,_tt,_te,_cr,_eol
_sc14_msg09:
		.BYTE	___________,_ka,_i_,_lt,_o_,_i_,___,_ka__ne__da,_col,___,_BA,_I_,_KU,_de,___,_RE,_str,_ZA,_str,_no,_ret
		.BYTE	_______________________,_BA,_TT,_TE,_RI,_str,_no,___,_zi,_uu,_u_,_de,_n_,_ga,___,_de,_ki,_ru,_n_,_zi,_yy,_ret
		.BYTE	_______________________,_ne,_e_,_no,_ka,_AA,_cr,_eol
_sc14_msg0A:
		.BYTE	___________,_ka,_i_,_lt,_ka__ne__da,_col,___,_zi,_uu,_u_,_de,_n_,_na,_ra,___,_ma,_ka,_si,_to,_ke,_yo,_cr,_eol
_sc14_msg0B:
		.BYTE	___________,_ka,_i_,_lt,_dot,_dot,_dot,_u_,_wa,_AA,_cr,_ret
		.BYTE	_______________________,_ti,_ki,_si,_oo,_u_,_ex,___,_ya,_tt,_ti,_ma,_tt,_ta,_ex,_ret
		.BYTE	_______,_ka__ne__da,_lt,_BA,_TT,_TE,_RI,_str,___,_BA,_TT,_TE,_RI,_str,_cr,_eol
_sc14_msg0C:
		.BYTE	_______,_ka__ne__da,_lt,_na,_n_,_de,$89,___,_BA,_I_,_KU,_no,_hi,_to,_tu,_ya,___,_hu,_ta,_tu,_yo,_o_,_cr,_ret
		.BYTE	___________,_ka,_i_,_lt,_na,_ni,_str,_tt,___,_na,_ra,_col,___,_zi,_bu,_n_,_no,_BA,_I_,_KU,_de,_ret
		.BYTE	_______________________,_ya,_tt,_ta,_ra,___,_i_,_i_,_da,_ro,_OO,_cr,_eol
_sc14_msg0D:
		.BYTE	_______,_ka__ne__da,_lt,_a_,_col,___,_HO,_RA,_col,___,_BA,_I_,_KU,___,_ma,_da,_ret
		.BYTE	_______________________,_mo,_e_,_te,_ru,_tt,_te,_dot,_dot,_dot,_ret
		.BYTE	___________,_ka,_i_,_lt,_WA,_AA,_dot,_dot,_dot,_dot,_dot,_dot,_ret
		.BYTE	_______,_ka__ne__da,_lt,_HA,_TT,_HA,_TT,_HA,_TT,_dot,_dot,_dot,_eol
_sc14_msg0E:
		.BYTE	_te_tsu__o_,_no,_ya,_tu,_col,_ma,_da,___,_a_,_no,_GA,_RE,_KI,_no,_ya,_ma,_de,_ret
		.BYTE	_BO,_SU,_wo,___,_ki,_do,_tt,_te,_ya,_ga,_ru,_ha,_zu,_da,_ze,_dot,_dot,_dot,_eol
_sc14_msg0F:
		.BYTE	_so,_re,_ma,_de,___,_O_,_RE,_ta,_ti,_no,_ko,_to,_wo,___,_zi,_tt,_to,___,_mi,_te,_i_,_ta,___,_KE,_I_,_ga,_ret
		.BYTE	_ku,_ti,_wo,_hi,_ra,_i_,_ta,_cr,_ret
		.BYTE	___________,_KE,_I_,_lt,_an0,_ko,_re,_col,___,_mo,_tt,_te,_tt,_te,_yo,_dot,_dot,_dot,_aof,_eol
_sc14_msg10:
		.BYTE	_O_,_RE,_ha,___,_mo,_u_,_i_,_ti,_do,___,_O_,_RI,_N_,_PI,_TT,_KU,_ka,_i_,_zi,_oo,_u_,_ret
		.BYTE	_yo,_te,_i_,_ti,_ni,___,_mu,_ka,_tt,_ta,_cr,_eol
_sc14_msg11:
		.BYTE	_KE,_I_,_ha,___,_ho,_no,_o_,_wo,___,_mi,_te,_i_,_ta,_cr,_eol
_sc14_msg12:
		.BYTE	___________,_ka,_i_,_lt,_O_,_RE,_no,_BA,_I_,_KU,_ga,_str,_col,___,_mo,_e_,_ti,_ma,_u_,_str,_tt,_cr,_eol
_sc14_msg13:
		.BYTE	_______,_ka__ne__da,_lt,_a_,_tt,___,_ki,_ko,_e_,_te,_ta,_dot,_dot,_dot,_ret
		.BYTE	___________,_ka,_i_,_lt,_ki,_ko,_e_,_te,_ru,_yo,_OO,_str,_cr,_eol
_sc14_msg14:
		.BYTE	_KE,_I_,_ha,___,_O_,_RE,_ni,___,_ka,_ga,_mi,_wo,___,_wa,_ta,_si,_ta,_cr,_ret
		.BYTE	_so,_i_,_tu,_ha,___,_yo,_ru,_na,_no,_ni,___,_ka,_ga,_ya,_i_,_te,_mi,_e_,_ta,_cr,_eol

		SECTION_END		F14
