
		SECTION_START	F12

		MSG_START	_scene12_msg_lib
		MSG_IDX	_sc12_msg00
		MSG_IDX	_sc12_msg01
		MSG_IDX	_sc12_msg02
		MSG_IDX	_sc12_msg03
		MSG_IDX	_sc12_msg04
		MSG_IDX	_sc12_msg05
		MSG_IDX	_sc12_msg06
		MSG_IDX	_sc12_msg07
		MSG_IDX	_sc12_msg08
		MSG_IDX	_sc12_msg09
		MSG_IDX	_sc12_msg0A
		MSG_IDX	_sc12_msg0B
		MSG_IDX	_sc12_msg0C
		MSG_IDX	_sc12_msg0D
		MSG_IDX	_sc12_msg0E
		MSG_IDX	_sc12_msg0F
		MSG_IDX	_sc12_msg10
		MSG_IDX	_sc12_msg11
		MSG_IDX	_sc12_msg12
		MSG_IDX	_sc12_msg13
		MSG_IDX	_sc12_msg14
		MSG_IDX	_sc12_msg15
		MSG_IDX	_sc12_msg16
		MSG_IDX	_sc12_msg17
		MSG_IDX	_sc12_msg18
		MSG_IDX	_sc12_msg19
		MSG_IDX	_sc12_msg1A
		MSG_IDX	_sc12_msg1B
		MSG_IDX	_sc12_msg1C
		MSG_IDX	_sc12_msg1D
		MSG_IDX	_sc12_msg1E
		MSG_IDX	_sc12_msg1F
		MSG_IDX	_sc12_msg20
		MSG_IDX	_sc12_msg21
		MSG_IDX	_sc12_msg22
		MSG_IDX	_sc12_msg23
		MSG_IDX	_sc12_msg24
		MSG_IDX	_sc12_msg25
		MSG_IDX	_sc12_msg26
		MSG_IDX	_sc12_msg27
		MSG_IDX	_sc12_msg28
		MSG_IDX	_sc12_msg29
;		MSG_IDX	_sc12_msg2A						; _sc13_msg2A alt version
;		MSG_IDX	_sc12_msg2B						; _sc13_msg2B alt version
;		MSG_IDX	_sc12_msg2C						; -unused-
;		MSG_IDX	_sc12_msg2D						; -unused-
;		MSG_IDX	_sc12_msg2E						; -unused-
_sc12_msg00:
		.BYTE	_O_,_RE,_ha,___,_de,_n_,_ki,_ya,_no,_ma,_e_,_wo,___,_to,_o_,_ri,_ka,_ka,_tt,_ta,_cr,_ret
		.BYTE	_MO,_NI,_TA,_str,_ha,___,_A_,_str,_MI,_str,_no,_HE,_RI,_to,___,_TE,_RE,_BI,_no,_RE,_PO,_str,_TA,_str,_wo,_ret
		.BYTE	_u_,_tu,_si,_da,_si,_te,_i_,_ta,_ze,_cr,_eol
_sc12_msg01:
		.BYTE	_RE,_PO,_str,_TA,_str,_lt,_an0,_i_,_ma,___,_ko,_no,_NE,_O_,_to,_u_,_ki,_oo,_u_,_de,_ha,_ret
		.BYTE	_______________________,_na,_ni,_ga,___,_o_,_ko,_tt,_te,_i_,_ru,_no,_de,_si,_oo,_u_,_ka,_qe,_ret
		.BYTE	_______________________,_go,_ra,_n_,_no,_e_,_i_,_zo,_u_,_ha,_ret
		.BYTE	_______________________,_se,_n_,_si,_yy,_ni,_yo,_ru,___,_ka,_sa,_i_,_no,_mo,_yo,_u_,_de,_su,_cr,_aof,_eol
_sc12_msg02:
		.BYTE	_RE,_PO,_str,_TA,_str,_lt,_an0,_so,_si,_te,_dot,_dot,_dot,___,_ko,_no,_si,_oo,_u_,_ne,_n_,_ha,___,_i_,_tt,_ta,_i_,_ret
		.BYTE	_______________________,_na,_ni,_mo,_no,_de,_si,_oo,_u_,_ka,_qe,_ret
		.BYTE	_______________________,_ta,_tt,_ta,_hi,_to,_ri,_de,___,_KU,_str,_DE,_TA,_str,_gu,_n_,_to,_ret
		.BYTE	_______________________,_ta,_ta,_ka,_tt,_te,_i_,_ru,_no,_de,___,_a_,_ri,_ma,_si,_oo,_u_,_ka,_qe,_aof,_eol
_sc12_msg03:
		.BYTE	_RE,_PO,_str,_TA,_str,_lt,_an0,_mi,_na,_sa,_ma,___,_ta,_da,_i_,_ma,___,_gu,_n_,_yo,_ri,___,_ki,_oo,_u_,_ko,_u_,_ret
		.BYTE	_______________________,_ti,_yy,_ku,_ri,_ku,_se,_yo,_col,_to,_no,___,_hu,_to,_u_,_me,_i_,_re,_i_,_ga,_ret
		.BYTE	_______________________,_wa,_re,_wa,_re,_ni,_mu,_ke,_te,___,_ha,_tt,_se,_ra,_re,_ta,_no,_de,_su,_cr,_ret
		.BYTE	_______________________,_ho,_u_,_do,_u_,_no,_zi,_yu,_u_,_ga,___,_i_,_ma,_ret
		.BYTE	_______________________,_hu,_mi,_ni,_zi,_ra,_re,_yo,_u_,_to,___,_si,_te,_i_,_ma,_su,_ex,_aof,_eol
_sc12_msg04:
		.BYTE	___________________,_lt,_ha,_si,_da,_col,___,_ha,_si,_ni,___,_mu,_ka,_tt,_ta,_zo,_OO,_cr,_ret
		.BYTE	___________________,_lt,_gu,_n_,_ta,_i_,_mo,___,_de,_te,_ru,_zo,_cr,_ret
		.BYTE	___________________,_lt,_ha,_si,_no,_mu,_ko,_u_,_ha,___,_O_,_RI,_N_,_PI,_TT,_KU,_ka,_i_,_zi,_oo,_u_,_ret
		.BYTE	_______________________,_yo,_te,_i_,_ti,_da,_zo,_OO,_cr,_eol
_sc12_msg05:
		.BYTE	_ya,_zi,_u_,_ma,_ta,_ti,_ha,___,_ku,_ti,_gu,_ti,_ni,___,_ha,_na,_su,_to,_col,___,_ZO,_RO,_ZO,_RO,_to,_ret
		.BYTE	_a_,_ru,_ki,_da,_si,_ta,_cr,_eol
_sc12_msg06:
		.BYTE	_O_,_RE,_ha,___,_ga,_tt,_ko,_u_,_no,___,_BA,_I_,_KU,_o_,_ki,_ba,_ni,___,_ya,_tt,_te,_ki,_ta,_ze,_cr,_eol
_sc12_msg07:
		.BYTE	___________,_ka,_i_,_lt,_ho,_n_,_to,_u_,_ni,___,_hi,_to,_ri,_de,___,_i_,_ku,_no,_ka,_yo,_OO,_cr,_eol
_sc12_msg08:
		.BYTE	___________,_ka,_i_,_lt,_ka__ne__da,_AA,___,_do,_ko,_ni,___,_i_,_ku,_tu,_mo,_ri,_da,_yo,_cr,_ret
		.BYTE	_______________________,_ya,_ma,_ga,_ta,_no,___,_hu,_ku,_si,_uu,_u_,_tu,_tt,_ta,_tt,_te,_col,_ret
		.BYTE	_______________________,_do,_ko,_ni,___,_te_tsu__o_,_ga,___,_i_,_ru,_no,_ka,_ret
		.BYTE	_______________________,_wa,_ka,_n_,_na,_i_,_da,_ro,_cr,_eol
_sc12_msg09:
		.BYTE	_O_,_RE,_ha,___,_O_,_RI,_N_,_PI,_TT,_KU,_ka,_i_,_zi,_oo,_u_,___,_yo,_te,_i_,_ti,_ni,_ret
		.BYTE	_mu,_ka,_tt,_ta,_cr,_eol
_sc12_msg0A:
		.BYTE	_O_,_RE,_ha,___,_ko,_u_,_so,_ku,_do,_u_,_ro,_de,___,_te_tsu__o_,_ni,___,_ya,_ra,_re,_ta,_ret
		.BYTE	_A_,_str,_MI,_str,_no,_se,_n_,_si,_yy,_no,___,_za,_n_,_ga,_i_,_wo,___,_mi,_tu,_ke,_ta,_cr,_eol
_sc12_msg0B:
		.BYTE	_______,_mu,_se,_n_,_lt,_ZI,_TT,_KE,_N_,_TA,_I_,_ha,___,_ki,_uu,_u_,_si,_ga,_i_,_ret
		.BYTE	_______________________,_O_,_RI,_N_,_PI,_TT,_KU,_ke,_n_,_se,_tu,_ge,_n_,_ba,_no,___,_mi,_na,_mi,_ga,_wa,_ret
		.BYTE	_______________________,_2,_KI,_RO,_no,___,_ti,_te,_n_,_ni,___,_to,_u_,_ta,_tu,_TT,_ex,_ret
		.BYTE	_______________________,_wa,_ga,_ta,_i_,_ha,___,_ho,_bo,___,_ka,_i_,_me,_tu,_zi,_oo,_u_,_ta,_i_,_de,_ret
		.BYTE	_______________________,_a_,_ri,_ma,_su,_dot,_dot,_dot,_eol
_sc12_msg0C:
		.BYTE	_te_tsu__o_,_no,___,_si,_oo,_u_,_ge,_ki,_ha,_de,___,_ya,_ra,_re,_ta,_mi,_ta,_i_,_da,_tt,_ta,_ze,_cr,_ret
		.BYTE	_na,_n_,_ni,_n_,_mo,_no,___,_A_,_str,_MI,_str,_no,_si,_ta,_i_,_ga,___,_se,_n_,_si,_yy,_no,_na,_ka,_ni,_ret
		.BYTE	_ko,_ro,_ga,_tt,_te,_i_,_ta,_cr,_eol
_sc12_msg0D:
		.BYTE	_HA,_N_,_DO,_TA,_I_,_PU,_no,___,_RE,_str,_ZA,_str,_BI,_str,_MU,_da,_cr,_eol
_sc12_msg0E:
		.BYTE	_______,_ka__ne__da,_lt,_ko,_i_,_tu,_de,___,_te_tsu__o_,_no,_ya,_tu,_col,_ret
		.BYTE	_______________________,_bu,_ti,_no,_me,_si,_te,_ya,_ru,_ex,_eol
_sc12_msg0F:
		.BYTE	_ka,_i_,_me,_tu,_si,_ta,___,_RE,_str,_ZA,_str,_ho,_u_,_bu,_ta,_i_,_da,_cr,_eol
_sc12_msg10:
		.BYTE	_O_,_RI,_N_,_PI,_TT,_KU,_ka,_i_,_zi,_oo,_u_,___,_yo,_te,_i_,_ti,_ma,_de,___,_a_,_to,_su,_ko,_si,_da,_cr,_eol
_sc12_msg11:
		.BYTE	_O_,_RI,_N_,_PI,_TT,_KU,_ka,_i_,_zi,_oo,_u_,___,_yo,_te,_i_,_ti,_no,_yo,_ko,_no,___,_A_,_str,_MI,_str,_no,_ret
		.BYTE	_hi,_mi,_tu,_ki,_ti,_cr,_eol
_sc12_msg12:
		.BYTE	_so,_si,_te,___,_so,_no,_ki,_oo,_da,_i_,_na,___,_re,_i_,_to,_u_,_KA,_PU,_SE,_RU,_no,___,_u_,_e_,_de,_ha,_ret
		.BYTE	_te_tsu__o_,_to,___,_KE,_I_,_ga,___,_ta,_i_,_ke,_tu,_si,_te,_i_,_ta,_cr,_eol
_sc12_msg13:
		.BYTE	_______,_te_tsu__o_,_lt,_an0,_o_,_ma,_e_,_ha,___,_ka__ne__da,_to,___,_i_,_tt,_si,_oo,_ni,_i_,_ta,_dot,_dot,_dot,_aof,_eol
_sc12_msg14:
		.BYTE	___________,_KE,_I_,_lt,_ya,_ga,_te,_ha,___,_zi,_bu,_n_,_de,___,_so,_no,_ti,_ka,_ra,_wo,_ret
		.BYTE	_______________________,_o_,_sa,_e_,_ra,_re,_na,_ku,_na,_ru,_dot,_dot,_dot,_eol
_sc12_msg15:
		.BYTE	_re,_i_,_ki,_ga,___,_hu,_ki,_a_,_ge,_ru,_na,_ka,_de,___,_hu,_ta,_ri,_ha,___,_si,_oo,_u_,_ge,_ki,_ha,_wo,_ret
		.BYTE	_to,_ba,_si,_ta,_ex,_ret
		.BYTE	_si,_oo,_u_,_ge,_ki,_ha,_ga,___,_SU,_PA,_str,_KU,_si,_ta,_cr,_eol
_sc12_msg16:
		.BYTE	_ka,_ra,_da,_ka,_ra,___,_O_,_str,_RA,_wo,___,_ha,_tt,_si,_na,_ga,_ra,___,_ra,_tt,_ka,_ret
		.BYTE	_si,_te,_i_,_ku,___,_KE,_I_,_cr,_eol
_sc12_msg17:
		.BYTE	_KA,_PU,_SE,_RU,_no,___,_za,_n_,_ga,_i_,_ga,___,_mi,_e_,_te,_ki,_ta,_cr,_ret
		.BYTE	_so,_ko,_ni,_ha,___,_ti,_uu,_u_,_si,_n_,_ki,_uu,_u_,_ga,___,_ko,_ro,_ga,_tt,_te,_i_,_ta,_cr,_eol
_sc12_msg18:
		.BYTE	_te_tsu__o_,_no,___,_si,_oo,_u_,_ge,_ki,_ha,_ni,_yo,_tt,_te,___,_ti,_uu,_u_,_si,_n_,_ki,_uu,_u_,_no,_ret
		.BYTE	_na,_ka,_ka,_ra,___,_SA,_N_,_PU,_RU,_KE,_str,_SU,_ga,___,_de,_te,_ki,_ta,_cr,_ret
		.BYTE	_______,_te_tsu__o_,_lt,_na,_n_,_da,_col,___,_ko,_re,_ha,_qe,_eol
_sc12_msg19:
		.BYTE	_______,_ta,_i_,_sa,_lt,_so,_re,_ga,___,_A_,_KI,_RA,_da,_dot,_dot,_dot,_ret
		.BYTE	_______________________,_o_,_ma,_e_,_no,___,_a_,_i_,_ta,_ga,_tt,_te,_i_,_ta,___,_A_,_KI,_RA,_da,_ex,_eol
_sc12_msg1A:
		.BYTE	_______,_ta,_i_,_sa,_lt,_ka,_ko,_no,___,_ti,_oo,_u_,_ze,_tu,_te,_ki,_na,___,_me,_za,_me,_no,_a_,_to,_ret
		.BYTE	_______________________,_so,_no,_ka,_ra,_da,_ha,___,_a_,_ri,_to,_a_,_ra,_yu,_ru,___,_gi,_zi,_uu,_tu,_de,_ret
		.BYTE	_______________________,_ti,_oo,_u_,_sa,_zi,_tt,_ke,_n_,_wo,___,_u_,_ke,_ta,_cr,_eol
_sc12_msg1B:
		.BYTE	_______,_ta,_i_,_sa,_lt,_to,_u_,_zi,_no,___,_ka,_ga,_ku,_si,_yy,_ha,___,_so,_no,_na,_zo,_wo,_ret
		.BYTE	_______________________,_to,_ku,_ko,_to,_ga,___,_de,_ki,_zu,_col,___,_a_,_tu,_me,_ta,_DE,_str,_TA,_to,_ret
		.BYTE	_______________________,_zi,_tt,_ke,_n_,_SA,_N_,_PU,_RU,_wo,___,_ko,_u_,_se,_i_,_ni,_ret
		.BYTE	_______________________,_ta,_ku,_su,_ta,_me,_col,___,_re,_i_,_to,_u_,_KA,_PU,_SE,_RU,_ni,___,_ho,_zo,_n_,_ret
		.BYTE	_______________________,_su,_ru,_ko,_to,_ni,___,_si,_ta,_no,_da,_cr,_eol
_sc12_msg1C:
		.BYTE	_______,_ta,_i_,_sa,_lt,_an0,_A_,_KI,_RA,_ha,___,_su,_de,_ni,___,_si,_n_,_de,_i_,_ta,_no,_da,_cr,_ret
		.BYTE	_______________________,_do,_u_,_da,_col,___,_ki,_ga,_su,_n_,_da,_ka,___,_te_tsu__o_,_ex,_aof,_eol
_sc12_msg1D:
		.BYTE	_______,_te_tsu__o_,_lt,_an0,_u_,_ru,_se,$89,_ex,_ret
		.BYTE	_______________________,_ri,_ka,_no,_zi,_ka,_n_,_zi,_yy,___,_ne,$89,_n_,_da,_yo,_ex,_aof,_eol
_sc12_msg1E:
		.BYTE	_______,_ta,_i_,_sa,_lt,_an0,_sa,_AA,___,_i_,_tt,_si,_oo,_ni,___,_ka,_e_,_ru,_n_,_da,_ex,_aof,_eol
_sc12_msg1F:
		.BYTE	_O_,_RE,_ha,___,_BA,_I_,_KU,_wo,_to,_me,_te,_col,___,_a_,_ta,_ri,_wo,___,_mi,_ta,_cr,_eol
_sc12_msg20:
		.BYTE	_SU,_TA,_ZI,_A_,_MU,_wa,_ki,_ni,___,_to,_me,_ra,_re,_ta,___,_so,_u_,_ko,_u_,_si,_re,_i_,_si,_yy,_ka,_ra,_ret
		.BYTE	_ka,_ku,_se,_i_,_ki,_wo,___,_tu,_ka,_tt,_ta,___,_ta,_i_,_sa,_no,_ko,_e_,_ga,_ret
		.BYTE	_na,_ga,_re,_te,_ki,_ta,_cr,_eol
_sc12_msg21:
		.BYTE	_O_,_RE,_ha,___,_RE,_str,_ZA,_str,_BI,_str,_MU,_wo,___,_wa,_ki,_ni,_ka,_ka,_e_,_col,___,_BA,_I_,_KU,_no,_ret
		.BYTE	_PA,_WA,_str,_SU,_I_,_TT,_TI,_wo,_i_,_re,_ta,_cr,_eol
_sc12_msg22:
		.BYTE	_______,_te_tsu__o_,_lt,_an0,_wa,_re,_ro,_OO,_ex,_ex,_aof,_eol
_sc12_msg23:
		.BYTE	_O_,_RE,_ha,___,_yo,_ko,_me,_de,___,_mi,_na,_ga,_ra,___,_su,_su,_n_,_de,_tt,_ta,_cr,_eol
_sc12_msg24:
		.BYTE	___________,_ka,_i_,_lt,_si,_oo,_u_,_si,_uu,_u_,___,_ka,_ke,_ta,_ho,_u_,_ga,___,_i_,_i_,_ze,_cr,_ret
		.BYTE	_______________________,_o_,_i_,_tt,_col,___,_ka__ne__da,_AA,_cr,_eol
_sc12_msg25:
		.BYTE	_______,_ka__ne__da,_lt,_ho,_si,_ga,_tt,_te,_n_,_da,_ro,_OO,_dot,_dot,_dot,___,_ko,_i_,_tu,_wo,_dot,_dot,_dot,_eol
_sc12_msg26:
		.BYTE	_i_,_ma,___,_e_,_ta,_i_,_no,_si,_re,_na,_i_,___,_ki,_oo,_da,_i_,_KA,_PU,_SE,_RU,_ga,_ret
		.BYTE	_su,_ga,_ta,_wo,___,_a_,_ra,_wa,_si,_te,_i_,_ta,_cr,_eol
_sc12_msg27:
		.BYTE	_si,_oo,_u_,_ge,_ki,_ha,_wo,___,_u_,_ke,_te,___,_ta,_o_,_re,_ta,_no,_ha,_ret
		.BYTE	_KE,_I_,_da,_tt,_ta,_cr,_eol
_sc12_msg28:
		.BYTE	_ya,_ga,_te,___,_re,_i_,_ki,_no,___,_hu,_n_,_si,_uu,_tu,_ga,___,_o_,_sa,_ma,_tt,_ta,_KA,_PU,_SE,_RU,_ni,_ret
		.BYTE	_si,_oo,_u_,_ge,_ki,_ha,_wo,___,_u_,_ke,_ta,_ta,_me,_ka,_col,___,_ki,_re,_tu,_ga,___,_ha,_si,_tt,_ta,_cr,_eol
_sc12_msg29:
		.BYTE	_______,_ta,_i_,_sa,_lt,_so,_si,_te,_dot,_dot,_dot,___,_so,_no,_na,_re,_no,_ha,_te,_no,___,_su,_ga,_ta,_ga,_ret
		.BYTE	_______________________,_so,_re,_da,_cr,_eol
;_sc12_msg2A:
;		.BYTE	_yu,_u_,_ya,_ke,_no,_so,_ra,_ni,___,_na,_ga,_re,_bo,_si,_ga,___,_ki,_ra,_me,_i_,_te,_i_,_ta,_cr,_ret
;		.BYTE	___,_A_,_str,_MI,_str,_lt,_S,_O,_L,_da,_so,_u_,_de,_su,_dot,_dot,_dot,_eol
;_sc12_msg2B:
;		.BYTE	_______,_ta,_i_,_sa,_lt,_an0,_a_,_no,_te_tsu__o_,_ga,___,_S,_O,_L,_wo,_dot,_dot,_dot,_ret
;		.BYTE	_______________________,_ko,_ko,_ma,_de,___,_PA,_WA,_str,_wo,___,_mi,_ni,_tu,_ke,_ta,_to,_ret
;		.BYTE	_______________________,_i_,_u_,_no,_ka,_AA,_dot,_dot,_dot,_aof,_eol
;_sc12_msg2C:
;		.BYTE	___________,_KE,_I_,_lt,_a_,_na,_ta,_no,_yo,_u_,_ni,___,_ti,_ka,_ra,_wo,___,_tu,_ka,_tt,_te,_ha,_ret
;		.BYTE	_______________________,_i_,_ke,_na,_i_,_wa,_cr,_eol
;_sc12_msg2D:
;		.BYTE	_______,_te_tsu__o_,_lt,_na,_ni,_II,_qe,_eol
;_sc12_msg2E:
;		.BYTE	_______,_te_tsu__o_,_lt,_GA,_KI,_do,_mo,_dot,_dot,_dot,___,_GA,_KI,_do,_mo,_da,_na,_dot,_dot,_dot,_eol

		SECTION_END		F12
