
		SECTION_START	F5

		MSG_START	_scene5_msg_lib
		MSG_IDX	_sc5_msg00
		MSG_IDX	_sc5_msg01
		MSG_IDX	_sc5_msg02						; reused
		MSG_IDX	_sc5_msg03
		MSG_IDX	_sc5_msg04
		MSG_IDX	_sc5_msg05
		MSG_IDX	_sc5_msg06
;		MSG_IDX	_sc5_msg07						; -unused-
		MSG_IDX	_sc5_msg08
		MSG_IDX	_sc5_msg09
		MSG_IDX	_sc5_msg0A
		MSG_IDX	_sc5_msg0B
		MSG_IDX	_sc5_msg0C
		MSG_IDX	_sc5_msg0D
		MSG_IDX	_sc5_msg0E
		MSG_IDX	_sc5_msg0F
		MSG_IDX	_sc5_msg10
		MSG_IDX	_sc5_msg11
		MSG_IDX	_sc5_msg12
		MSG_IDX	_sc5_msg13
		MSG_IDX	_sc5_msg14
		MSG_IDX	_sc5_msg15
		MSG_IDX	_sc5_msg16						; reused
		MSG_IDX	_sc5_msg17						; reused
		MSG_IDX	_sc5_msg18						; reused
		MSG_IDX	_sc5_msg19
		MSG_IDX	_sc5_msg1A
		MSG_IDX	_sc5_msgB3						; scene 5 msg
_sc5_msg00:
		.BYTE	_ma,_zu,___,_O_,_RE,_ta,_ti,_no,___,_ta,_ma,_ri,_ba,_col,___,_ha,_ru,_ki,_ya,_ni,___,_mu,_ka,_tt,_ta,_cr,_ret
		.BYTE	___,_MA,_SU,_TA,_str,_lt,_an0,_o_,_ma,_e_,_ta,_ti,_col,___,_na,_n_,_no,_yo,_u_,_da,_cr,_ret
		.BYTE	_______________________,_bi,_tt,_ku,_ri,_sa,_se,_ya,_ga,_tt,_te,_cr,_aof,_eol
_sc5_msg01:
		.BYTE	___,_MA,_SU,_TA,_str,_lt,_an0,_yo,_o_,_col,___,_mo,_u_,___,_o_,_ka,_e_,_ri,_ka,_i_,_cr,_ret
		.BYTE	_______________________,_te_tsu__o_,_no,_ya,_tu,_ha,___,_mi,_tu,_ka,_tt,_ta,_no,_ka,_qe,_aof,_eol
_sc5_msg02:
		.BYTE	___,_MA,_SU,_TA,_str,_lt,_an0,_KO,_RA,_TT,_ex,___,_ma,_col,_ma,_te,_tt,_cr,_aof,_ret
		.BYTE	_______,_ka__ne__da,_lt,_ma,_te,_ne,$89,_yo,_str,_cr,_eol
_sc5_msg03:
		.BYTE	_O_,_RE,_ta,_ti,_ha,___,_num,_ku,_ma,_de,___,_ya,_tt,_te,_ki,_ta,_cr,_eol
_sc5_msg04:
		.BYTE	_O_,_RE,_ta,_ti,_ha,___,_ha,_ru,_ki,_ya,_no,_ma,_e_,_de,___,_te_tsu__o_,_no,___,_yu,_ku,_e_,_wo,_ret
		.BYTE	_ki,_i_,_te,_mi,_ru,_ko,_to,_ni,_si,_ta,_cr,_eol
_sc5_msg05:
		.BYTE	_______,_o_,_to,_ko,_lt,_an0,_e_,_tt,___,_te_tsu__o_,_OO,_qe,_ret
		.BYTE	_______________________,_2,_ku,_no,_ho,_u_,_ni,___,_ha,_si,_tt,_te,_tt,_ta,_ze,_cr,_aof,_eol
_sc5_msg06:
		.BYTE	_______,_o_,_to,_ko,_lt,_an0,_te,_me,$A1,_col,___,_u_,_ru,_se,_str,_n_,_da,_yo,_cr,_aof,_eol
;_sc5_msg07:
;		.BYTE	_______,_o_,_to,_ko,_lt,_an0,_te_tsu__o_,_qe,___,_si,_ra,_ne,$89,_na,_str,_cr,_aof,_eol
_sc5_msg08:
		.BYTE	_______,_o_,_to,_ko,_lt,_an0,_te_tsu__o_,_ka,_qe,___,_sa,_tt,_ki,___,_3,_ku,_no,_ho,_u_,_ni,_ret
		.BYTE	_______________________,_ha,_si,_tt,_te,_tt,_ta,_ze,_cr,_aof,_eol
_sc5_msg09:
		.BYTE	_______,_o_,_to,_ko,_lt,_an0,_na,_n_,_da,_yo,_OO,_col,___,_i_,_ki,_na,_ri,_cr,_aof,_eol
_sc5_msg0A:
		.BYTE	_______,_o_,_to,_ko,_lt,_an1,_te_tsu__o_,_qe,___,_so,_re,_na,_ra,___,_4,_ku,_no,_ho,_u_,_he,_ret
		.BYTE	_______________________,_i_,_tt,_ta,_mi,_ta,_i_,_da,_ze,_cr,_aof,_eol
_sc5_msg0B:
		.BYTE	_______,_o_,_to,_ko,_lt,_an0,_u_,_ru,_se,_e_,_na,_a_,_col,___,_PI,_str,_NA,_TU,___,_ku,_re,_yo,_OO,_cr,_aof,_eol
_sc5_msg0C:
		.BYTE	_______,_o_,_to,_ko,_lt,_an0,_su,_col,___,_su,_ma,_ne,_e_,_na,_a_,_cr,_ret
		.BYTE	_______________________,_dot,_dot,_dot,_da,_col,___,_da,_re,_ka,___,_sa,_ga,_si,_te,_ru,_no,_ka,_qe,_aof,_eol
_sc5_msg0D:
		.BYTE	_su,_i_,_ro,_ni,___,_mi,_zu,_ga,___,_na,_ga,_re,_te,_i_,_ru,_cr,_ret
		.BYTE	_ki,_uu,_u_,_si,_ga,_i_,_to,___,_NE,_O_,_to,_u_,_ki,_oo,_u_,_no,___,_a_,_i_,_da,_ni,_a_,_ru,_cr,_eol
_sc5_msg0E:
		.BYTE	_NE,_O_,_to,_u_,_ki,_oo,_u_,_no,___,_SU,_RA,_MU,_ga,_i_,_da,_cr,_ret
		.BYTE	_u_,_do,_n_,_ya,___,_DO,_str,_MU,_ga,_a_,_ru,_cr,_eol
_sc5_msg0F:
		.BYTE	_NE,_O_,_to,_u_,_ki,_oo,_u_,_no,___,_ha,_zu,_re,_da,_cr,_ret
		.BYTE	_ti,_ka,_ku,_ni,___,_KO,_N_,_BI,_NA,_str,_TO,_ga,___,_ta,_ti,_na,_ra,_n_,_de,_i_,_ru,_cr,_eol
_sc5_msg10:
		.BYTE	_______,_ka__ne__da,_lt,_ko,_ko,_ro,_ni,___,_ya,_ma,_si,_i_,_ko,_to,_ga,_a_,_ru,_ka,_ra,_col,_ret
		.BYTE	_______________________,_so,_u_,_ya,_tt,_te,_col,___,_i_,_tu,_mo,_BI,_KU,_BI,_KU,_si,_te,_n_,_da,_yo,_cr,_ret
		.BYTE	_______________________,_ta,_ma,_ni,_ha,___,_hu,_tu,_u_,_no,_no,_mi,_mo,_no,_mo,_ret
		.BYTE	_______________________,_u_,_re,_yo,_na,_AA,_str,_TT,_cr,_eol
_sc5_msg11:
		.BYTE	___,_MA,_SU,_TA,_str,_lt,_an0,_o_,_ma,_e_,_ra,_ko,_so,___,_na,_n_,_ka,___,_no,_n_,_de,_ke,_cr,_ret
		.BYTE	_______________________,_u_,_ti,_ha,___,_ma,_ti,_a_,_wa,_se,_ba,_si,_oo,_zi,_yy,_ret
		.BYTE	_______________________,_ne,$89,_n_,_da,_yo,_cr,_aof,_ret
		.BYTE	___,_ya,_ma,_ga,_ta,_lt,_a_,_no,_col,___,_i_,_nu,_no,_SI,$6A,_N_,_BE,_N_,_wo,_str,_TT,_qe,_eol
_sc5_msg12:
		.BYTE	_MA,_SU,_TA,_str,_no,_ya,_tu,_col,___,_mi,_gi,_te,_no,_si,_ta,_ni,___,_PI,_str,_NA,_TU,_wo,_ret
		.BYTE	_ka,_ku,_si,_te,_ya,_ga,_ru,_cr,_eol
_sc5_msg13:
		.BYTE	___,_MA,_SU,_TA,_str,_lt,_an0,_O_,_I_,_col,___,_PI,_str,_NA,_TU,_na,_ra,___,_mo,_u_,___,_ne,$89,_zo,_cr,_aof,_eol
_sc5_msg14:
		.BYTE	___,_MA,_SU,_TA,_str,_lt,_an0,_te_tsu__o_,_na,_ra,___,_num,_ku,_da,_to,_col,_ret
		.BYTE	_______________________,_i_,_tt,_ta,_ha,_zu,_da,_ze,_cr,_aof,_eol
_sc5_msg15:
		.BYTE	_te_tsu__o_,_no,_su,_ga,_ta,_ha,___,_na,_i_,_cr,_eol
_sc5_msg16:
		.BYTE	_______,_o_,_to,_ko,_lt,_an0,_te,_me,_e_,_col,___,_sa,_ke,_ku,_sa,_i_,___,_i_,_ki,_si,_ya,_ga,_tt,_te,_col,_ret
		.BYTE	_______________________,_na,_ma,_i_,_ki,_na,_n_,_da,_yo,_str,_ex,_aof,_ret
		.BYTE	_o_,_to,_ko,_ga,___,_hu,_i_,_ni,___,_O_,_RE,_no,_ga,_n_,_me,_n_,_wo,___,_na,_gu,_tt,_te,_ki,_ta,_cr,_ret
		.BYTE	_KE,_N_,_KA,_ni,___,_na,_tt,_ta,_cr,_eol
_sc5_msg17:
		.BYTE	___________________,_lt,_U_,_U_,_str,_TT,___,_U_,_U_,_str,_TT,_ret
		.BYTE	___________,_ka,_i_,_lt,_ka__ne__da,_AA,___,_PO,_RI,_da,_ze,_ex,_ret
		.BYTE	_______,_ka__ne__da,_lt,_ni,_ge,_ro,_str,_ex,_ex,_ret
		.BYTE	_ret
		.BYTE	_dot,_dot,_dot,_ke,_do,___,_O_,_RE,_ta,_ti,_ha,___,_PO,_RI,_ni,___,_tu,_ka,_ma,_tt,_te,_si,_ma,_tt,_ta,_cr,_eol
_sc5_msgB3:
		.BYTE	___,_MA,_SU,_TA,_str,_lt,_an0,_te_tsu__o_,_na,_ra,___,_num,_ku,_no,_ho,_u_,_he,___,_i_,_tt,_ta,_ze,_cr,_aof,_ret
		.BYTE	___________,_ka,_i_,_lt,_te,_ma,___,_ka,_ke,_sa,_se,_ya,_ga,_tt,_te,_str,_cr,_eol
;		.BYTE	_______,_ka__ne__da,_lt,_wa,_ri,_II,_na,_str,_cr,___,_MA,_SU,_TA,_str,_col,___,_tu,_i_,_de,_ni,_ret
;		.BYTE	_______________________,_ko,_no,_PI,_str,_NA,_TU,_col,___,_i_,_ta,_da,_i_,_to,_ku,_ze,$89,_cr,_eol
_sc5_msg18:
;		.BYTE	_ka__ne__da,_si,_oo,_u_,_ne,_n_,_ha,___,_si,_oo,_u_,_ne,_n_,_i_,_n_,_o_,_ku,_ri,_ni,_ret
;		.BYTE	_na,_ri,_ma,_si,_ta,_cr,_eol
		.BYTE	_______,_ka__ne__da,_lt,_wa,_ri,_II,_na,_str,_cr,___,_MA,_SU,_TA,_str,_col,___,_tu,_i_,_de,_ni,_ret
		.BYTE	_______________________,_ko,_no,_PI,_str,_NA,_TU,_col,___,_i_,_ta,_da,_i_,_to,_ku,_ze,$89,_cr,_eol
_sc5_msg19:
		.BYTE	_o_,_to,_ko,_lt,_an0,_a_,_a_,_col,___,_so,_i_,_tu,_na,_ra,___,_mu,_ko,_u_,_no,_ret
		.BYTE	_______________,_KO,_N_,_BI,_NA,_str,_TO,_no,_ho,_u_,_he,___,_i_,_tt,_ta,_ze,_cr,_aof,_eol
_sc5_msg1A:
		.BYTE	_______,_o_,_to,_ko,_lt,_an0,_he,_he,_tt,_col,___,_ko,_re,___,_PI,_str,_NA,_TU,_ka,_AA,_qe,_aof,_eol

		SECTION_END		F5
