
		SECTION_START	FE

		MSG_START	_sceneE_msg_lib
		MSG_IDX	_scE_msg00
;		.WORD	0
		MSG_IDX	_scE_msg02
		MSG_IDX	_scE_msg03
		MSG_IDX	_scE_msg04
_scE_msg00:
		.BYTE	_______,_ka__ne__da,_lt,_do,_ke,_do,_ke,_do,_ke,_tt,_tu,_tt,_ta,_ra,_a_,_str,_tt,_ex,_eol
_scE_msg02:
		.BYTE	_GA,_TT,_SI,_YY,_str,_N_,_ex,_ex,___,_BO,_N_,_TT,_ex,_ret
		.BYTE	_______,_ka__ne__da,_lt,_i_,_tt,_te,_str,_tt,_cr,_eol
_scE_msg03:
		.BYTE	_A,_RU,_str,_MU,_no,_na,_ka,_ni,___,_a_,_tt,_ta,___,_ki,_ni,_a_,_ta,_tt,_te,_col,_ret
		.BYTE	_F,_dot,_P,_dot,_H,_ha,___,_ba,_ku,_ha,_tu,_si,_te,_si,_ma,_i_,_col,___,_O_,_RE,_to,_KE,_I_,_ha,_ret
		.BYTE	_yu,_ka,_ni,_na,_ge,_da,_sa,_re,_ta,_cr,_eol
_scE_msg04:
		.BYTE	_so,_ko,_ni,___,_i_,_ta,_no,_ha,___,_si,_wa,_da,_ra,_ke,_no,_GA,_KI,_to,_ret
		.BYTE	_A_,_str,_MI,_str,_no,_TA,_KO,_col,___,_so,_re,_ni,_dot,_dot,_dot,___,_te_tsu__o_,_da,_tt,_ta,_cr,_eol

		SECTION_END		FE
