
		SECTION_START	F1

		MSG_START	_scene1_msg_lib
		MSG_IDX	_sc1_msg0B
		MSG_IDX	_sc1_msg0C
		MSG_IDX	_sc1_msg0D
		MSG_IDX	_sc1_msg0E
		MSG_IDX	_sc1_msg0F
		MSG_IDX	_sc1_msg10
		MSG_IDX	_sc1_msg11
		MSG_IDX	_sc1_msg12
		MSG_IDX	_sc1_msg13
		MSG_IDX	_sc1_msg14
		MSG_IDX	_sc1_msg15
		MSG_IDX	_sc1_msg16
		MSG_IDX	_sc1_msg17
		MSG_IDX	_sc1_msg18
		MSG_IDX	_sc1_msg1A
		MSG_IDX	_sc1_msg1B
		MSG_IDX	_sc1_msg1C
		MSG_IDX	_sc1_msg1D
		MSG_IDX	_sc1_msg1E
		MSG_IDX	_sc1_msg1F
		MSG_IDX	_sc1_msg20
		MSG_IDX	_sc1_msg21
		MSG_IDX	_sc1_msg22
		MSG_IDX	_sc1_msg23
		MSG_IDX	_sc1_msg24
		MSG_IDX	_sc1_msg25
		MSG_IDX	_sc1_msg27
		MSG_IDX	_sc1_msg28
		MSG_IDX	_sc1_msg29
		MSG_IDX	_sc1_msg2A
		MSG_IDX	_sc1_msg2B
		MSG_IDX	_sc1_msg2C
		MSG_IDX	_sc1_msg2D
		MSG_IDX	_sc1_msg31
		MSG_IDX	_sc1_msg32
		MSG_IDX	_sc1_msg80
		MSG_IDX	_sc1_msg81
		MSG_IDX	_sc1_msgB9
_sc1_msg80:
		.BYTE	___,_A_,_str,_MI,_str,_lt,_u_,_ru,_sa,_i_,_tt,_ex,_eol
_sc1_msg81:
		.BYTE	___,_A_,_str,_MI,_str,_lt,_an0,_KO,_RA,_TT,_ex,___,_no,_zo,_ku,_n_,_zi,_yy,_na,_i_,_tt,_ex,_aof,_eol
_sc1_msgB9:
		.BYTE	_a_,_ku,_ru,_hi,___,_O_,_RE,_ta,_ti,_ha,___,_A_,_str,_MI,_str,_no,___,_to,_ri,_si,_ra,_be,_wo,_ret
		.BYTE	_u_,_ke,_ru,_HA,_ME,_ni,_na,_tt,_ta,_cr,_eol
_sc1_msg0B:
		.BYTE	___,_A_,_str,_MI,_str,_lt,_an0,_so,_re,_de,_col,_ret
		.BYTE	_______________________,_O_,_MA,_E_,_ra,___,_na,_n_,_de,___,_a_,_n_,_na,_to,_ko,_ro,_ni,_ret
		.BYTE	_______________________,_i_,_ta,_n_,_da,_qe,_aof,_eol
_sc1_msg0C:
		.BYTE	_______,_ka__ne__da,_lt,_ki,_to,_ku,_no,_HA,_HA,_ni,_a_,_i_,_ni,___,_yo,_na,_ka,_ni,_ret
		.BYTE	_______________________,_na,_ka,_ma,_to,___,_BA,_I_,_KU,_de,___,_ha,_si,_tt,_te,_ta,_ra,_col,_ret
		.BYTE	_______________________,_KU,_RA,_U_,_N_,_tt,_te,_i_,_u_,___,_hu,_ri,_oo,_u_,_GU,_RU,_str,_PU,_ni,_ret
		.BYTE	_______________________,_ka,_ra,_ma,_re,_te,_col,___,_na,_ka,_ma,_ga,_AA,___,_hi,_to,_ri,_ret
		.BYTE	_______________________,_ya,_ra,_re,_ta,_mo,_n_,_de,$A1,___,_tu,_i_,_KA,_TT,_to,_na,_tt,_te,_dot,_dot,_dot,_eol
_sc1_msg0D:
		.BYTE	___,_A_,_str,_MI,_str,_lt,_an0,_tu,_i_,_KA,_TT,_to,_na,_tt,_te,___,_KU,_RA,_U_,_N_,_no,_ya,_tu,_ra,_wo,_ret
		.BYTE	_______________________,_8,_ni,_n_,_ba,_ka,_ri,___,_si,_ro,_BI,_RU,_o_,_ku,_ri,_ni,_si,_ta,_dot,_dot,_dot,_ret
		.BYTE	_______________________,_to,___,_i_,_u_,_wa,_ke,_ka,_dot,_dot,_dot,_ret
		.BYTE	_______________________,_dot,_dot,_dot,_dot,_de,___,_ki,_to,_ku,_no,_HA,_HA,_ha,_do,_u_,_si,_ta,_n_,_da,_qe,_aof,_eol
_sc1_msg0E:
		.BYTE	_______,_ka__ne__da,_lt,_e_,_e_,___,_o_,_ka,_ge,_sa,_ma,_de,___,_yu,_u_,_be,_ret
		.BYTE	_______________________,_to,_u_,_ge,_wo,___,_ko,_e_,_ma,_si,_te,_dot,_dot,_dot,_cr,_eol
_sc1_msg0F:
		.BYTE	___,_A_,_str,_MI,_str,_lt,_an0,_to,_u_,_ge,_wo,___,_ko,_e_,_te,___,_TU,_str,_RI,_N_,_GU,_ni,_de,_mo,_ret
		.BYTE	_______________________,_de,_ka,_ke,_ta,_no,_ka,_qe,_aof,_eol
_sc1_msg10:
		.BYTE	_______,_ka__ne__da,_lt,_o_,_na,_ka,_su,_i_,_ta,_str,_cr,_eol
_sc1_msg11:
		.BYTE	_A_,_str,_MI,_str,_no,___,_to,_ri,_si,_ra,_be,_ka,_n_,_da,_ze,_cr,_eol
_sc1_msg12:
		.BYTE	_O_,_RE,_da,_yo,_col,___,_O_,_dot,_RE,_cr,_eol
_sc1_msg13:
		.BYTE	_O_,_RE,_ta,_ti,_no,___,_me,_n_,_ki,_oo,_si,_oo,_str,_da,_ze,_col,_ret
		.BYTE	_da,_i_,_zi,_ni,___,_a_,_tu,_ka,_e_,_tt,_te,_str,_no,_cr,_eol
_sc1_msg14:
		.BYTE	_ha,_n_,_se,_i_,_hu,_bu,_n_,_si,_no,_RI,_SU,_TO,_mi,_ta,_i_,_da,_col,_ret
		.BYTE	_so,_n_,_na,_ni,_si,_ra,_be,_na,_ku,_tt,_te,_mo,___,_so,_ko,_ni,_ha,___,_O_,_RE,_ta,_ti,_no,_ret
		.BYTE	_KA,_O_,_na,_n_,_te,___,_no,_tt,_te,_ru,_WA,_KE,_ne,_str,_no,_ni,_sa,_cr,_eol
_sc1_msg15:
		.BYTE	___,_A_,_str,_MI,_str,_lt,_an0,_mi,_ri,_yy,_a_,___,_wa,_ka,_ru,_sa,_cr,_ret
		.BYTE	_______________________,_mo,_u_,_i_,_i_,_col,___,_o_,_ma,_e_,_ta,_ti,_no,___,_to,_ri,_si,_ra,_be,_ha,_ret
		.BYTE	_______________________,_o_,_wa,_ri,_da,_cr,___,_o_,_mo,_te,_de,___,_ma,_tt,_te,_ro,_cr,_ret
		.BYTE	_______________________,_tu,_gi,_tt,_ex,_aof,_eol
_sc1_msg16:
		.BYTE	_O_,_RE,_no,_na,_ka,_ma,_da,_ze,_col,___,_O_,_RE,_ta,_ti,___,_mi,_n_,_na,_ret
		.BYTE	_ke,_n_,_ko,_u_,___,_yu,_u_,_ri,_oo,_u_,___,_hu,_ri,_oo,_u_,___,_si,_oo,_str,_ne,_n_,___,_da,_ze,_ex,_eol
_sc1_msg17:
		.BYTE	_ko,_re,_ga,___,_O_,_RE,_no,___,_KA,_O_,_da,_ze,_cr,_eol
_sc1_msg18:
		.BYTE	_______,_ka__ne__da,_lt,_ne,$89,___,_o_,_zi,_sa,_n_,_ta,_ti,_ha,_sa,_AA,_ret
		.BYTE	_______________________,_NA,_N_,_de,___,_yu,_u_,_be,___,_a_,_n_,_na,_to,_ko,_ni,_i_,_ta,_wa,_ke,_qe,_eol
_sc1_msg1A:
		.BYTE	_ya,_ma,_ga,_ta,_ku,_n_,_da,_yo,_cr,_eol
_sc1_msg1B:
		.BYTE	_ka,_i_,_ku,_n_,_da,_yo,_cr,_eol
_sc1_msg1C:
		.BYTE	_ku,_wa,_ta,_ku,_n_,_da,_yo,_cr,_eol
_sc1_msg1D:
		.BYTE	_wa,_ta,_na,_be,_ku,_n_,_da,_yo,_cr,_eol
_sc1_msg1E:
		.BYTE	_ta,_ke,_ya,_ma,_ku,_n_,_da,_yo,_cr,_eol
_sc1_msg1F:
		.BYTE	___,_ya,_ma,_ga,_ta,_lt,_yu,_u_,_be,_ha,___,_mo,_u_,_su,_ko,_si,_da,_tt,_ta,_yo,_na,_a_,_col,_ret
		.BYTE	_______________________,_KU,_RA,_U_,_N_,_no,_ya,_tu,_ra,_wo,___,_tu,_bu,_se,_ru,_to,_ko,_ro,_ret
		.BYTE	_______________________,_da,_tt,_ta,_n_,_da,_ze,_cr,_eol
_sc1_msg20:
		.BYTE	___________,_ka,_i_,_lt,_do,_str,_de,_mo,_i_,_str,_ke,_do,___,_O_,_ZI,_sa,_n_,_col,_ret
		.BYTE	_______________________,_te_tsu__o_,_ha,___,_do,_ko,_ni,_i_,_ru,_n_,_da,_yo,$88,_cr,_eol
_sc1_msg21:
		.BYTE	___,_A_,_str,_MI,_str,_lt,_an0,_ko,_ra,_tt,_ex,___,_yo,_so,_mi,_wo,_su,_ru,_n_,_zi,_yy,_na,_i_,_tt,_ex,_aof,_eol
_sc1_msg22:
		.BYTE	___,_A_,_str,_MI,_str,_lt,_an0,_ha,_n_,_se,_i_,_hu,_bu,_n_,_si,_to,_no,___,_tu,_ki,_a_,_i_,_ha,_ret
		.BYTE	_______________________,_na,_i_,_n_,_da,_ro,_u_,_na,_qe,_aof,_eol
_sc1_msg23:
		.BYTE	_______,_ka__ne__da,_lt,_ma,_col,_ma,_sa,_ka,___,_O_,_RE,_ta,_ti,___,_ma,_zi,_me,_na,_ret
		.BYTE	_______________________,_ke,_n_,_ko,_u_,_yu,_u_,_ri,_oo,_u_,_hu,_ri,_oo,_u_,_si,_oo,_u_,_ne,_n_,_ret
		.BYTE	_______________________,_de,_su,_yo,_str,_cr,_eol
_sc1_msg24:
		.BYTE	_______,_ka__ne__da,_lt,_O_,_ZI,_sa,_n_,___,_o_,_to,_ko,_ma,_e_,_de,_su,_ne,_ex,_eol
_sc1_msg25:
		.BYTE	_______,_ka__ne__da,_lt,_O_,_ZI,_sa,_n_,___,_TI,_YY,_TT,_KU,_a_,_i_,_te,_ru,_yo,_str,_cr,_eol
_sc1_msg27:
		.BYTE	_______,_ka__ne__da,_lt,_ha,_n_,_se,_i_,_hu,_bu,_n_,_si,_no,_RI,_SU,_TO,_da,_na,_dot,_dot,_dot,_ret
		.BYTE	_______________________,_a_,_tt,___,_o_,_n_,_na,_no,_ko,_mo,_i_,_ru,_n_,_da,_ex,_ret
		.BYTE	_______________________,_ka,_tt,_wa,_i_,_i_,_str,___,_e_,_str,_tt,_to,_na,_ma,_e_,_ha,_dot,_dot,_dot,_eol
_sc1_msg28:
		.BYTE	_______,_ka__ne__da,_lt,_ne,_e_,___,_so,_no,_KO,_no,___,_na,_ma,_e_,___,_na,_n_,_te,_i_,_u_,_no,_qe,_ret
		.BYTE	_______________________,_o_,_si,_e_,_te,___,_ku,_n_,_na,_i_,_qe,_eol
_sc1_msg29:
		.BYTE	_______,_ka__ne__da,_lt,_so,_no,_KO,___,_do,_ko,_ni,___,_su,_n_,_de,_n_,_no,_qe,_eol
_sc1_msg2A:
		.BYTE	_______,_ka__ne__da,_lt,_ne,_tt,___,_de,_n_,_wa,_ba,_n_,_go,_u_,_da,_ke,_de,_mo,_ret
		.BYTE	_______________________,_o_,_si,_e_,_te,_ku,_da,_sa,_i_,_yo,_col,___,_o_,_ne,_ga,_i_,_cr,_eol
_sc1_msg2B:
		.BYTE	___,_A_,_str,_MI,_str,_lt,_an0,_e_,_e_,_e_,_i_,_tt,_col,___,_so,_n_,_na,_ko,_to,_ga,___,_wa,_ka,_tt,_te,_ri,_yy,_ret
		.BYTE	_______________________,_sa,_ga,_su,_wa,_ke,_na,_i_,_da,_ro,_tt,_ex,_aof,_eol
_sc1_msg2C:
		.BYTE	___________,_bu,_ka,_lt,_an1,_do,_u_,_ya,_ra,___,_KO,_I_,_TU,_ra,___,_ka,_n_,_ke,_i_,_na,_i_,_ret
		.BYTE	_______________________,_mi,_ta,_i_,_de,_su,_ne,_e_,_cr,_aof,_eol
_sc1_msg2D:
		.BYTE	_______,_ka__ne__da,_lt,_ko,_ri,_yy,_i_,_i_,_ya,_col,___,_TU,_str,_RI,_N_,_GU,_da,_tt,_te,_yo,_OO,_cr,_ret
		.BYTE	_______________________,_a_,_ha,_ha,_ha,_dot,_dot,_dot,_eol
_sc1_msg31:
		.BYTE	___,_A_,_str,_MI,_str,_lt,_ko,_ra,_tt,_col,___,_da,_ma,_re,_ex,_eol
_sc1_msg32:
		.BYTE	_ta,_i_,_i_,_ku,_ka,_n_,_no,_na,_ka,_wo,___,_BE,_NI,_YA,_i_,_ta,_de,___,_si,_ki,_tt,_ta,_da,_ke,_no,_ret
		.BYTE	_ka,_se,_tu,_no,___,_to,_ri,_si,_ra,_be,_si,_tu,_no,_na,_ka,_da,_cr,_eol

		SECTION_END		F1
