
		SECTION_START	F2

		MSG_START	_scene2_msg_lib
		MSG_IDX	_sc2_msg00
		MSG_IDX	_sc2_msg01
		MSG_IDX	_sc2_msg02
		MSG_IDX	_sc2_msg03
		MSG_IDX	_sc2_msg04
		MSG_IDX	_sc2_msg05
		MSG_IDX	_sc2_msg06
		MSG_IDX	_sc2_msg07
		MSG_IDX	_sc2_msg08
		MSG_IDX	_sc2_msg09
		MSG_IDX	_sc2_msg0A
		MSG_IDX	_sc2_msg0B
		MSG_IDX	_sc2_msg0C
		MSG_IDX	_sc2_msg0D
		MSG_IDX	_sc2_msg0E
		MSG_IDX	_sc2_msg0F
		MSG_IDX	_sc2_msg10
;		MSG_IDX	_sc2_msg11						; -unused-
		MSG_IDX	_sc2_msg12
		MSG_IDX	_sc2_msg13
		MSG_IDX	_sc2_msg14
		MSG_IDX	_sc2_msg15
		MSG_IDX	_sc2_msg16
		MSG_IDX	_sc2_msg17
		MSG_IDX	_sc2_msg18						; reused
		MSG_IDX	_sc2_msg19
		MSG_IDX	_sc2_msg1A
;		.WORD	0								; dummy
		MSG_IDX	_sc2_msg1C
		MSG_IDX	_sc2_msg1D
		MSG_IDX	_sc2_msg1E
		MSG_IDX	_sc2_msg1F
		MSG_IDX	_sc2_msg20
		MSG_IDX	_sc2_msg21
		MSG_IDX	_sc2_msg22
		MSG_IDX	_sc2_msg23
		MSG_IDX	_sc2_msg24
		MSG_IDX	_sc2_msg25
		MSG_IDX	_sc2_msg26
		MSG_IDX	_sc2_msg27
		MSG_IDX	_sc2_msg28
		MSG_IDX	_sc2_msgA2					; scene 2 msg
		MSG_IDX	_sc2_msgBA					; scene 2 msg
;		MSG_IDX	_sc2_msg29						; -unused-
_sc2_msg00:
		.BYTE	_O_,_RE,_ta,_ti,_ha,___,_to,_ri,_si,_ra,_be,_si,_tu,_no,___,_o_,_mo,_te,_no,___,_RO,_str,_KA,_ni,_ret
		.BYTE	_da,_sa,_re,_ta,_cr,_ret
		.BYTE	_ret
		.BYTE	___,_A_,_str,_MI,_str,_lt,_ti,_oo,_tt,_to,___,_ko,_ko,_de,___,_ma,_tt,_te,_ro,_dot,_dot,_dot,_cr,_ret
		.BYTE	_______________________,_yo,_str,_si,_col,___,_tu,_gi,_ex,___,_ha,_i_,_tt,_te,_ko,_i_,_ex,_eol
_sc2_msg01:
		.BYTE	_DE,_MO,_ga,_ku,_se,_i_,_ya,___,_TE,_RO,_RI,_SU,_TO,_ta,_ti,_ga,___,_sa,_wa,_i_,_de,_i_,_ru,_cr,_ret
		.BYTE	___,_ya,_ma,_ga,_ta,_lt,_ke,_tt,___,_ya,_tu,_ra,___,_e_,_n_,_so,_ku,_ki,_bu,_n_,_da,_ze,_cr,_eol
_sc2_msg02:
		.BYTE	_ko,_no,___,_ta,_i_,_i_,_ku,_ka,_n_,_no,_na,_ka,_ga,___,_su,_be,_te,___,_BE,_NI,_YA,_i_,_ta,_de,_ret
		.BYTE	_si,_ki,_ra,_re,_ta,___,_to,_ri,_si,_ra,_be,_si,_tu,_ni,___,_na,_tt,_te,_i_,_ru,_yo,_u_,_da,_ze,_cr,_eol
_sc2_msg03:
		.BYTE	___________________,_lt,_so,_re,_de,_yo,_OO,___,_na,_n_,_te,_yu,_u_,_ka,_str,_dot,_dot,_dot,_eol
_sc2_msg04:
		.BYTE	___________________,_lt,_ma,_a_,___,_yo,_u_,_su,_ru,_ni,_str,_dot,_dot,_dot,_eol
_sc2_msg05:
		.BYTE	_na,_n_,_da,_ka,___,_DO,_A_,_no,_mu,_ko,_u_,_ga,___,_sa,_wa,_ga,_si,_i_,_ze,_cr,_eol
_sc2_msg06:
		.BYTE	___________________,_lt,_O_,_RE,_ta,_ti,_ha,_col,_zi,_yu,_u_,_ka,_ku,_me,_i_,_no,_da,_na,_str,_dot,_dot,_dot,_eol
_sc2_msg07:
		.BYTE	___________________,_lt,_i_,_si,_yy,___,_yo,_n_,_de,_ku,_re,_str,_cr,_eol
_sc2_msg08:
		.BYTE	___________________,_lt,_be,_n_,_zi,_oo,___,_i_,_ka,_se,_str,_cr,_eol
_sc2_msg09:
		.BYTE	___________________,_lt,_ha,_ra,_he,_tt,_te,_n_,_da,_yo,_str,_cr,_eol
_sc2_msg0A:
		.BYTE	_______,_ka__ne__da,_lt,_qe,_ex,_dot,_dot,_dot,_ret
		.BYTE	_______________________,_ko,_i_,_tu,___,_do,_tt,_ka,_de,___,_mi,_ta,_yo,_u_,_na,_dot,_dot,_dot,_eol
_sc2_msg0B:
		.BYTE	_______,_ka__ne__da,_lt,_qe,_ex,_dot,_dot,_dot,_ret
		.BYTE	_______________________,_a_,_tt,_ex,___,_sa,_tt,_ki,_no,___,_o_,_n_,_na,_no,_KO,_da,_ex,_ret
		.BYTE	_______________________,_ti,_oo,_tt,_to,___,_o_,_ti,_yy,_ni,___,_sa,_so,_tt,_te,_mi,_yo,_str,_tt,_to,_cr,_eol
_sc2_msg0C:
		.BYTE	_O_,_RE,_ga,___,_o_,_n_,_na,_no,_KO,_ni,___,_ha,_na,_si,_ka,_ke,_yo,_u_,_to,_su,_ru,_to,_ret
		.BYTE	_to,_tu,_ze,_n_,___,_ha,_n_,_se,_i_,_hu,_ga,_ku,_se,_i_,_ga,___,_hi,_to,_ri,___,_ta,_ti,_a_,_ga,_tt,_te,_ret
		.BYTE	_si,_uu,_ri,_uu,_u_,_da,_n_,_no,___,_PI,_N_,_wo,___,_nu,_ki,_ya,_ga,_tt,_ta,_ex,_eol
_sc2_msg0D:
		.BYTE	_A_,_str,_MI,_str,_ha,___,_si,_uu,_ri,_uu,_u_,_da,_n_,_wo,___,_mo,_tt,_te,_i_,_tt,_ta,_cr,_eol
_sc2_msg0E:
		.BYTE	___________,_ka,_i_,_lt,_ke,_i_,_sa,_tu,_to,_A_,_str,_MI,_str,_ga,___,_ki,_oo,_u_,_ri,_oo,_ku,_si,_te,_ret
		.BYTE	_______________________,_ha,_n_,_se,_i_,_hu,_bu,_n_,_si,_ga,_ri,_to,___,_ki,_ta,_ka,_col,_ret
		.BYTE	_______________________,_a_,_str,_a_,_dot,_dot,_dot,_eol
_sc2_msg0F:
		.BYTE	_A,_K,_I,_R,_A,___,_HU,_AA,_MI,_KO,_N_,___,_ha,_tu,_ba,_i_,_ti,_uu,_u_,_qe,_eol
_sc2_msg10:
		.BYTE	_______,_ka__ne__da,_lt,_O_,_I_,_ex,___,_ya,_ma,_ga,_ta,_col,___,_ni,_ge,_ru,_n_,_da,_tt,_ex,_ret
		.BYTE	___,_ya,_ma,_ga,_ta,_lt,_o_,_u_,_ex,___,_mi,_n_,_na,___,_i_,_ku,_zo,_tt,_ex,_ret
		.BYTE	___,_A_,_str,_MI,_str,_lt,_KO,_RA,_str,_TT,___,_ma,_te,_tt,_ex,___,_da,_tt,_so,_u_,_da,_str,_tt,_ex,_eol
_sc2_msg12:
		.BYTE	_______,_ka__ne__da,_lt,_ko,_n_,_no,_ya,_ro,_str,_tt,_ex,___,_so,_i_,_tu,_wo,___,_yo,_ko,_se,_tt,_ex,_ret
		.BYTE	_O_,_RE,_ha,___,_ya,_tu,_ni,___,_to,_bi,_ka,_ka,_tt,_te,___,_si,_uu,_ri,_uu,_u_,_da,_n_,_wo,_ret
		.BYTE	_u_,_ba,_i_,_to,_ro,_u_,_to,_si,_ta,_ex,_eol
_sc2_msg13:
		.BYTE	_si,_ka,_si,___,_si,_uu,_ri,_uu,_u_,_da,_n_,_ha,___,_BA,_KU,_HA,_TU,_si,_te,_si,_ma,_tt,_ta,_dot,_dot,_dot,_eol
_sc2_msg14:
		.BYTE	_he,_tt,_ex,___,_o_,_n_,_na,_no,_ko,_zi,_yy,_n_,_ex,_ret
		.BYTE	_o_,_ti,_yy,_ni,___,_sa,_so,_o_,_str,_tt,_to,_cr,_eol
_sc2_msg15:
		.BYTE	_______,_ka__ne__da,_lt,_mi,_n_,_na,_ex,___,_hu,_se,_ru,_n_,_da,_tt,_ex,_ret
		.BYTE	_O_,_RE,_no,_hi,_to,_ko,_e_,_de,___,_a_,_wa,_te,_te,_i_,_ta,___,_re,_n_,_ti,_uu,_u_,_mo,_ret
		.BYTE	_yu,_ka,_ni,___,_hu,_se,_te,___,_na,_ri,_yu,_ki,_wo,___,_mi,_ma,_mo,_tt,_ta,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_eol
_sc2_msg16:
		.BYTE	_1,_2,_ga,_tu,___,_2,_5,_ni,_ti,___,_RI,_RI,_str,_ma,_tu,_za,_ka,___,_KO,_N_,_SA,_str,_TO,_qe,_ret
		.BYTE	_to,_u_,_ta,_i_,_i_,_ku,_ka,_n_,_da,_tt,_te,_yo,_OO,_cr,___,_da,_re,_da,_i_,_col,___,_so,_re,_tt,_te,_cr,_eol
_sc2_msg17:
		.BYTE	___,_A_,_str,_MI,_str,_lt,_KO,_RA,_AA,_ex,___,_zi,_yy,_ma,_da,_tt,___,_do,_ke,_tt,_ex,_eol
_sc2_msg18:
		.BYTE	___,_ga,_ku,_se,_i_,_lt,_an0,_zi,_yu,_u_,_ka,_ku,_me,_i_,_str,_II,_ex,___,_BA,_N_,_ZA,_I_,_ex,_ex,_aof,_ret
		.BYTE	_YA,_col,___,_YA,_BA,_I_,_ze,___,_ko,_ri,_yy,_str,_cr,_eol
_sc2_msg19:
		.BYTE	_______,_ka__ne__da,_lt,_o_,_do,_tt,_te,_DA,_ME,_na,_ra,___,_hu,_se,_ru,_si,_ka,_na,_i_,_ex,_ret
		.BYTE	_______________________,_mi,_n_,_na,___,_hu,_se,_ru,_n_,_da,_ex,_eol
_sc2_msg1A:
		.BYTE	___,_A_,_str,_MI,_str,_lt,_dot,_dot,_dot,_dot,_o_,_ma,_e_,_ra,_col,___,_a_,_ya,_si,_ge,_na,_ret
		.BYTE	_______________________,_si,_n_,_ko,_u_,_si,_uu,_u_,_ki,_oo,_u_,_da,_n_,_ta,_i_,_no,_ret
		.BYTE	_______________________,_re,_n_,_ti,_uu,_u_,_da,_na,_cr,_ret
		.BYTE	_______________________,_ko,_tt,_ti,_he,_ko,_i_,_ex,_eol
_sc2_msg1C:
		.BYTE	___,_A_,_str,_MI,_str,_lt,_hu,_tt,_col,_hu,_ha,_tu,_da,_ex,___,_to,_tt,_tu,_ka,_ma,_e_,_ro,_ex,_ret
		.BYTE	___,_ga,_ku,_se,_i_,_lt,_hi,_e_,_e_,_tt,___,_GO,_col,___,_GO,_ME,_N_,_na,_sa,_str,_i_,_ex,_ret
		.BYTE	_ret
		.BYTE	_ga,_ku,_se,_i_,_ha,___,_hu,_ku,_ro,_da,_ta,_ki,_ni,_sa,_re,_te,_i_,_ru,_cr,_eol
_sc2_msg1D:
		.BYTE	_DO,_SU,_TT,___________,_GA,_SU,_TT,___________,_DO,_SU,_ex,_ret
		.BYTE	___,_A_,_str,_MI,_str,_lt,_yo,_si,___,_mo,_u_,_i_,_i_,_da,_ro,_u_,_cr,_ret
		.BYTE	_______________________,_tu,_re,_te,_yu,_ke,_dot,_dot,_dot,_dot,_dot,_dot,_cr,_ret
		.BYTE	_______________________,_a_,_to,_de,_ta,_tt,_pu,_ri,___,_si,_bo,_tt,_te,_ya,_ru,_ex,_eol
_sc2_msg1E:
		.BYTE	___,_ya,_ma,_ga,_ta,_lt,_BA,_KA,_YA,_RO,_str,_TT,_ex,_ret
		.BYTE	_______________________,_si,_nu,_n_,_na,_ra,___,_hi,_to,_ri,_de,___,_ku,_bi,_de,_mo,_ret
		.BYTE	_______________________,_ku,_ku,_tt,_te,___,_si,_ne,$89,_str,_ex,___,_A_,_HO,_str,_ex,___,_TA,_KO,_str,_ex,_eol
_sc2_msg1F:
		.BYTE	___,_A_,_str,_MI,_str,_lt,_an0,_o_,_ma,_e_,_ta,_ti,_col,_mo,_u_,_ka,_e_,_tt,_te,_i_,_i_,_zo,_cr,_ret
		.BYTE	_______________________,_ga,_tt,_ko,_u_,_ni,_ha,___,_re,_n_,_ra,_ku,___,_si,_to,_i_,_ta,_ka,_ra,_na,_ex,_aof,_ret
		.BYTE	_ret
		.BYTE	_ret
		.BYTE	_a_,_no,_KO,_wo,___,_na,_n_,_to,_ka,___,_tu,_re,_da,_se,_na,_i_,_ka,_na,_AA,_dot,_dot,_dot,_dot,_dot,_cr,_eol
_sc2_msg20:
		.BYTE	_to,_col,_to,_tu,_ze,_n_,___,_hu,_ha,_tu,_da,_to,___,_o_,_mo,_tt,_te,_i_,_ta,_ret
		.BYTE	_si,_uu,_ri,_uu,_u_,_da,_n_,_ga,___,_BA,_KU,_HA,_TU,_si,_te,_si,_ma,_tt,_ta,_ex,_eol
_sc2_msg21:
		.BYTE	_______,_ka__ne__da,_lt,_YA,_BA,_I_,_TT,_ret
		.BYTE	_______________________,_a_,_no,_KO,_no,___,_zi,_uu,_n_,_ba,_n_,_ga,___,_mo,_u_,_su,_gu,_ret
		.BYTE	_______________________,_ma,_wa,_tt,_te,_ku,_ru,_zi,_yy,_n_,_ka,_yo,_str,_cr,_eol
_sc2_msg22:
		.BYTE	_______,_a_,_no,_KO,___,_a_,_se,_tt,_te,_ru,_ze,_cr,_ret
		.BYTE	_______,_a_,_str,_a_,___,_na,_ki,_so,_u_,_na,___,_ka,_o_,_si,_te,_ru,_yo,_str,_cr,_eol
_sc2_msg23:
		.BYTE	_mi,_n_,_na,___,_HO,_TT,_to,_si,_te,_ru,_ze,_col,_ret
		.BYTE	_si,_ka,_si,___,_a_,_se,_tt,_ta,_na,_col,_ret
		.BYTE	_a_,_no,_KO,___,_mo,_u_,_su,_gu,___,_to,_ri,_si,_ra,_be,_da,_na,_a_,_dot,_dot,_dot,_dot,_ret
		.BYTE	_na,_n_,_to,_ka,___,_tu,_re,_da,_si,_ta,_i_,_no,_ni,_dot,_dot,_dot,_dot,_eol
_sc2_msg24:
		.BYTE	_______,_ka__ne__da,_lt,_ti,_oo,_tt,_to,___,_O_,_ZI,_SA,_N_,_ex,_ret
		.BYTE	_______________________,_a_,_no,_col,___,_A_,_I_,_TU,_mo,___,_O_,_RE,_no,_na,_ka,_ma,_na,_n_,_da,_ex,_ret
		.BYTE	_______________________,_tu,_re,_te,_tt,_te,___,_i_,_i_,_de,_si,_oo,_ex,_ret
		.BYTE	___,_A_,_str,_MI,_str,_lt,_an0,_na,_ni,_str,_II,_ex,_aof,_eol
_sc2_msg25:
		.BYTE	___,_A_,_str,_MI,_str,_lt,_an0,_da,_re,_ga,___,_o_,_zi,_sa,_n_,_da,_to,_col,___,_ko,_no,_ya,_ro,_u_,_ex,_ret
		.BYTE	_______________________,_i_,_i_,_ka,_col,___,_ko,_zo,_u_,_ex,___,_O_,_RE,_ha,___,_ma,_da,_ret
		.BYTE	_______________________,_2,_5,_da,_si,_col,___,_ke,_tt,_ko,_n_,_mo,___,_si,_te,_na,_i_,_n_,_da,_ex,_ret
		.BYTE	_______________________,_ku,_ti,_no,_ki,_ki,_ka,_ta,_ni,___,_ki,_wo,_tu,_ke,_ro,_ex,_aof,_eol
_sc2_msg26:
		.BYTE	___,_A_,_str,_MI,_str,_lt,_an0,_yo,_si,_tt,_ex,_ret
		.BYTE	_______________________,_so,_i_,_tu,_mo,___,_tu,_re,_te,_i_,_tt,_te,_yo,_si,_ex,_ex,_aof,_eol
_sc2_msg27:
		.BYTE	_RA,_TT,_KI,_str,_ex,_ret
		.BYTE	_ko,_u_,_si,_te,___,_O_,_RE,_ta,_ti,_ha,___,_ta,_i_,_i_,_ku,_ka,_n_,_ka,_ra,___,_de,_ru,_ko,_to,_ga,_ret
		.BYTE	_de,_ki,_ta,_cr,_ret
		.BYTE	_ka,_no,_zi,_oo,_mo,___,_i_,_tt,_si,_oo,_ni,_ne,_ex,_eol
_sc2_msg28:
		.BYTE	_______,_ka__ne__da,_lt,_a_,_re,_de,_mo,___,_da,_n_,_so,_u_,_si,_te,_ru,_tu,_mo,_ri,_ka,_na,_qe,_eol
_sc2_msgA2:
		.BYTE	_______,_ka__ne__da,_lt,_hi,_e_,_str,_tt,___,_o_,_col,_o_,_ka,_str,_sa,_str,_n_,_ex,_eol
_sc2_msgBA:
		.BYTE	___,_ga,_ku,_se,_i_,_lt,_ex,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_ret
		.BYTE	_______________________,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_ret
		.BYTE	_______________________,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_ret
		.BYTE	_______________________,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_dot,_a_,_re,_qe,_eol

;_sc2_msg11:
;		.BYTE	_ka__ne__da,_ta,_ti,_ha,___,_A_,_str,_MI,_str,_ni,___,_tu,_ka,_ma,_tt,_te,_si,_ma,_i_,_col,_ret
;		.BYTE	_si,_oo,_u_,_ne,_n_,_i_,_n_,_o_,_ku,_ri,_ni,___,_na,_ri,_ma,_si,_ta,_cr,_eol
;_sc2_msg29:
;		.BYTE	_______,_ka__ne__da,_lt,_he,_he,_tt,___,_SU,_I_,_MA,_se,_str,_n_,_ex,_eol

		SECTION_END		F2
