
		SECTION_START	F17

		MSG_START	_scene17_msg_lib
		MSG_IDX_SP	_sc17_msg76					; scene 17 msg
		MSG_IDX_SP	_sc17_msg77					; scene 17 msg
		MSG_IDX_SP	_sc17_msg78					; scene 17 msg
		MSG_IDX_SP	_sc17_msg79					; scene 17 msg
		MSG_IDX_SP	_sc17_msg7A					; scene 17 msg
		MSG_IDX_SP	_sc17_msg7B					; scene 17 msg
		MSG_IDX_SP	_sc17_msg84					; scene 17 msg
		MSG_IDX_SP	_sc17_msg86					; scene 17 msg
		MSG_IDX_SP	_sc17_msg8C					; scene 17 msg
		MSG_IDX_SP	_sc17_msgB6					; scene 17 msg
		MSG_IDX_SP	_sc11_12_13_msg97			; scenes 11,12,13 msg
		MSG_IDX_SP	_sc11_15_msg96				; scenes 11,15 msg
		MSG_IDX_SP	_sc13_15_msg99				; scenes 13,15 msg
		MSG_IDX_SP	_sc13_15_msg9A				; scenes 13,15 msg
		MSG_IDX_SP	_sc13_15_msg9B				; scenes 13,15 msg
		MSG_IDX_SP	_sc13_15_msg9E				; scenes 13,15 msg
		MSG_IDX_SP	_sc13_15_msg9F				; scenes 13,15 msg
		MSG_IDX_SP	_sc15_16_msgC9				; scenes 15,16 msg
		MSG_IDX_SP	_sc15_16_msgCB				; scenes 15,16 msg
		MSG_IDX_SP	_sc15_16_msgC5				; scenes 15,16 msg
		MSG_IDX_SP	_sc15_16_msgC7				; scenes 15,16 msg
		MSG_IDX_SP	_sc15_16_msgCA				; scenes 15,16 msg
		MSG_IDX_SP	_sc15_16_msgC8				; scenes 15,16 msg
		MSG_IDX_SP	_sc15_16_msgC6				; scenes 15,16 msg
		MSG_IDX_SP	_sc2_13_msgA0				; scenes 2,13 msg
		MSG_IDX_SP	_sc2_13_15_16_msg82			; scenes 2,13,15,16 msg
		MSG_IDX_SP	_sc2_15_msgA1				; scenes 2,15 msg
		MSG_IDX_SP	_sc2_6_msg83				; scenes 2,6 msg
		MSG_IDX_SP	_sc2_F_10_12_13_msg85		; scenes 2,F,10,12,13 msg
		MSG_IDX_SP	_sc5_6_msgA4				; scenes 5,6 msg
		MSG_IDX_SP	_sc5_6_15_msgAB				; scenes 5,6,15 msg
		MSG_IDX_SP	_sc5_A_msg7F				; scenes 5,A msg
		MSG_IDX_SP	_sc6_15_msg88				; scenes 6,15 msg
		MSG_IDX_SP	_sc6_15_msg89				; scenes 6,15 msg
		MSG_IDX_SP	_sc8_A_msg8F				; scenes 8,A msg
		MSG_IDX_SP	_scA_10_msg94				; scenes A,10 msg
		MSG_IDX_SP	_scA_B_msgA8				; scenes A,B msg
		MSG_IDX_SP	_scA_B_msgA7				; scenes A,B msg
		MSG_IDX_SP	_scA_B_msgA6				; scenes A,B msg
		MSG_IDX_SP	_scA_B_msgAA				; scenes A,B msg
		MSG_IDX_SP	_scA_B_msgAF				; scenes A,B msg
		MSG_IDX_SP	_scA_B_msgB0				; scenes A,B msg
		MSG_IDX_SP	_scA_B_msgB1				; scenes A,B msg
		MSG_IDX_SP	_scA_B_msgB2				; scenes A,B msg
		MSG_IDX_SP	_scA_B_msgA9				; scenes A,B msg
		MSG_IDX_SP	_scC_15_msgA5				; scenes C,15 msg
		MSG_IDX_SP	_scC_D_13_16_msg90			; scenes C,D,13,16 msg
		MSG_IDX_SP	_scD_E_13_msg91				; scenes D,E,13 msg
		MSG_IDX_SP	_scF_12_13_15_msg93			; scenes F,12,13,15 msg
;		MSG_IDX_SP	_msg00BF_placeholder		; -unused-
;		MSG_IDX_SP	_msg00C1_placeholder		; -unused-
;		MSG_IDX_SP	_sc17_msgA3					; -unused-
_sc17_msg76:
		.BYTE	_______,_MI,_YA,_KO,_lt,_o_,_str,_col,___,_so,_ti,_ha,___,_so,_no,_mi,_wo,___,_se,_i_,_zi,_oo,_u_,_na,_ru,_ret
		.BYTE	_______________________,_ho,_no,_o_,_de,___,_ki,_yo,_me,_col,___,_ka,_na,_ra,_zu,_ya,_ret
		.BYTE	_______________________,_ma,_i_,_mo,_do,_tt,_te,_ku,_ru,_no,_zi,_yy,_AA,_str,_ex,_eol
_sc17_msg77:
		.BYTE	_______,_MI,_YA,_KO,_lt,_o_,_str,_col,___,_so,_ti,_ha,___,_ya,_me,_ta,_i_,_to,___,_mo,_u_,_su,_no,_ka,_ex,_ret
		.BYTE	___________________,_A,_BO,_TA,_N_,___,_ha,_i_,_ex,_ret
		.BYTE	___________________,_B,_BO,_TA,_N_,___,_i_,_i_,_e_,_ex,_eol
_sc17_msg78:
		.BYTE	_______,_MI,_YA,_KO,_lt,_A_,_KI,_RA,_sa,_ma,_no,___,_me,_za,_me,_ha,___,_ti,_ka,_i_,_ex,_ret
		.BYTE	_______________________,_so,_ti,_no,_ti,_ka,_ra,_ga,___,_hi,_tu,_yo,_u_,_na,_no,_zi,_yy,_col,_ret
		.BYTE	_______________________,_ko,_ko,_ro,_si,_te,___,_ka,_ka,_re,_yo,_str,_eol
_sc17_msg79:
		.BYTE	_______,_MI,_YA,_KO,_lt,_ba,_ka,_mo,_no,_me,_col,___,_ti,_ga,_tt,_te,_o_,_ro,_u_,_ga,_tt,_ex,_ret
		.BYTE	_______________________,_mo,_u_,_i_,_ti,_do,___,_ni,_uu,_u_,_ri,_oo,_ku,___,_su,_ru,_no,_zi,_yy,_ex,_eol
_sc17_msg7A:
		.BYTE	_______,_ka__ne__da,_lt,_an0,_O_,_RE,_no,_PA,_SU,_WA,_str,_DO,_ha,_ret
		.BYTE	_ret
		.BYTE	_______________________________,_______________________________,_______________,_da,_ze,_str,_ex,_ex,_aof,_eol
_sc17_msg7B:
		.BYTE	_______,_MI,_YA,_KO,_lt,_o_,_str,_col,___,_yo,_ku,_zo,___,_mo,_do,_tt,_te,_ki,_ta,_no,_OO,_ex,_ret
		.BYTE	_______________________,_so,_ti,_no,_PA,_SU,_WA,_str,_DO,_wo,___,_ni,_uu,_u_,_ri,_oo,_ku,_ret
		.BYTE	_______________________,_su,_ru,_no,_zi,_yy,_AA,_str,_ex,_eol
_sc5_A_msg7F:
		.BYTE	_______,_ka__ne__da,_lt,_GO,_KU,_TT,___,_GO,_KU,_TT,___,_PU,_HA,_str,_TT,_cr,_eol
_sc2_13_15_16_msg82:
		.BYTE	_______,_ka__ne__da,_lt,_u_,_wa,_str,_tt,___,_ya,_me,_ro,_str,_tt,_ex,_eol
_sc2_6_msg83:
		.BYTE	_______,_ka__ne__da,_lt,_a_,_wa,_col,_a_,_wa,_col,_a_,_wa,_col,_do,_col,_do,_u_,_si,_yo,_u_,_dot,_dot,_dot,_ex,_eol
_sc17_msg84:
		.BYTE	_ka__ne__da,_si,_oo,_u_,_ne,_n_,_ha,___,_si,_n_,_de,_si,_ma,_i_,_ma,_si,_ta,_dot,_dot,_dot,_dot,_dot,_dot,_eol
_sc2_F_10_12_13_msg85:
		.BYTE	_______,_ka__ne__da,_lt,_dot,_dot,_dot,_dot,_dot,_dot,_eol
_sc17_msg86:
		.BYTE	_GE,_str,_MU,_O_,_str,_BA,_str,_de,_su,_ex,_ret
		.BYTE	_mo,_u_,_i_,_ti,_do,___,_ya,_ri,_na,_o_,_si,_te,_ku,_da,_sa,_i_,_cr,_ret
		.BYTE	_A,_BO,_TA,_N_,_______,_ya,_ru,_ex,_ret
		.BYTE	_B,_BO,_TA,_N_,_______,_mo,_u_,_ya,_me,_ru,_ex,_eol
_sc6_15_msg88:
		.BYTE	_______,_ka__ne__da,_lt,_te_tsu__o_,_col,_do,_u_,_si,_ta,_AA,_str,_ex,_eol
_sc6_15_msg89:
		.BYTE	_______,_te_tsu__o_,_lt,_an0,_u_,_wa,_a_,_str,_tt,_col,_HA,_A_,_str,_TT,___,_HA,_A_,_str,_TT,_ret
		.BYTE	_______________________,_HA,_A_,_str,_TT,___,_HA,_A_,_str,_TT,___,_HA,_A_,_str,_TT,_cr,_ret
		.BYTE	_______________________,_u_,_str,_u_,_col,___,_o_,_str,_tt,_cr,_aof,_eol
_sc17_msg8C:
		.BYTE	_ka__ne__da,_si,_oo,_u_,_ne,_n_,_ha,___,_A_,_str,_MI,_str,_ni,_tu,_ka,_ma,_ri,_col,_ret
		.BYTE	_si,_oo,_u_,_ne,_n_,_i_,_n_,_o_,_ku,_ri,_ni,___,_na,_ri,_ma,_si,_ta,_cr,_eol
_sc17_msgB6:
		.BYTE	_______,_MI,_YA,_KO,_lt,_so,_ti,_no,_PA,_SU,_WA,_str,_DO,_ha,_ret
		.BYTE	_password,_ret
		.BYTE	_______________________,_zi,_yy,___,_ke,_tt,_si,_te,___,_wa,_su,_re,_ru,_de,_na,_i_,_zo,_cr,_eol
_sc8_A_msg8F:
		.BYTE	_______,_ka__ne__da,_lt,_A_,_RE,_TT,___,_na,_n_,_da,___,_ko,_ko,_ha,_qe,_eol
_scC_D_13_16_msg90:
		.BYTE	_______,_ka__ne__da,_lt,_u_,_wa,_AA,_str,_TT,_ex,___,_gu,_bu,_tt,_dot,_dot,_dot,_eol
_scD_E_13_msg91:
		.BYTE	___________,_KE,_I_,_lt,_BA,_KA,_str,_TT,_ex,_ret
		.BYTE	_______,_ka__ne__da,_lt,_u_,_wa,_AA,_str,_TT,_ex,_ret
		.BYTE	___________,_KE,_I_,_lt,_ki,_yy,_a_,_str,_tt,_ex,_ex,_eol
_scF_12_13_15_msg93:
		.BYTE	_______,_te_tsu__o_,_lt,_an0,_u_,_wa,_AA,_str,___,_a_,_a_,_str,_tt,_cr,_aof,_eol
_scA_10_msg94:
		.BYTE	_DO,_A_,_ni,_ha,___,_ka,_gi,_ga,___,_ka,_ka,_tt,_te,_i_,_ma,_su,_cr,_eol
_sc11_15_msg96:
		.BYTE	_______,_ka__ne__da,_lt,_an0,_ba,_ka,_ya,_ro,_u_,_str,_tt,_ex,_aof,_eol
_sc11_12_13_msg97:
		.BYTE	___________,_ka,_i_,_lt,_ka__ne__da,_AA,_str,_tt,_ex,_eol
_sc13_15_msg99:
		.BYTE	_O_,_RE,_ha,___,_RE,_str,_ZA,_str,_no,_ne,_ra,_i_,_wo,___,_tu,_ke,_ta,_cr,_eol
_sc13_15_msg9A:
		.BYTE	_RE,_str,_ZA,_str,_ga,___,_te_tsu__o_,_no,_mu,_ne,_ni,___,_me,_i_,_ti,_uu,_u_,_si,_ta,_ex,_ret
		.BYTE	_______,_te_tsu__o_,_lt,_u_,_tt,___,_gu,_u_,_str,_tt,_cr,_ret
		.BYTE	_______,_ka__ne__da,_lt,_ya,_tt,_ta,_ze,_ex,___,_ya,_ma,_ga,_ta,_AA,_ex,_ex,_eol
_sc13_15_msg9B:
		.BYTE	_te_tsu__o_,_ha,___,_si,_n_,_de,_si,_ma,_i_,_ma,_si,_ta,_dot,_dot,_dot,_eol
_sc13_15_msg9E:
		.BYTE	_te_tsu__o_,_no,_ka,_mi,_no,_ke,_ga,___,_sa,_ka,_da,_tt,_te,_ki,_ta,_cr,_ret
		.BYTE	_te_tsu__o_,_ha,___,_si,_oo,_u_,_ge,_ki,_ha,_wo,___,_to,_ba,_su,_tu,_mo,_ri,_da,_ex,_eol
_sc13_15_msg9F:
		.BYTE	_RE,_str,_ZA,_str,_ga,___,_ha,_zu,_re,_ta,_ex,_eol
_sc2_13_msgA0:
		.BYTE	_______,_ka__ne__da,_lt,_A_,_RA,_ex,___,_e_,_tt,_sa,_tt,_sa,_str,_tt,_dot,_dot,_dot,_ret
		.BYTE	_ret
		.BYTE	_______________________,_dot,_dot,_dot,_da,_col,_da,_me,_da,___,_ki,_ki,_me,_ga,_na,_i_,_ex,_eol
_sc2_15_msgA1:
		.BYTE	_______,_ka__ne__da,_lt,_NA,_U_,_dot,_MA,_KU,_dot,_SA,_dot,_MA,_N_,_dot,_DA,___,_e_,_to,_col,_e_,_str,_tt,_to,_ret
		.BYTE	_______________________,_dot,_dot,_dot,_eol
_sc5_6_msgA4:
		.BYTE	_______,_o_,_to,_ko,_lt,_dot,_dot,_dot,_dot,_dot,_dot,_eol
_scC_15_msgA5:
		.BYTE	_mo,_u_,___,_ma,_ni,_a_,_i_,_so,_u_,_ni,___,_na,_i_,_ex,_ex,_eol
_scA_B_msgA6:
		.BYTE	_TE,_RO,_RI,_SU,_TO,_lt,_an0,_RA,_BO,_ni,___,_se,_n_,_ni,_uu,_u_,___,_su,_ru,_n_,_da,_to,_OO,_ex,_ret
		.BYTE	_______________________,_si,_oo,_u_,_ki,_ka,_ex,_ret
		.BYTE	_______________________,_ko,_no,_ma,_e_,_no,___,_GA,_KI,_n_,_to,_ki,_da,_tt,_te,_dot,_dot,_dot,_aof,_eol
_scA_B_msgA7:
		.BYTE	_TE,_RO,_RI,_SU,_TO,_lt,_an0,_si,_uu,_u_,_go,_to,_ni,___,_ha,_tt,_ko,_u_,_si,_te,_i_,_ru,_ret
		.BYTE	_______________________,_RA,_BO,_no,_PA,_SU,_da,_dot,_dot,_dot,_aof,_eol
_scA_B_msgA8:
		.BYTE	_TE,_RO,_RI,_SU,_TO,_lt,_an0,_dot,_dot,_dot,_a_,_ta,_ra,_si,_i_,_ZI,_TT,_KE,_N_,_TA,_I_,_II,_str,_qe,_aof,_eol
_scA_B_msgA9:
		.BYTE	_______,_RI,_UU,_U_,_lt,_an1,_ki,_uu,_u_,_si,_ga,_i_,_no,___,_ko,_u_,_so,_ku,_de,___,_zi,_ko,_wo,_ret
		.BYTE	_______________________,_o_,_ko,_si,_ta,___,_si,_oo,_u_,_ne,_n_,_ga,___,_RA,_BO,_ni,_ret
		.BYTE	_______________________,_si,_uu,_u_,_yo,_u_,___,_sa,_re,_te,_i_,_ru,_dot,_dot,_dot,_aof,_eol
_scA_B_msgAA:
		.BYTE	_______,_RI,_UU,_U_,_lt,_an1,_si,_oo,_ku,_gi,_oo,_u_,___,_ku,_n_,_re,_n_,_ko,_u_,_no,_ret
		.BYTE	_______________________,_se,_i_,_to,_ra,_si,_i_,_n_,_da,_ga,_col,___,_a_,_ta,_ra,_si,_i_,_ret
		.BYTE	_______________________,_ZI,_N_,_TA,_I_,_ZI,_TT,_KE,_N_,_no,___,_ta,_i_,_si,_oo,_u_,_to,_na,_tt,_te,_col,_ret
		.BYTE	_______________________,_i_,_ma,_dot,_dot,_dot,_aof,_eol
_sc5_6_15_msgAB:
		.BYTE	_______,_ka__ne__da,_lt,_an0,_te_tsu__o_,_str,_ex,_aof,_eol
_scA_B_msgAF:
		.BYTE	_______,_RI,_UU,_U_,_lt,_an1,_so,_u_,_da,_cr,___,_dot,_dot,_dot,_se,_n_,_si,_uu,_u_,___,_wa,_re,_wa,_re,_ga,_ret
		.BYTE	_______________________,_2,_6,_GO,_U_,_to,_yo,_ba,_re,_ru,___,_ZI,_TT,_KE,_N_,_TA,_I_,_wo,_ret
		.BYTE	_______________________,_tu,_re,_da,_so,_u_,_to,_si,_ta,___,_a_,_no,_ba,_n_,_dot,_dot,_dot,_aof,_eol
_scA_B_msgB0:
		.BYTE	_______,_RI,_UU,_U_,_lt,_an1,_ki,_n_,_ki,_uu,_u_,_no,___,_si,_re,_i_,_na,_n_,_da,_cr,_ret
		.BYTE	_______________________,_so,_re,_ni,___,_da,_n_,_do,_ri,_mo,___,_de,_ki,_te,_ru,_dot,_dot,_dot,_aof,_ret
		.BYTE	_ret,_eol
_scA_B_msgB1:
		.BYTE	___________,_KE,_I_,_lt,_an2,_ne,_du,_sa,_ma,_ka,_ra,_ne,_qe,_ex,___,_mo,_ku,_te,_ki,_ha,_qe,_aof,_eol
_scA_B_msgB2:
		.BYTE	_______,_RI,_UU,_U_,_lt,_an1,_a_,_ta,_ra,_si,_i_,_ZI,_TT,_KE,_N_,_TA,_I_,_no,___,_si,_oo,_u_,_sa,_i_,_na,_ret
		.BYTE	_______________________,_DE,_str,_TA,_da,_cr,_aof,_eol
_sc15_16_msgC5:
		.BYTE	_______,_te_tsu__o_,_lt,_an0,_o_,_str,_N_,___,_o_,_str,_N_,_cr,_aof,_ret
		.BYTE	_te_tsu__o_,_ha,___,_ka,_o_,_da,_ke,_ga,___,_ni,_n_,_ge,_n_,_no,_col,___,_ni,_ku,_no,_ka,_ta,_ma,_ri,_ret
		.BYTE	_da,_tt,_ta,_cr,_eol
_sc15_16_msgC6:
		.BYTE	_______,_te_tsu__o_,_lt,_an0,_HO,_GI,_YY,_str,_TT,_ex,_aof,_ret
		.BYTE	_DO,_RO,_DO,_RO,_no,___,_ni,_ku,_no,_ka,_ta,_ma,_ri,_ga,___,_sa,_ke,_bi,_go,_e_,_wo,_ret
		.BYTE	_a_,_ge,_te,_i_,_ta,_cr,_eol
_sc15_16_msgC7:
		.BYTE	_______,_te_tsu__o_,_lt,_an0,_ka__ne__da,_AA,_str,_TT,___,_ni,_ge,_ro,_OO,_str,_tt,_cr,_aof,_ret
		.BYTE	_______,_ka__ne__da,_lt,_ku,_tt,_so,_u_,_dot,_dot,_dot,_ret
		.BYTE	_______,_te_tsu__o_,_lt,_an0,_u_,_wa,_str,_tt,___,_HO,_GI,_YY,_str,_TT,_cr,_aof,_eol
_sc15_16_msgC8:
		.BYTE	_ni,_ku,_no,_ka,_ta,_ma,_ri,_ga,___,_hi,_ro,_ga,_ru,___,_SU,_TA,_ZI,_A_,_MU,_no,_ha,_si,_ni,_ret
		.BYTE	_KI,_YO,_KO,_col,___,_MA,_SA,_RU,_col,___,_TA,_KA,_SI,_ga,___,_su,_wa,_tt,_te,_i_,_ta,_cr,_ret
		.BYTE	_3,_ni,_n_,_no,_ma,_e_,_ni,_ha,___,_SA,_N_,_PU,_RU,_KE,_str,_SU,_ga,___,_o_,_ka,_re,_te,_i_,_ta,_cr,_eol
_sc15_16_msgC9:
		.BYTE	_hi,_ka,_ri,_ha,___,_SU,_TA,_ZI,_A_,_MU,_ma,_de,_mo,___,_o_,_o_,_i_,_tu,_ku,_si,_ta,_cr,_eol
_sc15_16_msgCA:
		.BYTE	_ya,_ga,_te,___,_hi,_ka,_ri,_ha,___,_BI,_RU,_wo,___,_ha,_ka,_i_,_si,_na,_ga,_ra,_col,_ret
		.BYTE	_ki,_uu,_u_,_si,_ga,_i_,_wo,___,_si,_n_,_si,_oo,_ku,___,_si,_ha,_zi,_me,_te,_i_,_tt,_ta,_cr,_eol
_sc15_16_msgCB:
		.BYTE	_hi,_ka,_ri,_ha,___,_ki,_oo,_da,_i_,_na,___,_hi,_ka,_ri,_no,_ta,_ma,_to,___,_na,_tt,_ta,_cr,_ret
		.BYTE	_ki,_uu,_u_,_si,_ga,_i_,_no,___,_ho,_to,_n_,_do,_ga,___,_hi,_ka,_ri,_ni,___,_no,_ma,_re,_ta,_dot,_dot,_dot,_eol
;_msg00BF_placeholder:
;		.BYTE	_0,_0,_B,_F,_eol
;_msg00C1_placeholder:
;		.BYTE	_0,_0,_C,_1,_eol
;_sc17_msgA3:
;		.BYTE	___________________,_DO,_U_,_str,_N_,_ex,_ex,_eol

		SECTION_END		F17
