
		SECTION_START	FD

		MSG_START	_sceneD_msg_lib
		MSG_IDX	_scD_msg00
		MSG_IDX	_scD_msg01
		MSG_IDX	_scD_msg02
		MSG_IDX	_scD_msg03
		MSG_IDX	_scD_msg04
		MSG_IDX	_scD_msg05
		MSG_IDX	_scD_msg06
		MSG_IDX	_scD_msg07
		MSG_IDX	_scD_msg08
		MSG_IDX	_scD_msg09
		MSG_IDX	_scD_msg0A
;		MSG_IDX	_scD_msg0B					; -unused-
		MSG_IDX	_scD_msg0C
		MSG_IDX	_scD_msg0D
		MSG_IDX	_scD_msg0E
_scD_msg00:
		.BYTE	_O_,_RE,_ha,___,_A_,_str,_MI,_str,_no,___,_F,_dot,_P,_dot,_H,_wo,___,_u_,_ba,_i_,_col,___,_KE,_I_,_wo,_ret
		.BYTE	_no,_se,_te,_col,___,_RA,_BO,_no,_na,_ka,_wo,___,_ni,_ge,_ma,_wa,_tt,_te,_i_,_ta,_cr,_ret
		.BYTE	_______,_ka__ne__da,_lt,_yo,_str,_si,_col,___,_da,_n_,_da,_n_,___,_wa,_ka,_tt,_te,_ki,_ta,_zo,_OO,_cr,_eol
_scD_msg01:
		.BYTE	___________,_KE,_I_,_lt,_ki,_yy,_a_,_str,_tt,_col,___,_A_,_str,_MI,_str,_yo,_ex,_ret
		.BYTE	_______,_ka__ne__da,_lt,_ma,_ka,_si,_to,_ke,_tt,_tu,_str,_no,_cr,_eol
_scD_msg02:
		.BYTE	_______,_mu,_se,_n_,_lt,_PI,_str,_TT,___,_GA,_GA,_str,_TT,___,_GA,_GA,_TT,_cr,_ret
		.BYTE	_______________________,_ta,_i_,_sa,_ni,___,_zi,_uu,_u_,_ka,_ki,_no,___,_si,_yo,_u_,_ki,_oo,_ka,_wo,_ret
		.BYTE	_______________________,_dot,_dot,_dot,_GA,_GA,_str,_TT,_cr,_ret
		.BYTE	_i_,_tu,_no,_ma,_ni,_ka,___,_mu,_se,_n_,_ki,_no,_SU,_I_,_TT,_TI,_wo,___,_i_,_re,_te,_si,_ma,_tt,_te,_ret
		.BYTE	_i_,_ta,_yo,_u_,_da,_cr,_eol
_scD_msg03:
		.BYTE	_______,_mu,_se,_n_,_lt,_na,_ni,_ka,_no,___,_ma,_ti,_ga,_i_,_de,_ha,___,_na,_i_,_ka,_col,_ret
		.BYTE	_______________________,_a_,_no,_si,_oo,_u_,_ne,_n_,_ha,___,_do,_u_,_mi,_te,_mo,___,_RA,_BO,_ni,_ret
		.BYTE	_______________________,_ni,_uu,_u_,_i_,_n_,_ti,_uu,_u_,_no,___,_ka,_n_,_zi,_yy,_da,_dot,_dot,_dot,_eol
_scD_msg04:
		.BYTE	_______,_ka__ne__da,_lt,_te_tsu__o_,_ha,___,_do,_ko,_da,_AA,_str,_ex,_ret
		.BYTE	___________,_KE,_I_,_lt,_da,_ma,_tt,_te,_ex,___,_BO,_RI,_UU,_str,_MU,_wo,___,_a_,_ge,_te,_cr,_eol
_scD_msg05:
		.BYTE	_______,_mu,_se,_n_,_lt,_GA,_GA,_str,_TT,___,_so,_no,_mo,_no,_ha,___,_bi,_oo,_u_,_si,_tu,_wo,_ret
		.BYTE	_______________________,_nu,_ke,_da,_si,_ta,___,_SI,_MA,___,_te_tsu__o_,___,_to,_i_,_u_,_ret
		.BYTE	_______________________,_ZI,_TT,_KE,_N_,_TA,_I_,___,_de,_a_,_ru,_cr,_eol
_scD_msg06:
		.BYTE	_______,_mu,_se,_n_,_lt,_BE,_BI,_str,_RU,_str,_MU,_he,___,_mu,_ka,_tt,_te,_i_,_ru,_to,_ret
		.BYTE	_______________________,_o_,_mo,_wa,_re,_ru,_dot,_dot,_dot,_GA,_str,_TT,_cr,_ret
		.BYTE	_______,_ka__ne__da,_lt,_te_tsu__o_,_ga,_AA,_qe,_ex,_eol
_scD_msg07:
		.BYTE	_______,_mu,_se,_n_,_lt,_GA,_str,_TT,___,_hi,_zi,_oo,_u_,_ni,___,_ki,_ke,_n_,_na,_ret
		.BYTE	_______________________,_zi,_oo,_u_,_ta,_i_,_da,_col,___,_i_,_ka,_se,_te,_ha,_na,_ra,_n_,_ex,_ret
		.BYTE	_______________________,_ku,_ri,_ka,_e_,_su,_col,___,_ze,_tt,_ta,_i_,_ni,___,_i_,_ka,_se,_te,_ha,_ret
		.BYTE	_______________________,_na,_ra,_n_,_ex,_eol
_scD_msg08:
		.BYTE	___________,_KE,_I_,_lt,_dot,_dot,_dot,_ko,_no,_tu,_ki,_a_,_ta,_ri,_ni,___,_BE,_BI,_str,_RU,_str,_MU,_ga,_ret
		.BYTE	_______________________,_a_,_ru,_wa,_cr,_ret
		.BYTE	_______,_ka__ne__da,_lt,_e_,_tt,_qe,_ret
		.BYTE	___________,_KE,_I_,_lt,_so,_ko,_he,___,_i_,_tt,_te,_ex,_eol
_scD_msg09:
		.BYTE	_______,_ka__ne__da,_lt,_A,_RU,_str,_MU,_qe,_ret
		.BYTE	___________,_KE,_I_,_lt,_na,_ni,___,_si,_te,_ru,_no,_col,_ret
		.BYTE	_______________________,_so,_re,_ga,___,_BE,_BI,_str,_RU,_str,_MU,_yo,_ex,_ret
		.BYTE	_______,_ka__ne__da,_lt,_e_,_tt,_qe,___,_a_,_tt,_col,_u_,_wa,_str,_tt,___,_to,_ma,_ra,_na,_i_,_str,_cr,_eol
_scD_msg0A:
		.BYTE	___________,_KE,_I_,_lt,_BU,_RE,_str,_KI,_ex,_ex,___,_BU,_RE,_str,_KI,___,_wa,_ka,_n_,_na,_i_,_no,_ret
		.BYTE	_______________________,_a_,_n_,_ta,_AA,_ex,_ret
		.BYTE	_______,_ka__ne__da,_lt,_O_,_RE,___,_ki,_oo,_u_,___,_me,_n_,_ki,_oo,_si,_oo,_u_,_ret
		.BYTE	_______________________,_mo,_tt,_te,_ne,_str,_n_,_da,_yo,_str,_ex,_eol
;_scD_msg0B:
;		.BYTE	_______,_ka__ne__da,_lt,_do,_tt,_ti,_ni,_i_,_ke,_ba,___,_i_,_i_,_n_,_da,_col,___,_i_,_tt,_ta,_i_,_ex,_ret
;		.BYTE	___________,_KE,_I_,_lt,_ma,_tt,_su,_gu,_yo,_dot,_dot,_dot,_ret
;		.BYTE	_______________________,_ko,_no,_ma,_ma,___,_ma,_tt,_su,_gu,_ni,_dot,_dot,_dot,_ret
;		.BYTE	_______,_ka__ne__da,_lt,_e_,_tt,_dot,_dot,_dot,_eol
_scD_msg0C:
		.BYTE	_______,_KI,_YO,_KO,_lt,_an0,_ha,_n_,_ni,_uu,_u_,_yo,_u_,_no,___,_E_,_RE,_BE,_str,_TA,_str,_ga,_a_,_ru,_no,_cr,_ret
		.BYTE	_______________________,_so,_re,_de,___,_ti,_ka,_8,_ka,_i_,_ma,_de,___,_i_,_ke,_ru,_wa,_cr,_aof,_eol
_scD_msg0D:
		.BYTE	_O_,_RE,_ta,_ti,_ha,___,_to,_u_,_to,_u_,___,_ti,_ka,_8,_ka,_i_,_ma,_de,___,_ya,_tt,_te,_ki,_ta,_ze,_cr,_eol
_scD_msg0E:
		.BYTE	___________________,_A,_BO,_TA,_N_,___,_u_,_tu,_ret
		.BYTE	___________________,_B,_BO,_TA,_N_,___,_ka,_wa,_su,_eol

		SECTION_END		FD
