
		SECTION_START	FB

		MSG_START	_sceneB_msg_lib
		MSG_IDX	_scB_msg00
		MSG_IDX	_scB_msg01
		MSG_IDX	_scB_msg02
		MSG_IDX	_scB_msg03
;		MSG_IDX	_scB_msg04						; -unused-
		MSG_IDX	_scB_msg05
		MSG_IDX	_scB_msg06
		MSG_IDX	_scB_msg07
		MSG_IDX	_scB_msg08
		MSG_IDX	_scB_msg09
		MSG_IDX	_scB_msg0A
		MSG_IDX	_scB_msg0B
		MSG_IDX	_scB_msg0C
		MSG_IDX	_scB_msg0D
		MSG_IDX	_scB_msg0E
		MSG_IDX	_scB_msg0F
		MSG_IDX	_scB_msg10
		MSG_IDX	_scB_msg11
		MSG_IDX	_scB_msg12
		MSG_IDX	_scB_msg13
_scB_msg00:
		.BYTE	_O_,_RE,_ha,___,_tu,_u_,_ki,_ko,_u_,_ka,_ra,___,_hi,_ki,_zu,_ri,_da,_sa,_re,_te,_si,_ma,_tt,_ta,_cr,_eol
_scB_msg01:
		.BYTE	_______,_ka__ne__da,_lt,_i_,_te,_tt,___,_i_,_te,_col,_i_,_te,_te,_te,$89,_col,_ret
		.BYTE	_______________________,_na,_ni,___,_su,_n_,_da,_yo,_OO,_cr,_eol
_scB_msg02:
		.BYTE	___________,_KE,_I_,_lt,_ka__ne__da,_ku,_n_,_dot,_dot,_dot,_eol
_scB_msg03:
		.BYTE	_______,_ka__ne__da,_lt,_ti,_oo,_tt,_to,___,_ma,_tt,_te,_ku,_re,_col,___,_ha,_na,_si,_wo,_dot,_dot,_dot,_ret
		.BYTE	_______________________,_O_,_RE,_no,_ha,_na,_si,_wo,___,_ki,_i_,_te,_ku,_re,_cr,_eol
;_scB_msg04:
;		.BYTE	___________,_KE,_I_,_lt,_an2,_ta,_su,_ke,_te,_mo,_ra,_tt,_ta,_no,_yo,_ex,_aof,_ret
;		.BYTE	_______,_ka__ne__da,_lt,_2,_ka,_i_,_mo,_ne,_str,_tt,_cr,_ret
;		.BYTE	_______,_RI,_UU,_U_,_lt,_an1,_wa,_re,_wa,_re,_ni,___,_ti,_ka,_du,_ku,_ta,_me,___,_ka,_mo,_si,_re,_n_,_cr,_aof,_eol
_scB_msg05:
		.BYTE	_______,_ka__ne__da,_lt,_O_,_RE,_no,_na,_ka,_ma,___,_na,_n_,_da,_yo,_col,___,_ki,_uu,_u_,_si,_ga,_i_,_de,_ret
		.BYTE	_______________________,_zi,_ko,_tt,_ta,_tt,_te,_no,_ha,_ex,_ret
		.BYTE	_______________________,_ha,_na,_si,_ga,___,_ki,_uu,_u_,_de,___,_si,_n_,_zi,_ra,_n_,_na,_i_,_ret
		.BYTE	_______________________,_de,_si,_oo,_u_,_ke,_do,_col,___,_ho,_n_,_to,_u_,_na,_n_,_de,_su,_cr,_ret
		.BYTE	_______________________,_i_,_tt,_si,_oo,_ni,___,_ha,_si,_tt,_te,_ta,_n_,_da,_yo,_col,___,_O_,_RE,_mo,_ex,_eol
_scB_msg06:
		.BYTE	_______,_ka__ne__da,_lt,_tu,_re,_te,_tt,_te,_ku,_re,_yo,_col,___,_RA,_BO,_HE,_dot,_dot,_dot,_eol
_scB_msg07:
		.BYTE	_______,_ka__ne__da,_lt,_ta,_no,_mu,_yo,_col,___,_ki,_ku,_ha,___,_i_,_tt,_to,_ki,_no,_ha,_zi,_tt,_te,_ret
		.BYTE	_______________________,_yu,_str,_de,_si,_oo,_u_,_col,___,_e_,_str,_tt,___,_i_,_wa,_na,_i_,_dot,_dot,_dot,_eol
_scB_msg08:
		.BYTE	_______,_RI,_UU,_U_,_lt,_an1,_na,_ni,_tt,___,_o_,_ma,_e_,___,_si,_tt,_te,_i_,_ru,_no,_ka,_tt,_qe,_aof,_eol
_scB_msg09:
		.BYTE	_KE,_I_,_no,_hi,_to,_ko,_to,_de,___,_ta,_su,_ke,_ra,_re,_ta,___,_O_,_RE,_ha,___,_ya,_tu,_ra,_no,_ret
		.BYTE	_he,_ya,_ni,___,_tu,_re,_te,_ko,_ra,_re,_ta,_cr,_ret
		.BYTE	_ya,_tu,_ra,_ha,___,_na,_ni,_ka,___,_so,_u_,_da,_n_,_ti,_uu,_u_,_da,_tt,_ta,_ze,_cr,___,_eol
_scB_msg0A:
		.BYTE	_______,_RI,_UU,_U_,_lt,_an1,_wa,_ka,_tt,_ta,_col,___,_o_,_ma,_e_,_mo,___,_ko,_i_,_ex,_ret
		.BYTE	_______________________,_ko,_re,_ga,___,_RA,_BO,_no,_PA,_SU,_da,_cr,_aof,_eol
_scB_msg0B:
		.BYTE	_KE,_I_,_ti,_yy,_n_,_ta,_ra,___,_O_,_ZI,_sa,_n_,_ta,_ti,_ni,___,_O_,_RE,_ta,_ti,_no,_ko,_to,_ret
		.BYTE	_ha,_na,_sa,_na,_i_,_ka,_ra,___,_ko,_ma,_tt,_ti,_yy,_u_,_ze,_str,_cr,_eol
_scB_msg0C:
		.BYTE	_______,_ka__ne__da,_lt,_ex,___,_te_tsu__o_,_no,_ko,_to,_da,_ze,_col,___,_so,_re,_tt,_te,_cr,_eol
_scB_msg0D:
		.BYTE	_a_,_no,_yo,_ru,_no,___,_si,_wa,_da,_ra,_ke,_no,_GA,_KI,_ga,___,_ZI,_TT,_KE,_N_,_TA,_I_,_no,_ret
		.BYTE	_na,_re,_no,_ha,_te,_da,_to,___,_si,_ta,_ra,_dot,_dot,_dot,_qe,_ret
		.BYTE	_RA,_BO,_ni,_i_,_ru,___,_te_tsu__o_,_mo,_qe,_ex,_eol
_scB_msg0E:
		.BYTE	_te_tsu__o_,_col,___,_ma,_tt,_te,_ro,_yo,_str,_cr,_eol
_scB_msg0F:
		.BYTE	_TE,_RO,_RI,_SU,_TO,_lt,_an0,_A_,_str,_MI,_str,_ha,___,_zi,_n_,_ta,_i_,_zi,_tt,_ke,_n_,_no,___,_hi,_mi,_tu,_wo,_ret
		.BYTE	_______________________,_ma,_mo,_ru,_ta,_me,___,_u_,_go,_i_,_te,_i_,_ru,_yo,_u_,_da,_cr,_aof,_eol
_scB_msg10:
		.BYTE	_TE,_RO,_RI,_SU,_TO,_lt,_an0,_RA,_BO,_to,_i_,_e_,_do,_mo,_col,___,_PA,_SU,_sa,_e_,_a_,_re,_ba,_ret
		.BYTE	_______________________,_se,_n_,_ni,_uu,_u_,_ha,___,_yo,_u_,_i_,_na,_ha,_zu,_da,_cr,_aof,_eol
_scB_msg11:
		.BYTE	_TE,_RO,_RI,_SU,_TO,_lt,_an0,_se,_i_,_hu,_ga,___,_zi,_n_,_mi,_n_,_no,___,_hu,_ku,_si,_wo,_ret
		.BYTE	_______________________,_ka,_e_,_ri,_mi,_zu,_col,___,_ke,_tu,_ze,_i_,_wo,___,_wa,_ke,_no,_wa,_ka,_ra,_n_,_ret
		.BYTE	_______________________,_zi,_tt,_ke,_n_,_no,_ta,_me,_ni,___,_tu,_ka,_tt,_te,_i_,_ru,_to,_i_,_u_,_ret
		.BYTE	_______________________,_si,_oo,_u_,_ko,_col,___,_so,_re,_wo,___,_tu,_ka,_ma,_ne,_ba,_na,_ra,_n_,_no,_da,_cr,_aof,_eol
_scB_msg12:
		.BYTE	_TE,_RO,_RI,_SU,_TO,_lt,_an0,_ki,_sa,_ma,_AA,_ex,___,_ya,_ha,_ri,___,_SU,_PA,_I_,_ka,_qe,_ex,_aof,_eol
_scB_msg13:
		.BYTE	___________,_KE,_I_,_lt,_an0,_A_,_N_,_TA,_AA,___,_do,_ko,_ni,___,_KA,_ME,_RA,_na,_n_,_te,_ret
		.BYTE	_______________________,_a_,_ru,_wa,_ke,_qe,_aof,_eol
;_scB_msg13:
;		.BYTE	_0,_A,_1,_6,_eol

		SECTION_END		FB
