
		SECTION_START	FA

		MSG_START	_sceneA_msg_lib
		MSG_IDX	_scA_msg00
		MSG_IDX	_scA_msg01
		MSG_IDX	_scA_msg02
		MSG_IDX	_scA_msg03
		MSG_IDX	_scA_msg04
		MSG_IDX	_scA_msg05
		MSG_IDX	_scA_msg06
		MSG_IDX	_scA_msg07
		MSG_IDX	_scA_msg08
		MSG_IDX	_scA_msg09
		MSG_IDX	_scA_msg0A
		MSG_IDX	_scA_msg0B
		MSG_IDX	_scA_msg0C
		MSG_IDX	_scA_msg0D
		MSG_IDX	_scA_msg0E
		MSG_IDX	_scA_msg0F
		MSG_IDX	_scA_msg10
		MSG_IDX	_scA_msg11
		MSG_IDX	_scA_msg12
		MSG_IDX	_scA_msg13
		MSG_IDX	_scA_msg14
		MSG_IDX	_scA_msg15
;		MSG_IDX	_scA_msg16					; -unused-
		MSG_IDX	_scA_msg17
		MSG_IDX	_scA_msg18
		MSG_IDX	_scA_msg19
		MSG_IDX	_scA_msg1A
_scA_msg00:
		.BYTE	_O_,_RE,_ha,___,_se,_ma,_i_,_he,_ya,_ni,___,_ka,_n_,_ki,_n_,___,_sa,_re,_te,_si,_ma,_tt,_ta,_ze,_cr,_eol
_scA_msg01:
		.BYTE	_se,_n_,_me,_n_,_zi,_oo,_de,_su,_cr,_eol
_scA_msg02:
		.BYTE	_BA,_KA,_ya,_ro,_u_,_tt,_col,___,_do,_ko,_ga,___,_SU,_PA,_I_,_da,_tt,_te,_n_,_da,_yo,_OO,_ex,_eol
_scA_msg03:
		.BYTE	_KE,_I_,_ti,_yy,_str,_n_,_col,___,_ko,_n_,_do,_ko,_so,___,_ti,_yy,_n_,_to,___,_o_,_ti,_yy,_ni,_ret
		.BYTE	_sa,_so,_u_,_yo,_OO,_cr,_eol
_scA_msg04:
		.BYTE	_ya,_tu,_ra,___,_me,_no,_i_,_ro,___,_ka,_e_,_te,___,_KE,_I_,_ti,_yy,_n_,_wo,_ret
		.BYTE	_o_,_i_,_ma,_wa,_si,_ya,_ga,_tt,_te,_cr,_ret
		.BYTE	_ke,_do,_col,___,_ha,_n_,_se,_i_,_hu,_bu,_n_,_si,_ga,_ri,_ni,___,_si,_ti,_yy,_a_,_ret
		.BYTE	_o_,_o_,_ge,_sa,___,_da,_tt,_ta,_na,_dot,_dot,_dot,_eol
_scA_msg05:
		.BYTE	_ZI,_TT,_KE,_I_,_TA,_I_,_to,_ka,___,_i_,_i_,_ya,_ga,_tt,_te,_cr,_ret
		.BYTE	_te_tsu__o_,_OO,_col,___,_do,_ko,_ni,___,_tu,_re,_te,_i_,_ka,_re,_ta,_n_,_da,_cr,_eol
_scA_msg06:
		.BYTE	_hu,_ro,_de,_su,_cr,_eol
_scA_msg07:
		.BYTE	_______,_ka__ne__da,_lt,_te_tsu__o_,_no,_ko,_to,_da,_ex,_eol
_scA_msg08:
		.BYTE	_tu,_u_,_ki,_ko,_u_,_no,_A_,_MI,_de,_su,_cr,_eol
_scA_msg09:
		.BYTE	_______,_ka__ne__da,_lt,_BI,_str,_RU,_da,_ze,_cr,_ret
		.BYTE	_______________________,_o_,_tt,___,_ko,_i_,_tu,_ha,___,_no,_me,_so,_u_,_da,_ex,_eol
_scA_msg0A:
		.BYTE	_______,_ka__ne__da,_lt,_do,_u_,_se,___,_ya,_tu,_ra,_no,___,_BI,_str,_RU,_da,_col,_ret
		.BYTE	_______________________,_no,_n_,_zi,_yy,_o_,_u_,_ex,___,_e_,_tt,_to,___,_SE,_N_,_NU,_KI,_ha,_dot,_dot,_dot,_ret
		.BYTE	_______________________,_ti,_e_,_tt,___,_SE,_N_,_NU,_KI,_ga,___,_na,_i_,_ex,_ret
		.BYTE	_______________________,_do,_ko,_ka,___,_SE,_N_,_ga,___,_nu,_ke,_ru,___,_ba,_si,_oo,_ha,_ret
		.BYTE	_______________________,_ne,$89,_ka,_na,_a_,_dot,_dot,_dot,_eol
_scA_msg0B:
		.BYTE	_______,_ka__ne__da,_lt,_o_,_tt,___,_ko,_ko,_na,_ra,___,_u_,_ma,_ku,___,_SE,_N_,_ga,_ret
		.BYTE	_______________________,_hi,_tt,_ka,_ka,_ru,_zo,_ex,___,_yo,_i_,_si,_oo,_tt,_to,_dot,_dot,_dot,_eol
_scA_msg0C:
		.BYTE	_SI,_UU,_PO,_N_,_ex,___,_GA,_TA,_N_,_ex,_ret
		.BYTE	_A_,_MI,_ga,___,_ha,_zu,_re,_ma,_si,_ta,_ex,_ret
		.BYTE	_ko,_ko,_ka,_ra,___,_ni,_ge,_ra,_re,_so,_u_,_de,_su,_cr,_eol
_scA_msg0D:
		.BYTE	_KA,_TI,___,_KA,_TI,_ret
		.BYTE	_______,_ka__ne__da,_lt,_u_,_str,_n_,___,_u_,_ma,_ku,___,_hi,_tt,_ka,_ka,_ra,_ne,$89,_na,_a_,_cr,_eol
_scA_msg0E:
		.BYTE	_O_,_RE,_ha,___,_tu,_u_,_ki,_ko,_u_,_he,___,_ka,_ra,_da,_wo,___,_mo,_gu,_ri,_ko,_ma,_se,_ta,_cr,_eol
_scA_msg0F:
		.BYTE	_dot,_dot,_dot,_O_,_RE,_ha,___,_ne,_te,_si,_ma,_tt,_ta,_cr,_eol
_scA_msg10:
		.BYTE	_BI,_str,_RU,_no,_KE,_str,_SU,_de,_su,_cr,_eol
_scA_msg11:
		.BYTE	_______,_ka__ne__da,_lt,_ti,_e_,_tt,_col,___,_na,_n_,_ni,_mo,_na,_i_,___,_he,_ya,_da,_ze,_cr,_eol
_scA_msg12:
		.BYTE	_______,_ka__ne__da,_lt,_se,_ma,_i_,___,_tu,_u_,_ki,_ko,_u_,_da,_ze,_dot,_dot,_dot,_eol
_scA_msg13:
		.BYTE	_______,_ka__ne__da,_lt,_to,_na,_ri,_no,_he,_ya,_no,___,_tu,_u_,_ki,_ko,_u_,_ma,_de,_ret
		.BYTE	_______________________,_ki,_ti,_ma,_tt,_ta,_dot,_dot,_dot,_eol
_scA_msg14:
		.BYTE	_ha,_na,_si,_go,_e_,_ga,___,_su,_ru,_cr,_ret
		.BYTE	_RI,_UU,_U_,_to,___,_TE,_RO,_RI,_SU,_TO,_ta,_ti,_da,_dot,_dot,_dot,_eol
_scA_msg15:
		.BYTE	_ko,_ko,_ka,_ra,___,_ni,_ge,_ra,_re,_so,_u_,_da,_cr,_eol
;_scA_msg16:
;		.BYTE	_te,_n_,_zi,_oo,_u_,_ka,_ra,___,_si,_zu,_ku,_ga,___,_o_,_ti,_te,_ku,_ru,_cr,_eol
_scA_msg17:
		.BYTE	_KE,_I_,_ti,_yy,_str,_n_,_col,___,_ko,_n_,_do,___,_i_,_tt,_si,_oo,_ni,___,_ha,_i_,_ro,_u_,_NE,_ex,_eol
_scA_msg18:
		.BYTE	_GA,_TA,_TT,_ex,_ex,_ret
		.BYTE	_______,_ka__ne__da,_lt,_si,_ma,_tt,_ta,_ex,_eol
_scA_msg19:
		.BYTE	_TE,_RO,_RI,_SU,_TO,_lt,_da,_re,_da,_AA,_ex,_ex,_eol
_scA_msg1A:
		.BYTE	_mo,_tt,_to,___,_ya,_tu,_ra,_no,_ha,_na,_si,_wo,___,_ki,_ke,_ne,$89,_ka,_qe,_eol

		SECTION_END		FA
