
		SECTION_START	FC

		MSG_START	_sceneC_msg_lib
		MSG_IDX	_scC_msg00
		MSG_IDX	_scC_msg01
		MSG_IDX	_scC_msg02
		MSG_IDX	_scC_msg03
		MSG_IDX	_scC_msg04
		MSG_IDX	_scC_msg05
		MSG_IDX	_scC_msg06
		MSG_IDX	_scC_msg07
		MSG_IDX	_scC_msg08
		MSG_IDX	_scC_msg09
		MSG_IDX	_scC_msg0A
		MSG_IDX	_scC_msg0B
		MSG_IDX	_scC_msg0C
		MSG_IDX	_scC_msg0D
		MSG_IDX	_scC_msg0E
		MSG_IDX	_scC_msg0F
		MSG_IDX	_scC_msg10
		MSG_IDX	_scC_msg11
		MSG_IDX	_scC_msg12
		MSG_IDX	_scC_msg13
_scC_msg00:
		.BYTE	_tu,_gi,_no,_hi,___,_O_,_RE,_ta,_ti,_ha,___,_RA,_BO,_he,___,_se,_n_,_ni,_uu,_u_,_si,_ta,_cr,_ret
		.BYTE	_ko,_ko,_ha,___,_RA,_BO,_no,_na,_ka,_no,___,_ha,_i_,_su,_i_,_ro,_da,_dot,_dot,_dot,_eol
_scC_msg01:
		.BYTE	_______,_ka__ne__da,_lt,_ku,_se,_str,_yo,_str,_ret
		.BYTE	___________,_KE,_I_,_lt,_u_,_ru,_sa,_i_,_wa,_ne,_cr,_eol
_scC_msg02:
		.BYTE	_______,_ka__ne__da,_lt,_na,_n_,_da,_yo,_OO,_str,_cr,___,_ku,_se,_str,_ka,_ra,___,_ku,_se,_str,_ret
		.BYTE	_______________________,_tu,_tt,_ta,_n_,_da,_ro,_OO,_col,___,_ha,_na,_ga,___,_wa,_ru,_i_,_II,_n_,_zi,_yy,_ret
		.BYTE	_______________________,_ne,_str,_ka,_col,___,_o_,_ma,_e_,_ha,_yo,_str,_cr,_eol
_scC_msg03:
		.BYTE	_TE,_RO,_RI,_SU,_TO,_lt,_ko,_no,_sa,_ki,_ni,___,_ti,_uu,_u_,_o_,_u_,___,_ha,_i_,_se,_n_,_ko,_u_,_ga,_ret
		.BYTE	_______________________,_a_,_ru,_ha,_zu,_da,_dot,_dot,_dot,_ret
		.BYTE	_______________________,_so,_re,_wo,___,_tu,_ka,_e_,_ba,___,_ti,_ka,_ma,_de,___,_ti,_oo,_tt,_ko,_u_,_ret
		.BYTE	_______________________,_de,_ki,_ru,_ze,_cr,_eol
_scC_msg04:
		.BYTE	_______,_RI,_UU,_U_,_lt,_i_,_ka,_n_,_ex,___,_ha,_tt,_ke,_n_,_sa,_re,_ta,_zo,_ex,_ex,_ret
		.BYTE	_TE,_RO,_RI,_SU,_TO,_lt,_F,_dot,_P,_dot,_H,_da,_ex,_ex,_eol
_scC_msg05:
		.BYTE	_TE,_RO,_RI,_SU,_TO,_lt,_si,_ma,_za,_ki,_II,_str,_ex,_ret
		.BYTE	_TE,_RO,_RI,_SU,_TO,_no,___,_hi,_to,_ri,_ga,___,_ya,_ra,_re,_ta,_ex,_eol
_scC_msg06:
		.BYTE	___________,_KE,_I_,_lt,_ha,_ya,_ku,_si,_na,_sa,_i_,_col,___,_si,_zu,_ka,_ni,_cr,_eol
_scC_msg07:
		.BYTE	_O_,_RE,_ha,___,_si,_n_,_da,___,_TE,_RO,_RI,_SU,_TO,_no,___,_zi,_uu,_u_,_wo,___,_to,_ri,_a_,_ge,_ta,_cr,_eol
_scC_msg08:
		.BYTE	_ke,_do,___,_O_,_RE,_ha,___,_F,_dot,_P,_dot,_H,_no,___,_hi,_ki,_ga,_ne,_ni,_ret
		.BYTE	_sa,_wa,_tt,_te,_si,_ma,_tt,_ta,_cr,_ret
		.BYTE	_BA,_RU,_KA,_N_,_ho,_u_,_ga,___,_DO,_RO,_ni,___,_u_,_ti,_ko,_ma,_re,_te,_i_,_tt,_ta,_cr,_eol
_scC_msg09:
		.BYTE	_______,_ka__ne__da,_lt,_A_,_RE,_TT,_ex,___,_TA,_MA,_ga,___,_na,_ku,_na,_tt,_ti,_yy,_tt,_ta,_cr,_eol
_scC_msg0A:
		.BYTE	_______,_ka__ne__da,_lt,_ku,_so,_str,_tt,_ex,_ret
		.BYTE	_O_,_RE,_ha,___,_zi,_uu,_u_,_wo,___,_na,_ge,_tu,_ke,_ta,_cr,_eol
_scC_msg0B:
		.BYTE	_______,_ka__ne__da,_lt,_u_,_str,_col,___,_ge,_ho,_col,___,_ge,_ho,_ge,_ho,_cr,_ret
		.BYTE	_O_,_RE,_ha,___,_DO,_RO,_no,_na,_ka,_ni,___,_hu,_se,_ta,_cr,_eol
_scC_msg0C:
		.BYTE	_BA,_SI,_YY,_TT,_ex,_ret
		.BYTE	_O_,_RE,_ha,___,_yo,_ko,_tt,_to,_bi,_de,___,_ka,_wa,_si,_col,___,_ha,_i_,_su,_i_,_ko,_u_,_no,_ret
		.BYTE	_ka,_be,_wo,___,_yo,_zi,_no,_bo,_tt,_ta,_cr,_eol
_scC_msg0D:
		.BYTE	_______,_ka__ne__da,_lt,_ku,_ru,_zo,_OO,_ex,_eol
_scC_msg0E:
		.BYTE	_______,_ka__ne__da,_lt,_to,_ri,_yy,_a_,_str,_tt,_ex,_ret
		.BYTE	_O_,_RE,_ha,___,_F,_dot,_P,_dot,_H,_ni,___,_to,_bi,_tu,_i_,_ta,_cr,_eol
_scC_msg0F:
		.BYTE	_______,_ka__ne__da,_lt,_u_,_wa,$9E,_cr,_ret
		.BYTE	___________,_KE,_I_,_lt,_ki,_yy,_a_,_str,_tt,_cr,_eol
_scC_msg10:
		.BYTE	_F,_dot,_P,_dot,_H,_no,___,_o_,_sa,_e_,_ga,___,_ki,_ka,_zu,_col,___,_O_,_RE,_ha,_ret
		.BYTE	_DO,_RO,_si,_bu,_ki,_no,_na,_ka,_wo,___,_u_,_go,_ki,_ma,_wa,_tt,_ta,_cr,_ret
		.BYTE	_O_,_RE,_ha,___,_sa,_n_,_za,_n_,_na,_me,_ni,___,_a_,_tt,_te,_col,___,_yo,_u_,_ya,_ku,_ret
		.BYTE	_F,_dot,_P,_dot,_H,_ni,___,_no,_ri,_ko,_n_,_da,_cr,_eol
_scC_msg11:
		.BYTE	___________,_KE,_I_,_lt,_ki,_yy,_a_,_ex,_ret
		.BYTE	_______,_ka__ne__da,_lt,_KE,_I_,_ex,___,_ko,_tt,_ti,_da,_col,___,_ha,_ya,_ku,___,_no,_re,_ex,_eol
_scC_msg12:
		.BYTE	___________,_KE,_I_,_lt,_ki,_yy,_a_,_str,_tt,_col,_ka__ne__da,_ku,_n_,_col,___,_u_,_si,_ro,_tt,_ex,_eol
_scC_msg13:
		.BYTE	___________________,_A,_BO,_TA,_N_,___,_u_,_tu,_ret
		.BYTE	___________________,_B,_BO,_TA,_N_,___,_ka,_wa,_su,_ret
		.BYTE	___________________,_SE,_RE,_KU,_TO,___,_hu,_ri,_mu,_ku,_eol

		SECTION_END		FC
