
		SECTION_START	F16

		MSG_START	_scene16_msg_lib
		MSG_IDX	_sc16_msg00
		MSG_IDX	_sc16_msg01
		MSG_IDX	_sc16_msg0D
		MSG_IDX	_sc16_msg0E
		MSG_IDX	_sc16_msg0F
		MSG_IDX	_sc16_msg10
		MSG_IDX	_sc16_msg11
		MSG_IDX	_sc16_msg14
		MSG_IDX	_sc16_msg1D
		MSG_IDX	_sc16_msg1E
		MSG_IDX	_sc16_msg1F
		MSG_IDX	_sc16_msg20
		MSG_IDX	_sc16_msg21
		MSG_IDX	_sc16_msg22
		MSG_IDX	_sc16_msg24
		MSG_IDX	_sc16_msg25
		MSG_IDX	_sc16_msg26
		MSG_IDX	_sc16_msg27
		MSG_IDX	_sc16_msg28
		MSG_IDX	_sc16_msg29
		MSG_IDX	_sc16_msg2A
		MSG_IDX	_sc16_msg2B
		MSG_IDX	_sc16_msg7C					; scene 16 msg
		MSG_IDX	_sc16_msg7D					; scene 16 msg
		MSG_IDX	_sc16_msg7E					; scene 16 msg
		MSG_IDX	_sc16_msg9C					; scene 16 msg
		MSG_IDX	_sc16_msgC0					; scene 16 msg
		MSG_IDX	_sc16_msgC2					; scene 16 msg
		MSG_IDX	_sc16_msgC3					; scene 16 msg
		MSG_IDX	_sc16_msgC4					; scene 16 msg
		MSG_IDX	_sc16_msgCC					; scene 16 msg
		MSG_IDX	_sc16_msgCD					; scene 16 msg
		MSG_IDX	_sc16_msgCE					; scene 16 msg
		MSG_IDX	_sc16_msgCF					; scene 16 msg
		MSG_IDX	_sc16_msgD0					; scene 16 msg
		MSG_IDX	_sc16_msgD1					; scene 16 msg
		MSG_IDX	_sc16_msgD2					; scene 16 msg
		MSG_IDX	_sc16_msgD3					; scene 16 msg
		MSG_IDX	_sc16_msgD4					; scene 16 msg
		MSG_IDX	_sc16_msgD5					; scene 16 msg
		MSG_IDX	_sc16_msgD6					; scene 16 msg
		MSG_IDX	_sc16_msgD7					; scene 16 msg
		MSG_IDX	_sc16_msgD8					; scene 16 msg
		MSG_IDX	_sc16_msgD9					; scene 16 msg
		MSG_IDX	_sc16_msgDA					; scene 16 msg
		MSG_IDX	_sc16_msgDB					; scene 16 msg
		MSG_IDX	_sc16_msgDC					; scene 16 msg
		MSG_IDX	_sc16_msgDD					; scene 16 msg
		MSG_IDX	_sc16_msgDE					; scene 16 msg
		MSG_IDX	_sc16_msgDF					; scene 16 msg
		MSG_IDX	_sc16_msgE0					; scene 16 msg
		MSG_IDX	_sc16_msgE1					; scene 16 msg
		MSG_IDX	_sc16_msgE2					; scene 16 msg
		MSG_IDX	_sc16_msgE3					; scene 16 msg
		MSG_IDX	_sc16_msgE4					; scene 16 msg
		MSG_IDX	_sc16_msgE5					; scene 16 msg
		MSG_IDX	_sc16_msgE6					; scene 16 msg
		MSG_IDX	_sc16_msgE7					; scene 16 msg
		MSG_IDX	_sc16_msgE8					; scene 16 msg
		MSG_IDX	_sc16_msgE9					; scene 16 msg
		MSG_IDX	_sc16_msgEA					; scene 16 msg
		MSG_IDX	_sc16_msgEB					; scene 16 msg
		MSG_IDX	_sc16_msgEC					; scene 16 msg
		MSG_IDX	_sc16_msgED					; scene 16 msg
		MSG_IDX	_sc16_msgEE					; scene 16 msg
		MSG_IDX	_sc16_msgEF					; scene 16 msg
_sc16_msg00:
		.BYTE	_O_,_RE,_no,_me,_no,_ma,_e_,_ni,___,_ti,_i_,_sa,_ku,_na,_tt,_ta,___,_hi,_ka,_ri,_no,_ta,_ma,_ga,_ret
		.BYTE	_a_,_tt,_ta,_cr,_eol
_sc16_msg01:
		.BYTE	_O_,_RE,_ha,___,_yu,_tt,_ku,_ri,_to,___,_hu,_ri,_ka,_e_,_ri,_col,___,_KE,_I_,_wo,___,_mi,_tu,_me,_ta,_cr,_eol
_sc16_msg0D:
		.BYTE	_______,_KI,_YO,_KO,_lt,_an0,_so,_u_,_dot,_dot,_dot,___,_wa,_ta,_si,_ta,_ti,_ga,___,_yo,_n_,_da,_no,_dot,_dot,_dot,_ret
		.BYTE	_______________________,_te_tsu__o_,_ku,_n_,_wo,___,_tu,_re,_te,_tt,_te,_mo,_ra,_u_,_ta,_me,_ni,_cr,_aof,_ret
		.BYTE	_______,_ka__ne__da,_lt,_tu,_re,_te,_ku,$88,_str,_tt,_cr,___,_dot,_dot,_dot,_do,_ko,_he,_qe,_eol
_sc16_msg0E:
		.BYTE	_______,_TA,_KA,_SI,_lt,_te_tsu__o_,_ku,_n_,_ni,_ha,___,_mu,_ri,_da,_tt,_ta,_no,_sa,_dot,_dot,_dot,_ret
		.BYTE	_______________________,_mo,_ti,_ro,_n_,___,_bo,_ku,_ra,_ni,_mo,_dot,_dot,_dot,_ret
		.BYTE	_______________________,_A_,_KI,_RA,_ku,_n_,_ni,_mo,_dot,_dot,_dot,_ret
		.BYTE	_______,_MA,_SA,_RU,_lt,_i_,_ma,_no,___,_bo,_ku,_ta,_ti,_ni,_ha,___,_o_,_o_,_ki,_su,_gi,_ta,_n_,_da,_cr,_eol
_sc16_msg0F:
		.BYTE	_______,_KI,_YO,_KO,_lt,_an0,_de,_mo,___,_i_,_tu,_ka,_ha,___,_wa,_ta,_si,_ta,_ti,_ni,_mo,_dot,_dot,_dot,_aof,_ret
		.BYTE	_______,_MA,_SA,_RU,_lt,_mo,_u_,___,_ha,_zi,_ma,_tt,_te,_i_,_ru,_ka,_ra,_ne,_dot,_dot,_dot,_eol
_sc16_msg10:
		.BYTE	_______,_KI,_YO,_KO,_lt,_an0,_a_,_na,_ta,_no,_to,_mo,_da,_ti,_no,_dot,_dot,_dot,_aof,_ret
		.BYTE	_______,_ka__ne__da,_lt,_O_,_RE,_no,_dot,_dot,_dot,___,_KE,_I_,_TT,_ex,___,_KE,_I_,_no,_ko,_to,_da,_na,_cr,_eol
_sc16_msg11:
		.BYTE	___________,_KE,_I_,_lt,_ka__ne__da,_ku,_str,_n_,_cr,_ret
		.BYTE	_KE,_I_,_no,_ko,_e_,_ga,___,_ki,_ko,_e_,_te,_ki,_ta,_dot,_dot,_dot,_ret
		.BYTE	_______,_ka__ne__da,_lt,_an0,_KE,_I_,_dot,_dot,_dot,_aof,_eol
_sc16_msg14:
		.BYTE	_______,_MA,_SA,_RU,_lt,_KI,_YO,_KO,_str,___,_TA,_KA,_SI,_str,_cr,_ret
		.BYTE	_______,_TA,_KA,_SI,_lt,_KI,_YO,_KO,_str,___,_MA,_SA,_RU,_str,_cr,_ret
		.BYTE	_______,_KI,_YO,_KO,_lt,_TA,_KA,_SI,_ku,_str,_n_,___,_MA,_SA,_RU,_ku,_str,_n_,_cr,_eol
_sc16_msg1D:
		.BYTE	_ti,_i_,_sa,_ku,_na,_tt,_ta,___,_hi,_ka,_ri,_no,_ta,_ma,_ga,___,_ki,_e_,_i_,_ri,_so,_u_,_ni,_ret
		.BYTE	_na,_ri,_na,_ga,_ra,___,_o_,_ri,_te,_ki,_ta,_dot,_dot,_dot,_eol
_sc16_msg1E:
		.BYTE	_ki,_ga,_tu,_i_,_ta,_to,_ki,_col,___,_O_,_RE,_ha,___,_SU,_TA,_ZI,_A_,_MU,_no,_ret
		.BYTE	_GA,_RE,_KI,_no,_ya,_ma,_no,_u_,_e_,_ni,___,_i_,_ta,_cr,_eol
_sc16_msg1F:
		.BYTE	_O_,_RE,_ha,___,_ki,_e_,_te,_si,_ma,_i_,_so,_u_,_na,___,_hi,_ka,_ri,_no,_ta,_ma,_wo,___,_o_,_mo,_wa,_zu,_ret
		.BYTE	_ni,_gi,_ri,_si,_me,_te,_i_,_ta,_cr,_eol
_sc16_msg20:
		.BYTE	_______,_ka__ne__da,_lt,_te_tsu__o_,_dot,_dot,_dot,_dot,_dot,_dot,_eol
_sc16_msg21:
		.BYTE	___________,_KE,_I_,_lt,_ka__ne__da,_ku,_n_,_dot,_dot,_dot,_ret
		.BYTE	_______,_ka__ne__da,_lt,_a_,_ri,_ga,_to,_u_,_dot,_dot,_dot,___,_yo,_n_,_de,_ku,_re,_ta,_da,_ro,_OO,_col,_ret
		.BYTE	_______________________,_ki,_ko,_e_,_ta,_ze,_dot,_dot,_dot,_eol
_sc16_msg22:
		.BYTE	___________,_KE,_I_,_lt,_te_tsu__o_,_ku,_n_,_ha,_dot,_dot,_dot,_ret
		.BYTE	_______,_ka__ne__da,_lt,_i_,_tt,_ti,_ma,_tt,_ta,_dot,_dot,_dot,___,_a_,_no,_3,_ni,_n_,_mo,_dot,_dot,_dot,_ret
		.BYTE	_______________________,_A_,_KI,_RA,_mo,_dot,_dot,_dot,_ret
		.BYTE	___________,_KE,_I_,_lt,_ka__ne__da,_ku,_n_,_dot,_dot,_dot,___,_a_,_na,_ta,_col,___,_sa,_tt,_ki,_dot,_dot,_dot,_eol
_sc16_msg24:
		.BYTE	_SA,_TT,_to,___,_ku,_mo,_ga,_na,_ga,_re,_col,___,_O_,_RE,_ta,_ti,_ni,___,_hi,_ga,_sa,_si,_ta,_cr,_ret
		.BYTE	_O_,_RE,_ta,_ti,_ha,___,_zu,_tt,_to,___,_hi,_ka,_ri,_wo,___,_mi,_tu,_me,_te,_i_,_ta,_dot,_dot,_dot,_eol
_sc16_msg25:
		.BYTE	_so,_si,_te,___,_O_,_RE,_ta,_ti,_ha,___,_BA,_I_,_KU,_ni,_no,_ri,_col,___,_NE,_O_,_to,_u_,_ki,_oo,_u_,_wo,_ret
		.BYTE	_me,_za,_si,_te,___,_ha,_si,_tt,_ta,_cr,_eol
_sc16_msg26:
		.BYTE	_ku,_zu,_re,_ka,_ke,_ta,___,_NE,_O_,_to,_u_,_ki,_oo,_u_,_no,___,_BI,_RU,_gu,_n_,_ni,_mo,_ret
		.BYTE	_i_,_tt,_pa,_i_,_ni,___,_hi,_ka,_ri,_ga,___,_hu,_ri,_so,_so,_i_,_de,_i_,_ta,_cr,_eol
_sc16_msg27:
		.BYTE	_dot,_dot,_dot,_ma,_tt,_si,_ro,_na,_ku,_u_,_ka,_n_,_ni,___,_hi,_ka,_ri,_ga,___,_ha,_si,_ri,_col,_ret
		.BYTE	_ya,_ga,_te,___,_GE,_N_,_SI,_ga,___,_ta,_n_,_zi,_oo,_u_,_si,_ta,_cr,_ret
		.BYTE	_GE,_N_,_SI,_ha,_dot,_dot,_dot,_eol
_sc16_msg28:
		.BYTE	_se,_i_,_ti,_oo,_u_,_si,_col,___,_GA,_SU,_zi,_oo,_u_,_no,_mo,_no,_to,___,_na,_tt,_ta,_cr,_ret
		.BYTE	_tu,_i_,_ni,_ha,___,_u_,_ti,_uu,_u_,_ga,___,_a_,_ra,_wa,_re,_dot,_dot,_dot,_ret
		.BYTE	_SE,_I_,_U_,_N_,_to,_dot,_dot,_dot,_eol
_sc16_msg29:
		.BYTE	_HO,_SI,_BO,_SI,_ga,___,_u_,_ma,_re,_te,_i_,_tt,_ta,_dot,_dot,_dot,_eol
_sc16_msg2A:
		.BYTE	_______,_te_tsu__o_,_lt,_bo,_ku,_ha,_dot,_dot,_dot,___,_te_tsu__o_,_dot,_dot,_dot,_eol
_sc16_msg2B:
		.BYTE	_______,_ka__ne__da,_lt,_do,_u_,_ka,_na,_AA,_dot,_dot,_dot,___,_ki,_tt,_to,_dot,_dot,_dot,___,_a_,_tt,_ex,_eol
_sc16_msg7C:
		.BYTE	_ka,_re,_ra,_ha,___,_ki,_uu,_u_,_si,_ga,_i_,_de,___,_sa,_ra,_ni,___,_ka,_ku,_da,_i_,_si,_te,_i_,_ku,_ret
		.BYTE	_ki,_oo,_da,_i_,_na,_hi,_ka,_ri,_wo,___,_na,_ga,_me,_te,_i_,_ta,_cr,_eol
_sc16_msg7D:
		.BYTE	_NE,_O_,_to,_u_,_ki,_oo,_u_,_wo,___,_sa,_ra,_na,_ru,___,_sa,_i_,_a_,_ku,_ga,_ret
		.BYTE	_o_,_si,_tu,_tu,_mo,_u_,_to,___,_si,_te,_i_,_ta,_dot,_dot,_dot,_eol
_sc16_msg7E:
		.BYTE	_da,_ga,___,_ka__ne__da,_ni,_yo,_tt,_te,___,_tu,_i_,_ni,___,_A_,_KI,_RA,_ga,___,_ka,_ku,_se,_i_,_ret
		.BYTE	_si,_te,_si,_ma,_tt,_ta,_cr,_eol
_sc16_msg9C:
		.BYTE	_ka__ne__da,_no,_ka,_tu,_ya,_ku,_de,___,_A_,_KI,_RA,_no,_ka,_ku,_se,_i_,_ha,___,_so,_si,_de,_ki,_ta,_cr,_ret
		.BYTE	_NE,_O_,_to,_u_,_ki,_oo,_u_,_ni,___,_he,_i_,_wa,_ga,___,_mo,_do,_tt,_ta,_dot,_dot,_dot,_eol
_sc16_msgC0:
		.BYTE	_hi,_ka,_ri,_ha,___,_GA,_RE,_KI,_wo,___,_su,_i_,_a_,_ge,_col,___,_hi,_ro,_ga,_tt,_te,_i_,_tt,_ta,_cr,_ret
		.BYTE	_______,_te_tsu__o_,_lt,_na,_n_,_da,_col,___,_ko,_no,_hi,_ka,_ri,_ha,_qe,_ret
		.BYTE	_i_,_tt,_si,_uu,_n_,_col,_ret
		.BYTE	_O_,_RE,_no,_me,_no,_ma,_e_,_ga,___,_ma,_tt,_si,_ro,_ni,_na,_tt,_ta,_cr,_eol
_sc16_msgC2:
		.BYTE	_SA,_N_,_PU,_RU,_KE,_str,_SU,_ni,___,_me,_i_,_ti,_uu,_u_,_si,_ta,_RE,_str,_ZA,_str,_no,_ret
		.BYTE	_E_,_NE,_RU,_GI,_str,_ga,___,_te_tsu__o_,_no,_PA,_WA,_str,_to,___,_ki,_oo,_u_,_si,_n_,_si,_col,_ret
		.BYTE	_A_,_KI,_RA,_ga,___,_ka,_ku,_se,_i_,___,_si,_te,_si,_ma,_tt,_ta,_no,_da,_tt,_ta,_cr,_eol
_sc16_msgC3:
		.BYTE	_A_,_KI,_RA,_no,_hi,_ka,_ri,_ha,___,_sa,_ra,_ni,___,_ka,_ku,_da,_i_,_si,_col,___,_ka__ne__da,_to,_ret
		.BYTE	_te_tsu__o_,_wo,___,_tu,_tu,_mi,_ko,_n_,_da,_cr,_ret
		.BYTE	_______,_te_tsu__o_,_lt,_u_,_wa,_AA,_str,_col,___,_A_,_dot,_dot,_dot,___,_A_,_KI,_RA,_AA,_dot,_dot,_dot,_eol
_sc16_msgC4:
		.BYTE	_NE,_O_,_to,_u_,_ki,_oo,_u_,_ni,___,_yo,_u_,_ya,_ku,___,_si,_zu,_ke,_sa,_ga,___,_mo,_do,_tt,_ta,_cr,_eol
_sc16_msgCC:
		.BYTE	_RE,_str,_ZA,_str,_no,_E_,_NE,_RU,_GI,_str,_ni,_yo,_tt,_te,___,_bo,_u_,_ti,_oo,_u_,_si,_ta,_ret
		.BYTE	_te_tsu__o_,_ha,___,_tu,_i_,_ni,___,_3,_ni,_n_,_ni,_col,___,_so,_si,_te,___,_A_,_KI,_RA,_no,_ret
		.BYTE	_SA,_N_,_PU,_RU,_KE,_str,_SU,_ma,_de,_ni,_mo,___,_si,_oo,_ku,_si,_wo,___,_no,_ba,_si,_ta,_cr,_eol
_sc16_msgCD:
		.BYTE	_______,_KI,_YO,_KO,_lt,_TE,_col,___,_te_tsu__o_,_ku,_n_,_dot,_dot,_dot,_ret
		.BYTE	_______________________,_ki,_yy,_a_,_str,_ex,_ret
		.BYTE	_______,_TA,_KA,_SI,_lt,_da,_col,___,_da,_me,_da,_yo,_str,_ex,_ret
		.BYTE	_______,_MA,_SA,_RU,_lt,_u_,_wa,_a_,_str,_ex,___,_dot,_dot,_dot,_A_,_KI,_RA,_ku,_n_,_ga,_dot,_dot,_dot,_eol
_sc16_msgCE:
		.BYTE	_SU,_TA,_ZI,_A_,_MU,_wo,___,_ha,_ka,_i_,_si,_ta,_te_tsu__o_,_ha,_col,_ret
		.BYTE	_ki,_uu,_u_,_si,_ga,_i_,___,_ze,_n_,_ta,_i_,_wo,___,_no,_mi,_ko,_n_,_da,_cr,_eol
_sc16_msgCF:
		.BYTE	_ya,_ga,_te,___,_ki,_uu,_u_,_si,_ga,_i_,_no,___,_ho,_u_,_ka,_i_,_ni,_yo,_tt,_te,_col,_ret
		.BYTE	_ka,_i_,_su,_i_,_ga,___,_NE,_O_,_to,_u_,_ki,_oo,_u_,_ni,___,_na,_ga,_re,_ko,_n_,_da,_cr,_eol
_sc16_msgD0:
		.BYTE	_NE,_O_,_to,_u_,_ki,_oo,_u_,_ni,___,_si,_zu,_ke,_sa,_ga,___,_mo,_do,_tt,_ta,_cr,_ret
		.BYTE	_ha,_ka,_i_,_si,_tu,_ku,_sa,_re,_ta,___,_ki,_uu,_u_,_si,_ga,_i_,_de,___,_te_tsu__o_,_ga,_ret
		.BYTE	_na,_i_,_te,_i_,_ta,_cr,_ret
		.BYTE	_______,_te_tsu__o_,_lt,_o_,_str,_N_,_col,___,_o_,_str,_N_,_col,___,_o_,_str,_N_,_col,___,_o_,_str,_N_,_col,_ret
		.BYTE	_______________________,_o_,_str,_N_,_col,___,_o_,_str,_N_,_col,___,_o_,_str,_N_,_dot,_dot,_dot,_eol
_sc16_msgD1:
		.BYTE	_O_,_RE,_ha,___,_GA,_KI,_no,_TE,_RE,_PO,_str,_TE,_str,_SI,$6A,_N_,_de,___,_SU,_TA,_ZI,_A_,_MU,_ka,_ra,_ret
		.BYTE	_da,_tt,_si,_uu,_tu,_si,_ta,_cr,_eol
_sc16_msgD2:
		.BYTE	_ha,_ka,_i_,_sa,_re,_ta,___,_SU,_TA,_ZI,_A_,_MU,_ni,___,_o_,_ri,_ta,_tt,_ta,___,_O_,_RE,_ta,_ti,_ha,_ret
		.BYTE	_so,_ko,_de,___,_KE,_I_,_to,_ka,_i_,_ni,___,_de,_a_,_tt,_ta,_cr,_eol
_sc16_msgD3:
		.BYTE	_dot,_dot,_dot,_si,_ka,_si,_col,_ret
		.BYTE	_2,_tu,_no,_PA,_WA,_str,_ga,___,_do,_u_,___,_PU,_RA,_SU,_dot,_MA,_I_,_NA,_SU,_ni,_ret
		.BYTE	_sa,_yo,_u_,_si,_ta,_no,_ka,_dot,_dot,_dot,_eol
_sc16_msgD4:
		.BYTE	_A_,_KI,_RA,_to,_te_tsu__o_,_ha,___,_GA,_RE,_KI,_no,_na,_ka,_de,___,_sa,_i_,_se,_i_,_si,_te,_i_,_ta,_cr,_ret
		.BYTE	_______,_te_tsu__o_,_lt,_yo,_u_,_ya,_ku,___,_a_,_e_,_ta,_na,_AA,_dot,_dot,_dot,_ret
		.BYTE	_______________________,_A_,_KI,_RA,_ti,_yy,_n_,_yo,_OO,_dot,_dot,_dot,_eol
_sc16_msgD5:
		.BYTE	_ka,_i_,_me,_tu,_si,_ta,___,_NE,_O_,_to,_u_,_ki,_oo,_u_,_wo,___,_bu,_ta,_i_,_ni,_ret
		.BYTE	_a_,_ra,_ta,_na,___,_A_,_KI,_RA,_no,_SU,_TO,_str,_RI,_str,_ga,___,_ha,_zi,_ma,_ro,_u_,_to,_ret
		.BYTE	_si,_te,_i_,_ta,_dot,_dot,_dot,_ret
		.BYTE	_da,_i_,_to,_u_,_ki,_oo,_u_,_te,_i_,_ko,_ku,_he,_dot,_dot,_dot,_eol
_sc16_msgD6:
		.BYTE	_ka__ne__da,_ha,___,_mo,_ga,_i_,_ta,_ga,_col,___,_tu,_i_,_ni,___,_hi,_ka,_ri,_ni,_ret
		.BYTE	_no,_mi,_ko,_ma,_re,_te,_si,_ma,_tt,_ta,_cr,_eol
_sc16_msgD7:
		.BYTE	_dot,_dot,_dot,_ka__ne__da,_ha,___,_A_,_KI,_RA,_ni,___,_no,_mi,_ko,_ma,_re,_col,___,_si,_oo,_u_,_me,_tu,_ret
		.BYTE	_si,_te,_si,_ma,_tt,_ta,_cr,_eol
_sc16_msgD8:
		.BYTE	_NE,_O_,_to,_u_,_ki,_oo,_u_,_ni,___,_si,_zu,_ke,_sa,_ga,___,_mo,_do,_tt,_ta,_cr,_ret
		.BYTE	_su,_be,_te,_ga,___,_ha,_ka,_i_,_si,_tu,_ku,_sa,_re,_te,_i_,_ta,_dot,_dot,_dot,_eol
_sc16_msgD9:
		.BYTE	_ko,_u_,_so,_ku,_do,_u_,_ro,_no,___,_ri,_oo,_u_,_ki,_n_,_zi,_oo,_ni,___,_ka,_i_,_to,_KE,_I_,_ha,_ret
		.BYTE	_i_,_ta,_cr,_eol
_sc16_msgDA:
		.BYTE	___________,_ka,_i_,_lt,_an1,_YA,_BA,_I_,_ze,_str,___,_ni,_ge,_ta,_ho,_u_,_ga,___,_i_,_i_,_ze,_col,_ret
		.BYTE	_______________________,_o_,_i_,_cr,_aof,_ret
		.BYTE	___________,_KE,_I_,_lt,_an0,_ka__ne__da,_ku,_n_,_dot,_dot,_dot,___,_ka__ne__da,_ku,_str,_n_,_cr,_aof,_eol
_sc16_msgDB:
		.BYTE	_hi,_ka,_ri,_ha,___,_u_,_na,_ri,_wo,_a_,_ge,_te,_col,___,_ki,_uu,_u_,_si,_ga,_i_,_wo,_ret
		.BYTE	_si,_n_,_si,_oo,_ku,___,_si,_te,_i_,_tt,_ta,_cr,_eol
_sc16_msgDC:
		.BYTE	_BI,_RU,_ha,___,_su,_be,_te,___,_no,_mi,_ko,_ma,_re,_col,___,_GA,_RE,_KI,_col,___,_KA,_N_,_BA,_N_,_col,_ret
		.BYTE	_A_,_str,_MI,_str,_no,_so,_u_,_ko,_u_,_si,_yy,_na,_do,_ga,___,_su,_i_,_ko,_ma,_re,_col,_ret
		.BYTE	_hu,_ki,_a_,_ge,_ra,_re,_te,_i_,_ta,_cr,_ret
		.BYTE	_ki,_uu,_u_,_si,_ga,_i_,_ga,___,_hi,_ka,_ri,_ni,___,_o_,_o_,_i_,_tu,_ku,_sa,_re,_ta,_cr,_eol
_sc16_msgDD:
		.BYTE	_O_,_RE,_ha,___,_hi,_ka,_ri,_no,_na,_ka,_wo,___,_ta,_da,_yo,_tt,_te,_i_,_ta,_cr,_ret
		.BYTE	_dot,_dot,_dot,_O_,_RE,_no,_me,_no,_ma,_e_,_ni,___,_i_,_ro,_n_,_na,___,_ka,_ko,_no,_de,_ki,_go,_to,_ga,_ret
		.BYTE	_u_,_ka,_n_,_de,_ki,_ta,_cr,_eol
_sc16_msgDE:
		.BYTE	_______,_ka__ne__da,_lt,_da,_ka,_ra,___,_o_,_ma,_e_,_no,_ha,___,_tu,_tt,_ko,_mi,_ga,_ret
		.BYTE	_______________________,_ta,_ri,_ne,$89,_N_,_da,_yo,_cr,_ret
		.BYTE	___,_ya,_ma,_ga,_ta,_lt,_KO,_str,_NA,_str,_ha,___,_si,_nu,_ki,_de,___,_i_,_ku,_n_,_da,_yo,_ret
		.BYTE	_______________________,_i_,_i_,_ka,_col,___,_mi,_te,_ro,_dot,_dot,_dot,_eol
_sc16_msgDF:
		.BYTE	___________,_ka,_i_,_lt,_na,_n_,_da,_yo,_col,___,_so,_re,_cr,_ret
		.BYTE	___,_ya,_ma,_ga,_ta,_lt,_KO,_str,_NA,_RI,_N_,_GU,_da,_yo,_cr,_ret
		.BYTE	_______,_ka__ne__da,_lt,_ha,_ha,_ha,_dot,_dot,_dot,___,_na,_AA,___,_te_tsu__o_,_dot,_dot,_dot,_eol
_sc16_msgE0:
		.BYTE	___________________,_lt,_mi,_ro,_yo,_col,___,_ma,_ta,___,_ki,_ta,_ze,_cr,_ret
		.BYTE	___________________,_lt,_te,_n_,_ni,_uu,_u_,_se,_i_,_ka,_cr,_ret
		.BYTE	___________________,_lt,_su,_te,_ra,_re,_ta,_n_,_da,_yo,_cr,_ret
		.BYTE	___________________,_lt,_hu,_ko,_u_,_ga,___,_ka,_o_,_ni,___,_de,_te,_ru,_ze,_cr,_eol
_sc16_msgE1:
		.BYTE	_______,_ka__ne__da,_lt,_ko,_re,_ha,_dot,_dot,_dot,___,_o_,_ma,_e_,_no,___,_yu,_me,_na,_no,_ka,_cr,_ret
		.BYTE	_______________________,_te_tsu__o_,_str,_tt,_cr,_eol
_sc16_msgE2:
		.BYTE	_______,_te_tsu__o_,_lt,_HI,_TT,_KU,___,_HI,_TT,_KU,_dot,_dot,_dot,_ret
		.BYTE	_______,_ka__ne__da,_lt,_a_,_ta,_ra,_si,_ku,___,_ha,_i_,_tt,_te,_ki,_ta,_ya,_tu,_ni,_ha,___,_i_,_tu,_mo,_ret
		.BYTE	_______________________,_a_,_a_,_na,_n_,_da,_cr,___,_ki,_oo,_u_,___,_ki,_ta,_n_,_da,_ro,_OO,_cr,_ret
		.BYTE	_______________________,_O_,_RE,_mo,___,_ya,_ra,_re,_ta,_ke,_do,_dot,_dot,_dot,___,_de,_mo,_ret
		.BYTE	_______________________,_ho,_n_,_to,_ha,___,_yo,_wa,_i_,_n_,_da,_ze,_col,___,_a_,_i_,_tu,_dot,_dot,_dot,_eol
_sc16_msgE3:
		.BYTE	_______,_te_tsu__o_,_lt,_BO,_KU,_ha,_dot,_dot,_dot,___,_te_tsu__o_,_dot,_dot,_dot,_ret
		.BYTE	_______________________,_SI,_MA,___,_te_tsu__o_,_dot,_dot,_dot,_ret
		.BYTE	_______,_ka__ne__da,_lt,_he,_he,_tt,___,_zi,_tu,_ha,_sa,_col,___,_O_,_RE,_mo,_ret
		.BYTE	_______________________,_ki,_ta,_ba,_tt,_ka,_na,_n_,_da,_cr,___,_na,_ma,_e_,_ha,_dot,_dot,_dot,_eol
_sc16_msgE4:
		.BYTE	_dot,_dot,_dot,_to,_tu,_ze,_n_,___,_GA,_KI,_do,_mo,_no,_su,_ga,_ta,_ga,___,_u_,_ka,_n_,_de,_ki,_ta,_cr,_ret
		.BYTE	_GA,_KI,_do,_mo,_ha,___,_ke,_n_,_ki,_uu,_u_,_si,_tu,_mi,_ta,_i_,_na,_he,_ya,_de,_ret
		.BYTE	_a_,_so,_n_,_de,_i_,_ta,_cr,_ret
		.BYTE	_GA,_KI,_do,_mo,_no,___,_mu,_ko,_u_,_ni,___,_mi,_na,_re,_na,_i_,_GA,_KI,_ga,___,_i_,_ta,_cr,_ret
		.BYTE	_so,_i_,_tu,_ha,___,_wa,_ra,_tt,_te,_i_,_ta,_cr,_eol
_sc16_msgE5:
		.BYTE	_______,_ka__ne__da,_lt,_an0,_ko,_re,_ga,___,_A_,_KI,_RA,_AA,_dot,_dot,_dot,_qe,_aof,_eol
_sc16_msgE6:
		.BYTE	_ki,_oo,_da,_i_,_na,_hi,_ka,_ri,_no,_ta,_ma,_ha,___,_NE,_O_,_to,_u_,_ki,_oo,_u_,_no,_u_,_e_,_ni,_ret
		.BYTE	_si,_uu,_tu,_ge,_n_,_si,_ta,_cr,_ret
		.BYTE	_ya,_ga,_te,___,_hi,_ka,_ri,_no,___,_ti,_oo,_u_,_zi,_oo,_u_,_ga,___,_a_,_n_,_ko,_ku,_ni,_ret
		.BYTE	_na,_tt,_ta,_cr,_ret
		.BYTE	_so,_re,_ha,___,_BU,_RA,_TT,_KU,_HO,_str,_RU,_ni,___,_ni,_te,_i_,_ta,_cr,_eol
_sc16_msgE7:
		.BYTE	_O_,_RE,_no,___,_me,_no,_ma,_e_,_no,___,_ku,_u_,_ka,_n_,_ga,___,_yu,_ga,_mi,_ha,_zi,_me,_te,_i_,_ta,_cr,_ret
		.BYTE	_______,_ka__ne__da,_lt,_an0,_u_,_wa,_str,_tt,___,_KE,$89,$89,_str,_I_,_ex,_aof,_eol
_sc16_msgE8:
		.BYTE	_hi,_ka,_ri,_no,_ta,_ma,_ha,___,_a_,_n_,_ko,_ku,_bu,_bu,_n_,_ni,___,_ka,_n_,_ze,_n_,_ni,_ret
		.BYTE	_nu,_ri,_ka,_e_,_ra,_re,_ta,_cr,_ret
		.BYTE	_so,_no,_ti,_uu,_u_,_si,_n_,_ni,___,_mu,_ka,_tt,_te,___,_ku,_mo,_ga,___,_na,_ga,_re,_te,_i_,_ta,_cr,_eol
_sc16_msgE9:
		.BYTE	_a_,_n_,_ko,_ku,_no,_ki,_uu,_u_,_ga,___,_NE,_O_,_to,_u_,_ki,_oo,_u_,_no,___,_BI,_RU,_gu,_n_,_wo,_ret
		.BYTE	_o_,_o_,_i_,_col,___,_ku,_zu,_si,_te,_i_,_tt,_ta,_cr,_ret
		.BYTE	_NE,_O_,_to,_u_,_ki,_oo,_u_,_no,___,_ti,_uu,_u_,_si,_n_,_ni,___,_ki,_oo,_da,_i_,_na,_ret
		.BYTE	_KU,_RE,_str,_TA,_str,_ga,___,_u_,_ka,_bi,_a_,_ga,_tt,_ta,_cr,_eol
_sc16_msgEA:
		.BYTE	_a_,_n_,_ko,_ku,_no,_ki,_uu,_u_,_ha,___,_NE,_O_,_to,_u_,_ki,_oo,_u_,_wo,___,_o_,_o_,_i_,_tu,_ku,_si,_col,_ret
		.BYTE	_u_,_mi,_ni,_ma,_de,___,_hi,_ro,_ga,_tt,_ta,_cr,_eol
_sc16_msgEB:
		.BYTE	_NE,_O_,_to,_u_,_ki,_oo,_u_,_no,___,_BI,_RU,_ga,_i_,_ni,___,_ka,_i_,_su,_i_,_ga,_ret
		.BYTE	_na,_ga,_re,_ko,_n_,_de,_ki,_ta,_cr,_eol
_sc16_msgEC:
		.BYTE	_BI,_RU,_ha,___,_tu,_gi,_tu,_gi,_to,___,_ta,_o_,_re,_col,___,_ka,_i_,_su,_i_,_ni,_ret
		.BYTE	_no,_mi,_ko,_ma,_re,_te,_i_,_tt,_ta,_cr,_eol
_sc16_msgED:
		.BYTE	_yo,_u_,_ya,_ku,___,_a_,_sa,_ni,_na,_ri,_col,___,_na,_ga,_re,_ru,___,_ku,_mo,_no,_a_,_i_,_da,_ka,_ra,_ret
		.BYTE	_hi,_ka,_ri,_ga,_sa,_si,_ko,_n_,_de,_ki,_ta,_cr,_ret
		.BYTE	_ka,_i_,_su,_i_,_ga,___,_hi,_ki,_ha,_zi,_me,_ta,_cr,_eol
_sc16_msgEE:
		.BYTE	_SU,_TA,_ZI,_A_,_MU,_ka,_ra,___,_mi,_ta,___,_NE,_O_,_to,_u_,_ki,_oo,_u_,_ha,___,_si,_zu,_ke,_sa,_ni,_ret
		.BYTE	_tu,_tu,_ma,_re,_te,_i_,_ta,_dot,_dot,_dot,_eol
_sc16_msgEF:
		.BYTE	___________,_ka,_i_,_lt,_an0,_a_,_str,_tt,___,_ka__ne__da,_AA,_str,_tt,___,_i_,_ki,_te,_ta,_ka,_AA,_str,_cr,_ret
		.BYTE	_______________________,_u_,_str,_tt,___,_O_,_RE,_ha,___,_te,_tt,_ki,_ri,___,_o_,_ma,_e_,_mo,_ret
		.BYTE	_______________________,_a_,_n_,_na,_ka,_de,$89,_str,___,_n_,_qe,___,_te_tsu__o_,_ha,_qe,_ret
		.BYTE	_______________________,_te_tsu__o_,_ha,___,_do,_u_,_si,_ta,___,_si,_n_,_da,_no,_ka,_qe,_aof,_eol

		SECTION_END		F16
