
		SECTION_START	F8

		MSG_START	_scene8_msg_lib
		MSG_IDX	_sc8_msg00
		MSG_IDX	_sc8_msg01
;		MSG_IDX	_sc8_msg02							; -unused-
		MSG_IDX	_sc8_msg03
		MSG_IDX	_sc8_msg04
		MSG_IDX	_sc8_msg05
		MSG_IDX	_sc8_msg06
		MSG_IDX	_sc8_msg07
		MSG_IDX	_sc8_msg08
		MSG_IDX	_sc8_msg0A
		MSG_IDX	_sc8_msg0B
		MSG_IDX	_sc8_msg0C
		MSG_IDX	_sc8_msg0E
		MSG_IDX	_sc8_msg0F
		MSG_IDX	_sc8_msg10
		MSG_IDX	_sc8_msg11
		MSG_IDX	_sc8_msg12
		MSG_IDX	_sc8_msg13
		MSG_IDX	_sc8_msg14
		MSG_IDX	_sc8_msg15
		MSG_IDX	_sc8_msg16
		MSG_IDX	_sc8_msg17
		MSG_IDX	_sc8_msg18
		MSG_IDX	_sc8_msg19
		MSG_IDX	_sc8_msg1A
		MSG_IDX	_sc8_msg1B
		MSG_IDX	_sc8_msg1C
		MSG_IDX	_sc8_msg8A					; scene 8 msg
		MSG_IDX	_sc8_msg8B					; scene 8 msg
_sc8_msg00:
		.BYTE	_______,_ka__ne__da,_lt,_A_,_I_,_TU,_col,___,_do,_ko,_ni,___,_i_,_tt,_ta,_n_,_da,_cr,_eol
_sc8_msg01:
		.BYTE	_su,_i_,_ro,_no,___,_yo,_ko,_no,_mi,_ti,_da,_ze,_cr,_ret
		.BYTE	_su,_i_,_ro,_ha,___,_ko,_no,_sa,_ku,_no,___,_mu,_ko,_u_,_ga,_wa,_ni,___,_na,_ga,_re,_te,_ru,_ze,_cr,_eol
;_sc8_msg02:
;		.BYTE	_______,_ka__ne__da,_lt,_ya,_ba,_i_,_tt,_col,___,_ki,_du,_ka,_re,_te,_si,_ma,_tt,_ta,_ex,_eol
_sc8_msg03:
		.BYTE	_______,_ka__ne__da,_lt,_hi,_to,_no,_ko,_e_,_ga,___,_si,_ta,_yo,_u_,_da,_dot,_dot,_dot,_eol
_sc8_msg04:
		.BYTE	_______,_ka__ne__da,_lt,_su,_i_,_ro,_ka,_ra,_ka,_dot,_dot,_dot,_eol
_sc8_msg05:
		.BYTE	_______,_ka__ne__da,_lt,_a_,_tt,___,_ka,_no,_zi,_oo,_ga,_dot,_dot,_dot,___,_A_,_str,_MI,_str,_ni,_ret
		.BYTE	_______________________,_zi,_uu,_u_,_wo,___,_mu,_ke,_ra,_re,_te,_i_,_ru,_ex,_ret
		.BYTE	_______________________,_na,_n_,_to,_ka,___,_ta,_su,_ke,_da,_si,_te,___,_o_,_ti,_yy,_ni,_ret
		.BYTE	_______________________,_sa,_so,_e_,_na,_i_,_da,_ro,_u_,_ka,_qe,_eol
_sc8_msg06:
		.BYTE	_______,_ka__ne__da,_lt,_a_,_no,_OO,___,_o_,_zi,_sa,_n_,_qe,___,_ya,_tt,_pa,_ri,_ret
		.BYTE	_______________________,_bo,_u_,_ri,_oo,_ku,_ha,___,_i_,_ke,_ma,_se,_n_,_yo,_dot,_dot,_dot,_eol
_sc8_msg07:
		.BYTE	_______,_ka__ne__da,_lt,_TI,_KI,_SI,$6A,_U_,___,_mu,_si,___,_sa,_re,_te,_si,_ma,_tt,_ta,_ex,_eol
_sc8_msg08:
		.BYTE	_______,_ka__ne__da,_lt,_HA,_TT,_HA,_TT,_HA,___,_ho,_n_,_to,_u_,_no,___,_TE,_RO,_RI,_SU,_TO,_ha,_ret
		.BYTE	_______________________,_ko,_no,_o_,_re,_da,_ex,_eol
_sc8_msg0A:
		.BYTE	_O_,_RE,_ha,___,_bo,_u_,_ze,_n_,_to,___,_si,_te,_i_,_ru,___,_ka,_no,_zi,_oo,_no,_ka,_ta,_wo,_ret
		.BYTE	_ta,_ta,_i_,_ta,_cr,_eol
_sc8_msg0B:
		.BYTE	_______,_ka__ne__da,_lt,_O_,_RE,_ha,___,_o_,_to,_ga,___,_si,_na,_i_,_yo,_u_,_ni,___,_SO,_str,_TT,_to,_ret
		.BYTE	_______________________,_sa,_ku,_no,_ka,_ge,_ni,___,_si,_yy,_ga,_mi,_ko,_n_,_da,_cr,_eol
_sc8_msg0C:
		.BYTE	_ha,_i_,_go,_ni,_i_,_ta,___,_ho,_ka,_no,_A_,_str,_MI,_str,_ni,___,_O_,_RE,_ha,___,_zi,_uu,_u_,_wo,_ret
		.BYTE	_tu,_ki,_tu,_ke,_ra,_re,_ta,_cr,_eol
_sc8_msg0E:
		.BYTE	_______,_ka__ne__da,_lt,_yo,_si,_tt,___,_so,_tt,_to,___,_ti,_ka,_du,_i_,_te,___,_A_,_str,_MI,_str,_no,_ret
		.BYTE	_______________________,_o_,_tt,_sa,_n_,_wo,___,_ya,_tt,_tu,_ke,_yo,_u_,_cr,_ret
		.BYTE	_O_,_RE,_ha,___,_sa,_ku,_wo,___,_no,_ri,_ko,_e_,_yo,_u_,_to,_si,_te,_dot,_dot,_dot,_eol
_sc8_msg0F:
		.BYTE	_GO,_OO,_O_,_str,_N_,_ex,_ret
		.BYTE	_te,_tu,_se,_i_,_no,___,_sa,_ku,_wo,___,_ke,_tt,_te,_si,_ma,_tt,_ta,_cr,_eol
_sc8_msg10:
		.BYTE	_A_,_str,_MI,_str,_ga,___,_hu,_ri,_mu,_i_,_ta,_cr,_ret
		.BYTE	_______,_ka__ne__da,_lt,_ya,_ba,_i_,_tt,___,_ki,_du,_ka,_re,_te,_si,_ma,_tt,_ta,_ex,_ex,_eol
_sc8_msg11:
		.BYTE	_______,_ka__ne__da,_lt,_KI,_MI,_ha,___,_ka,_n_,_ze,_n_,_ni,___,_ho,_u_,_i_,_sa,_re,_ta,_cr,_ret
		.BYTE	_______________________,_o_,_to,_na,_si,_ku,___,_zi,_uu,_u_,_wo,___,_su,_te,_col,___,_ka,_no,_zi,_oo,_wo,_ret
		.BYTE	_______________________,_ni,_ga,_si,_na,_sa,_i_,_cr,_eol
_sc8_msg12:
		.BYTE	_______,_ka__ne__da,_lt,_ya,_col,___,_ya,_da,_na,_a_,_cr,___,_BO,_KU,_ha,___,_ta,_da,_dot,_dot,_dot,_eol
_sc8_msg13:
		.BYTE	_______,_ka__ne__da,_lt,_ka,_col,___,_ka,_mi,_sa,_ma,_qe,_ex,_eol
_sc8_msg14:
		.BYTE	_O_,_RE,_ha,___,_A_,_str,_MI,_str,_ni,___,_to,_bi,_ka,_ka,_tt,_ta,_cr,_ret
		.BYTE	_dot,_dot,_dot,_si,_ka,_si,___,_si,_tt,_so,_ku,_si,_te,___,_A_,_str,_MI,_str,_no,_ma,_e_,_de,_ret
		.BYTE	_KO,_KE,_te,_si,_ma,_tt,_ta,_cr,_eol
_sc8_msg15:
		.BYTE	_______,_ka__ne__da,_lt,_E_,_str,_I_,_col,___,_ya,_ke,_ku,_so,_da,_tt,_ex,_ret
		.BYTE	_O_,_RE,_ha,___,_A_,_str,_MI,_str,_ni,___,_mu,_ka,_tt,_te,___,_DA,_TT,_SI,_UU,_si,_ta,_cr,_eol
_sc8_msg16:
		.BYTE	_ZU,_ZA,_str,_TT,_cr,_ret
		.BYTE	_O_,_RE,_ha,___,_A_,_str,_MI,_str,_no,___,_a_,_si,_mo,_to,_de,___,_to,_ma,_tt,_ta,_cr,_eol
_sc8_msg17:
		.BYTE	_O_,_RE,_ha,___,_BA,_KU,_te,_n_,_de,___,_ta,_ma,_wo,___,_yo,_ke,_yo,_u_,_to,_si,_te,_dot,_dot,_dot,_ret
		.BYTE	_a_,_si,_wo,___,_su,_be,_ra,_se,_te,_col,___,_KO,_KE,_te,_si,_ma,_tt,_ta,_cr,_eol
_sc8_msg18:
		.BYTE	_______,_ka__ne__da,_lt,_u_,_str,___,_a_,_a_,_a_,_tt,___,_a_,_str,_tt,_cr,_ret
		.BYTE	_O_,_RE,_ha,___,_A_,_str,_MI,_str,_ni,___,_to,_bi,_tu,_i_,_ta,_cr,_eol
_sc8_msg19:
		.BYTE	_O_,_RE,_ha,___,_A_,_str,_MI,_str,_to,_i_,_tt,_si,_oo,_ni,___,_do,_bu,_ni,___,_o_,_ti,_ta,_cr,_ret
		.BYTE	_DO,_RO,_SI,_BU,_KI,_ka,_ra,___,_ka,_o_,_wo,___,_a_,_ge,_ta,_to,_ki,_col,___,_mo,_u_,_hi,_to,_ri,_no,_ret
		.BYTE	_A_,_str,_MI,_str,_ga,___,_mi,_e_,_ta,_cr,_ret
		.BYTE	_A_,_str,_MI,_str,_ha,___,_O_,_RE,_ni,_mu,_ka,_tt,_te,___,_zi,_uu,_u_,_wo,___,_ka,_ma,_e_,_ta,_ex,_eol
_sc8_msg1A:
		.BYTE	_o_,_n_,_na,_no,_ko,_lt,_an0,_ya,_me,_te,$89,_ex,_aof,_eol
_sc8_msg1B:
		.BYTE	_si,_ka,_si,___,_ma,_ta,_be,_tu,_no,___,_A_,_str,_MI,_str,_no,_ke,_ha,_i_,_ga,___,_si,_te,_i_,_ta,_cr,_ret
		.BYTE	_______,_ka__ne__da,_lt,_an0,_i_,_ko,_u_,_ze,_cr,_aof,_eol
_sc8_msg1C:
		.BYTE	_______,_ka__ne__da,_lt,_ka,_no,_zi,_oo,_OO,_ex,___,_so,_n_,_na,_o_,_tt,_sa,_n_,_to,_ret
		.BYTE	_______________________,_ni,_ra,_me,_tt,_ko,_na,_n_,_ka,___,_si,_te,_na,_i_,_de,$89,_ret
		.BYTE	_______________________,_o_,_re,_to,___,_o_,_ti,_yy,___,_no,_mi,_ni,___,_i_,_ka,_na,_AA,_str,_i_,_cr,_eol
_sc8_msg8A:
		.BYTE	___,_A_,_str,_MI,_str,_lt,_yo,_str,_si,_col,___,_so,_ko,_ma,_de,_da,_ex,_eol
_sc8_msg8B:
		.BYTE	_A_,_str,_MI,_str,_ga,___,_te,_ni,_si,_ta,___,_zi,_uu,_u_,_wo,___,_ha,_tt,_po,_u_,_si,_ta,_ex,_ex,_eol

		SECTION_END		F8
