
		SECTION_START	F0

		MSG_START	_scene0_msg_lib
		MSG_IDX _sc0_msgB8
		MSG_IDX	_sc0_msg01
		MSG_IDX	_sc0_msg02
		MSG_IDX	_sc0_msg03
		MSG_IDX	_sc0_msg04
		MSG_IDX	_sc0_msg05
		MSG_IDX	_sc0_msg06
		MSG_IDX	_sc0_msg07
		MSG_IDX	_sc0_msg08
		MSG_IDX	_sc0_msg09
		MSG_IDX	_sc0_msg19
		MSG_IDX	_sc0_msg26
		MSG_IDX	_sc0_msg2E
		MSG_IDX	_sc0_msg2F
		MSG_IDX	_sc0_msg30
_sc0_msgB8:
		.BYTE	_so,_no,_yo,_ru,___,_O_,_RE,_ta,_ti,_ha,___,_KU,_RA,_U_,_N_,_no,_re,_n_,_ti,_uu,_u_,_wo,___,_o_,_tt,_te,_col,_ret
		.BYTE	_ki,_uu,_u_,_si,_ga,_i_,_no,_ko,_u_,_so,_ku,_do,_u_,_ro,_wo,___,_ha,_si,_tt,_te,_i_,_ta,_cr,_eol
_sc0_msg01:
		.BYTE	_te_tsu__o_,_no,_BA,_I_,_KU,_ga,___,_i_,_tt,_si,_uu,_n_,_no,_u_,_ti,_ni,_col,_ret
		.BYTE	_ho,_no,_o_,_ni,___,_tu,_tu,_ma,_re,_te,_si,_ma,_tt,_ta,_n_,_da,_cr,_eol
_sc0_msg02:
		.BYTE	_O_,_RE,_ga,___,_ka,_ke,_tu,_ke,_te,___,_te_tsu__o_,_wo,_da,_ki,_o_,_ko,_si,_ta,_cr,_ret
		.BYTE	_______,_ka__ne__da,_lt,_si,_tt,_ka,_ri,_si,_ro,___,_te_tsu__o_,_ex,_ret
		.BYTE	_______,_te_tsu__o_,_lt,_A_,_I_,_TU,_ni,_dot,_dot,_dot,___,_A_,_I_,_TU,_ni,___,_ya,_ra,_re,_ta,_dot,_dot,_dot,_ret
		.BYTE	_te_tsu__o_,_no,_yu,_bi,_sa,_su,_ho,_u_,_ni,_ha,___,_SI,_WA,_da,_ra,_ke,_no,___,_GA,_KI,_da,_ka,_ret
		.BYTE	_ZI,_ZI,_I_,_da,_ka,___,_wa,_ka,_ra,_na,_i_,_no,_ga,___,_ta,_tt,_te,_i_,_ta,_cr,_eol
_sc0_msg03:
		.BYTE	_______,_ka__ne__da,_lt,_YA,_RO,_str,_TT,_ex,___,_te_tsu__o_,_ni,___,_na,_ni,_wo,_si,_ta,_n_,_da,_ex,_ret
		.BYTE	_HE,_RI,_no,_o_,_to,_ga,___,_O_,_RE,_no,_ko,_e_,_wo,_ke,_si,_ta,_cr,_ret
		.BYTE	_A_,_str,_MI,_str,_no,_he,_ri,_da,_tt,_ta,_cr,_ret
		.BYTE	_GA,_KI,_ha,___,_so,_tt,_ti,_wo,_mi,_te,___,_o_,_bi,_e_,_da,_si,_ta,_cr,_eol
_sc0_msg04:
		.BYTE	_HE,_RI,_ha,___,_O_,_RE,_ta,_ti,_no,_su,_gu,_so,_ba,_he,___,_o_,_ri,_te,_ki,_ta,_cr,_ret
		.BYTE	_HE,_RI,_no,_DO,_A_,_ga,_a_,_ku,_to,_col,___,_so,_ko,_ni,_ha,___,_hi,_to,_ri,_no,_o_,_to,_ko,_ga,_ret
		.BYTE	_ta,_tt,_te,_i_,_ta,_cr,_eol
_sc0_msg05:
		.BYTE	_so,_no,_o_,_to,_ko,_wo,_mi,_ru,_to,___,_TA,_KA,_SI,_to,_ka,_i_,_u_,_SI,_WA,_no,_GA,_KI,_ha,_ret
		.BYTE	_ma,_e_,_yo,_ri,___,_ko,_wa,_ba,_tt,_ta,_ka,_o_,_ni,_na,_tt,_ta,_cr,_eol
_sc0_msg06:
		.BYTE	___,_A_,_str,_MI,_str,_lt,_ri,_oo,_u_,_te,_wo,___,_a_,_ta,_ma,_no,_u_,_si,_ro,_ni,_ma,_wa,_si,_te,_ret
		.BYTE	_______________________,_ri,_oo,_u_,_hi,_za,_wo,___,_zi,_me,_n_,_ni,_tu,_ke,_ru,_n_,_da,_ex,_eol
_sc0_msg07:
		.BYTE	_______,_ka__ne__da,_lt,_ti,_oo,_tt,_col,_ti,_oo,_tt,_to,_ma,_tt,_te,_yo,___,_O_,_ZI,_sa,_n_,_ex,_ret
		.BYTE	_______________________,_O_,_RE,_ta,_ti,___,_na,_n_,_ni,_mo,_si,_te,_ne,_str,_yo,_u_,_cr,_eol
_sc0_msg08:
		.BYTE	_______,_ka__ne__da,_lt,_na,_ka,_ma,_ga,___,_KE,_GA,_si,_te,_ru,_n_,_SU,_yo,_str,_cr,_ret
		.BYTE	___,_A_,_str,_MI,_str,_lt,_ta,_i_,_sa,_ex,___,_KE,_GA,_ni,_n_,_ga,___,_i_,_ti,_me,_i_,___,_i_,_ma,_su,_ex,_ret
		.BYTE	_______,_o_,_to,_ko,_lt,_an0,_so,_i_,_tu,_ha,___,_RA,_BO,_he,_tu,_re,_te,_yu,_ku,_cr,___,_i_,_ku,_zo,_ex,_ex,_aof,_eol
_sc0_msg09:
		.BYTE	_______,_ka__ne__da,_lt,_an1,_TE,_ME,_str,$89,___,_ko,_no,_TA,_KO,_ex,_ret
		.BYTE	_______________________,_O_,_RE,_ta,_ti,_wo,___,_do,_str,_su,_n_,_da,_yo,_str,_tt,_ex,_aof,_eol
_sc0_msg19:
		.BYTE	_______,_o_,_to,_ko,_lt,_an0,_TA,_KA,_SI,_col,___,_mu,_ka,_e_,_ni,_ki,_ta,_zo,_cr,_ret
		.BYTE	_______________________,_sa,_a_,___,_wa,_ta,_si,_to,_i_,_tt,_si,_oo,_ni,___,_ka,_e_,_ro,_u_,_cr,_ret
		.BYTE	_______________________,_o_,_ma,_e_,_ta,_ti,_ha,___,_so,_to,_no,_se,_ka,_i_,_de,_ha,_ret
		.BYTE	_______________________,_i_,_ki,_te,_yu,_ke,_n_,_no,_da,_ex,_aof,_eol
_sc0_msg26:
		.BYTE	_so,_n_,_to,_ki,_ni,_ka,_gi,_tt,_te,___,_A_,_TA,_MA,_wo,___,_ha,_si,_tt,_te,_i_,_ta,_no,_ha,_ret
		.BYTE	_te_tsu__o_,_da,_tt,_ta,_cr,_ret
		.BYTE	_ri,_oo,_u_,_ki,_n_,_si,_oo,_a_,_to,_wo,___,_su,_gi,_ta,_a_,_ta,_ri,_de,_ret
		.BYTE	_so,_i_,_tu,_ha,___,_o_,_ko,_tt,_ta,_dot,_dot,_dot,_eol
_sc0_msg2E:
		.BYTE	_______,_o_,_to,_ko,_lt,_an0,_ho,_ka,_no,_re,_n_,_ti,_uu,_u_,_ha,___,_ze,_i_,_i_,_n_,_TA,_I_,_HO,_si,_ro,_ex,_aof,_ret
		.BYTE	_A_,_str,_MI,_str,_ga,___,_de,_te,_ki,_te,_col,___,_O_,_RE,_ta,_ti,_wo,___,_to,_ri,_ka,_ko,_n_,_da,_cr,_eol
_sc0_msg2F:
		.BYTE	_GA,_KI,_to,_te_tsu__o_,_wo,___,_no,_se,_ta,_HE,_RI,_ha,___,_yu,_tt,_ku,_ri,_to,_ret
		.BYTE	_to,_bi,_ta,_tt,_ta,_cr,_eol
_sc0_msg30:
		.BYTE	_do,_u_,_ya,_ra,___,_O_,_RE,_ta,_ti,_ha,___,_ha,_n_,_se,_i_,_hu,_bu,_n_,_si,_da,_to,_ret
		.BYTE	_o_,_mo,_wa,_re,_te,_ru,_yo,_u_,_da,_ze,_cr,_eol

		SECTION_END		F0
